service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
=> EVAKA-4240: fix child duplication bug

service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaDevController.kt
=> Point varda update job to new varda update service

service/src/integrationTest/resources/application-integration-test.yaml, service/src/main/kotlin/fi/espoo/evaka/shared/config/AsyncJobConfig.kt
=> Fix async job runner disable flag

frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx, frontend/src/e2e-playwright/pages/citizen/citizen-income.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-income-statement.spec.ts
=> Add e2e test for income statement based on gross income

frontend/src/e2e-playwright/pages/employee/child-information.ts, frontend/src/e2e-playwright/specs/5_employee/child-information.spec.ts, frontend/src/e2e-test-common/dev-api/data-init.ts, frontend/src/e2e-test-common/dev-api/fixtures.ts, frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx
- Fix input widths on edit mode
- Add an E2E test for editing at least one attribute
=> Child profile editor improvements

frontend/src/employee-frontend/components/fee-decisions/Actions.tsx, frontend/src/employee-frontend/components/invoices/Actions.tsx, frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionActions.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
* Fix regression where finance decision/invoice send errors were ignored.
* Show a better error message when fee decision send fails because of existing decisions waiting for manual sending.
=> EVAKA-HOTFIX fee decision send conflict feedback

service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiPayloadIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt, service/src/main/resources/db/migration/R__koski_views.sql
=> Fix off-by-one resigned state in Koski integration

frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx, frontend/src/citizen-frontend/income-statements/types/common.ts, frontend/src/e2e-playwright/pages/citizen/citizen-calendar.ts, frontend/src/e2e-playwright/pages/citizen/citizen-income.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-income-statement.spec.ts, frontend/src/lib-components/atoms/form/Checkbox.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
=> EVAKA-4213 Entrepreneur income e2e tests

service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- Combine failed varda update service needs to other to-be-updated service needs for simpler code
- Simplify error handling to avoid messing up the error logging
- Delete those service needs from varda which have been changed in evaka so that those should be deleted from varda
=> Improve varda sync

frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Add very elementary translations to citizen calendar page.
=> EVAKA-4240 citizen calendar elementary translations

service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt, service/src/main/resources/WEB-INF/templates/ipost/ipost-letter2.html, service/src/main/resources/WEB-INF/templates/preparatory/decision.html, service/src/main/resources/WEB-INF/templates/preschool/decision.html, service/src/main/resources/WEB-INF/templates/shared/acceptance-form.html, service/src/main/resources/WEB-INF/templates/shared/common.html
Use unit name as fallback on daycare and preschool decisions when the unit doesn't have a "name on decision" set.
=> Use unit name as fallback on decision PDFs

frontend/src/e2e-playwright/pages/employee/finance/finance-page.ts, frontend/src/e2e-playwright/pages/employee/person-profile.ts, frontend/src/e2e-playwright/specs/4_finance/income-staments.spec.ts, frontend/src/e2e-test-common/dev-api/index.ts, frontend/src/e2e-test-common/dev-api/types.ts, frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx, frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
=> EVAKA-4231 simple employee's income statement page e2e test

frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
=> Link to fee thresholds

service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
=> EVAKA-4000 avoid blank guardian oids

service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt, service/src/test/kotlin/fi/espoo/evaka/varda/VardaUnitModelTest.kt
Clean up the implementation a bit. Also, avoid unit getting sent to Varda every day if it's closing date is set to the future.
=> EVAKA-4000 update varda units

service/src/main/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pis/service/FamilyOverviewService.kt
Since the family overview didn't use the new `IncomeTypesProvider` the multipliers were mapped to 0.
=> EVAKA-HOTFIX fix family overview income values

service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/MockDvvModificationsService.kt, service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
=> Handle unknown DVV VTJ mutp modifications

frontend/src/employee-frontend/api/income-statement.ts, frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx, frontend/src/lib-common/api-types/incomeStatement.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
Show start date, created date and primary care area in income statement listing.
The `LEFT JOIN` of `primary_units_view` always yields 0..1 results.
=> EVAKA-4213 Improve income statement listing

frontend/src/lib-common/finite-date-range.spec.ts, frontend/src/lib-common/finite-date-range.ts
=> Simplify FiniteRange.includes() and add some unit tests

service/src/integrationTest/kotlin/fi/espoo/evaka/shared/auth/AclIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/resources/db/migration/R__acl_views.sql
=> Implement person_acl_view and fix person search for scoped roles

service/src/main/kotlin/fi/espoo/evaka/varda/VardaOrganizerChild.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt, service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt, service/src/test/kotlin/fi/espoo/evaka/varda/VardaUnitModelTest.kt
- move converters under data classes for discoverability
- remove some dead code
- remove excess debug log from error message parser
=> EVAKA-4000 minor refactoring

service/src/main/resources/WEB-INF/templates/preparatory/decision.properties, service/src/main/resources/WEB-INF/templates/preparatory/decision_sv.properties
The Jira ticket has the details.
=> EVAKA-4273 update preparatory decision texts

service/src/main/kotlin/fi/espoo/evaka/vtjclient/service/vtjclient/VtjClientService.kt, service/src/test/kotlin/fi/espoo/evaka/vtjclient/service/VtjClientServiceTest.kt
=> Do not log whole ssn on VTJ requests

frontend/src/e2e-playwright/pages/employee/mobile/pairing-flow.ts, frontend/src/e2e-playwright/specs/6_mobile/pairing.spec.ts
Encapsulate locators within page object in pairing flow, expose interactions
=> Refactor pairing flow e2e tests

service/src/main/kotlin/fi/espoo/evaka/varda/VardaOrganizer.kt
=> Do not try to update varda organizer info if it is not changed

frontend/src/employee-frontend/components/unit/unit-details/CreateUnitPage.tsx
When an unit is created the user is redirected to an invalid enpoint. This should fix the issue.
=> EVAKA: Fix create unit redirect url

service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaDevController.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
Add first version of utilizing async jobs
=> EVAKA-4000 schedule update using async jobs

frontend/src/citizen-frontend/localization/state.tsx, frontend/src/lib-common/utils/useLocalStorage.ts
=> Store citizen ui lang in local storage

service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt, service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
Add forgotten insert part 🤦‍♂️
=> EVAKA-4000 fix sql - add lost insert clause

frontend/src/e2e-playwright/specs/7_messaging/messaging.spec.ts, frontend/src/employee-frontend/components/messages/MessageEditor.tsx, frontend/src/employee-frontend/components/messages/MessagesPage.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/DraftQueriesTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageReceiversIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/message/DraftContent.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/message/DraftQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/message/Message.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccountQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageController.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageNotificationEmailService.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- Add type aliases for messaging tables
- Add error handling and double-click prevention to message editor
- Make messaging e2e tests faster by opening the right amount of browser instances for each test
=> Messaging improvements

service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
=> EVAKA increase async job runner threadpool

frontend/src/e2e-playwright/pages/employee/finance/finance-page.ts, frontend/src/e2e-playwright/specs/4_finance/value-decisions.spec.ts, frontend/src/employee-frontend/components/fee-decisions/FeeDecisionsPage.tsx, frontend/src/employee-frontend/components/voucher-value-decision/VoucherValueDecisionActionBar.tsx, frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionsPage.tsx, frontend/src/employee-frontend/state/invoicing-ui.tsx, frontend/src/employee-frontend/state/invoicing.ts
=> Allow sending value decision from details page

service/src/main/kotlin/fi/espoo/evaka/varda/VardaDevController.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt, service/src/main/kotlin/fi/espoo/evaka/varda/integration/MockVardaIntegrationEndpoint.kt, service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- fix regex & test data
- add param to control if reset should add new children or not
=> EVAKA-4000 fix error parsing

apigw/src/enduser/app.ts, apigw/src/internal/app.ts
Checks Redis connection and sends ping in health check.
=> Check redis connection in API-gateway health check

frontend/src/employee-mobile-frontend/components/attendances/child-info/ImageEditor.tsx
=> EVAKA-4291: bigger image crop handles

frontend/src/citizen-frontend/applications/editor/contact-info/GuardianSubSection.tsx
Remove the asterisk as requested by the UX
=> Remove asterisk as instructed in the UX spec

docs/README.md, docs/vasu-json-examples/vasu_content__authors_content.json, docs/vasu-json-examples/vasu_content__content.json, docs/vasu-json-examples/vasu_content__evaluation_discussion_content.json, docs/vasu-json-examples/vasu_content__vasu_discussion_content.json, docs/vasu-json-examples/vasu_document__basics.json
=> EVAKA-DOCS: document vasu schema

.circleci/config.yml
- Copy frontend files always into s3 bucket so those can be installed separetely
=> Copy files to S3 before deploy

frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx, frontend/src/employee-frontend/components/messages/types.ts
Sent messages are currently deserialized  incorrectly. Fix that.
=> Fix sent message deserialization

service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
=> Adjust varda retry counts

frontend/src/employee-frontend/components/messages/MessageEditor.tsx, frontend/src/lib-components/molecules/FileUpload.tsx
Implement slim alternative without drag and drop feature for FileUpload component.
=> EVAKA-4214 Slim file upload component

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/attachment/Attachment.kt, service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentQueries.kt, service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/message/DraftQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccountAccessQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccountQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/resources/db/migration/R__message_account_access_view.sql
Implement attachment and draft access queries with message account access view
=> EVAKA-4214 Message attachment access control

service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
=> EVAKA-4000-init-varda-client-once

frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
=> EVAKA-HOTFIX: fix link on child current group

frontend/src/employee-frontend/components/messages/SingleThreadView.tsx, frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx, frontend/src/lib-common/generated/api-types/messaging.d.ts, service/src/main/kotlin/fi/espoo/evaka/messaging/message/Message.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageQueries.kt
=> EVAKA-4214 Show messages in employee's message views

frontend/src/citizen-frontend/messages/ThreadList.tsx, frontend/src/citizen-frontend/messages/ThreadListItem.tsx
=> EVAKA-4214 Show attachments in citizen thread list

service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/DatabaseConfig.kt, service/src/main/resources/application-local.yaml
This is not enabled by default, and is mostly meant for local use when debugging some SQL.
Only affects the actual application, so tests / integration tests won't log SQL.
=> Add support for logging executed SQL

frontend/src/citizen-frontend/header/DesktopNav.tsx, frontend/src/e2e-playwright/pages/citizen/citizen-header.ts, frontend/src/e2e-playwright/utils/user.ts
Create citizen user dropdown menu (see the attached picture). Also update styling in the language dropdown.
=> Citizen income to a dropdown menu

service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
=> EVAKA-4295: vasu info texts

service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
=> Work around reflection errors by using public classes

service/src/main/kotlin/fi/espoo/evaka/s3/ContentTypeUtils.kt
=> EVAKA-HOTFIX: improve content type check

service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccountAccessQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
=> Fix attachment permissions for WeakCitizen

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FinanceDecisions.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
Fix a bug with voucher value decisions sending in cases where a child's head of family changes.
=> EVAKA-HOTFIX value decisions with changing head of family

frontend/src/employee-frontend/components/absences/Absences.tsx
=> EVAKA-UX: add absence type legend

service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/StaffAttendanceService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiQueries.kt, service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt, service/src/main/kotlin/fi/espoo/evaka/reports/DecisionsReport.kt, service/src/main/kotlin/fi/espoo/evaka/reports/StartingPlacementsReport.kt, service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt, service/src/main/resources/db/migration/R__koski_views.sql, service/src/main/resources/db/migration/V144__database_tweaks_transactional.sql, service/src/main/resources/db/migration/V145__database_tweaks_nontransactional.sql, service/src/main/resources/migrations.txt
=> Improve database indexing and index use with date columns

frontend/src/e2e-playwright/pages/mobile/child-page.ts, frontend/src/e2e-playwright/pages/mobile/note-page.ts, frontend/src/e2e-playwright/specs/6_mobile/notes.spec.ts, frontend/src/e2e-test/pages/employee/mobile/mobile-groups.ts, frontend/src/e2e-test/specs/6_mobile/backup-care-dailynotes.spec.ts, frontend/src/e2e-test/specs/6_mobile/dailynotes.spec.ts, frontend/src/employee-mobile-frontend/assets/i18n/fi.ts, frontend/src/employee-mobile-frontend/components/attendances/child-info/ChildButtons.tsx, frontend/src/employee-mobile-frontend/components/attendances/notes/DailyNoteEditor.tsx, frontend/src/lib-components/atoms/RoundIcon.tsx
- https://www.figma.com/file/8FXipaHxJcHwwfCl273PWS/Kasvattajan-mobiili?node-id=0%3A1
=> Refactor mobile daycare note UI

frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Filled in the translations received from the translation office. Some texts were modified and added after the translation. These are marked with TODOs.
=> EVAKA-4213 income statement i18n

frontend/src/citizen-frontend/App.tsx, frontend/src/citizen-frontend/applications/ApplicationCreation.tsx, frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx, frontend/src/citizen-frontend/applying/Applying.tsx, frontend/src/citizen-frontend/header/DesktopNav.tsx, frontend/src/citizen-frontend/header/MobileNav.tsx, frontend/src/citizen-frontend/map/MapView.tsx, frontend/src/e2e-playwright/pages/citizen/citizen-header.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-header.spec.ts, frontend/src/lib-components/molecules/Tabs.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Group some navbar tabs under a single `Applying`-tab with a sub-navbar.
=> Evaka create citizen subnavigation

frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx, frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx, frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
- Fix income statement view on small resolutions by consistently showing values below labels
- Fix income statement editor action buttons on small resolutions by putting the checkbox on its own row
=> EVAKA-4213 income statement responsiveness

service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
=> Refactor IncomeStatement data class

frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
=> Grammar fixes for income statement translations

frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx, frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx, frontend/src/lib-components/atoms/buttons/AddButton.tsx, frontend/src/lib-components/atoms/buttons/InlineButton.tsx, frontend/src/lib-components/atoms/buttons/ResponsiveAddButton.tsx, frontend/src/lib-components/atoms/buttons/ResponsiveInlineButton.tsx
=> Add responsive inline and add buttons

service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
Update `last_login` on a successful employee pin check.
=> Update last_login on employee pin check

frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> Fix a typo

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> Enable message attachments in production

evaka-bom/build.gradle.kts
https://nvd.nist.gov/vuln/detail/CVE-2021-40690
=> Upgrade Apache xmlsec

frontend/src/citizen-frontend/App.tsx
This avoids an extra full page load, and some E2E flakiness caused by it
=> Use SPA redirect in citizen /

service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
=> Fix typo in vasu static section

frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx, frontend/src/employee-frontend/components/person-profile/income/missingIncomePeriodUtils.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
Small fixes to income statements.
=> Income statement fixes

frontend/src/citizen-frontend/header/DesktopNav.tsx
=> EVAKA-HOTFIX: Don't reload page to navigate to income statements

frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx
=> Hide employee ACL dropdowns until data has loaded

frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt, service/src/main/resources/WEB-INF/templates/daycare/voucher/decision.properties, service/src/main/resources/WEB-INF/templates/shared/common.properties
=> [EVAKA-4296] Update e-mail address

frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx, frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx, frontend/src/citizen-frontend/applications/editor/verification/ServiceNeedPartTime.tsx, frontend/src/employee-frontend/components/ApplicationPage.tsx, frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx, frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx, frontend/src/employee-frontend/components/applications/ApplicationsList.tsx, frontend/src/employee-frontend/components/unit/TabApplications.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/FeatureFlags.kt
When featureFlags.daycareApplication.serviceNeedOptionsEnabled is true, set default value to first full time service need option
=> Set default service need option on application when options are displayed

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGeneratorIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/People.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/messaging/FeeDecisionGenerationJobProcessor.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerator.kt
Fix a bug that caused finance decisions to get wrong family compositions.
=> EVAKA-HOTFIX wrong family compositions on finance decisions

frontend/src/employee-mobile-frontend/components/attendances/child-info/ImageEditor.tsx
There's no need to use quality 100 images
=> Set default JPEG quality to 70

service-lib/src/main/resources/fi/espoo/voltti/logging/logback/access-appender.xml, service-lib/src/main/resources/fi/espoo/voltti/logging/logback/audit-appender.xml, service-lib/src/main/resources/fi/espoo/voltti/logging/logback/default-appender-sanitized.xml, service-lib/src/main/resources/fi/espoo/voltti/logging/logback/default-appender.xml, service-lib/src/main/resources/fi/espoo/voltti/logging/logback/vtj-appender.xml
=> Enable logger name

frontend/package.json
=> Retry E2E tests

frontend/src/e2e-playwright/specs/6_mobile/child-attendances.spec.ts
=> Fix flaky test

service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/varda/Varda.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaResetService.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
=> Add debug logging to find out where varda service need creation fails

.circleci/config.yml
=> Use node.js 16 in circleci too

.circleci/config.yml
=> Remove unused e2e caching code

frontend/src/e2e-playwright/pages/mobile/child-page.ts, frontend/src/employee-mobile-frontend/components/attendances/child-info/PinLogin.tsx, frontend/src/lib-components/molecules/PinInput.tsx
Fixes problem with low resolution devices where submit arrow does not fit in the screen.
Long term solution will be implemented in the new pin login flow.
=> Use plain pin code input in child sensitive info component

frontend/src/citizen-frontend/messages/MessageComponents.tsx, frontend/src/citizen-frontend/messages/ThreadView.tsx, frontend/src/employee-frontend/components/messages/SingleThreadView.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Scroll to the bottom upon opening a message thread so that the newest message is displayed right away.
=> Scroll to message thread bottom

service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
=> EVAKA-FIX Allow tika filetypes

frontend/src/employee-frontend/components/Header.tsx, frontend/src/employee-frontend/components/SettingsPage.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts
The admin settings page should be hidden in Espoo, so add a feature flag for that.
While at it, add some related React perf optimizations.
=> Admin settings feature flag

frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
=> Improved message recipient stylings

service/src/main/kotlin/fi/espoo/evaka/messaging/MessageAccountQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt, service/src/main/resources/db/migration/R__message_account_access_view.sql
=> EVAKA 4310: Messaging for special education teachers

service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
=> Enable Tomcat JMX in EspooConfig

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
This reverts commit 8424620145f96fec56e6f51184eb8629013ed891, reversing
changes made to 764e1b2ddebce668976770ed433402faa16dc2a2.
=> EVAKA-HOTFIX revert attendance fix

frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Add translations for header item
- Growth and learning
- Tillväxt och inlärning
=> EVAKA-HOTFIX add missing translations

frontend/src/employee-mobile-frontend/components/auth/PinLogin.tsx
The actual fix is adding `getItemValue`. Rest of the changes are just type improvements.
=> HOTFIX: employee selection in PIN login form

docs/README.md
Open term vasu a bit more.
﻿#### Summary
=> Add vasu explanation in Finnish

frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposalRow.tsx, frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposals.tsx, frontend/src/employee-frontend/types/unit.ts, frontend/src/lib-common/generated/api-types/placement.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlan.kt, service/src/main/resources/db/migration/V173__create_rejected_not_confirmed_state_for_placement_plans.sql, service/src/main/resources/migrations.txt
=> Placement plan UX fix

frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Fix links on income statement page to use correct language version and point to the main page.
=> Fix links on income statement page

service/src/main/resources/WEB-INF/templates/club/decision.properties, service/src/main/resources/WEB-INF/templates/daycare/transfer/decision.properties, service/src/main/resources/WEB-INF/templates/daycare/transfer/decision_sv.properties, service/src/main/resources/WEB-INF/templates/daycare/voucher/decision.properties, service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.html, service/src/main/resources/WEB-INF/templates/preparatory/decision.html, service/src/main/resources/WEB-INF/templates/preparatory/decision.properties, service/src/main/resources/WEB-INF/templates/preparatory/decision_sv.properties, service/src/main/resources/WEB-INF/templates/preschool/decision.html, service/src/main/resources/WEB-INF/templates/preschool/decision.properties, service/src/main/resources/WEB-INF/templates/preschool/decision_sv.properties, service/src/main/resources/WEB-INF/templates/shared/common.html, service/src/main/resources/WEB-INF/templates/shared/common.properties, service/src/main/resources/WEB-INF/templates/shared/common_sv.properties
=> Fix security problems with th:utext usage

service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt, service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt, service/src/main/resources/application-local.yaml, service/src/test/kotlin/fi/espoo/evaka/varda/integration/VardaClientTest.kt
=> Remove unused config

frontend/src/citizen-frontend/calendar/CalendarGridView.tsx, service/src/main/resources/dev-data/espoo-dev-data.sql
Add minimal care areas (2), units (2), groups (2), unit managers (2) for dev purposes
=> Add minimal generic dev data

frontend/src/e2e-test/specs/5_employee/unit-acl.spec.ts
=> Remove a debug call from an e2e test

frontend/src/employee-frontend/components/vasu/VasuEditPage.tsx, frontend/src/employee-frontend/components/vasu/VasuStateTransitionButtons.tsx, frontend/src/employee-frontend/components/vasu/components/LeaveVasuPageButton.tsx, frontend/src/lib-components/layout/FullWidthDiv.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
This is in order to improve the UX of this flow. The action is the same
as pressing the back button in the browser.
=> Add a 'leave page' button to the vasu editor and preview pages

frontend/src/citizen-frontend/map/SearchInput.tsx
Functionally they should be identical and visually they are pretty much the same (and closer to other comboboxes).
=> Replace react-select with Combobox in map view

frontend/src/citizen-frontend/messages/ThreadView.tsx, frontend/src/employee-frontend/components/messages/SingleThreadView.tsx, frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx, frontend/src/lib-common/generated/api-types/messaging.ts, service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
=> Fix messaging bulletin regression

frontend/src/employee-frontend/components/applications/ApplicationsPage.tsx, frontend/src/employee-frontend/state/StateProvider.tsx
Otherwise the application page filters are lost when navigating between pages.
=> Make ApplicationUIContext global again

frontend/src/e2e-playwright/pages/employee/finance/finance-page.ts, frontend/src/e2e-playwright/specs/4_finance/fee-decisions.spec.ts, frontend/src/e2e-playwright/specs/4_finance/head-of-family-fee-decisions.spec.ts, frontend/src/e2e-playwright/specs/4_finance/invoices.spec.ts, frontend/src/e2e-playwright/specs/4_finance/value-decisions.spec.ts, frontend/src/e2e-playwright/specs/4_finance/voucher-reports.spec.ts, frontend/src/e2e-test-common/dev-api/fixtures.ts, frontend/src/e2e-test-common/dev-api/index.ts, frontend/src/e2e-test-common/dev-api/types.ts, frontend/src/employee-frontend/components/fee-decision-details/Heading.tsx, frontend/src/employee-frontend/components/voucher-value-decision/VoucherValueDecisionHeading.tsx, frontend/src/employee-frontend/types/invoicing.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/resources/WEB-INF/templates/fee-decision/decision.html, service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.html, service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt, service/src/test/kotlin/fi/espoo/evaka/invoicing/service/PdfServiceTest.kt
- If fee decision has partner set, and all the children in the decision are both parents' children, show the partner in details UI and .pdf
- If voucher value decision has partner set, and child in the decision is both parent's child, show the partner in details UI and .pdf
=> Show partner name in invoicing decision information

frontend/src/employee-frontend/components/vasu/VasuEditPage.tsx, frontend/src/employee-frontend/components/vasu/VasuPage.tsx, frontend/src/employee-frontend/components/vasu/components/MultiSelectQuestion.tsx, frontend/src/employee-frontend/components/vasu/components/RadioGroupQuestion.tsx, frontend/src/employee-frontend/components/vasu/components/TextQuestion.tsx, frontend/src/employee-frontend/components/vasu/sections/DynamicSections.tsx, frontend/src/employee-frontend/components/vasu/templates/CreateQuestionModal.tsx, frontend/src/employee-frontend/components/vasu/templates/VasuTemplateEditor.tsx, frontend/src/employee-frontend/components/vasu/vasu-content.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
=> Vasu followup section

service/src/integrationTest/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentNotificationServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentNotificationService.kt
The sending of pedagogical documentation notifications did not work if
one of the guardians of the child did not have an email address
configured. This makes sure that even if one guardian is missing an
email address, all the other guardians and heads of the child are sent
the notification.
=> Make sure guardians with email addresses get pedadoc notifications

frontend/src/employee-frontend/components/decision-draft/DecisionDraft.tsx
Broken in d4f96c2fa7343b2450b23e0b454b2702e42bccd8
=> EVAKA-HOTFIX Fix changing the unit of a decision

frontend/src/employee-frontend/components/person-profile/income/IncomeItemHeader.tsx
=> Fix chevron directions in IncomeItemHeader

frontend/src/e2e-playwright/pages/employee/units/unit.ts, frontend/src/e2e-playwright/specs/5_employee/unit-acl.spec.ts, frontend/src/e2e-playwright/utils/index.ts, frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx
The fix here is to type to the combo box before attempting to select anything from it. Just opening the combo box doesn't work in about 1/20 of the times.
While searching for the fix, refactored the tests to use locators and the unit access control components to use `renderResult`, `useApiState`, factored out inline components, etc.
=> Fix a flaky E2E test

frontend/src/citizen-frontend/header/DesktopNav.tsx, frontend/src/citizen-frontend/header/MobileNav.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts
- Add personal details page's Swedish and English translations
- Remove personalDetailsPage feature flag
=> EVAKA-4259 personal details finishing touches

frontend/src/citizen-frontend/App.tsx
Show calendar page if user has access to calendar, otherwise show map.
=> Improve citizen landing page selection

frontend/src/lib-components/layout/ListGrid.tsx
Apply bottom margin only to direct children.
=> EVAKA-FIX ListGrid mobile margins

service/src/main/kotlin/fi/espoo/evaka/varda/VardaQueries.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
- Ensure varda child is eventually deleted when there are no service needs to be sent from evaka
=> Varda improvements

frontend/src/employee-frontend/components/PersonProfile.tsx, frontend/src/employee-frontend/components/person-profile/IncomeStatementsTable.tsx, frontend/src/employee-frontend/components/person-profile/PersonApplications.tsx, frontend/src/employee-frontend/components/person-profile/PersonDecisions.tsx, frontend/src/employee-frontend/components/person-profile/PersonDependants.tsx, frontend/src/employee-frontend/components/person-profile/PersonFamilyOverview.tsx, frontend/src/employee-frontend/components/person-profile/PersonFridgeChild.tsx, frontend/src/employee-frontend/components/person-profile/PersonFridgeHead.tsx, frontend/src/employee-frontend/components/person-profile/PersonFridgePartner.tsx, frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx, frontend/src/employee-frontend/components/person-profile/PersonInvoices.tsx, frontend/src/employee-frontend/state/person.tsx
Like #1659 but for `PersonContext` this time.
=> Refactor person context

service/.dockerignore, service/Dockerfile, service/dd-jmxfetch/conf.yaml, service/entrypoint.sh
=> Configuration for Datadog jmxfetch

frontend/src/employee-frontend/components/voucher-value-decision/VoucherValueDecisionSummary.tsx, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt, service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.html, service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.properties, service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision_sv.properties
=> Update voucher value decision PDF texts

service/Dockerfile
=> Update datadog-java-agent to version 0.90.0

frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx
=> More fixes to the assistance needs/actions report

frontend/src/citizen-frontend/api-client.ts, frontend/src/citizen-frontend/applications/editor/ApplicationFormClub.tsx, frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx, frontend/src/citizen-frontend/applications/editor/ApplicationFormPreschool.tsx, frontend/src/citizen-frontend/applications/editor/validations.ts, frontend/src/e2e-playwright/browser.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-club-application.spec.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-daycare-application.spec.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-preschool-application.spec.ts, frontend/src/e2e-playwright/utils/application-forms.ts, frontend/src/employee-frontend/api/client.ts, frontend/src/employee-mobile-frontend/api/client.ts, frontend/src/lib-common/local-date.ts, frontend/src/lib-common/utils/helpers.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt, service/src/integrationTest/resources/application-integration-test.yaml, service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt, service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/SpringMvcConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/domain/EvakaClock.kt, service/src/main/resources/application-local.yaml
Mechanism for using mocked time in tests.
Includes the commit from https://github.com/espoon-voltti/evaka/pull/1679 since I noticed the bug when converting the club and preschool application tests.
=> Mock clock

frontend/src/employee-mobile-frontend/components/attendances/child-info/ChildButtons.tsx, frontend/src/employee-mobile-frontend/components/common/BottomNavbar.tsx
=> EVAKA-FIX hide mobile message buttons by the feature flag

evaka-bom/build.gradle.kts, service/owasp-suppressions.xml
=> Backend upgrades 2021-11 part 2

service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/CaretakerServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/CaretakerService.kt
=> EVAKA-HOTFIX: Handle two caretaker rows with same start date gracefully

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> Re-enable other basis feature flag in Espoo

service/src/integrationTest/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentNotificationServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentNotificationService.kt
=> Send pedagogical documents notifications to guardians only

service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- Send application notification email for service voucher unit applications
=> Send application notification for service voucher unit applications

frontend/src/e2e-test/pages/employee/units/unit-page.ts, frontend/src/e2e-test/specs/2_employee-2/application-transitions.spec.ts, frontend/src/employee-frontend/components/UnitPage.tsx, frontend/src/employee-frontend/components/unit/TabApplicationProcess.tsx, frontend/src/employee-frontend/components/unit/TabApplications.tsx, frontend/src/employee-frontend/components/unit/TabPlacementProposals.tsx, frontend/src/employee-frontend/components/unit/TabWaitingConfirmation.tsx, frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposals.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> Reorganize unit application tabs

frontend/src/e2e-playwright/pages/employee/child-information.ts, frontend/src/e2e-playwright/specs/5_employee/vasu.spec.ts, frontend/src/e2e-test-common/dev-api/index.ts, frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx, frontend/src/employee-frontend/components/vasu/VasuEditPage.tsx, frontend/src/employee-frontend/components/vasu/VasuPage.tsx, frontend/src/employee-frontend/components/vasu/components/FollowupQuestion.tsx, frontend/src/employee-frontend/components/vasu/components/VasuContainer.tsx, frontend/src/employee-frontend/components/vasu/components/question-props.d.ts, frontend/src/employee-frontend/components/vasu/sections/DynamicSections.tsx, frontend/src/employee-frontend/components/vasu/templates/CreateQuestionModal.tsx, frontend/src/employee-frontend/components/vasu/templates/VasuTemplateEditor.tsx, frontend/src/employee-frontend/components/vasu/vasu-content.ts, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- Refactored the layout of the vasu pages
- Render the follow up section similar to a text question, but with different styling
- Currently stores only one string. Next PR will introduce "log rows"
=> Vasu followup element

service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImageQueries.kt, service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimes.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/PreschoolTerms.kt, service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsTokenQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceBasicsController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeAlterationQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeThresholdQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageAccountQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pairing/MobileDeviceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt, service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/auth/AclQueries.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaQueries.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateQueries.kt
`SELECT * FROM` queries fail when there is an `ADD COLUMN` operation running at the same time.
=> Replace SELECT * FROM ... queries with explicit column names

frontend/src/citizen-frontend/messages/MessageEditor.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Citizen message editor reject draft button

.circleci/config.yml, message-service/Dockerfile, message-service/buildSrc/src/main/kotlin/Version.kt, service/Dockerfile, service/buildSrc/src/main/kotlin/Version.kt, service/src/main/kotlin/fi/espoo/evaka/shared/domain/HelsinkiDateTime.kt
=> Use Java 17

.circleci/config.yml, apigw/package.json, apigw/src/index.ts, apigw/src/shared/config.ts, apigw/src/tracer.ts, apigw/yarn.lock, service/entrypoint.sh
=> Add APM monitoring to node

frontend/src/employee-mobile-frontend/components/common/GroupSelector.tsx, frontend/src/employee-mobile-frontend/components/common/GroupSelectorBar.tsx, frontend/src/employee-mobile-frontend/components/common/TopBarWithGroupSelector.tsx, frontend/src/employee-mobile-frontend/components/messages/MessageEditorPage.tsx, frontend/src/employee-mobile-frontend/components/messages/MessagesPage.tsx, frontend/src/employee-mobile-frontend/components/messages/ThreadView.tsx, frontend/src/employee-mobile-frontend/state/messages.tsx
- Show empty box if selected account undefined / not found
- Set selected account undefined if selected group is not in nestedAccounts
=> EVAKA-4256 empty message box when selected account is undefined

frontend/src/citizen-frontend/header/Header.tsx
Fix mobile header moving differently from its menu.
=> EVAKA "scroll bug"

frontend/src/lib-components/atoms/buttons/IconButton.tsx, frontend/src/lib-components/employee/messages/MessageEditor.tsx, frontend/src/lib-icons/free-icons.ts, frontend/src/lib-icons/index.ts, frontend/src/lib-icons/pro-icons.ts
Add expand / collapse button to desktop new message view
=> Add expand / collapse buttons to new message desktop view

apigw/src/shared/config.ts
=> Fix login in local development

service/entrypoint.sh
=> Separate statsd host

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
=> Document no replies on own bulletin

frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx
=> Fix link to unit map on application page;

frontend/src/lib-components/employee/messages/MessageEditor.tsx
- Make new message expanded view (almost) full screen
- Fix bottom bar height
=> Evaka fix expand message even more

frontend/src/e2e-playwright/pages/mobile/thread-view.ts, frontend/src/e2e-playwright/specs/6_mobile/messages.spec.ts, frontend/src/e2e-test-common/dev-api/index.ts, frontend/src/employee-mobile-frontend/components/messages/MessagesPage.tsx, frontend/src/employee-mobile-frontend/components/messages/ThreadView.tsx, frontend/src/lib-components/atoms/form/TextArea.tsx
- Choose sender from current accounts
- Use TextArea as input component
=> EVAKA-4256 fix mobile message replier

frontend/src/citizen-frontend/header/DesktopNav.tsx, frontend/src/citizen-frontend/header/MobileNav.tsx
- Show lock icons for weak citizen for all menu items where strong auth is needed
- Show attention indicator always if email is missing
- Simplify some components by passing in mobile navigation by passing user as a required prop
- Use flex gaps instead of random margin left on the last child
- Add missing generic fonts to nav link fonts
=> Unify citizen navigation layouts

frontend/src/e2e-playwright/specs/6_mobile/messages.spec.ts, frontend/src/employee-mobile-frontend/components/messages/MessagesPage.tsx, frontend/src/employee-mobile-frontend/components/messages/ThreadView.tsx
- Add timeout to temporarily fix the issue (correct fix needs more refactoring)
- Also set thread heading sticky and adjust some margins
=> EVAKA-FIX flaky e2e test temporarily with timeout

frontend/src/lib-common/generated/action.d.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
=> Do not show pre preschool assistance actions to non admin

frontend/src/e2e-playwright/specs/6_mobile/messages.spec.ts, frontend/src/employee-mobile-frontend/components/messages/MessagesPage.tsx, frontend/src/employee-mobile-frontend/components/messages/ThreadView.tsx, frontend/src/employee-mobile-frontend/state/messages.tsx
- Avoid rendering thread view twice on read
- Tweak unread message logic in another commit
=> EVAKA-FIX another take on flaky mobile message e2e-test

frontend/src/e2e-playwright/specs/0_citizen/citizen-applications-list.spec.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-club-application.spec.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-daycare-application.spec.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-decisions.spec.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-header.spec.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-income-statement.spec.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-map.spec.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-pedagogical-documents.spec.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-personal-details.spec.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-preschool-application.spec.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-reservations.spec.ts, frontend/src/e2e-playwright/specs/4_finance/fee-decisions.spec.ts, frontend/src/e2e-playwright/specs/4_finance/finance-basics.spec.ts, frontend/src/e2e-playwright/specs/4_finance/invoices.spec.ts, frontend/src/e2e-playwright/specs/4_finance/value-decisions.spec.ts, frontend/src/e2e-playwright/specs/4_finance/voucher-reports.spec.ts, frontend/src/e2e-playwright/specs/6_mobile/absences.spec.ts, frontend/src/e2e-playwright/specs/6_mobile/child-attendances.spec.ts, frontend/src/e2e-playwright/specs/6_mobile/messages.spec.ts, frontend/src/e2e-playwright/specs/6_mobile/notes.spec.ts, frontend/src/e2e-playwright/specs/6_mobile/pin-login.spec.ts, frontend/src/e2e-playwright/specs/6_mobile/staff.spec.ts, frontend/src/e2e-playwright/specs/8_access/access.spec.ts
=> Remove page.close() calls

frontend/src/employee-frontend/api/invoicing.ts, frontend/src/employee-frontend/components/person-profile/PersonFeeDecisions.tsx, frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx, frontend/src/employee-frontend/state/ui.tsx, frontend/src/lib-components/molecules/date-picker/DatePicker.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/src/main/kotlin/fi/espoo/evaka/Audit.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
- Add option to open date picker above input
- Refactor person fee decisions component
- Add way to manually trigger value decision generation
=> EVAKA manual voucher value decision generation

service/src/main/kotlin/fi/espoo/evaka/shared/job/JobSchedule.kt
=> EVAKA-4000 run varda jobs daily again

frontend/src/e2e-playwright/pages/citizen/citizen-applications.ts, frontend/src/e2e-playwright/pages/citizen/citizen-decisions.ts, frontend/src/e2e-playwright/pages/citizen/citizen-map.ts, frontend/src/e2e-playwright/pages/citizen/citizen-messages.ts, frontend/src/e2e-playwright/pages/employee/applications.ts, frontend/src/e2e-playwright/pages/employee/child-information.ts, frontend/src/e2e-playwright/pages/employee/employee-nav.ts, frontend/src/e2e-playwright/pages/employee/employee-pin.ts, frontend/src/e2e-playwright/pages/employee/finance-basics.ts, frontend/src/e2e-playwright/pages/employee/messages/messages-page.ts, frontend/src/e2e-playwright/pages/employee/person-search.ts, frontend/src/e2e-playwright/pages/employee/reports.ts, frontend/src/e2e-playwright/pages/mobile/absences-page.ts, frontend/src/e2e-playwright/pages/mobile/child-page.ts, frontend/src/e2e-playwright/pages/mobile/list-page.ts, frontend/src/e2e-playwright/pages/mobile/message-editor.ts, frontend/src/e2e-playwright/pages/mobile/messages.ts, frontend/src/e2e-playwright/pages/mobile/mobile-nav.ts, frontend/src/e2e-playwright/pages/mobile/staff-page.ts, frontend/src/e2e-playwright/pages/mobile/thread-view.ts, frontend/src/e2e-playwright/utils/element.ts
=> Rename RawElement to RawElementDEPRECATED

frontend/src/e2e-playwright/pages/employee/units/unit.ts, frontend/src/e2e-playwright/specs/5_employee/unit.spec.ts, frontend/src/e2e-test/specs/5_employee/units.spec.ts, frontend/src/employee-frontend/components/UnitPage.tsx
=> Store open unit groups to local storage for persistence over navigation

frontend/src/employee-mobile-frontend/api/attendances.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- Avoid unnecessary and heavy calculation of responses which are not used on client side
=> Remove unused response calculation

frontend/src/employee-frontend/components/UnitPage.tsx, frontend/src/lib-components/molecules/Tabs.tsx
=> Tiny CSS fixes

frontend/src/employee-mobile-frontend/components/attendances/AttendanceList.tsx
=> Fix attendance page child filtering

frontend/src/citizen-frontend/messages/MessageEditor.tsx
CItizen message editor full screen on mobile
=> Citizen mobile message editor fullscreen

frontend/src/employee-frontend/components/child-information/assistance-action/AssistanceActionForm.tsx, frontend/src/employee-frontend/components/child-information/assistance-action/AssistanceActionRow.tsx, frontend/src/employee-frontend/components/common/LabelValueList.tsx
Tampere is not going to use assistance measures.
=> Hide assistance measures if empty options

frontend/src/employee-frontend/components/child-information/placements/ServiceNeeds.tsx
=> Hide delete service need modal on submit

frontend/src/e2e-playwright/pages/mobile/list-page.ts, frontend/src/e2e-playwright/specs/6_mobile/child-attendances.spec.ts, frontend/src/e2e-test-common/dev-api/fixtures.ts, frontend/src/employee-mobile-frontend/components/attendances/AttendanceList.tsx, frontend/src/employee-mobile-frontend/components/common/GroupSelectorBar.tsx
=> Add e2e test for child attendance list and group selector

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> Enable personal mobile devices in staging

service/src/main/kotlin/fi/espoo/evaka/note/child/daily/ChildDailyNoteQueries.kt
=> Delete child daily notes after 14 hours

service/dd-jmxfetch/conf.yaml, service/src/main/kotlin/fi/espoo/evaka/shared/config/DatabaseConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/RedisConfig.kt
Datadog configuration is an *educated guess* and has not been tested
=> Add hikari + jedis metrics

frontend/src/employee-frontend/components/Header.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts
The feature is ready to be used in production.
=> Remove personal mobile devices experimental feature flag

frontend/src/employee-frontend/components/UnitPage.tsx, frontend/src/employee-frontend/components/unit/TabPlacementProposals.tsx, frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposalRow.tsx, frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposals.tsx, frontend/src/employee-frontend/types/unit.ts, frontend/src/lib-common/generated/api-types/placement.ts, frontend/src/lib-components/layout/Table.tsx, frontend/src/lib-components/typography.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlan.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanQueries.kt, service/src/main/kotlin/fi/espoo/evaka/units/UnitsView.kt
=> Display citizen rejected decision for two weeks

frontend/src/e2e-playwright/pages/employee/units/unit.ts, frontend/src/e2e-playwright/specs/5_employee/unit-acl.spec.ts, frontend/src/e2e-playwright/specs/5_employee/unit-editor.spec.ts, frontend/src/e2e-playwright/specs/5_employee/unit-groups.spec.ts, frontend/src/employee-frontend/components/unit/tab-unit-information/UnitInformation.tsx, frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- Warning when setting unit closing date that placements must end by then
- Warning when send-to-varda is set for unit which provider type not meant for varda
- Warning (info) when handler address is missing for "standard" units
- Show / hide invoicing related fields based on unit invoicing selection
=> Unit editor validations and warnings

frontend/src/lib-common/generated/action.d.ts, service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/PermittedRoleActions.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
=> Moves vasu followup comment access control to `AccessControl.kt`

frontend/src/employee-frontend/components/vasu/sections/EvaluationDiscussionSection.tsx
The evaluation discussion section should be highlighted when a document is published as ready and edited by an employee.
=> Highlight the evaluation discussion section of vasu documents

frontend/src/lib-customizations/espoo/employee/assets/i18n/vasu/fi.ts
=> Small tweak to the titles of the vasu document

frontend/src/e2e-playwright/pages/employee/fridge-head-information-page.ts, frontend/src/e2e-playwright/specs/5_employee/income.spec.ts, frontend/src/e2e-playwright/utils/index.ts
=> Fix flaky e2e test

frontend/src/e2e-playwright/pages/mobile/list-page.ts, frontend/src/e2e-playwright/pages/mobile/messages.ts, frontend/src/e2e-playwright/pages/mobile/unread-message-counts.ts, frontend/src/e2e-playwright/specs/6_mobile/messages.spec.ts, frontend/src/employee-mobile-frontend/App.tsx, frontend/src/employee-mobile-frontend/api/messages.ts, frontend/src/employee-mobile-frontend/components/common/BottomNavbar.tsx, frontend/src/employee-mobile-frontend/components/messages/MessagesPage.tsx, frontend/src/employee-mobile-frontend/components/messages/UnreadMessagesPage.tsx, frontend/src/employee-mobile-frontend/state/messages.tsx, frontend/src/employee-mobile-frontend/state/unit.tsx, frontend/src/lib-common/generated/api-types/messaging.ts, frontend/src/lib-components/typography.ts, frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- Add new page for showing unread counts by group 
- Show indicator in bottom nav if any group has unread messages
=> EVAKA-4256 show unread counts by group

frontend/package.json
=> Don't run eslint for files under dist/

frontend/eslint-plugin/rules/no-testonly.js, frontend/src/e2e-playwright/specs/4_finance/fee-decisions.spec.ts, frontend/src/e2e-playwright/specs/5_employee/income.spec.ts
-remove used it.only and describe.only
-lint it.only
-lint describe.only
refactor linting config
=> Evaka fix fix flaky test

frontend/src/e2e-playwright/pages/employee/vasu/vasu.ts, frontend/src/e2e-playwright/pages/mobile/pin-login-page.ts, frontend/src/e2e-playwright/specs/6_mobile/messages.spec.ts, frontend/src/employee-mobile-frontend/components/auth/PinLogin.tsx, frontend/src/lib-components/atoms/buttons/Button.tsx
=> Flaky E2E fixes

evaka-bom/build.gradle.kts
=> Upgrade log4j to silence the OWASP check

evaka-bom/build.gradle.kts, message-service/owasp-suppressions.xml, service/owasp-suppressions.xml
=> Upgrade netty

service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
An alternative to #1805. Closes #1805.
=> EVAKA-4335: Handle overnight reservations (alternative)

frontend/src/employee-frontend/components/vasu/VasuEditPage.tsx, frontend/src/employee-frontend/components/vasu/VasuPage.tsx, frontend/src/employee-frontend/components/vasu/api.ts, frontend/src/employee-frontend/components/vasu/components/FollowupQuestion.tsx, frontend/src/employee-frontend/components/vasu/sections/DynamicSections.tsx, frontend/src/employee-frontend/components/vasu/use-vasu.ts, frontend/src/lib-common/api-types/vasu.ts, frontend/src/lib-common/generated/api-types/vasu.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
=> Ask server whether user is allowed to edit vasu followup comments

frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Text updates for preschool application

service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
=> Fix build: Suppress a deprecation

service/Dockerfile
=> Update Datadog Agent

frontend/src/employee-mobile-frontend/components/messages/ThreadView.tsx
=> EVAKA-4256 Use max width for message container

frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
=> Tiny text changes

service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
Use fridge partner relationships in addition to being a head of a child to find placements to determine the care area.
=> Resolve income statement care area correctly

frontend/src/employee-frontend/components/reports/VoucherServiceProviderUnit.tsx
=>  EVAKA-4354: Sort voucher value decision rows alphabetically

service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
=> Warn when deprecated configuration keys are used

service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
=> Unified service part 3

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> EVAKA-4348 Absence modal text change

frontend/src/employee-frontend/components/vasu/components/MultiFieldListQuestion.tsx
- Fix MultiFieldListQuestion state setter
- Improve MultiFieldListQuestion readonly formatting
=> EVAKA-4204 fix curriculum multi field list component

frontend/src/e2e-playwright/pages/citizen/citizen-header.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-header.spec.ts, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Fix citizen nav translations

frontend/src/employee-frontend/components/vasu/VasuEditPage.tsx, frontend/src/employee-frontend/components/vasu/VasuPage.tsx, frontend/src/employee-frontend/components/vasu/api.ts, frontend/src/employee-frontend/components/vasu/sections/BasicsSection.tsx, frontend/src/employee-frontend/components/vasu/sections/VasuEvents.tsx, frontend/src/employee-frontend/components/vasu/sections/VasuHeader.tsx, frontend/src/employee-frontend/components/vasu/use-vasu.ts, frontend/src/lib-common/generated/api-types/vasu.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/vasu/fi.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/vasu/sv.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
* Add an optional child language section to the "basics" section that is included in preschool curriculums.
* Change some curriculum texts depending on its type.
=> EVAKA-4204 full support for preschool curriculum

service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/Paging.kt
=> mapToPaged: Run the SQL query once instead of three times

frontend/src/citizen-frontend/messages/MessageEditor.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Fix messaging english translations

README.md, docs/diagrams/src/evaka-container.puml, service-lib/README.md, service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/SoapStackIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt, service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/FuelManagerConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/SfiConfig.kt, service/src/main/kotlin/fi/espoo/evaka/vtjclient/config/KeyManagerConfig.kt, service/src/main/kotlin/fi/espoo/evaka/vtjclient/config/TrustManagerConfig.kt, service/src/main/resources/application-local.yaml, service/src/main/resources/application.yaml, service/src/test/kotlin/fi/espoo/evaka/vtjclient/config/KeyManagerConfigTest.kt
=> Unified service - part 5

service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/Paging.kt
The previous PR went in a bit too early 😬
=> Even more ergonomic mapToPaged overloads

frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> Fix typo in personal devices page

frontend/src/e2e-playwright/pages/employee/vasu/vasu.ts, frontend/src/e2e-playwright/specs/5_employee/vasu.spec.ts, frontend/src/employee-frontend/components/vasu/VasuEditPage.tsx, frontend/src/employee-frontend/components/vasu/components/MultiFieldListQuestion.tsx, frontend/src/employee-frontend/components/vasu/components/MultiFieldQuestion.tsx, frontend/src/employee-frontend/components/vasu/components/ValueOrNoRecord.tsx
=> Adds e2e tests for filling out the authors section of the vasu document

frontend/src/e2e-playwright/pages/employee/child-information-page.ts, frontend/src/e2e-playwright/specs/5_employee/child-information-assistance-needs.spec.ts, frontend/src/employee-frontend/components/child-information/assistance-need/AssistanceNeedRow.tsx, frontend/src/employee-frontend/components/common/Toolbar.tsx, service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- In addition to admin, also SEO should see pre preschool assistance needs and actions
=> Show pre preschool assistance need and actions to SEO

frontend/package.json, frontend/src/e2e-playwright/pages/employee/vasu/pageSections.ts, frontend/src/e2e-playwright/pages/employee/vasu/vasu.ts, frontend/src/e2e-playwright/specs/5_employee/vasu.spec.ts, frontend/src/employee-frontend/components/vasu/components/DateQuestion.tsx, frontend/src/employee-frontend/components/vasu/components/MultiSelectQuestion.tsx, frontend/src/employee-frontend/components/vasu/components/TextQuestion.tsx
=> Vasu fill remaining sections e2e

evaka-bom/build.gradle.kts
=> Upgrade log4j

frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, frontend/src/lib-customizations/espoo/featureFlags.tsx, service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
- Filter curriculums based on child placements
- Remove the word vasu from UI
- Finish preschool default template
- Enable preschool templates in staging
=> EVAKA-4204 leops finishing touches

frontend/src/lib-customizations/espoo/featureFlags.tsx
The flag was accidentally turned on in prod.
=> Disable leops in prod

service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
=> Changes to application decision message

proxy/files/etc/nginx/nginx.conf.template, proxy/files/etc/nginx/proxy_params.template
=> Increase timeout and reset connection header

frontend/src/lib-components/atoms/RoundIcon.tsx
The component already has support for text content with different sizes.
=> Remove outdated RoundIcon warning

frontend/src/e2e-playwright/pages/employee/vasu/vasu.ts, frontend/src/e2e-playwright/specs/5_employee/vasu.spec.ts, frontend/src/employee-frontend/components/vasu/VasuEditPage.tsx, frontend/src/employee-frontend/components/vasu/sections/VasuEvents.tsx
Fixes flakiness in vasu tests
Adds test for publishing a vasu document
=> Vasu publishing e2e & flaky fix

frontend/src/employee-frontend/components/unit/TabWaitingConfirmation.tsx
=> EVAKA-FIX Remove excess title from TabWaitingConfirmation

.circleci/template.yml
=> Fix CI pull requests

.circleci/template.yml
=> No deploy for pulls

frontend/src/employee-frontend/components/UnitPage.tsx
=> Fix unit event count

evaka-bom/build.gradle.kts
Fix https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-42550
=> Fix CVE-2021-42550

service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt, service/src/test/kotlin/fi/espoo/evaka/invoicing/service/PdfServiceTest.kt
Similar to https://github.com/espoon-voltti/evaka/pull/1577 but for fee & voucher value decisions.
=> Add fee decision maker from settings

frontend/src/e2e-playwright/pages/mobile/messages.ts, frontend/src/e2e-playwright/specs/6_mobile/messages.spec.ts, frontend/src/employee-mobile-frontend/components/messages/MessagesPage.tsx, frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
If staff member is without group access they should be informed about it instead of showing spinner eternally
=> EVAKA-4265 Show info about missing group access in mobile messages

frontend/src/e2e-playwright/pages/employee/vasu/pageSections.ts, frontend/src/e2e-playwright/pages/employee/vasu/vasu.ts, frontend/src/e2e-playwright/specs/5_employee/vasu.spec.ts
=> Adds e2e test for filling out the evaluation section of a finalized vasu

service/src/main/kotlin/fi/espoo/evaka/placement/PlacementType.kt
=> TREV-207 SCHOOL_SHIFT_CARE as non billable

frontend/src/employee-frontend/components/child-information/FridgeParents.tsx
=> Fridge parent name order fix

service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
=> EVAKA-4368 fix English information in application message

frontend/src/e2e-playwright/pages/admin/application-workbench-page.ts, frontend/src/e2e-playwright/pages/employee/applications/application-read-view.ts, frontend/src/e2e-playwright/pages/employee/placement-draft-page.ts, frontend/src/e2e-playwright/specs/5_employee/application-transitions.spec.ts, frontend/src/employee-frontend/components/ApplicationPage.tsx, frontend/src/employee-frontend/components/UnitPage.tsx, frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx, frontend/src/employee-frontend/components/application-page/DecisionResponse.tsx, frontend/src/employee-frontend/components/application-page/VTJGuardian.tsx, frontend/src/employee-frontend/components/child-information/ChildDetails.tsx, frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx, frontend/src/employee-frontend/components/person-profile/PersonFamilyOverview.tsx, frontend/src/employee-frontend/components/person-profile/PersonFridgeHead.tsx, frontend/src/employee-frontend/components/placement-draft/PlacementDraft.tsx, frontend/src/employee-frontend/components/placement-draft/PlacementDraftRow.tsx, frontend/src/employee-frontend/components/placement-draft/UnitCard.tsx, frontend/src/employee-frontend/components/placement-draft/UnitCards.tsx, frontend/src/lib-common/api.ts
=> Flaky e2e test fixes

frontend/src/citizen-frontend/applications/Applications.tsx, frontend/src/e2e-playwright/pages/citizen/citizen-applications.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-daycare-application.spec.ts
=> Flaky e2e test fix

frontend/src/e2e-playwright/pages/employee/units/unit.ts, frontend/src/e2e-playwright/specs/5_employee/application-transitions.spec.ts, frontend/src/e2e-test-common/dev-api/index.ts, frontend/src/employee-frontend/api/client.ts, frontend/src/employee-frontend/components/UnitPage.tsx, frontend/src/employee-frontend/components/applications/ApplicationsList.tsx, frontend/src/employee-frontend/components/applications/CircleIcon.tsx, frontend/src/employee-frontend/components/unit/TabPlacementProposals.tsx, frontend/src/employee-frontend/components/unit/TabWaitingConfirmation.tsx, frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposalRow.tsx, frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposals.tsx, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/kotlin/fi/espoo/evaka/units/UnitsView.kt
=> Move applications rejected by citizen under placement plans

frontend/src/e2e-playwright/pages/employee/units/unit.ts, frontend/src/e2e-playwright/specs/5_employee/unit-editor.spec.ts, frontend/src/employee-frontend/components/unit/TabUnitInformation.tsx, frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx
=> Flaky test fix

service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
=> Add missing service voucher info to English translation; finetune some paragraph breaks.

frontend/src/e2e-test/specs/2_employee-2/guardian-information-page.spec.ts, frontend/src/employee-frontend/components/child-information/FridgeParents.tsx, frontend/src/employee-frontend/components/child-information/GuardiansAndParents.tsx, frontend/src/employee-frontend/components/child-information/MessageBlocklist.tsx, frontend/src/employee-frontend/components/person-profile/PersonDependants.tsx, frontend/src/employee-frontend/components/person-profile/PersonFamilyOverview.tsx, frontend/src/employee-frontend/components/person-profile/PersonFridgeChild.tsx, frontend/src/employee-frontend/components/person-profile/PersonFridgePartner.tsx, frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx, frontend/src/employee-frontend/components/person-profile/person-fridge-child/FridgeChildModal.tsx, frontend/src/employee-frontend/components/person-profile/person-fridge-partner/FridgePartnerModal.tsx, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt, service/src/main/resources/db/migration/R__application_view.sql
Ping @huhtari. Attempt to fix #1886 as discussed.
=> Unified name order in information pages

frontend/src/e2e-playwright/utils/page.ts
=> Flaky test fix: Better opening of collapsibles

.circleci/template.yml
=> Store e2e screenshots correctly in CicleCI

service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/AbstractIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/AbstractIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/utils/SpringMvcTestController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/SpringMvcConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
=> Remove DeprecatedConnections completely

frontend/src/employee-frontend/components/absences/StaffAttendance.tsx
=> EVAKA-FIX: Align staff attendance row with absence columns

frontend/src/e2e-playwright/pages/employee/units/unit.ts, frontend/src/employee-frontend/components/unit/TabGroups.tsx
=> Hide whole missing group list if it is empty

.circleci/template.yml
Removed sceduled cleanup that does not work with dynamic CI. Moved to another repository.
=> Removed scheduled cleanup

service/src/integrationTest/kotlin/fi/espoo/evaka/shared/utils/SpringMvcTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/utils/SpringMvcTestController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/SpringMvcConfig.kt
No need to have an automatic closing mechanism since we no longer have the automatic opening mechanism.
=> Remove Database.DeprecatedConnection leftovers

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
Value decision annulling didn't work if the decision's child's all placements were deleted.
=> Fix value decision annulling when all placements have been deleted

frontend/src/citizen-frontend/map/MapBox.tsx, frontend/src/citizen-frontend/messages/EmptyThreadView.tsx, frontend/src/employee-frontend/components/Header.tsx, frontend/src/employee-frontend/components/applications/ActionsMenu.tsx, frontend/src/employee-frontend/components/common/StatusIconContainer.tsx, frontend/src/employee-frontend/components/common/StickyActionBar.tsx, frontend/src/employee-frontend/components/login-page/Login.tsx, frontend/src/employee-frontend/components/messages/SingleThreadView.tsx, frontend/src/employee-frontend/components/placement-draft/UnitCard.tsx, frontend/src/employee-frontend/components/reports/DuplicatePeople.tsx, frontend/src/employee-frontend/components/reports/common.tsx, frontend/src/employee-mobile-frontend/components/messages/ThreadView.tsx, frontend/src/lib-components/atoms/Loader.tsx, frontend/src/lib-components/atoms/dropdowns/Combobox.tsx, frontend/src/lib-components/atoms/form/TextArea.tsx, frontend/src/lib-components/atoms/state/Spinner.tsx, frontend/src/lib-components/employee/messages/EmptyMessageFolder.tsx, frontend/src/lib-components/molecules/Toast.tsx, frontend/src/lib-components/molecules/modals/BaseModal.tsx
Replace all remaining custom colors in components with colors from theme.
=> Remove all custom color codes from components

service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
=> Hide closed units from citizen map

frontend/src/lib-common/themes/espoo-theme.ts, frontend/src/lib-components/molecules/CollapsibleSection.tsx
=> Use primary hover color in collapsible section

frontend/src/employee-mobile-frontend/components/common/BottomNavbar.tsx, frontend/src/employee-mobile-frontend/components/staff/StaffAttendanceEditor.tsx, frontend/src/lib-components/layout/flex-helpers.ts
=> Remove marginBottom from FixedSpaceRow props

frontend/src/e2e-playwright/pages/mobile/child-page.ts, frontend/src/e2e-playwright/pages/mobile/list-page.ts, frontend/src/e2e-playwright/specs/6_mobile/child-attendances.spec.ts
- E2E test for marking present child departed
=> E2E test for mobile departure

frontend/src/e2e-playwright/pages/employee/units/unit-diary-page.ts, frontend/src/e2e-playwright/specs/5_employee/absence.spec.ts, frontend/src/employee-frontend/components/absences/AbsenceCell.tsx, frontend/src/employee-frontend/components/common/Tooltip.tsx, frontend/src/lib-common/api-types/child/Absences.ts, frontend/src/lib-common/utils/absences-date-range.spec.ts, frontend/src/lib-common/utils/number.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/AbsenceServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
=> Absence modifier info in absence calendar tooltip text

service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
Add `integration.invoice.send_codebtor` default value.
=> EVAKA-4357 invoice codebtor integration default

service/src/main/kotlin/fi/espoo/evaka/invoicing/integration/InvoiceIntegrationClient.kt
- Leave codebtor property from json if it should not be send
- Trim string data send to community
=> EVAKA HOTFIX invoice integration codebtor

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/integration/InvoiceIntegrationClient.kt
=> Fix address trimming in invoice integration

frontend/src/lib-components/molecules/CollapsibleSection.tsx
- smaller, responsive chevron
- remove redundant height and width from chevron container
- remove redundant duplicate click handler
=> Apply new styles to collapsible section

frontend/src/citizen-frontend/calendar/CalendarPage.tsx, frontend/src/citizen-frontend/children/ChildHeader.tsx, frontend/src/citizen-frontend/children/ChildrenPage.tsx, frontend/src/lib-components/layout/responsive-layout.tsx, frontend/src/lib-components/typography.ts
=> Fix typography on children pages

service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt, service/src/main/resources/db/migration/R__koski_views.sql
Make sure only the *last* study right of a child can be marked as qualified.
If a child changed to a different eVaka daycare in May-June, we sent qualified study rights for both daycares because the Koski integration only looked at one child+unit+type -combo at a time and our qualification criteria only looked at the placement end date. Now, we explicitly require that the study right is the last one in the system before marking it as qualified.
Note: this is still not 100% foolproof, because a child can for example move to a different city in May, so the placement ends in May but eVaka has no record of what happens after it. In this case our system sends a qualified study right, because we have (currently) no way of knowing what the child actually did when the placement ended. If we need …
=> Only child's last placement can qualify Koski study right

frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx, frontend/src/citizen-frontend/applications/editor/validations.ts
- Use only applicable terms in citizen preschool application
- Remove outdated citizen preschool date check
=> EVAKA new preschool term

frontend/src/citizen-frontend/children/ChildHeader.tsx, frontend/src/citizen-frontend/children/ChildrenPage.tsx, frontend/src/lib-components/atoms/RoundImage.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Add an alt text to child's picture for screen readers

service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedQueries.kt
Change ordering by hours per week to descending.
=> Change service need option ordering

frontend/eslint-plugin/index.js, frontend/eslint-plugin/rules/no-page-pause.js, frontend/eslint-plugin/rules/utils.js, frontend/src/e2e-playwright/specs/5_employee/placement-sketching-report.spec.ts, frontend/src/e2e-playwright/specs/6_mobile/child-attendances.spec.ts, frontend/src/e2e-playwright/specs/6_mobile/notes.spec.ts
=> Disallow `page.pause()` calls

frontend/src/citizen-frontend/messages/ThreadView.tsx, frontend/src/e2e-playwright/pages/citizen/citizen-messages.ts, frontend/src/e2e-playwright/pages/employee/messages/messages-page.ts, frontend/src/e2e-playwright/specs/7_messaging/messaging.spec.ts, frontend/src/employee-frontend/components/messages/SingleThreadView.tsx, frontend/src/lib-components/layout/ButtonContainer.tsx, frontend/src/lib-components/molecules/MessageReplyEditor.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> EVAKA-FIX add missing message discard button

frontend/src/employee-frontend/components/Header.tsx
=> Fix svg stretching in header (safari)

.circleci/template.yml
=> CI for KeyCloak

frontend/src/citizen-frontend/header/DesktopNav.tsx, frontend/src/citizen-frontend/header/MobileNav.tsx
The new order is
- calendar
- messages
- growth and learning
- children
- applications
=> Rearrange menu items for citizens

frontend/src/employee-frontend/components/absences/AbsenceTable.tsx, frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/ReservationsTable.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx
Select reference points intentionally; use start date of the selected interval in
=> EVAKA-3456 tweak age indicators

frontend/src/e2e-playwright/specs/5_employee/unit-groups.spec.ts, frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
In the group section, avoid confusing users with child capacity factor of 1. Instead, show a dash to indicate non-effective factor.
=> EVAKA-FIX show — when capacity factor equals 1

service/src/main/kotlin/fi/espoo/evaka/invoicing/integration/InvoiceIntegrationClient.kt
=> Better invoice integration error logging

service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/CaretakerService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Invoices.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValue.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiClient.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pairing/PairingsController.kt, service/src/main/kotlin/fi/espoo/evaka/reports/FamilyContactReport.kt, service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt, service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
=> Use more type-safe IDs

service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceUpkeepIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/test/TestData.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceIntegrationTest.kt
=> Fix Kotlin compiler warnings

service/src/main/kotlin/fi/espoo/evaka/identity/ExternalIdentifier.kt, service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
=> Remove unnecessary equals/hashCode overrides

frontend/src/employee-frontend/components/Units.tsx, frontend/src/lib-common/generated/api-types/shared.ts, service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/EmployeeFeatures.kt
Redirect users automatically to the only unit in their unit list if they don't have the rights to create new units.
=> Unit list automatic redirect

service/src/main/resources/db/migration/V195__evaka_user_decision_resolved_by.sql, service/src/main/resources/migrations.txt
=> Add evaka_user fk constraint to decision.resolved_by

frontend/src/e2e-playwright/pages/employee/reports.ts, frontend/src/e2e-playwright/specs/5_employee/varda_error_report.spec.ts, frontend/src/e2e-test-common/dev-api/fixtures.ts, frontend/src/e2e-test-common/dev-api/index.ts, frontend/src/e2e-test-common/dev-api/types.ts, frontend/src/employee-frontend/api/reports.ts, frontend/src/employee-frontend/components/reports/VardaErrors.tsx, frontend/src/employee-frontend/types/reports.ts, frontend/src/lib-common/generated/api-types/reports.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/src/main/kotlin/fi/espoo/evaka/reports/VardaErrorsReport.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaController.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaDevController.kt
=> Reset child from varda error report

frontend/src/e2e-playwright/pages/employee/employee-nav.ts, frontend/src/e2e-playwright/pages/employee/vasu/pageSections.ts, frontend/src/e2e-playwright/pages/employee/vasu/vasu-template-edit.ts, frontend/src/e2e-playwright/pages/employee/vasu/vasu-templates-list.ts, frontend/src/e2e-playwright/pages/employee/vasu/vasu.ts, frontend/src/e2e-playwright/specs/5_employee/leops.spec.ts, frontend/src/e2e-playwright/specs/5_employee/vasu.spec.ts, frontend/src/e2e-test-common/dev-api/fixtures.ts, frontend/src/e2e-test-common/dev-api/index.ts, frontend/src/employee-frontend/components/vasu/VasuStateTransitionButtons.tsx, frontend/src/employee-frontend/components/vasu/components/MultiSelectQuestion.tsx, frontend/src/employee-frontend/components/vasu/components/ValueOrNoRecord.tsx, frontend/src/employee-frontend/components/vasu/sections/DynamicSections.tsx, frontend/src/employee-frontend/components/vasu/sections/VasuHeader.tsx, frontend/src/employee-frontend/components/vasu/templates/CreateOrEditTemplateModal.tsx, frontend/src/employee-frontend/components/vasu/templates/VasuTemplateEditor.tsx, frontend/src/employee-frontend/components/vasu/templates/VasuTemplatesPage.tsx, frontend/src/lib-common/api-types/vasu.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuTemplateIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuTest.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- fix texts
- add and use new multi select text selection
- e2e test for creating a leops template and filling it
=> Leops template changes and improvements

frontend/src/employee-frontend/components/fee-decision-details/Actions.tsx, frontend/src/employee-frontend/components/fee-decision-details/FeeDecisionDetailsPage.tsx, frontend/src/employee-frontend/components/invoice/Actions.tsx, frontend/src/employee-frontend/components/invoice/InvoicePage.tsx, frontend/src/employee-frontend/components/voucher-value-decision/VoucherValueDecisionActionBar.tsx, frontend/src/employee-frontend/components/voucher-value-decision/VoucherValueDecisionPage.tsx
* Fix `AsyncButton` usage in `InvoicePage.tsx`, `FeeDecisionDetailsPage.tsx` and `VoucherValueDecisionPage.tsx` 
* Remove the low value error messages
* Add more `useCallback` usage
=> Fix async button in finance decision and invoice pages

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
=> Do not cleanup a person with income statement

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/service/MergeService.kt
=> Handle evaka_user references in person merge

frontend/src/citizen-frontend/personal-details/PersonalDetails.tsx, frontend/src/e2e-playwright/pages/citizen/citizen-personal-details.ts, frontend/src/e2e-playwright/specs/0_citizen/citizen-personal-details.spec.ts, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- Warn about missing phone number
- Alert supports one or two alerts
- E2E tests
=> Warn about missing phone number

service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
Responding to review comments.
=> Speculated occupancy cleanups

frontend/src/citizen-frontend/localization/state.tsx, frontend/src/e2e-test/pages/citizen/citizen-header.ts, frontend/src/e2e-test/specs/0_citizen/citizen-header.spec.ts
=> Update the `<html lang=...>` attribute whenever the language changes

frontend/src/citizen-frontend/localization/state.tsx
=> Switch from `useCallback` to more idiomatic `useEffect`

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeAlterationQueriesTest.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionDraftService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeAlterationQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pis/service/MergeService.kt, service/src/main/kotlin/fi/espoo/evaka/reports/EndedPlacementsReport.kt, service/src/main/kotlin/fi/espoo/evaka/reports/PresenceReport.kt, service/src/main/kotlin/fi/espoo/evaka/reports/StartingPlacementsReport.kt
=> Replace some raw JDBC mapping code

frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx, frontend/src/lib-components/atoms/form/InputField.tsx
=> Fix postal info layout

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/MissingHeadOfFamilyReportTest.kt
=> Fix missing objectMapper

frontend/src/employee-frontend/components/fee-decision-details/TypeSelect.tsx, frontend/src/lib-customizations/employee.tsx, frontend/src/lib-customizations/espoo/employee.tsx, frontend/src/lib-customizations/types.d.ts
Tre doesn't use `RELIEF_PARTLY_ACCEPTED`.
=> Add decision type to customizations

frontend/src/employee-frontend/components/absences/AbsenceLegend.tsx, frontend/src/employee-frontend/components/absences/Absences.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/AbsenceDay.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx, frontend/src/lib-customizations/common.tsx
Add absence legend with icons to calendar week view.
=> EVAKA-4378 Absence legend to calendar week view

.circleci/template.yml
=> Use CIRCLE_WORKFLOW_ID to fix CI

frontend/src/employee-frontend/components/unit/unit-reservations/ReservationsTable.tsx
=> EVAKA-4378 Highlight today on the weekly calendar

proxy/Dockerfile
=> Upgrade proxy

service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
=> Change 'vanhempi' to 'huoltaja' in leops

keycloak/Dockerfile
=> Remove duplicate apk update

frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/dev-api/index.ts, frontend/src/e2e-test/dev-api/types.ts, frontend/src/e2e-test/pages/employee/units/unit.ts, frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts, frontend/src/e2e-test/specs/5_employee/unit-application-process.spec.ts, frontend/src/e2e-test/specs/5_employee/unit-groups.spec.ts, frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposals.tsx, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanQueries.kt
- E2E test for unit application process placement plan view
- use latest application related decision with placement plans to avoid duplicates
=> Remove duplicate placement plans

frontend/src/lib-common/themes/espoo-theme.ts, frontend/src/lib-components/molecules/ExpandingInfo.tsx
=> Use info status color in ExpandingInfo, change Espoo info color to m2

service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
=> Avoid batch usage where JDBI bug is known to be triggered

keycloak/Dockerfile
=> Set commit hash for KeyCloak

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
=> Use mocked time in value decision tests

frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposalRow.tsx, frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposals.tsx
There was an error in console that the modal is inside a table but not inside tr and td, so wrap it inside them
=> Error: Element inside a table must be wrapped in tr and td

apigw/src/enduser/app.ts, apigw/src/internal/app.ts, apigw/src/shared/session.ts
If this is not done, req.session will contain stale expiry timestamp from redis data.
=> Make sure session maxAge is always up to date

apigw/src/internal/index.ts, proxy/files/etc/nginx/nginx.conf.template
https://sigopt.com/blog/the-case-of-the-mysterious-aws-elb-504-errors/
https://backstage.headout.com/2021/04/07/fixing-ambiguous-aws-elb-504-timeouts-can-make-or-break-the-server/
=> Increase node timeouts

service/src/integrationTest/kotlin/fi/espoo/evaka/ServiceNeedTestFixtures.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerator.kt
Fee/voucher value decision should not be generated for school shift care.
=> Add school shift care as non paid placement

frontend/src/employee-frontend/components/absences/AbsenceTable.tsx, frontend/src/employee-frontend/components/absences/utils.ts
=> Fix direct dependency to fi translations in AbsenceTable week day

frontend/src/employee-frontend/components/Header.tsx
=> Add missing hover color to employee top nav

frontend/src/lib-components/molecules/CollapsibleSection.tsx
=> Add missing hover highlight to icon in CollapsibleSection

service/src/main/resources/db/migration/V199__invoice_row_cost_centers.sql
NULL = NULL -> NULL
NULL IS NOT DISTINCT FROM NULL -> TRUE
=> Fix migration when sub_cost_center is NULL

.circleci/config.yml, .circleci/template.yml, bin/ci-login-cloud, bin/ci-login-registry, compose/docker-compose.e2e-tests.yml, compose/e2e/playwright.Dockerfile
=> Build e2e separetely

frontend/src/employee-frontend/components/absences/AbsenceTable.tsx, frontend/src/employee-frontend/components/absences/Absences.tsx, frontend/src/employee-frontend/components/unit/TabCalendar.tsx, frontend/src/employee-frontend/types/absence.ts, frontend/src/lib-common/api-types/child/absence.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/AbsenceServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/domain/HelsinkiDateTime.kt
Show a montly total of reserved and attended hours for each child in unit absence table. A warning is shown if the attendance total is greated than reserved total.
=> EVAKA-4142 attendances and reservations in absence table

frontend/src/employee-frontend/components/common/LabelValueList.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> Add reservation/service/attendance times to legend in week view

frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/specs/5_employee/child-information-assistance-needs.spec.ts, frontend/src/e2e-test/specs/5_employee/child-information-placements.spec.ts, frontend/src/e2e-test/specs/5_employee/unit-application-process.spec.ts, frontend/src/e2e-test/specs/5_employee/unit-groups.spec.ts, frontend/src/employee-frontend/components/fee-decisions/generation/GeneratorButton.tsx, frontend/src/employee-frontend/components/reports/EndedPlacements.tsx, frontend/src/employee-frontend/components/reports/Occupancies.tsx, frontend/src/employee-frontend/components/reports/PresenceReport.tsx, frontend/src/employee-frontend/components/reports/StartingPlacements.tsx, frontend/src/employee-frontend/components/reports/VoucherServiceProviders.tsx, frontend/src/employee-frontend/components/vasu/VasuEditPage.tsx, frontend/src/employee-mobile-frontend/components/staff/StaffAttendanceEditor.tsx, frontend/src/lib-common/date-range.ts, frontend/src/lib-common/date.ts, frontend/src/lib-common/finite-date-range.ts, frontend/src/lib-common/local-date.ts
- Strictly define allowed date, time and datetime formats
- ~Separate ISO date formatting from human readable formatting~ Replace ISO formatting with `LocalDate`
- Separate time formatting from date formatting
=> Add types to date formatting functions

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueAreaReportTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt, service/src/integrationTest/resources/application-integration-test.yaml, service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
https://github.com/espoon-voltti/evaka/pull/1849 for voucher value decisions.
=> Add possibility to send voucher value decisions in advance

service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/db/DatabaseEnum.kt, service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt, service/src/main/resources/db/migration/V202__absence_type_enum.sql, service/src/main/resources/migrations.txt
=> Make absence.type an enum instead of text

frontend/src/citizen-frontend/header/DesktopNav.tsx, frontend/src/citizen-frontend/header/MobileNav.tsx
=> Hide Children from citizen navigation if feature is not enabled

.circleci/template.yml
=> Fix CI docker build retry

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorDifferIntegrationTest.kt
- Make sure invoice engine differ detects multiple changed invoices
=> Make a test to ensure diff reports multiple different invoices

frontend/src/employee-frontend/components/unit/unit-reservations/ReservationsTable.tsx
Change week calendar today highlight color to green.
Move top highlight from `th` to first `td`. Add bottom highlight to last row.
=> Change week calendar today highlight color to green

service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/AbsenceServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/domain/HelsinkiDateTime.kt
=> Fix edge case with reservations using daily service times

frontend/src/lib-common/api-types/child/common.ts
=> Use weekend irregular daily service times

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/NewInvoiceGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/NewDraftInvoiceGenerator.kt
=> Don't ignore unpaid fee decisions when computing operational day counts

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/NewInvoiceGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/NewDraftInvoiceGenerator.kt
=> Drop empty invoices if fee decision's total price is 0

.circleci/template.yml
=> Increase node memory limit in `yarn build` in CI

frontend/src/employee-frontend/App.tsx, frontend/src/employee-frontend/api/reports.ts, frontend/src/employee-frontend/components/Reports.tsx, frontend/src/employee-frontend/components/reports/InvoiceGeneratorDiff.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> A simple report to show the generated diff from InvoiceGeneratorDiff

.circleci/template.yml
=> Fix CI variable

service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DefaultDraftInvoiceGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
=> Make invoice generator configurable

keycloak/.dockerignore, keycloak/.gitignore, keycloak/Dockerfile, keycloak/evaka-logging/pom.xml, keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/EvakaLoggingEventListenerProvider.java, keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/EvakaLoggingEventListenerProviderFactory.java, keycloak/evaka-logging/src/main/resources/META-INF/services/org.keycloak.events.EventListenerProviderFactory, keycloak/evaka-logging/src/main/resources/META-INF/services/org.keycloak.events.EventListenerProviderFactory.license
Provides custom event logging handlers that can be configured to omit or hash fields.
=> Custom KeyCloak event logging handler

frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/dev-api/index.ts, frontend/src/e2e-test/dev-api/types.ts, frontend/src/e2e-test/pages/employee/units/unit-calendar-page.ts, frontend/src/e2e-test/pages/employee/units/unit.ts, frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts, frontend/src/employee-frontend/api/unit.ts, frontend/src/employee-frontend/components/unit/TabCalendar.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/ReservationModalSingleChild.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/ReservationsTable.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx, frontend/src/lib-common/api-types/reservations.ts, service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Add better support for overnight reservations.
=> EVAKA-4378 better ui support for days with two reservations

service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaClientIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaOrganizerChildrenIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUnitIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceIntegrationTest.kt
This is the base class for *all* full application tests, so it should be minimal and only contain stuff needed for the majority of tests.
=> Tidy up FullApplicationTest

service/owasp-suppressions.xml
We don't use persistent Tomcat sessions
=> Suppress CVE-2022-23181

frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> Generalize two Espoo specific i18n properties

frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
=> Use correct mocked date in reservation e2e test cases

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
=> Fix echa increase being applied multiple times

service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
=> Validate absence type in citizen's absence endpoint

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/NewInvoiceGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Invoices.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DefaultDraftInvoiceGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorDiffer.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/NewDraftInvoiceGenerator.kt
=> Invoicing for surplus contract days

frontend/src/citizen-frontend/calendar/CalendarPage.tsx, frontend/src/citizen-frontend/calendar/DayView.tsx, frontend/src/citizen-frontend/calendar/calendar-elements.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx, frontend/src/lib-common/api-types/reservations.ts, frontend/src/lib-common/generated/api-types/reservations.ts, frontend/src/lib-common/reservations.ts, frontend/src/lib-components/atoms/StatusIcon.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenControllerTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenQueriesTest.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
=> EVAKA-4142 citizen warnings when attendance differs from reservation

frontend/src/employee-frontend/components/invoice/InvoiceRowsSection.tsx, frontend/src/employee-mobile-frontend/components/attendances/AttendancePageWrapper.tsx, frontend/src/employee-mobile-frontend/components/common/GroupSelectorBar.tsx, frontend/src/lib-components/atoms/buttons/AsyncButton.tsx
=> Fix per-child row sum on invoice page

service/src/integrationTest/kotlin/fi/espoo/evaka/TestInvoiceProductProvider.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/EspooInvoiceProducts.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceProductProvider.kt
=> Add an invoice product for contract surplus days

frontend/src/employee-frontend/index.tsx
=> EVAKA-HOTFIX: Add tooltips back to occupancy charts

frontend/src/employee-frontend/api/child/assistance-actions.ts, frontend/src/employee-frontend/api/child/assistance-needs.ts, frontend/src/employee-frontend/components/child-information/AssistanceAction.tsx, frontend/src/employee-frontend/components/child-information/AssistanceNeed.tsx, frontend/src/employee-frontend/components/child-information/assistance-action/AssistanceActionForm.tsx, frontend/src/employee-frontend/components/child-information/assistance-action/AssistanceActionRow.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/AssistanceNeedForm.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/AssistanceNeedRow.tsx, frontend/src/employee-frontend/components/common/Toolbar.tsx, frontend/src/employee-frontend/types/child.ts, frontend/src/lib-common/generated/api-types/assistanceaction.ts, frontend/src/lib-common/generated/api-types/assistanceneed.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceAction.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionController.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeed.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
UI to respect permitted actions.
=> Add permitted actions support for assistance

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
=> Don't reset employee roles if ACLs have been updated recently

keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/EvakaLoggingEventListenerProvider.java, keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/EvakaLoggingEventListenerProviderFactory.java
=> Add identity to KeyCloak logging

frontend/src/citizen-frontend/children/PlacementTerminationForm.tsx, frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
=> Fix termination of PRESCHOOL_DAYCARE when terminating only the paid part

frontend/src/employee-frontend/api/child/backup-care.ts, frontend/src/employee-frontend/components/child-information/BackupCare.tsx, frontend/src/employee-frontend/components/child-information/backup-care/BackupCareForm.tsx, frontend/src/employee-frontend/components/child-information/backup-care/BackupCareRow.tsx, frontend/src/employee-frontend/state/child.tsx, frontend/src/employee-frontend/types/child.ts, frontend/src/employee-frontend/utils/roles.tsx, frontend/src/lib-common/generated/api-types/backupcare.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/backupcare/BackupCareIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCare.kt, service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareController.kt
https://github.com/espoon-voltti/evaka/pull/2110 for backup care.
=> Add permitted actions support for backup care

frontend/src/employee-frontend/components/unit/unit-reservations/ReservationsTable.tsx
=> Fix current day highlight in unit week calendar

keycloak/Dockerfile, keycloak/bin/entrypoint.sh, keycloak/docker-compose.yml, keycloak/evaka-logging/pom.xml, keycloak/evaka-review-profile/pom.xml
=> Update KeyCloak to 17 using legacy

frontend/src/employee-frontend/components/fee-decision-details/ChildSection.tsx
Exactly same label and value is in the previous item.
=> Fix duplicate care area in fee decision page

proxy/Dockerfile
=> Update proxy requirements

frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx, frontend/src/lib-components/atoms/buttons/AsyncButton.tsx, frontend/src/lib-components/molecules/modals/FormModal.tsx, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
Try to fix the root issue by avoiding double clicks (using `AsyncButton`) in placement update save button.
Fix the NPE to another exception by using the correct mapping functions.
=> Fix a NullPointerException, disallow double clicks

frontend/src/citizen-frontend/income-statements/ChildrenIncomeStatements.tsx, frontend/src/e2e-test/pages/citizen/citizen-child-income.ts, frontend/src/e2e-test/specs/0_citizen/citizen-child-income-statement.spec.ts, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
- No duplicate children if child has multiple placements 
- Indicate it If there is 0 children who need income statements
=> Evaka 4274 indicate no income statements needed

frontend/src/citizen-frontend/children/PlacementTerminationForm.tsx, frontend/src/lib-common/generated/api-types/placement.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanQueries.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementTermination.kt
=> Fix consequent daycareOnly placement terminations

frontend/src/e2e-test/browser.ts, frontend/src/e2e-test/pages/citizen/citizen-header.ts, frontend/src/e2e-test/specs/0_citizen/citizen-header-customization.spec.ts, frontend/src/e2e-test/tsconfig.json, frontend/src/e2e-test/utils/page.ts, frontend/src/lib-common/utils/helpers.ts, frontend/src/lib-customizations/citizen.tsx, frontend/src/lib-customizations/common.tsx, frontend/src/lib-customizations/employee.tsx, frontend/src/lib-customizations/employeeMobile.tsx, frontend/src/lib-customizations/tsconfig.json, frontend/src/lib-customizations/types.d.ts
=> Dynamic E2E customization overrides

service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
Seems like I missed one place in my `child_attendance` refactor.
=> Fix mobile unit stats query

frontend/src/citizen-frontend/App.tsx, frontend/src/citizen-frontend/LoginPage.tsx, frontend/src/citizen-frontend/applying/ApplyingRouter.tsx, frontend/src/citizen-frontend/header/DesktopNav.tsx, frontend/src/citizen-frontend/header/MobileNav.tsx, frontend/src/citizen-frontend/header/const.ts, frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts, frontend/src/e2e-test/specs/0_citizen/citizen-map.spec.ts, frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts, frontend/src/e2e-test/utils/user.ts, frontend/src/employee-frontend/components/login-page/Login.tsx, frontend/src/lib-components/atoms/buttons/LinkButton.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Add a login page for citizens and switch the login link in header to weak authentication from strong authentication.
=> EVAKA-4424 citizen login page

frontend/src/citizen-frontend/calendar/DayView.tsx, frontend/src/citizen-frontend/calendar/ReservationModal.tsx, frontend/src/citizen-frontend/calendar/api.ts, frontend/src/employee-frontend/components/unit/unit-reservations/ReservationModalSingleChild.tsx, frontend/src/lib-common/generated/api-types/reservations.ts, frontend/src/lib-common/reservations.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservableDaysCalculationUnitTest.kt, service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriod.kt, service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodQueries.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservableDays.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt, service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
=> EVAKA-4162 Handle holiday period deadlines in citizen's reservations

frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts
Fix e2e test broken by new login page.
=> EVAKA-4424 fix broken e2e test

frontend/src/citizen-frontend/api-client.ts
=> Send mocked time correctly in e2e tests

frontend/src/e2e-test/pages/employee/units/unit-calendar-page.ts, frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts, frontend/src/employee-frontend/api/absences.ts, frontend/src/employee-frontend/api/unit.ts, frontend/src/employee-frontend/components/applications/ApplicationActions.tsx, frontend/src/employee-frontend/components/common/EllipsisMenu.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/AbsenceDay.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/ReservationsTable.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/reservation-table-edit-state.ts, frontend/src/lib-common/api-types/reservations.ts, frontend/src/lib-common/generated/api-types/attendance.ts, frontend/src/lib-common/reservations.ts, frontend/src/lib-components/atoms/form/TimeInput.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/src/main/kotlin/fi/espoo/evaka/Audit.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/AbsenceController.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
Add option to edit reservations inline in employee week view. Also fix day highlight change that was lost in some rebase.
Does not include editing attendances since it's a lot more complicated because of multi-day attendances.
=> EVAKA-4377 reservations inline editing

frontend/src/citizen-frontend/App.tsx, frontend/src/citizen-frontend/header/EvakaLogo.tsx
- Make citizen page evaka logo link to home
- Remove requireAuth from ApplyingRouter
=> EVAKA-4424 login page improvements

evaka-base/Dockerfile
=> Update base image packages

service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizenIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodFixtures.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodQueries.kt
=> EVAKA-4162 Add server-side validation for adding free absences

keycloak/Dockerfile
=> Update KeyCloak packages

frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
Make individual invoice sending warning optional.
=> Optional invoice sending warning

service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClient.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/integration/InvoiceIntegrationClient.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
Since some invoice integrations support people without SSNs the logic should be in the integration client.
=> Move invoice manual sending logic to integration client

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx, frontend/src/citizen-frontend/calendar/DayView.tsx, frontend/src/citizen-frontend/calendar/HolidayModal.tsx, frontend/src/citizen-frontend/calendar/ReservationModal.tsx, frontend/src/citizen-frontend/header/DesktopNav.tsx, frontend/src/citizen-frontend/header/MobileNav.tsx, frontend/src/lib-common/names.ts
=> Format preferredName consistently, remove repetition

frontend/src/e2e-test/specs/5_employee/guardian-income-statements.spec.ts, frontend/src/employee-frontend/components/IncomeStatementPage.tsx
=> Return to correct url after mark as handled

frontend/src/employee-mobile-frontend/components/attendances/actions/MarkDeparted.tsx
Show warning in employee mobile if departure is marked on the same minute as arrival. Intended as a quick solution.
=> Display validation error on 0min attendance

frontend/src/citizen-frontend/Footer.tsx, frontend/src/lib-components/atoms/ExternalLink.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Tampere is going to use `ExternalLink` component.
=> Refactor footer to support links customization

service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
- Replace mutation with fold
- handle null guardian case
=> Tiny refactoring of PendingDecisionEmailService

frontend/src/citizen-frontend/header/DesktopNav.tsx, frontend/src/citizen-frontend/header/MobileNav.tsx, frontend/src/citizen-frontend/map/MapView.tsx, frontend/src/citizen-frontend/map/SearchSection.tsx
- Direct to citizen login page from login button
- Add button to navigate back to login screen from map
=> EVAKA citizen login button change

frontend/src/citizen-frontend/calendar/CalendarPage.tsx, frontend/src/citizen-frontend/calendar/holiday-modal/FreeHolidaySelector.tsx, frontend/src/citizen-frontend/calendar/holiday-modal/HolidayModal.tsx, frontend/src/citizen-frontend/calendar/holiday-modal/HolidaySelector.tsx, service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt
=> Validate holiday date range input

frontend/src/citizen-frontend/calendar/calendar-elements.tsx, frontend/src/e2e-test/pages/citizen/citizen-calendar.ts, frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts, frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Indicate free absence in citizen's reservation calendar

service/build.gradle.kts, service/buildSrc/build.gradle.kts
=> Upgrade Kotlin in buildSrc + ktlint gradle dependency config

frontend/src/employee-frontend/components/person-profile/income/missingIncomePeriodUtils.spec.ts, frontend/src/employee-frontend/components/person-profile/income/missingIncomePeriodUtils.ts
=> Avoid trying to create date ranges starting after they end

service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
The partner's children query was missing a date range check.
=> Fix child placement periods query

service/src/main/kotlin/fi/espoo/evaka/shared/utils/FormValidation.kt
=> Use same phone validation regex in backend as in frontend

frontend/src/employee-frontend/components/unit/tab-groups/notes/ChildDailyNoteForm.tsx
=> Fix state update on an unmounted ChildDailyNoteForm component

service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenQueriesTest.kt, service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Also remove duplicated reservation code
=> EVAKA-4162 Prevent removal of FREE_ABSENCEs

frontend/src/e2e-test/pages/employee/holiday-periods.ts, frontend/src/e2e-test/specs/5_employee/holiday-period.spec.ts, frontend/src/employee-frontend/components/holiday-periods/FixedPeriodQuestionnaireForm.tsx, frontend/src/employee-frontend/components/holiday-periods/HolidayPeriodForm.tsx, frontend/src/employee-frontend/components/holiday-periods/HolidayPeriodsPage.tsx
=> Add e2e test for questionnaire CRUD

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
=> Fix voucher value report annulled decisions refund query

frontend/src/citizen-frontend/calendar/CalendarPage.tsx, frontend/src/citizen-frontend/calendar/HolidayPeriodBanner.tsx, frontend/src/citizen-frontend/calendar/holiday-modal/FixedPeriodSelectionModal.tsx, frontend/src/citizen-frontend/holiday-periods/api.ts, frontend/src/citizen-frontend/holiday-periods/state.tsx, frontend/src/e2e-test/pages/citizen/citizen-calendar.ts, frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts, frontend/src/employee-frontend/components/holiday-periods/FixedPeriodQuestionnaireForm.tsx, frontend/src/lib-common/api-types/holiday-period.ts, frontend/src/lib-common/generated/api-types/holidayperiod.ts, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizenIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayQuestionnaireQueries.kt
=> Holiday questionnaire: Implement the continuous placement condition

frontend/src/citizen-frontend/calendar/ActionPickerModal.tsx, frontend/src/citizen-frontend/calendar/CalendarGridView.tsx, frontend/src/citizen-frontend/calendar/CalendarPage.tsx, frontend/src/citizen-frontend/calendar/HolidayPeriodBanner.tsx, frontend/src/citizen-frontend/calendar/ReportHolidayLabel.tsx, frontend/src/citizen-frontend/holiday-periods/state.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Implement questionnaire strong auth requirement and indication

frontend/src/citizen-frontend/Footer.tsx, frontend/src/citizen-frontend/applications/editor/EditorSection.tsx, frontend/src/citizen-frontend/index.css, frontend/src/lib-components/layout/Container.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Fixes to UI bugs introduced in https://github.com/espoon-voltti/evaka/pull/2191
- Fix collapsible container title alignment
- Remove a:hover styles from citizen index.css
=> EVAKA FIX ui bugs from accessibility changes

frontend/src/citizen-frontend/LoginPage.tsx, frontend/src/citizen-frontend/header/DesktopNav.tsx, frontend/src/citizen-frontend/header/Header.tsx, frontend/src/citizen-frontend/header/MobileNav.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- Update texts
- Remove login button
=> EVAKA-4438 tweak login page

frontend/src/citizen-frontend/calendar/CalendarPage.tsx, frontend/src/citizen-frontend/calendar/DayView.tsx, frontend/src/citizen-frontend/calendar/holiday-modal/FixedPeriodSelectionModal.tsx, frontend/src/e2e-test/pages/citizen/citizen-calendar.ts, frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts, frontend/src/e2e-test/utils/page.ts
=> Add more e2e tests for citizen holiday modal

frontend/src/citizen-frontend/income-statements/ChildrenIncomeStatements.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- In citizen child income list, make reporting child income optional
=> Make child income optional for citizen

frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> Requested info text change

service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt
=> Fix user type in holiday questionnaire

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/PresenceReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/PresenceReport.kt
=> Count child as present if not absent from all categories

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/MissingServiceNeedReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/MissingServiceNeedReport.kt
- Show missing service needs in service voucher units, grouping the service voucher units as their own care area
=> Show service voucher units in the missing service needs report

frontend/package.json, frontend/yarn.lock
No breaking changes. Fixes vulnerability in follow-redirects.
=> Upgrade axios

.circleci/template.yml, compose/db/Dockerfile, keycloak/docker-compose.yml
=> Use Postgres 14 locally

evaka-base/Dockerfile
=> Update base image

frontend/src/employee-frontend/components/unit/TabAttendances.tsx
=> EVAKA-4455 Swap positions of the titles on the attendances tab

frontend/src/citizen-frontend/LoginPage.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> EVAKA-FIX: login page heading texts

frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Login page text change

frontend/src/citizen-frontend/App.tsx, frontend/src/citizen-frontend/header/DesktopNav.tsx, frontend/src/citizen-frontend/header/MobileNav.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts
=> Remove placement termination feature flag

service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt
For Tampere both fee and voucher value decisions should behave
exactly the same on how to display validity end. Copied the logic
from fee decision so we can use it in the voucher value template.
=> Add pdf variable for voucher value decision

frontend/src/employee-frontend/api/staff-attendance.ts, frontend/src/employee-frontend/components/absences/Absences.tsx, frontend/src/employee-frontend/components/unit/TabAttendances.tsx, frontend/src/employee-frontend/components/unit/tab-attendances/GroupSelector.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/ChildReservationsTable.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/attendance-elements.tsx, frontend/src/employee-mobile-frontend/api/attendances.ts, frontend/src/employee-mobile-frontend/api/realtimeStaffAttendances.ts, frontend/src/employee-mobile-frontend/components/attendances/actions/MarkDeparted.tsx, frontend/src/employee-mobile-frontend/state/staff-attendance.tsx, frontend/src/lib-common/generated/api-types/attendance.ts, frontend/src/lib-components/layout/Table.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
=> EVAKA-4455 View staff attendances

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
When checking whether a child's value decision should be annulled or ended, leave out placements that do not generate voucher value decisions from the child's active placements. Previously a child switching into preschool wouldn't have their active decision automatically ended or annulled.
=> End value decisions when child placements do not generate new value decisions

frontend/package.json, frontend/src/lib-common/utils/useIntersectionObserver.ts, frontend/yarn.lock
=> Add polyfill for IntersectionObserver

keycloak/Dockerfile, keycloak/evaka-logging/pom.xml, keycloak/evaka-review-profile/pom.xml
17.0.1
https://github.com/keycloak/keycloak/issues/9539
=> Upgrade KeyCloak

frontend/src/lib-common/theme.ts, frontend/src/lib-customizations/common.tsx
=> Add absence colors to theme

frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx, frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancySingleDay.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/src/main/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancy.kt
=> EVAKA-4455 New realtime attendance graph

evaka-bom/build.gradle.kts, frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
=> Upgrade jackson, fix broken e2e tests

frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> Display title for y-axis in realtime attendance graph

frontend/src/employee-frontend/components/unit/TabAttendances.tsx
Always render week view when `'no-group'` or `'staff'` is selected, hiding week/month selection.
=> Improve group selection UX in attendance table

frontend/src/employee-frontend/api/staff-attendance.ts, frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/attendance-elements.tsx, frontend/src/lib-common/generated/action.d.ts, frontend/src/lib-common/generated/api-types/attendance.ts, frontend/src/lib-common/local-date.ts, service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Can only edit existing attendances, cannot create new ones. Adding of new ones will be implemented when adding the employee table to the group views.
=> EVAKA-4455 Implement realtime staff attendance editing

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts
=> Add a feature flag for showing PLANNED_ABSENCE for citizens with children in shift care

service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
=> Correctly filter realtime staff attendances by unit

frontend/src/employee-frontend/components/absences/AbsenceTable.tsx
=> Hide staff attendance in month view when using realtime staff attendance

evaka-bom/build.gradle.kts
This fixes a security vulnerability
=> Upgrade postgres jdbc driver

frontend/src/e2e-test/specs/5_employee/fridge-head-information.spec.ts, frontend/src/employee-frontend/components/person-profile/PersonFamilyOverview.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> Show child income on family overview

service/src/main/resources/db/migration/V221__message_account_evaka_user_id.sql
=> HOTFIX: Fix a faulty migration

apigw/package.json, apigw/yarn.lock
=> Upgrade node-forge

evaka-bom/build.gradle.kts
This includes Spring 5.3.18, which contains a critical security fix
=> Upgrade to Spring Boot 2.6.6

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
=> Give unit supervisors access to applications with assistance need

service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
=> Fix a time-based e2e test failure

service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AccessControlTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/ApplicationAccessControlTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AttachmentAccessControlTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/ChildAccessControlTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/IsCitizenTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/StaticActionRuleTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/UnitAccessControlTest.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pairing/MobileDeviceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/auth/Acl.kt, service/src/main/kotlin/fi/espoo/evaka/shared/auth/AuthenticatedUser.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsMobile.kt, service/src/main/resources/db/migration/R__acl_views.sql
=> Access Control DSL - part 4

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt, service/src/main/resources/db/migration/V221__message_recipient_foreign_key_on_delete_cascade.sql, service/src/main/resources/migrations.txt
- Person with sent messages is not cleaned up
- Person with received messages can be cleaned up
- Increase the SQL statement timeout in inactive person cleanup
=> Inactive people cleanup fixes

frontend/src/e2e-test/pages/employee/child-information.ts, frontend/src/e2e-test/specs/5_employee/child-information.spec.ts, frontend/src/employee-frontend/components/child-information/FamilyContacts.tsx
Ensure family contact info can be edited also after setting them to empty strings.
=> EVAKA-FIX: make family contacts editable

service/src/main/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancy.kt
=> Fix placement join in realtime occupancy query

service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt, service/src/main/kotlin/fi/espoo/evaka/reports/ChildAgeLanguageReport.kt, service/src/main/resources/db/migration/R__primary_units_view.sql
`date_of_birth` is not a nullable column
=> Remove unnecessary null checks

frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts, frontend/src/e2e-test/specs/5_employee/units.spec.ts, frontend/src/employee-frontend/state/unit.tsx
=> Default to 1 day in unit view filters

frontend/src/employee-frontend/state/invoicing-ui.tsx
=> Remove the default start date from finance filters

frontend/src/lib-common/generated/api-types/shared.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationUpkeepIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/JobSchedule.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
=> Clean up reservations that are outside placements

frontend/src/employee-frontend/components/unit/unit-reservations/ChildReservationsTable.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/attendance-elements.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> EVAKA-4455 Change the copy in the headers on the staff attendance table

frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
- Remove wrong size limit from allergies
- Make the UI wider
=> Remove wrong allergies length limit and widen the UI field

frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/attendance-elements.tsx
=> EVAKA-4455 Add staff attendance table to group views

frontend/src/citizen-frontend/calendar/CalendarPage.tsx
Push most modal states to the URL, so that using the back button closes the modals or goes to the previous modal state.
=> Enhance back button UX in citizen calendar

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
=> Ensure that every fridge family targetted update generates a new fee decision

service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt, service/src/main/kotlin/fi/espoo/evaka/application/Application.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt, service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt, service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlan.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/Timeline.kt, service/src/main/kotlin/fi/espoo/evaka/units/UnitsView.kt
=> Fix various placement plan occupancy calculation bugs

frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx, frontend/src/lib-common/generated/api-types/attendance.ts, service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
The staff attendance table includes the attendance times of all employees assigned to a group.
=> EVAKA-4455 Allow normal staff to see the staff attendance in groups

service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
Change the word `servicehänvisning` to `servicehandledning` and update Swedish service counselling's PO box.
=> EVAKA-4453 update Espoo Swedish email texts

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/MissingServiceNeedReportTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/StartingPlacementsReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/StartingPlacementsReport.kt
- Add service voucher unit children as own care area to starting children report
=> Add service voucher unit children to starting children report

service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationQueriesSmokeTest.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
=> Application search technical improvements

service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservableDaysCalculationUnitTest.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservableDays.kt
=> Move last reservable date to end of August

frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
- Add group acl drop downs for unit supervisors and special education teachers
- Include all group acl employees in realtime staff attendances
=> EVAKA-4487 extend group staff acl

frontend/src/citizen-frontend/LoginPage.tsx, frontend/src/lib-components/layout/Container.tsx, frontend/src/lib-components/layout/responsive-layout.tsx, frontend/src/lib-components/typography.ts, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- Fix `H2` style on mobile
- Fix `ContentArea` spacings on mobile and desktop
- Make the citizen login page look better on mobile
=> Style fixes in general, and to login page in particular

frontend/src/employee-frontend/components/child-information/PedagogicalDocuments.tsx, frontend/src/lib-customizations/espoo/employee.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> EVAKA-4456 pedagogical documentation info texts

compose/db-integration-test/Dockerfile, compose/db-integration-test/postgresql.conf
=> Try to speed up evaka_it database

frontend/src/employee-frontend/api/staff-attendance.ts, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx, frontend/src/lib-common/generated/api-types/attendance.ts, service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
Also includes a commit for optimizing fetching of groups for employees.
Might be easier to review by commit than all at once.
=> EVAKA-4455 Allow marking new staff attendances in the staff attendance table on group views

frontend/src/employee-frontend/components/applications/ActionBar.tsx, frontend/src/employee-frontend/components/applications/ApplicationsFilters.tsx, frontend/src/employee-frontend/components/applications/ApplicationsList.tsx, frontend/src/employee-frontend/components/applications/ApplicationsPage.tsx, frontend/src/employee-frontend/components/common/Filters.tsx, frontend/src/employee-frontend/state/application-ui.tsx
Debounce application search filters:
- Area
=> Debounce application filters

frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
=> Allow vtj refresh to service workers

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceUpkeepIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
=> Automatically end attendances if placement has ended

frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> Add proper text for mobile devices in "absence modified by" labels

frontend/src/lib-components/typography.ts
=> Change H1 font-size to 32px

frontend/src/employee-frontend/components/applications/ApplicationsFilters.tsx
=> Fix broken application filter

frontend/src/citizen-frontend/header/DesktopNav.tsx, frontend/src/citizen-frontend/header/MobileNav.tsx, frontend/src/e2e-test/specs/0_citizen/citizen-header.spec.ts, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Change citizen applying subnav title back to "Hakemukset"

frontend/src/employee-frontend/components/person-profile/PersonInvoiceCorrections.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts
The feature is ready for production.
=> EVAKA-4391 remove invoice corrections feature flag

frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponseList.tsx, frontend/src/citizen-frontend/decisions/decisions-page/ApplicationDecisionsBlock.tsx, frontend/src/citizen-frontend/decisions/shared.tsx
Order application's decisions by date instead of type.
Also use non-mutating lodash `sortBy` instead of `array.sort()`
=> Order decisions by date instead of type

frontend/README.md, frontend/package.json, frontend/src/e2e-test/browser.ts
No need for `--testTimeout` anymore :smile:
=> Fix automatic jest timeout configuration

service/src/main/kotlin/fi/espoo/evaka/application/Application.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
=> Fix passing of type to application search query

frontend/src/lib-components/atoms/buttons/Button.tsx, frontend/src/lib-components/atoms/buttons/InlineButton.tsx, frontend/src/lib-components/atoms/buttons/LinkButton.tsx, frontend/src/lib-components/atoms/buttons/button-commons.tsx
=> Change border-radius of all buttons from 2px to 4px

frontend/src/citizen-frontend/App.tsx, frontend/src/citizen-frontend/messages/ThreadList.tsx, frontend/src/citizen-frontend/messages/state.tsx, frontend/src/lib-components/molecules/ThreadListItem.tsx, service/src/main/kotlin/fi/espoo/evaka/emailclient/MockEmailClient.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- Make message thread list items buttons for better accessibility
- Save citizen selected message thread in url for better mobile navigation experience
- Add direct link to message thread in notification email
=> EVAKA citizen messages ux improvements

frontend/src/citizen-frontend/applying/ApplyingRouter.tsx, frontend/src/citizen-frontend/map/UnitListItem.tsx
=> EVAKA-FIX: better accessible map page

frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> Fix typo in decision type i18n

frontend/src/lib-common/local-date.ts
=> Report invalid dates to Sentry

service/src/main/kotlin/fi/espoo/evaka/reports/patu/EspooPatuIntegrationClient.kt
=> Set ACCEPT header

service/src/main/kotlin/fi/espoo/evaka/reports/patu/EspooPatuIntegrationClient.kt
=> Add debug printout

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/IncomeIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/AuditQueries.kt, service/src/main/resources/db/migration/V228__evaka_user_lastname_firstname.sql, service/src/main/resources/dev-data/employees.sql, service/src/main/resources/migrations.txt
=> Switch all evaka_user names to last_name first_name

apigw/src/shared/routes/auth/saml/index.ts
=> Fix browser back after login

frontend/src/employee-frontend/components/Header.tsx
=> Add focus style to employee-frontend header

service/src/main/kotlin/fi/espoo/evaka/reports/patu/EspooPatuIntegrationClient.kt
=> Remove unnecessary logging

frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> Show a helpful message if there's no data for the selected day

frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx, frontend/src/lib-common/local-date.spec.ts, frontend/src/lib-common/local-date.ts
=> Fix frontend date validation + tiny refactoring

apigw/src/enduser/publicRoutes.ts, apigw/src/internal/app.ts
=> Add /version endpoint to api gateways

frontend/src/citizen-frontend/calendar/ReservationModal.tsx, frontend/src/lib-components/atoms/form/TimeInput.tsx, frontend/src/lib-components/molecules/modals/BaseModal.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- copy changes
- more clear layout
- all modals now have their contents left aligned instead of centered
=> UX improvements for the reservation dialog

frontend/src/employee-frontend/components/unit/TabAttendances.tsx
=> Default to week view when realtime staff attendances are enabled

frontend/src/citizen-frontend/applying/ApplyingRouter.tsx, frontend/src/citizen-frontend/header/DesktopNav.tsx
Move lock from top level applications nav link to sub nav links.
Also bring back sub nav for anonymous users redirecting them to map tab.
=> Move lock from top level applications nav link to sub nav links

frontend/src/employee-frontend/api/staff-attendance.ts, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/attendance-elements.tsx, frontend/src/lib-common/generated/api-types/attendance.ts, frontend/src/lib-components/atoms/form/TimeInput.tsx, service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
For overnight attendances, we create one attendance per day. The first day ends at 23:59 and the following day starts at 00:00. 
Rendered as:
When editing:
=> EVAKA-4455 overnight staff attendances

frontend/src/citizen-frontend/AccessibilityStatement.tsx, frontend/src/citizen-frontend/App.tsx, frontend/src/citizen-frontend/Footer.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Still awaiting translations for sv and en, show the fi text in the meanwhile.
=> Add accessibility statement

apigw/Dockerfile, evaka-base/Dockerfile, keycloak/Dockerfile
=> Update container packages

frontend/src/citizen-frontend/calendar/CalendarPage.tsx, frontend/src/citizen-frontend/calendar/HolidayPeriodCta.tsx, frontend/src/e2e-test/pages/citizen/citizen-calendar.ts, frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts, frontend/src/lib-components/molecules/Toast.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- Clicking the holiday notification/toast will open the holiday questionnaire.
- The copy for the holiday questionnaire button was changed to reflect the copy in the notification
=> Holiday cta ux

evaka-bom/build.gradle.kts, service/buildSrc/src/main/kotlin/Version.kt
=> Upgrade spring boot to 2.6.7 (solves CVE-2022-22968)

frontend/src/employee-frontend/components/unit/TabWaitingConfirmation.tsx
Date range shouldn't ignore daycare period
=> EVAKA-FIX show complete placement plan date range

evaka-bom/build.gradle.kts, frontend/src/employee-frontend/api/applications.ts, frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx, frontend/src/employee-frontend/types/person.ts, frontend/src/lib-common/generated/api-types/pis.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, service/buildSrc/src/main/kotlin/Version.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/ParentshipDAOIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
- Show vtj update timestamp on person profile page
=> Show vtj update timestamp on person profile

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
=> Allow users to see child images with weak login

service/Dockerfile
=> Update service packages

frontend/src/lib-common/local-date.ts
This is no longer needed since we found the bug
=> Remove invalid date Sentry reporting

frontend/src/e2e-test/pages/employee/guardian-information.ts, frontend/src/e2e-test/specs/5_employee/income.spec.ts, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/IncomeController.kt
Delete attachments before deleting income
=> EVAKA-FIX delete income with attachments

frontend/src/citizen-frontend/localization/state.tsx
Sv is not currently supported in Tampere.
=> Fix citizen default language validation

frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/ChartTooltip.tsx, frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> EVAKA-4406 Add child headcount to the occupancy chart tooltip

keycloak/Dockerfile, keycloak/evaka-logging/pom.xml, keycloak/evaka-review-profile/pom.xml
=> Keycloak 18

service/owasp-suppressions.xml
=> Add suppression for owasp misidentification

frontend/src/employee-mobile-frontend/components/UnitList.tsx, frontend/src/lib-common/generated/api-types/attendance.ts, frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts, service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
- Refactor the unit list view in the employee mobile frontend to look like the designs
- Add the current unit utilization to the info shown
=> EVAKA-4406 Add utilization to info in units list

frontend/src/e2e-test/pages/admin/application-workbench-page.ts, frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts
=> Fix flaky E2E test: "Placement proposal flow"

frontend/src/e2e-test/pages/employee/finance/finance-page.ts, frontend/src/e2e-test/specs/4_finance/invoices.spec.ts
=> Flaky test fixes

service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
=> Fix div by zero

frontend/src/citizen-frontend/calendar/CalendarPage.tsx, frontend/src/citizen-frontend/calendar/ReservationModal.tsx
=> Use first empty reservable date as default on reservation modal

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
The report didn't work correctly when the `valid_to` date of a decision was moved back to an earlier month, if that month had already been freezed.
Fixing this involved changing a bit how the report generating SQL query works. It now explicitly checks that it's refunding/correcting those months that have changed, and explicitly adds newly added decisions as corrections.
This also has the effect that some unneeded refunds/corrections are not made at all (see the test `when one of part month decisions is annulled it is refunded correctly`).
=> Fix a bug in voucher value report

service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueriesTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueAreaReportTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
=> Feature to use daycare finance handler always

frontend/src/citizen-frontend/Footer.tsx
=> TREV-483 fix footer link layout with under 1024px screens

frontend/src/employee-frontend/components/reports/VoucherServiceProviderUnit.tsx
- Last name first on voucher value report unit UI and report
=> Lastname first

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
The new test documents what happens if there's a force majeure absence and long sick leave.
=> Add an invoicing test case

service/src/main/kotlin/fi/espoo/evaka/reports/PlacementSketchingReport.kt
=> Sort placement skectching report also by child name

service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt
=> Fix literal "null" appearing in message notifications

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
=> HOTFIX: Fix invoice generation with a custom daily fee divisor and a short month

apigw/generate-jwts.ts, apigw/src/shared/auth/index.ts, apigw/src/shared/auth/jwt.ts, service/src/main/kotlin/fi/espoo/evaka/shared/auth/AuthenticatedUser.kt, service/src/main/kotlin/fi/espoo/evaka/shared/auth/AuthenticatedUserJsonDeserializer.kt, service/src/main/kotlin/fi/espoo/evaka/shared/auth/AuthenticatedUserJsonSerializer.kt, service/src/main/kotlin/fi/espoo/evaka/shared/auth/JwtTokens.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/HttpFilterConfig.kt
=> Add integration user type for /integration paths

frontend/src/employee-frontend/components/reports/Raw.tsx
=> Fix raw report link

service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
=> Log employee global roles in login audit event

service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
IN + bindList writes all the parameters literally in the generated SQL, which is usually not the best way to do things
=> Replace IN + bindList with ANY + normal bind

evaka-bom/build.gradle.kts
=> Upgrade a vulnerable dependency

frontend/src/e2e-test/dev-api/data-init.ts, frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/dev-api/index.ts, frontend/src/e2e-test/dev-api/types.ts, frontend/src/e2e-test/pages/employee/guardian-information.ts, frontend/src/e2e-test/specs/4_finance/person-finance-decisions.spec.ts, frontend/src/e2e-test/utils/page.ts, frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx
=> EVAKA-FIX add e2e test for retroactive value decision generation

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
The daily refund price was calculated incorrectly if the number of operational days in a month was less then the overridden daily fee divisor.
=> Calculate the daily price correctly with short months

frontend/src/employee-frontend/api/auth.ts, frontend/src/employee-mobile-frontend/api/auth.ts
=> Report user as logged out if the wrong session is used

frontend/src/lib-components/typography.ts
=> Lower h2 font size on mobile

service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
=> Add missing bind argument

frontend/src/employee-frontend/components/invoice/InvoiceRowsSection.tsx, frontend/src/lib-common/generated/api-types/invoicing.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/Helpers.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Invoices.kt, service/src/test/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClientTest.kt
Add the new field to InvoiceRowDetailed and fetch the value from the DB
Oulu and Turku need this information for their invoicing
=> Add daycare type to InvoiceRowDetailed objects

.circleci/template.yml
=> Select cluster in CI

frontend/src/citizen-frontend/header/DesktopNav.tsx
=> Add hover style to citizen header

frontend/src/lib-components/employee/messages/MessageEditor.tsx
=> Don't limit dropdown width in non-expanded state

service/owasp-suppressions.xml
It's an old CVE, not relevant for us, and just happens to have been updated yesterday.
=> Suppress CVE-2016-1000027

frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
=> Text change

proxy/Dockerfile
=> Update proxy packages

frontend/src/citizen-frontend/header/DesktopNav.tsx, frontend/src/citizen-frontend/header/MobileNav.tsx, frontend/src/citizen-frontend/messages/MessageComponents.tsx, frontend/src/citizen-frontend/messages/MessageEditor.tsx, frontend/src/citizen-frontend/messages/MessagesPage.tsx, frontend/src/citizen-frontend/messages/ThreadList.tsx, frontend/src/citizen-frontend/messages/ThreadView.tsx, frontend/src/lib-components/atoms/buttons/InlineButton.tsx, frontend/src/lib-components/atoms/buttons/ReturnButton.tsx, frontend/src/lib-components/atoms/form/MultiSelect.tsx, frontend/src/lib-components/molecules/MessageReplyEditor.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Add bunch of accessibility and layout fixes to citizen's message page
=> EVAKA-FIX messaging accessibility tweaks

keycloak/README.md
=> Update KeyCloak development instructions

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
=> Pass a Database.Read handle to InvoiceGenerationLogicChooser

evaka-bom/build.gradle.kts, service/buildSrc/src/main/kotlin/Version.kt, service/owasp-suppressions.xml
=> Fix OWASP with one upgrade and one suppression

.circleci/template.yml, frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts, frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
- fix flaky test
- disable CI owasp check as it is borked
=> Fix flaky test (failed because child ACL is placement end + 1month)

frontend/src/e2e-test/specs/4_finance/income-staments.spec.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
=> EVAKA-FIX: income statement search order by last name

frontend/src/lib-common/generated/api-types/reports.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ReportSmokeTests.kt, service/src/main/kotlin/fi/espoo/evaka/reports/FamilyContactReport.kt
=> Fix null propagation in family contact report

service/src/integrationTest/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentNotificationServiceIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AccessControlTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/UnitAccessControlTest.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/auth/UserRole.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/PilotFeature.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/ActionRule.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/ActionRuleMapping.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGlobalRole.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsEmployee.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsMobile.kt, service/src/main/resources/db/migration/R__acl_views.sql
=> Add support for unit feature flags to HasUnitRole/HasGroupRole action rules

apigw/package.json, apigw/src/internal/app.ts, apigw/src/shared/auth/index.ts, apigw/src/shared/config.ts, apigw/src/shared/service-client.ts, apigw/yarn.lock
https://github.com/espoon-voltti/evaka/commit/7208284bc7085235b59e5fd28a9079b7a98aff38 support for apigw with basic auth.
=> Add apigw basic auth support for integration paths

frontend/src/employee-mobile-frontend/api/auth.ts
=> Report invalid user types in mobile frontend

frontend/src/employee-frontend/api/reports.ts, frontend/src/employee-frontend/components/reports/Occupancies.tsx, frontend/src/lib-common/generated/api-types/reports.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt, service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt, service/src/main/kotlin/fi/espoo/evaka/reports/OccupancyReport.kt
- adds provider type filter
- adds all areas filter (also adds area column to report)
- updates filters order (area before types)
=> Occupancy report improvements part1

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
The surplus day increases no longer affect the refunded price.
=> Fix daily refunds on invoices with surplus day increases

.circleci/template.yml
=> Re-enable OWASP check

frontend/src/e2e-test/pages/admin/application-workbench-page.ts, frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts, frontend/src/employee-frontend/components/applications/ApplicationsList.tsx, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
Handle both placement proposal rejection statuses
=> EVAKA-FIX: handle both placement proposal rejections

frontend/src/e2e-test/specs/6_mobile/child-attendances.spec.ts, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
Use intersection of placement and group placement dates
=> EVAKA-FIX: avoid child attending to many groups

service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt
=> Update inactive people cleanup timeout

frontend/src/employee-mobile-frontend/components/staff-attendance/MarkExternalStaffMemberArrivalPage.tsx, frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts
Give a hint that the name of the employee should be written lastname firstname to avoid using both ways
=> Give a hint how the name should be written

service/src/main/resources/WEB-INF/templates/fee-decision/decision_sv.properties
The missing translation caused that particular text to be in Finnish on Swedish decisions.
=> Add missing Swedish fee decision translation key

service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
=> Adjust sent extended compulsory education date ranges to fit Koski requirements

frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Add accessibility statement translations

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionsIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
=> Fix creating empty invoices when person has only uninvoiceable refunds

frontend/src/e2e-test/dev-api/index.ts, frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts, frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
This PR only adds tests for editing in the 'staff' view. Group views coming later incl. editing and adding new entries.
=> EVAKA-4406 Add E2E tests for editing realtime staff attendances

frontend/src/lib-common/helsinki-date-time.spec.ts, frontend/src/lib-common/helsinki-date-time.ts, frontend/src/lib-common/json.d.ts, frontend/src/lib-common/local-date.ts, frontend/src/lib-common/local-time.spec.ts, frontend/src/lib-common/local-time.ts
These types are not used anywhere at the moment, but can be taken into use one place at a time.
=> Add rough MVP of frontend LocalTime/HelsinkiDateTime

frontend/src/employee-frontend/api/unit.ts, frontend/src/employee-frontend/components/unit/unit-details/CreateUnitPage.tsx, frontend/src/employee-frontend/components/unit/unit-details/UnitDetailsPage.tsx, frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx, frontend/src/employee-frontend/types/unit.ts, frontend/src/lib-common/generated/api-types/daycare.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/DaycareEditIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/resources/db/migration/V239__daycare_extra_fields.sql, service/src/main/resources/migrations.txt
=> Add unit fields: business id, iban, provider id

service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
Previously we adjusted extended compulsory education date range based on disability date ranges, but it turns out the former also affects the latter.
=> Adjust data even more based on Koski rules

frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts, frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts, frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
=> Fix realtime staff attendance queries not including Sundays

service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiClient.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiQueries.kt, service/src/main/kotlin/fi/espoo/evaka/koski/Oppija.kt
Makes the Koski preparatory education confirmation municipality the one configured.
=> Make Koski confirmation municipality configurable

service/src/main/resources/WEB-INF/templates/preschool/decision_sv.properties, service/src/main/resources/WEB-INF/templates/shared/daycare-correction.html, service/src/main/resources/WEB-INF/templates/shared/daycare-correction.properties
Update the Swedish preschool decision address along with a new note below the postal address as specified.
=> Update Swedish preschool decision address

service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
Staff member may be in unit without specific group acl.
Related to https://github.com/espoon-voltti/evaka/pull/2521
=> Fix attendance present

service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt
=> Fix stack overflow

service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceClientIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModifications.kt, service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
=> Use default vtj update in case we cannot patch the vtj mutp changes in

frontend/src/e2e-test/pages/mobile/staff-page.ts, frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts, frontend/src/employee-mobile-frontend/api/realtimeStaffAttendances.ts, frontend/src/employee-mobile-frontend/components/staff-attendance/StaffMarkArrivedPage.tsx, frontend/src/employee-mobile-frontend/components/staff-attendance/StaffMarkDepartedPage.tsx, frontend/src/employee-mobile-frontend/components/staff-attendance/StaffMemberPage.tsx, frontend/src/lib-common/generated/api-types/attendance.ts, frontend/src/lib-components/atoms/dropdowns/Select.tsx, frontend/src/lib-components/atoms/form/TimeInput.tsx, frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
Show employee planned attendance in mobile and add support for multiple staff attendances with different types.
=> EVAKA-4407 staff attendance plans in mobile

frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
=> Fix assistance need decision date pickers

frontend/src/citizen-frontend/calendar/ReservationModal.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Do not break if there are no reservable days

frontend/src/e2e-test/pages/employee/assistance-need-decision/assistance-need-decision-edit-page.ts, frontend/src/e2e-test/specs/5_employee/assistance-need-decision.spec.ts, frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionEditPage.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/common.tsx, frontend/src/lib-components/atoms/Chip.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
=> EVAKA-4469 Add status header to the top-right of assistance need decision editor

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
(Again) fix a flaky test for next year
=> Fix flaky test for now

frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Fix translation

frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Citizen vasu swedish translations

frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts, frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts, frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx
=> Add more realtime staff attendance E2E tests

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
=> Fix reservations not showing in employee mobile for backup care children

frontend/src/employee-mobile-frontend/components/attendances/ChildList.tsx, frontend/src/employee-mobile-frontend/components/attendances/child-info/AttendanceChildPage.tsx, frontend/src/lib-common/generated/api-types/attendance.ts, frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
The query left out children backup care without an active group placement in original unit.
=> Fix child attendances query used in mobile

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileUnitControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
=> Handle backup care children in mobile unit info data

service/owasp-suppressions.xml
=> Surpress CVE-2022-34305

frontend/src/e2e-test/specs/5_employee/assistance-need-decision.spec.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
=> EVAKA-4569 Update assistance need decision texts

frontend/src/lib-common/local-date.spec.ts, frontend/src/lib-common/local-date.ts, frontend/src/lib-components/molecules/date-picker/DatePicker.tsx, frontend/src/lib-components/molecules/date-picker/DateRangePicker.tsx
=> Fix some LocalDate-related bugs

service/src/integrationTest/kotlin/fi/espoo/evaka/FixtureBuilder.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
=> Async job to terminate open staff attendances

frontend/src/e2e-test/pages/employee/reports.ts, frontend/src/e2e-test/specs/5_employee/assistance-need-decisions-report.spec.ts, frontend/src/employee-frontend/components/child-information/AssistanceNeedDecisionSection.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionReadOnly.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/api.ts, frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReportDecision.tsx, frontend/src/lib-common/generated/action.d.ts, frontend/src/lib-common/generated/api-types/assistanceneed.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/Audit.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- Adds support for approving and rejecting assistance need decisions
- Adds ability for possible decision-makers to change themselves to be the decision-maker
=> EVAKA-4469 Add assistance need decision accepting & rejecting

frontend/webpack.config.js
=> Provide sentry release

service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt, service/src/main/kotlin/fi/espoo/evaka/note/child/daily/ChildDailyNoteQueries.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt, service/src/main/resources/db/migration/R__set_returning_functions.sql
=> PoC of set-returning functions for handling placements and backup care

service/src/integrationTest/kotlin/fi/espoo/evaka/FixtureBuilder.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt, service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
For occupancy report, caretaker counts should be calculated from realtime attendances if those are available.
=> EVAKA-4561 realtime attendances in occupancy report

frontend/src/citizen-frontend/child-documents/vasu/components/CheckboxQuestion.tsx, frontend/src/citizen-frontend/child-documents/vasu/components/MultiSelectQuestion.tsx, frontend/src/citizen-frontend/child-documents/vasu/components/Paragraph.tsx, frontend/src/citizen-frontend/child-documents/vasu/sections/CitizenDynamicSections.tsx, frontend/src/citizen-frontend/child-documents/vasu/vasu-content.ts, frontend/src/e2e-test/specs/5_employee/leops.spec.ts, frontend/src/employee-frontend/components/vasu/components/CheckboxQuestion.tsx, frontend/src/employee-frontend/components/vasu/components/MultiSelectQuestion.tsx, frontend/src/employee-frontend/components/vasu/components/Paragraph.tsx, frontend/src/employee-frontend/components/vasu/sections/DynamicSections.tsx, frontend/src/employee-frontend/components/vasu/templates/VasuTemplateEditor.tsx, frontend/src/employee-frontend/components/vasu/vasu-content.ts, frontend/src/lib-common/api-types/vasu.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
**#2623 should be merged before this!**
- Updates the default LEOPS template to follow the new guidelines
- Adds ability for checkbox questions not to have numbering
- Adds ability for multi select questions to have a date field, and a sub-text displayed below the option
=> EVAKA-4469 LEOPS changes

.github/workflows/build.yml
=> No sentry on test

.github/workflows/build.yml
=> Disable fail fast for e2e test

.github/workflows/build.yml
=> Fix deploy

frontend/Dockerfile
=> Update frontend Nginx

frontend/src/citizen-frontend/child-documents/ChildDocuments.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> EVAKA-4553 Add disclaimer for child document deletion

frontend/src/employee-frontend/components/reports/VardaErrors.tsx
=> EVAKA-4525 Wrap all characters in varda errors report

frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/sv.tsx
=> EVAKA-4569 Update translations of assistance need decisions

frontend/src/employee-frontend/components/absences/AbsenceTable.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/attendance-elements.tsx, frontend/src/lib-components/layout/Table.tsx
=> EVAKA-4435 Make unit calendar table headings sticky

frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts, frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts, frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx, frontend/src/lib-common/api-types/reservations.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt, service/src/main/resources/db/migration/R__set_returning_functions.sql
The attendances page of the main placement unit didn't show children in the week view if they were in backup care during the entire week.
=> Show children in backup care in the attendances page of the placement unit

frontend/src/employee-frontend/components/UnitFeaturesPage.tsx, frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReportDecision.tsx, frontend/src/lib-common/generated/api-types/daycare.ts, frontend/src/lib-components/atoms/buttons/ButtonLink.ts, frontend/src/lib-components/atoms/form/MultiSelect.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileUnitControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentNotificationServiceIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/UnitAccessControlTest.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
- Add translations for the features
- Show provider type below unit name
- Add filter for specific provider types
- Allow selecting/unselecting all features (of filtered units)
- Add undo with 1-deep history for accidental uses of "select/unselect all"
- Make table scrollable, and the heading sticky
=> EVAKA-4544 Improve unit features page

.github/workflows/build.yml, frontend/build-docker.sh
=> Simple CI pipeline for fork pull requests

frontend/src/employee-frontend/components/reports/Occupancies.tsx, frontend/src/lib-components/layout/Table.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
See https://github.com/espoon-voltti/evaka/pull/2566
=> Occupancy report improvements part3

frontend/src/employee-frontend/api/parentships.ts, frontend/src/employee-frontend/components/ChildInformation.tsx, frontend/src/employee-frontend/components/child-information/FridgeParents.tsx, frontend/src/employee-frontend/components/person-profile/PersonFridgeChild.tsx, frontend/src/employee-frontend/components/person-profile/PersonFridgePartner.tsx, frontend/src/employee-frontend/components/person-profile/PersonInvoiceCorrections.tsx, frontend/src/employee-frontend/state/child.tsx, frontend/src/employee-frontend/state/person.tsx, frontend/src/lib-common/generated/action.d.ts, frontend/src/lib-common/generated/api-types/pis.ts, service/codegen/src/main/kotlin/evaka/codegen/actionenum/Definitions.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/ParentshipControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/controllers/ParentshipController.kt
Fixes create/update/delete button visibility.
=> Add permitted actions support for parentship functionality

.github/workflows/build.yml, frontend/build-docker.sh
=> Fix fork require

service/src/main/kotlin/fi/espoo/evaka/daycare/service/DaycareService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceBasicsController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceCorrectionsController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/ExceptionHandling.kt, service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ExceptionHandler.kt, service/src/main/kotlin/fi/espoo/evaka/shared/db/PGUtils.kt, service/src/main/kotlin/fi/espoo/evaka/shared/domain/Errors.kt
=> Add cause support for our custom exception types

service/owasp-suppressions.xml
=> Remove unnecessary OWASP suppressions

service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt, service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
Adds assistance need decision email notifications to guardians
=> EVAKA-4469 Add assistance need decision email notifications

frontend/src/citizen-frontend/children/AssistanceNeedSection.tsx, frontend/src/e2e-test/pages/citizen/citizen-children.ts
=> EVAKA-4469 Add table for mobile of assistance need decisions

frontend/src/employee-frontend/components/reports/Occupancies.tsx
=> Fix occupancy report percentages

frontend/src/employee-frontend/components/UnitFeaturesPage.tsx, frontend/src/lib-common/generated/api-types/daycare.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
=> Add unit features filtering by care type

service/src/main/resources/WEB-INF/templates/fee-decision/decision.html, service/src/main/resources/WEB-INF/templates/shared/common.html, service/src/main/resources/WEB-INF/templates/shared/layout.html
- Move the address field slightly to the top
- Fix table layouts not taking all of the available spacing, which in turn made `text-right` columns ineffective
=> Fix PDF layout

service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/SoapStackIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/sficlient/MockSfiMessagesClient.kt, service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiAsyncJobs.kt, service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesClient.kt, service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt, service/src/main/kotlin/fi/espoo/evaka/shared/message/MessageProvider.kt
_Depends on #2675_
Adds Suomi.fi notifications for assistance need decisions.
=> EVAKA-4469 assistance need decision Suomi.fi

.github/workflows/build.yml
=> Store log results

evaka-bom/build.gradle.kts, frontend/src/employee-mobile-frontend/components/attendances/child-info/ImageEditor.tsx, service/build.gradle.kts, service/src/integrationTest/kotlin/fi/espoo/evaka/childimages/ChildImageTest.kt, service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImage.kt, service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImageController.kt
=> Limit child photo dimensions

.github/workflows/build.yml, frontend/src/citizen-frontend/messages/ThreadListItem.tsx, frontend/src/employee-mobile-frontend/components/messages/MessagePreview.tsx
=> CodeQL analysis

frontend/src/citizen-frontend/LoginPage.tsx, frontend/src/citizen-frontend/applications/ApplicationCreation.tsx, frontend/src/citizen-frontend/applications/editor/AdditionalDetailsSection.tsx, frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx, frontend/src/citizen-frontend/applications/editor/contact-info/ChildSubSection.tsx, frontend/src/citizen-frontend/applications/editor/contact-info/GuardianSubSection.tsx, frontend/src/citizen-frontend/applications/editor/service-need/AssistanceNeedSubSection.tsx, frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx, frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx, frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx, frontend/src/citizen-frontend/calendar/ReservationModal.tsx, frontend/src/citizen-frontend/child-documents/vasu/VasuPage.tsx, frontend/src/citizen-frontend/children/PlacementTerminationForm.tsx, frontend/src/lib-common/utils/scrolling.ts, frontend/src/lib-components/atoms/form/Checkbox.tsx, frontend/src/lib-components/atoms/form/MultiSelect.tsx, frontend/src/lib-components/atoms/form/Radio.tsx, frontend/src/lib-components/molecules/ExpandingInfo.tsx, frontend/src/lib-components/molecules/FileUpload.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- Wrapping of expanding info button with inline text elements
- Application:
- Text changes
- Warning box
- Only one expanded info visible at once
- Attachment area
- Remove "clear all" button from multi-selects on mobile
=> Application/general UI fixes

service/src/main/resources/db/migration/V255__drop_unused.sql, service/src/main/resources/migrations.txt
Other sequences (including decision_number) are still in use
=> Drop unused sequence

frontend/src/e2e-test/pages/employee/vasu/vasu.ts, service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
=> Fix flaky e2e test: vasu followup

.github/workflows/build.yml
=> Fix fork building

frontend/src/citizen-frontend/LoginPage.tsx, frontend/src/citizen-frontend/RequireAuth.tsx, frontend/src/citizen-frontend/header/const.ts
=> Fix login redirect

frontend/src/employee-frontend/components/reports/Raw.tsx, frontend/src/lib-common/generated/api-types/reports.ts, service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
- Add staff dimensioning (henkilöstömitoitus) to raw report
- Use static value 7
=> Add staff dimensioning to raw report

.github/workflows/build.yml
=> Fix e2e pipefail

.github/workflows/build.yml
=> Rename e2e test result artifact

frontend/src/citizen-frontend/child-documents/CitizenVasuAndLeops.tsx, frontend/src/citizen-frontend/children/AssistanceNeedSection.tsx, frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/pages/employee/assistance-need-decision/assistance-need-decision-preview-page.ts, frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts, frontend/src/e2e-test/specs/5_employee/assistance-need-decision.spec.ts, frontend/src/e2e-test/specs/5_employee/child-information-assistance-needs.spec.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
=> Fix broken tests

frontend/src/employee-frontend/components/unit/TabAttendances.tsx, frontend/src/employee-frontend/components/unit/tab-attendances/GroupSelector.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
=> Add all children/staff group option to unit page

frontend/src/citizen-frontend/children/ChildConsentsSection.tsx, frontend/src/e2e-test/pages/employee/assistance-need-decision/assistance-need-decision-edit-page.ts, frontend/src/e2e-test/specs/5_employee/assistance-need-decision.spec.ts, frontend/src/employee-frontend/components/SettingsPage.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionEditPage.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx, frontend/src/lib-components/assistance-need-decision/AssistanceNeedDecisionReadOnly.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/sv.tsx, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt
- pedagogical motivation and guardians heard on fields should be required
- all guardians should be heard (and if for some reason not, it should be explained why in the same field)
- updated text for support level motivation
- the decision-maker (and its title) is required
- at least one preparer (and its title) is required
=> EVAKA-4469 Update assistance need decision required fields

frontend/src/employee-frontend/components/person-profile/PersonFridgeChild.tsx
=> Fix fridge child edit modal

evaka-bom/build.gradle.kts
=> Upgrade to PostgreSQL JDBC 42.4.1

service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
=> Set last login on first login

frontend/src/employee-frontend/components/unit/tab-unit-information/Occupancy.tsx, frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx, frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancySingleDay.tsx
Use different graph min and max x-values depending on whether the queried date is the current date.
=> Fix realtime occupancy graph for past dates

compose/README.md, keycloak/README.md, keycloak/compose-resources/configuration/evaka.json
=> KeyCloak dev user

.github/workflows/build.yml
=> Include traces as test artifact

frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/sv.tsx
=> Sv language fixes

frontend/src/citizen-frontend/children/ChildConsentsSection.tsx, frontend/src/citizen-frontend/children/ChildrenPage.tsx, frontend/src/citizen-frontend/header/Header.tsx, frontend/src/employee-frontend/components/child-information/ChildConsentsSection.tsx, frontend/src/lib-common/generated/api-types/children.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/children/consent/ChildConsentControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/children/consent/ChildConsent.kt, service/src/main/kotlin/fi/espoo/evaka/children/consent/ChildConsentController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
=> Make enabled child consent types customizable

.github/workflows/build.yml
=> Login to public ECR in E2E tests

service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTest.kt
=> Use the correct assertThrows function

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx, frontend/src/citizen-frontend/calendar/DayView.tsx, frontend/src/citizen-frontend/calendar/ReservationModal.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- Changed spacing and design of modals
- Removed absence button from the day view modal; instead, adding a new reservation will overwrite the absence
=> EVAKA-4577 Modify absence and day view modals

frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/dev-api/index.ts, frontend/src/e2e-test/dev-api/types.ts, frontend/src/e2e-test/pages/employee/finance/finance-page.ts, frontend/src/e2e-test/specs/4_finance/payments.spec.ts, frontend/src/e2e-test/specs/6_mobile/child-attendances.spec.ts, frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts, frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts, frontend/src/employee-frontend/api/invoicing.ts, frontend/src/employee-frontend/components/payments/Actions.tsx, frontend/src/employee-frontend/components/payments/PaymentFilters.tsx, frontend/src/employee-frontend/components/payments/Payments.tsx, frontend/src/employee-frontend/components/payments/PaymentsPage.tsx, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Payments.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- Fix payments sending frontend request
- Add e2e test for sending payments
- Navigate to unit voucher report on payment click
=> EVAKA fix payments sending

frontend/package.json, frontend/src/employee-frontend/components/Search.tsx, frontend/src/employee-frontend/components/child-information/BackupPickup.tsx, frontend/src/employee-frontend/components/invoice/InvoiceRowsSectionRow.tsx, frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx, frontend/src/employee-frontend/components/reports/Invoices.tsx, frontend/src/employee-frontend/components/reports/Occupancies.tsx, frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Add react/self-closing-comp eslint rule

service/src/main/resources/WEB-INF/templates/fee-decision/decision.properties, service/src/main/resources/WEB-INF/templates/fee-decision/decision_sv.properties, service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.html, service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.properties, service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision_sv.properties, service/src/main/resources/WEB-INF/templates/shared/common.html, service/src/main/resources/WEB-INF/templates/shared/common.properties, service/src/main/resources/WEB-INF/templates/shared/common_sv.properties
=> Koneellisesti -> sähköisesti -translation

frontend/src/e2e-test/pages/admin/application-details-page.ts, frontend/src/e2e-test/pages/admin/application-workbench-page.ts, frontend/src/e2e-test/specs/5_employee/application-details.spec.ts, frontend/src/employee-frontend/components/application-page/ApplicationNoteBox.tsx
A basic test for application note creation, editing and deletion.
=> Add an application note e2e test

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Check that the message sender (eg. group) can send messages to the chosen recipients.
=> Check that message sender can send messages to recipients

frontend/src/e2e-test/pages/mobile/messages.ts, frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
=> Fix assertions in messaging mobile e2e tests

frontend/src/citizen-frontend/applications/ChildApplicationsBlock.tsx, frontend/src/citizen-frontend/child-documents/vasu/VasuPage.tsx, frontend/src/citizen-frontend/children/AssistanceNeedDecisionPage.tsx, frontend/src/citizen-frontend/children/ChildPage.tsx, frontend/src/citizen-frontend/children/ChildrenPage.tsx, frontend/src/employee-frontend/components/PersonProfile.tsx, frontend/src/employee-frontend/components/child-information/ChildDetails.tsx, frontend/src/employee-frontend/components/person-profile/PersonApplications.tsx, frontend/src/employee-frontend/components/person-profile/PersonDecisions.tsx, frontend/src/employee-frontend/components/person-profile/PersonDependants.tsx, frontend/src/employee-frontend/components/person-profile/PersonFamilyOverview.tsx, frontend/src/employee-frontend/components/person-profile/PersonFeeDecisions.tsx, frontend/src/employee-frontend/components/person-profile/PersonFridgeChild.tsx, frontend/src/employee-frontend/components/person-profile/PersonFridgeHead.tsx, frontend/src/employee-frontend/components/person-profile/PersonFridgePartner.tsx, frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx, frontend/src/employee-frontend/components/person-profile/PersonInvoiceCorrections.tsx, frontend/src/employee-frontend/components/person-profile/PersonInvoices.tsx, frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx, frontend/src/lib-components/assistance-need-decision/AssistanceNeedDecisionInfoHeader.tsx, frontend/src/lib-components/assistance-need-decision/AssistanceNeedDecisionReadOnly.tsx, frontend/src/lib-components/atoms/RoundImage.tsx, frontend/src/lib-components/atoms/buttons/ReturnButton.tsx, frontend/src/lib-components/layout/Container.tsx, frontend/src/lib-components/molecules/CollapsibleSection.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/sv.tsx
Miscellaneous spacing tweaks, and fixed active box for collapsed sections overflowing. Some examples:
=> Spacing UI tweaks

frontend/src/employee-frontend/api/auth.ts
Caused unnecessary popup when the login was successful on consequent logins.
=> Remove loginError param from RelayState

frontend/build.js, frontend/dev-server.js, frontend/package.json, frontend/src/e2e-test/browser.ts, frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/utils/page.ts, frontend/webpack.config.js
=> Add additional eslint rules

frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponse.tsx, frontend/src/lib-components/atoms/form/Radio.tsx
The missing field is already warned about sufficiently; the person accepting must clear the field manually to encounter this error.
=> Remove throw error from accept decision

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/FamilyConflictReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/resources/db/migration/R__primary_units_view.sql
Include family conflicts for children with future placements as well. Also fix a flaky service integration test.
=> Show family conflicts for future placements

frontend/src/employee-frontend/components/common/Filters.tsx, frontend/src/lib-common/generated/api-types/invoicing.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
=> Filter out new placements from fee decision search results

frontend/src/lib-components/molecules/modals/BaseModal.tsx
=> Center modal title and text

frontend/src/employee-frontend/api/applications.ts, frontend/src/employee-frontend/api/invoicing.ts, frontend/src/employee-frontend/components/application-page/ApplicationActionsBar.tsx
Fix two mismatches between AsyncButton API (which wants `Promise<Result<X>>`) and the actual REST API call (which returned `Promise<X>` so the promise may be rejected)
=> Add missing Result wrappings

service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
Using `realized_placement_one` made the performance awful, so use manual placement and backup care joins instead. Also, some of the date conditions were changed to utilize indices better.
The new query was tested in production and its duration went from over a minute to a bit over one second.
=> Fix reservation report query performance

service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
=> Add child id and unit id to PlacementCancel audit message

frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
Invalid attendances were not properly cleared/deleted for valid attendances
=> Fix external staff attendance table editing

frontend/src/employee-frontend/components/reports/VoucherServiceProviderUnit.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
=> Add forgotten field also to report excel

frontend/src/citizen-frontend/messages/MessagesPage.tsx, frontend/src/citizen-frontend/messages/ThreadList.tsx, frontend/src/citizen-frontend/messages/ThreadListItem.tsx, frontend/src/citizen-frontend/messages/ThreadView.tsx, frontend/src/e2e-test/pages/citizen/citizen-messages.ts, frontend/src/lib-components/molecules/ThreadListItem.tsx
- Make the new message button float on mobile (like the button in calendar)
- Fix spacing for desktop and mobile
- Wrap time-related information in time elements
=> Citizen message UI updates

.github/workflows/build.yml, apigw/build-docker.sh
=> Ensure that tests are executed every time

frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/children/consent/ChildConsentControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/children/consent/ChildConsentController.kt, service/src/main/kotlin/fi/espoo/evaka/children/consent/ChildConsentQueries.kt
=> Disable consents for children without a placement

keycloak/Dockerfile, keycloak/evaka-logging/pom.xml, keycloak/evaka-review-profile/pom.xml
=> Keycloak 19

frontend/src/employee-frontend/components/vasu/VasuPage.tsx
=> Update vasu sticky footer to be edge-to-edge

frontend/src/employee-frontend/components/vasu/components/MultiSelectQuestion.tsx, frontend/src/employee-frontend/components/vasu/templates/VasuTemplateEditor.tsx, frontend/src/lib-components/molecules/ExpandingInfo.tsx, service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
- Update info and field texts in LEOPS
- Move multi-select infos to individual options
- Added new field of additional assistance need information
=> EVAKA-4597 Update LEOPS fields and texts

frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx, frontend/src/lib-components/assistance-need-decision/AssistanceNeedDecisionReadOnly.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/sv.tsx, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt, service/src/main/resources/WEB-INF/templates/assistance-need/decision.html, service/src/main/resources/WEB-INF/templates/assistance-need/decision.properties, service/src/main/resources/WEB-INF/templates/assistance-need/decision_sv.properties
- Updated appeal instructions of assistance need decisions
- Updated text for end date in assistance need decisions
=> EVAKA-4589 update appeal instructions and end date change to assistance need decisions

service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt
=> Use unique documentId in assistance decision suomifi message

frontend/src/employee-frontend/api/invoicing.ts, frontend/src/employee-frontend/components/common/Filters.tsx, frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionFilters.tsx, frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionsPage.tsx, frontend/src/employee-frontend/state/invoicing-ui.tsx, frontend/src/lib-common/generated/api-types/invoicing.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
Add a checkbox to filter out voucher value decisions with starting placements
=> Filter out starting placements from voucher value decisions

.github/workflows/build.yml
=> Install frontend files to tute

service/src/integrationTest/kotlin/fi/espoo/evaka/LocalTimeRange.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/LocalTimeRangeTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
Child should be counted between attendance start and end time.
=> Fix attendance reservation report

service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationDetailsService.kt
Applications for preparatory+connected were erroneously marked as `additionalDaycareApplications` if the previous placement was preschool, and vice versa.
=> Fix marking as additionalDaycareApplication

frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/dev-api/index.ts, frontend/src/e2e-test/dev-api/types.ts, frontend/src/e2e-test/pages/mobile/unit-list-page.ts, frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts, frontend/src/e2e-test/specs/6_mobile/unit-list.spec.ts, frontend/src/e2e-test/utils/mobile.ts, frontend/src/employee-mobile-frontend/components/UnitList.tsx, service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
=> Do not include staff with 0 coefficient in mobile staff count

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
=> Evaka fix improve vtj logging

service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiClient.kt
=> Make koski caller id configurable

frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx
Render '00:00' and '23:59' using arrows in order to make the table
easier to read. This is similar to how staff attendances are rendered.
=> EVAKA-4596 Render overnight child attendances using arrows

frontend/src/employee-frontend/components/absences/AbsenceCell.tsx, frontend/src/lib-common/generated/api-types/daycare.ts, frontend/src/lib-common/utils/absences-date-range.spec.ts, service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/AbsenceController.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt, service/src/main/resources/db/migration/R__child_absences_functions.sql
=> Absence fixes

frontend/src/employee-frontend/api/reports.ts, frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx, frontend/src/lib-common/generated/api-types/reports.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
=> Add attendance reservation report groups filter
