- frontend/packages/employee-frontend/src/components/reports/Applications.tsx
- frontend/packages/employee-frontend/src/components/reports/ChildAgeLanguage.tsx
> Evaka 3884 missing report area filter

- README.md
Add contact information to readme.
None
Check the readme preview.
```
```
> Add contact information to readme

- compose/db-integration-test/Dockerfile
- compose/db/Dockerfile
- compose/docs/diagrams/src/evaka-container.puml
- compose/docs/diagrams/src/varda-integration.puml
- message-service/src/integrationTest/kotlin/fi/espoo/evaka/msg/config/PostgresContainer.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/TestContainers.kt
Upgrade to PostgreSQL 12 in local development / integration tests
> Upgrade to PostgreSQL 12

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
> Support fetching applications with no status

- frontend/packages/employee-frontend/src/components/applications/ApplicationsPage.tsx
Changed the default pageSize of applicaitons list from 200 to 50 to temporarily help with perf issues
> EVAKA-HOTFIX changed default pagesize of applications list

- frontend/packages/employee-frontend/src/components/applications/ApplicationsFilters.tsx
> Prevent extra application search request on reload

- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/LocationServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/LocationService.kt
Include future daycares when fetching areas
```
```
> EVAKA-3930 Include future daycares

- frontend/packages/employee-frontend/src/components/reports/Occupancies.tsx
Fixed area filter in occupancy report.
> EVAKA-HOTFIX fixed area filter in occupancy report

- frontend/e2e-test/test/e2e/pages/admin/application-workbench-page.ts
- frontend/packages/employee-frontend/src/api/index.ts
- frontend/packages/employee-frontend/src/components/applications/ApplicationsFilters.tsx
- frontend/packages/employee-frontend/src/components/applications/ApplicationsList.tsx
- frontend/packages/employee-frontend/src/components/applications/ApplicationsPage.tsx
- frontend/packages/employee-frontend/src/components/shared/atoms/Tooltip.stories.tsx
- frontend/packages/employee-frontend/src/components/shared/atoms/Tooltip.tsx
- frontend/packages/employee-frontend/src/state/application-ui.tsx
> EVAKA-3927: avoid double render, use high-perf tooltips

- frontend/e2e-test/test/e2e/specs/4_invoicing/invoices.spec.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/ApplicationPage.tsx
- frontend/packages/employee-frontend/src/components/application-page/ApplicationActionsBar.tsx
- frontend/packages/employee-frontend/src/components/fee-decision-details/Actions.tsx
- frontend/packages/employee-frontend/src/components/fee-decision-details/FeeDecisionDetailsPage.tsx
- frontend/packages/employee-frontend/src/components/fee-decisions/Actions.tsx
- frontend/packages/employee-frontend/src/components/invoice/Actions.tsx
- frontend/packages/employee-frontend/src/components/invoice/InvoicePage.tsx
- frontend/packages/employee-frontend/src/components/invoices/Actions.tsx
- frontend/packages/employee-frontend/src/components/person-profile/income/IncomeItemEditor.tsx
- frontend/packages/employee-frontend/src/components/shared/atoms/buttons/AsyncButton.tsx
- frontend/packages/employee-frontend/src/components/shared/atoms/buttons/Button.stories.tsx
- frontend/packages/employee-frontend/src/components/shared/layout/flex-helpers.ts
State dependant button texts, optional "primary" button styles and use AsyncButton in fee decision, invoice and application views.
> AsyncButton improvements

- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/ChildAttendanceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/resources/db/migration/V5__child_attendance.sql
- service/src/main/resources/migrations.txt
> EVAKA-3923: backend for child attendances

- service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionResolutionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementPlanIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/enduser/daycare/DaycareJsonDeserialize.kt
- service/src/main/kotlin/fi/espoo/evaka/application/persistence/daycare/DaycareFormV0.kt
- service/src/test/kotlin/fi/espoo/evaka/application/enduser/daycare/DaycareApplicationSerializerTest.kt
> Change preferred service start and end times as freeform strings

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/applications/ApplicationsList.tsx
- frontend/packages/employee-frontend/src/types/application.ts
- service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Fetch unit name if placement plan exists and show it on the application list. 
```
```
> Show proposed unit's name on application list

- frontend/e2e-test/package.json
- frontend/e2e-test/test/e2e/pages/admin/application-workbench-page.ts
- frontend/e2e-test/test/e2e/pages/enduser/club-application-form.ts
- frontend/e2e-test/test/e2e/pages/enduser/daycare-application.ts
- frontend/e2e-test/test/e2e/pages/enduser/enduser-navigation.ts
- frontend/packages/employee-frontend/package.json
- frontend/packages/enduser-frontend/package.json
- frontend/packages/enduser-frontend/src/store/modules/decisions.ts
- frontend/packages/enduser-frontend/src/views/applications/application-list-item.vue
- frontend/packages/enduser-frontend/src/views/applications/daycare-application/daycare-application.vue
- frontend/packages/enduser-frontend/src/views/decisions/decision-list-item.vue
- frontend/packages/enduser-frontend/src/views/decisions/decision-list.vue
- frontend/packages/lib-common/package.json
- frontend/packages/maintenance-page/package.json
- frontend/yarn.lock
- E2E: Update to Testcafe 1.9.x, fix misc issues
- Updating to Testcafe 1.9.x exposed a few issues via warnings
- Expect `.exists` values not `Selector`s
- Previously this would have actually checked nothing and just pass if a `Selector` was somewhat valid
- Use the correct selector for "check and send" button in all selectors
- Exposed by the `.exists` check
- Enduser: add `applicationId` and matching `data-` attributes to decision list, fix selectors
- Selector was broken anyway (missing double quotes in data-attribute's value) but it also referenced an attribute that wasn't even in the data (`data-application-id`) for decision summaries
- To check statuses in application & decision lists, target the actual status text elements instead of the whole containers
- At least in 1.9.x, …
> [EVAKA-3928] Update Testcafe, fix E2E test issues

- service-lib/src/test/kotlin/fi/espoo/voltti/logging/MdcKeyTest.kt
One of the tests needs cleanup afterwards, or it might affect other
logging tests
> Clear MDC in MdcKeyTest

- frontend/e2e-test/test/e2e/specs/5_employee/income.spec.ts
- frontend/packages/employee-frontend/.storybook/config.jsx
- frontend/packages/employee-frontend/src/components/common/EuroInput.tsx
- frontend/packages/employee-frontend/src/components/fee-decision-details/FeeDecisionDetailsPage.tsx
- frontend/packages/employee-frontend/src/components/fee-decision-details/Heading.tsx
- frontend/packages/employee-frontend/src/components/fee-decision-details/IncomeSection.tsx
- frontend/packages/employee-frontend/src/components/fee-decision-details/PartsSection.tsx
- frontend/packages/employee-frontend/src/components/fee-decision-details/Summary.scss
- frontend/packages/employee-frontend/src/components/fee-decision-details/Summary.tsx
- frontend/packages/employee-frontend/src/components/person-profile/income/income-table/IncomeTableRow.tsx
- frontend/packages/employee-frontend/src/components/shared/atoms/buttons/ReturnButton.tsx
- frontend/packages/employee-frontend/src/components/shared/atoms/form/InputField.tsx
- frontend/packages/employee-frontend/src/components/shared/atoms/form/SimpleSelect.tsx
- frontend/packages/employee-frontend/src/components/shared/layout/Table.tsx
- frontend/packages/employee-frontend/src/index.scss
* Remove import to old styleguide styles
* Show head of family income in fee decision page
* Fix the layout in fee decision page
* Slighly improve income editor UI
> Fix fee decision view

- message-service/src/main/kotlin/fi/espoo/evaka/msg/config/DatabaseConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/DatabaseConfig.kt
* leak detection has served its purpose, so disable it by default
* make it configurable via env by using the standard key used by Spring (even though we're configuring it manually)
> Disable leak detection but make it configurable

- .circleci/config.yml
> EVAKA-3463 Add SES-notification-processor version to circle config

- service/src/main/kotlin/fi/espoo/evaka/invoicing/integration/InvoiceIntegrationClient.kt
Cut names by the max length
```
```
> Fix community recipient name lengths

- frontend/packages/employee-frontend/src/App.tsx
- frontend/packages/employee-frontend/src/api/reports.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/reports/FamilyContacts.tsx
- frontend/packages/employee-frontend/src/components/unit/Groups.tsx
- frontend/packages/employee-frontend/src/types/reports.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ReportSmokeTests.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/FamilyConflictReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/FamilyContactReport.kt
A link to the report is available under the unit view.
```
```
> EVAKA-3921: family contacts report

- frontend/e2e-test/test/e2e/pages/invoicing.ts
- frontend/packages/employee-frontend/src/App.tsx
- frontend/packages/employee-frontend/src/api/invoicing.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/FinancePage.tsx
- frontend/packages/employee-frontend/src/components/Header.tsx
- frontend/packages/employee-frontend/src/components/fee-decisions/FeeDecisionsPage.tsx
- frontend/packages/employee-frontend/src/components/invoices/InvoicesPage.tsx
- frontend/packages/employee-frontend/src/components/shared/molecules/Tabs.tsx
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
Merge fee decisions and invoices pages into one finance page that has its own tab navigation. Also use a better path for fee decisions api.
> EVAKA-3893 preparation for value decisions

- frontend/packages/employee-frontend/package.json
- frontend/packages/employee-frontend/src/App.tsx
- frontend/packages/employee-frontend/src/api/absences.ts
- frontend/packages/employee-frontend/src/api/unit.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/AttendancePage.tsx
- frontend/packages/employee-frontend/src/components/Header.tsx
- frontend/packages/employee-frontend/src/components/shared/atoms/RoundIcon.tsx
- frontend/packages/employee-frontend/src/components/shared/atoms/buttons/Button.tsx
- frontend/packages/employee-frontend/src/components/unit/UnitInformation.tsx
- frontend/packages/employee-frontend/src/constants.ts
- frontend/packages/employee-frontend/src/index.html
- frontend/packages/employee-frontend/src/types/attendance.d.ts
- frontend/yarn.lock
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/AbsenceController.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
Mobile POC for adding attendances or absences for children.
Spec here: https://www.figma.com/proto/UyFTAPt5kFhErtP56e7Ze8/Evaka-design?node-id=508%3A84&scaling=scale-down
> EVAKA 3795 attendances mobile POC

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaChildrenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaPlacementsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaChildren.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaPlacements.kt
- service/src/main/resources/db/migration/V6__add_delete_columns_to_varda_tables.sql
- service/src/main/resources/migrations.txt
Add ability to soft delete decisions & placements sent to Varda
Also remove old unit list
```
```
> EVAKA-3886 fix duplicate varda units

- compose/README.md
- frontend/README.md
- frontend/packages/employee-frontend/README.md
- frontend/packages/enduser-frontend/README.md
Improve instructions for running eVaka on local development environment.
None
Please read through and check for any typos. Also, please double-check versions I've added.
```
```
> Improve instructions for running eVaka locally

- frontend/packages/employee-frontend/src/components/AttendancePage.tsx
Fixed couple of minor things in the attendance POC:
> Lapsen nimi kokonaisena siihen lapsen näkymään
> Lapsen näkymässä tilat suomeksi (samoin kun ovat listalla).
> Muutama pikseli väliä listalla näkyvien lasten väliin että erottuvat toisistaan
> EVAKA-HOTFIX minor tweaks to attendance POC

- frontend/packages/employee-frontend/src/components/AttendancePage.tsx
Removed extra group info from attendances page.
> EVAKA-HOTFIX removed extra group info from attendances page

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaPlacementsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaPlacements.kt
Remove placements first, then decisions
```
```
> EVAKA-HOTFIX-correct-order-of-varda-removals

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/ApplicationPage.tsx
- frontend/packages/employee-frontend/src/components/application-page/ApplicationEditView.tsx
Refresh unit list in application edit view when changing the preferred start date on application.
> Refresh application unit list on date change

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/reports/FamilyContacts.tsx
- service/src/main/kotlin/fi/espoo/evaka/reports/FamilyConflictReport.kt
> EVAKA-3921: change report sorting and spreadsheet layout

- service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceActionsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ChildAgeLanguageReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/Common.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceNeedReport.kt
> EVAKA-bugfix: fix unit type on reports

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
> Fix partime label

- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceClientIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModifications.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsBatchRefreshService.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceClient.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/VTJBatchRefreshService.kt
> Review fixes

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
> Use form update timestamp to indicate application was modified

- frontend/packages/employee-frontend/src/components/child-information/CreateApplicationModal.tsx
Replace the hard coded value in application type select with the real value.
> Hotfix: application type select in paper application modal

- apigw/src/shared/auth/dev-passport-strategy.ts
- apigw/src/shared/auth/espoo-ad-saml.ts
- apigw/src/shared/routes/auth/saml/index.ts
- service/src/main/kotlin/fi/espoo/evaka/shared/db/DevDataInitializer.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/dev-data/employees.sql
> dev-login v2 with employee dev-data

- service/src/integrationTest/kotlin/fi/espoo/evaka/emailclient/EmailClientIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/MockEmailClient.kt
> EVAKA-3463 Swedish texts to emails

- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionController.kt
> Show decisions to unit supervisor

- frontend/packages/enduser-frontend/src/localization/app/en.json
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/localization/app/sv.json
- frontend/packages/enduser-frontend/src/views/applications/daycare-application/daycare-application.vue
Changed application start date to be editable by the enduser while the application has not been sent to WAITING_PLACEMENT state.
> Evaka 3806 enduser can change startdate after application has been sent

- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
> EVAKA-3463 Edit swedish email subject

- service/src/main/resources/db/migration/V9__update_varda_child.sql
> EVAKA-HOTFIX: fix migration v9

- service/src/integrationTest/resources/integration-test-common.properties
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/AwsConfig.kt
- service/src/main/resources/application-local.properties
Read the voucher value decision bucket name from env. Depends on infra changes.
> Voucher value decision bucket

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaFeeDataIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaChildren.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
- service/src/main/resources/db/migration/V11__add_constraint_to_varda_child.sql
- service/src/main/resources/migrations.txt
> EVAKA-HOTFIX Various Varda fixes

- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
See commit messages
Merge and apply same time with https://github.com/espoon-voltti/evaka-infra/pull/298
> EVAKA-3463 Name to email address

- frontend/packages/employee-frontend/src/components/common/styled/common.ts
- frontend/packages/employee-frontend/src/config.ts
- frontend/packages/enduser-frontend/src/icons/pro-icons.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/ChildAttendanceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FinanceDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/DvvModificationServiceConfig.kt
Searched all the files missing the license headers with
find . -iname "*.kt" -print0 | xargs -0 grep -iL "SPDX"
and
find ./frontend/packages/**/src -iname "*.js" -print0 | xargs -0 grep -iL "SPDX"
```
```
> Add missing license headers

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaPlacementsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaPlacements.kt
> EVAKA_HOTFIX: fix varda update order

- frontend/packages/employee-frontend/src/components/Reports.tsx
- service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceActionsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceNeedReport.kt
Show the following reports to unit manager with the from own units: 
- service need
```
```
> Show own units' reports to unit manager

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaPlacements.kt
Consider soft deleted rows inexistent
```
```
> EVAKA_HOTFIX: fix some varda queries

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaFeeDataIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
Ensure fee data is sent only once
```
```
> EVAKA_HOTFIX: fix varda queries again

- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
> EVAKA-3900: hotfix evaka launch date

- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
> EVAKA-3900: hotfix 2 - filter by gap end instead of placement end

- service/src/integrationTest/kotlin/fi/espoo/evaka/backupcare/BackupCareIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
> EVAKA-3900: hotfix 3 - ignore missing service needs before evaka-launch

- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceClientIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/MockDvvModificationsService.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModifications.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceClient.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/DvvModificationServiceConfig.kt
* Adds support for two dvv modification service modifications
- name change
- residence code change
* Supports paging
* Handles transactions correctly
```
```
> Support dvv name and residence code changes and paging

- service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceActionsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/MissingHeadOfFamilyReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/MissingServiceNeedReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceNeedReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt
> Fix report unit filtering

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/EmailResponseIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
> EVAKA-3463 Tweak application emails

- .circleci/config.yml
- Starting from 2020-11-01 Docker Hub effectively requires authentication for all pulls -> add authentication from shared voltti-dockerhub Context
- CI passes without warnings in Docker related steps (incl. executor setups)
- ~[ ] Tests have been written for the change (e2e, integration tests)~
- ~[ ] The change conforms to the UX specifications~
```
```
> CI: Add Docker Hub auth

- .circleci/config.yml
- Accidentally deleted too many permissions from frontend_build_and_test -> re-add sentry-release for Sentry API token
None
None really
```
```
> [EVAKA-HOTFIX] CI: fix Sentry release

- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsBatchRefreshService.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
If there are no changes, dvv mutp service returns ajanTasalla=true AND viimeisinKirjausavain = the original token. In this case do not create a new modification token.
```
```
> Handle properly case where there is no modifications found

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
Decision should be part time only if the care hours per week are under 25 hours - 25 hour care should yield full time decision
> EVAKA-FIX Varda decision part time bug

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/voucher-value-decision/VoucherValueDecisionCoPaymentSection.tsx
- frontend/packages/employee-frontend/src/components/voucher-value-decision/VoucherValueDecisionSummary.tsx
- frontend/packages/employee-frontend/src/components/voucher-value-decision/VoucherValueDecisionValueSection.tsx
- frontend/packages/employee-frontend/src/components/voucher-value-decisions/VoucherValueDecisions.tsx
- frontend/packages/employee-frontend/src/types/invoicing.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/DecisionGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Placements.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValue.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/resources/db/migration/V12__voucher_value_decision_value.sql
- service/src/main/resources/dev-data/espoo-dev-data.sql
- service/src/main/resources/migrations.txt
Add voucher values to voucher value decisions.
> Voucher values

- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
Update voucher value decision pdf contents slightly so it's not just an empty document. But since we don't have a spec for the contents yet, keep it simple.
> Slightly updated voucher value decision pdf contents

- frontend/e2e-test/test/e2e/pages/employee/units/unit-page.ts
- frontend/e2e-test/test/e2e/specs/5_employee/units.spec.ts
- frontend/packages/employee-frontend/src/api/unit.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/common/FormModal.tsx
- frontend/packages/employee-frontend/src/components/unit/tab-groups/groups/Group.tsx
- frontend/packages/employee-frontend/src/components/unit/tab-groups/groups/group/GroupRenameModal.tsx
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareGroupQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
> EVAKA-3969: renaming groups

- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
Translation problems: Update swedish email text
> EVAKA-3463 Update swedish email text

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/child-information/ChildApplications.tsx
- frontend/packages/employee-frontend/src/components/person-profile/PersonApplications.tsx
- frontend/packages/employee-frontend/src/types/application.ts
- service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Infer application type from bits and pieces in the child applications list view.
```
```
> EVAKA-3978 application service type in child application list

- service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/OccupancyReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
Use unit operational days to filter out non operational days from occupancy and raw reports.
> EVAKA-3744 operational days in reports

- service/src/main/kotlin/fi/espoo/evaka/shared/auth/Acl.kt
> Allow director access to all units

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
> Fix unit applications view guardian name

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/common/Filters.tsx
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
Validate application search date filters in backend and add warning texts to date filter components in application, fee decision and invoice lists.
> Validate search filter dates

- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
> EVAKA-3463 Update swedish texts

- frontend/packages/employee-frontend/src/components/common/DateRangeInput.scss
- frontend/packages/employee-frontend/src/components/common/EuroInput.tsx
- frontend/packages/employee-frontend/src/components/common/Select.tsx
- frontend/packages/employee-frontend/src/components/invoice/InvoiceRowsSection.tsx
- frontend/packages/employee-frontend/src/components/invoice/InvoiceRowsSectionRow.tsx
- frontend/packages/employee-frontend/src/components/shared/atoms/form/InputField.tsx
* improve layout and column widths
* simplify validation error, remove "jumpiness" caused by column width changes
* track a separate "string value" in amount editor to allow more flexible editing
* fix jumpy right-aligned text input (padding applied to wrong side)
> [EVAKA-3971] Invoice editor UI/UX fixes

- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
> EVAKA-3463 Remove extra character from email

- frontend/packages/employee-frontend/src/components/absences/utils.ts
- frontend/packages/lib-common/src/local-date.ts
> Use ISO day of week as supposed

- frontend/e2e-test/test/e2e/pages/employee/absences/absences-page.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/types/absence.ts
https://voltti.slack.com/archives/CMBBWQSBY/p1604583000004300
```
```
> Use sensible defaults that work for all unit types

- frontend/packages/employee-frontend/src/App.tsx
- frontend/packages/employee-frontend/src/api/reports.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/Reports.tsx
- frontend/packages/employee-frontend/src/components/reports/VoucherServiceProviders.tsx
- frontend/packages/employee-frontend/src/config.ts
- frontend/packages/employee-frontend/src/types/reports.ts
- service/src/main/kotlin/fi/espoo/evaka/reports/DummyVoucherServiceProviderReport.kt
Ongoing work - Voucher service provider report UI and dummy backend
```
```
> Voucher service provider report

- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
> EVAKA-3463 Update swedish email texts

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/attendances/AttendanceList.tsx
- frontend/packages/employee-frontend/src/components/attendances/AttendancePageWrapper.tsx
Fixed attendance links and filtering of attendances
> EVAKA-HOTFIX fixed attendance links and filtering

- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsBatchRefreshService.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
> Evaka 4002 improve dvv logging

- service/src/main/kotlin/fi/espoo/evaka/pis/service/FamilyInitializerService.kt
Remove nested independent transactions
> Fix family initializer transactions

- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
Only include units that are open now or in the future in the unit filters.
> Only include open units in filters

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
couple of bug fixes. see commit messages
> EVAKA-4000 Varda decision bugs

- frontend/packages/employee-frontend/src/components/attendances/AttendanceChildPage.tsx
- frontend/packages/employee-frontend/src/components/attendances/AttendanceList.tsx
Fixed wrong group id usage in the child view.
> EVAKA-HOTFIX use proper groupIds in child page

- service/src/main/kotlin/fi/espoo/evaka/reports/ApplicationsReport.kt
Add simple join condition to skip transfer applications from the list
> EVAKA-3984 filter transfer applications from report

- apigw/yarn.lock
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaChildrenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaFeeDataIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaChildren.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- service/src/main/resources/mock-vtj-data.json
> Do not send nameless people to Varda

- apigw/src/internal/app.ts
- frontend/packages/employee-frontend/src/api/hidden.ts
- frontend/packages/employee-frontend/src/components/Search.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiUpdateService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/SecurityConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
https://github.com/espoon-voltti/evaka-infra/pull/309
```
```
> Separate endpoint for scheduled operations

- service/src/main/kotlin/fi/espoo/evaka/reports/MissingServiceNeedReport.kt
> Include only invoiced units in missing service need report

- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
> Update Suomi.fi message texts

- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
> Remove an unused parameter causing a 401 on lambda call

- apigw/src/internal/app.ts
- apigw/src/shared/proxy-utils.ts
- service/src/integrationTest/resources/integration-test-common.properties
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/AwsConfig.kt
- service/src/main/resources/application-local.properties
- service/src/main/resources/application.properties
- service/src/main/resources/db/migration/V16__attachments.sql
- service/src/main/resources/migrations.txt
> EVAKA-3464: attachments

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Fix application delete that fails because of references from attachment table.
> EVAKA-3464 fix application delete

- frontend/e2e-test/test/e2e/dev-api/fixtures.ts
- frontend/e2e-test/test/e2e/dev-api/types.ts
- frontend/e2e-test/test/e2e/pages/reports.ts
- frontend/e2e-test/test/e2e/specs/3_reporting/voucher-reports.spec.ts
- frontend/packages/employee-frontend/src/components/Reports.tsx
- frontend/packages/employee-frontend/src/components/reports/AssistanceActions.tsx
- frontend/packages/employee-frontend/src/components/reports/AssistanceNeeds.tsx
- frontend/packages/employee-frontend/src/components/reports/ChildrenInDifferentAddress.tsx
- frontend/packages/employee-frontend/src/components/reports/FamilyConflicts.tsx
- frontend/packages/employee-frontend/src/components/reports/MissingHeadOfFamily.tsx
- frontend/packages/employee-frontend/src/components/reports/MissingServiceNeed.tsx
- frontend/packages/employee-frontend/src/components/reports/PartnersInDifferentAddress.tsx
- frontend/packages/employee-frontend/src/components/reports/ReportDownload.tsx
- frontend/packages/employee-frontend/src/components/reports/VoucherServiceProviders.tsx
> Use area filter in csv report

- apigw/src/shared/middleware/csrf.ts
- apigw/src/shared/middleware/error-handler.ts
Log these errors + metadata about headers/cookies
> Log CSRF errors in apigw

- frontend/e2e-test/test/e2e/dev-api/fixtures.ts
- service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
> Fix residence code and street address comparison

- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiUpdateService.kt
This makes sure it's included if logs are searched with the word "Koski"
> Add the word Koski to scheduling log message

- service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/service/persondetails/PersonStorageService.kt
> Use locks in VTJ updates and use them in a consistent order

- service/src/integrationTest/resources/integration-test-common.properties
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/AwsConfig.kt
- service/src/main/resources/application-local.properties
Update attachments bucket env variable name.
> EVAKA-3464 attachments bucket config

- frontend/packages/employee-frontend/src/api/invoicing.ts
- frontend/packages/employee-frontend/src/components/common/StickyActionBar.tsx
- frontend/packages/employee-frontend/src/components/fee-decision-details/Actions.tsx
- frontend/packages/employee-frontend/src/components/voucher-value-decision/VoucherValueDecisionActionBar.tsx
- frontend/packages/employee-frontend/src/components/voucher-value-decision/VoucherValueDecisionPage.tsx
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
Add a button to voucher value decision page to mark a decision that is waiting for manual sending as sent.
> Add ability to mark value decision manually sent

- frontend/packages/enduser-frontend/src/components/common/file-upload.vue
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/store/modules/forms.ts
Add a fancier file input and show a special error message when file attachment is too big.
> EVAKA-3464 better file input

- frontend/packages/employee-frontend/src/components/attendances/AttendancePageWrapper.tsx
Last fix broke one link and this fixes it.
> EVAKA-HOTFIX fixed broken link

- frontend/packages/enduser-frontend/src/components/common/file-upload.vue
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentQueries.kt
Fix attachment insert and a vue lint warning.
> EVAKA-3464 attachments fixes

- frontend/packages/enduser-frontend/src/router.ts
This should be tested in staging before deploying to prod
> EVAKA-deadlocks: await for auth in router before sending other requests

- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/views/applications/daycare-application/daycare-application.vue
Use old text before attachments are enabled. Text were updated earlier without realizing it should be behind feature flag. 
```
```
> HOTFIX: misleading attachment text

- frontend/e2e-test/test/e2e/pages/admin/unit-details-page.ts
- frontend/e2e-test/test/e2e/specs/5_employee/unit-editor.spec.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/unit/unit-details/UnitEditor.tsx
Require unit type in unit editor. Also disable form submit if there are any errors.
> Require type in unit editor

- frontend/e2e-test/test/e2e/pages/employee/applications/application-read-view.ts
- frontend/e2e-test/test/e2e/pages/enduser/enduser-navigation.ts
- frontend/e2e-test/test/e2e/specs/1_application/application-attachment.spec.ts
- frontend/packages/enduser-frontend/src/views/applications/daycare-application/daycare-application.vue
Add simple e2e-test for extended care attachments
> EVAKA-3464 e2e-test for extended care attachments

- frontend/e2e-test/test/e2e/pages/employee/applications/application-read-view.ts
- frontend/e2e-test/test/e2e/pages/enduser/enduser-navigation.ts
- frontend/e2e-test/test/e2e/specs/1_application/application-attachment.spec.ts
- frontend/packages/enduser-frontend/src/components/common/file-upload.vue
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
- service/src/main/kotlin/fi/espoo/evaka/s3/DocumentService.kt
- service/src/main/kotlin/fi/espoo/evaka/s3/S3DocumentClient.kt
> Evaka 3464 Remove attachment from S3 bucket

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/enduser-frontend/src/localization/app/en.json
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/localization/app/sv.json
I've checked the Swedish translations.
> Change part-time localizations to part-day

- compose/ecosystem.config.js
On some occasions the apigw was not rebuilt after a change. Clean up the old build on restart to make sure it is always up to date.
```
```
> Make sure apigw is built after a change

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/attendances/Absences.tsx
- frontend/packages/employee-frontend/src/components/attendances/AttendanceChildAbsent.tsx
Removed absence type from child page.
> Evaka hotfix mobile poc changes

- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/AbsenceServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
Do not show both paid and free halves on absence diary when a 5-year-old is in part time daycare.
> EVAKA-4019 absences for 5-year-olds in part time daycare

- frontend/packages/enduser-frontend/src/localization/app/en.json
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/localization/app/sv.json
> EVAKA-4011 add h/week to part day label on application

- frontend/packages/enduser-frontend/src/localization/app/en.json
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/localization/app/sv.json
- frontend/packages/enduser-frontend/src/views/applications/daycare-application/daycare-application.vue
Add English and Swedish localizations for attachments texts and update the attachments related text visuals to match UX specs.
> EVAKA-3464 missing attachments localizations

- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/Acl.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/UserRole.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/resources/db/migration/V24__mobile_user_role.sql
- service/src/main/resources/migrations.txt
> EVAKA-4006: add mobile user-role

- service/src/main/kotlin/fi/espoo/evaka/pairing/PairingAsyncJobs.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/PairingsController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
> EVAKA-4006: Garbage collect expired pairings

- apigw/src/internal/__tests__/mobile-device-session.ts
- apigw/src/internal/mobile-device-session.ts
- apigw/src/internal/routes/auth-status.ts
- apigw/src/shared/service-client.ts
- frontend/packages/employee-frontend/src/components/Header.tsx
- frontend/packages/employee-frontend/src/components/mobile/MobileLander.tsx
- frontend/packages/employee-frontend/src/state/user.tsx
- frontend/packages/employee-frontend/src/types/index.ts
- service/src/main/kotlin/fi/espoo/evaka/pairing/Pairing.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/Acl.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/UserRole.kt
> [EVAKA-4006] Include mobile device info in /auth/status endpoint

- frontend/packages/employee-frontend/src/api/index.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/applications/ActionBar.tsx
- frontend/packages/employee-frontend/src/components/common/FormModal.tsx
- frontend/packages/employee-frontend/src/components/common/StickyActionBar.tsx
- frontend/packages/employee-frontend/src/components/fee-decisions/FeeDecisionsPage.tsx
- frontend/packages/employee-frontend/src/components/invoices/Actions.tsx
- frontend/packages/employee-frontend/src/components/invoices/Invoices.tsx
- frontend/packages/employee-frontend/src/components/invoices/InvoicesPage.tsx
- frontend/packages/employee-frontend/src/components/invoices/invoices-state.ts
- frontend/packages/employee-frontend/src/components/shared/atoms/buttons/AsyncButton.tsx
- frontend/packages/employee-frontend/src/components/voucher-value-decision/VoucherValueDecisionActionBar.tsx
- frontend/packages/employee-frontend/src/state/invoicing-ui.tsx
* Improve send area invoices toggle UX
* Refactor invoice list page state
* Use async button in send invoices modal
* Use full width action bar in finance list views
> EVAKA-3858 send invoices UX

- frontend/e2e-test/test/e2e/pages/admin/application-workbench-page.ts
- frontend/e2e-test/test/e2e/specs/2_employee-2/employee-reads-application.spec.ts
- frontend/packages/employee-frontend/src/api/applications.ts
- frontend/packages/employee-frontend/src/components/applications/ActionBar.tsx
- frontend/packages/employee-frontend/src/components/applications/ApplicationActions.tsx
- frontend/packages/employee-frontend/src/components/decision-draft/DecisionDraft.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Remove mass confirmation button because it seems to be unnecessary now and potentially confusing
```
```
> EVAKA-4023 remove mass confirmation button from application view

- frontend/e2e-test/test/e2e/pages/enduser/enduser-navigation.ts
- frontend/e2e-test/test/e2e/specs/1_application/application-validations.spec.ts
- frontend/packages/enduser-frontend/src/components/modal/message-modal.vue
- frontend/packages/enduser-frontend/src/components/styleguide/c-datepicker.vue
- frontend/packages/enduser-frontend/src/localization/app/en.json
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/localization/app/sv.json
- frontend/packages/enduser-frontend/src/views/applications/daycare-application/daycare-application.vue
Validation for preferred start date and E2E tests for modifying it
```
```
> Validation for application preferred start date

- frontend/packages/employee-frontend/webpack.config.js
- frontend/packages/enduser-frontend/vue.config.js
> On Macos the webpack_dev_server takes 150% cpu constantly without this

- .circleci/config.yml
- frontend/e2e-test/package.json
- frontend/e2e-test/test/e2e/config/index.ts
- frontend/e2e-test/test/e2e/config/users.ts
- frontend/e2e-test/test/e2e/dev-api/index.ts
- frontend/e2e-test/test/e2e/pages/employee/mobile/pairing-flow.ts
- frontend/e2e-test/test/e2e/pages/employee/units/unit-page.ts
- frontend/e2e-test/test/e2e/specs/5_employee/unit-acl.spec.ts
- frontend/e2e-test/test/e2e/specs/6_mobile/pairing.spec.ts
- frontend/packages/employee-frontend/src/components/attendances/AttendanceGroupSelectorPage.tsx
- frontend/packages/employee-frontend/src/components/mobile/MobileLander.tsx
- frontend/packages/employee-frontend/src/components/mobile/PairingWizard.tsx
- frontend/packages/employee-frontend/src/components/unit/MobilePairingModal.tsx
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Added e2e tests for mobile pairing flow.
These tests only test only side of the pairing flow at a time and "mock" the other side with dev-api calls.
> EVAKA-4006 e2e tests for mobile pairing flow

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/person-profile/PersonIncome.tsx
- frontend/packages/employee-frontend/src/components/person-profile/income/missingIncomePeriodUtils.tsx
Warn employee when changes on incomes leads to periods of unreported income.
Screenshot for reference.
> EVAKA-3859: Missing income days warning

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
Delete placements before sending decision updates to Varda to prevent date range conflicts on decision dates update. The test is not very robust, but it's the best we can do at this point.
> Delete varda placements before updating a decision

- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentsControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/integrationTest/resources/application-integration-test.properties
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
- service/src/main/resources/application.properties
Prevent uploading more than the specified amount of attachments. This should never happen to a non malicious user so no user UI is created for this.
> Set max limit for file uploads per user

- frontend/packages/employee-frontend/src/api/attendances.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/attendances/AbsenceSelector.tsx
- frontend/packages/employee-frontend/src/components/attendances/Absences.tsx
- frontend/packages/employee-frontend/src/components/attendances/AttendanceChildComing.tsx
- frontend/packages/employee-frontend/src/components/attendances/AttendanceChildDeparted.tsx
- frontend/packages/employee-frontend/src/components/attendances/AttendanceChildPresent.tsx
- frontend/packages/employee-frontend/src/components/attendances/components.tsx
- frontend/packages/employee-frontend/src/types/absence.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/test/kotlin/fi/espoo/evaka/attendance/AttendanceTests.kt
> EVAKA-4004: Preschool daycare partial absences

- frontend/packages/employee-frontend/src/api/attendances.ts
- frontend/packages/employee-frontend/src/components/attendances/ChildListItem.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
> EVAKA-4017: attendances of backup care children

- frontend/packages/employee-frontend/src/components/unit/tab-unit-information/UnitAccessControl.tsx
- frontend/packages/employee-frontend/src/constants.ts
Actually hides mobile devices in production
> EVAKA-HOTFIX disable mobile pairing from production

- frontend/packages/employee-frontend/src/components/unit/tab-unit-information/UnitAccessControl.tsx
- frontend/packages/employee-frontend/src/constants.ts
This pull request enables mobile pairing functionality for pilot units in production
> EVAKA-HOTFIX enable mobile pairing for pilot units in production

- frontend/packages/employee-frontend/src/components/shared/molecules/Tabs.tsx
> Bug fix: hide unit page zero counters

- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceUpkeepIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
At the end of day set departure time for unfinished attendances
- built on top of https://github.com/espoon-voltti/evaka/pull/250, needs rebasing after that is completed and merged
- scheduled lamda in evaka-infra https://github.com/espoon-voltti/evaka-infra/pull/319
> EVAKA-4005: attendance upkeep

- apigw/src/enduser/routes.ts
- frontend/packages/enduser-frontend/src/components/common/file-upload.vue
- frontend/packages/enduser-frontend/src/localization/app/en.json
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/localization/app/sv.json
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
- service/src/main/kotlin/fi/espoo/evaka/s3/DocumentService.kt
- service/src/main/kotlin/fi/espoo/evaka/s3/S3DocumentClient.kt
When user uploads an attachment and tries to retrieve it too soon (or the file is irretrievable), show a modal saying that file processing is in progress.
> EVAKA-3464 pending attachment download

- proxy/Dockerfile
- proxy/nginx.conf.template
> KeyCloak to proxy

- service/src/main/kotlin/fi/espoo/evaka/pis/SystemIdentityController.kt
> Fix mobile identity endpoint HTTP method

- apigw/src/internal/__tests__/mobile-device-session.ts
- apigw/src/internal/mobile-device-session.ts
- apigw/src/internal/routes/auth-status.ts
- apigw/src/shared/auth/dev-passport-strategy.ts
- apigw/src/shared/auth/espoo-ad-saml.ts
- apigw/src/shared/dev-api.ts
- apigw/src/shared/routes/auth/saml/index.ts
- apigw/src/shared/service-client.ts
- apigw/src/shared/session.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/SystemIdentityControllerTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/JdbiExtensionsTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/MobileDeviceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/SystemIdentityController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/JdbiExtensions.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- clear token if it's no longer valid based on service response
- logout user (= clear session) if mobile device has been removed
- fix handling of null values in external id column mapper
- add more tests for JDBI column/argument mappers
- add apigw tests for mobile device token rotation
- add apigw tests for mobile device deletion
- add service tests for /system/mobile-identity endpoint
- fix apigw dev login
> Fixes to mobile device functionality

- message-service/build.gradle.kts
- message-service/buildSrc/src/main/kotlin/Version.kt
- message-service/gradle/wrapper/gradle-wrapper.properties
- service/build.gradle.kts
- service/buildSrc/src/main/kotlin/Version.kt
- service/gradle/wrapper/gradle-wrapper.properties
- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/integration/InvoiceIntegrationClient.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
- service/src/main/kotlin/fi/espoo/evaka/units/UnitsView.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaTokenProvider.kt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisionsTest.kt
> Upgrade to kotlin 1.4.21

- service/src/main/kotlin/fi/espoo/evaka/reports/FamilyConflictReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/FamilyContactReport.kt
diff looks bigger than it is due to fixing filenames by swapping them
> EVAKA-4043: backup children in contact report + fix file names

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
Should have rebased branch on top of master 😞
> Fix lint error caused by ktlint version mismatch

- apigw/src/shared/config.ts
> Make employee gw only config optional

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
I forgot to take this into account when I was doing the refactor. It's pretty much pointless to leave the rows in the database since we can't connect the row to anything in Varda.
> Delete varda fee data rows completely on clean up

- frontend/packages/employee-frontend/src/api/attendances.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/attendances/Absences.tsx
- frontend/packages/employee-frontend/src/components/attendances/components.tsx
- frontend/packages/employee-frontend/src/types/absence.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DecisionGenerator.kt
- service/src/test/kotlin/fi/espoo/evaka/attendance/AttendanceTests.kt
> EVAKA-4018: 5 year old absences

- frontend/packages/employee-frontend/src/state/user.tsx
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ExceptionHandler.kt
> EVAKA-PATCH: do not expose error messages

- frontend/e2e-test/test/e2e/dev-api/index.ts
- frontend/e2e-test/test/e2e/pages/employee/units/unit-page.ts
- frontend/e2e-test/test/e2e/specs/5_employee/unit-acl.spec.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/unit/MobilePairingModal.tsx
- service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
This PR hides "mobile device users" from employee listings.
> EVAKA-HOTFIX hide mobile users from employees listing

- frontend/e2e-test/test/e2e/pages/employee/units/unit-page.ts
- frontend/e2e-test/test/e2e/specs/5_employee/unit-acl.spec.ts
- frontend/packages/employee-frontend/src/api/unit.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/unit/tab-unit-information/UnitAccessControl.tsx
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
- Special education teachers can be added or removed from an unit
- E2E test for this case
- As an admin, go to unit page
- Add user to special education teacher role
- Login as that user and verify you can see the unit
- Login as an admin and remove the user from special education teacher role
> EVAKA-4041: Add special education teacher view for admin

- service/src/main/kotlin/fi/espoo/evaka/varda/integration/MockVardaIntegrationEndpoint.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- service/src/test/kotlin/fi/espoo/evaka/varda/integration/VardaClientTest.kt
Update the Varda token refresh error message check.
> Fix Varda expired token refresh

- frontend/e2e-test/test/e2e/specs/5_employee/application-details.spec.ts
- frontend/packages/enduser-frontend/src/localization/app/en.json
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/localization/app/sv.json
- frontend/packages/enduser-frontend/src/views/applications/daycare-application/daycare-application.vue
Update application instructions to match 2021-2022 preschool application period.
> EVAKA-4042: Update application instructions

- frontend/packages/enduser-frontend/src/views/applications/daycare-application/daycare-application.vue
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
> EVAKA-4040: prevent preschool applications for next term before 8.1.2021

- frontend/e2e-test/test/e2e/pages/reports.ts
- frontend/e2e-test/test/e2e/specs/5_employee/placement-sketching-report.spec.ts
- frontend/packages/employee-frontend/src/App.tsx
- frontend/packages/employee-frontend/src/api/reports.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/Reports.tsx
- frontend/packages/employee-frontend/src/components/reports/PlacementSketching.tsx
- frontend/packages/employee-frontend/src/types/reports.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ReportSmokeTests.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/PlacementSketchingReport.kt
> Placement sketching report

- frontend/packages/enduser-frontend/src/localization/app/en.json
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/localization/app/sv.json
Fix `2020` to `2021` from swedish translations.
> Fix old dates from instructions

- frontend/packages/employee-frontend/src/components/unit/tab-unit-information/UnitAccessControl.tsx
Administrator adds special education teachers into units. However, unit supervisors need to know
which special education teachers are assigned to their unit. This change allows unit supervisors
to see a list of special education teachers on the unit page. Unit supervisors are not allowed
to remove or add special education teachers into the unit.
> EVAKA-4100: Unit supervisors see a list of special education teachers

- frontend/packages/enduser-frontend/src/config.ts
> Enable attachments in production

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/reports/PlacementSketching.tsx
- frontend/packages/employee-frontend/src/types/reports.ts
- service/src/main/kotlin/fi/espoo/evaka/reports/PlacementSketchingReport.kt
> Evaka 3996 Placement sketching report: requested changes

- frontend/packages/enduser-frontend/src/localization/app/en.json
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/localization/app/sv.json
Add missing translations for Swedish and English versions.
> Add missing translations for Swedish and English locales

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaPlacementsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaPlacements.kt
Varda has validations for this, so we have to take this into account. Funny that _we_ don't have a validation for this ourselves. 😄
> Use unit closing date as Varda placement's max end date

- frontend/e2e-test/test/e2e/pages/employee/applications/application-read-view.ts
- frontend/e2e-test/test/e2e/specs/2_employee-2/application-transitions.spec.ts
- frontend/packages/employee-frontend/src/components/application-page/DecisionResponse.tsx
Employee should be able to choose any day within two weeks from decision start date
> EVAKA-HOTFIX: update decision start date on acceptance

- service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
> Avoid doing VTJ querys on varda fee data update

- service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentsControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
> Evaka fix delete also application attachments

- message-service/src/main/resources/application.properties
- Hide Spring banner from boot logs, just unnecessary noise in invalid logs
> message-srv: remove noise from logs

- frontend/e2e-test/test/e2e/pages/enduser/enduser-navigation.ts
- frontend/e2e-test/test/e2e/specs/1_application/application-validations.spec.ts
- frontend/packages/enduser-frontend/src/localization/app/en.json
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/localization/app/sv.json
- frontend/packages/enduser-frontend/src/views/applications/daycare-application/daycare-application.vue
> Hide preferred unit selector until preferred start date is selected

- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailClient.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/MockEmailClient.kt
- service/src/main/kotlin/fi/espoo/evaka/identity/Identifiers.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/ParentshipController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PartnershipsController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/controllers/VtjController.kt
- service/src/test/kotlin/fi/espoo/evaka/vtjclient/service/VtjClientServiceTest.kt
> Remove unnecessary "VolttiIdentifier" type

- compose/proxy/nginx.conf
- frontend/packages/citizen-frontend/src/configs/index.ts
- frontend/packages/employee-frontend/src/configs/index.ts
- frontend/packages/enduser-frontend/src/config.ts
- proxy/nginx.conf.template
The previous value was just copied from employee frontend config.
> Use correct citizen frontend sentry dsn

- apigw/src/enduser/routes.ts
- frontend/packages/citizen-frontend/src/Header.tsx
- frontend/packages/citizen-frontend/src/decisions/Decisions.tsx
- frontend/packages/citizen-frontend/src/decisions/types.ts
- frontend/packages/citizen-frontend/src/index.html
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- frontend/packages/employee-frontend/src/components/child-information/assistance-action/AssistanceActionForm.tsx
- frontend/packages/employee-frontend/src/components/child-information/assistance-need/AssistanceNeedForm.tsx
- frontend/packages/employee-frontend/src/components/child-information/placements/PlacementRow.tsx
- frontend/packages/employee-frontend/src/components/child-information/service-need/ServiceNeedForm.tsx
- frontend/packages/employee-frontend/src/components/decision-draft/DecisionDraft.tsx
- frontend/packages/employee-frontend/src/components/group-caretakers/GroupCaretakersModal.tsx
- frontend/packages/employee-frontend/src/components/invoices/InvoicesPage.tsx
- frontend/packages/employee-frontend/src/components/placement-draft/Placements.tsx
- frontend/packages/employee-frontend/src/components/unit/tab-groups/groups/group/GroupUpdateModal.tsx
- frontend/packages/employee-frontend/src/components/unit/tab-placement-proposals/PlacementProposals.tsx
- frontend/packages/lib-components/src/atoms/Link.tsx
- frontend/packages/lib-components/src/molecules/MessageBoxes.tsx
- frontend/packages/lib-components/src/typography.ts
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt
> Evaka 3899 citizen decisions list

- frontend/packages/citizen-frontend/src/decisions/Decisions.tsx
- frontend/packages/citizen-frontend/src/index.html
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- frontend/packages/employee-frontend/src/components/child-information/assistance-action/AssistanceActionForm.tsx
- frontend/packages/employee-frontend/src/components/child-information/assistance-need/AssistanceNeedForm.tsx
- frontend/packages/employee-frontend/src/components/child-information/placements/PlacementRow.tsx
- frontend/packages/employee-frontend/src/components/child-information/service-need/ServiceNeedForm.tsx
- frontend/packages/lib-components/src/atoms/RoundIcon.tsx
- frontend/packages/lib-components/src/molecules/MessageBoxes.tsx
- frontend/packages/lib-components/src/typography.ts
Visual improvements to new citizen frontend decisions list.
> EVAKA-3899 decision list styling

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
> Give instructions how to properly change the fridge partner

- frontend/e2e-test/test/e2e/dev-api/fixtures.ts
- frontend/e2e-test/test/e2e/dev-api/index.ts
- frontend/e2e-test/test/e2e/pages/citizen/citizen-decisions.ts
- frontend/e2e-test/test/e2e/pages/citizen/citizen-homepage.ts
- frontend/e2e-test/test/e2e/specs/0_citizen/citizen-decisions.spec.ts
- frontend/e2e-test/test/e2e/specs/0_citizen/citizen-homepage.spec.ts
- frontend/packages/citizen-frontend/src/decisions/Decisions.tsx
- frontend/packages/lib-components/src/molecules/MessageBoxes.tsx
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
> Citizen decisions list E2E test

- frontend/packages/enduser-frontend/src/localization/app/en.json
Add missing English translations for preschool application attachments
> HOTFIX: Add attachment message translations

- frontend/packages/citizen-frontend/src/App.tsx
- frontend/packages/citizen-frontend/src/Footer.tsx
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
> Citizen footer

- frontend/packages/employee-frontend/src/components/application-page/ApplicationReadView.tsx
- frontend/packages/employee-frontend/src/components/application-page/VTJGuardian.tsx
- frontend/packages/lib-components/src/typography.stories.tsx
- frontend/packages/lib-components/src/typography.ts
Unify typography in application read view.
> HOTFIX: Unify typography in application read view

- frontend/packages/employee-frontend/src/components/unit/tab-unit-information/Occupancy.tsx
Wrong value was passed as prop to the component.
> Fix single day occupancy realized value

- frontend/packages/enduser-frontend/src/localization/app/en.json
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/localization/app/sv.json
- frontend/packages/enduser-frontend/src/utils/helpers.ts
Handle `municipal_school` similarily to `municipal`
> HOTFIX: add missing provider type translation

- .gitattributes
Some developers use WSL, change line endings to support it.
> Change line ending configuration to support WSL

- service/src/main/kotlin/fi/espoo/evaka/reports/PlacementSketchingReport.kt
> Fix placement sketching query OutOfMemory -error

- proxy/Dockerfile
Current build is broken with old ruby version.
> Update ruby in proxy docker image

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/reports/PlacementSketching.tsx
> Show other preferred units in placement sketching report

- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/EmailResponseIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementPlanIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/domain/TimeIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaFeeDataIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
Fetch preschool term from db instead of using hard coded terms
> EVAKA-HOTFIX: Fetch preschool term from db

- frontend/packages/citizen-frontend/src/App.tsx
- frontend/packages/citizen-frontend/src/applications/Applications.tsx
- frontend/packages/citizen-frontend/src/applications/types.ts
- frontend/packages/citizen-frontend/src/header/DesktopNav.tsx
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- frontend/packages/enduser-frontend/src/localization/app/en.json
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/localization/app/sv.json
- frontend/packages/enduser-frontend/src/views/desktop.vue
- frontend/packages/enduser-frontend/src/views/mobile.vue
- service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
> Citizen applications page base

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
The separate clean up for decisions derived from temporary and regular placements caused all decisions derived from placements to be deleted every night.
> Fix Varda derived decision clean up

- frontend/packages/citizen-frontend/src/App.tsx
- frontend/packages/citizen-frontend/src/applications/api.ts
- frontend/packages/citizen-frontend/src/applications/editor/AdditionalDetailsSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationEditor.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ContactInfoSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/DaycareApplicationEditor.tsx
- frontend/packages/citizen-frontend/src/applications/editor/FeeSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/Heading.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ServiceNeedSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/UnitPreferenceSection.tsx
- frontend/packages/citizen-frontend/src/applications/types.ts
- frontend/packages/citizen-frontend/src/decisions/decisions-page/Decisions.tsx
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Add a base for application editor code.
Also, modify new citizen applications endpoint by not returning applications that are hidden from the guardian from the api.
> Citizen application editor base

- .circleci/config.yml
- message-service/README.md
- message-service/build.gradle.kts
- message-service/buildSrc/src/main/kotlin/Version.kt
- message-service/owasp-suppressions.xml
- message-service/src/main/kotlin/fi/espoo/evaka/msg/config/SwaggerConfig.kt
- service-lib/build.gradle.kts
- service/README.md
- service/build.gradle.kts
- service/buildSrc/src/main/kotlin/Version.kt
- service/owasp-suppressions.xml
Add OWASP dependency checks to service and message service.
Update some dependencies with vulnerabilities.
Suppress warnings for false positives and dependencies we can't do anything about.
> OWASP dependency checks

- frontend/packages/citizen-frontend/src/decisions/decision-response-page/DecisionResponse.tsx
> EVAKA-3899: Small fixes

- frontend/packages/employee-frontend/src/api/attendances.ts
- frontend/packages/employee-frontend/src/components/placement-draft/Placements.tsx
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
Sort child attendances children by first name.
> Evaka hotfix sort attendances

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaChildren.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaPlacements.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
There's a mysterious problem in production and I hope this might help debug it. This isn't too spammy so keeping it at `info` level should be fine.
> Log numbers for varda integration data

- service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
When searching finance decision handlers, same handlers are returned
multiple times. Return only distinct results.
> EVAKA-4112 Return only distinct finance decision handlers

- frontend/e2e-test/test/e2e/dev-api/fixtures.ts
- frontend/e2e-test/test/e2e/dev-api/index.ts
- frontend/e2e-test/test/e2e/dev-api/types.ts
- frontend/e2e-test/test/e2e/pages/citizen/citizen-decision-response.ts
- frontend/e2e-test/test/e2e/pages/citizen/citizen-decisions.ts
- frontend/e2e-test/test/e2e/specs/0_citizen/citizen-decisions.spec.ts
- frontend/packages/citizen-frontend/src/decisions/decision-response-page/DecisionResponse.tsx
- frontend/packages/citizen-frontend/src/decisions/decisions-page/ApplicationDecisionsBlock.tsx
- frontend/packages/lib-components/src/atoms/LinkWrapperInlineBlock.tsx
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
> EVAKA-3899: citizen responds to decisions e2e-tests

- frontend/packages/employee-frontend/src/index.scss
Change the html font size to reflect the change to designs.
> EVAKA-HOTFIX change html font size from 15px to 100%

- service/src/main/kotlin/fi/espoo/evaka/application/enduser/daycare/DaycareJsonDeserialize.kt
Fix a (very old) bug in saving other children to application form.
> Fix other children application bug

- frontend/packages/citizen-frontend/src/App.tsx
- frontend/packages/citizen-frontend/src/applications/ApplicationCreation.tsx
- frontend/packages/citizen-frontend/src/applications/ChildApplicationsBlock.tsx
- frontend/packages/citizen-frontend/src/applications/InfoBallWrapper.tsx
- frontend/packages/citizen-frontend/src/applications/api.ts
- frontend/packages/citizen-frontend/src/applications/editor/AdditionalDetailsSection.tsx
- frontend/packages/citizen-frontend/src/auth/Authenticated.tsx
- frontend/packages/citizen-frontend/src/auth/state.tsx
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- frontend/packages/employee-frontend/src/components/person-profile/income/IncomeItemEditor.tsx
- frontend/packages/lib-components/src/atoms/form/Radio.tsx
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
Implement application creation dialog.
Also fix income editor radio button widths since it came kind of free with these changes and this dialog reminded me of it.
> Citizen new application dialog

- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
Custodian information should be updated also when custodian relation is deleted and updated
> Update custodian info on all DVV modification types

- frontend/packages/citizen-frontend/src/applications/api.ts
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormData.ts
- frontend/packages/citizen-frontend/src/applications/editor/DaycareApplicationEditor.tsx
- frontend/packages/citizen-frontend/src/applications/types.ts
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationUpdateIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerEnduser.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationForm.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
> EVAKA-4103: improved application update api

- frontend/e2e-test/test/e2e/pages/citizen/citizen-applications.ts
- frontend/e2e-test/test/e2e/pages/citizen/citizen-homepage.ts
- frontend/e2e-test/test/e2e/specs/0_citizen/citizen-applications-list.spec.ts
- frontend/e2e-test/test/e2e/specs/0_citizen/citizen-homepage.spec.ts
> Citizen application list e2e tests

- frontend/packages/citizen-frontend/src/applications/editor/ApplicationEditor.tsx
- frontend/packages/citizen-frontend/src/applications/editor/DaycareApplicationEditor.tsx
- frontend/packages/citizen-frontend/src/applications/editor/verification/BasicsSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/verification/DaycareApplicationVerificationView.tsx
- frontend/packages/citizen-frontend/src/applications/editor/verification/UnitPreferenceSection.tsx
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- frontend/packages/lib-components/src/atoms/HorizontalLine.tsx
- frontend/packages/lib-components/src/atoms/buttons/ReturnButton.tsx
- frontend/packages/lib-components/src/atoms/form/Checkbox.tsx
Next part: add the remaining content sections.
> EVAKA-4103: application verification view - part 1

- frontend/packages/lib-components/src/atoms/buttons/Button.tsx
- frontend/packages/lib-components/src/atoms/buttons/InlineButton.tsx
- frontend/packages/lib-components/src/atoms/buttons/button-commons.tsx
> button style update

- frontend/packages/employee-frontend/src/components/unit/unit-details/UnitEditor.tsx
- frontend/packages/lib-components/src/atoms/form/InputField.tsx
- frontend/packages/lib-components/src/layout/flex-helpers.ts
> Make necessary unit editor inputs bigger

- frontend/packages/citizen-frontend/src/applications/editor/EditorSection.tsx
Cursor should be a pointer when an item is clickable.
> Editor section cursor to pointer on hover

- frontend/packages/citizen-frontend/src/App.tsx
- frontend/packages/citizen-frontend/src/applications/Applications.tsx
- frontend/packages/citizen-frontend/src/applications/ChildApplicationsBlock.tsx
- frontend/packages/citizen-frontend/src/applications/api.ts
- frontend/packages/citizen-frontend/src/applications/editor/DaycareApplicationEditor.tsx
- frontend/packages/citizen-frontend/src/decisions/decision-response-page/DecisionResponse.tsx
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- frontend/packages/citizen-frontend/src/overlay/Info.tsx
- frontend/packages/citizen-frontend/src/overlay/state.tsx
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
> Evaka 4103 citizen info modal

- frontend/packages/employee-frontend/src/api/absences.ts
- frontend/packages/employee-frontend/src/components/absences/AbsenceTable.tsx
- frontend/packages/employee-frontend/src/components/absences/StaffAttendance.tsx
- frontend/packages/employee-frontend/src/components/absences/utils.ts
- frontend/packages/employee-frontend/src/types/absence.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/AbsenceServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/PresenceReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
Filter holidays out from absence diary columns and calculate the diary columns in back end. Also, take holidays into account on reports.
> EVAKA-4114 holidays on absences and reports

- frontend/e2e-test/test/e2e/dev-api/fixtures.ts
- frontend/e2e-test/test/e2e/pages/citizen/citizen-applications.ts
- frontend/e2e-test/test/e2e/specs/0_citizen/citizen-applications-list.spec.ts
> E2E test for citizen deleting unprocessed applications

- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiUpdateService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/Timeline.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
- service/src/test/kotlin/fi/espoo/evaka/shared/TimelineTest.kt
> Execute Koski planning inside an async job

- service/src/main/resources/db/migration/V33__drop_service_need_temporary.sql
- service/src/main/resources/migrations.txt
The service needs have been migrated to the new placement types in production already.
> EVAKA-4124 drop service need's temporary column

- frontend/packages/citizen-frontend/src/Footer.tsx
- frontend/packages/citizen-frontend/src/applications/ApplicationCreation.tsx
- frontend/packages/citizen-frontend/src/applications/editor/EditorSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/FileUpload.tsx
- frontend/packages/citizen-frontend/src/applications/editor/unit-preference/PreferredUnitBox.tsx
- frontend/packages/citizen-frontend/src/applications/editor/verification/BasicsSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/verification/UnitPreferenceSection.tsx
- frontend/packages/citizen-frontend/src/applications/read-view/ApplicationReadView.tsx
- frontend/packages/citizen-frontend/src/header/Logo.tsx
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- frontend/packages/lib-components/src/atoms/Chip.tsx
- frontend/packages/lib-components/src/atoms/ExternalLink.tsx
- frontend/packages/lib-components/src/atoms/HorizontalLine.tsx
- frontend/packages/lib-components/src/atoms/LinkWrapperInlineBlock.tsx
- frontend/packages/lib-components/src/atoms/form/MultiSelect.tsx
- frontend/packages/lib-components/src/layout/ButtonContainer.tsx
- frontend/packages/lib-components/src/molecules/date-picker/DatePickerDay.tsx
- frontend/packages/lib-components/src/molecules/date-picker/DatePickerInput.tsx
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
> Add missing localizations and copyright texts

- apigw/src/shared/routes/auth/saml/index.ts
- frontend/packages/enduser-frontend/src/views/navigation-view.vue
> Pass user locale as suomi.fi auth request param

- service-lib/src/main/kotlin/fi/espoo/voltti/logging/loggers/AppMiscLoggers.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
Do Varda fee data updates before sending new fee data. This should prevent fee data from overlapping in Varda even temporarily. Also, log request url, method, body and response message when request to Varda fails.
> Varda fee data update consistency

- frontend/e2e-test/test/e2e/dev-api/fixtures.ts
- frontend/e2e-test/test/e2e/dev-api/index.ts
- frontend/e2e-test/test/e2e/dev-api/types.ts
- frontend/e2e-test/test/e2e/pages/employee/applications/application-list-view.ts
- frontend/e2e-test/test/e2e/specs/2_employee-2/application-search.spec.ts
- frontend/packages/citizen-frontend/src/applications/editor/unit-preference/UnitsSubSection.tsx
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/applications/ApplicationsFilters.tsx
- frontend/packages/employee-frontend/src/components/applications/ApplicationsPage.tsx
- frontend/packages/employee-frontend/src/components/common/Filters.tsx
- frontend/packages/employee-frontend/src/components/fee-decisions/FeeDecisionFilters.tsx
- frontend/packages/employee-frontend/src/components/invoices/InvoiceFilters.tsx
- frontend/packages/employee-frontend/src/state/application-ui.tsx
- frontend/packages/employee-frontend/src/types/application.ts
- frontend/packages/lib-components/src/atoms/form/MultiSelect.tsx
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Update application list search filters for service voucher applications.
Changes:
* Change area filter from a set of checkboxes into a multi select
* Move application type filter under unit filter
* Move secondary units checkbox under unit filter multi select
* Add a new voucher application filter under transfer application filter
* Add an e2e test for the new filter
> EVAKA-3770 voucher application search filters

- frontend/packages/citizen-frontend/src/applications/api.ts
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Warn user when they are attempting to create a duplicate application.
> Fix duplicate application warning bug

- .circleci/config.yml
- service/build-docker.sh
- service/build.gradle.kts
Preparations to allow using evaka-service in a Gradle composite build
> Tampere backend preparations

- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModifications.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
> Make SSN nullable

- service/src/main/kotlin/fi/espoo/evaka/pis/service/FamilyInitializerService.kt
Logging helps diagnosing conflict cases later
> Log conflict cases in FamilyInitializerService

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/applications/ApplicationsList.tsx
- frontend/packages/employee-frontend/src/types/application.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
Show current (or future if none exist) placement unit in applications list and add an endpoint for a scheduled job that cancels all outdated transfer applications.
> EVAKA-3956 transfer application improvements

- apigw/src/enduser/publicRoutes.ts
- frontend/packages/citizen-frontend/src/App.tsx
- frontend/packages/citizen-frontend/src/Footer.tsx
- frontend/packages/citizen-frontend/src/applications/ApplicationCreation.tsx
- frontend/packages/citizen-frontend/src/applications/Applications.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationEditor.tsx
- frontend/packages/citizen-frontend/src/applications/read-view/ApplicationReadView.tsx
- frontend/packages/citizen-frontend/src/decisions/decision-response-page/DecisionResponseList.tsx
- frontend/packages/citizen-frontend/src/decisions/decisions-page/Decisions.tsx
- frontend/packages/citizen-frontend/src/header/DesktopNav.tsx
- frontend/packages/citizen-frontend/src/header/Header.tsx
- frontend/packages/citizen-frontend/src/header/MobileNav.tsx
- frontend/packages/citizen-frontend/src/header/const.ts
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- frontend/packages/citizen-frontend/src/map/MapBox.tsx
- frontend/packages/citizen-frontend/src/map/MapView.tsx
- frontend/packages/citizen-frontend/src/map/SearchSection.tsx
- frontend/packages/citizen-frontend/src/map/UnitList.tsx
- frontend/packages/citizen-frontend/src/map/UnitListItem.tsx
- frontend/packages/citizen-frontend/src/map/UnitSearchPanel.tsx
- frontend/packages/citizen-frontend/src/map/const.ts
- frontend/packages/lib-icons/free-icons.ts
- frontend/packages/lib-icons/index.ts
- frontend/packages/lib-icons/pro-icons.ts
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
list units, filter by language, improve layout
desktop:
mobile:
> EVAKA-4115: listing units

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaChildren.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaPlacements.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
Preparatory daycare placements were not included in Varda placement integration since unlike with decision types it has its own placement type.
> Varda include preparatory daycare placements

- message-service/src/main/kotlin/fi/espoo/evaka/msg/config/JwtConfig.kt
- service-lib/src/main/kotlin/fi/espoo/voltti/auth/JwtKeys.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/JwtConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/DevDataInitializer.kt
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/service/persondetails/MockPersonDetailsService.kt
This one commit was accidentally lost during force push :grimacing:
> Tampere backend preparations part 2

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionDraftService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
Do not cancel transfer applications that are waiting for confirmation or that are already accepted or rejected. Also clean up any related placement plans and decision drafts.
> EVAKA-3956 transfer application cancelling

- frontend/packages/employee-frontend/src/components/ChildInformation.tsx
- frontend/packages/employee-frontend/src/components/Header.tsx
- frontend/packages/employee-frontend/src/components/PersonProfile.tsx
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionController.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedController.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionController.kt
Hide applications, decisions and assistance need and actions from finance employees.
> EVAKA-4136 hide info from finance employees

- frontend/packages/citizen-frontend/src/applications/editor/verification/AdditionalDetailsSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/verification/ApplicationVerificationView.tsx
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
Add translations to verification view
> EVAKA-4103 translate verification view

- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/DaycareEditIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/LocationServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
- service/src/main/resources/db/migration/V35__create_round_the_clock_field.sql
- service/src/main/resources/migrations.txt
Summary:
Re-enable the legacy round the clock checkbox from unit editor for front end filtering purposes.
> Round the clock flag

- frontend/packages/citizen-frontend/src/App.tsx
- frontend/packages/citizen-frontend/src/applications/ApplicationCreation.tsx
- frontend/packages/citizen-frontend/src/applications/Applications.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormClub.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormDaycare.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormPreschool.tsx
- frontend/packages/citizen-frontend/src/applications/editor/EditorSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/FileUpload.tsx
- frontend/packages/citizen-frontend/src/applications/editor/contact-info/GuardianSubSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/service-need/PreferredStartSubSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/unit-preference/PreferredUnitBox.tsx
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- frontend/packages/lib-components/src/atoms/Chip.tsx
- frontend/packages/lib-components/src/atoms/RoundIcon.tsx
- frontend/packages/lib-components/src/atoms/buttons/IconButton.tsx
- frontend/packages/lib-components/src/atoms/buttons/InlineButton.tsx
- frontend/packages/lib-components/src/atoms/buttons/ReturnButton.tsx
- frontend/packages/lib-components/src/atoms/form/InputField.tsx
- frontend/packages/lib-components/src/layout/Container.tsx
- frontend/packages/lib-components/src/molecules/ExpandingInfo.tsx
- frontend/packages/lib-components/src/molecules/date-picker/DatePicker.tsx
- frontend/packages/lib-components/src/molecules/date-picker/DatePickerInput.tsx
> EVAKA-4103 Acessibility fixes

- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- frontend/packages/citizen-frontend/src/map/MapBox.tsx
- frontend/packages/citizen-frontend/src/map/MapView.tsx
- frontend/packages/citizen-frontend/src/map/SearchInput.tsx
- frontend/packages/citizen-frontend/src/map/SearchSection.tsx
- frontend/packages/citizen-frontend/src/map/UnitDetailsPanel.tsx
- frontend/packages/citizen-frontend/src/map/UnitList.tsx
- frontend/packages/citizen-frontend/src/map/UnitListItem.tsx
- frontend/packages/citizen-frontend/src/map/UnitSearchPanel.tsx
- frontend/packages/citizen-frontend/src/map/api.ts
- frontend/packages/citizen-frontend/src/map/distances.ts
- frontend/packages/lib-common/src/api-types/units/PublicUnit.ts
- frontend/packages/lib-components/src/atoms/form/MultiSelect.tsx
- frontend/packages/lib-components/src/colors.ts
> EVAKA-4115: Implement citizen map address search, filters, details view etc.

- frontend/e2e-test/test/e2e/pages/citizen/citizen-application-new.ts
- frontend/e2e-test/test/e2e/specs/0_citizen/citizen-daycare-application-create.spec.ts
- frontend/packages/citizen-frontend/src/applications/ApplicationCreation.tsx
- frontend/packages/citizen-frontend/src/applications/ChildApplicationsBlock.tsx
- frontend/packages/citizen-frontend/src/applications/api.ts
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormClub.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormDaycare.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormPreschool.tsx
- frontend/packages/citizen-frontend/src/applications/editor/Heading.tsx
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- frontend/packages/lib-common/src/api-types/application/ApplicationsOfChild.ts
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
For transfer applications, show piece of text next to the title on application list & editor
> EVAKA-4103 indicate transfer applications

- frontend/e2e-test/test/e2e/dev-api/fixtures.ts
- frontend/e2e-test/test/e2e/dev-api/index.ts
- frontend/e2e-test/test/e2e/dev-api/types.ts
- frontend/packages/citizen-frontend/src/applications/api.ts
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormClub.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormDaycare.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormPreschool.tsx
- frontend/packages/citizen-frontend/src/applications/editor/unit-preference/UnitPreferenceSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/unit-preference/UnitsSubSection.tsx
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
When shift care checkbox is marked, filter the units that do not offer shift care.
> Filter units by shift care in application editor

- frontend/packages/citizen-frontend/src/applications/read-view/ApplicationReadView.tsx
- frontend/packages/citizen-frontend/src/applications/read-view/ApplicationReadViewContents.tsx
> EVAKA:4103: citizen read-only application views

- frontend/packages/employee-frontend/src/components/unit/unit-details/UnitDetailsPage.tsx
> EVAKA: include email when selecting unit finance decision handler

- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/ConfirmedOccupancyTest.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
This changes the coefficients to what they were before. Part week children caused the occupancy percentages to be off.
> Use placement type only for daycare occupancy

- frontend/packages/employee-frontend/src/components/reports/StartingPlacements.tsx
- frontend/packages/employee-frontend/src/types/reports.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/StartingPlacementsReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/StartingPlacementsReport.kt
> EVAKA-4134: add care area to starting placements report

- frontend/e2e-test/test/e2e/pages/citizen/citizen-application-editor.ts
- frontend/packages/citizen-frontend/src/applications/ChildApplicationsBlock.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationEditor.tsx
- frontend/packages/citizen-frontend/src/applications/editor/EditorSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/verification/ApplicationVerificationView.tsx
- frontend/packages/citizen-frontend/src/applications/editor/verification/BasicsSection.tsx
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- frontend/packages/lib-components/src/atoms/Chip.tsx
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
- Minor improvements for citizen application flow
- fix selection chips
> EVAKA: citizen ux improvements

- frontend/packages/citizen-frontend/src/applications/editor/verification/ContactInfoSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/verification/UnitPreferenceSection.tsx
> EVAKA-4103: include quick selection children in verification view

- frontend/e2e-test/test/e2e/pages/citizen/citizen-application-editor.ts
- frontend/e2e-test/test/e2e/pages/citizen/citizen-applications.ts
- frontend/e2e-test/test/e2e/specs/0_citizen/citizen-daycare-application-create.spec.ts
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationEditor.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormClub.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormDaycare.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormPreschool.tsx
- frontend/packages/citizen-frontend/src/applications/editor/service-need/PreferredStartSubSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/service-need/ServiceNeedSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/validations.ts
- frontend/packages/citizen-frontend/src/form-validation.ts
- frontend/packages/citizen-frontend/src/localization/en.ts
- frontend/packages/citizen-frontend/src/localization/fi.ts
- frontend/packages/citizen-frontend/src/localization/sv.ts
- frontend/packages/lib-common/src/local-date.ts
- frontend/packages/lib-components/src/atoms/form/InputField.tsx
- frontend/packages/lib-components/src/molecules/date-picker/DatePicker.tsx
- frontend/packages/lib-components/src/molecules/date-picker/DatePickerDay.tsx
> Evaka 4103 datepicker disabled days

- docs/diagrams/src/evaka-context.puml
Update C4 context diagrams.
* Add new roles
* Group municipal and other external systems
* Add new external systems
> Update C4 Context diagrams

- frontend/packages/employee-frontend/src/components/applications/ApplicationsFilters.tsx
Updates the unit list when selecting an area. This is to help user not to select an area/unit combination that does not exist.
> EVAKA-HOTFIX update unit filter list when changing the area filter

- frontend/packages/citizen-frontend/src/applications/ApplicationCreation.tsx
- frontend/packages/citizen-frontend/src/applications/Applications.tsx
- frontend/packages/citizen-frontend/src/applications/editor/FeeSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/Heading.tsx
- frontend/packages/citizen-frontend/src/applications/editor/contact-info/ChildSubSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/service-need/PreferredStartSubSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
- frontend/packages/citizen-frontend/src/applications/editor/unit-preference/SiblingBasisSubSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/unit-preference/UnitsSubSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/verification/ApplicationVerificationView.tsx
- frontend/packages/citizen-frontend/src/decisions/decisions-page/Decisions.tsx
- frontend/packages/citizen-frontend/src/localization/en.tsx
- frontend/packages/citizen-frontend/src/localization/fi.tsx
- frontend/packages/citizen-frontend/src/localization/sv.tsx
> Get rid of dangerouslySetInnerHTML in citizen frontend

- frontend/packages/citizen-frontend/src/applications/editor/FileUpload.tsx
- frontend/packages/citizen-frontend/src/applications/editor/service-need/AssistanceNeedSubSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/verification/AdditionalDetailsSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/verification/ServiceNeedSection.tsx
- frontend/packages/citizen-frontend/src/header/MobileNav.tsx
- frontend/packages/lib-components/src/atoms/HorizontalLine.tsx
- frontend/packages/lib-components/src/atoms/buttons/ReturnButton.tsx
> EVAKA-4103: citizen frontend UI/UX fixes

- frontend/packages/citizen-frontend/src/applications/editor/validations.ts
- frontend/packages/citizen-frontend/src/decisions/api.ts
- frontend/packages/citizen-frontend/src/decisions/decision-response-page/DecisionResponse.tsx
- frontend/packages/citizen-frontend/src/decisions/types.ts
- frontend/packages/lib-components/src/molecules/date-picker/DatePicker.tsx
- frontend/packages/lib-components/src/molecules/date-picker/DatePickerDay.tsx
- frontend/packages/lib-components/src/molecules/date-picker/DatePickerInput.tsx
Changed the now deprecated old datepicker to the new datepicker when accepting a decision.
> Evaka 4103 remove old datepicker

- frontend/packages/citizen-frontend/src/localization/en.tsx
- frontend/packages/citizen-frontend/src/localization/fi.tsx
- frontend/packages/citizen-frontend/src/localization/sv.tsx
* Remove notion about two weeks handling time for shift care. (There is
no two weeks handling time for applications for shift care)
* Improve Finnish translation of assistance need description
* Improve Finnish translation of children of spouse
> EVAKA-4140: Improve translations for citizen application

- frontend/e2e-test/test/e2e/dev-api/data-init.ts
- frontend/e2e-test/test/e2e/dev-api/fixtures.ts
- frontend/e2e-test/test/e2e/pages/citizen/citizen-application-editor.ts
- frontend/e2e-test/test/e2e/specs/0_citizen/citizen-daycare-application-create.spec.ts
- frontend/packages/citizen-frontend/src/applications/ChildApplicationsBlock.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormData.ts
- frontend/packages/citizen-frontend/src/applications/editor/contact-info/ChildSubSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/service-need/PreferredStartSubSection.tsx
- frontend/packages/citizen-frontend/src/decisions/decision-response-page/DecisionResponse.tsx
- frontend/packages/citizen-frontend/src/decisions/decision-response-page/DecisionResponseList.tsx
- frontend/packages/citizen-frontend/src/decisions/decisions-page/ApplicationDecisionsBlock.tsx
- frontend/packages/citizen-frontend/src/decisions/decisions-page/Decisions.tsx
- frontend/packages/citizen-frontend/src/decisions/shared.tsx
- frontend/packages/citizen-frontend/src/localization/en.tsx
- frontend/packages/lib-components/src/colors.stories.tsx
- frontend/packages/lib-components/src/layout/flex-helpers.ts
- frontend/packages/lib-components/src/molecules/modals/FormModal.tsx
- frontend/packages/lib-components/src/white-space.ts
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/service/persondetails/NewMockPersonDetailsService.kt
- service/src/main/resources/mock-vtj-data.json
- service/src/test/kotlin/fi/espoo/evaka/vtjclient/service/MockDataServiceTest.kt
- Make modals fit mobile screens
- Split "remove application" link on another line on mobile
- Do not show Gap on mobile
- Fix english mailto address
- Make "you have 1 pending applications" spacing bigger
- Fix application status icon & text left spacing
> UI polishing

- frontend/packages/citizen-frontend/src/applications/editor/validations.ts
- frontend/packages/lib-common/src/local-date.ts
- frontend/packages/lib-components/src/molecules/date-picker/DatePickerDay.tsx
> EVAKA-4103: fix valid preferred start dates

- service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/application/SendApplicationReceivedEmailAsyncJobs.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
> Do not try to resend email is email address is missing.

- frontend/packages/employee-frontend/src/components/unit/unit-details/CreateUnitPage.tsx
- frontend/packages/employee-frontend/src/components/unit/unit-details/UnitDetailsPage.tsx
> EVAKA: hide null emails on finance handler dropdown

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/DecisionGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
Fix age coeffiecient according to new spec: https://voltti.atlassian.net/browse/EVAKA-4044
> EVAKA-4044 update voucher value age coefficient

- service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
> Log actual created job count

- frontend/packages/citizen-frontend/src/localization/en.tsx
- frontend/packages/citizen-frontend/src/localization/sv.tsx
> Lost in translation

- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
> EVAKA-HOTFIX: add alternative accepted magic bytes for jpeg

- frontend/packages/citizen-frontend/src/header/DesktopNav.tsx
- frontend/packages/citizen-frontend/src/header/MobileNav.tsx
- frontend/packages/citizen-frontend/src/map/MapBox.tsx
> EVAKA: fix lang menu z-index and nav link active state

- frontend/packages/citizen-frontend/src/localization/en.tsx
- frontend/packages/citizen-frontend/src/localization/fi.tsx
- frontend/packages/citizen-frontend/src/localization/sv.tsx
- frontend/packages/citizen-frontend/src/map/MapView.tsx
Use smaller side margins on large screens to utilize the screen space better
> Map: Better space usage for large screens

- frontend/README.md
- frontend/package.json
- frontend/packages/citizen-frontend/src/header/MobileNav.tsx
> Remove leftover vue references

- frontend/packages/employee-frontend/src/components/unit/tab-unit-information/UnitInformation.tsx
- frontend/packages/employee-frontend/src/constants.ts
- frontend/packages/employee-mobile-frontend/src/components/attendances/AttendanceChildPage.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/AttendanceList.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/AttendancePageWrapper.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/ChildListItem.tsx
- frontend/packages/employee-mobile-frontend/src/components/mobile/components.tsx
- frontend/packages/employee-mobile-frontend/src/index.css
Added new styles for ChildListItem and made some other improvements to styles.
> EVAKA-4030 new styles for child list item

- apigw/src/enduser/publicRoutes.ts
- frontend/packages/citizen-frontend/src/map/MapView.tsx
- frontend/packages/citizen-frontend/src/map/api.ts
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
> EVAKA-HOTFIX: fix unit filtering on map

- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/DaycareDailyNote.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/DaycareDailyNoteController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/DaycareDailyNoteQueries.kt
- service/src/main/resources/db/migration/V36__daycare_daily_note.sql
- service/src/main/resources/migrations.txt
Backend for https://www.figma.com/file/8FXipaHxJcHwwfCl273PWS/Kasvattajan-mobiili?node-id=1700%3A5
> Daycare daily note api

- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
- service/src/main/resources/WEB-INF/templates/daycare/daycare-acceptance-form.html
- service/src/main/resources/WEB-INF/templates/daycare/daycare-decision-page1.html
- service/src/main/resources/WEB-INF/templates/daycare/transfer/daycare-acceptance-form.html
- service/src/main/resources/WEB-INF/templates/daycare/transfer/daycare-decision-page1.html
- service/src/main/resources/WEB-INF/templates/daycare/voucher/daycare-acceptance-form.html
- service/src/main/resources/WEB-INF/templates/daycare/voucher/daycare-decision-page1.html
> EVAKA-4143 hide daycare time from preschool daycare decisions

- frontend/packages/citizen-frontend/src/localization/en.tsx
- frontend/packages/citizen-frontend/src/localization/fi.tsx
- frontend/packages/citizen-frontend/src/localization/sv.tsx
- frontend/packages/citizen-frontend/src/map/MapBox.tsx
- frontend/packages/citizen-frontend/src/map/UnitDetailsPanel.tsx
- frontend/packages/citizen-frontend/src/map/const.ts
> Add external link for service voucher units

- frontend/packages/citizen-frontend/src/localization/sv.tsx
> Latest swedish translations

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/decision-draft/DecisionDraft.tsx
Update the decision draft type labels for preschool and preparatory daycare.
> EVAKA-4144 decision draft labels

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Hide cancelled applications from citizen.
> EVAKA-HOTFIX hide cancelled applications from citizen

- frontend/packages/citizen-frontend/src/decisions/decisions-page/ApplicationDecisionsBlock.tsx
- frontend/packages/citizen-frontend/src/localization/sv.tsx
- frontend/packages/lib-components/src/white-space.ts
-latest swedish translations (from sveb)
-missing club translations (by GT)
-fix gap media query
> Evaka fix citizen fixes

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/BulletinIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/Bulletin.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinControllerEmployee.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinQueries.kt
> EVAKA-3952: add integration smoke tests and fix bugs

- frontend/packages/lib-components/src/molecules/date-picker/DatePicker.tsx
Force day picker to be at least 16 pixels from both screen edges. This is only relevant with mobile screen sizes when the date picker input is close enough to the edge.
> EVAKA-HOTFIX day picker in mobile

- frontend/packages/employee-frontend/src/components/ApplicationPage.tsx
- frontend/packages/employee-frontend/src/components/application-page/DecisionResponse.tsx
Use AsyncButton to indicate request state and scroll back to the position the user was in before the page was refreshed.
> EVAKA-4146 decision response ux

- frontend/packages/citizen-frontend/src/localization/en.tsx
- frontend/packages/citizen-frontend/src/localization/sv.tsx
Swedish and English phrases were grammatically incorrect and unnecessarily split into two parts around the date.
> EVAKA-HOTFIX improve decision response localizations

- message-service/build.gradle.kts
- message-service/buildSrc/src/main/kotlin/Version.kt
- message-service/gradle/wrapper/gradle-wrapper.properties
- message-service/src/integrationTest/resources/application-integration-test.yaml
- service-lib/build.gradle.kts
- service/build.gradle.kts
- service/buildSrc/src/main/kotlin/Version.kt
- service/gradle/wrapper/gradle-wrapper.properties
- service/src/integrationTest/resources/application-integration-test.yaml
> Upgrade most backend dependencies

- frontend/packages/citizen-frontend/src/App.tsx
- frontend/packages/citizen-frontend/src/config.ts
- frontend/packages/citizen-frontend/src/header/DesktopNav.tsx
- frontend/packages/citizen-frontend/src/header/MobileNav.tsx
- frontend/packages/citizen-frontend/src/index.css
- frontend/packages/citizen-frontend/src/localization/en.tsx
- frontend/packages/citizen-frontend/src/localization/fi.tsx
- frontend/packages/citizen-frontend/src/localization/sv.tsx
- frontend/packages/citizen-frontend/src/messages/MessageListItem.tsx
- frontend/packages/citizen-frontend/src/messages/MessageReadView.tsx
- frontend/packages/citizen-frontend/src/messages/MessagesList.tsx
- frontend/packages/citizen-frontend/src/messages/MessagesPage.tsx
- frontend/packages/citizen-frontend/src/messages/api.ts
- frontend/packages/citizen-frontend/src/messages/const.ts
- frontend/packages/citizen-frontend/src/messages/types.ts
- frontend/packages/lib-components/src/colors.ts
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinQueries.kt
> EVAKA-3952: citizen reads bulletins

- frontend/packages/citizen-frontend/src/applications/ApplicationCreation.tsx
- frontend/packages/citizen-frontend/src/applications/Applications.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationEditor.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormClub.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormDaycare.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationFormPreschool.tsx
- frontend/packages/citizen-frontend/src/applications/read-view/ApplicationReadView.tsx
- frontend/packages/citizen-frontend/src/decisions/decision-response-page/DecisionResponseList.tsx
- frontend/packages/citizen-frontend/src/decisions/decisions-page/Decisions.tsx
- frontend/packages/citizen-frontend/src/map/MapView.tsx
- frontend/packages/citizen-frontend/src/useTitle.tsx
> Add document.title to every citizen page

- .circleci/config.yml
- frontend/README.md
- frontend/init-pro-icons.sh
- frontend/package.json
- frontend/packages/lib-icons/package.json
- frontend/unpack-pro-icons.sh
- frontend/yarn.lock
Install pro icons manually directly to node_modules, so yarn won't try to resolve them and fail
> Support both free and pro icon sets once again

- frontend/packages/employee-frontend/src/App.tsx
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/Header.tsx
- frontend/packages/employee-frontend/src/components/messages/MessagesPage.tsx
- frontend/packages/employee-frontend/src/config.ts
Initialize dummy MessagesPage behind a feature flag.
> EVAKA-3952 unit supervisor messages

- frontend/packages/citizen-frontend/src/localization/en.tsx
Got a proper translation for club info text from Sari.
> EVAKA-HOTFIX Proper translation for club info text

- frontend/packages/employee-frontend/src/components/messages/MessageEditor.tsx
- frontend/packages/employee-frontend/src/components/messages/MessagesPage.tsx
- frontend/packages/employee-frontend/src/components/messages/api.ts
- frontend/packages/employee-frontend/src/components/messages/types.ts
- frontend/packages/lib-components/src/atoms/buttons/IconButton.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/BulletinIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinControllerEmployee.kt
> EVAKA-3952: unpolished version of employee sends messages UI

- frontend/packages/employee-frontend/src/App.tsx
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/messages/MessagesPage.tsx
- frontend/packages/employee-frontend/src/components/messages/UnitsList.tsx
- frontend/packages/employee-frontend/src/components/messages/api.ts
- frontend/packages/employee-frontend/src/components/messages/types.ts
Simple first draft of employee's unit list in the messaging section
> EVAKA-3952 units in employee's message view

- frontend/packages/employee-frontend/src/components/messages/MessageBoxes.tsx
- frontend/packages/employee-frontend/src/components/messages/MessagesPage.tsx
- frontend/packages/employee-frontend/src/components/messages/UnitsList.tsx
- frontend/packages/employee-frontend/src/components/messages/api.ts
- frontend/packages/employee-frontend/src/components/messages/types.ts
> EVAKA-3952 employee unit message boxes

- frontend/packages/citizen-frontend/src/messages/MessageListItem.tsx
- frontend/packages/employee-frontend/package.json
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/messages/MessageBoxes.tsx
- frontend/packages/employee-frontend/src/components/messages/MessageEditor.tsx
- frontend/packages/employee-frontend/src/components/messages/MessageList.tsx
- frontend/packages/employee-frontend/src/components/messages/MessageReadView.tsx
- frontend/packages/employee-frontend/src/components/messages/MessagesPage.tsx
- frontend/packages/employee-frontend/src/components/messages/UnitsList.tsx
- frontend/packages/employee-frontend/src/config.ts
- frontend/yarn.lock
> EVAKA-3952: employee sends and views bulletins - part 2

- frontend/packages/employee-frontend/src/components/messages/MessagesPage.tsx
- frontend/packages/employee-frontend/src/components/messages/api.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/BulletinIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/Bulletin.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinControllerEmployee.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinQueries.kt
- service/src/main/resources/db/migration/V39__add_unit_id_to_bulletin.sql
- service/src/main/resources/migrations.txt
Require param in draft creation
Add foreign key & required api param
> EVAKA-3952 bulletin references daycare

- frontend/packages/employee-frontend/src/components/messages/MessagesPage.tsx
> HOTFIX: fix broken MessagesPage

- frontend/packages/citizen-frontend/src/applications/editor/service-need/PreferredStartSubSection.tsx
- frontend/packages/citizen-frontend/src/localization/en.tsx
- frontend/packages/citizen-frontend/src/localization/fi.tsx
- frontend/packages/citizen-frontend/src/localization/sv.tsx
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
Do not check duplicates for club applications and add the newest club term to citizen application.
The solutions are not ideal, but this is pretty urgent.
> EVAKA-HOTFIX club application terms and duplicates

- frontend/packages/employee-frontend/src/components/messages/MessageBoxes.tsx
- frontend/packages/employee-frontend/src/components/messages/MessageList.tsx
- frontend/packages/employee-frontend/src/components/messages/MessageReadView.tsx
- frontend/packages/employee-frontend/src/components/messages/MessagesPage.tsx
- frontend/packages/employee-frontend/src/components/messages/UnitsList.tsx
- frontend/packages/employee-frontend/src/components/messages/api.ts
- frontend/packages/employee-frontend/src/components/messages/types.ts
- frontend/packages/employee-frontend/src/index.css
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/BulletinIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/Bulletin.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinControllerEmployee.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinQueries.kt
- service/src/main/resources/db/migration/V40__unit_id_in_bulletin_as_not_null.sql
- service/src/main/resources/migrations.txt
> EVAKA-3952: UI fixes to messaging

- .circleci/config.yml
- frontend/e2e-test/package.json
- frontend/package.json
- frontend/packages/employee-frontend/src/components/reports/ReportDownload.tsx
- frontend/packages/lib-components/src/colors.stories.tsx
- frontend/packages/lib-components/src/layout/PageWrapper.tsx
> EVAKA: run ts type-check in pipeline

- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinQueries.kt
- service/src/main/resources/db/migration/V43__rename_bulletin_guardian_id.sql
- service/src/main/resources/migrations.txt
> EVAKA-3952: send bulletins also to head of child

- frontend/packages/citizen-frontend/src/localization/sv.tsx
> Fix swedish service voucher link address

- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/integrationTest/resources/application-integration-test.yaml
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
- enable pending decision reminder email sending
- do not wipe out existing person email if application has none
> Evaka fix enable pending decision reminder sending

- frontend/packages/citizen-frontend/src/App.tsx
- frontend/packages/citizen-frontend/src/header/DesktopNav.tsx
- frontend/packages/citizen-frontend/src/header/Header.tsx
- frontend/packages/citizen-frontend/src/header/MobileNav.tsx
- frontend/packages/citizen-frontend/src/messages/MessagesPage.tsx
- frontend/packages/citizen-frontend/src/messages/api.ts
- frontend/packages/citizen-frontend/src/messages/state.tsx
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinQueries.kt
Show number of unread messages in nav
> EVAKA-3952-unread-bulletins-count

- frontend/packages/employee-mobile-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-mobile-frontend/src/components/common/BottomNavbar.tsx
- frontend/packages/lib-icons/free-icons.ts
- frontend/packages/lib-icons/index.ts
- frontend/packages/lib-icons/pro-icons.ts
Create bottom navigation component.
Looks like this:
Takes two props: Which section is selected at the moment (if any) and how many messages are unread.
> EVAKA-4030 Create bottom navbar

- frontend/e2e-test/test/e2e/pages/employee/mobile/mobile-groups.ts
- frontend/e2e-test/test/e2e/specs/6_mobile/dailynotes.spec.ts
- frontend/packages/employee-mobile-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-mobile-frontend/src/components/attendances/AttendanceList.tsx
Indicator text for employee mobile attendance UI that list is empty
https://www.figma.com/file/8FXipaHxJcHwwfCl273PWS/Kasvattajan-mobiili?node-id=1701%3A2519
> Empty list indicator text for employee mobile

- frontend/packages/employee-mobile-frontend/src/App.tsx
- frontend/packages/employee-mobile-frontend/src/api/attendances.ts
- frontend/packages/employee-mobile-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-mobile-frontend/src/components/attendances/AbsenceSelector.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/Absences.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/AttendanceChildComing.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/AttendanceChildDeparted.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/AttendanceChildPage.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/AttendanceChildPresent.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/AttendancePageWrapper.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/ChildListItem.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/actions/MarkAbsent.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/actions/MarkDeparted.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/actions/MarkPresent.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/components.tsx
- frontend/packages/employee-mobile-frontend/src/components/attendances/notes/DailyNote.tsx
- frontend/packages/employee-mobile-frontend/src/components/mobile/components.tsx
- frontend/packages/lib-components/src/layout/flex-helpers.ts
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/daycarydailynote/DaycareDailyNote.kt
> EVAKA-4030 new child page

- .circleci/config.yml
- frontend/e2e-test/package.json
- frontend/e2e-test/test/e2e/dev-api/fixtures.ts
- frontend/e2e-test/test/e2e/dev-api/index.ts
- frontend/e2e-test/test/e2e/pages/citizen/citizen-homepage.ts
- frontend/e2e-test/test/e2e/pages/citizen/citizen-messages.ts
- frontend/e2e-test/test/e2e/pages/employee/home.ts
- frontend/e2e-test/test/e2e/pages/employee/messaging/messages-page.ts
- frontend/e2e-test/test/e2e/specs/7_messaging/sending-and-receiving-bulletins.spec.ts
- frontend/packages/citizen-frontend/src/header/DesktopNav.tsx
- frontend/packages/citizen-frontend/src/messages/MessageListItem.tsx
- frontend/packages/citizen-frontend/src/messages/MessageReadView.tsx
- frontend/packages/employee-frontend/src/components/messages/MessageBoxes.tsx
- frontend/packages/employee-frontend/src/components/messages/MessageEditor.tsx
- frontend/packages/employee-frontend/src/components/messages/UnitsList.tsx
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
> EVAKA-3952: messaging e2e tests

- frontend/packages/employee-frontend/src/components/person-profile/PersonFridgeChild.tsx
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/ParentshipController.kt
> EVAKA: unit supervisor can delete conflict parentships

- frontend/e2e-test/test/e2e/dev-api/fixtures.ts
- frontend/e2e-test/test/e2e/specs/7_messaging/sending-and-receiving-bulletins.spec.ts
> EVAKA-HOTFIX: fix e2e rebase issue

- frontend/packages/citizen-frontend/src/localization/fi.tsx
Add better instructions when applying service voucher.
> EVAKA-4156: Improve instructions for service voucher

- frontend/src/citizen-frontend/localization/en.tsx
- frontend/src/citizen-frontend/localization/sv.tsx
Add translations for additional service voucher instructions.
> EVAKA-4156: Add translations for additional service voucher instructions

- frontend/src/citizen-frontend/localization/en.tsx
- frontend/src/citizen-frontend/localization/fi.tsx
- frontend/src/citizen-frontend/localization/sv.tsx
> Citizen fronend application text fixes

- service/src/main/kotlin/fi/espoo/evaka/pis/service/FamilyOverviewService.kt
> EVAKA-HOTFIX: family overview handle not found

- frontend/src/employee-frontend/components/decision-draft/DecisionDraft.tsx
- frontend/src/employee-frontend/components/placement-draft/PlacementDraft.tsx
Quick fix to avoid accidental double placement plan submits
> EVAKA-FIX prevent double submits in placement draft view

- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/components/reports/VoucherServiceProviderUnit.tsx
- frontend/src/employee-frontend/types/reports.ts
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
- service/src/main/resources/db/migration/V44__voucher_value_report_snapshot.sql
- service/src/main/resources/migrations.txt
> EVAKA-4016: voucher value freeze (sql edition)

- frontend/src/employee-mobile-frontend/App.tsx
- frontend/src/employee-mobile-frontend/api/attendances.ts
- frontend/src/employee-mobile-frontend/assets/i18n/fi.ts
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceChildPage.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceList.tsx
- frontend/src/employee-mobile-frontend/components/attendances/ChildListItem.tsx
- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkPresent.tsx
- frontend/src/employee-mobile-frontend/components/attendances/notes/DailyNoteEditor.tsx
- service/src/main/kotlin/fi/espoo/evaka/messaging/daycarydailynote/DaycareDailyNote.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/daycarydailynote/DaycareDailyNoteController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/daycarydailynote/DaycareDailyNoteQueries.kt
Adds a daily note editor to the mobile frontend. Accessible from the child's page middle button.
> Evaka 4030 daily note editor

- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/DecisionGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/BulletinIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinControllerEmployee.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinNotificationEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
- service/src/main/resources/db/migration/V45__add_sent_at_to_bulletin_instance.sql
- service/src/main/resources/migrations.txt
First draft - forked from `PendingDecisionEmailService`
> EVAKA-3952-unread-bulletin-notification-email

- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-frontend/api/applications.ts
- frontend/src/employee-frontend/api/invoicing.ts
- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/components/child-information/CreateApplicationModal.tsx
- frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
- frontend/src/employee-frontend/components/messages/api.ts
Lack of error handling has caused prod to log some errors. Here's a proposed fix to a bunch of them.
> Frontend network error fix

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
For retroactive fee decisions, ensure approver is set as decision handler.
> EVAKA-4121 retroactive fee decision handler

- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaOrganizerIntegrationTest.kt
- service/src/integrationTest/resources/legacy_db_data.sql
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaOrganizer.kt
- service/src/main/resources/db/migration/V47__drop_iban_from_varda_organizer.sql
- service/src/main/resources/migrations.txt
Remove deprecated iban field from varda_organizer
> EVAKA-FIX remove iban from varda organizer

- frontend/src/employee-mobile-frontend/components/attendances/AttendanceChildPage.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendancePageWrapper.tsx
- frontend/src/employee-mobile-frontend/components/attendances/notes/DailyNoteEditor.tsx
Changed input fields to `TextArea` components, added user info to daily notes and made inactive buttons gray.
> EVAKA-4030 daily notes fixes

- frontend/src/employee-frontend/components/Reports.tsx
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/Acl.kt
> EVAKA-4016 allow unit supervisors to read voucher report

- frontend/README.md
- frontend/dev-server.js
- frontend/package.json
- frontend/yarn.lock
Restore lost functionality + update README
> New frontend project structure and build - part 3

- frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
Hides the desktop daily notifications from production.
> EVAKA-HOTFIX hide desktop daily notes from produciton

- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueAreaReportTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
> EVAKA-4016: fix partial month corrections

- frontend/src/citizen-frontend/localization/en.tsx
- frontend/src/citizen-frontend/localization/fi.tsx
- frontend/src/citizen-frontend/localization/sv.tsx
Add additional information when applying for service voucher in daycare or preschool.
**How to test:** Run locally, and check _Preferred units_ section in daycare and preschool application.
> EVAKA-3761: Additional information regarding service voucher

- message-service/owasp-suppressions.xml
- service/owasp-suppressions.xml
https://nvd.nist.gov/vuln/detail/CVE-2020-13936
> Add owasp suppression for irrelevant vulnerability

- frontend/src/employee-frontend/api/absences.ts
- frontend/src/employee-frontend/api/daycare.ts
- frontend/src/employee-frontend/api/unit.ts
There have been some issues with sorting absences, applications and units containing scandinavian letters. The real fix requires recreating the databases, but here's a quick frontend fix for the meantime.
> Add locale sorting to a few API calls

- service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
> Evaka fix less email async job retry

- frontend/src/citizen-frontend/localization/fi.tsx
Fix minor typo in Finnish localization.
> EVAKA-HOTFIX: Fix minor typo

- proxy/nginx.conf.template
Optonal redirect from given SV domain to main domain on proxy. The redirect will add ?lang=sv to request.
> Redirect sv-domain to main domain with lang parameter

- service/README.md
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/daycarydailynote/DaycareDailyNoteQueries.kt
- the :now in the SQL query needed casting.
- integration test for basic functionality
- README corrections
> Evaka fix dailynote cleanup fix

- frontend/src/e2e-test/pages/employee/mobile/child-page.ts
- frontend/src/employee-mobile-frontend/components/attendances/notes/DailyNoteEditor.tsx
- service/src/main/kotlin/fi/espoo/evaka/messaging/daycarydailynote/DaycareDailyNoteQueries.kt
> Fix E2E tests broken by a rebase

- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/unit/tab-unit-information/UnitInformation.tsx
> EVAKA: remove mobile poc link

- frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
> Use L width inputs for OID fields

- frontend/src/e2e-test/pages/employee/units/unit-page.ts
- frontend/src/e2e-test/specs/2_employee-2/employee-dailynote.spec.ts
- frontend/src/employee-frontend/api/unit.ts
- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/unit/tab-groups/daycare-daily-notes/DaycareDailyNoteModal.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
- service/src/main/kotlin/fi/espoo/evaka/messaging/daycarydailynote/DaycareDailyNoteController.kt
Daycare daily note for group, desktop: https://www.figma.com/file/8FXipaHxJcHwwfCl273PWS/Kasvattajan-mobiili?node-id=1735%3A548
Mobile will be on a separate PR
> Daycare group daily note UI

- frontend/src/employee-frontend/api/person.ts
- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/ChildInformation.tsx
- frontend/src/employee-frontend/components/child-information/MessageBlocklist.tsx
- frontend/src/employee-frontend/components/messages/types.ts
- frontend/src/employee-frontend/state/child.tsx
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/ChildRecipientsController.kt
A commit that does most of the messaging blocklist frontend stuff.
> Most of messaging blocklist frontend

- .circleci/config.yml
> Fix frontend cache key mismatch

- frontend/src/employee-mobile-frontend/components/attendances/notes/DailyNote.tsx
Added missing reminders to the DailyNote view.
> EVAKA-HOTFIX add missing reminders to note view

- frontend/src/e2e-test/pages/employee/mobile/child-page.ts
- frontend/src/e2e-test/pages/employee/mobile/mobile-groups.ts
- frontend/src/e2e-test/specs/6_mobile/dailynotes.spec.ts
- frontend/src/employee-mobile-frontend/api/attendances.ts
- frontend/src/employee-mobile-frontend/assets/i18n/fi.ts
- frontend/src/employee-mobile-frontend/components/attendances/notes/DailyNoteEditor.tsx
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/daycarydailynote/DaycareDailyNoteQueries.kt
- Show group daycare daily note on mobile
- No editing capability yet (PO decision)
https://www.figma.com/file/8FXipaHxJcHwwfCl273PWS/Kasvattajan-mobiili?node-id=1735%3A548
> Employee mobile group daily note & daily note edit fixes

- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
If a child's both guardians got their own decision documents only the "other" guardian's document would get saved in s3.
> EVAKA-HOTFIX decision document s3 key

- frontend/src/e2e-test/pages/citizen/citizen-messages.ts
- frontend/src/e2e-test/pages/employee/child-information/child-information-page.ts
- frontend/src/e2e-test/specs/7_messaging/sending-and-receiving-bulletins.spec.ts
- frontend/src/employee-frontend/api/person.ts
- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/ChildInformation.tsx
- frontend/src/employee-frontend/components/child-information/MessageBlocklist.tsx
- frontend/src/employee-frontend/components/messages/types.ts
- frontend/src/employee-frontend/state/child.tsx
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/ChildRecipientsController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V48__messaging_blocklist.sql
- service/src/main/resources/migrations.txt
DO NOT MERGE
- Agreed with PO that this goes behind a feature flag for now
Todo
> EVAKA-4151: messaging blocklist

- evaka-base/Dockerfile
We want to update all packages on image to latest always to get latest fixes. This will add dist-upgrade on base image.
> Always update packages

- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
Because there might be a long time between submitting an application and creating the decisions for the guardians, make sure that the parents are still custodians.
> Make sure that decisions are sent only to current guardians

- frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponseList.tsx
> EVAKA-HOTFIX: fix accepting secondary decision without primary decision

- service/src/main/resources/db/migration/V50__add_bulletin_reciever.sql
Remove accidentally committed line
> EVAKA-HOTFIX revert changes made to migration

- frontend/src/e2e-test/specs/5_employee/backup-care.spec.ts
- frontend/src/e2e-test/specs/5_employee/units.spec.ts
- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/unit/tab-groups/daycare-daily-notes/DaycareDailyNoteModal.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
- frontend/src/employee-frontend/types/unit.ts
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceAbsentPage.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceChildPage.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceComingPage.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceDepartedPage.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceList.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendancePageWrapper.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendancePresentPage.tsx
- frontend/src/employee-mobile-frontend/components/attendances/ChildListItem.tsx
- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkAbsent.tsx
- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkDeparted.tsx
- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkPresent.tsx
- frontend/src/employee-mobile-frontend/components/attendances/notes/DailyNote.tsx
- frontend/src/employee-mobile-frontend/components/attendances/notes/DailyNoteEditor.tsx
- Fix daycare group layout to match UX spec (more space, correct table header alignment)
- Fix daycare daily note group note text to be black, not gray
- Make employee unit group view daily note add / create button more obvious
- Show group note on employee mobile attendance UI
- Add sleeping hours to employee web UI tooltip
> Evaka fix daily note fixes

- frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx
- service/src/main/kotlin/fi/espoo/evaka/ClubTerm.kt
`// TODO: hard-coding is not a good solution` :relieved:
> EVAKA-HOTFIX add missing 2021-2022 club term to backend

- compose/docker-compose.e2e.yml
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/BulletinIntegrationTest.kt
- service/src/integrationTest/resources/application-integration-test.yaml
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinNotificationEmailService.kt
Add notification email content
https://voltti.atlassian.net/browse/EVAKA-4150
NB: depends on https://github.com/espoon-voltti/evaka-infra/pull/381
> EVAKA-4150 bulletin notification email content

- frontend/src/employee-frontend/components/ChildInformation.tsx
- frontend/src/employee-frontend/components/child-information/BackupPickup.tsx
- service/src/main/kotlin/fi/espoo/evaka/backuppickup/BackupPickupController.kt
Updated permissions for backup pickups so creating, editing and deleting requires more access.
> EVAKA-HOTFIX update backup pickup permissions

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/BulletinIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinQueries.kt
Add missing where-clause (and block list handling)...
> EVAKA-FIX limit new bulletin receivers by unitId

- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeAlterationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
- service/src/main/resources/db/migration/V57__add_missing_enums.sql
- service/src/main/resources/migrations.txt
Title says it all pretty much. I left out the `placement_type` and `service_need` columns in `fee_decision_part` and `voucher_value_decision_part` tables because they will probably have to be changed anyway when we change the service need model.
> Use postgres enums in finance related tables with enum data

- frontend/.gitignore
- frontend/src/citizen-frontend/Footer.tsx
- frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx
- frontend/src/citizen-frontend/applications/editor/verification/ApplicationVerificationView.tsx
- frontend/src/citizen-frontend/applications/editor/verification/ServiceNeedAttachments.tsx
- frontend/src/citizen-frontend/localization/en.tsx
- frontend/src/citizen-frontend/localization/fi.tsx
- frontend/src/citizen-frontend/localization/sv.tsx
- frontend/src/lib-customizations/citizen.tsx
- frontend/src/lib-customizations/employee.tsx
- frontend/src/lib-customizations/espoo/citizen.tsx
- frontend/src/lib-customizations/espoo/employee.tsx
- frontend/src/lib-customizations/espoo/enCustomizations.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/espoo/fiCustomizations.tsx
- frontend/src/lib-customizations/espoo/svCustomizations.tsx
- frontend/src/lib-customizations/types.d.ts
POC for frontend customization: localization, logo, flagging features on/off (urgency attachments at this point, because needed at Tampere)
> TREV-57 POC customizations: logo, footer cityLabel, urgencyAttachments

- frontend/src/employee-frontend/components/child-information/MessageBlocklist.tsx
Fixed html issue with div as a child of `tbody` element
> EVAKA-HOTFIX Fixed html issue with div as a child of thead element

- frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application-create.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationUpdateIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/DuplicateApplicationIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTestUtils.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/PlannedOccupancyTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/auth/AclIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/resources/db/migration/V60__application_person_foreign_keys.sql
- service/src/main/resources/migrations.txt
> EVAKA-TECH: add missing fkey constraints to application

- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/messages/ReceiverSelection.tsx
- frontend/src/employee-frontend/components/messages/receiver-selection-utils.ts
- frontend/src/employee-frontend/components/messages/types.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/BulletinIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinControllerEmployee.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinQueries.kt
Enable an employee to edit message receivers from the message editor.
> Receiver selection from the message editor

- frontend/src/employee-frontend/api/child/daily-service-times.ts
- frontend/src/employee-frontend/components/child-information/DailyServiceTimesSection.tsx
- frontend/src/employee-frontend/types/child.ts
- frontend/src/employee-mobile-frontend/api/attendances.ts
- frontend/src/employee-mobile-frontend/assets/i18n/fi.ts
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceChildPage.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceDailyServiceTimes.tsx
- frontend/src/employee-mobile-frontend/components/attendances/components.tsx
- frontend/src/lib-common/api-types/child/common.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimes.kt
> EVAKA-4157 Daily service times (mobile)

- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimes.kt
> EVAKA-HOTFIX Fix reading time ranges and child attendances

- service/src/main/kotlin/fi/espoo/evaka/pis/FamilyContact.kt
The data class does not match query results.
> EVAKA-HOTFIX make backupPhone nullable in FamilyContact

- frontend/src/citizen-frontend/localization/en.tsx
- frontend/src/citizen-frontend/localization/fi.tsx
- frontend/src/citizen-frontend/localization/sv.tsx
- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-mobile-frontend/assets/i18n/fi.ts
> EVAKA-FIX text changes

- apigw/generate-jwts.ts
- apigw/src/shared/auth/index.ts
- apigw/src/shared/auth/jwt.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/async/AsyncJobQueriesTest.kt
- service/src/integrationTest/resources/legacy_db_data.sql
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/AuthenticatedUser.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/JwtTokens.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/UserRole.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/dev-data/employees.sql
Start passing fine-grained data from apigw, clean up some legacy stuff.
**This shouldn't be merged until part 1 has been deployed to production**
> [DONTMERGE] Split AuthenticatedUser to separate variants - part 2

- frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
Hide groupnote button from prod.
> EVAKA-HOTFIX removed groupnote button from prod

- service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentQueries.kt
Do not return attachments uploaded by employees to end users.
> EVAKA-4160 Restrict end user attachments

- frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application-create.spec.ts
Remove assert that depends on the day the test is run. It's also not super important to do in this test.
> Fix time dependant e2e test

- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceClientIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTestBase.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceClient.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/FuelManagerConfig.kt
Trevaka requires basic authentication for the http requests.
From https://github.com/espoon-voltti/evaka/pull/682
> Allow person modifications client customization

- service/src/main/resources/db/migration/V65__new_service_needs.sql
- service/src/main/resources/migrations.txt
> EVAKA-4176: new service needs data model

- frontend/src/e2e-test/pages/employee/messaging/messages-page.ts
- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/messages/MessageList.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/messages/ReceiverSelection.tsx
> Misc. receiver selection UI fixes

- frontend/src/citizen-frontend/localization/en.tsx
- frontend/src/citizen-frontend/localization/fi.tsx
- frontend/src/citizen-frontend/localization/sv.tsx
- frontend/src/lib-customizations/espoo/enCustomizations.tsx
- frontend/src/lib-customizations/espoo/fiCustomizations.tsx
- frontend/src/lib-customizations/espoo/svCustomizations.tsx
- frontend/src/lib-customizations/types.d.ts
> Enable customization of citizen footer links

- frontend/src/lib-components/atoms/form/Radio.tsx
`yarn storybook` http://localhost:9001/?path=/story/evaka-atoms-form-radio--default
> Fix Radio button hover styles to match design system

- frontend/src/employee-frontend/api/child/placements.ts
- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/child-information/placements/NewServiceNeeds.tsx
- frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
- frontend/src/employee-frontend/config.ts
- frontend/src/employee-frontend/types/child.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/dao/PlacementQueriesIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/DaycareService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
- service/src/main/kotlin/fi/espoo/evaka/serviceneednew/NewServiceNeed.kt
- service/src/main/kotlin/fi/espoo/evaka/serviceneednew/NewServiceNeedQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/units/UnitsView.kt
> EVAKA-4176: display new service needs to admin role

- proxy/nginx.conf.template
This enables common parameters for KeyCloak nginx.
> KeyCloak parameters

- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/Reports.tsx
- frontend/src/employee-frontend/components/reports/InvalidServiceNeed.tsx
- frontend/src/employee-frontend/types/reports.ts
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/messaging/FeeDecisionGenerationJobProcessor.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/InvalidServiceNeedReport.kt
- service/src/main/kotlin/fi/espoo/evaka/serviceneednew/NewServiceNeedQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/utils/kotlin.kt
> EVAKA-4176: Invalid service needs report

- frontend/src/citizen-frontend/applications/editor/ApplicationFormData.ts
- frontend/src/citizen-frontend/applications/editor/contact-info/GuardianSubSection.tsx
- frontend/src/citizen-frontend/applications/editor/validations.ts
- frontend/src/citizen-frontend/form-validation.ts
- frontend/src/citizen-frontend/localization/en.tsx
- frontend/src/citizen-frontend/localization/fi.tsx
- frontend/src/citizen-frontend/localization/sv.tsx
- frontend/src/e2e-test/pages/citizen/citizen-application-editor.ts
- frontend/src/e2e-test/utils/application-forms.ts
- frontend/src/lib-common/api-types/application/ApplicationDetails.ts
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationForm.kt
> EVAKA 4152: Require guardian email when an application is sent

- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/components/reports/ServiceNeeds.tsx
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceNeedReport.kt
Added a checkbox for admin in Lasten palvelutarpeet ja iät yksiköissä report, which gets the report data from v2 endpoint that uses the new service need data model.
> EVAKA-4176: new service needs report

- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/components/reports/MissingServiceNeed.tsx
- service/src/main/kotlin/fi/espoo/evaka/reports/MissingServiceNeedReport.kt
> EVAKA-4176: new missing service needs report

- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/reports/Raw.tsx
- frontend/src/employee-frontend/types/reports.ts
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
> EVAKA-3766, EVAKA-4193: raw report improvements

- frontend/src/citizen-frontend/map/MapBox.tsx
- frontend/src/citizen-frontend/map/const.ts
- frontend/src/lib-customizations/citizen.tsx
- frontend/src/lib-customizations/espoo/citizen.tsx
- frontend/src/lib-customizations/espoo/mapConfig.tsx
- frontend/src/lib-customizations/types.d.ts
Map center and zoom must be configurable for other installations.
> Add map customization

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/MessageProvider.kt
Messages sent by the app includes words like "Espoo" and "eVaka" which needs to customized for other installations.
> Refactor sfi messages to allow customization

- frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx
> Allow supervisors to see (but not edit) other supervisors

- frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx
- frontend/src/employee-frontend/components/common/Attachment.tsx
Show attachment to be received when application is received, or later if it's actually uploaded later.
> EVAKA-4160 fix visible attachment received at

- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/reports/InvalidServiceNeed.tsx
- frontend/src/employee-frontend/types/reports.ts
- service/src/main/kotlin/fi/espoo/evaka/reports/InvalidServiceNeedReport.kt
Unit is based on current placement
> EVAKA-4176: improvements to invalid service needs report

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/async/AsyncJobQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsBatchRefreshService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinNotificationEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/PairingsController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt
Jobs completed more than 1 months ago + all jobs planned to execute more than 6 months ago
> Add endpoint for async job garbage collection

- frontend/src/e2e-playwright/pages/dev-login-form.ts
- frontend/src/e2e-playwright/pages/employee/child-information-page.ts
- frontend/src/e2e-playwright/pages/employee/employee-nav.ts
- frontend/src/e2e-playwright/specs/5_employee/child-information.spec.ts
- frontend/src/e2e-playwright/specs/5_employee/employees.spec.ts
- frontend/src/e2e-playwright/specs/5_employee/voucher-reports.spec.ts
- frontend/src/e2e-playwright/specs/8_access/access.spec.ts
- frontend/src/e2e-test-common/config.ts
- frontend/src/e2e-test-common/dev-api/types.ts
- frontend/src/employee-frontend/components/child-information/Assistance.tsx
- frontend/src/employee-frontend/components/child-information/BackupCare.tsx
- frontend/src/employee-frontend/components/child-information/FamilyContacts.tsx
- frontend/src/employee-frontend/components/child-information/FeeAlteration.tsx
- frontend/src/employee-frontend/components/child-information/FridgeParents.tsx
- frontend/src/employee-frontend/components/child-information/Guardians.tsx
- frontend/src/employee-frontend/components/child-information/Placements.tsx
- frontend/src/employee-frontend/components/child-information/ServiceNeed.tsx
- message-service/build.gradle.kts
- service/build.gradle.kts
Added basic tests for page structure
> EVAKA basic tests for page structure

- service/src/integrationTest/kotlin/fi/espoo/evaka/ServiceNeedTestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGeneratorIntegrationTest.kt
- service/src/main/resources/dev-data/espoo-dev-data.sql
Make sure finance decisions work with the new placement types
> EVAKA-4176 finance decisions and five year old daycare

- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/ConfirmedOccupancyTest.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
- service/src/main/resources/dev-data/espoo-dev-data.sql
> EVAKA-4176: 5 years old daycare occupancies

- frontend/src/lib-common/api.spec.ts
- frontend/src/lib-common/api.ts
- `class Result<A>` methods
- Apply a function wrapped in a result: `apply(f: Result<(v: T) => A>): Result<A>`. Failure wins loading, loading wins success.
- Map `Loading`, `Failure` and `Success` in one step: `mapAll(fs: { loading: (v: A) => T, failure: (v: A) => T, success: (v: A) => T) => T`
- Top-level functions
- `map` for mapping 2-3 results simultaneously
- `combine` for combining 2-3 results to one result with a tuple value
`mapAll` will ease exhaustive rendering of result values:
```
mapAll(someResponse, {
loading() { return <Loading /> },
failure() { return <ErrorSegment /> },
success(value) {
// use value to render the actual content
}
})
```
`combine` will be useful when a component depends on multiple API requests:
```
combine(response1, response2).mapAll(
loading() { return …
```
> Add functional Result helpers

- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
- frontend/src/employee-frontend/types/child.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
> EVAKA-4177: provider type on child's placements

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
Almost forgot to add the new placement types.
> EVAKA-4176 include 5yo daycare in Varda

- frontend/src/employee-mobile-frontend/components/attendances/child-info/AutoPinLogout.tsx
- frontend/src/employee-mobile-frontend/components/attendances/child-info/InactivityTimeout.tsx
- frontend/src/employee-mobile-frontend/components/attendances/child-info/PinLogin.tsx
After logging in with PIN, 
- log out after 120 seconds of inactivity OR
- log out on blur (for example screen lock)
Tested to work on IOS 14 device
> Automagically log out after 120 seconds of inactivity

- frontend/src/citizen-frontend/localization/en.tsx
- frontend/src/citizen-frontend/localization/fi.tsx
- frontend/src/citizen-frontend/localization/sv.tsx
- frontend/src/lib-customizations/espoo/enCustomizations.tsx
- frontend/src/lib-customizations/espoo/fiCustomizations.tsx
- frontend/src/lib-customizations/espoo/svCustomizations.tsx
- frontend/src/lib-customizations/types.d.ts
> Application list view texts customizable

- frontend/src/lib-components/atoms/buttons/AsyncButton.tsx
The test failed because `AsyncButton`'s delayed `onSuccess` callback was run after the component had already unmounted causing a wrong set of data to be displayed in the list. Do a proper clean up of all the `setTimeout`s when the component is unmounted.
> Fix flaky value decision e2e test

- frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
- frontend/src/employee-frontend/config.ts
- frontend/src/employee-frontend/types/child.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
Use the new service needs to show missing service need days in local environment.
> EVAKA-4176 missing service need indicators

- frontend/src/citizen-frontend/localization/en.tsx
- frontend/src/citizen-frontend/localization/fi.tsx
- frontend/src/citizen-frontend/localization/sv.tsx
- frontend/src/employee-frontend/assets/i18n/fi.ts
Added more info on service vouchers to citizen application and added minor employee application and unit translation fixes.
> EVAKA-FIX minor translation fixes

- service/src/main/resources/WEB-INF/templates/shared/common.html
> Update pdf headers

- frontend/src/employee-frontend/components/Header.tsx
Enable PIN-code changing in production.
> EVAKA-HOTFIX enable pin code changing in production

- frontend/src/e2e-playwright/pages/mobile/mobile-nav.ts
- frontend/src/e2e-playwright/pages/mobile/staff-page.ts
- frontend/src/e2e-playwright/specs/6_mobile/staff.spec.ts
- frontend/src/e2e-playwright/utils/mobile.ts
- frontend/src/employee-frontend/api/absences.ts
- frontend/src/employee-mobile-frontend/components/common/BottomNavbar.tsx
- frontend/src/employee-mobile-frontend/components/common/GroupSelector.tsx
- frontend/src/employee-mobile-frontend/components/common/TopBar.tsx
- frontend/src/employee-mobile-frontend/components/staff/PlusMinus.tsx
- frontend/src/employee-mobile-frontend/components/staff/StaffAttendanceEditor.tsx
> EVAKA-4172 Mobile staff attendance E2E tests

- frontend/src/e2e-test/pages/employee/mobile/child-page.ts
- frontend/src/e2e-test/specs/6_mobile/dailynotes.spec.ts
- frontend/src/employee-mobile-frontend/api/attendances.ts
- frontend/src/employee-mobile-frontend/assets/i18n/fi.ts
- frontend/src/employee-mobile-frontend/components/attendances/AttendancePageWrapper.tsx
- frontend/src/employee-mobile-frontend/components/attendances/ChildListItem.tsx
- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkAbsent.tsx
- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkDeparted.tsx
- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkPresent.tsx
- frontend/src/employee-mobile-frontend/components/attendances/child-info/ChildSensitiveInfo.tsx
- frontend/src/employee-mobile-frontend/components/attendances/child-info/PinLogin.tsx
- frontend/src/employee-mobile-frontend/components/attendances/child-info/PinLogout.tsx
- frontend/src/employee-mobile-frontend/components/attendances/notes/DailyNote.tsx
- frontend/src/employee-mobile-frontend/components/attendances/notes/DailyNoteEditor.tsx
- frontend/src/employee-mobile-frontend/components/common/GroupSelector.tsx
- frontend/src/employee-mobile-frontend/components/mobile/components.tsx
- frontend/src/lib-common/utils/useSingleAndDoubleClick.ts
- frontend/src/lib-components/atoms/Chip.tsx
- frontend/src/lib-components/atoms/buttons/AsyncButton.tsx
- frontend/src/lib-components/layout/Container.tsx
- frontend/src/lib-components/typography.ts
Refactored the mobile daily note view from the feedback from pilot units meeting.
The spec can be found from figma: https://www.figma.com/file/8FXipaHxJcHwwfCl273PWS/Kasvattajan-mobiili?node-id=2922%3A83.
> EVAKA-UI refactor mobile group notes

- frontend/src/e2e-playwright/pages/employee/employee-pin.ts
- frontend/src/e2e-playwright/specs/5_employee/employee-pin.spec.ts
- frontend/src/e2e-test-common/dev-api/types.ts
- frontend/src/employee-frontend/api/employees.ts
- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/employee/EmployeePinCodePage.tsx
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
https://www.figma.com/file/UyFTAPt5kFhErtP56e7Ze8/eVaka-employee?node-id=3536%3A0
> Evaka 3914 pin frozen info desktop

- service/src/main/kotlin/fi/espoo/evaka/reports/InvalidServiceNeedReport.kt
Show invalid service needs to unit supervisors only if they can actually correct the data.
> EVAKA-4176 improve invalid service needs report for supervisors

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/FiveYearOldDaycarePlacementsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
- service/src/main/resources/db/scripts/migrate-5yo-daycare-placements.sql
Infer 5yo daycare placement type when creating and modifying placements.
> EVAKA-4176 infer 5yo daycare

- service/src/main/resources/db/scripts/migrate-5yo-daycare-placements.sql
The latest version of the migration that was run in prod.
> EVAKA-4176 fix 5yo placement migration

- frontend/src/citizen-frontend/applications/api.ts
- frontend/src/citizen-frontend/localization/en.tsx
- frontend/src/citizen-frontend/localization/fi.tsx
- frontend/src/citizen-frontend/localization/sv.tsx
- frontend/src/citizen-frontend/map/MapBox.tsx
- frontend/src/citizen-frontend/map/MapView.tsx
- frontend/src/citizen-frontend/map/api.ts
- frontend/src/e2e-playwright/pages/citizen/citizen-map.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-map.spec.ts
- frontend/src/e2e-playwright/specs/8_access/access.spec.ts
- frontend/src/e2e-test-common/dev-api/index.ts
- frontend/src/employee-frontend/api/daycare.ts
- frontend/src/lib-common/api-types/units/PublicUnit.ts
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Show private units that do not have applyPeriods on the citizen map with a text that tells that you can't apply to them through eVaka and you need to contact the unit yourself.
> EVAKA-4199 add private units to map

- frontend/src/employee-frontend/types/absence.ts
- frontend/src/employee-mobile-frontend/api/attendances.ts
- frontend/src/employee-mobile-frontend/components/attendances/Absences.tsx
- frontend/src/employee-mobile-frontend/components/attendances/components.tsx
- frontend/src/employee-mobile-frontend/types/index.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/AbsenceServiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/ConfirmedOccupancyTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
Remove deduction of 5-year-old daycare from a child's age and just rely on placement type.
> EVAKA-4176 5yo daycare leftovers

- service/src/main/kotlin/fi/espoo/evaka/serviceneednew/NewServiceNeedQueries.kt
- service/src/main/resources/dev-data/espoo-dev-data.sql
Add option for 5yo part week daycare that is between 35 and 45 hours.
> EVAKA-4176 missing 5yo service need option

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/application/SendApplicationReceivedEmailAsyncJobs.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
Send confirmation email when receiving preschool application. We use different content if application is sent within preschool application period.
> EVAKA-4206 preschool application received email

- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/unit/tab-groups/daycare-daily-notes/DaycareDailyNoteModal.tsx
- frontend/src/employee-mobile-frontend/assets/i18n/fi.ts
Minor text fixes for daily notes
> EVAKA-FIX Changed couple of translations for daily notes

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/Message.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccountQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageQueries.kt
- service/src/main/resources/db/migration/R__message_account_name_view.sql
- service/src/main/resources/db/migration/V75__messages.sql
- service/src/main/resources/migrations.txt
Initial database model for bidirectional messaging. Mock data for frontend development.
> EVAKA-4190 new messaging data model and initial implementation

- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceClientIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTestBase.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/MockDvvModificationsService.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/VTJBatchRefreshServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
- Only call person info update from VTJ SOAP update once per person DVV mutp info group
> DVV Mutp improvements

- service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/NewServiceNeedIntegrationTest.kt
> EVAKA-4176: new service need integration tests

- frontend/src/citizen-frontend/applications/ApplicationCreation.tsx
- frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx
- frontend/src/citizen-frontend/applications/editor/verification/ServiceNeedAttachments.tsx
- frontend/src/citizen-frontend/localization/en.tsx
- frontend/src/citizen-frontend/localization/fi.tsx
- frontend/src/citizen-frontend/localization/sv.tsx
- frontend/src/citizen-frontend/map/SearchSection.tsx
- frontend/src/lib-customizations/espoo/enCustomizations.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/espoo/fiCustomizations.tsx
- frontend/src/lib-customizations/espoo/svCustomizations.tsx
- frontend/src/lib-customizations/types.d.ts
> Possibility to hide preschool options from citizen UI

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaChildrenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaFeeDataIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaPlacementsIntegrationTest.kt
- service/src/integrationTest/resources/application-integration-test.yaml
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaChildren.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaPlacements.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- service/src/main/resources/application-local.yaml
- service/src/test/kotlin/fi/espoo/evaka/varda/integration/VardaClientTest.kt
Add param `lahdejarjestelma` to main models
Depends on https://github.com/espoon-voltti/evaka-infra/pull/403
> EVAKA-4210 add varda sourceSystem param

- service/src/main/resources/WEB-INF/templates/shared/common.html
Handle club decision type in pdf template
> EVAKA-BUGFIX: add missing unit name for club decision

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageQueries.kt
- service/src/main/resources/db/migration/V76__messages_v2.sql
- service/src/main/resources/migrations.txt
There is no message data in any of the environments yet so ALTER TABLE with NOT NULL constraints should succeed.
> Migrate to the new message thread data model

- frontend/src/citizen-frontend/map/UnitDetailsPanel.tsx
- frontend/src/lib-customizations/citizen.tsx
- frontend/src/lib-customizations/espoo/citizen.tsx
- frontend/src/lib-customizations/types.d.ts
> Route guide link URL as customizable

- frontend/src/citizen-frontend/map/UnitDetailsPanel.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Added missing translation to back to search button.
> EVAKA-FIX add translation to back to search button

- service/src/main/kotlin/fi/espoo/evaka/invoicing/messaging/FeeDecisionGenerationJobProcessor.kt
> EVAKA-4176 fix service need migration query

- frontend/src/e2e-test/specs/6_mobile/backup-care-dailynotes.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/daycarydailynote/DaycareDailyNoteQueries.kt
> Backup care child daily notes support

- frontend/src/citizen-frontend/applications/editor/AdditionalDetailsSection.tsx
- frontend/src/citizen-frontend/applications/editor/service-need/AssistanceNeedSubSection.tsx
- frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
> Improve customization support for application texts

- frontend/src/e2e-test/specs/6_mobile/pin-login.spec.ts
- frontend/src/employee-mobile-frontend/api/attendances.ts
- frontend/src/employee-mobile-frontend/components/attendances/child-info/PinLogin.tsx
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- Only show employees with a valid pin in employee PIN login list
- Pass PIN as body param instead of query param
> Only show employees with pin in login list

- service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/SystemIdentityController.kt
- service/src/main/resources/db/migration/V78__last_login.sql
- service/src/main/resources/migrations.txt
Mark employee and person last login timestamp
> Mark last login timestamp on person and employee login

- frontend/src/employee-frontend/components/messages/api.ts
- frontend/src/employee-frontend/components/messages/types.ts
Initial api types for employee frontend messaging
> EVAKA-4190 Add messaging api-types to employee frontend

- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/PersonQueriesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccountQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/Person.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/SystemIdentityController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/service/persondetails/PersonStorageService.kt
> EVAKA-4190 Add a message account for persons upon creation

- frontend/src/employee-frontend/config.ts
This enables Employee login on production.
> Enable Evaka Employee login on Production

- service/src/main/kotlin/fi/espoo/evaka/reports/OccupancyReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
- service/src/test/kotlin/fi/espoo/evaka/shared/domain/TimeTest.kt
> EVAKA-4176: backup cares in occupancy calculation v2

- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/UnitAcl.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccountQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/AclQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V81__message_account_active.sql
- service/src/main/resources/migrations.txt
- Add support for marking message accounts as active/inactive
- Add message account for unit supervisor when giving them a supervisor role
- Deactivate the message account when removing the last supervisor role
> EVAKA-4190 Supervisor message account

- CONTRIBUTING.md
- Describe the current PR process
- Leave any code style guidelines out for now (as we don't have them officially documented/decided anywhere else either)
> [EVAKA] Docs: Basic contributing guide

- frontend/src/employee-frontend/components/child-information/placements/NewServiceNeeds.tsx
> EVAKA-4176: default service needs cannot be selected

- frontend/src/employee-mobile-frontend/components/attendances/child-info/ChildSensitiveInfo.tsx
> Backup pickup phone icon

- .circleci/config.yml
- frontend/package.json
> Make CI fail on lint warnings

- frontend/src/citizen-frontend/messages/api.ts
- frontend/src/employee-frontend/components/messages/MessageList.tsx
- frontend/src/employee-frontend/components/messages/ReceivedMessages.tsx
- frontend/src/employee-frontend/components/messages/api.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/Message.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MockThreads.kt
Implement marking messages read by citizen and employee.
> EVAKA-4190 Mark messages read

- frontend/src/employee-frontend/components/Reports.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/InvoicingReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/InvoiceReport.kt
> EVAKA-4226: remove invoicing report from director

- frontend/src/e2e-playwright/specs/8_access/access.spec.ts
- frontend/src/employee-frontend/components/Header.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/PersonQueriesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
- service/src/main/resources/db/migration/R__acl_views.sql
Query performance tested in prod db: seems fine.
> EVAKA-3876: limited person search for unit supervisors and VEOs

- frontend/src/lib-common/theme.ts
- frontend/src/lib-common/themes/espoo-theme.ts
- frontend/src/lib-components/typography.ts
treVaka design requires slightly different font weights for headings. This adds support for it.
> Add font weight configurations to theme

- service/src/main/resources/db/migration/V84__create_message_accounts.sql
- service/src/main/resources/migrations.txt
Create message account for
- all daycare groups
- all persons
- employees who are supervisors
> EVAKA-4190 Create message accounts for existing entities in migration

- service/src/main/resources/db/migration/V84__create_message_accounts.sql
> EVAKA-HOTFIX Do not create message accounts for existing entities

- frontend/src/lib-components/atoms/ExternalLink.tsx
> Keep external link icon and text on the same row

- frontend/src/e2e-playwright/specs/8_access/access.spec.ts
- frontend/src/employee-frontend/components/Header.tsx
Enable Messages page for staff role
> EVAKA-4190 Enable Messages page for staff role

- service/src/integrationTest/kotlin/fi/espoo/evaka/FixtureBuilder.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
* Count planned absence as an absence in occupancy calculations
* Use half even rounding for consistency with the old implementation
> EVAKA-4176 occupancy calculation fixes

- frontend/src/employee-frontend/components/messages/MessageComponents.tsx
- frontend/src/employee-frontend/components/messages/MessageList.tsx
- frontend/src/employee-frontend/components/messages/MessageTypeChip.tsx
- frontend/src/employee-frontend/components/messages/ReceivedMessages.tsx
- frontend/src/employee-frontend/components/messages/SentMessages.tsx
- frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
- frontend/src/employee-frontend/components/messages/api.ts
- frontend/src/employee-frontend/components/messages/types.ts
MVP implementation of employee's sent messages
> EVAKA-4190 MVP implementation of employee's sent messages

- frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
- frontend/src/employee-frontend/types/child.ts
- frontend/src/employee-frontend/types/unit.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/backupcare/BackupCareIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCare.kt
- service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareQueries.kt
> EVAKA-4176: missing service needs in unit groups view

- frontend/src/e2e-test/pages/invoicing.ts
- frontend/src/e2e-test/specs/4_invoicing/invoices.spec.ts
- frontend/src/employee-frontend/api/invoicing.ts
- frontend/src/employee-frontend/components/invoices/Invoices.tsx
- frontend/src/employee-frontend/types/invoicing.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Invoices.kt
- service/src/main/resources/db/migration/V86__add_invoice_created_at.sql
- service/src/main/resources/migrations.txt
Add new column & show timestamp on invoice table
> EVAKA-3686 show invoice created at 

- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/messages/ReceiverSelection.tsx
- frontend/src/employee-frontend/components/messages/SelectorNode.ts
- frontend/src/employee-frontend/components/messages/Sidebar.tsx
- frontend/src/employee-frontend/components/messages/api.ts
- frontend/src/employee-frontend/components/messages/types-view.d.ts
- frontend/src/employee-frontend/components/messages/types.ts
* Allow send message with manually entered receiver ids.
> Evaka 4190 rudimentary send message

- frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
- frontend/src/employee-frontend/components/reports/MissingServiceNeed.tsx
- frontend/src/employee-frontend/components/reports/Occupancies.tsx
- frontend/src/employee-frontend/components/reports/Raw.tsx
- frontend/src/employee-frontend/components/reports/ServiceNeeds.tsx
- frontend/src/employee-frontend/config.ts
Use new service needs for everything apart from Varda and fee decisions in production.
> EVAKA-4176 partial use of new service needs in prod

- frontend/src/e2e-playwright/specs/8_access/access.spec.ts
- frontend/src/employee-frontend/components/ChildInformation.tsx
Show backup pickups for unit supervisors and unit staff. Hide them from special education teachers.
> EVAKA-HOTFIX show backup pickups for unit supervisors and unit staff

- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/messages/api.ts
- frontend/src/employee-frontend/components/messages/types.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageController.kt
Move account id from body to request path in POST /messages endpoint to unify paths
> EVAKA-4190 Unify message endpoints

- frontend/src/employee-frontend/App.tsx
> Use a better default route for DIRECTOR role

- service/README.md
The old instructions just didn't work correctly
> Fix list-migrations.sh instructions

- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/AbstractIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/FiveYearOldDaycarePlacementsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
- service/src/main/resources/application.yaml
> EVAKA-TREVAKA: five year old daycare can be disabled by env var

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaChildren.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDevController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaPlacements.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
First draft of functions to delete varda records.
Also add a dev controller to test these against their QA env.
> EVAKA-4148 varda child reset

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/MockEmailClient.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/Message.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageNotificationEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
- service/src/main/resources/db/migration/V90__message_recipients_notification_sent_at.sql
- service/src/main/resources/migrations.txt
- Notification emails about new messages are sent as async jobs, one per email
- Wrap message sending functions in a class for easier injection of `MessageNotificationEmailService`
- Remove notification service for bulletins
> EVAKA-4190 Email notifications about new messages

- service/src/main/kotlin/fi/espoo/evaka/invoicing/messaging/FeeDecisionGenerationJobProcessor.kt
Do service need sync on placement update since the new service needs depend on placements as well.
> EVAKA-4176 service need sync on placement update

- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageControllerCitizen.kt
Reduce copy-paste when checking for message account access.
> EVAKA-4190 Unify message access control

- frontend/src/employee-frontend/components/Reports.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/StartingPlacementsReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/EndedPlacementsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/StartingPlacementsReport.kt
> EVAKA-4238: remove two reports from director

- frontend/src/e2e-test-common/dev-api/index.ts
- frontend/src/e2e-test/specs/7_messaging/sending-and-receiving-bulletins.spec.ts
- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/messages/ReceiverSelection.tsx
- frontend/src/employee-frontend/components/messages/SelectorNode.ts
- frontend/src/employee-frontend/components/messages/Sidebar.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
* Close the message editor on send.
* Clear the receiver selection and message content on editor close.
* Reduce the number of /receivers/ requests.
> Refactor messaging

- service/src/main/kotlin/fi/espoo/evaka/messaging/daycarydailynote/DaycareDailyNoteController.kt
> Allow VEO role to use daily note endpoints

- service/src/main/kotlin/fi/espoo/evaka/shared/config/HttpFilterConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDevController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/MockVardaIntegrationEndpoint.kt
Add missing config to enable dev controller unless in prod
> EVAKA-4148 Allow traffic to varda-dev controller

- frontend/src/citizen-frontend/messages/ThreadListItem.tsx
- frontend/src/citizen-frontend/messages/ThreadReadView.tsx
- frontend/src/e2e-test-common/config.ts
- frontend/src/e2e-test-common/dev-api/index.ts
- frontend/src/e2e-test/pages/citizen/citizen-messages.ts
- frontend/src/e2e-test/pages/employee/messaging/messages-page.ts
- frontend/src/e2e-test/specs/7_messaging/sending-and-receiving-messages.spec.ts
- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/messages/Sidebar.tsx
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
> Reimplement messaging e2e tests

- compose/README.md
- Clarified (apparently optional) additional configuration need
- Document problem with another database server running
> Update README based on new dev experience

- frontend/src/employee-frontend/components/child-information/assistance-action/AssistanceActionForm.tsx
- frontend/src/employee-frontend/components/child-information/assistance-action/AssistanceActionRow.tsx
- frontend/src/employee-frontend/constants.ts
- frontend/src/employee-frontend/types/child.ts
- frontend/src/lib-customizations/employee.tsx
- frontend/src/lib-customizations/espoo/employee.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
Minimal support to hide some of the assistance measure selections.
> Assistance measure configuration

- frontend/src/employee-frontend/components/child-information/placements/NewServiceNeeds.tsx
- frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
- frontend/src/employee-frontend/components/child-information/placements/new-service-needs/MissingServiceNeedRow.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Show new service need editor for all roles in staging.
> EVAKA-4176 enable new service needs in staging

- frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx
- frontend/src/employee-frontend/utils/index.ts
- frontend/src/lib-common/utils/useUniqueId.ts
- frontend/src/lib-components/atoms/Chip.tsx
- frontend/src/lib-components/molecules/FileUpload.tsx
- frontend/src/lib-components/molecules/date-picker/DatePickerInput.tsx
- replaces various Math.random calls that were done on every render
- a global hidden mutable state variable is good enough for tracking the next available id, since all we care about is uniqueness
> Add useUniqueId hook

- frontend/src/citizen-frontend/Footer.tsx
- frontend/src/lib-customizations/citizen.tsx
- frontend/src/lib-customizations/types.d.ts
treVaka design requires logo in the footer. This adds support to show logo in the right corner.
> Add footer logo support

- frontend/src/employee-frontend/components/child-information/placements/NewServiceNeeds.tsx
- frontend/src/employee-frontend/utils/date.spec.ts
- frontend/src/employee-frontend/utils/date.ts
- frontend/src/lib-common/finite-date-range.spec.ts
- frontend/src/lib-common/finite-date-range.ts
> EVAKA-4176: fix and refactor gap calculation

- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkAbsentBeforehand.tsx
- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkDeparted.tsx
- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkPresent.tsx
- frontend/src/employee-mobile-frontend/components/attendances/child-info/ChildInfo.tsx
- frontend/src/employee-mobile-frontend/components/attendances/child-info/PinLogin.tsx
- frontend/src/employee-mobile-frontend/components/mobile/components.tsx
!Important styling fixes after changes from absences page
> EVAKA-4161 styling fixes

- .circleci/config.yml
Screenshots were generated but not stored :see_no_evil:
> Store playwright screenshots in CI

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/PendingDecisionEmailServiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageNotificationEmailService.kt
> EVAKA-4235 Merge email language versions

- frontend/src/employee-frontend/components/messages/ReceiverSelection.tsx
- frontend/src/employee-frontend/components/messages/SelectorNode.ts
- Add missing date of birth and parents to recipient selector
- Make childNodes a required property in SelectorNode
- Unify layout by wrapping receiver selection in ContentArea
> EVAKA-4190 Finalize receiver selection layout

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageReceiversIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccountQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageQueries.kt
An employee can send a message to given recipients if each recipient has a child that has an active placement in a daycare the employer works at (has an ACL row for).
> EVAKA-4190 Authorization for sending messages

- frontend/src/e2e-test/pages/employee/messaging/messages-page.ts
- frontend/src/e2e-test/specs/7_messaging/sending-and-receiving-messages.spec.ts
- frontend/src/employee-frontend/components/messages/MessageBox.tsx
- frontend/src/employee-frontend/components/messages/MessageDrafts.tsx
- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/messages/useDraft.ts
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
* Test that a draft is saved correctly.
* Test that a draft is not saved when a message is sent.
* Test that a draft is not saved when it's discarded.
> Additional e2e tests

- frontend/src/citizen-frontend/map/MapBox.tsx
Open private service voucher unit link in a new tab.
> EVAKA-HOTFIX open popup link in new tab

- frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application-create.spec.ts
- frontend/src/lib-components/layout/flex-helpers.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Update citizen daycare application titles and info text to include service voucher.
Also fix alignment issues caused by `FixedSpaceFlexWrap` not having explicit content alignment style properties set.
> EVAKA-4224 update citizen daycare application texts

- frontend/src/employee-frontend/api/absences.ts
- frontend/src/employee-frontend/components/absences/AbsenceCell.tsx
- frontend/src/employee-frontend/components/absences/Absences.tsx
- frontend/src/employee-frontend/components/common/ColourInfoItem.tsx
- frontend/src/employee-frontend/components/invoice/AbsencesModal.tsx
- frontend/src/employee-frontend/state/absence.tsx
- frontend/src/employee-frontend/types/absence.ts
- frontend/src/employee-frontend/types/reports.ts
- frontend/src/lib-common/api-types/child/Absences.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/AbsenceServiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/RealizedOccupancyTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/AbsenceController.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/PresenceReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
- service/src/main/resources/db/migration/V95__remove_absence_soft_delete.sql
- service/src/main/resources/migrations.txt
remove absence soft delete, fix endpoint auth and clean up some code
> EVAKA-TECH: remove absence soft delete

- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- Move sender to message state instead of separate useState
- Use named functions for effects instead of comments
> EVAKA-4190 Fix sender selection

- frontend/src/employee-frontend/api/finance-basics.ts
- frontend/src/employee-frontend/components/finance-basics/FeeThresholdsItemEditor.tsx
- frontend/src/employee-frontend/components/finance-basics/FeesSection.tsx
- frontend/src/employee-frontend/types/finance-basics.ts
- frontend/src/employee-frontend/utils/money.ts
- frontend/src/lib-common/utils/local-date.ts
- frontend/src/lib-components/atoms/form/InputField.tsx
- frontend/src/lib-components/typography.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceBasicsController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/PricingWithValidity.kt
Add a basic fee thresholds editor for creating new fee thresholds.
Also changes InputField's wrapper div to be inline so that the component behaves more like an input by default.
> EVAKA-4184 basic fee thresholds editor

- frontend/src/employee-frontend/components/Header.tsx
- frontend/src/employee-frontend/components/messages/GroupMessageAccountList.tsx
- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- frontend/src/employee-frontend/components/messages/MessageDrafts.tsx
- frontend/src/employee-frontend/components/messages/MessageList.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/messages/ReceivedMessages.tsx
- frontend/src/employee-frontend/components/messages/Sidebar.tsx
- frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
- frontend/src/employee-frontend/state/StateProvider.tsx
- Display unread message counts in header and account list
- Move thread selection logic to context and context to higher level in component tree
- Auto-expand group accounts which have unread messages
> EVAKA-4190 Display unread counts

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationDetailsService.kt
Placement types for 5yo daycare were never included in the existing placements check.
> Fix daycare transfer application for children in 5yo daycare

- frontend/src/employee-frontend/components/ApplicationPage.tsx
Do not fetch units on every edit of application.
> EVAKA-HOTFIX do not fetch units on every edit of application

- frontend/src/employee-frontend/components/child-information/DailyServiceTimesSection.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceDailyServiceTimes.tsx
- frontend/src/lib-common/api-types/child/common.ts
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimes.kt
- service/src/main/resources/db/migration/V98__add_type_to_daily_service_times.sql
- service/src/main/resources/migrations.txt
> EVAKA-4216: refactor daily service times model

- frontend/README.md
- frontend/src/lib-components/.storybook/main.js
- frontend/webpack.config.js
Explicit configuration via the ICONS env variable is still honored if set
> Detect and use pro icons automatically

- frontend/src/citizen-frontend/auth/state.tsx
- frontend/src/citizen-frontend/header/DesktopNav.tsx
- frontend/src/citizen-frontend/header/MobileNav.tsx
> EVAKA-4190 Indicate strong authentication requirement in citizen nav

- frontend/src/employee-frontend/components/child-information/DailyServiceTimesSection.tsx
- frontend/src/employee-mobile-frontend/assets/i18n/fi.ts
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceDailyServiceTimes.tsx
- frontend/src/lib-common/api-types/child/common.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimes.kt
- service/src/main/resources/db/migration/V103__add_variable_time_to_daily_service_time_type.sql
- service/src/main/resources/migrations.txt
Adds possibility to add variable time to daily service times.
> EVAKA-4216 add variable time to daily service times

- frontend/src/citizen-frontend/messages/MessageTypeChip.tsx
- frontend/src/citizen-frontend/messages/MessagesPage.tsx
- frontend/src/citizen-frontend/messages/ThreadList.tsx
- frontend/src/citizen-frontend/messages/ThreadListItem.tsx
- frontend/src/citizen-frontend/messages/ThreadView.tsx
- frontend/src/citizen-frontend/messages/api.ts
- frontend/src/citizen-frontend/messages/state.tsx
- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- frontend/src/employee-frontend/components/messages/MessageTypeChip.tsx
- frontend/src/employee-frontend/components/messages/ReceivedMessages.tsx
- frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
- frontend/src/employee-frontend/components/messages/api.ts
- frontend/src/employee-frontend/components/messages/types.ts
- frontend/src/lib-common/api-types/messaging/message.ts
- frontend/src/lib-components/molecules/MessageReplyEditor.tsx
- frontend/src/lib-components/utils/useReplyRecipients.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageService.kt
- Possible recipients are those who have participated in the thread (except self)
- Default recipients are those who participated in the last message
- The original thread author cannot be removed from recipients
- Disable reply button when the user has not entered any text and when the state is loading
> EVAKA-4190 Implement toggling of reply recipients

- frontend/src/e2e-playwright/browser.ts
> Capture Playwright page errors and logs

- frontend/src/e2e-playwright/pages/employee/reports.ts
- frontend/src/e2e-playwright/utils/element.ts
- frontend/src/e2e-playwright/utils/index.ts
- frontend/src/e2e-test/pages/admin/unit-details-page.ts
- frontend/src/e2e-test/pages/reports.ts
- frontend/src/employee-frontend/components/reports/Applications.tsx
- frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
- frontend/src/employee-frontend/components/reports/ChildAgeLanguage.tsx
- frontend/src/employee-frontend/components/reports/ChildrenInDifferentAddress.tsx
- frontend/src/employee-frontend/components/reports/EndedPlacements.tsx
- frontend/src/employee-frontend/components/reports/FamilyConflicts.tsx
- frontend/src/employee-frontend/components/reports/MissingHeadOfFamily.tsx
- frontend/src/employee-frontend/components/reports/MissingServiceNeed.tsx
- frontend/src/employee-frontend/components/reports/Occupancies.tsx
- frontend/src/employee-frontend/components/reports/PartnersInDifferentAddress.tsx
- frontend/src/employee-frontend/components/reports/PlacementSketching.tsx
- frontend/src/employee-frontend/components/reports/StartingPlacements.tsx
- frontend/src/employee-frontend/components/reports/VoucherServiceProviderUnit.tsx
- frontend/src/employee-frontend/components/reports/VoucherServiceProviders.tsx
- frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
- frontend/src/lib-components/atoms/form/Combobox.tsx
> More Combobox

- frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
> EVAKA-4190 Show recipient names

- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeThresholdsWithValidity.kt
* Fix fee decision income thresholds for 4 person families
* Fix sibling discount multiplier for cases other than 0.5 as well
> EVAKA-HOTFIX fee decision 4 person family income thresholds

- frontend/src/e2e-playwright/browser.ts
Often it's useful to have both the viewport screenshot and the full page screenshot.
> Capture also full page screenshots

- frontend/src/employee-frontend/api/unit.ts
- frontend/src/employee-frontend/components/UnitPage.tsx
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
- service/src/main/kotlin/fi/espoo/evaka/units/UnitsView.kt
Test how calculating missing group placements in kotlin affects performance
> EVAKA-TECH: faster missing group placements?

- message-service/src/integrationTest/resources/application-integration-test.yaml
- message-service/src/main/resources/application.yaml
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/resources/application.yaml
> EVAKA-HOTFIX: change mock s3 proxy

- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/components/Reports.tsx
- frontend/src/employee-frontend/components/reports/Applications.tsx
- frontend/src/employee-frontend/components/reports/Decisions.tsx
- frontend/src/employee-frontend/types/reports.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ReportSmokeTests.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/DecisionsReport.kt
> EVAKA-3573: decisions report

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUnitIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/MockVardaIntegrationEndpoint.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- service/src/test/kotlin/fi/espoo/evaka/varda/VardaUnitModelTest.kt
Add missing Varda unit create / update request mandatory lahdejarjestelma -paramater. Refactor code to equal other varda parts.
> Send missing lahdejarjestelma with varda unit

- message-service/owasp-suppressions.xml
- service/owasp-suppressions.xml
> Add an OWASP suppression for CVE-2021-22118

- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
Prefer personal account when selecting the default message account
> EVAKA-4190 Prefer personal account as default

- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageController.kt
> EVAKA-4190 Authorize admins to access messaging endpoints

- frontend/src/employee-frontend/api/child/placements.ts
- frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
- frontend/src/employee-frontend/types/child.ts
- frontend/src/employee-frontend/types/unit.ts
- frontend/src/lib-common/finite-date-range.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
> EVAKA-4209: show current group of child

- README.md
Add missing instructions on running CI for forked Pull Requests README
> Improve readme remote branch CI instructions

- frontend/src/employee-frontend/components/child-information/placements/CreatePlacementModal.tsx
> EVAKA-4250: improve direct placement unit filtering

- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-frontend/api/employees.ts
- frontend/src/employee-frontend/components/employees/EmployeeList.tsx
- frontend/src/employee-frontend/components/employees/EmployeePage.tsx
- frontend/src/employee-frontend/types/employee.ts
- frontend/src/employee-frontend/types/index.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
> EVAKA-4251: global role editor MVP

- frontend/src/e2e-playwright/pages/employee/employee-nav.ts
- frontend/src/e2e-playwright/pages/employee/invoicing/invoicing-page.ts
- frontend/src/e2e-playwright/specs/5_employee/value-decisions.spec.ts
- frontend/src/employee-frontend/api/invoicing.ts
- frontend/src/employee-frontend/components/common/Filters.tsx
- frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionFilters.tsx
- frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionsPage.tsx
- frontend/src/employee-frontend/state/invoicing-ui.tsx
- frontend/src/employee-mobile-frontend/components/attendances/components.tsx
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
Added similar date filters to voucher value decisions list that can be found in fee decisions list.
> EVAKA-4196 add date range to value decisions list

- frontend/src/e2e-playwright/specs/5_employee/value-decisions.spec.ts
> EVAKA-HOTFIX Fix an e2e that slipped through before e2e refactor merge

- service/src/main/kotlin/fi/espoo/evaka/reports/DecisionsReport.kt
> EVAKA-HOTFIX: fix decisions report preference_none

- frontend/src/lib-components/molecules/MessageBoxes.tsx
> Not displaying MessageBox when title and message is empty

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaChildrenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaOrganizerChildrenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaChildren.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaOrganizerChild.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- service/src/main/resources/db/migration/V106__create_varda_organizer_child.sql
- service/src/main/resources/migrations.txt
Add VardaOrganizerChild with a new table
> EVAKA-4148 new varda children

- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-frontend/components/WelcomePage.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Added welcome page for users without roles.
> EVAKA added welcome page for users without roles

- frontend/src/employee-frontend/components/ApplicationPage.tsx
- frontend/src/employee-frontend/components/application-page/ApplicationActionsBar.tsx
- frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
- frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx
Fix daily service time inputs not showing up when toggling preschool daycare on paper application editor.
Navigate back to child's info page when canceling the editing of a new application.
> EVAKA-HOTFIX preschool daycare paper application

- frontend/src/employee-mobile-frontend/assets/i18n/fi.ts
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceChildDeparted.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceChildPresent.tsx
- frontend/src/employee-mobile-frontend/components/attendances/child-info/ChildInfo.tsx
- frontend/src/employee-mobile-frontend/components/attendances/components.tsx
Add couple of missing styling updates to mobile ChildInfo page.
> EVAKA-4225 ChildInfo styling updates

- frontend/src/citizen-frontend/config.ts
- frontend/src/employee-frontend/components/Header.tsx
- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- frontend/src/employee-frontend/config.ts
> EVAKA-4190 Enable messaging in prod for pilot units

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDevController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
Run updateAll on demand to test integration in staging
> EVAKA-FIX run varda update all from dev controller

- frontend/src/e2e-test/pages/invoicing.ts
- frontend/src/e2e-test/specs/4_invoicing/fee-decisions.spec.ts
- frontend/src/e2e-test/specs/4_invoicing/voucher-value-decisions.spec.ts
- frontend/src/lib-components/atoms/buttons/AsyncButton.tsx
Wait for decision send action to show a success state before running pending async jobs.
> EVAKA invoicing flaky test improvements

- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
> EVAKA-HOTFIX: fix english application names

- message-service/README.md
- service/README.md
- Also generalize message-service docs as we're no longer Voltti-specific
- Follow the guide to update some certificate in e.g. dev trust store
> Docs: trust and key store usage in service

- service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/PDFServiceTest.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/Decision.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionDraftService.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt
For treVaka decision templates.
> Add unit phone to decision query results

- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
- service/src/main/resources/db/migration/R__dev_temp.sql
> EVAKA-4203: first draft of vasu backend

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt
Update bad urls & phone numbers
> EVAKA-HOTFIX application received email texts

- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-frontend/api/child/vasu.ts
- frontend/src/employee-frontend/components/vasu/VasuPage.tsx
- frontend/src/employee-frontend/config.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
> EVAKA-4203 first draft of vasu page

- frontend/src/employee-frontend/api/vasu.ts
- frontend/src/employee-frontend/components/ChildInformation.tsx
- frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx
- frontend/src/employee-frontend/state/child.tsx
- frontend/src/employee-frontend/types/vasu.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt
Implement initial child's Vasu and Leops view for dev purposes
> EVAKA-4203 Initial child's Vasu and Leops view

- frontend/src/employee-frontend/api/finance-basics.ts
- frontend/src/employee-frontend/components/common/StatusLabel.tsx
- frontend/src/employee-frontend/components/finance-basics/FeeThresholdsEditor.tsx
- frontend/src/employee-frontend/components/finance-basics/FeeThresholdsItemEditor.tsx
- frontend/src/employee-frontend/components/finance-basics/FeesSection.tsx
- frontend/src/employee-frontend/types/finance-basics.ts
- frontend/src/lib-common/api.ts
- frontend/src/lib-components/atoms/buttons/AsyncButton.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceBasicsController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/PricingQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeThresholds.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V109__fee_thresholds_default_id.sql
- service/src/main/resources/migrations.txt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/service/PdfServiceTest.kt
Copy and edit actions for fee thresholds.
Also changes `StatusLabel.tsx` component's dark green color to emerald to match the latest specs.
> EVAKA-4184 fee thresholds copying and editing

- .circleci/config.yml
- compose/db/postgresql.conf
- Adjust postgresql config:
- More meaningful logging
- More aggressive autovacuum & analyze settings
- Also store docker-compose logs for successful jobs
> CI job debugging tweaks

- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/HelsinkiDateTime.kt
> EVAKA-HOTFIX: patch attendance issue when lambda is missing

- frontend/src/e2e-playwright/browser.ts
- frontend/src/e2e-playwright/jest-environment.js
> Await playwright video promises properly

- frontend/src/employee-frontend/api/unit.ts
- frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
- frontend/src/employee-frontend/components/unit/TabApplications.tsx
- frontend/src/employee-frontend/types/application.ts
- service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Service need should be in application form data only if frontend feature flag `serviceNeedOptionsEnabled` is true -> this change should not affect Espoo.
> Add service need name to application lists

- frontend/src/employee-frontend/api/person.ts
- frontend/src/employee-frontend/components/ApplicationPage.tsx
- frontend/src/employee-frontend/components/Reports.tsx
- frontend/src/employee-frontend/components/child-information/FamilyContacts.tsx
- frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
- service/src/main/kotlin/fi/espoo/evaka/application/notes/NoteController.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/AbsenceController.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/ChildController.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/StaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ChildrenInDifferentAddressReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/PartnersInDifferentAddressReport.kt
Updated following accesses:
Child additional info should be editable by `STAFF` and `SPECIAL_EDUCATION_TEACHER`
Child daily notes should be editable by `SPECIAL_EDUCATION_TEACHER`
Absences should be editable by `SPECIAL_EDUCATION_TEACHER`
Application notes should be hidden from `UNIT_SUPERVISOR`
Hide partners and children in different addresses reports from `UNIT_SUPERVISORS`
Person contact info should be editable by `STAFF`
> EVAKA-4243 Updated access

- frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx
- frontend/src/lib-components/atoms/state/Spinner.tsx
- frontend/src/lib-components/molecules/FullScreenDimmedSpinner.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Move vasu template selection to modal.
Also implement full screen dimmed spinner which acts as loading state for actions that result in a modal opening or page navigation.
> EVAKA-4203 Move vasu template selection to modal

- frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Check that opening date is on or before closing date, and vice versa. Default min and max values are 1.1.1960 - 1.1.2100
> Prevent marking unit closed before it was opened

- frontend/src/employee-frontend/components/vasu/VasuPage.tsx
- frontend/src/employee-frontend/components/vasu/templates/CreateQuestionModal.tsx
- frontend/src/employee-frontend/components/vasu/templates/CreateTemplateModal.tsx
- frontend/src/employee-frontend/components/vasu/templates/VasuTemplateEditor.tsx
- frontend/src/employee-frontend/components/vasu/templates/VasuTemplatesPage.tsx
- frontend/src/employee-frontend/components/vasu/templates/api.ts
- frontend/src/employee-frontend/components/vasu/vasu-content.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplate.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateController.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateQueries.kt
- service/src/main/resources/db/migration/R__dev_temp.sql
> EVAKA-4203: oph questions, create template modal, template language

- apigw/src/shared/auth/suomi-fi-saml.ts
- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/auth/LoginErrorModal.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Show login error dialog. 
Test using URL `http://localhost:9099/?loginError=true`. 
Also fixed dev login error.
> Show error on failed login

- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailConfig.kt
Add optional email whitelisting to service. Depends on https://github.com/espoon-voltti/evaka-infra/pull/432.
Tested in staging with both whitelisted and non-whitelisted emails.
> EVAKA-TECH optional email whitelist

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDevController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
> Preparations for testing new varda update service in staging

- frontend/src/employee-frontend/components/person-profile/income/IncomeItemBody.tsx
- frontend/src/employee-frontend/types/income.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
If income has been generated from application then show it on the income list
> EVAKA-HOTFIX add application info to incomes in frontend

- frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx
- frontend/src/employee-frontend/components/vasu/api.ts
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
- service/src/main/resources/db/migration/R__dev_temp.sql
- Add `vasu_document_state` type enum.
- Also add explicit `modified_at` and `published_at` fields to vasu document. Update `modified_at` when content is updated.
> EVAKA-4203 Vasu document state

- frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx
- frontend/src/employee-frontend/components/vasu/api.ts
- frontend/src/employee-frontend/components/vasu/templates/VasuTemplatesPage.tsx
- frontend/src/employee-frontend/components/vasu/templates/api.ts
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateController.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateQueries.kt
Show and select valid vasu templates only.
> EVAVA-4203 Show and select valid templates

- service/src/main/kotlin/fi/espoo/evaka/shared/auth/Acl.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateController.kt
> EVAKA-4203: improved access control in vasu backend

- frontend/src/employee-frontend/components/child-information/placements/CreatePlacementModal.tsx
- frontend/src/lib-components/molecules/modals/FormModal.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
* Remove buggy `defaultUnit` from create placement modal
* Add more form validations in create placement modal
> EVAKA-HOTFIX placement modal default unit error

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDevController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- do not trigger update with old fee data
- improve logging
> Fixes after staging tests

- compose/README.md
- compose/db.sh
To help development here is script to dump and restore local database.
> Script to dump and restore local database

- frontend/src/employee-frontend/config.ts
> Enable finance basics page in staging

- frontend/src/citizen-frontend/applications/ApplicationCreation.tsx
- frontend/src/citizen-frontend/applications/api.ts
- frontend/src/citizen-frontend/messages/api.ts
- frontend/src/employee-frontend/components/messages/api.ts
Handle api call errors by wrapping them in `Result`.
> EVAKA-HOTFIX add missing try catches

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
-do not send child info to varda if child has no ssn
> Do not send child information to varda if child has no SSN

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- improve logging to make it easier to follow what the varda update actually does
> Improve varda update statistics logging

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaOrganizerChildrenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaOrganizerChild.kt
- service/src/main/resources/db/migration/V115__add_varda_person_id.sql
- service/src/main/resources/migrations.txt
Store varda person id for creating varda child
> EVAKA-FIX: Store varda person id for creating varda child

- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
Replace null with person url 🙄
> EVAKA-FIX varda henkilo part 2

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaOrganizerChildrenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaOrganizerChild.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
Use person oid, not organizer oid
> EVAKA-FIX use correct henkilo_oid

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaOrganizerChild.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
Use application.sentdate when possible
> EVAKA_FIX: varda paatos hakemuspvm

- frontend/src/employee-frontend/components/finance-basics/FeeThresholdsEditor.tsx
- frontend/src/employee-frontend/config.ts
Fix a couple of bugs related to date comparisons and enable fee thresholds editor in production.
> EVAKA-HOTFIX fix fee thresholds editor bugs

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
> Use guardians instead of fridge family as varda fee data guardian info

- frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx
- frontend/src/employee-frontend/components/common/VasuStateChip.tsx
- frontend/src/employee-frontend/components/vasu/VasuPage.tsx
- frontend/src/employee-frontend/components/vasu/api.ts
- frontend/src/employee-frontend/components/vasu/sections/VasuHeader.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
Implement vasu header section.
> EVAKA-4203 Vasu header section

- frontend/README.md
- frontend/src/e2e-playwright/pages/citizen/citizen-messages.ts
- frontend/src/e2e-playwright/pages/employee/messages/messages-page.ts
- frontend/src/e2e-playwright/specs/7_messaging/messaging.spec.ts
- frontend/src/e2e-playwright/utils/user.ts
- frontend/src/employee-frontend/components/messages/ReceivedMessages.tsx
- frontend/src/employee-frontend/components/messages/SentMessages.tsx
- frontend/src/lib-components/molecules/MessageReplyEditor.tsx
Add an e2e to test sending and replying to a message.
> EVAKA-4190: Messaging Playwright Tests

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- According to https://wiki.eduuni.fi/display/OPHPALV/Huoltajan+tiedot fee data must not be sent to varda if head of family is not the child's guardian
> If head of family is not a guardian, do not send fee data to varda

- frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx
- frontend/src/employee-frontend/components/vasu/VasuPage.tsx
- frontend/src/employee-frontend/components/vasu/api.ts
- frontend/src/employee-frontend/components/vasu/sections/VasuHeader.tsx
- frontend/src/employee-frontend/components/vasu/use-vasu.ts
Auto-save vasu document on changes. Display latest save time, show spinner while saving.
Also fix infinite loop if create request fails.
> EVAKA-4203 Auto-save vasu document on changes

- frontend/src/employee-frontend/components/invoices/Invoices.tsx
Use unique before passing children to component
> EVAKA-FIX: unique people for invoice children cell

- frontend/src/employee-frontend/api/applications.ts
- frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposalRow.tsx
- frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposals.tsx
- frontend/src/employee-frontend/types/application.ts
- frontend/src/employee-frontend/types/unit.ts
- frontend/src/lib-customizations/employee.tsx
- frontend/src/lib-customizations/espoo/employee.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- frontend/src/lib-customizations/types.d.ts
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlan.kt
- service/src/main/resources/db/migration/V117__placement_reject_reason_3.sql
- service/src/main/resources/migrations.txt
Adds support to customize placement reject reason selection list. Also adds third reason for Tampere.
> Add placement reject reason customization support

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Use an `EXISTS` query for finding duplicate applications instead of aggregating all duplicates in an array and checking the array length.
> Optimize the applications query

- .circleci/config.yml
- evaka-bom/build.gradle.kts
- message-service/build-docker.sh
- message-service/build.gradle.kts
- message-service/buildSrc/src/main/kotlin/Version.kt
- service/build.gradle.kts
- service/buildSrc/src/main/kotlin/Version.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/FamilySchemaConstraintsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/ParentshipDAOIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/PartnershipDAOIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueAreaReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageNotificationEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/InvoiceReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/MessageProvider.kt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
- service/vtjclient/build.gradle.kts
Highlights:
- Kotlin 1.5
- Spring Boot 2.5.1
> Upgrade backend dependencies

- frontend/src/employee-frontend/components/vasu/VasuPage.tsx
- frontend/src/employee-frontend/components/vasu/api.ts
- frontend/src/employee-frontend/components/vasu/sections/VasuEvents.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
- service/src/main/resources/db/migration/R__dev_temp.sql
Add event timestamps to vasu document schema, show them in events sections
> EVAKA-4203 Event timestamps

- .circleci/config.yml
- frontend/src/employee-frontend/components/common/Filters.tsx
- frontend/src/employee-frontend/components/fee-decisions/FeeDecisionFilters.tsx
- frontend/src/employee-frontend/components/invoices/InvoiceFilters.tsx
- frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionFilters.tsx
> Use clearable selector for finance unit and handler

- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Use more human-friendly wording
> EVAKA-FIX: better required validation message

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/PDFServiceTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/People.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/MessageProvider.kt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/domain/PeopleTest.kt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/service/PdfServiceTest.kt
Refactor hard coded values to support customization.
Also fixes voucher value fee decision po box visibility.
> Refactor default mail address to support customization

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaOrganizerChild.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
Add trivial fixes together with a more significant experiment where we try to fetch person data from Varda to ensure it matches their validations.
> EVAKA-FIX: minor v2rda fixes

- frontend/src/employee-frontend/components/vasu/templates/VasuTemplateEditor.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
> EVAKA-4203: confirm unsaved vasu template changes

- frontend/src/employee-frontend/components/vasu/templates/CopyTemplateModal.tsx
- frontend/src/employee-frontend/components/vasu/templates/VasuTemplatesPage.tsx
- frontend/src/employee-frontend/components/vasu/templates/api.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateController.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateQueries.kt
Add support for copying vasu templates.
- Copy custom vasu sections from a template to another
- Add 1 year to both start and end date by default
> EVAKA-4203 Copy vasu template

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
> EVAKA-FIX: experimental varda guardians

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- Store varda ids on failure
- Do not double process retried service needs modified today
- Improve logging
> Fix failure handling and add logging

- frontend/src/employee-frontend/components/vasu/VasuPage.tsx
- frontend/src/employee-frontend/components/vasu/api.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
Implement vasu state transitions with events
> EVAKA-4203 State transitions

- frontend/src/employee-frontend/components/vasu/VasuPage.tsx
- frontend/src/employee-frontend/components/vasu/api.ts
- frontend/src/employee-frontend/components/vasu/sections/EvaluationDiscussionSection.tsx
- frontend/src/employee-frontend/components/vasu/sections/VasuDiscussionSection.tsx
- frontend/src/employee-frontend/components/vasu/sections/VasuEvents.tsx
- frontend/src/employee-frontend/components/vasu/use-vasu.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
- service/src/main/resources/db/migration/R__dev_temp.sql
> EVAKA-4203: vasu and evaluation discussion sections

- frontend/src/employee-frontend/components/ChildInformation.tsx
- frontend/src/employee-frontend/components/vasu/VasuPage.tsx
- frontend/src/employee-frontend/components/vasu/VasuStateTransitionButtons.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt
Implement vasu state transition modals.
> EVAKA-4203 Vasu state transition modals

- frontend/src/e2e-playwright/specs/7_messaging/messaging.spec.ts
Do not try to login again when not having logged out in between
> EVAKA-HOTFIX: fix flaky messaging e2e test

- frontend/src/employee-frontend/components/common/VasuStateChip.tsx
- frontend/src/employee-frontend/components/vasu/VasuPage.tsx
- frontend/src/employee-frontend/components/vasu/VasuStateTransitionButtons.tsx
- frontend/src/employee-frontend/components/vasu/api.ts
- frontend/src/employee-frontend/components/vasu/sections/AuthorsSection.tsx
- frontend/src/employee-frontend/components/vasu/sections/EvaluationDiscussionSection.tsx
- frontend/src/employee-frontend/components/vasu/sections/VasuDiscussionSection.tsx
- frontend/src/employee-frontend/components/vasu/use-vasu.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
- service/src/main/resources/db/migration/R__dev_temp.sql
> EVAKA-4203: authors section and section numberings

- frontend/src/employee-frontend/components/unit/tab-groups/groups/group/GroupUpdateModal.tsx
- service/src/main/resources/db/migration/V119__daycare_group_start_before_end.sql
- service/src/main/resources/migrations.txt
Group end date should never be before start date
> Group end date validation

- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
- service/src/main/resources/db/migration/R__dev_temp.sql
> EVAKA-4203: publishing backend

- service/src/main/resources/db/migration/R__dev_temp.sql
> EVAKA-HOTFIX: fix vasu R-migration to cascade on drop tables

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementType.kt
Filter uninvoiced placement types already in SQL
> EVAKA-HOTFIX: bad placement type for invoicing

- service/src/main/kotlin/fi/espoo/evaka/vtjclient/service/persondetails/PersonStorageService.kt
Init child when a child person is created so that for example editing the child profile info works before an application is created
> Init child table when a child person is created

- service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuTemplateIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplate.kt
> EVAKA-4203: vasu integration tests

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDevController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- Allow varda child reset in all environments
- Fix a typo in sql
> Evaka 4000 reset child fix

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
> Only send SENT fee data to Varda

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
Add happy path logging for child reset
Add better logging for delete steps
> EVAKA-4000: better logging for Varda child reset

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerator.kt
Let voucher value decision period change on next first of month after third birthday (unless the child is born on first of month).
> EVAKA-4217: voucher value period after third birthday

- frontend/src/employee-frontend/config.ts
> EVAKA-AI: enable route on staging

- frontend/src/e2e-test/pages/employee/child-information/child-information-page.ts
- frontend/src/e2e-test/pages/employee/messaging/messages-page.ts
- frontend/src/e2e-test/specs/2_employee-2/paper-application.spec.ts
- frontend/src/e2e-test/utils/helpers.ts
- frontend/src/employee-frontend/components/child-information/CreateApplicationModal.tsx
- frontend/src/employee-frontend/components/child-information/placements/CreatePlacementModal.tsx
- frontend/src/employee-frontend/components/common/Select.tsx
- frontend/src/employee-frontend/components/decision-draft/DecisionDraft.tsx
- frontend/src/employee-frontend/components/invoice/InvoiceRowsSectionRow.tsx
- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/messages/Sidebar.tsx
- frontend/src/employee-frontend/components/reports/EndedPlacements.tsx
- frontend/src/employee-frontend/components/reports/Occupancies.tsx
- frontend/src/employee-frontend/components/reports/VoucherServiceProviderUnit.tsx
- frontend/src/employee-frontend/components/reports/VoucherServiceProviders.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/group/GroupTransferModal.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/missing-group-placements/BackupCareGroupModal.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/missing-group-placements/GroupPlacementModal.tsx
- frontend/src/lib-components/atoms/form/Combobox.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Refactor `Select` component to use `Combobox` instead of `react-select`.
> Refactor Select component to use Combobox instead of react-select

- frontend/src/lib-components/atoms/form/Combobox.stories.tsx
- frontend/src/lib-components/atoms/form/Combobox.tsx
- Indicate Combobox open state in toggle
- Add story
> Indicate Combobox open state in toggle

- frontend/src/lib-components/molecules/CollapsibleSection.tsx
> Fix chevron direction in collapsible section

- frontend/src/citizen-frontend/applications/ChildApplicationsBlock.tsx
- frontend/src/citizen-frontend/decisions/shared.tsx
- Use dark greyscale for draft
- Use red accent for rejected
- Use correct icon size and align properly
**Before**
**After**
> Fix application and decision status icons

- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt
Always try to show validTo on relief decisions. If the end date is missing for any reason though, fallback to open ended version.
> EVAKA-FIX: Always try to show validTo on relief decisions

- frontend/src/employee-frontend/App.tsx
React router's Switch does not work correctly if its child routes are wrapped in a fragment.
> EVAKA-FIX broken redirect to login page

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaFeeDataIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaOrganizerChildrenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaChildren.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaOrganizerChild.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- service/src/main/resources/db/migration/V121__add_person_oid.sql
- service/src/main/resources/migrations.txt
Each person that will be sent to varda should have either SSN or OID in our DB. If a person doesn't have SSN in DVV they are first manually inserted into Varda and their OID then manually updated to eVaka. Then we can use their OID as an identifier when communicating with Varda.
> EVAKA-4000 handle people without ssn

- frontend/src/employee-mobile-frontend/assets/i18n/fi.ts
- frontend/src/employee-mobile-frontend/components/attendances/child-info/ChildButtons.tsx
- frontend/src/employee-mobile-frontend/components/attendances/child-info/ChildInfo.tsx
- frontend/src/employee-mobile-frontend/components/attendances/components.tsx
- frontend/src/employee-mobile-frontend/components/mobile/components.tsx
- frontend/src/lib-components/atoms/Chip.tsx
Add minor CSS tweaks to child's mobile view
> [EVAKA-4267] Mobile UI tweaks

- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/JobSchedule.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Daily job that logs ids of people that have no data that has to be kept and can be removed from the database.
> EVAKA clean up inactive people

- service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt
Querying one at a time took 7.5 hours in production even if the load was minimal.
> Do inactive people query in one database query

- frontend/src/lib-components/typography.ts
> Add underline to <a> elements inside <P>

- frontend/src/e2e-playwright/pages/employee/child-information-page.ts
- frontend/src/e2e-playwright/specs/8_access/access.spec.ts
- frontend/src/e2e-test/pages/employee/child-information/child-information-page.ts
- frontend/src/e2e-test/specs/2_employee-2/child-information.spec.ts
- frontend/src/employee-frontend/components/ChildInformation.tsx
- frontend/src/employee-frontend/components/Search.tsx
- frontend/src/employee-frontend/components/child-information/BackupPickup.tsx
- frontend/src/employee-frontend/components/child-information/FamilyContacts.tsx
- frontend/src/employee-frontend/components/child-information/FridgeParents.tsx
- frontend/src/employee-frontend/components/child-information/GuardiansAndParents.tsx
- frontend/src/employee-frontend/components/child-information/Placements.tsx
- frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Update child page layout by grouping up some sections into one. Fridge parents section is moved under guardians section and backup pickups are moved under family contacts.
Also includes some small UI changes to match the latest specs.
> EVAKA child page collapsible grouping

- frontend/src/employee-mobile-frontend/components/attendances/ChildListItem.tsx
- frontend/src/lib-icons/free-icons.ts
- frontend/src/lib-icons/index.ts
- frontend/src/lib-icons/pro-icons.ts
Update child block layout slightly in employee mobile list views to match newest UX specs. Also changes the backup care indicator icon's color from primary blue to accent green.
> EVAKA employee mobile icons in list view

- frontend/src/lib-components/molecules/FileUpload.tsx
- Fixes Sentry issue: [EVAKA-CITIZEN-FRONTEND-R](https://sentry.io/organizations/espoon-voltti/issues/2395241288/)
- Though the stack trace is identical to the original issue (https://github.com/espoon-voltti/evaka/pull/849), this is a different issue altogether but Sentry doesn't support manually splitting events to new issues so here we go :shrug:
- Disable the file delete button in `FileUpload` once deletion has been started
- Previously a user could click a button multiple times, which (on an unreliable mobile connection, for example) could lead to 403 errors when the first request goes through and all subsequent requests fails due to the attachment already being deleted
- This is effectively similar to using `AsyncButton` but currently that button includes UI which isn't usable here …
> [EVAKA-HOTFIX] Prevent double clicks on file delete & download during delete

- frontend/src/e2e-test/utils/helpers.ts
- frontend/src/employee-frontend/components/fee-decisions/FeeDecisions.tsx
- frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisions.tsx
- frontend/src/lib-components/atoms/form/Combobox.tsx
- frontend/src/lib-components/atoms/form/InputField.tsx
- frontend/src/lib-components/molecules/DatePickerDeprecated.tsx
Make the input and combobox border colors darker and update combobox styles to match specs more closely.
Attempt to fix some e2e flakyness by disabling fee and value decision toggles when the decisions haven't been loaded.
> Update input and combobox border colors

- frontend/src/employee-frontend/api/applications.ts
- frontend/src/employee-frontend/components/ApplicationPage.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Add term validation errors to employee application editor since the back end will reject start dates that do not match a term anyway.
> Add terms validation to employee application editor

- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-frontend/components/FinancePage.tsx
- frontend/src/employee-frontend/components/Reports.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
The feature flag should be unnecessary now as well.
> Enable voucher value decisions in prod

- service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/JobSchedule.kt
Automatically delete all people with no archived data. Disable the scheduled job as a default to test it in staging first.
> Automatically delete people with no archive data

- frontend/src/employee-frontend/components/vasu/templates/VasuTemplateEditor.tsx
- frontend/src/employee-frontend/components/vasu/templates/api.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuTemplateQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplate.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateQueries.kt
readonly mode in frontend for used vasu templates
> EVAKA-4203: prevent changes to vasu template content once it is in use

- apigw/package.json
- apigw/yarn.lock
Verified in staging that login still works after this upgrade
> Forcibly upgrade to xmldom 0.7

- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-frontend/components/ChildInformation.tsx
- frontend/src/employee-frontend/components/Header.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
- service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
> EVAKA-4203: enable vasu in staging

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
Send fee data for all guardians living in the same address
> Only send fee data if the head of family is the child's guardian

- service/src/main/kotlin/fi/espoo/evaka/pis/service/MergeService.kt
constraint violation in merge tool should return http 409 instead of http 500
> EVAKA-HOTFIX: improve merge tool error handling

- frontend/src/lib-components/atoms/form/Checkbox.tsx
It was changed in the design system already a long time ago.
> Change checkbox label font size from 15 px to 16 px

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- improve varda data removal logging
> Support effica decisions in varda update

- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionAddress.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/People.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/MessageProvider.kt
- service/src/main/resources/WEB-INF/templates/fee-decision/decision.html
- service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.html
- service/src/test/kotlin/fi/espoo/evaka/invoicing/domain/PeopleTest.kt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/service/PdfServiceTest.kt
To support multiple address rows in fee decisions.
> Refactor fee decision template address model

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaChildren.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
Avoid sending null values to /hae-henkilo and /henkilot
> EVAKA-4000: fix bad person payload

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
Almost trivial pr to
- introduce some variables for self-documenting / clarification
- add test to ensure all fee data related to a service need is sent
> EVAKA-4000: minor fee data tweak

- apigw/src/internal/routes/auth-status.ts
- apigw/src/shared/service-client.ts
- frontend/src/employee-frontend/components/Header.tsx
- frontend/src/employee-frontend/types/index.ts
- service/src/main/kotlin/fi/espoo/evaka/pis/SystemIdentityController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/EmployeeFeatures.kt
Part 1: move menu item visibility checks to the backend. This removes several hard-coded role lists from the frontend, and enables the backend to have more complicated logic if necessary.
> New frontend access control - part 1

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- Log all varda child ids that should be reset in varda
- Only mark varda child resetted if all data was uploaded correctly
> Improve varda reset error handling and logging

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- Do not try to fetch guardians after failed fee data varda upload
- Log beginning part of ssn after a failed request for debugging
> Evaka 4000 improve reliability

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
Exclude null nullables from VardaGuardian
> EVAKA-4000: exclude null oid from guardian payload

- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
- service/src/main/resources/db/migration/R__dev_temp.sql
> EVAKA-4240 database model for attendance reservation

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
> Handle non invoiced service needs correctly

- frontend/src/citizen-frontend/auth/state.tsx
- frontend/src/citizen-frontend/header/DesktopNav.tsx
- frontend/src/citizen-frontend/header/MobileNav.tsx
- frontend/src/citizen-frontend/messages/ThreadList.tsx
- frontend/src/e2e-playwright/specs/7_messaging/messaging.spec.ts
- frontend/src/e2e-playwright/specs/8_access/access.spec.ts
- frontend/src/e2e-test-common/dev-api/fixtures.ts
- frontend/src/e2e-test-common/dev-api/index.ts
- frontend/src/e2e-test-common/dev-api/types.ts
- frontend/src/employee-frontend/components/Header.tsx
- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccountQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/Acl.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/CitizenFeatures.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/PilotFeature.kt
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/controllers/VtjController.kt
- service/src/main/resources/db/migration/V129__add_pilot_daycare_field.sql
- service/src/main/resources/dev-data/espoo-dev-data.sql
- service/src/main/resources/migrations.txt
* Citizen gets a list of accessible features in auth-status
* Create daycare pilot feature data field.
* Access to messaging is restricted based on enabled daycare pilot features.
* Message receivers are filtered based on enabled daycare pilot features.
> Citizen accessible features, daycare pilot features

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
> EVAKA-4000 fix reset logic

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementType.kt
Take only invoiced placements into account when determining whether a child gets July for free or not.
> EVAKA-HOTFIX free july and placement types

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- service/src/main/resources/db/migration/V130__varda_service_need_updated.sql
- service/src/main/resources/migrations.txt
- add created and update columns to varda_service_need
- fix logging
> Evaka 4000 add updated to varda service need

- frontend/src/employee-frontend/api/unit.ts
- frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
- frontend/src/employee-frontend/types/child.ts
- frontend/src/employee-frontend/types/reports.ts
- frontend/src/employee-frontend/types/unit.ts
- frontend/src/lib-customizations/employee.tsx
- frontend/src/lib-customizations/espoo/employee.tsx
- frontend/src/lib-customizations/types.d.ts
Tampere needed to remove "Suomenkielinen opetustoimi" (TREV-269)
> Customizable unit provider types

- frontend/src/employee-frontend/components/common/CareTypeLabel.tsx
- frontend/src/employee-frontend/types/index.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Group tables didn't show the new placement type (see https://github.com/espoon-voltti/evaka/pull/956)
> Add school shift care support to group tables

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
> EVAKA-4000: minor varda tweaks

- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/auth/state.tsx
- frontend/src/citizen-frontend/calendar/CalendarListView.tsx
- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/DayElem.tsx
- frontend/src/citizen-frontend/calendar/WeekElem.tsx
- frontend/src/citizen-frontend/calendar/api.ts
- frontend/src/citizen-frontend/header/DesktopNav.tsx
- frontend/src/citizen-frontend/header/MobileNav.tsx
- frontend/src/lib-common/local-date.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationsControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/CitizenFeatures.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/PilotFeature.kt
- service/src/main/resources/db/migration/R__dev_temp.sql
- service/src/main/resources/db/migration/V133__add_reservations_pilot_feature.sql
- service/src/main/resources/dev-data/espoo-dev-data.sql
- service/src/main/resources/migrations.txt
> EVAKA-4240: mobile first calendar

- service/src/main/kotlin/fi/espoo/evaka/reports/MissingServiceNeedReport.kt
> EVAKA-HOTFIX: fix missing service need report

- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
Nowadays we should throw on failure and avoid all optimistic designs.
> EVAKA-4000 fail fast paginated get

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDevController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
> EVAKA-4000 reset error messages

- frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
- frontend/src/lib-customizations/employee.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
The handlers not needed in the city's implementation need to be removed from the "decisionCustomization.handler" array.
> Customizable decision customization handlers

- frontend/package.json
- frontend/yarn.lock
- fixes random `page.isVisible` failures that are causing some E2E flakiness
> Upgrade to Playwright 1.14

- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt
- service/src/main/resources/WEB-INF/templates/fee-decision/decision.html
- service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
Added fee alteration amount and "is absolute" values to PDF variables to able to use them in templates.
> Update fee alteration pdf variables

- service/src/main/kotlin/fi/espoo/evaka/shared/utils/FuelExtensions.kt
- Log if request RETRY_AFTER is large
> Improve varda client logging

- frontend/src/employee-mobile-frontend/api/attendances.ts
- frontend/src/employee-mobile-frontend/assets/i18n/fi.ts
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceChildAbsent.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceChildDeparted.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceChildPresent.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceDailyServiceTimes.tsx
- frontend/src/employee-mobile-frontend/components/attendances/ChildListItem.tsx
- frontend/src/employee-mobile-frontend/components/attendances/child-info/ArrivalAndDeparture.tsx
- frontend/src/employee-mobile-frontend/components/attendances/child-info/ChildInfo.tsx
- frontend/src/employee-mobile-frontend/components/attendances/components.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceUpkeepIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
Show attendance reservations in child list and child page in employee mobile. No feature flags or pilot feature checks are used (should they?).
Also refactor:
* existing code under attendance package to use `HelsinkiDateTime` instead of `Instant`s and `OffsetDateTime`s and pass the query date as parameter.
* mobile child page
> EVAKA-4240 attendance reservations in employee mobile

- frontend/src/employee-frontend/components/Header.tsx
- frontend/src/employee-frontend/components/messages/EmptyMessageFolder.tsx
- frontend/src/employee-frontend/components/messages/MessageComponents.tsx
- frontend/src/employee-frontend/components/messages/MessageList.tsx
- frontend/src/employee-frontend/components/messages/ReceivedMessages.tsx
- frontend/src/employee-frontend/components/messages/Sidebar.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Make some UI fixes to the employee side of the messaging.
> EVAKA-4190: Messaging employee UI fixes

- frontend/src/employee-frontend/components/messages/MessageList.tsx
Inbox loading state is currently displayed incorrectly. Fix that.
> EVAKA-4190: Fix inbox loading state

- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/api.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenControllerTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
> EVAKA-4240: citizen makes reservations backend v1

- frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- Clean up error messages
- Remove some unnecessary & repeating try-catches
- Add more metadata to client errors that are written to db
- Remove too aggressive oid validations from UI (basically a bugfix)
> EVAKA-4000 tweak error handling

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- use relative starting from timestamp
- update varda service need evaka service need timestamp in retry
- only include modified service needs which have not yet been tried to be sent to varda
> Improve service need modification detection

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- remove char limit from logging errors to db
- exclude service needs with 0 hour option
- update delete operation (for sync): break after failure (no point in continuing) + rely on try-catch
> EVAKA-4000 minor improvements

- service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.html
See [this](https://voltti.atlassian.net/browse/EVAKA-4275) for details.
> EVAKA-4275: Fix voucher value decision layout

- .circleci/config.yml
Fix failing download on CI test that prevents E2E.
> Fix failing download in CI E2E tests

- service-lib/src/main/kotlin/fi/espoo/voltti/logging/MdcKey.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/AuthenticatedUser.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/JwtToAuthenticatedUser.kt
This field was never put into the MDC, so it was never included in logs.
> Log userIdHash in service logs

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDevController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaOrganizerChild.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- move oid check to better position
- clean up logic and some log messages
- clean up dead code
> EVAKA-4000 minor varda improvements part x

- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/components/Reports.tsx
- frontend/src/employee-frontend/components/reports/VardaErrors.tsx
- frontend/src/employee-frontend/types/reports.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ReportSmokeTests.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceNeedReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/VardaErrorReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/VardaErrorsReport.kt
> Evaka 4000 varda errors report

- frontend/src/employee-frontend/api/child/placements.ts
- frontend/src/employee-frontend/api/unit.ts
- frontend/src/employee-frontend/components/child-information/placements/service-needs/ServiceNeedReadRow.tsx
- frontend/src/employee-frontend/types/child.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
- service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeed.kt
- service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedConfirmationDeserializer.kt
- service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- service/src/main/resources/db/migration/V137__service_need_confirmed_by_nullable.sql
- service/src/main/resources/migrations.txt
https://github.com/espoon-voltti/evaka/pull/871 added support for application service need (i.e. citizen selects service need in the application form). This PR adds support to automatically persist that service need to placement when citizen accepts the decision.
> Set application service need to placement

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/MockVardaIntegrationEndpoint.kt
Find full service need change set instead of using modification timestamp
> EVAKA-4000 new service need query

- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkDeparted.tsx
- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkPresent.tsx
- frontend/src/employee-mobile-frontend/components/attendances/child-info/ArrivalAndDeparture.tsx
- frontend/src/employee-mobile-frontend/components/attendances/child-info/ChildInfo.tsx
- frontend/src/lib-common/date.spec.ts
- frontend/src/lib-common/date.ts
- Disable submit button if time input value is not valid
- Replace artisan time formatting with date-fns
> Validate time string properly in child attendance forms

- frontend/src/employee-frontend/components/reports/VardaErrors.tsx
- frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
- Remove varda errors excel report
- Trim unit oph attributes
> Evaka 4000 minor improvements

- service/src/main/kotlin/fi/espoo/evaka/shared/auth/Acl.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
> EVAKA-HOTFIX: Fix authorization of global scope actions for scoped roles

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- improve varda sync progress logging, and log successful operations
> Improve varda sync progress and success logging

- frontend/package.json
- frontend/src/citizen-frontend/header/EspooLogo.tsx
- frontend/src/citizen-frontend/map/UnitList.tsx
- frontend/yarn.lock
Related to JIRA TREV-297:
- Needed e2e-playwright link to package.json to get Tampere e2e tests working with Espoo tests' sources
- Add some data-qa attrs for checking Tampere-specific changes
These changes also help other cities to test their implementation of evaka
> e2e-playwright link + add needed data-qa attrs

- frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
- frontend/src/citizen-frontend/income-statements/types/body.ts
> EVAKA-4213 Require accountant info for self employed

- frontend/src/citizen-frontend/header/DesktopNav.tsx
- frontend/src/citizen-frontend/header/MobileNav.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
> EVAKA-4213 Enable experimental citizen income statements navigation in staging

- frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
- frontend/src/citizen-frontend/income-statements/api.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
* List income statements within table
* Income statements can be deleted only if they have not been handled
> EVAKA-4213 Citizen income statement listing and removal

- frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
- frontend/src/citizen-frontend/income-statements/api.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Use modal to prevent accidental deletions.
~Pending rebase after #1310.~
> EVAKA-4213 Confirmation modal for deleting income statement

- frontend/src/e2e-test/specs/2_employee-2/application-transitions.spec.ts
- frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposals.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
> EVAKA-4236: allow partial acceptance of placement proposal

- frontend/src/e2e-playwright/pages/employee/child-information.ts
- frontend/src/e2e-playwright/specs/5_employee/child-information.spec.ts
- frontend/src/e2e-test-common/dev-api/data-init.ts
- frontend/src/e2e-test-common/dev-api/fixtures.ts
- frontend/src/employee-frontend/components/ChildInformation.tsx
- frontend/src/employee-frontend/components/PersonProfile.tsx
- service/src/main/resources/mock-vtj-data.json
> Evaka fix indicate deceased child

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaOrganizerChild.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- remove excess logging
- exclude service needs with < 1 hours per week
- try to parse varda client errors
> EVAKA-4000 clean up and improve Varda update

- frontend/src/employee-frontend/components/reports/Raw.tsx
- frontend/src/employee-frontend/components/reports/ReportDownload.tsx
- frontend/src/employee-frontend/components/reports/VoucherServiceProviderUnit.tsx
- frontend/src/employee-frontend/types/reports.ts
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
> Add cost center column to the raw report

- frontend/src/employee-frontend/components/person-profile/income/income-table/IncomeTableRow.tsx
- frontend/src/employee-frontend/types/income.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Incomes.kt
> Add new income coefficients

- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenControllerTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
Add some basic validation to citizen reservations. Also make next year reservable for citizens a month earlier.
> EVAKA-4240 basic citizen reservation validations

- service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt
> EVAKA-4213 Prevent citizen from editing/deleting handled income statements

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/MockVardaIntegrationEndpoint.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- Parse errors from different keys
- Add simple way to verify parsing
- Also remove unnecessary cleaning of old tables
> EVAKA-4000 better error handling for varda client

- service/src/main/resources/db/migration/V139__absence_modified_by_citizen.sql
> EVAKA-HOTFIX split very long migration into two parts

- frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
- frontend/src/e2e-playwright/pages/citizen/citizen-header.ts
- frontend/src/e2e-playwright/pages/citizen/citizen-income.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-income-statement.spec.ts
> EVAKA-4213 Simple e2e test for submitting income statement

- frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx
- frontend/src/employee-frontend/types/person.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
> Include person oph oid in profile data
