frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Update income form text

frontend/src/e2e-test/specs/5_employee/leops.spec.ts, frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx, frontend/src/lib-components/assistance-need-decision/AssistanceNeedDecisionReadOnly.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/sv.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt, service/src/main/resources/WEB-INF/templates/assistance-need/decision.html, service/src/main/resources/WEB-INF/templates/assistance-need/decision.properties, service/src/main/resources/WEB-INF/templates/assistance-need/decision_sv.properties
=> Vasu, leops, and assistance need decision text changes

frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx
Fixes csv when opened in Excel apparently. Same is used at least in occupancy report.
=> Fix attendance reservation report decimal format

frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/utils/page.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
=> Don't try to create buckets that already exist in S3 mock

service/src/main/resources/db/migration/V265__finance_decisions_partner_constraint.sql, service/src/main/resources/migrations.txt
=> Add a check constraint for finance decision partners

frontend/src/employee-frontend/api/unit.ts, frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx, frontend/src/lib-common/generated/api-types/daycare.ts, service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
Hide shut down units from unit ACL editor (when adding new permissions)
=> Hide shut down units from unit ACL editor

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/VTJBatchRefreshServiceIntegrationTest.kt
=> Clean leftovers from a change (fixes compiler warning)

evaka-bom/build.gradle.kts
=> Upgrade a dependency to fix a CVE

service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
=> Avoid conflicts or handle them gracefully with realtime staff attendances

frontend/src/employee-frontend/components/absences/AbsenceCell.tsx, frontend/src/lib-common/generated/api-types/daycare.ts, frontend/src/lib-common/utils/absences-date-range.spec.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenQueriesTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/AbsenceController.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt, service/src/main/kotlin/fi/espoo/evaka/reports/PresenceReport.kt, service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt, service/src/main/kotlin/fi/espoo/evaka/reports/SextetReport.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
This is for quicker revert of possible performance degrading changes.
=> Revert absence logic changes

frontend/src/employee-frontend/api/reports.ts, frontend/src/employee-frontend/components/reports/Occupancies.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt, service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt, service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt, service/src/main/kotlin/fi/espoo/evaka/reports/OccupancyReport.kt
Also adds sane default for provider type filter.
=> Add occupancy report unit type filter

service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt, service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
=> Fix occupancy report showing closed units with given period

frontend/src/citizen-frontend/children/ChildPage.tsx, frontend/src/citizen-frontend/children/api.ts, frontend/src/citizen-frontend/children/state.tsx, frontend/src/citizen-frontend/navigation/DesktopNav.tsx, frontend/src/citizen-frontend/navigation/MobileNav.tsx, frontend/src/e2e-test/pages/citizen/citizen-header.ts, frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts, frontend/src/e2e-test/specs/0_citizen/citizen-header.spec.ts, frontend/src/lib-common/generated/api-types/children.ts, service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/children/Children.kt, service/src/main/kotlin/fi/espoo/evaka/children/ChildrenQueries.kt
Only show children with an active or future placement or some documents to read in the citizen children menu.
=> Hide inactive children from citizen children menu

service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
=> Add more checks to silence staff attendance alerts

frontend/src/citizen-frontend/attachments.ts
=> Fix downloading of attachments with special characters in the name

frontend/src/employee-frontend/components/applications/ApplicationsFilters.tsx, frontend/src/employee-frontend/components/common/Filters.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
Add a select/unselect all button under the all application statuses checkboxes.
https://user-images.githubusercontent.com/70927/188797232-5c495a9b-2554-4dd6-a630-bbfc2d6798df.mov
=> Add select/unselect all to application search all statuses filter

service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
=> Fix calendar event access control check

frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/dev-api/index.ts, frontend/src/e2e-test/dev-api/types.ts, frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts, frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/FixtureBuilder.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- Add planned attendances for employees without realtime attendances
=> Evaka 4598 staff plans week view

frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
=> Use a translated string

proxy/files/etc/nginx/conf.d/nginx.conf.template
=> Limit configuration

frontend/src/citizen-frontend/messages/MessagesPage.tsx, frontend/src/citizen-frontend/navigation/MobileNav.tsx
=> Fix footer

service/src/main/kotlin/fi/espoo/evaka/shared/config/AwsConfig.kt
This was already fixed in the integration test config in an earlier pull request
=> Don't try to create buckets that already exist (local dev edition ™)

frontend/src/employee-frontend/components/unit/TabCalendar.tsx
The occupancy graph was moved below the calendar in the same PR with calendar events. Now it's moved back to the top.
=> Move occupancy graph back above attendance calendar

frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/sv.tsx, service/src/main/resources/WEB-INF/templates/assistance-need/decision_sv.properties
=> More sv translations for assistance decision

service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
=> Silence more staff attendance alerts

frontend/src/lib-customizations/espoo/employee/assets/i18n/vasu/sv.ts, service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
To test these create new Swedish daycare and preschool curriculum templates.
=> EVAKA-4630 Svebi translations for curriculum default contents

frontend/src/e2e-test/pages/employee/child-information.ts, frontend/src/e2e-test/specs/5_employee/child-information.spec.ts, frontend/src/employee-frontend/components/child-information/FamilyContacts.tsx
This fixes the broken UX as well as makes E2E tests non-flaky.
Before: 
After:
<video src="https://user-images.githubusercontent.com/70927/188869878-78c5e070-302d-4077-8720-192dc5d3596c.mov">
=> Rehaul family contact editing

frontend/src/e2e-test/pages/employee/vasu/pageSections.ts, frontend/src/e2e-test/specs/5_employee/vasu.spec.ts
=> Fix promise use in vasu e2e tests

service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareQueries.kt
=> Avoid deleting unrelated backup cares

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> Open vasu and leops in production

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/DuplicatePeopleReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/DuplicatePeopleReport.kt
=> Trim white spaces from duplicate people report matching

frontend/src/employee-frontend/components/reports/MissingServiceNeed.tsx
* Use `useApiState` and `renderResult`
* Tell the user if there are no results more clearly
=> Missing service needs report enhancements

frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Update accessibility statement

frontend/src/employee-frontend/components/invoice/InvoiceRowsSectionRow.tsx, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
=> Disallow non-negative amounts in invoice rows

frontend/src/employee-frontend/api/child/fee-alteration.ts, frontend/src/employee-frontend/components/child-information/FeeAlteration.tsx, frontend/src/employee-frontend/components/child-information/fee-alteration/FeeAlterationEditor.tsx, frontend/src/employee-frontend/components/child-information/fee-alteration/FeeAlterationList.tsx, frontend/src/employee-frontend/types/fee-alteration.ts, frontend/src/lib-common/generated/action.d.ts, frontend/src/lib-common/generated/api-types/invoicing.ts, service/codegen/src/main/kotlin/evaka/codegen/actionenum/Definitions.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeAlterationIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeAlterationController.kt
=> Fix fee alteration buttons visibility

frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionEditPage.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/api.ts, frontend/src/employee-frontend/components/child-information/assistance-need/decision/assistance-need-decision-form.ts, frontend/src/lib-common/generated/action.d.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt, service/src/main/kotlin/fi/espoo/evaka/Audit.kt, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
=> Assistance decision maker options

frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
=> Fix group link in child's placements section

frontend/src/employee-frontend/components/person-profile/PersonFeeDecisions.tsx, frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx
=> Fix fee / voucher value decision buttons visibility

frontend/src/employee-frontend/api/income.ts, frontend/src/employee-frontend/components/child-information/ChildIncome.tsx, frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx, frontend/src/employee-frontend/components/person-profile/income/IncomeItemHeader.tsx, frontend/src/employee-frontend/components/person-profile/income/IncomeList.tsx, frontend/src/employee-frontend/types/income.ts, frontend/src/lib-common/generated/action.d.ts, service/codegen/src/main/kotlin/evaka/codegen/actionenum/Definitions.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/IncomeIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/IncomeController.kt
=> Fix income buttons visibility

service/owasp-suppressions.xml
https://nvd.nist.gov/vuln/detail/CVE-2022-38751
=> Suppress CVE-2022-38751

frontend/src/employee-frontend/components/unit/TabCalendar.tsx, frontend/src/employee-frontend/types/unit.ts
=> Don't crash the calendar page if a unit doesn't have operating days

frontend/src/employee-frontend/App.tsx, frontend/src/employee-frontend/api/reports.ts, frontend/src/employee-frontend/components/Reports.tsx, frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx, frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx, frontend/src/lib-common/generated/api-types/reports.ts, frontend/src/lib-common/local-date.ts, frontend/src/lib-common/local-time.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportByChildTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
=> Add attendance reservation by child report

frontend/src/employee-frontend/components/child-information/DailyServiceTimesSection.tsx
=> Fix daily service times button visibility

frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
=> Do not require financial decision handler for invoiced units

frontend/src/lib-customizations/espoo/employee/assets/i18n/vasu/sv.ts, service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
=> Update preschool curriculum Swedish defaults

frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx, frontend/src/employee-frontend/components/vasu/VasuPage.tsx, frontend/src/employee-frontend/components/vasu/VasuStateTransitionButtons.tsx, frontend/src/employee-frontend/components/vasu/api.ts, frontend/src/employee-frontend/components/vasu/use-vasu.ts, frontend/src/lib-common/generated/api-types/vasu.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt
Hides buttons from users without permission to edit or move between states.
=> Add permitted actions support to curriculum documents

frontend/src/employee-frontend/components/ChildInformation.tsx, frontend/src/employee-frontend/components/PersonProfile.tsx
=> Add person components for director role

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> Enable assistance decisions in Espoo prod

service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
=> Make sure invoices are sent only once using a database lock

service/owasp-suppressions.xml
=> Silence an OWASP warning

frontend/src/employee-frontend/components/child-information/DailyServiceTimesSection.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
=> EVAKA-4642 update daily service times info text

frontend/src/employee-frontend/components/unit/TabCalendar.tsx
=> Allow director to edit unit data filters

frontend/src/employee-frontend/components/vasu/VasuEditPage.tsx, frontend/src/employee-frontend/components/vasu/VasuPage.tsx, frontend/src/employee-frontend/components/vasu/components/DateQuestion.tsx, frontend/src/employee-frontend/components/vasu/components/RadioGroupQuestion.tsx, frontend/src/employee-frontend/components/vasu/components/RadioGroupQuestionOption.tsx, frontend/src/employee-frontend/components/vasu/sections/DynamicSections.tsx, frontend/src/employee-frontend/components/vasu/sections/VasuEvents.tsx, frontend/src/employee-frontend/components/vasu/sections/VasuHeader.tsx, frontend/src/lib-components/molecules/date-picker/DatePickerInput.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/vasu/fi.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/vasu/sv.ts, service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
- Update a Swedish curriculum question
- Make date input info texts match curriculum language
- Make curriculum events section match document language
=> EVAKA swedish curriculum fixes

service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
=> Fix a flaky integration test

frontend/src/employee-frontend/api/invoicing.ts, frontend/src/employee-frontend/components/invoice/InvoicePage.tsx, frontend/src/employee-frontend/components/invoice/InvoiceRowsSection.tsx, frontend/src/employee-frontend/components/invoice/InvoiceRowsSectionRow.tsx, frontend/src/employee-frontend/components/invoices/Actions.tsx, frontend/src/employee-frontend/components/invoices/Invoices.tsx, frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx, frontend/src/employee-frontend/components/invoices/invoices-state.ts, frontend/src/employee-frontend/components/person-profile/PersonInvoiceCorrections.tsx, frontend/src/lib-common/generated/action.d.ts, frontend/src/lib-common/generated/api-types/invoicing.ts, service/codegen/src/main/kotlin/evaka/codegen/actionenum/Definitions.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceCorrectionsController.kt
Also updates some invoice buttons visibility.
=> Fix invoice correction buttons visibility

frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionEditPage.tsx
=> Fix some assistance decision errors not showing on preview

frontend/src/citizen-frontend/messages/MessageEditor.tsx, frontend/src/citizen-frontend/messages/ThreadView.tsx, frontend/src/citizen-frontend/messages/api.ts, frontend/src/e2e-test/pages/citizen/citizen-messages.ts, frontend/src/e2e-test/pages/employee/messages/messages-page.ts, frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts, frontend/src/e2e-test/utils/page.ts, frontend/src/employee-frontend/components/messages/SingleThreadView.tsx, frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx, frontend/src/lib-common/generated/api-types/messaging.ts, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/Audit.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt, service/src/main/resources/db/migration/V271__message_thread_children.sql, service/src/main/resources/migrations.txt
Help the employees identify who a message is regarding by allowing the guardian to indicate who they are messaging about.
Citizen composing a message:
Unit supervisor's inbox:
=> EVAKA-4481 Associate messages with children

evaka-base/Dockerfile, evaka-base/yarn.Dockerfile
=> Bump ubuntu

frontend/src/e2e-test/dev-api/index.ts, frontend/src/e2e-test/specs/5_employee/vasu.spec.ts, frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx, frontend/src/lib-common/generated/api-types/placement.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
=> Filter curriculum templates according to placement unit language

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
Fix some edge cases that occur when an invoice is split into multiple rows from multiple fee decisions and contract surplus days hit the montly maximum.
=> EVAKA-HOTFIX invoices with multiple fee decisions and surplus contract days

frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
Previously the calendar events attendees selection was reset to the default every time the date range was updated. Now the date range changes keep whole groups selected and any individually selected children. If a child changes groups within the unit they are not automatically selected unless their whole new group is selected.
=> Fix calendar event attendees selection resetting unnecessarily

frontend/src/citizen-frontend/calendar/CalendarNotifications.tsx, frontend/src/citizen-frontend/calendar/CalendarPage.tsx, frontend/src/citizen-frontend/calendar/ReservationModal.tsx, frontend/src/e2e-test/pages/citizen/citizen-calendar.ts, frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts, frontend/src/lib-common/finite-date-range.ts
=>  Open reservation modal on corresponding toast click

frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx, frontend/src/lib-common/generated/action.d.ts, service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
* Do not let finance admins add ssns
* Only let service workers and admins to update personal details of people with no ssn
=> Editing personal details for people with no ssn

service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt
=> Add Espoo default finance decision street address

frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
=> Fix calendar event modal crashing sometimes

service/src/main/kotlin/fi/espoo/evaka/vasu/VasuNotificationService.kt
=> Do not try to send curriculum notification to people with no email

frontend/src/employee-frontend/components/common/Filters.tsx, frontend/src/lib-common/generated/api-types/invoicing.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueriesTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueriesTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt, service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
Adds new filter for fee & voucher value decisions.
=> Add finance decision max fee accepted filter

service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/ParentshipQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pis/service/FamilyInitializerService.kt, service/src/main/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyService.kt, service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
=> Add new children to partner's existing fridge family

frontend/src/lib-common/reservations.ts
=> Send only reservable reservations from frontend

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuControllerCitizen.kt
=> Add missing access control check

service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaQueries.kt
Varda does not accept service needs ending before 1.1.2019
Varda does not accept financial decisions ending before 1.9.2019
=> Varda: Do no consider service needs ending before 01-01-2019

frontend/src/employee-frontend/components/reports/VoucherServiceProviders.tsx, service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
- Sort voucher value unit report by area and unit name
- Sort groups on employee mobile attendance UI
=> Add missing sortings

frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/employee-frontend/api/invoicing.ts, frontend/src/employee-frontend/components/common/Filters.tsx, frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionDifferenceIcon.tsx, frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionFilters.tsx, frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisions.tsx, frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionsPage.tsx, frontend/src/employee-frontend/state/invoicing-ui.tsx, frontend/src/lib-common/generated/api-types/invoicing.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/ServiceNeedTestFixtures.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueriesTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt, service/src/main/resources/db/migration/V275__voucher_value_decision_difference.sql, service/src/main/resources/migrations.txt, service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
=> Add voucher value decision difference

service/src/main/kotlin/fi/espoo/evaka/shared/config/JwtConfig.kt
=> Accept 1s jwt leeway

service/src/main/resources/WEB-INF/templates/daycare/voucher/decision_sv.properties
=> Fix invalid properties in Swedish voucher value decision

frontend/src/citizen-frontend/navigation/DesktopNav.tsx, frontend/src/citizen-frontend/navigation/MobileNav.tsx, frontend/src/citizen-frontend/navigation/shared-components.tsx
Sometimes browser starts sending requests to backend and logout request gets cancelled. Fix by using regular link and bypassing React.
=> Fix citizen logout

frontend/src/e2e-test/specs/5_employee/unit-groups.spec.ts, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
Show backup care child multiplier on employee group view
=> Show backup care child multiplier in employee group view

service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/children/ChildrenQueries.kt, service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayQuestionnaireQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
=> Fix unread pedagogical documents count

frontend/src/e2e-test/pages/employee/child-information.ts, frontend/src/employee-frontend/components/child-information/Guardians.tsx
=> Fix a flaky evaka rights e2e test

frontend/src/employee-frontend/api/income-statement.ts, frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx, frontend/src/lib-common/generated/api-types/incomestatement.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
=> Add income statement sort

frontend/src/employee-frontend/components/common/Filters.tsx, frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionDifferenceIcon.tsx, frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionFilters.tsx, frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisions.tsx
Filter and data are now in the same order.
=> Add voucher value decision difference sort

apigw/src/shared/certificates.ts
=> Add new certificate to list

frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/employee-frontend/api/invoicing.ts, frontend/src/employee-frontend/components/common/Filters.tsx, frontend/src/employee-frontend/components/fee-decisions/FeeDecisionDifferenceIcon.tsx, frontend/src/employee-frontend/components/fee-decisions/FeeDecisionFilters.tsx, frontend/src/employee-frontend/components/fee-decisions/FeeDecisions.tsx, frontend/src/employee-frontend/components/fee-decisions/FeeDecisionsPage.tsx, frontend/src/employee-frontend/state/invoicing-ui.tsx, frontend/src/lib-common/generated/api-types/invoicing.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/Helpers.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueriesTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionSearchTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/shared/db/JdbiExtensions.kt, service/src/main/resources/db/migration/V276__fee_decision_difference.sql, service/src/main/resources/migrations.txt, service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
https://github.com/espoon-voltti/evaka/pull/2961 & https://github.com/espoon-voltti/evaka/pull/2989 for fee decisions.
=> Add fee decision difference filter

service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaQueries.kt
=> Make sure financial decisions before 1.9.2019 are not sent to varda

frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
- Radio had key set correctly, but its siblings didn't
- move the key to a common parent instead
=> Fix use of key attribute

frontend/src/employee-frontend/components/unit/TabUnitInformation.tsx, frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx, frontend/src/employee-frontend/components/unit/tab-unit-information/UnitMobileDevices.tsx, frontend/src/employee-frontend/state/unit.tsx
=> Fix some access control issues on the unit information page

frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx
We have plenty of "Cannot read properties of undefined (reading 'y')" in Sentry coming from here
=> Guard against missing data in occupancy day graph

apigw/package.json, apigw/yarn.lock
=> Upgrade to passport-saml 3.2.3

service/src/integrationTest/kotlin/fi/espoo/evaka/shared/PDFServiceTest.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionSendAddress.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/message/MessageProvider.kt, service/src/test/kotlin/fi/espoo/evaka/invoicing/service/PdfServiceTest.kt
=> Use DocumentLang enum everywhere

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
End realtime staff attendances to units that are not open round the clock at six. Previously only attendances that had lasted over 24 hours when the scheduled job was run had their departure times set. This meant that the attendances were practically never ended automatically.
=> EVAKA-4654 end ongoing realtime staff attendances

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> Enable foster parents in Espoo prod

service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
- Fix application decisions having null sent date on documents
- Fix application decisions having wrong localized file names
=> EVAKA-HOTFIX decision date on documents

frontend/src/employee-frontend/api/income-statement.ts, frontend/src/employee-frontend/components/income-statements/IncomeStatementFilters.tsx, frontend/src/employee-frontend/state/invoicing-ui.tsx, frontend/src/lib-common/generated/api-types/incomestatement.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
Adds new filter to income statement search.
=> Add income statement search filter: placement valid date

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueriesTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionSearchTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Moved hard coded post office to `FeatureConfig`.
=> Fix fee decision search external child filter for other cities

frontend/src/e2e-test/dev-api/index.ts, frontend/src/e2e-test/pages/employee/guardian-information.ts, frontend/src/e2e-test/specs/5_employee/guardian-information-page.spec.ts, frontend/src/employee-frontend/components/person-profile/PersonInvoiceCorrections.tsx, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
=> Evaka 4665 filter out non costcenter units

frontend/src/citizen-frontend/applications/editor/contact-info/SecondGuardianSubSection.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Show agreement with other guardian -dialog both in preschool and vaka application
=> Show other guardian agreement question also on vaka application

service/src/main/resources/db/migration/V278__daycare_around_the_clock_not_null.sql, service/src/main/resources/db/migration/V279__voucher_value_vs_co_payment_check.sql, service/src/main/resources/migrations.txt
-Make daycare round_the_clock non nullable, and set all null values to false
-Add check for voucher value decision voucher_value is greater or equal than co_payment
=> Add db constraints

frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/lib-common/generated/api-types/invoicing.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/ServiceNeedTestFixtures.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueriesTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/resources/db/migration/V280__voucher_value_decision_service_need_missing.sql, service/src/main/resources/migrations.txt, service/src/test/kotlin/fi/espoo/evaka/invoicing/service/PdfServiceTest.kt
Same filters as in fee decision search.
=> Add voucher value decision search filters

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Allow role to view reservations & attendances and edit caretakers.
=> Update early childhood secretary actions

frontend/src/employee-frontend/api/income-statement.ts, frontend/src/employee-frontend/components/fee-decisions/FeeDecisionsPage.tsx, frontend/src/employee-frontend/components/invoices/invoices-state.ts, frontend/src/employee-frontend/components/payments/payments-state.ts, frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionsPage.tsx, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
=> Do not send search requests when date filters are inverted

service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancyTest.kt, service/src/main/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancy.kt
=> Use capacity 1.0 for child without placement

frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisions.tsx, frontend/src/lib-common/generated/api-types/invoicing.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueriesTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
=> Add voucher value decision sort

evaka-base/README.md
=> Fix ubuntu version from README

frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
=> Update link in citizen income form

.github/workflows/build.yml
=> Fix Github Actions deprecations

frontend/src/e2e-test/dev-api/index.ts, frontend/src/e2e-test/pages/employee/finance/finance-page.ts, frontend/src/e2e-test/specs/0_citizen/citizen-applications-list.spec.ts, frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts, frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts, frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts, frontend/src/e2e-test/specs/4_finance/fee-decisions.spec.ts, frontend/src/e2e-test/specs/4_finance/value-decisions.spec.ts, frontend/src/e2e-test/specs/5_employee/application-attachments.spec.ts, frontend/src/e2e-test/specs/5_employee/application-details.spec.ts, frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts, frontend/src/e2e-test/specs/5_employee/applications.spec.ts, frontend/src/e2e-test/specs/5_employee/fridge-head-information.spec.ts, frontend/src/e2e-test/specs/5_employee/vasu.spec.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementPlanIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- use max(requested, today) for placement plan draft start dates
- add mock clock to tests that broke
=> Don't suggest past in placement plan draft

service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUnitIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/shared/domain/EvakaClock.kt, service/src/main/resources/db/migration/R__triggers.sql
=> Handle database clock drift in VardaUnitIntegrationTest

frontend/src/citizen-frontend/messages/ThreadListItem.tsx, frontend/src/employee-frontend/components/messages/MessageContext.tsx, frontend/src/employee-frontend/components/messages/ThreadList.tsx, frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx, frontend/src/lib-components/atoms/buttons/AsyncButton.tsx
* Show the delete message button only on received messages (for employees)
* Don't open threads when clicking the delete thread button
=> Message deletion bugfixes

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
=> Add backup care edit for early childhood secretary role

evaka-bom/build.gradle.kts, service/buildSrc/src/main/kotlin/Version.kt
=> Upgrade Spring Boot + Security

.github/workflows/build.yml
=> Service and API-gateway test improvements

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGeneratorIntegrationTest.kt
The children were in the expected order majority of the time, but it wasn't guaranteed.
=> Fix fee decision integration test flakyness

frontend/src/employee-frontend/components/invoice/InvoiceRowsSectionRow.tsx
The amount practically always had an invalid state.
=> Fix invoice correction row validation

frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts, frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts, frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts, frontend/src/e2e-test/utils/page.ts, frontend/src/employee-frontend/components/unit/unit-reservations/ChildReservationsTable.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceExternalPersonModal.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx, frontend/src/employee-mobile-frontend/components/attendances/Reservations.tsx, frontend/src/employee-mobile-frontend/components/attendances/actions/MarkDeparted.tsx, frontend/src/employee-mobile-frontend/components/attendances/child-info/ArrivalAndDeparture.tsx, frontend/src/employee-mobile-frontend/components/staff-attendance/ExternalStaffMemberPage.tsx, frontend/src/employee-mobile-frontend/components/staff-attendance/MarkExternalStaffMemberArrivalPage.tsx, frontend/src/employee-mobile-frontend/components/staff-attendance/StaffMarkArrivedPage.tsx, frontend/src/employee-mobile-frontend/components/staff-attendance/StaffMarkDepartedPage.tsx, frontend/src/employee-mobile-frontend/components/staff-attendance/StaffMemberPage.tsx, frontend/src/employee-mobile-frontend/components/staff/StaffAttendanceEditor.tsx, frontend/src/lib-common/date.ts, frontend/src/lib-common/local-time.spec.ts, frontend/src/lib-common/local-time.ts
=> Better E2E tests for external staff attendances

apigw/package.json, apigw/yarn.lock
=> apigw security upgrades

frontend/src/employee-frontend/api/reports.ts, frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx, frontend/src/lib-common/generated/api-types/reports.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportByChildTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
Also fixes empty columns if child's placement starts in the middle of given period (or is in backup care).
=> Add absences to attendance reservation report

service/src/main/kotlin/fi/espoo/evaka/Audit.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt, service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareController.kt, service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImageController.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/AbsenceController.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
=> Fix accidental confusion between objectId and args

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
=> Change the staff attendance cleanup to end days at 20:00

.github/workflows/build.yml, bin/split-integration-tests.sh, compose/docker-compose.integration.yml, service/Dockerfile
=> Split integration tests and store database logs

service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationUpdateIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/backupcare/BackupCareIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/ChildrenControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerSearchIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/FamilyOverviewTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/ParentshipControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PartnershipsControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedIntegrationTest.kt
=> Use direct route calls instead of HTTP in some integration tests

frontend/src/e2e-test/pages/mobile/staff-page.ts, frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts, frontend/src/employee-mobile-frontend/components/staff-attendance/StaffMarkArrivedPage.tsx, frontend/src/employee-mobile-frontend/components/staff-attendance/StaffMarkDepartedPage.tsx, frontend/src/employee-mobile-frontend/components/staff-attendance/StaffMemberPage.tsx, frontend/src/employee-mobile-frontend/components/staff-attendance/components/StaffAttendanceTypeSelection.tsx, frontend/src/employee-mobile-frontend/utils/staffAttendances.ts, frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
- Updated spec: https://www.figma.com/file/ews5fjKzEmPZO2EvJfr5LL/Trevaka-Employee?node-id=1402%3A11614
=> Mobile staff realtime attendance changes

service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeAlterationIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
Convert some integration tests to use direct route calls instead of HTTP requests.
=> Use direct route calls instead of HTTP requests

frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/MultiSelectQuestion.tsx, frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/sections/CitizenDynamicSections.tsx, frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/vasu-content.ts, frontend/src/e2e-test/pages/employee/vasu/pageSections.ts, frontend/src/e2e-test/specs/5_employee/vasu.spec.ts, frontend/src/employee-frontend/components/vasu/components/MultiSelectQuestion.tsx, frontend/src/employee-frontend/components/vasu/components/RadioGroupQuestion.tsx, frontend/src/employee-frontend/components/vasu/components/RadioGroupQuestionOption.tsx, frontend/src/employee-frontend/components/vasu/sections/DynamicSections.tsx, frontend/src/employee-frontend/components/vasu/templates/VasuTemplateEditor.tsx, frontend/src/employee-frontend/components/vasu/use-vasu.ts, frontend/src/employee-frontend/components/vasu/vasu-content.ts, frontend/src/lib-common/api-types/vasu.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuTemplateIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
=> Add dateRange and intervention option support for vasu MultiSelectQuestion

frontend/src/lib-common/form-validation.ts, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
=> Fix integer validation error text

service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/application/PendingDecisionEmailServiceIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageReceiversIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentNotificationServiceIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/MissingReservationsRemindersTest.kt, service/src/main/kotlin/fi/espoo/evaka/emailclient/MockEmailClient.kt
=> Fix MockEmailClient thread safety problems

frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
Same functionality can be used for other roles.
=> Update personal mobile texts

service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt, service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
Overnight attendances are now split (in proportion) to both days instead of the whole attendance being reported on the first day.
=> Split overnight staff attendances in reporting

service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
first() throws an exception when the collection is empty, which doesn't make any sense if the function is supposed to return a nullable result
=> Use firstOrNull when a nullable result is wanted

frontend/src/citizen-frontend/calendar/CalendarPage.tsx, frontend/src/citizen-frontend/calendar/NonReservableDaysWarningModal.tsx, frontend/src/citizen-frontend/calendar/ReservationModal.tsx, frontend/src/e2e-test/pages/citizen/citizen-calendar.ts, frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts, frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts, frontend/src/lib-common/reservations.ts, frontend/src/lib-components/molecules/modals/BaseModal.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
=> Show a warning to citizen if some days were unreservable

service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlDecision.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Some actions were skipped:
- anything only used by citizens
- anything only used by mobile devices
- actions which are meant to be allowed to a specific employee only
=> Make admin permissions explicit

evaka-bom/build.gradle.kts, service/README.md, service/buildSrc/build.gradle.kts, service/buildSrc/src/main/kotlin/Version.kt, service/custom-ktlint-rules/build.gradle, service/src/integrationTest/kotlin/fi/espoo/evaka/koski/MockKoskiServer.kt, service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCare.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt
=> Backend upgrades 2022/11

.github/workflows/build.yml
=> Fix build for dependabot PRs

frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx, frontend/src/employee-frontend/components/application-page/ApplicationStatusSection.tsx, frontend/src/lib-common/generated/api-types/decision.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/PDFServiceTest.kt, service/src/main/kotlin/fi/espoo/evaka/decision/Decision.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt
=> Show the name of the user who approved or rejected an application

frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts, frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
- Remove day navigation
- Close the modal on save
=> Tweak the UX of the staff attendance details modal

frontend/src/citizen-frontend/applications/editor/service-need/AssistanceNeedSubSection.tsx, frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx, frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx, frontend/src/lib-customizations/citizen.tsx, frontend/src/lib-customizations/espoo/citizen.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts
=> Preschool application customizations

frontend/src/employee-frontend/types/family-overview.ts, frontend/src/lib-common/generated/api-types/pis.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/FamilyControllerTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/FamilyContact.kt, service/src/main/kotlin/fi/espoo/evaka/pis/controllers/FamilyController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
=> Include foster parents in family contacts

frontend/src/e2e-test/pages/mobile/child-attendance-page.ts, frontend/src/e2e-test/pages/mobile/child-page.ts, frontend/src/e2e-test/specs/6_mobile/child-attendances.spec.ts, frontend/src/employee-mobile-frontend/api/attendances.ts, frontend/src/employee-mobile-frontend/components/attendances/actions/MarkDeparted.tsx, frontend/src/employee-mobile-frontend/components/attendances/actions/MarkPresent.tsx, frontend/src/employee-mobile-frontend/components/attendances/child-info/ArrivalAndDeparture.tsx, frontend/src/employee-mobile-frontend/components/attendances/child-info/AttendanceChildPage.tsx, frontend/src/employee-mobile-frontend/components/attendances/child-info/child-state-pages/AttendanceChildDeparted.tsx, frontend/src/employee-mobile-frontend/components/attendances/child-info/child-state-pages/AttendanceChildPresent.tsx, frontend/src/employee-mobile-frontend/components/attendances/components.tsx, frontend/src/lib-common/generated/api-types/attendance.ts, frontend/src/lib-components/atoms/buttons/AsyncButton.tsx, frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts, frontend/src/lib-icons/fontawesome.d.ts, frontend/src/lib-icons/free-icons.ts, frontend/src/lib-icons/pro-icons.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- Child can have multiple attendances per day: come, leave for a while and then come back before actual departure for the day. Also show these times on mobile child page.
- UI fixes to better match the UX spec
=> Multiple child attendances

evaka-bom/build.gradle.kts
=> Upgrade postgresql jdbc driver

frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx, frontend/src/citizen-frontend/applications/editor/ApplicationFormClub.tsx, frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx, frontend/src/citizen-frontend/applications/editor/ApplicationFormPreschool.tsx, frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx, frontend/src/citizen-frontend/applications/editor/service-need/ServiceNeedSection.tsx, frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx, frontend/src/citizen-frontend/applications/editor/validations.ts, frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx, frontend/src/lib-common/api-types/application/ApplicationDetails.ts, frontend/src/lib-common/api-types/application/ApplicationFormData.ts, frontend/src/lib-common/generated/api-types/application.ts, frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/test/TestData.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationForm.kt, service/src/main/kotlin/fi/espoo/evaka/application/persistence/daycare/DaycareFormV0.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
https://github.com/espoon-voltti/evaka/pull/871 for preschool application.
Espoo:
Tampere:
=> Add service need option selector for preschool application

evaka-bom/build.gradle.kts, service/build.gradle.kts, service/src/main/kotlin/fi/espoo/evaka/shared/Tracing.kt, service/src/main/kotlin/fi/espoo/evaka/shared/auth/JwtToAuthenticatedUser.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/HttpFilterConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/TracingConfig.kt
=> Add user ID hash to OpenTracing span

service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
=> Do what varda suggested to fix path

frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx
If a term has already ended leave it out of citizen club applications.
=> Do not show already ended club terms on application

frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
=> Check that staff arrival and departure are not the same time

keycloak/Dockerfile
=> Update KeyCloak image packages

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
While at it, use direct route calls in the tests.
=> Fix flaky integration tests

frontend/src/employee-frontend/components/Reports.tsx
=> Fix report path

frontend/src/citizen-frontend/children/sections/consents/ChildConsentsSection.tsx
=> Hide child consents save button if already saved

service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaTokenProvider.kt
=> Add debug logging to varda token fetch

service/src/main/kotlin/fi/espoo/evaka/varda/VardaResetService.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
=> Log full error in catch

frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx, frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx, frontend/src/lib-common/api-types/application/ApplicationFormData.ts, frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Some small improvements to preschool application.
=> Preschool application improvements

evaka-bom/build.gradle.kts
=> Upgrade netty to fix CVE

service/src/main/kotlin/fi/espoo/evaka/shared/Tracing.kt
`.use()` on the scope returned by activateSpan only closes the scope but doesn't finish the span.
=> Finish active span correctly

frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts, frontend/src/employee-frontend/components/unit/unit-reservations/ChildReservationsTable.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/attendance-elements.tsx, service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
=> Show all child daily attendances and reservations in the desktop UI

frontend/src/citizen-frontend/applications/editor/AdditionalDetailsSection.tsx, frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx, frontend/src/citizen-frontend/applications/editor/validations.ts, frontend/src/e2e-test/utils/application-forms.ts, frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx
- Enable the `connectedDaycarePreferredStartDate` feature flag and update validation code to work correctly
- Copy updates
=> EVAKA-4699 preschool application copy changes

frontend/src/employee-frontend/components/unit/TabCalendar.tsx
=> Allow absence calendar without `READ_CHILD_ATTENDANCES` permission

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
=> Spread message notifications execution time

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Show the attendance calendar on unit page to special education teachers.
=> Give special education teachers rights to unit attendances

apigw/src/shared/auth/dev-ad-strategy.ts, apigw/src/shared/auth/dev-sfi-strategy.ts, apigw/src/shared/routes/auth/saml/index.ts, apigw/src/shared/routes/auth/saml/types.ts
- use same code path with all strategies
=> Fix invalid "this" value in logout call

service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt
=> Fix assistance decision pdf name

frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
=> EVAKA-4699 Remove unnecessary part of copy

compose/docker-compose.yml
- this is the minimum version used in real Espoo environments
- v7 is latest and upgrading to it should be planned
=> Upgrade to redis v5 in local development

frontend/src/employee-frontend/components/messages/MessageContext.tsx, frontend/src/employee-frontend/components/messages/MessagesPage.tsx
=> Stop unconditionally adding messaging params to URL

service/src/main/resources/db/migration/V291__application_other_guardian_cascade.sql, service/src/main/resources/migrations.txt
Fixes constraint error on application delete
=> Cascade deletes to application_other_guardian

apigw/src/enduser/publicRoutes.ts, apigw/src/enduser/routes.ts, frontend/src/citizen-frontend/applications/api.ts, frontend/src/citizen-frontend/attachments.ts, service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionController.kt
- /citizen <- accessible by enduser-gw / AuthenticatedUser.Citizen
- /public <- accessible without authentication
=> Use consistent prefixes in enduser-gw routes

service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/PureJdbiTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunnerTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/auth/AclIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobRunnerTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AccessControlTest.kt, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt, service/src/main/kotlin/fi/espoo/evaka/shared/auth/Acl.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/ActuatorConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/ScheduledJobConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/SecurityConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/SpringMvcConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt, service/src/main/kotlin/fi/espoo/evaka/shared/db/DevDataInitializer.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobRunner.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
=> OpenTracing spans for scheduled jobs and database transactions

frontend/src/citizen-frontend/messages/MessageCharacteristics.tsx, frontend/src/citizen-frontend/messages/MessageComponents.tsx, frontend/src/citizen-frontend/messages/MessagesPage.tsx, frontend/src/citizen-frontend/messages/ThreadList.tsx, frontend/src/citizen-frontend/messages/ThreadListItem.tsx, frontend/src/citizen-frontend/messages/ThreadView.tsx, frontend/src/lib-components/atoms/ScreenReaderOnly.tsx, frontend/src/lib-components/atoms/buttons/Button.tsx, frontend/src/lib-components/molecules/ScreenReaderButton.tsx, frontend/src/lib-components/molecules/ThreadListItem.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- Allow screen reader to read titles for items such as subject, recipients, etc.
- Enhance focus control
- Allow navigation in thread's messages view
=> Citizen messaging accessibility enhancements

frontend/src/citizen-frontend/messages/MessageEditor.tsx, frontend/src/lib-common/generated/api-types/messaging.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
=> Ignore children with only secondary recipients

keycloak/Dockerfile, keycloak/evaka-logging/pom.xml, keycloak/evaka-review-profile/pom.xml
=> KeyCloak 20.0.2

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt
=> Guardians in application_other_guardian are not inactive

service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedQueries.kt
=> Use service need option display order if set

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt
=> Do not clean up guardians who are on guardian blocklist

evaka-base/dd-jmxfetch/conf.yaml, service/build.gradle.kts, service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/application/PendingDecisionEmailServiceIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunnerTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobRunnerTest.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/AsyncJobConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobRunner.kt
=> Redesign async job runner execution model, expose metrics

frontend/src/employee-frontend/components/reports/Raw.tsx, frontend/src/lib-common/generated/api-types/reports.ts, service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
=> Add postal code to raw report

frontend/src/employee-frontend/api/child/placements.ts, frontend/src/employee-frontend/components/child-information/PedagogicalDocuments.tsx, frontend/src/employee-frontend/components/child-information/Placements.tsx, frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx, frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx, frontend/src/employee-frontend/components/child-information/placements/ServiceNeeds.tsx, frontend/src/employee-frontend/components/child-information/placements/service-needs/MissingServiceNeedRow.tsx, frontend/src/employee-frontend/components/child-information/placements/service-needs/ServiceNeedEditorRow.tsx, frontend/src/employee-frontend/components/child-information/placements/service-needs/ServiceNeedReadRow.tsx, frontend/src/employee-frontend/components/common/Toolbar.tsx, frontend/src/employee-frontend/components/person-profile/FosterChildren.tsx, frontend/src/employee-frontend/components/person-profile/PersonFridgePartner.tsx, frontend/src/employee-frontend/state/child.tsx, frontend/src/lib-common/generated/api-types/placement.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
Replace hard coded roles from frontend to permitted actions returned from backend.
=> Add permitted actions support for service need

apigw/src/shared/certificates.ts
=> Add missing certificate configuration

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx, frontend/src/lib-common/generated/api-types/reservations.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenControllerTest.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
If child has contract days in service need, planned absence should be visible for guardian.
=> Add contract day absence type for citizen

service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedVoucherCoefficientIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/vouchercoefficient/AssistanceNeedVoucherCoefficientController.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/vouchercoefficient/AssistanceNeedVoucherCoefficientQueries.kt
=> Generate finance decisions when assistance need voucher coefficient changes

frontend/src/citizen-frontend/applications/ApplicationCreation.tsx, frontend/src/citizen-frontend/applications/Applications.tsx, frontend/src/citizen-frontend/applications/ChildApplicationsBlock.tsx, frontend/src/citizen-frontend/applications/api.ts, frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx, frontend/src/citizen-frontend/applications/editor/ApplicationFormClub.tsx, frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx, frontend/src/citizen-frontend/applications/editor/ApplicationFormPreschool.tsx, frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx, frontend/src/citizen-frontend/applications/queries.ts, frontend/src/citizen-frontend/applications/read-view/ApplicationReadView.tsx, frontend/src/citizen-frontend/query.ts, frontend/src/lib-common/query.ts
=> Use react-query for citizen applications

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts
This feature needs some polish before going live.
=> Add citizen contract day absence feature flag

frontend/src/citizen-frontend/applications/editor/verification/ServiceNeedSection.tsx, frontend/src/e2e-test/pages/employee/applications/application-edit-view.ts, frontend/src/e2e-test/pages/employee/applications/create-application-modal.ts, frontend/src/e2e-test/specs/5_employee/feature-flag-preschool-application-connected-daycare-preferred-start-date.spec.ts, frontend/src/e2e-test/specs/5_employee/feature-flag-preschool-application-service-need-option.spec.ts, frontend/src/e2e-test/specs/5_employee/paper-application.spec.ts, frontend/src/employee-frontend/components/ApplicationPage.tsx, frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx, frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx, frontend/src/employee-frontend/components/child-information/CreateApplicationModal.tsx
Also adds preparatory feature flag usage where it was still missing.
=> Add feature flags support for preschool paper application

frontend/src/employee-frontend/components/decision-draft/DecisionDraft.tsx
=> Add spacing to decision draft page

service/owasp-suppressions.xml
See: https://github.com/jeremylong/DependencyCheck/issues/5213
=> Suppress CVE due to misidentification

frontend/src/employee-frontend/components/common/Filters.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationSummaryIntegrationTests.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationForm.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Also hides preparatory filters if preparatory is disabled with feature flag.
=> Fix preschool club application filter

frontend/src/citizen-frontend/children/sections/placement-termination/PlacementTerminationSection.tsx, frontend/src/citizen-frontend/children/sections/placement-termination/TerminatedPlacements.tsx, frontend/src/citizen-frontend/children/sections/placement-termination/utils.spec.ts, frontend/src/citizen-frontend/children/sections/placement-termination/utils.ts, frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementTermination.kt
=> Show termination of connected daycare if preschool/preparatory continues

service/buildSrc/src/main/kotlin/Version.kt, service/owasp-suppressions.xml
=> Bump org.owasp.dependencycheck to 7.4.4, add CVE suppressions

frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponseList.tsx, frontend/src/citizen-frontend/decisions/decisions-page/Decisions.tsx
E.g. show preschool decision before preschool daycare because former must be accepted before latter.
=> Fix citizen decisions order

frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
=> Add start/end date validation to placement editing

frontend/src/citizen-frontend/applications/editor/verification/ServiceNeedConnectedDaycare.tsx, frontend/src/citizen-frontend/applications/editor/verification/ServiceNeedSection.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Preschool application verification page didn't support feature flags.
=> Add preschool feature flags support for application verification

frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/pages/employee/applications/application-list-view.ts, frontend/src/e2e-test/pages/employee/person-search.ts, frontend/src/e2e-test/specs/5_employee/application-search.spec.ts, frontend/src/e2e-test/specs/5_employee/search-person.spec.ts, service/src/main/resources/db/migration/R__acl_views.sql
=> VEO should see people from assistance need applications only

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
=> Text fixes

frontend/src/citizen-frontend/map/MapView.tsx, frontend/src/citizen-frontend/map/SearchSection.tsx, frontend/src/e2e-test/pages/citizen/citizen-map.ts, frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx, frontend/src/lib-customizations/espoo/mapConfig.tsx, frontend/src/lib-customizations/types.d.ts
=> Customizable map filters

frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts, frontend/src/employee-frontend/components/messages/MessageContext.tsx
=> Allow opening archived messages

frontend/src/e2e-test/specs/5_employee/vasu.spec.ts, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
=> Allow closing of vasu by staff etc

service/src/main/kotlin/fi/espoo/evaka/shared/utils/FuelExtensions.kt
=> If varda returns error, log full response

frontend/src/citizen-frontend/query.ts, frontend/src/employee-mobile-frontend/query.ts
Disable react-query's automatic connection management that keeps requests pending if there's no network connection.
=> Fail requests if network is disconnected

frontend/src/e2e-test/specs/5_employee/vasu.spec.ts
=> Refactor e2e test

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
=> HOTFIX: Fix some messaging queries to handle sent_at = NULL

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt
=> Allow foster parents to see foster child's image

evaka-base/dd-jmxfetch/conf.yaml
=> Fix copy-paste error in counter name

frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
=> Open external link in application editor in a new window

service/src/main/kotlin/fi/espoo/evaka/shared/utils/FuelExtensions.kt
=> Remove problematic logging

frontend/src/e2e-test/pages/mobile/staff-page.ts, frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts, frontend/src/e2e-test/utils/page.ts, frontend/src/employee-mobile-frontend/staff-attendance/ExternalStaffMemberPage.tsx, frontend/src/employee-mobile-frontend/staff-attendance/MarkExternalStaffMemberArrivalPage.tsx, frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx, frontend/src/employee-mobile-frontend/staff-attendance/api.ts, frontend/src/lib-common/generated/api-types/attendance.ts, frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts, service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/domain/OperationalDays.kt
=>  Disallow marking arrival on non-operational days

frontend/src/lib-components/Notifications.tsx
If an event is captured when there's no internet connection, Sentry seems to discard that and subsequent events for a minute or so.
Add timestamp and duration of network outage as extra context to the events.
=> Only send network connection restored events to Sentry

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageAccountQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
=> Only spread MUNICIPAL message email notifications

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
If fridge partners "switch place" in the family, then their partnership periods must be merged to avoid including too many children in finance decisions.
=> Fix family composition corner case

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
=> Allow html elements in capacity factor info text

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx, frontend/src/citizen-frontend/calendar/CalendarPage.tsx, frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/dev-api/types.ts, frontend/src/e2e-test/pages/citizen/citizen-calendar.ts, frontend/src/e2e-test/specs/0_citizen/feature-flag-citizen-contract-day-absence.spec.ts, frontend/src/e2e-test/specs/5_employee/backup-care.spec.ts, frontend/src/e2e-test/specs/6_mobile/child-attendances.spec.ts, frontend/src/lib-components/atoms/Chip.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
Contract day absences should follow same rules as reservations, e.g. next week absence should be added before Tuesday in Tampere.
=> Fix contract day absence visibility

frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionPage.tsx
=> Don't navigate to edit if it's going to navigate back

frontend/src/citizen-frontend/calendar/DayView.tsx, frontend/src/citizen-frontend/calendar/calendar-elements.tsx, frontend/src/e2e-test/pages/citizen/citizen-calendar.ts, frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
=> Do not require setting attendance for weekend if sibling is in 24/7 daycare

service/src/main/kotlin/fi/espoo/evaka/reports/PlacementCountReportController.kt
Fixes the issue of report query not using inclusive date ranges in placement data acquisition.
=> Added missing parameter to date range formation

frontend/src/citizen-frontend/applications/editor/verification/UnitPreferenceSection.tsx, frontend/src/citizen-frontend/applications/read-view/ApplicationReadViewContents.tsx, frontend/src/e2e-test/pages/citizen/citizen-applications.ts, frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
=> Hide some application info from other guardian

service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
Alternatively we could make this API private since it's only used by AuthenticatedUser.Citizen, but this seems a bit simpler and consistent since other APIs in LocationController are public
=> Make "public" API actually public

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
=> Fix application text

frontend/src/citizen-frontend/LoginPage.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
=> New info text in citizen login page

service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
> Companion object of enum class 'FeeDecisionDifference' is uninitialized here. This warning will become an error in future releases. See https://youtrack.jetbrains.com/issue/KT-49110 for details.
=> Fix a kotlin compiler warning

service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
This API is actually used in employee-frontend, so we can't make it fully public or remove the `AuthenticatedUser` parameter
=> Revert "Make "public" API actually public"

frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx, frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx, frontend/src/lib-components/atoms/PlacementCircle.tsx, frontend/src/lib-components/atoms/Tooltip.tsx
Also adds service need start/end dates to tooltip.
=> Fix future service need visibility in group tables

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx, frontend/src/citizen-frontend/calendar/DayView.tsx, frontend/src/citizen-frontend/calendar/ReservationModal.tsx, frontend/src/citizen-frontend/calendar/RoundChildImages.tsx, frontend/src/citizen-frontend/calendar/holiday-modal/FixedPeriodSelectionModal.tsx, frontend/src/citizen-frontend/messages/MessageEditor.tsx, frontend/src/citizen-frontend/messages/ThreadView.tsx, frontend/src/citizen-frontend/navigation/DesktopNav.tsx, frontend/src/citizen-frontend/navigation/MobileNav.tsx, frontend/src/lib-common/names.ts
=> Do not show child preferred name to citizen

frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
=> Application text improvements

compose/docker-compose.yml
=> Use Redis v7 in compose

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
=> Allow VEO to delete absences

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
=> Requested text fix

evaka-bom/build.gradle.kts, service/owasp-suppressions.xml
=> Fix CVE-2022-45688

frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
=> Fix grammar

service/src/integrationTest/kotlin/fi/espoo/evaka/ServiceNeedTestFixtures.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
=> Add an invoicing test case, make another one more realistic

docs/diagrams/src/evaka-correcting-invoicing.puml, docs/diagrams/src/evaka-monthly-invoicing.puml
See result in https://github.com/espoon-voltti/evaka/wiki/Prosessikaaviot
=> Fix invoicing diagrams

frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts, frontend/src/employee-frontend/components/ApplicationPage.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageAccountQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt, service/src/main/resources/db/migration/V298__message_thread_application_id.sql, service/src/main/resources/migrations.txt
Replies to service worker messages create notes with the contents of the reply in the application
=> EVAKA-4694 Citizen can reply to service worker messages

service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerator.kt
=> Make sure that only one FeeThresolds is found for finance decisions

frontend/src/lib-common/generated/api-types/invoicing.ts, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt, service/src/main/resources/db/migration/V299__voucher_value_decision_thresholds_difference.sql, service/src/main/resources/migrations.txt
Fixes voucher value decision generator on thresholds changes.
=> Add voucher value decision thresholds difference

frontend/src/e2e-test/pages/mobile/child-attendance-page.ts, frontend/src/e2e-test/specs/6_mobile/child-attendances.spec.ts, frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx
=> Use the latest arrival when calculating departure warning

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailService.kt, service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt, service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt, service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailClient.kt, service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt, service/src/main/kotlin/fi/espoo/evaka/emailclient/MockEmailClient.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentNotificationService.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/MissingReservationsReminders.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuNotificationService.kt
=> Add message type to e-mail notification, refactor all e-mail templates to new style

frontend/src/employee-frontend/components/reports/Raw.tsx, frontend/src/lib-common/generated/api-types/reports.ts, service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
=> Add realized capacity column to raw report

service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt
=> Use eVaka as the sender name in Suomi.fi messages

evaka-base/Dockerfile, keycloak/Dockerfile
=> Update Docker image packages

frontend/src/e2e-test/pages/employee/messages/messages-page.ts, frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts, frontend/src/lib-components/employee/messages/MessageEditor.tsx
The simplified message editor removes
- The message type radio group
- The urgent checkbox
- Attachments
=> EVAKA-4694 Show a simplified message editor to service workers

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
=> Abcenses affect attendance reservations report

service/src/main/kotlin/fi/espoo/evaka/pis/service/FamilyInitializerService.kt
=> Avoid adding person as their own partner from application

frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx, frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts
=> Feature flag updates

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
=> Fix retroactive fee decision generation when head of family has changed

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt, service/src/main/resources/db/migration/V302__drop_pointless_index.sql, service/src/main/resources/db/migration/V303__message_thread_application_index.sql, service/src/main/resources/migrations.txt
=> Minor messaging improvements

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportByChildTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
=> Use daily service times as default for attendance reservation

service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTestHelpers.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/koski/MockKoskiServer.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiClient.kt
There's no need to spam our alerts channel with these failures, because:
- an error row will be listed in the Koski UI
- we'll try again next day
=> Don't fail the Koski job on status 4xx

service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfGeneration.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/pdfgen/PdfGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/PDFConfig.kt, service/src/main/kotlin/fi/espoo/voltti/pdfgen/PDFService.kt, service/src/test/kotlin/fi/espoo/evaka/invoicing/service/PdfGenerationTest.kt
- merge two PDFServices into one PdfGenerator. The API is a strange mix of two abstractions, but this was already the case
- add tracing to PDF generation, so we can see the durations of various steps
=> PDF generation improvements

frontend/src/e2e-test/pages/employee/finance/finance-page.ts, frontend/src/employee-frontend/components/invoices/Invoices.tsx, frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueriesTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/reports/InvoiceReport.kt, service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt, service/src/main/kotlin/fi/espoo/evaka/shared/domain/HelsinkiDateTime.kt, service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt, service/src/main/resources/db/migration/V304__invoice_indexing.sql, service/src/main/resources/migrations.txt
=> Improve invoice report query and add database indexes

frontend/Dockerfile
=> Updated ca-certificates for sentry

apigw/package.json, apigw/yarn.lock, service/Dockerfile
=> Upgrade Datadog agent/trace

service/src/main/resources/db/migration/V306__finance_decision_sending_indexes.sql, service/src/main/resources/migrations.txt
=> Add specific indexes for finance decision sending statuses

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/main/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClient.kt, service/src/test/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClientTest.kt
- Switch to use generic term
- Use generic term, Community system is no more
=> FIX remove community strings

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> Enable service worker messaging in prod

service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt, service/src/test/kotlin/fi/espoo/evaka/koski/KoskiTest.kt
=> Add väliaikaisesti keskeytynyt to Koski for sick leaves of over 7 days

frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
- Resolution 30min -> 15min
- Scroll the report to 6AM
=> Attendance reservation report improvements

frontend/src/lib-components/atoms/buttons/ReturnButton.tsx
=> Hide a nonfunctioning return button instead of disabling it

frontend/src/employee-frontend/components/Units.tsx
=> Keep names in alphabetical order when sorting units by type or area

keycloak/Dockerfile, keycloak/evaka-logging/pom.xml, keycloak/evaka-review-profile/pom.xml
=> KeyCloak 20.0.5

frontend/src/citizen-frontend/calendar/DayView.tsx, frontend/src/citizen-frontend/calendar/RoundChildImages.tsx, frontend/src/citizen-frontend/calendar/calendar-elements.tsx
=> Limit the number of rendered child images in citizen calendar

frontend/src/employee-frontend/components/unit/tab-groups/missing-group-placements/GroupPlacementModal.tsx
=> Make child name appear below the info label

frontend/src/e2e-test/pages/mobile/child-attendance-page.ts, frontend/src/e2e-test/specs/6_mobile/child-attendances.spec.ts, frontend/src/employee-mobile-frontend/child-attendance/DailyNote.tsx, frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsent.tsx, frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx, frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx, frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
=> Show all active group notes where daily notes are displayed

frontend/src/citizen-frontend/calendar/DayView.tsx, frontend/src/citizen-frontend/calendar/TimeRangeInput.tsx
=> Layout fixes for citizen's reservation popup

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Currency.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerator.kt
=> Round value decision's voucher value to full euros

frontend/src/citizen-frontend/income-statements/ChildIncomeStatementEditor.tsx, frontend/src/citizen-frontend/income-statements/ChildIncomeStatementView.tsx, frontend/src/citizen-frontend/income-statements/ChildrenIncomeStatements.tsx, frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx, frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx, frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx, frontend/src/citizen-frontend/income-statements/api.ts, frontend/src/citizen-frontend/income-statements/queries.ts, frontend/src/citizen-frontend/map/MapView.tsx, frontend/src/citizen-frontend/map/SearchInput.tsx, frontend/src/citizen-frontend/map/UnitDetailsPanel.tsx, frontend/src/citizen-frontend/map/api.ts, frontend/src/citizen-frontend/map/queries.ts, frontend/src/citizen-frontend/query.ts, frontend/src/lib-common/query.ts
=> Convert some code in citizen-frontend to use react-query 

service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt
=> Try to log the Suomi.fi SOAP message when a fault is encountered

service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
=> Fix duplicate children on child daily attendance report

.github/workflows/analyze.yml, .github/workflows/build.yml
=> Separate analyze and split tests more

service/src/main/resources/db/migration/V308__remove_old_tables.sql, service/src/main/resources/migrations.txt
=> Remove old database tables

.github/workflows/build.yml, bin/test-timings.sh, bin/timings.sh
=> E2E test timing split

service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiQueries.kt, service/src/main/resources/db/migration/V310__koski_input_data_version.sql, service/src/main/resources/migrations.txt
=> Add Koski input data version for cache busting

.github/workflows/build.yml
=> Deploy using invoke_workflow

service/src/main/kotlin/fi/espoo/evaka/pis/service/MergeService.kt
=> Log MergeService's SQL error

frontend/src/e2e-test/specs/5_employee/backup-care.spec.ts
=> Fix an e2e test by using mock clock

frontend/src/citizen-frontend/children/sections/vasu-and-leops/api.ts, frontend/src/employee-frontend/components/vasu/api.ts, frontend/src/lib-common/generated/api-types/vasu.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
=> Add vasu copy to duplicates

service/src/main/kotlin/fi/espoo/evaka/varda/VardaQueries.kt
Previous version of the fixed query did not finish in 15 minutes on production, the fixed version takes around a second.
=> Greatly improve query performance

keycloak/Dockerfile, keycloak/evaka-logging/pom.xml, keycloak/evaka-review-profile/pom.xml
This reverts commit 1efe57641679b23d91cfa7f78423e92fd4a2d80f.
=> Revert "Update KeyCloak to 21.0.1"

frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx
=> Fix timestamp formatting

keycloak/.gitignore, keycloak/Dockerfile, keycloak/evaka-logging/pom.xml, keycloak/evaka-review-profile/pom.xml, keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java, keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff, keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java, keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java.diff
=> Fix KeyCloak

frontend/src/employee-mobile-frontend/App.tsx, frontend/src/employee-mobile-frontend/auth/state.tsx, frontend/src/employee-mobile-frontend/common/service-worker.tsx, frontend/src/employee-mobile-frontend/service-worker.js, service/codegen/src/main/kotlin/evaka/codegen/apitypes/Config.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessagePushNotifications.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt, service/src/main/kotlin/fi/espoo/evaka/webpush/WebPush.kt, service/src/main/kotlin/fi/espoo/evaka/webpush/WebPushController.kt, service/src/main/kotlin/fi/espoo/evaka/webpush/WebPushCrypto.kt, service/src/main/kotlin/fi/espoo/evaka/webpush/WebPushQueries.kt, service/src/main/resources/db/migration/V313__message_push_notifications.sql, service/src/main/resources/migrations.txt, service/src/test/kotlin/fi/espoo/evaka/webpush/VapidKeyGenerator.kt, service/src/test/kotlin/fi/espoo/evaka/webpush/WebPushCryptoTest.kt
=>  Mobile web push notification subscription PoC - part 2

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
Related https://github.com/espoon-voltti/evaka/pull/3200 & https://github.com/espoon-voltti/evaka/pull/3430
=> Add future placement delete for unit supervisor

frontend/src/citizen-frontend/applications/ChildApplicationsBlock.tsx, frontend/src/lib-common/generated/api-types/application.ts, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
=> Hide new application link from duplicates

.github/workflows/build.yml
=> Push to public ECR and concurrent CI jobs

frontend/src/employee-mobile-frontend/service-worker.js, service/src/main/kotlin/fi/espoo/evaka/messaging/MessagePushNotifications.kt, service/src/main/kotlin/fi/espoo/evaka/webpush/WebPush.kt, service/src/main/kotlin/fi/espoo/evaka/webpush/WebPushCrypto.kt, service/src/main/kotlin/fi/espoo/evaka/webpush/WebPushQueries.kt, service/src/test/kotlin/fi/espoo/evaka/webpush/WebPushCryptoTest.kt
=> Mobile web push notification PoC - part 3

service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobRunner.kt
=> Improve scheduled jobs configuration

apigw/src/internal/app.ts, apigw/src/shared/config.ts, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/espoobi/Csv.kt, service/src/main/kotlin/fi/espoo/evaka/espoobi/EspooBiModels.kt, service/src/main/kotlin/fi/espoo/evaka/espoobi/EspooBiPoc.kt, service/src/main/resources/application-local.yaml
=> Espoo BI PoC

service/owasp-suppressions.xml
=> Suppress CVE-2023-20861 until spring boot fixes it

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
=> Prevent duplicate financial decisions

frontend/src/citizen-frontend/personal-details/PersonalDetails.tsx, frontend/src/lib-common/form/fields.ts, frontend/src/lib-common/form/form.ts, frontend/src/lib-common/form/hooks.ts, frontend/src/lib-common/form/memoize.ts, frontend/src/lib-common/form/types.ts, frontend/src/lib-common/form/validators.ts, frontend/src/lib-components/atoms/dropdowns/Select.tsx, frontend/src/lib-components/atoms/form/Checkbox.tsx, frontend/src/lib-components/atoms/form/InputField.tsx
=> Form validation PoC

service/src/main/kotlin/fi/espoo/evaka/reservations/MissingReservationsReminders.kt, service/src/main/resources/db/migration/V314__attendance_reservation_index.sql, service/src/main/resources/migrations.txt
=> Improve missing reservations query performance

service/owasp-suppressions.xml
=> Suppress CVE-2023-20860

service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/espoobi/Csv.kt, service/src/main/kotlin/fi/espoo/evaka/espoobi/EspooBiPoc.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/SpringMvcConfig.kt
=> Fix BI PoC by using annotation-free router

.github/workflows/build.yml
=> Revert on pull_request

frontend/webpack.config.js, service/src/main/kotlin/fi/espoo/evaka/messaging/MessagePushNotifications.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt, service/src/main/kotlin/fi/espoo/evaka/webpush/WebPush.kt, service/src/main/resources/db/migration/V315__drop_push_sent_at.sql, service/src/main/resources/migrations.txt
=> Mobile push notifications PoC - part 4

frontend/src/citizen-frontend/calendar/DayView.tsx
=> Avoid rendering raw LocalTimes

frontend/src/e2e-test/pages/employee/guardian-information.ts, frontend/src/e2e-test/specs/5_employee/income.spec.ts, frontend/src/employee-frontend/components/person-profile/income/IncomeList.tsx, frontend/src/employee-frontend/components/person-profile/income/IncomeNotifications.tsx
=> Hide unnecessary income notification title

service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
=> In case varda update fails, do full reset to avoid constant retries

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueriesTest.kt
=> Add tests for `findFeeDecisionsForHeadOfFamily`

service/owasp-suppressions.xml, service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
=> Fix email template

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
=> If employee arrives late, do not generate presence

frontend/src/e2e-test/pages/employee/reports.ts, frontend/src/e2e-test/specs/5_employee/placement-sketching-report.spec.ts, frontend/src/e2e-test/utils/page.ts, frontend/src/employee-frontend/api/reports.ts, frontend/src/employee-frontend/components/reports/PlacementSketching.tsx, frontend/src/lib-common/generated/api-types/reports.ts, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/main/kotlin/fi/espoo/evaka/reports/PlacementSketchingReport.kt
Add application status column & filter to placement sketching report.
=> Placement sketching report application status

frontend/src/e2e-test/specs/5_employee/child-information.spec.ts, frontend/src/employee-frontend/api/person.ts, frontend/src/employee-frontend/components/child-information/Guardians.tsx
=> Allow unit supervisor to see child guardians

service/src/main/kotlin/fi/espoo/evaka/webpush/WebPush.kt, service/src/main/kotlin/fi/espoo/evaka/webpush/WebPushCrypto.kt
=> Add subject to web push JWT + improve error logging

frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReport.tsx
- Add sorting by unit name
- Preserve care area when coming back from a decision
=> Assistance need decision report sorting

service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
=> Remove a check that makes a wrong assumption

frontend/src/citizen-frontend/applications/queries.ts
=> Ensure application is rerendered after a modification or a send

frontend/src/citizen-frontend/map/UnitDetailsPanel.tsx, frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts, frontend/src/employee-frontend/components/reports/Occupancies.tsx, frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceExternalPersonModal.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx, service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
=> Prevent future attendances

service/src/integrationTest/kotlin/fi/espoo/evaka/s3/DocumentServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/s3/DocumentService.kt
=> Fix attachment filename encoding

frontend/src/employee-frontend/App.tsx, frontend/src/employee-frontend/components/EmployeeRoute.tsx
=> Improve page titles in employee-frontend

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
=> If staff arrived with JUSTIFIED_CHANGE, automatically depart it at 2000

.github/workflows/build.yml
=> Fix double service build

apigw/src/enduser/mapRoutes.ts, apigw/src/enduser/routes.ts, apigw/src/internal/app.ts, apigw/src/shared/proxy-utils.ts, frontend/build.js
=> Don't parse body in proxies

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx, frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts, frontend/src/e2e-test/specs/0_citizen/feature-flag-citizen-contract-day-absence.spec.ts
=> If more than 1 child, select no children in absence modal

frontend/src/lib-components/Notifications.tsx
=> Reload by clicking anywhere on the notification

service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
=> Add link to citizen calendar to missing reservations email

service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationSearchIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- Fix the (K) application filter to show applications for children that are or have been in club care
=> Fix application club placement filter

frontend/src/employee-frontend/api/absences.ts, service/codegen/src/main/kotlin/evaka/codegen/Check.kt, service/codegen/src/main/kotlin/evaka/codegen/apitypes/Controllers.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/AbsenceController.kt
=> Fix absence delete endpoint

service/buildSrc/src/main/kotlin/Version.kt
=> Upgrade dependencycheck plugin

frontend/src/e2e-test/pages/employee/applications/application-read-view.ts, frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts, frontend/src/employee-frontend/components/application-page/ApplicationDecisionsSection.tsx
=> Do not allow employee to accept decision for placement proposal

frontend/src/citizen-frontend/calendar/ReservationModal.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/DailyRepetitionTimeInputGrid.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/IrregularRepetitionTimeInputGrid.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/RepetitionTimeInputGrid.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/WeeklyRepetitionTimeInputGrid.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/form.ts
=> Fix making irregular reservations when date range spans a weekend

frontend/src/lib-common/utils/helpers.spec.ts
=> Mock window.location.host correctly in tests

frontend/src/e2e-test/pages/employee/holiday-periods.ts, frontend/src/e2e-test/specs/5_employee/holiday-period.spec.ts, frontend/src/e2e-test/utils/page.ts, frontend/src/employee-frontend/components/holiday-periods/HolidayPeriodForm.tsx, frontend/src/lib-components/atoms/buttons/AddButton.tsx, frontend/src/lib-components/atoms/buttons/Button.tsx, frontend/src/lib-components/atoms/buttons/InlineButton.tsx, frontend/src/lib-components/atoms/buttons/SkipToContent.tsx, frontend/src/lib-components/atoms/buttons/button-commons.tsx, frontend/src/lib-components/molecules/date-picker/DateRangePicker.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodController.kt, service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
Clear reservations and absences from holiday period when it's created.
=> Holiday reservations, part 4

frontend/src/employee-frontend/api/reports.ts, frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimes.kt, service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
v2 is behind a hidden toggle so we can test and compare.
Could use some refactoring and optimization if this turns out to be a valid approach
=> rewrite AttendanceReservationReport in a hopefully faster way

service/src/main/kotlin/fi/espoo/evaka/reservations/MissingReservationsReminders.kt
=> Use array in missing reservations query

service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
=> fix AttendanceReservationReport backup-care join

service/owasp-suppressions.xml
=> Suppress CVE-2023-20863

service/src/main/kotlin/fi/espoo/evaka/reservations/MissingReservationsReminders.kt
=> fix missingReservationsQuery perf

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
Only send one notification per guardian for outdated income instead of one notification per child
=> Send only one notification per outdated income, not per child

frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts, frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
=> Holiday reservations text changes

bin/add-license-headers.sh
=> Upgrade to reuse 1.1.2

frontend/src/citizen-frontend/messages/MessageEditor.tsx, frontend/src/citizen-frontend/messages/ThreadView.tsx, frontend/src/employee-frontend/components/messages/SingleThreadView.tsx, frontend/src/lib-components/molecules/MessageReplyEditor.tsx, frontend/src/lib-components/molecules/ToggleableRecipient.tsx, frontend/src/lib-components/utils/useReplyRecipients.ts
=> Require at least one primary recipient in citizen replies

frontend/src/e2e-test/pages/employee/vasu/vasu.ts, frontend/src/e2e-test/specs/5_employee/vasu.spec.ts, frontend/src/employee-frontend/components/vasu/components/FollowupQuestion.tsx
=> improve vasu followup question formatting

frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
=> EVAKA-4806: remove day-off feature from group calendar

service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
=> Allow closing and re-opening a Database.Connection

frontend/src/employee-frontend/api/daycare.ts, service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
=> show future units in backup care unit list

frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
-Unclear whether this text really describes what the action does, waiting for clarification
=> Fix sv text

frontend/src/citizen-frontend/calendar/ReservationModal.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/DailyRepetitionTimeInputGrid.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/WeeklyRepetitionTimeInputGrid.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts, frontend/src/citizen-frontend/calendar/reservation-modal/form.ts, frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
https://user-images.githubusercontent.com/70927/233299810-6c410fa1-808b-43b9-b503-f5bf718cb193.mov
=> Prefill holiday form state

evaka-bom/build.gradle.kts, service/buildSrc/src/main/kotlin/Version.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/s3/DocumentServiceIntegrationTest.kt
=> upgrade spring boot to 3.0.6 to resolve CVE-2023-20873

frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
=> fix irregular days alignment issues

.github/workflows/build.yml, service/Dockerfile
=> Github registry cache

frontend/src/citizen-frontend/calendar/CalendarGridView.tsx, frontend/src/citizen-frontend/calendar/DayView.tsx, frontend/src/citizen-frontend/calendar/WeekElem.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts, frontend/src/citizen-frontend/calendar/reservation-modal/form.ts, frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts, frontend/src/e2e-test/utils/page.ts, frontend/src/lib-common/generated/api-types/reservations.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
* Show holidays correctly in irregular mode if no children are reservable
* Show free absences as not editable, as they cannot be overwritten anyway
=> Holiday and absence fixes to citizen reservation modal

frontend/src/e2e-test/pages/employee/assistance-need-decision/assistance-need-decision-preview-page.ts, frontend/src/e2e-test/specs/5_employee/assistance-need-decision.spec.ts, frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionPage.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/api.ts, frontend/src/lib-common/generated/action.d.ts, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/main/kotlin/fi/espoo/evaka/Audit.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
=> Allow admin to revert a sent assistance need decision

apigw/src/enduser/mapRoutes.ts
This forces us to buffer all responses in apigw memory, but it seems like an acceptable tradeoff
=> Log digitransit API errors

.github/workflows/cleanup.yml
=> Cleanup docker containers

frontend/src/citizen-frontend/calendar/CalendarPage.tsx, frontend/src/citizen-frontend/calendar/ReservationModal.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts, frontend/src/citizen-frontend/calendar/reservation-modal/form.ts, frontend/src/e2e-test/pages/citizen/citizen-calendar.ts, frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
=> Remove the non-reservable days warning modal

service/src/integrationTest/kotlin/fi/espoo/evaka/PureJdbiTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/espoobi/EspooBiPocTest.kt, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/espoobi/Csv.kt, service/src/main/kotlin/fi/espoo/evaka/espoobi/EspooBiModels.kt, service/src/main/kotlin/fi/espoo/evaka/espoobi/EspooBiPoc.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
=> Add more Espoo BI CSV routes/tables

frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts, frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts, frontend/src/lib-common/reservations.ts
=> Both arrival and departure cannot be 00:00

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> Enable temporary employee in Espoo envs

frontend/src/e2e-test/specs/5_employee/unit-acl.spec.ts, frontend/src/employee-frontend/components/unit/tab-unit-information/DaycareAclAdditionModal.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts
=> Remove temporary employee feature flag

bin/add-license-headers.sh
=> Remove unused code from license script

service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/JdbiExtensionsTest.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt, service/src/main/kotlin/fi/espoo/evaka/shared/Timeline.kt, service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt, service/src/main/kotlin/fi/espoo/evaka/shared/db/JdbiExtensions.kt
=>  Add bidirectional Timeline <-> datemultirange db mapping support 

service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/MissingReservationsRemindersTest.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementType.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/MissingReservationsReminders.kt
=> Use placement type to check whether reservations are required

.github/workflows/build.yml, service/test.Dockerfile
=> Separated OWASP check CI job

service/src/integrationTest/kotlin/fi/espoo/evaka/espoobi/EspooBiPocTest.kt, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/espoobi/Csv.kt, service/src/main/kotlin/fi/espoo/evaka/espoobi/EspooBiModels.kt, service/src/main/kotlin/fi/espoo/evaka/espoobi/EspooBiPoc.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
=> Add even more CSV routes for Espoo BI

apigw/src/internal/keycloak-employee-saml.ts
It's not guaranteed to be set, so we shouldn't require it
=> Mark email optional in employee Keycloak profile

service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
=> HOTFIX: Allow PRESENT reservations outside holiday periods if reservations are not needed

frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx, frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx, frontend/src/lib-common/generated/api-types/backupcare.ts, frontend/src/lib-common/generated/api-types/placement.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/backupcare/BackupCareIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCare.kt, service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareQueries.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
=> Add origin unit name next to backup care chip

service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationSearchIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
=> Change DAYCARE_ONLY filter to also match preparatory applications

frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx, frontend/src/employee-frontend/components/common/ToolbarAccordion.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Adds placement unit name to ~~unit supervisor and special education teacher~~ all unit roles for all placements (not just own units).
=> Update placement unit name visibility

service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
=> Disallow emptying days in a closed holiday period

service/src/main/kotlin/fi/espoo/evaka/espoobi/EspooBiModels.kt
Sent date can be null depending on the status of the decision
=> Fix nullability in BI decision model

service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
=> Make sure HTML emails use a full document

.github/workflows/build.yml
=> Separate tag job

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
Use the new form framework instead of hand-crafted artisanal validation.
=> Fix AbsenceModal validation

frontend/src/citizen-frontend/income-statements/ChildIncomeStatementEditor.tsx, frontend/src/e2e-test/pages/employee/units/unit.ts
-Fix stuck spinner on reload
-Fix flaky click on modal inputs
=> Fix flaky tests

service/gradle/libs.versions.toml
=> Upgrade Spring Boot

frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx, frontend/src/employee-frontend/components/document-templates/documents.tsx, frontend/src/employee-frontend/components/document-templates/question-descriptors/RadioButtonGroupQuestionDescriptor.tsx, frontend/src/employee-frontend/components/document-templates/question-descriptors/types.ts, frontend/src/employee-frontend/components/document-templates/templates.tsx, frontend/src/lib-common/generated/api-types/document.ts, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
=> implement radio button group question type

.github/dependabot.yml
=> Use dependabot for frontend dependencies

.github/workflows/build.yml
=> Use voltti-actions master

service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
=> Exclude future group placements from vasu

.github/dependabot.yml
=> Use dependabot for apigw dependencies

frontend/package.json, frontend/src/citizen-frontend/api-client.ts, frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx, frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx, frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx, frontend/src/citizen-frontend/attachments.ts, frontend/src/citizen-frontend/income-statements/ChildIncomeStatementAttachments.tsx, frontend/src/citizen-frontend/income-statements/IncomeStatementAttachments.tsx, frontend/src/e2e-test/dev-api/index.ts, frontend/src/employee-frontend/api/attachments.ts, frontend/src/employee-frontend/api/client.ts, frontend/src/employee-frontend/components/IncomeStatementPage.tsx, frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx, frontend/src/employee-frontend/components/child-information/PedagogicalDocumentRow.tsx, frontend/src/employee-frontend/components/person-profile/income/IncomeItemEditor.tsx, frontend/src/employee-mobile-frontend/client.ts, frontend/src/employee-mobile-frontend/messages/api.ts, frontend/src/lib-components/employee/messages/MessageEditor.tsx, frontend/src/lib-components/molecules/FileUpload.tsx, frontend/yarn.lock
=> Upgrade axios to v1.4.0

frontend/src/citizen-frontend/calendar/CalendarPage.tsx, frontend/src/citizen-frontend/calendar/DayView.tsx, frontend/src/citizen-frontend/calendar/ReservationModal.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts, frontend/src/citizen-frontend/calendar/reservation-modal/form.ts, frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
Tell the user when a holiday period is closed and certain reservations cannot be made anymore.
=> Closed holiday period reservations

frontend/package.json, frontend/yarn.lock
=> Upgrade Playwright

compose/docker-compose.e2e-tests.yml
=> Remove suffix from playwright

frontend/src/employee-frontend/api/document-templates.ts, frontend/src/employee-frontend/components/document-templates/queries.ts, frontend/src/employee-frontend/components/document-templates/template-editor/DocumentTemplatesPage.tsx, frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx, frontend/src/lib-components/molecules/date-picker/DateRangePicker.tsx
- templates can be duplicated
- draft templates can be deleted
- template validity can always be updated
=> Document templates: more basic functionality

frontend/src/employee-frontend/components/placement-draft/PlacementDraft.tsx
fixes https://65ed1b6e26bf4879b37d76005a58a119.eu-west-1.aws.found.io:9243/s/evaka/app/discover#/context/8e0c8c30-fc8f-11e8-874a-f5222c9eb5ef/bj_IVogBiFV4c0d11kjh?_a=(columns:!(),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8e0c8c30-fc8f-11e8-874a-f5222c9eb5ef',key:env,negate:!f,params:(query:prod),type:phrase),query:(match_phrase:(env:prod))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8e0c8c30-fc8f-11e8-874a-f5222c9eb5ef',key:traceId,negate:!f,params:(query:'09b9ab59d64bf65e0a57d888aeefaffd'),type:phrase),query:(match_phrase:(traceId:'09b9ab59d64bf65e0a57d888aeefaffd')))),predecessorCount:5,sort:!(!('@timestamp',desc)),successorCount:5)
better fix would be to use form framework and generated api types
=> fix validation in create placement plan

frontend/README.md, frontend/package.json, frontend/unpack-pro-icons.sh, frontend/yarn.lock
=> Upgrade Font Awesome pro icons to v6.4.0

frontend/src/employee-frontend/api/child/child-documents.ts, frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx, frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx, frontend/src/employee-frontend/components/child-information/queries.ts, frontend/src/lib-common/generated/action.d.ts, frontend/src/lib-common/generated/api-types/document.ts, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/codegen/src/main/kotlin/evaka/codegen/actionenum/Definitions.kt, service/src/main/kotlin/fi/espoo/evaka/Audit.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/resources/db/migration/V325__child_document_published_at.sql, service/src/main/resources/migrations.txt
- deleting child document drafts
- add and display `published_at` time
- admin can unpublish child documents
- bug fix: should not try to save content of published document (caused http 400 in background)
- fix i18n
=> Child documents: more basic functionality

frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts, frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx, frontend/src/lib-common/api-types/reservations.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
=> Always show missing holiday reservations in unit week calendar

service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesCitizenController.kt
=> Don't throw 403 when deleting a deleted thing

frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/lib-common/generated/api-types/invoicing.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/ServiceNeedTestFixtures.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/espoobi/EspooBiPocTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/Helpers.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionSearchTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/espoobi/EspooBiModels.kt, service/src/main/kotlin/fi/espoo/evaka/espoobi/EspooBiPoc.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerator.kt, service/src/main/resources/db/migration/V326__fee_decision_service_need_option_id.sql, service/src/main/resources/migrations.txt, service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt, service/src/test/kotlin/fi/espoo/evaka/invoicing/service/PdfGenerationTest.kt
=> Save precise service need option id information to fee decisions

frontend/src/employee-frontend/components/messages/api.ts
=> Catch API failure correctly

service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
=> Child documents: add tests and improve validation

frontend/src/employee-frontend/components/unit/tab-calendar/AttendanceGroupFilterSelect.tsx
=> include future groups in unit calendar filters

evaka-bom/build.gradle.kts
=> CVE fix: upgrade to Guava 32.0

frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
=> Add shift care instructions to preschool application

frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts, frontend/src/e2e-test/specs/5_employee/feature-flag-preschool-application-connected-daycare-preferred-start-date.spec.ts, frontend/src/e2e-test/specs/5_employee/feature-flag-preschool-application-service-need-option.spec.ts, frontend/src/e2e-test/specs/5_employee/paper-application.spec.ts
=> Fix time dependent e2e tests

frontend/src/citizen-frontend/children/sections/placement-termination/PlacementTerminationSection.tsx
Related to https://github.com/espoon-voltti/evaka/pull/3593, sorry
=> Fix extra character in placement termination ui

service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
Placement should not be joined via guardian because its incomes doesn't affect base fee.
=> Fix income statement query placement valid date filter

service/src/main/resources/WEB-INF/templates/preparatory/decision.properties, service/src/main/resources/WEB-INF/templates/preparatory/decision_sv.properties, service/src/main/resources/WEB-INF/templates/preschool/decision.properties, service/src/main/resources/WEB-INF/templates/preschool/decision_sv.properties
=> Fix decision texts

service/src/main/kotlin/fi/espoo/evaka/espoobi/EspooBiModels.kt
=> Nullable db field should be nullable in Kotlin

.github/workflows/build.yml
=> Remove test-environment from CI

frontend/src/employee-frontend/components/document-templates/DocumentView.tsx, frontend/src/employee-frontend/components/document-templates/documents.tsx, frontend/src/employee-frontend/components/document-templates/question-descriptors/CheckboxGroupQuestionDescriptor.tsx, frontend/src/employee-frontend/components/document-templates/question-descriptors/TextQuestionDescriptor.tsx, frontend/src/employee-frontend/components/document-templates/template-editor/TemplateQuestionModal.tsx, frontend/src/employee-frontend/components/document-templates/template-editor/TemplateQuestionView.tsx, frontend/src/employee-frontend/components/document-templates/template-editor/TemplateSectionModal.tsx, frontend/src/employee-frontend/components/document-templates/template-editor/TemplateSectionView.tsx, frontend/src/employee-frontend/components/document-templates/templates.tsx, frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx, frontend/src/lib-common/generated/api-types/document.ts, frontend/src/lib-components/atoms/form/TextArea.tsx, frontend/src/lib-components/molecules/modals/BaseModal.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt, service/src/main/resources/db/migration/V328__document_checkbox_group_extra.sql, service/src/main/resources/migrations.txt
- add multiline support for text question
- add info text option to section titles
- checkbox group question allows including extra text fields
- add realtime preview to question modal
=> Document template improvements

frontend/src/e2e-test/pages/employee/child-information.ts, frontend/src/e2e-test/pages/employee/documents/child-document.ts, frontend/src/e2e-test/pages/employee/documents/document-templates.ts, frontend/src/e2e-test/pages/employee/employee-nav.ts, frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts, frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx, frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx, frontend/src/employee-frontend/components/child-information/queries.ts, frontend/src/employee-frontend/components/document-templates/DocumentView.tsx, frontend/src/employee-frontend/components/document-templates/question-descriptors/TextQuestionDescriptor.tsx, frontend/src/employee-frontend/components/document-templates/template-editor/DocumentTemplatesPage.tsx, frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx, frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx, frontend/src/employee-frontend/components/document-templates/template-editor/TemplateSectionModal.tsx, frontend/src/employee-frontend/components/document-templates/template-editor/TemplateSectionView.tsx
=> add e2e test for document template and child document basics

.github/workflows/build.yml
=> Fix deploy branch

frontend/src/lib-common/sentry.spec.ts, frontend/src/lib-common/sentry.ts
=> Another stab at ignoring irrelevant Sentry errors

frontend/src/lib-components/Notifications.tsx
=> Stop sending network connection restored events to Sentry

frontend/src/e2e-test/pages/employee/guardian-information.ts, frontend/src/e2e-test/specs/5_employee/guardian-information-page.spec.ts, frontend/src/employee-frontend/components/invoice/InvoiceRowsSectionRow.tsx, frontend/src/employee-frontend/components/person-profile/PersonInvoiceCorrections.tsx
=> Fix invoice correction note creation

frontend/src/employee-frontend/api/reports.ts, frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx
- "Autosave" UI caused several heavy queries when the user selected the filter combination for the report is replaced with explicit search button
=> Use button to trigger attendance report fetch

.github/workflows/build.yml
=> Enable TCPdump

.github/workflows/build.yml
=> Remove unnessary container build integration tests

frontend/src/citizen-frontend/children/sections/pedagogical-documents/PedagogicalDocumentsSection.tsx
This section requires strong auth and even has the lock icon, but RequireAuth was missing
=> Add missing RequireAuth

frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx, frontend/src/e2e-test/pages/citizen/citizen-calendar.ts, frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
Added missing 2nd reservation addition tests for day view and reservation modal. Related to 2nd reservation bug fix.
=> Added e2e tests to verify citizen second reservation success

frontend/src/e2e-test/dev-api/types.ts, frontend/src/e2e-test/pages/employee/reports.ts, frontend/src/e2e-test/specs/5_employee/missing-head-of-family-report.spec.ts, frontend/src/e2e-test/utils/page.ts, frontend/src/employee-frontend/api/reports.ts, frontend/src/employee-frontend/components/Reports.tsx, frontend/src/employee-frontend/components/reports/DuplicatePeople.tsx, frontend/src/employee-frontend/components/reports/MissingHeadOfFamily.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/main/kotlin/fi/espoo/evaka/reports/MissingHeadOfFamilyReport.kt
https://github.com/espoon-voltti/evaka/pull/3343 for missing head of family report.
=> Add show duplicate filter to missing head of family report

service/owasp-suppressions.xml
=> Suppress CVE-2023-35116

service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
Adds missing coalesce to handle missing explicit service need shift care types.
=> Fix raw report type transformation

evaka-bom/build.gradle.kts
=> Bump bouncy castle

frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/dev-api/types.ts, frontend/src/e2e-test/pages/employee/reports.ts, frontend/src/e2e-test/specs/5_employee/manual-duplication-report.spec.ts, frontend/src/employee-frontend/components/Reports.tsx, frontend/src/employee-frontend/components/reports/ManualDuplicationReport.tsx, frontend/src/lib-common/generated/api-types/reports.ts, service/src/main/kotlin/fi/espoo/evaka/reports/ManualDuplicationReportController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Decision's were joined by child id, but they should be joined by application id.
=> Fix manual duplication report

apigw/yarn.lock
=> Fix apigw build

frontend/src/employee-frontend/components/reports/Raw.tsx
=> Use button instead of autofetch

evaka-bom/build.gradle.kts
=> Bump netty to fix CVE-2023-34468

evaka-bom/build.gradle.kts, frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/children/consent/ChildConsentQueries.kt
=> Use employee nickname in mobile

frontend/src/lib-components/molecules/date-picker/DatePicker.tsx, frontend/src/lib-components/molecules/modals/BaseModal.tsx
=> fix datepicker closing on modal scrollbar clicked

frontend/src/employee-frontend/App.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionReadPage.tsx, frontend/src/lib-common/generated/api-types/assistanceneed.ts, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecision.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt
=> Assistance need preschool decisions part 2

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
=> Change text

frontend/src/employee-frontend/api/reports.ts, frontend/src/employee-frontend/components/reports/PlacementCount.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/PlacementCountReportControllerTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/ManualDuplicationReportController.kt, service/src/main/kotlin/fi/espoo/evaka/reports/PlacementCountReportController.kt
=> Evaka fix placement count report

frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
=> Swedish translations

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt
=> Delete non relevant people after 2 months of inactivity

evaka-bom/build.gradle.kts, service/gradle/libs.versions.toml, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
=> Fix decision display name and content type

frontend/src/employee-frontend/App.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionReadPage.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/api-preschool.ts, frontend/src/employee-frontend/components/child-information/queries.ts, frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReport.tsx, frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReportPreschoolDecision.tsx, frontend/src/lib-common/generated/api-types/assistanceneed.ts, frontend/src/lib-common/generated/api-types/reports.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AssistanceNeedDecisionsReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecision.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedDecisionsReport.kt, service/src/main/resources/db/migration/V332__alter_assistance_need_preschool_decision_constraints.sql, service/src/main/resources/migrations.txt
=> Assistance need preschool decisions - part 3

frontend/src/citizen-frontend/index.tsx, frontend/src/employee-frontend/index.tsx, frontend/src/employee-mobile-frontend/index.tsx
=> Fix React 18 warnings

keycloak/Dockerfile
=> Upgrade Keycloak to 21.1.2

frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx, frontend/src/lib-common/generated/api-types/reports.ts, service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportController.kt
=> Update assistance report to work with new model

frontend/src/employee-mobile-frontend/child-info/ImageEditor.tsx
=> Close child image editor after successful upload

.github/workflows/build.yml
=> Use new CI role

.github/workflows/build.yml, .gitignore, frontend/.dockerignore, frontend/.gitignore, frontend/Dockerfile, frontend/README.md, frontend/setup-pro-icons.sh
=> Remove fontawesome files

service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/AbsenceServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
=> Don't show false missing holiday reservations in group month calendar

.github/workflows/build.yml, bin/add-license-headers.sh
=> Use forked reuse-tool action

.github/workflows/build.yml, .reuse/dep5, apigw/.gitignore, bin/add-license-headers.sh, compose/.gitignore, docs/.gitignore, evaka-bom/.gitignore, frontend/.gitignore, frontend/vendor/fortawesome/.gitignore, keycloak/.gitignore, proxy/.gitignore, service-lib/.gitignore, service/.gitignore, service/custom-ktlint-rules/.gitignore
=> Update reuse tool

frontend/src/employee-frontend/components/common/Filters.tsx, frontend/src/lib-common/generated/api-types/invoicing.ts, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
Adds a feature flagged finance view filter option for fee decisions with a child that has placement type `PRESCHOOL_CLUB`.
=> Finance view preschool club filter for fee decisions

service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
=> Keep unsent applications for 2 months

frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx, frontend/src/employee-mobile-frontend/common/components.tsx, frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
=> Enhance return-to-present UI

frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx, frontend/src/employee-frontend/components/vasu/VasuStateTransitionButtons.tsx, frontend/src/employee-frontend/components/vasu/api.ts, frontend/src/employee-frontend/components/vasu/queries.ts, frontend/src/employee-frontend/query.ts, frontend/src/lib-common/generated/action.d.ts, frontend/src/lib-components/atoms/buttons/MutateButton.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/Audit.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
=> Allow deletion of draft vasu for admin

service/build-docker.sh
=> Don't run owasp checks for fork PRs

frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/DailyServiceTimeTable.tsx, frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceNeedAndDailyServiceTimeSection.tsx, frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceNeedTable.tsx, frontend/src/citizen-frontend/navigation/MobileNav.tsx, frontend/src/e2e-test/pages/citizen/citizen-children.ts, frontend/src/e2e-test/pages/citizen/citizen-header.ts, frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts, frontend/src/lib-components/atoms/HorizontalLine.tsx
Mobile layout for https://github.com/espoon-voltti/evaka/pull/3593
=> Add citizen service need mobile layout

frontend/src/citizen-frontend/calendar/DayView.tsx
=> Prevent navigating past the edges of the calendar

frontend/src/lib-components/molecules/FileUpload.tsx
=> Hide the file delete button if upload is in progress

compose/e2e/playwright/bin/run-tests.sh, keycloak/.gitignore, keycloak/Dockerfile, keycloak/README.md, keycloak/evaka-logging/pom.xml, keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/EvakaLoggingEventListenerProvider.java, keycloak/evaka-review-profile/pom.xml, keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java, keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff, keycloak/update.sh
=> Update KeyCloak to 22.0.1

frontend/src/citizen-frontend/income-statements/ChildIncomeStatementEditor.tsx, frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx, frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx, frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx, frontend/src/citizen-frontend/income-statements/types/form.ts, frontend/src/e2e-test/pages/citizen/citizen-child-income.ts, frontend/src/e2e-test/specs/0_citizen/citizen-child-income-statement.spec.ts, frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
=> Require users to set the start date of income statement

evaka-bom/build.gradle.kts, service/owasp-suppressions.xml
=> Bump thymeleaf

frontend/src/e2e-test/pages/employee/child-information.ts, frontend/src/e2e-test/specs/5_employee/assistance-need-decision.spec.ts, frontend/src/e2e-test/specs/5_employee/child-information-assistance.spec.ts, frontend/src/e2e-test/specs/8_access/access.spec.ts, frontend/src/employee-frontend/components/ChildInformation.tsx, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
Staff should be able to read accepted daycare assistance decisions.
=> Add accepted daycare assistance decisions read for staff

service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt, service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt, service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt, service/src/main/kotlin/fi/espoo/evaka/shared/message/MessageProvider.kt
Send email and SFI message about a new decision.
This is mostly copy paste from previous implementation, but its correctness seems somewhat questionable.
=> Assistance need preschool decisions - part 5

apigw/src/enduser/dev-sfi-auth.ts
Move dev suomi.fi login submit button to top of page for easier usage
=> Reposition submit button on top of page for easier dev usage

service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionController.kt
=> assistance need preschool decision integration tests

frontend/src/lib-common/generated/api-types/assistanceneed.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecision.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt
=> fix nullability issue in assistance preschool decisions

service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt
=> Assistance need preschool decision update bug fix

service/src/main/resources/WEB-INF/templates/assistance-need-preschool/decision.html, service/src/main/resources/WEB-INF/templates/assistance-need-preschool/decision.properties
Lisäyksiä esiopetuksen tuentarpeen päätös-pdf:ään
=> add remaining fields to assistance need preschool decision pdf

frontend/src/employee-frontend/components/PersonProfile.tsx
Made the family-overview section visible for service workers in person profile.
=> Made family-overview visible for service worker -role.

frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceForm.tsx, frontend/src/employee-frontend/components/child-information/assistance/OtherAssistanceMeasureForm.tsx, frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceForm.tsx, frontend/src/lib-customizations/employee.tsx, frontend/src/lib-customizations/espoo/employee.tsx, frontend/src/lib-customizations/types.d.ts
=> Allow customizing visibility of assistance enums

frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/dev-api/types.ts, frontend/src/e2e-test/pages/employee/reports.ts, frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts, frontend/src/e2e-test/specs/5_employee/assistance-need-preschool-decision.spec.ts, frontend/src/employee-frontend/components/child-information/assistance-need/decision/api-preschool.ts, frontend/src/employee-frontend/components/child-information/queries.ts, frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReportPreschoolDecision.tsx, frontend/src/lib-common/generated/api-types/assistanceneed.ts, frontend/src/lib-components/assistance-need-decision/AssistanceNeedPreschoolDecisionReadOnly.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Esiopetuksen tuen tarpeen päätöksen mitätöinti
=> Assistance need preschool decision annulment

compose/e2e/playwright.Dockerfile
This reverts commit f0e8c2d1731fc27c0d58d533fc55df408ea86840.
=> Revert "Update playwright"

frontend/package.json, frontend/yarn.lock
Reverts espoon-voltti/evaka#3931
=> Revert "Bump downshift from 7.6.2 to 8.1.0 in /frontend"

apigw/package.json, apigw/yarn.lock
=> Upgrade DD

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> enable assistance need preschool decisions in staging

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt
=> Ensure that non fi-sv-en person gets emails with valid language

frontend/src/employee-frontend/components/child-information/assistance/AssistanceFactorSection.tsx, frontend/src/employee-frontend/components/child-information/assistance/OtherAssistanceMeasureSection.tsx, frontend/src/lib-components/molecules/ExpandingInfo.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
=> Add optional info boxes to some sections of child assistance

.github/workflows/playwright.yml
=> Disable pull request builds and tcpdumps, fix Dockerfile name

service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/pis/service/GuardianQueries.kt
=> send assistance decisions to foster parents

evaka-bom/build.gradle.kts, service/build.gradle.kts, service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
=> Use HTML as the master e-mail template format

frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx, frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
=> adjust assistance decision employee selection

frontend/src/lib-common/generated/api-types/vasu.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/espoobi/EspooBiPocTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/JobSchedule.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt, service/src/main/resources/db/migration/V338__curriculum_document_event_evaka_user_id.sql, service/src/main/resources/migrations.txt
=> Close expired vasus in a nightly scheduled job

.github/dependabot.yml
=> dependabot: group all lint deps

service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt
=> Remove non-existent tables + ids

frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/AttendanceSummaryTable.tsx, frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceNeedAndDailyServiceTimeSection.tsx, frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/api.ts, frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/queries.ts, frontend/src/citizen-frontend/query.ts, frontend/src/lib-common/generated/api-types/children.ts, frontend/src/lib-common/generated/api-types/serviceneed.ts, frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx, frontend/src/lib-customizations/types.d.ts, service/src/main/kotlin/fi/espoo/evaka/Audit.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt, service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeed.kt, service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
=> Add attendance summary for contract days children

.github/workflows/playwright.yml, compose/docker-compose.e2e-tests.yml
=> Fix playwright

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx, frontend/src/citizen-frontend/calendar/ReservationModal.tsx, frontend/src/citizen-frontend/messages/MessageEditor.tsx, frontend/src/e2e-test/pages/citizen/citizen-calendar.ts, frontend/src/e2e-test/pages/citizen/citizen-messages.ts, frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts, frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
=> Hide child from reservation/attendance modal if placement is in the past

frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
=> Update notification settings translations

service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationQueriesTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationService.kt, service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/domain/Language.kt, service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt, service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt, service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/JobSchedule.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt, service/src/main/resources/db/migration/V340__calendar_event_created_updated.sql, service/src/main/resources/migrations.txt
=> Send email digests to parents about new calendar events

service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt, service/src/main/resources/dev-data/espoo-dev-data.sql
=> Change assistance action option text

frontend/src/employee-mobile-frontend/common/service-worker.tsx, frontend/src/employee-mobile-frontend/messages/UnreadMessagesPage.tsx, frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
=> Add MVP of mobile push settings

service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt, service/src/main/resources/db/migration/R__koski_views.sql
This assistance level wasn't supposed to be sent...
=> Don't send SPECIAL_SUPPORT to Koski

frontend/src/employee-frontend/components/child-information/ChildDiscussions.tsx
Fixed form validation on creation modal for child discussion
=> Fix form validation on child discussion creation

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
Fix bugs in the voucher value decision report mega-SQL. Integration tests included.
=> Oulu voucher value report fixes

frontend/src/e2e-test/pages/employee/guardian-information.ts, frontend/src/employee-frontend/components/person-profile/income/IncomeItemEditor.tsx, frontend/src/lib-components/molecules/date-picker/DateRangePicker.tsx
New input widget allows clearing the income end date
=> Use clearable date input for income

frontend/src/citizen-frontend/decisions/decisions-page/AssistancePreschoolDecision.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, frontend/src/lib-customizations/defaults/employee/i18n/sv.tsx, service/src/main/resources/WEB-INF/templates/assistance-need-preschool/decision.html, service/src/main/resources/WEB-INF/templates/assistance-need-preschool/decision.properties, service/src/main/resources/WEB-INF/templates/assistance-need-preschool/decision_sv.properties
=> Assistance preschool decision i18n

frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx, frontend/src/lib-common/generated/api-types/reports.ts, service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportController.kt
Small improvements to assistance report:
1. [Cleanup assistance report unnecessary columns](https://github.com/espoon-voltti/evaka/commit/1a85c611df3b6581bebac38bc2d614a44e5bff75)
2. [Add assistance report unit filter](https://github.com/espoon-voltti/evaka/commit/11cb26ab19eaffeff0028ac358f4da6ca5b0adeb)
3. [Fix assistance report customization](https://github.com/espoon-voltti/evaka/commit/31f124938c484d6e12b8db8b188a90b00e2946bb)
=> Assistance report improvements part1

apigw/yarn.lock, frontend/yarn.lock
=> yarn dedupe

service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecision.kt
=> fix validation of assistance decision otherRepresentativeHeard

frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx, frontend/src/employee-frontend/components/child-information/queries.ts
=> invalidate decision makers when changing decision unit

frontend/src/citizen-frontend/decisions/assistance-decision-page/AssistancePreschoolDecisionPage.tsx
=> use language of the decision when rendering it for citizens

frontend/src/lib-customizations/defaults/employee/i18n/sv.tsx
=> add missing translation

frontend/src/lib-common/generated/api-types/decision.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt, service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionDraftService.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/decision/DecisionType.kt
I found a random branch with small enhancements.
=> Small enhancements

service/src/main/kotlin/fi/espoo/evaka/shared/auth/Acl.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Added two missing permissions for finance staff - read fee-decisions and income types.
=> Added missing permissions for finance staff.

.github/workflows/build.yml
=> Remove index.html and worker files before uploading

service/owasp-suppressions.xml
=> Add an owasp suppression

service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorV2.kt
=> extend fee decision draft generation to 15 months

frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
=> Fix static files index.html

apigw/src/internal/app.ts, service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt, service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- Use `EmailContent.fromHtml` for all emails
- Use consistent code style in all email messages
- Add an endpoint to `DevApi` to preview email messages (both html and text versions)
- Make calendar event notification email better
=> Email enhancements

.github/workflows/build.yml
=> Remove old S3 frontend installation

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Added missing permissions related to invoices and invoice corrections for finance staff role.
=> Fix finance staff role permissions

frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx, frontend/src/lib-components/assistance-need-decision/AssistanceNeedPreschoolDecisionReadOnly.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, frontend/src/lib-customizations/defaults/employee/i18n/sv.tsx
=> add legal texts to preschool assistance decision

.github/workflows/build.yml
=> Use mask-password in CI

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
=> fix fee decision generator v2 test

frontend/src/employee-frontend/api/invoicing.ts, frontend/src/employee-frontend/components/common/Filters.tsx, frontend/src/employee-frontend/components/fee-decisions/Actions.tsx, frontend/src/employee-frontend/components/fee-decisions/FeeDecisionsPage.tsx, frontend/src/lib-common/generated/api-types/invoicing.ts, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerationForPlacementChangesIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/Audit.kt, service/src/main/kotlin/fi/espoo/evaka/espoobi/EspooBiPoc.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorV2.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/resources/db/migration/V346__fee_decision_ignored_drafts.sql, service/src/main/resources/migrations.txt
=> Fee decision ignored status

frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
=> Add missing httpsScheme variable to svebi config

frontend/proxy/files/bin/proxy-entrypoint.sh, frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
=> Make S3 fallback static files optional

frontend/src/lib-components/atoms/dropdowns/Combobox.tsx
=> fix bug where clearing combobox submits the form

frontend/src/employee-frontend/App.tsx
`citizen-frontend` already has the same, so just add it to `employee-frontend`, too.
=> Redirect to front page if page is not found

frontend/src/citizen-frontend/calendar/DayView.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/DailyRepetitionTimeInputGrid.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/IrregularRepetitionTimeInputGrid.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx, frontend/src/citizen-frontend/calendar/reservation-modal/WeeklyRepetitionTimeInputGrid.tsx, frontend/src/employee-frontend/components/unit/TabCalendar.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/ReservationModalSingleChild.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx
All children can now have two reservations per day, so there's no need to pass the prop through the component hierarchy.
=> Remove unnecessary checks about two reservations

service/owasp-suppressions.xml
=> Suppress CVE that doesn't apply to us

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
August is half fee and attendance is always full month.
=> Fix preschool club invoicing

frontend/src/e2e-test/pages/employee/assistance-need-decision/assistance-need-preschool-decision-preview-page.ts, frontend/src/e2e-test/specs/5_employee/assistance-need-preschool-decision.spec.ts, frontend/src/employee-frontend/components/ChildInformation.tsx, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
- use authorization filter for fetching preschool assistance need decisions by child id for employee view
- check staff access to individual decision based on decision status
- e2e tests for role visibility
=> Staff preschool decision read access

frontend/src/e2e-test/specs/0_citizen/citizen-pedagogical-documents.spec.ts, frontend/src/e2e-test/specs/0_citizen/citizen-vasu.spec.ts, frontend/src/e2e-test/specs/5_employee/guardian-income-statements.spec.ts, service/owasp-suppressions.xml, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
=> add mocked now to failing e2e tests

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> Enable citizen email settings in Espoo

frontend/package.json, frontend/src/citizen-frontend/messages/ThreadView.tsx, frontend/src/employee-frontend/components/messages/SingleThreadView.tsx, frontend/src/employee-mobile-frontend/messages/ThreadView.tsx, frontend/src/lib-components/Notifications.tsx, frontend/src/lib-components/atoms/Linkify.spec.tsx, frontend/src/lib-components/atoms/Linkify.tsx, frontend/src/lib-components/jest.config.ts, frontend/src/lib-components/tsconfig.json, frontend/yarn.lock
=> Replace react-linkify with linkify-it

frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
disable child documents publishing until citizen frontend has been implemented
=> disable child documents publishing

frontend/src/e2e-test/pages/employee/guardian-information.ts, frontend/src/e2e-test/specs/5_employee/child-income.spec.ts, frontend/src/e2e-test/specs/5_employee/income.spec.ts, frontend/src/employee-frontend/api/partnerships.ts, frontend/src/employee-frontend/components/child-information/Placements.tsx, frontend/src/employee-frontend/components/child-information/placements/CreatePlacementModal.tsx, frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx, frontend/src/employee-frontend/components/child-information/placements/service-needs/ServiceNeedEditorRow.tsx, frontend/src/employee-frontend/components/common/RetroactiveConfirmation.spec.ts, frontend/src/employee-frontend/components/common/RetroactiveConfirmation.tsx, frontend/src/employee-frontend/components/person-profile/PersonFridgePartner.tsx, frontend/src/employee-frontend/components/person-profile/income/IncomeItemEditor.tsx, frontend/src/employee-frontend/components/person-profile/person-fridge-child/FridgeChildModal.tsx, frontend/src/employee-frontend/components/person-profile/person-fridge-partner/FridgePartnerModal.tsx, frontend/src/lib-common/generated/action.d.ts, frontend/src/lib-common/generated/api-types/pis.ts, service/codegen/src/main/kotlin/evaka/codegen/actionenum/Definitions.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PartnershipsControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PartnershipsController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
=> Confirm retroactive changes

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
=> Update preschool club invoicing

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> enable feeDecisionIgnoredStatus in espoo prod

frontend/src/lib-common/generated/api-types/assistance.ts, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/main/kotlin/fi/espoo/evaka/assistance/Assistance.kt, service/src/main/resources/db/migration/V347__add_finnish_second_language_assistance_measure_type.sql, service/src/main/resources/migrations.txt
Added enum value to other assistance measure type in db and frontend
=> added finnish as second language to assistance measure type

frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, frontend/src/lib-customizations/defaults/employee/i18n/sv.tsx, service/src/main/resources/WEB-INF/templates/assistance-need-preschool/decision.properties, service/src/main/resources/WEB-INF/templates/assistance-need-preschool/decision_sv.properties
=> fix confidentiality law reference

service/src/main/kotlin/fi/espoo/evaka/reports/FuturePreschoolersReport.kt
=> fix: only select current placement for preschooler raport

service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
Can be merged once the email notification settings feature is on in production.
=> Add unsubscribe links to all emails

frontend/src/lib-components/molecules/date-picker/DatePickerInput.tsx, frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
=> HOTFIX: Fix native android datepicker

frontend/src/citizen-frontend/personal-details/PersonalDetails.tsx, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts
=> Remove citizenEmailNotificationSettings feature flag

service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
=> regenerate finance decisions nightly

service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorV2.kt
=> fee decisions are created from original start date onwards

service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaService.kt, service/src/main/kotlin/fi/espoo/evaka/varda/old/VardaResetService.kt, service/src/main/kotlin/fi/espoo/evaka/varda/old/VardaUpdateService.kt
=> Bring old varda services back for now

frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx, frontend/src/lib-components/document-templates/DocumentView.tsx, frontend/src/lib-components/document-templates/question-descriptors/CheckboxQuestionDescriptor.tsx, frontend/src/lib-components/i18n.tsx, frontend/src/lib-customizations/defaults/components/i18n/en.tsx, frontend/src/lib-customizations/defaults/components/i18n/fi.tsx, frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
=> visual fixes to pedagogical documents read mode

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> enable placementGuarantee in Espoo staging

keycloak/Dockerfile, keycloak/evaka-logging/pom.xml, keycloak/evaka-review-profile/pom.xml, keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java, keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff, keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java.diff, keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/diffs.sh
=> KeyCloak 22.0.3

keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/diffs.sh
=> Fix diff.sh shellcheck

service/src/main/kotlin/fi/espoo/evaka/espoo/EspooAsyncJob.kt
The type system allows using the superclass here, but it doesn't work in practice...
=> Fix pool definition

service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Our config will be:
```
assistanceDecisionMakerRoles = setOf(UserRole.DIRECTOR, UserRole.UNIT_SUPERVISOR),
preschoolAssistanceDecisionMakerRoles = setOf(UserRole.DIRECTOR),
```
=> Add preschool assistance decision maker roles config

frontend/src/employee-frontend/components/timeline/TimelinePage.tsx
=> fix timeline rendering

service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
=> Log skipped fee decision ids

compose/e2e/playwright.Dockerfile
=> Bump playwright docker image

compose/README.md
=> Fix playwright tagging doc

frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/ChartTooltip.tsx, frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx
=> Fixes to the per-day occupancy graph

service/src/main/kotlin/fi/espoo/evaka/varda/old/VardaResetService.kt, service/src/main/kotlin/fi/espoo/evaka/varda/old/VardaUpdateService.kt
There is already an inbuilt 429 retry mechanism so reduce unnecessary retries for less load on varda
=> Reduce unnecessary retries

frontend/src/employee-mobile-frontend/child-attendance/actions/AbsenceSelector.tsx, frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsent.tsx, frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsentBeforehand.tsx, frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx, frontend/src/lib-customizations/types.d.ts, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
=> Add no partial absence type

frontend/src/e2e-test/pages/mobile/child-page.ts, frontend/src/e2e-test/pages/mobile/list-page.ts, frontend/src/e2e-test/specs/6_mobile/absences.spec.ts, frontend/src/e2e-test/specs/6_mobile/child-attendances.spec.ts, frontend/src/e2e-test/specs/6_mobile/messages.spec.ts, frontend/src/e2e-test/specs/6_mobile/notes.spec.ts, frontend/src/e2e-test/specs/6_mobile/pin-login.spec.ts, frontend/src/employee-mobile-frontend/child-attendance/AttendanceList.tsx, frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx, frontend/src/employee-mobile-frontend/child-attendance/ChildList.tsx, frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx, frontend/src/employee-mobile-frontend/child-attendance/DailyNote.tsx, frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx, frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx, frontend/src/employee-mobile-frontend/child-attendance/api.ts, frontend/src/employee-mobile-frontend/child-attendance/utils.ts, frontend/src/employee-mobile-frontend/child-info/AttendanceChildPage.tsx, frontend/src/employee-mobile-frontend/child-info/ChildButtons.tsx, frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildComing.tsx, frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildDeparted.tsx, frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildPresent.tsx, frontend/src/employee-mobile-frontend/common/ChildNameBackButton.tsx, frontend/src/employee-mobile-frontend/common/FreeTextSearch.tsx, frontend/src/lib-common/generated/api-types/attendance.ts, frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
* Show preschool/club children in absent list during term break
* Show "Ei toimintaa tänään" in child page
=> Preschool/club term breaks, part 3 (employee mobile frontend) 

apigw/src/internal/__tests__/mobile-device-session.ts, apigw/src/internal/routes/auth-status.ts, apigw/src/shared/service-client.ts, frontend/src/lib-common/generated/api-types/pis.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/pairing/PairingIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pairing/MobileDeviceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pairing/PairingQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pairing/PairingsController.kt, service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/resources/db/migration/V355__mobile_device_tracking.sql, service/src/main/resources/migrations.txt
=> Track user agent and last seen info of mobile devices

service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareQueries.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/data/BoundedRange.kt, service/src/main/kotlin/fi/espoo/evaka/shared/data/RangeBasedMap.kt, service/src/main/kotlin/fi/espoo/evaka/shared/data/RangeBasedSet.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
Instead of having special handling for all possible cases, use `DateMap` to figure out the *desired state*, and make sure we end up in that state.
=> Recreate backup cares on placement updates/deletes

frontend/src/e2e-test/browser.ts
=> Improve behaviour if a E2E test crashes

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerationForDataChangesIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Incomes.kt
=> fix bug with income equality comparison

service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentService.kt, service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
=> HOJKS - part 2

apigw/src/internal/app.ts, apigw/src/shared/config.ts, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBiClient.kt, service/src/main/resources/application-local.yaml
=> Fixes/updates to Espoo BI

frontend/src/citizen-frontend/calendar/calendar-elements.tsx, frontend/src/citizen-frontend/navigation/MobileNav.tsx, frontend/src/citizen-frontend/navigation/shared-components.tsx, frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/dev-api/index.ts, frontend/src/e2e-test/dev-api/types.ts, frontend/src/e2e-test/pages/citizen/citizen-calendar.ts, frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts, frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts, frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts, frontend/src/e2e-test/specs/0_citizen/feature-flag-citizen-reservations-intermittent-shif-care.spec.ts, frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts, frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
Also:
- Refactor calendar e2e page model for simpler asserting of day contents
- Some random fixes
=> Add more e2e tests for citizen calendar days

frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts, frontend/src/e2e-test/specs/5_employee/unit-calendar-events.spec.ts, frontend/src/e2e-test/utils/page.ts, frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
=> Enable calendar event save button only if data is valid

frontend/src/citizen-frontend/messages/MessageEditor.tsx, frontend/src/e2e-test/browser.ts, frontend/src/e2e-test/dev-api/index.ts, frontend/src/e2e-test/pages/citizen/citizen-messages.ts, frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunnerTest.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/AsyncJobConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
=> E2E test reliability fixes

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
If child arrives near preschool end time, it should be consired as billable attendance.
=> Fix partial absence thresholds for afternoon arrival

frontend/src/employee-frontend/components/person-profile/income/IncomeItemEditor.tsx
=> Move income editor's retroactive warning

frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx, frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/VasuPage.tsx, frontend/src/lib-components/layout/flex-helpers.ts
=> Add download (print) button to citizen child document view

frontend/src/e2e-test/pages/employee/child-information.ts, frontend/src/e2e-test/pages/employee/documents/child-document.ts, frontend/src/e2e-test/pages/employee/documents/document-templates.ts, frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts, frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts, frontend/src/e2e-test/utils/page.ts, frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx, frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx, frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
=> Hojks e2e tests

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt, service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
If sibling starts in the middle of the month, preschool club should be invoiced only once. And it should be from the first decision.
=> Fix preschool club double invoice

service/src/integrationTest/kotlin/fi/espoo/evaka/placement/FiveYearOldDaycarePlacementsIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
=> Fix placement guarantee for automatic five year old placements

.github/dependabot.yml
=> Ignore patch upgrades of gradle dependencies

service/evaka-bom/build.gradle.kts, service/gradle/libs.versions.toml
=> Refactor gradle dependencies to support dependabot

frontend/src/employee-frontend/components/common/RetroactiveConfirmation.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, frontend/src/lib-customizations/espoo/employee.tsx
=> Espoo retroactive confirmation email

frontend/src/employee-frontend/api/child/child-documents.ts, frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx, frontend/src/lib-common/generated/api-types/document.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
Child document list seems to be missing permitted actions support.
=> Add child documents permitted actions support

frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx, frontend/src/citizen-frontend/child-documents/api.ts, frontend/src/e2e-test/dev-api/fixtures.ts, frontend/src/e2e-test/dev-api/types.ts, frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts, frontend/src/employee-frontend/api/child/child-documents.ts, frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx, frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx, frontend/src/lib-common/generated/api-types/document.ts, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizenIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt, service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/resources/db/migration/V361__child_document_modified_at.sql, service/src/main/resources/migrations.txt
=> Display child document publish status and modified time

frontend/src/employee-frontend/components/document-templates/template-editor/TemplateSectionView.tsx
=> fix section buttons overlapping long title

frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx, frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx, frontend/src/lib-components/document-templates/question-descriptors/StaticTextDisplayQuestionDescriptor.tsx, frontend/src/lib-components/molecules/ExpandingInfo.tsx, service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
=> Template editor improvements

.github/workflows/build.yml
=> Slack notification on CI failures

frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
=> hotfix unnecesary initial save on child document

frontend/src/employee-mobile-frontend/App.tsx, frontend/src/employee-mobile-frontend/child-attendance/AttendanceList.tsx, frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx, frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx, frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsent.tsx, frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx, frontend/src/employee-mobile-frontend/child-info/AttendanceChildPage.tsx, frontend/src/employee-mobile-frontend/child-info/ChildButtons.tsx, frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildComing.tsx, frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildDeparted.tsx, frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildPresent.tsx, frontend/src/employee-mobile-frontend/child-notes/ChildNotes.tsx, frontend/src/employee-mobile-frontend/common/BottomNavbar.tsx, frontend/src/employee-mobile-frontend/common/selected-group.ts, frontend/src/employee-mobile-frontend/messages/MessageEditorPage.tsx, frontend/src/employee-mobile-frontend/messages/UnreadMessagesPage.tsx, frontend/src/employee-mobile-frontend/messages/state.tsx, frontend/src/employee-mobile-frontend/staff-attendance/MarkExternalStaffMemberArrivalPage.tsx, frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx, frontend/src/employee-mobile-frontend/staff-attendance/StaffListItem.tsx, frontend/src/employee-mobile-frontend/staff-attendance/StaffMarkArrivedPage.tsx, frontend/src/employee-mobile-frontend/staff-attendance/StaffMarkDepartedPage.tsx, frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx, frontend/src/employee-mobile-frontend/staff/StaffPage.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/note/NotesController.kt, service/src/main/kotlin/fi/espoo/evaka/note/child/daily/ChildDailyNoteQueries.kt, service/src/main/kotlin/fi/espoo/evaka/note/child/sticky/ChildStickyNoteQueries.kt
=> Fix invalid group note queries done with id=all

service/src/main/kotlin/fi/espoo/evaka/varda/VardaService.kt, service/src/main/kotlin/fi/espoo/evaka/varda/old/VardaResetService.kt
=> If child delete fails because child is not in varda, continue

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> Enable placement guarantee in Espoo prod

service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBi.kt, service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBiModels.kt
=> Add unit id to Espoo BI group model

frontend/src/e2e-test/pages/employee/child-information.ts, frontend/src/e2e-test/pages/employee/vasu/vasu.ts, frontend/src/e2e-test/specs/5_employee/curriculum-document.spec.ts, frontend/src/employee-frontend/App.tsx, frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx, frontend/src/employee-frontend/components/vasu/VasuEditPage.tsx, frontend/src/employee-frontend/components/vasu/VasuPage.tsx, frontend/src/employee-frontend/components/vasu/VasuStateTransitionButtons.tsx, frontend/src/employee-frontend/components/vasu/components/LeaveVasuPageButton.tsx, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt
=> Add leops to be visible from duplicate

frontend/src/e2e-test/pages/employee/documents/child-document.ts, frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts, frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx, frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
=> child documents: default to read mode, fine tune layout

.github/workflows/build.yml
=> Tag GHCR images and remove proxy in CI

frontend/src/employee-mobile-frontend/types/index.ts, frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
=> Fix preschool club text in employee mobile

keycloak/Dockerfile, keycloak/evaka-logging/pom.xml, keycloak/evaka-review-profile/pom.xml
=> Upgrade to Keycloak 22.0.4

service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
=> Remove an unused async job

.github/workflows/build.yml
=> Keep maintenance page index.html

apigw/README.md, compose/README.md, compose/compose-e2e, compose/compose-integration, compose/db.sh, compose/docker-compose.e2e.yml, compose/test-e2e, keycloak/README.md, keycloak/compose-keycloak, service/README.md
=> Use compose v2

frontend/src/employee-frontend/components/child-information/Placements.tsx, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Grant ECES permission to:
- add and update placements
- remove future placements
- add, update and remove service needs
- add, update and remove daycare groups
- view placement guarantee report
Changes OK for Tampere, Turku
ECES role not in use in Espoo, Oulu
=> Expanded ECES access to reports, groups, placements and service needs

frontend/src/e2e-test/specs/5_employee/child-information-assistance.spec.ts, frontend/src/lib-common/generated/action.d.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceController.kt, service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
In daycare
- STAFF, SUPERVISOR sees only current and future assistance info for child in same unit
- VEO sees also past info for child in same unit
- Admin sees all
In preschool same rules, and
- VEO sees only preschool period assistance info, not earlier
=> Fix assistance acl

frontend/src/citizen-frontend/applications/editor/ApplicationFormClub.tsx, frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx, frontend/src/citizen-frontend/applications/editor/ApplicationFormPreschool.tsx, frontend/src/citizen-frontend/applications/editor/unit-preference/SiblingBasisSubSection.tsx, frontend/src/citizen-frontend/applications/editor/unit-preference/UnitPreferenceSection.tsx, frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx, frontend/src/citizen-frontend/calendar/CalendarNotifications.tsx, frontend/src/e2e-test/specs/0_citizen/citizen-income.spec.ts
This paves way for the upcoming v5 which removes the `onSuccess` callback.
=> Fix react-query deprecations

.github/workflows/e2e.yml
=> Build e2e compose images on master pushes

frontend/src/citizen-frontend/income-statements/ChildIncomeStatementEditor.tsx, frontend/src/citizen-frontend/income-statements/ChildIncomeStatementView.tsx, frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx, frontend/src/citizen-frontend/income-statements/api.ts, frontend/src/citizen-frontend/income-statements/queries.ts, frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx, frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx, frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx, frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsent.tsx, frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx, frontend/src/employee-mobile-frontend/messages/queries.ts, frontend/src/employee-mobile-frontend/messages/state.tsx, frontend/src/lib-common/query.ts
=> Add `queryOrDefault` helper

service/evaka-bom/build.gradle.kts, service/owasp-suppressions.xml
=> Upgrade Tomcat to fix CVE

apigw/Dockerfile
=> Upgrade apigw's node to fix vulnerabilities

apigw/Dockerfile, frontend/Dockerfile
=> Update Node images Debian to Bookworm/12

frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
=> fix confirm text when completing pedagogical document

.github/workflows/build.yml, compose/README.md, compose/e2e/playwright.Dockerfile, compose/e2e/playwright/bin/run-tests.sh
=> Install Playwright browsers using yarn

service/src/main/kotlin/fi/espoo/evaka/varda/old/VardaUpdateService.kt
PT010 error means that we tried to update information for a PAOS organization which we do not have access to. This happens for example with closed PAOS units. As this only concers this specifix unit, continue updating the rest of the service needs to varda.
=> Do not stop update process on PT010 error.

frontend/src/citizen-frontend/messages/ThreadList.tsx, frontend/src/employee-mobile-frontend/messages/MessagesPage.tsx, frontend/src/employee-mobile-frontend/messages/state.tsx, frontend/src/lib-components/OnEnterView.tsx
Previously it was not possible to see older messages at all.
=> Infinite scroll for employee mobile messages

frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Part4 and hopefully last one: adds accordions to assistance report based on area and unit selections.
=> Assistance report improvements part4

frontend/src/employee-frontend/components/common/Filters.tsx
=> Fix income statement filter customizations

service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiDatabaseTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTestHelpers.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiQueries.kt, service/src/main/kotlin/fi/espoo/evaka/koski/KoskiUpdateService.kt, service/src/main/kotlin/fi/espoo/evaka/koski/Oppija.kt, service/src/main/kotlin/fi/espoo/evaka/placement/PlacementType.kt, service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt, service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt, service/src/main/resources/db/migration/R__koski_views.sql, service/src/main/resources/db/migration/V364__koski_model_updates.sql, service/src/main/resources/migrations.txt, service/src/test/kotlin/fi/espoo/evaka/koski/KoskiTest.kt
=> Koski refactoring, fix preparatory qualification rules, send SPECIAL_SUPPORT

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/FuturePreschoolersReportTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/FuturePreschoolersReport.kt
Only include currently open groups in the report
=> Fix the group report for the future preschoolers

service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/ActionRule.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGlobalRole.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsEmployee.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsMobile.kt, service/src/main/resources/db/migration/R__acl_views.sql
=> Improve performance of access control checks

service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
=> add null check to child document answers to validate input

service/src/main/kotlin/fi/espoo/evaka/varda/VardaService.kt, service/src/main/kotlin/fi/espoo/evaka/varda/old/VardaUpdateService.kt
If evaka tries to update varda information to a PAOS unit it has (no longer) update rights, continue adding other information to varda
=> Skip Varda PO003 errors

frontend/src/e2e-test/specs/5_employee/placement-guarantee-report.spec.ts, frontend/src/employee-frontend/components/reports/PlacementGuarantee.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/reports/PlacementGuaranteeReportControllerTest.kt, service/src/main/kotlin/fi/espoo/evaka/reports/PlacementGuaranteeReportController.kt
Report should include children who has placement guarantee after the given date and has no placement on the given date.
=> Fix placement guarantee report query

frontend/src/citizen-frontend/messages/queries.ts, frontend/src/citizen-frontend/messages/state.tsx, frontend/src/employee-mobile-frontend/messages/queries.ts, frontend/src/employee-mobile-frontend/messages/state.tsx, frontend/src/lib-common/query.ts
Add a better API for implementing infinite scrolling with eVaka's pagination conventions.
=> Paged infinite query

frontend/src/employee-frontend/components/employees/EmployeeList.tsx, frontend/src/lib-common/generated/api-types/pis.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
=> display group acl in user listing

service/evaka-bom/build.gradle.kts, service/gradle/libs.versions.toml
=> Fix CVE-2023-44483

frontend/src/e2e-test/pages/employee/vasu/vasu.ts, frontend/src/e2e-test/specs/5_employee/curriculum-document.spec.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt, service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
https://github.com/espoon-voltti/evaka/pull/3381 added vasu copy from duplicate which hasn't been working because duplicate might be created after vasu has been closed. Fix like https://github.com/espoon-voltti/evaka/pull/4194 & https://github.com/espoon-voltti/evaka/pull/4215.
=> Add latest vasu to be visible from duplicate of

frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx, frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx, frontend/src/e2e-test/pages/citizen/citizen-child-income.ts, frontend/src/e2e-test/pages/citizen/citizen-income.ts, frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx, frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx, frontend/src/lib-customizations/espoo/citizen.tsx
Most of the changes only for Espoo
=> EVAKA-4838: income statement text updates

frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx
Looks like I missed these in the first PR :(
=> Fix remaining group notes queries

frontend/src/e2e-test/specs/5_employee/assistance-need-decisions-report.spec.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AssistanceNeedDecisionAccessControlTest.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
- Fix assistance decision ACL rights
- Give VEO same ACL rights as admin
=> Assistance decision acl changes

service/src/integrationTest/kotlin/fi/espoo/evaka/PureJdbiTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationQueriesSmokeTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/espoo/bi/EspooBiJobTest.kt, service/src/main/kotlin/fi/espoo/evaka/shared/config/DatabaseConfig.kt, service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
For temporary development / debugging only! Don't leave these in committed code 🤨
=> Add API for logging the final SQL of a query

frontend/src/lib-common/generated/api-types/shared.ts, service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/EmployeeFeatures.kt
=> Remove old assistance model flag

frontend/src/citizen-frontend/navigation/DesktopNav.tsx, frontend/src/citizen-frontend/navigation/shared-components.tsx
Menu was not accessible for screen reader / braille terminal users.
Screen reader software is able to announce opened sub-menus, selected items, strong authentication requiring pages etc.
=> Improve navigation a11y

frontend/init-pro-icons.sh
=> Remove init-pro-icons.sh script

frontend/src/employee-mobile-frontend/messages/ThreadView.tsx
=> Show sender and recipient names correctly when children is empty

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
=> Fix time dependant tests

frontend/package.json, frontend/src/citizen-frontend/messages/ThreadListItem.tsx, frontend/src/employee-frontend/components/placement-draft/PlacementDraftRow.tsx, frontend/src/employee-frontend/components/unit/unit-reservations/attendance-elements.tsx, frontend/src/lib-components/atoms/buttons/IconButton.tsx, frontend/src/lib-components/messages/ThreadListItem.tsx, frontend/yarn.lock
=> Bump styled-components from 5.3.11 to 6.1.0

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> Enable document templates in espoo production

frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- add sorting to area & unit selectors.
- add "show zero rows" filter.
=> Assistance report improvements part5

frontend/src/lib-common/utils/idleTracker.ts, frontend/src/lib-common/utils/useRestApi.ts
=> Deprecate some old request-making helpers

frontend/src/e2e-test/specs/5_employee/assistance-need-decisions-report.spec.ts, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
-Instead of VEO seeing all assistance info, only show own units info
-Allow service worker to also read assistance factor
=> Assistance info ACL changes

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
Frontend allowed a citizen to send message to multiple groups, but validation in the service failed. Implement the frontend validation logic to service, too.
=> Fix new message recipient validation in service

frontend/src/employee-mobile-frontend/settings/NotificationSettings.tsx, frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
=> Fix frontend PR conflict

frontend/src/e2e-test/dev-api/index.ts, frontend/src/e2e-test/dev-api/types.ts, frontend/src/e2e-test/pages/mobile/staff-page.ts, frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts, frontend/src/employee-mobile-frontend/App.tsx, frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendanceEditPage.tsx, frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx, frontend/src/employee-mobile-frontend/staff-attendance/api.ts, frontend/src/employee-mobile-frontend/staff-attendance/queries.ts, frontend/src/lib-common/generated/api-types/attendance.ts, frontend/src/lib-components/molecules/PinInput.tsx, frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts, frontend/src/lib-customizations/espoo/featureFlags.tsx, frontend/src/lib-customizations/types.d.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
New feature under experimental feature flag for testing.
=> Add mobile staff attendance edit

frontend/src/employee-frontend/api/daycare.ts, frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx, frontend/src/employee-frontend/components/child-information/queries.ts, frontend/src/lib-common/generated/api-types/daycare.ts, service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt, service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
=> assistance decision unit can be any non-club unit

frontend/src/lib-customizations/espoo/featureFlags.tsx
=> espoo: enable voucher value decision ignored status

frontend/src/employee-mobile-frontend/messages/state.tsx
=> HOTFIX: Load messaging accounts correctly in personal mobile devices

service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt
=> Fix SFi error message check

service/src/main/kotlin/fi/espoo/evaka/reports/UnitsReport.kt
=> fix cost center nullability in unit report

frontend/src/e2e-test/pages/mobile/staff-page.ts, frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts, frontend/src/e2e-test/utils/page.ts, frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendanceEditPage.tsx, frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx, frontend/src/employee-mobile-frontend/staff-attendance/components/StaffMemberPageContainer.tsx, frontend/src/lib-components/atoms/dropdowns/Select.tsx, frontend/src/lib-components/atoms/form/TimeInput.tsx, frontend/src/lib-components/molecules/PinInput.tsx, frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts, service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
https://github.com/espoon-voltti/evaka/pull/4344 part2
=> Improve mobile staff attendance edit

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/VoucherValueDecisionGeneratorV2.kt
=> Voucher value v2 generator fixes

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt, service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
=> Commit transaction correctly when pin is invalid

frontend/src/employee-frontend/components/employees/EmployeeList.tsx, frontend/src/lib-common/generated/api-types/pis.ts, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
Helps tracking problems with integrations using employee number.
=> Add employee number to employees list

service/src/integrationTest/kotlin/fi/espoo/evaka/childimages/ChildImageTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/utils/Hex.kt, service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImage.kt, service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImageController.kt, service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pis/service/MergeService.kt
=> Handle child images when merging persons

frontend/src/employee-frontend/components/reports/EndedPlacements.tsx, frontend/src/employee-frontend/components/reports/StartingPlacements.tsx
=> Include the next year in starting and ended placement report filters

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
=> Change `FINANCE_STAFF` role name

service/src/integrationTest/kotlin/fi/espoo/evaka/s3/DocumentServiceIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt, service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt, service/src/main/kotlin/fi/espoo/evaka/s3/DocumentService.kt
Removes the requirement to add this bean in every customization.
=> Add document service bean by default

frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
=> Avoid page crash on interim form invalidity

frontend/src/employee-mobile-frontend/messages/state.tsx, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt, service/src/main/kotlin/fi/espoo/evaka/Audit.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageAccountQueries.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt, service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
=> Messaging related service enhancements

frontend/src/employee-mobile-frontend/child-attendance/actions/MarkReservations.tsx
=> Fix prettier

frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx, frontend/src/lib-common/generated/api-types/pis.ts, service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonControllerIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/PersonQueriesIntegrationTest.kt, service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/VTJBatchRefreshServiceIntegrationTest.kt, service/src/main/kotlin/fi/espoo/evaka/pis/ParentshipQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt, service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt, service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt, service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt, service/src/main/kotlin/fi/espoo/evaka/varda/VardaQueries.kt, service/src/test/kotlin/fi/espoo/evaka/vtjclient/service/VtjClientServiceTest.kt, service/src/test/kotlin/fi/espoo/evaka/vtjclient/service/persondetails/VTJPersonDetailsServiceTest.kt
1. copy varda person oid if exists to oph person oid (which is used for other integration)
2. hide duplicate button if person is already duplicate
=> Duplicate person improvements

frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
=> Show all daycare groups

frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx, frontend/src/lib-common/generated/api-types/assistance.ts, frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx, frontend/src/lib-customizations/espoo/employee.tsx, service/src/main/kotlin/fi/espoo/evaka/assistance/Assistance.kt, service/src/main/resources/db/migration/V370__alter_child_discussion_assistance_measure_types.sql, service/src/main/resources/migrations.txt
Added new child discussion related options to other assistance measure types. Child discussion data will be migrated to other assistance measures.
=> Added child discussion options in other assistance measure types

service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
=> Fix mobile occupancy coefficient

frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts, frontend/src/employee-mobile-frontend/staff-attendance/StaffMarkArrivedPage.tsx
=>  Fix staff attendance arrival time validation

frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx
Show daily service times on first row when multiple reservations.
=> Fix calendar daily service times display
