- frontend/src/citizen-frontend/navigation/Header.tsx
- frontend/src/citizen-frontend/navigation/MobileNav.tsx
> Hide header/footer from vasu print view

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt
In our codebase it's always a bug to return NULL for a non-nullable type, even if the type is primitive.
> Disable SQL null coalescing for primitive types

- keycloak/theme/evaka/login/theme.properties
- proxy/files/etc/nginx/conf.d/nginx.conf.template
Fixed error "Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Montserrat:200,300,400,700|Open+Sans:300,400,600,700' because it violates the following Content Security Policy directive".
Also fixes CSS file 404 error.
> Fix keycloak fonts

- frontend/webpack.config.js
With `display: 'fullscreen'` on Samsung phones the PWA browser window does not resize properly when the on screen keyboard is shown. That means that any inputs that are at the bottom of the screen are hidden behind the keyboard when focused.
> Fix employee mobile inputs staying behind Samsung on screen keyboard

- frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx
- frontend/src/lib-common/generated/api-types/messaging.ts
- service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
Aggregate the data in the database. Use a single `Message` type instead of multiple intermediate types. 
The SQL query in `getSentMessage()` is now almost identical with `getThreadMessages().`
> Simplify and speed up reading of a sent message

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
This adds new feature config to disable "partial absence thresholds" functionality which seems pretty Espoo-specific with many hard coded arrival/departure times etc.
> Add partial absence thresholds feature config

- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Replace the dreadful `generate_series` + `realized_placement_one` combo with more CPU-friendly reads from DB and data mangling in the Kotlin side.
Add integration tests for `AttendanceReservationsController`.
> Attendance reservations speedup

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementType.kt
Invoice generation assumed that families with children that are split between two fridge parents would still have two fee decisions, one for each parent. This caused some of the children not getting an invoice if their parent was not the head of family on a fee decision.
> Fix children not being invoiced when they are split between parents

- frontend/src/employee-frontend/components/reports/VoucherServiceProviders.tsx
Consider three units in voucher service providers unit report: Area A Unit A, Area B Unit B and Area A unit C. Currently if there is no area filter selected the units are grouped by area and then sorted (ACB). Instead it should be ordered by name only when there is no area filter. Thus the correct order of units should then be ABC
> Do not sort by area

- frontend/src/citizen-frontend/applications/api.ts
- frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
- frontend/src/lib-common/api-types/application/ApplicationFormData.ts
- frontend/src/lib-common/generated/api-types/application.ts
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Applications page does not work at all if a parent has a foster child without a SSN. Previously citizens could make applications only for their own dependants who always had a SSN.
> EVAKA-HOTFIX support applications for foster children without a SSN

- frontend/src/citizen-frontend/decisions/api.ts
- frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponse.tsx
- frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponseList.tsx
- frontend/src/employee-frontend/api/applications.ts
- frontend/src/employee-frontend/api/person.ts
- frontend/src/employee-frontend/components/person-profile/PersonDecisions.tsx
- frontend/src/lib-common/generated/api-types/decision.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/Decision.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
Citizens would previously see decisions waiting mailing in their decisions page. Accepting or rejecting those decisions would still fail. Hide them until they are marked as sent.
> Hide decisions waiting mailing from citizen

- frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx
- frontend/src/employee-mobile-frontend/components/messages/ThreadView.tsx
- frontend/src/lib-common/generated/api-types/messaging.ts
- service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Message copies cannot be replied to anyway so hide the message reply input.
> Hide mobile message input when message is a copy

- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt
`READ_PEDAGOGICAL_DOCUMENT_ATTACHMENT` action was missing a condition for foster parents.
> Fix pedagogical document attachment access control check for foster parents

- service/src/main/kotlin/fi/espoo/evaka/pis/service/FamilyInitializerService.kt
User provided SSNs are already validated when submitting applications but sometimes valid SSNs do not match anyone in VTJ so instead of failing the whole family initialization job log an error that can be handled manually later.
> Log errors instead of failing whole family initialization

- frontend/src/citizen-frontend/children/ResponsiveWholePageCollapsible.tsx
- frontend/src/citizen-frontend/children/sections/pedagogical-documents/PedagogicalDocumentsSection.tsx
- frontend/src/citizen-frontend/children/sections/vasu-and-leops/VasuAndLeopsSection.tsx
- frontend/src/lib-components/molecules/modals/BaseModal.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
The placement termination modal had a lower z-index than the modal for the placement termination section so the `ResponsiveWholePageCollapsible` component's z-index is lowered.
Also, show a text indicating that a child has no pedagogical documents and show the curriculum sharing info only if a child has curriculums.
Before:
After:
Before:
After:
> EVAKA-HOTFIX placement termination in mobile

- frontend/package.json
- frontend/src/lib-components/molecules/date-picker/DatePicker.tsx
- frontend/src/lib-components/molecules/date-picker/DatePickerDay.tsx
- frontend/yarn.lock
The built-in styles in the new version are minimal. I tried to make it look mostly like the old one but with eVaka colors.
**Old:**
**New:**
> Upgrade react-day-picker

- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/citizen-frontend/calendar/utils.ts
Fix the `getEarliestReservableDate` function that would always return `LocalDate.todayInSystemTz()` as reservable days are always in the future.
> Fix reservation modal default start date

- frontend/src/employee-frontend/components/messages/GroupMessageAccountList.tsx
- frontend/src/employee-frontend/components/messages/MessageBox.tsx
Update employee unread messages count visual:
old
new
Also fix group account message boxes not being expanded by default if they have any unread messages.
> EVAKA-4667 employee unread messages icons

- frontend/src/employee-frontend/App.tsx
- frontend/src/lib-common/api-types/employee-auth.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
- service/src/main/resources/dev-data/employees.sql
- Add MESSAGING role to employee management roles
- Add a messaging user to dev env test users
- Direct user with MESSAGING role to messages page by default
> EVAKA add messaging role to user management ui

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionSearchTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
- If both area filter and starting child filter was on, the generated SQL was invalid
- Add unit tests for both fee decision search and voucher value decision search
> Fix finance decision search query filters

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerator.kt
- service/src/main/resources/db/migration/V286__fee_decision_child_unique_constraint.sql
- service/src/main/resources/migrations.txt
Add a database constraint that makes sure a child is included only once on a fee decision. Fix a bug that caused children being duplicated on sent fee decisions. Make sure that automatic fee decision validity updates work for a family's both parents if their decisions used to be split into two in the past.
> Fix fee decision children being added to sent decisions

- frontend/src/employee-frontend/api/staff-attendance.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceExternalPersonModal.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/attendanceEditState.spec.ts
- frontend/src/lib-common/generated/api-types/attendance.ts
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
A previous PR accidentally removed the possibility to edit attendance data of externals. This PR brings it to the same modal that's used for staff.
All tests are missing ~and the frontend has rough edges still~ (fixed), but these will be fixed in the next PR because we need this to unblock production deployments.
> External staff attendance editing

- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
This fixes a bug where only a single child's name was shown in messages regarding multiple or all children of a guardian. Now all relevant children's names are shown.
> Ensure the names of all children are displayed in messages

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts
- frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx
Attendances of a person are now shown in the realtime staff attendance table even if the person is not staff for that group (any more).
While at it, change the staff attendance edit modal to use preselect the current group when adding a new attendance record.
> Include attendances of non-group-staff in group info

- frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
This way, IntelliJ IDEA detects the test cases correctly and they can be run from the IDE.
> Use `describe.each()` instead of manual looping

- evaka-bom/build.gradle.kts
- service/owasp-suppressions.xml
- Upgrade snakeyaml to 1.33
- Add a suppression for snakeyaml CVE-2022-41854, which does not concern us as we do not parse untrusted YAML files
> Snakeyaml CVE suppression

- frontend/src/e2e-test/pages/mobile/staff-page.ts
- frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
- frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
- frontend/src/employee-mobile-frontend/components/staff-attendance/StaffMarkDepartedPage.tsx
- frontend/src/employee-mobile-frontend/utils/staffAttendances.ts
- Use correct time parse function
- Use 5min tolerance instead of 15 on departure
- Show all present -type attendances on desktop unit group calendar + test
> Evaka 4598 staff attendance fixes

- frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
- Avoid overflowing the content area on the right side by removing a bit of padding and making the table scale with the window.
- Make the table header sticky, instead of each column header separately to avoid content flashing behind the header
Before:
After:
> Fix the looks of the applications list table

- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Decision makers already had the permission to read the report but not to perform any actual actions on it -> remove the need for DIRECTOR role for other actions too
> Update default permissions for assistance need decisions report

- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Special education teacher should see groups only from group_acl.
This default should work for Espoo, Tampere & Oulu so no overrides needed anymore.
> Fix special education teacher daycare group messages

- service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/ActionRule.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGlobalRole.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsEmployee.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsMobile.kt
equals/hashCode on the query itself was fine in many cases, but doesn't work well when the query itself is parameterized. Now that queries are defined using functions that *return QuerySql* instead of actually executing a query, we can use the returned QuerySql object as the cache key. This conveniently captures all information about the query, including its parameters, so caching works even for parameterized queries.
The only downside is slightly lower performance, because we need to create a QuerySql twice (one for the cache check, one for the query execution). This can be improved later by changing the Query abstraction slightly if necessary.
> Use a cache key in access control query caching

- frontend/src/citizen-frontend/utils.ts
- frontend/src/lib-components/atoms/Main.tsx
Remove `tabindex="-1"` from `<main>`. This has the effect that `<main>` won't receive focus events, and thus fixes the premature closing of the <DatePicker> calendar dialog on Safari.
Removen `tabindex` from `<main>` shouldn't break anything, as `tabindex="-1"` means that the element can be focused programmatically or by clicking, but not by keyboard. I don't see why this would be required. See the [MDN article on `tabindex`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex).
Also remove some dead code.
> Fix using the `DatePicker` calendar dialog with mouse on Safari

- service/src/main/resources/db/migration/R__acl_views.sql
The `ACTIVE` status means that the application has been accepted. In this state, employees shouldn't get permission through the application anymore, because the placement gives it the the correct employees.
The PR also refactors the date comparisons to be in a more natural order, at least to my brain 🧠
> Remove permissions to a child via an active application

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaResetService.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- Use new endpoint /v1/lapset/{id}/delete-all to delete all child data (https://virkailija.opintopolku.fi/varda/julkinen/swagger)
> Evaka fix varda use child deleteall

- frontend/src/lib-common/money.spec.ts
- frontend/src/lib-common/money.ts
Values were being parsed and stored correctly, only the formatting was off.
> Fix formatCents leaving out minus sign with values less than euro

- frontend/src/e2e-test/pages/employee/applications/application-edit-view.ts
- frontend/src/e2e-test/pages/employee/applications/application-read-view.ts
- frontend/src/e2e-test/specs/5_employee/paper-application.spec.ts
- frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
Previously the due date set at paper application creation would always get overwritten when the application is saved (or technically "sent").
> Calculate application due date only if not already set

- evaka-bom/build.gradle.kts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- Update thread participants only if thread still exists
- Send message email notification after undo period and only if the message still exists
> EVAKA do not send email notifications for undone messages

- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
The suggested first reservable date in the reservation modal suggested the first day of a holiday period in the following case:
- A holiday period is defined to start at a date later than today
- The deadline for reservations during the holiday period was earlier than today
- A reservation has been made for the kids, starting today and ending at a date after the end of the holiday period
---> The reservation modal suggested the first date of the holiday as the next reservable date.
This is now fixed by checking that the suggestion is an actual reservable day, which holidays are not.
> Make sure to only suggest actually reservable days

- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
Earlier all placements were inserted such that any existing placement would be trimmed from the ends, or split into two to make room for the new placement. This is still the case for all other kinds of placements, but CLUB placements only trim existing placements from the end (if they start before the new CLUB placement) and cancel any placement (or part of a placement) that would occur after the new CLUB placement has ended.
> Cancel all placements after an inserted CLUB placement

- service/gradle.properties
This matches our actual application, and fixes non-transactional migrations that use CONCURRENTLY. Without this fix running `./gradlew flywayMigrate` hangs forever due to a deadlock.
> Use session locks with Flyway Gradle plugin

- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/DatabaseConfig.kt
By default, future migrations (= in flyway_schema table but not in code) are ignored. This makes it possible to attempt a rollback to a different version even if the old version doesn't have all the migrations.
If we configure future migrations to not be ignored, this makes it possible to detect when data and code are out of sync, which is useful in some special scenarios.
> Allow failing on future Flyway migrations

- compose/db-integration-test/Dockerfile
- compose/db/Dockerfile
The pgextwlist psql extension does not work with 14-alpine3.17
> Use 14-alpine3.16 as db base image

- service/owasp-suppressions.xml
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageAccountQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
Previously an ex-pair that both were recipients of a message and had new families would get copies of their ex-partner's messages. The problem was basically non existant before municipal messaging.
Now bulletins are not grouped by family as they cannot be replied to so grouping has no benefits. This is to prevent multiple copies of bulletins in cases where all the adults in a family do not have the right to see all of their children's messages.
> Make sure people do not see other people's children in their messages

- frontend/src/citizen-frontend/navigation/Header.tsx
ChildrenContext and ApplicationsContext already refresh the unread counts automatically when the user state changes, so there's no need to do this again in the Header component.
> Don't refresh unread counts twice upon page load

- frontend/src/citizen-frontend/messages/MessageEditor.tsx
- frontend/src/e2e-test/pages/citizen/citizen-messages.ts
- frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
- frontend/src/lib-common/generated/api-types/messaging.ts
- frontend/src/lib-components/molecules/MessageReplyEditor.tsx
- frontend/src/lib-components/molecules/ToggleableRecipient.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- change the UI so that children are selected first and then receivers
- when selecting multiple children, only receivers that are related to *all selected children* are valid
- allow citizen to choose secondary recipients: if the citizen is a guardian, this means other guardians, and if the citizen is a foster parent, this means other foster parents. A foster parent can never select a guardian, and vice versa.
> [EVAKA-4604] Allow citizen to choose secondary recipients when sending a new message

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/auth/AclIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AccessControlTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/Tracing.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/JwtToAuthenticatedUser.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/SecurityConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
- access control operations start a new span in Datadog traces. This makes it easier to understand the total duration of the whole access control operation, including all database queries *and* normal CPU work
> Add tracing to access control operations

- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
Missing group placements showed placements from before 1.3.2020 after my previous refactoring.
> Fix missing group placements min date

- frontend/src/employee-frontend/components/reports/PlacementSketching.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
This also enables lib-customization to override those texts, e.g. in Tampere connected daycare is 'Täydentävä', not 'Liittyvä'.
> Fix placement sketching report csv header localization

- service/src/main/kotlin/fi/espoo/evaka/reports/VardaErrorsReport.kt
Use the last reset as the age of the error in varda errors report instead of the first reset
> Show latest reset in varda errors report

- frontend/src/employee-frontend/components/reports/PlacementCount.tsx
Replace decimal separator `.` to `,` in calculated CSV report values to enable easier Excel processing for FI users.
> Placement count report csv decimal separator fix

- service/owasp-suppressions.xml
> Suppress CVE-2022-41915 due to fix being misidentified as vulnerable

- apigw/src/shared/routes/auth/saml/index.ts
passport-saml typings claim req.user can be optional, but this is not true in practice
> Don't call logout when req.user is undefined

- frontend/src/citizen-frontend/children/sections/consents/ChildConsentsSection.tsx
- frontend/src/citizen-frontend/children/sections/pedagogical-documents/PedagogicalDocumentsSection.tsx
- frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/VasuPage.tsx
- frontend/src/citizen-frontend/decisions/assistance-decision-page/AssistanceDecisionPage.tsx
- frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponse.tsx
Extract the mutation function from useMutation/useMutationResult return value instead of passing the return value around as-is.
> HOTFIX: Avoid infinite loop caused by mutation in `useEffect`

- frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
Fix a bug where the previous attendance of an external staff member was cleared when creating a new attendance record.
> HOTFIX: Allow multiple attendances for external

- service/src/integrationTest/kotlin/fi/espoo/evaka/ServiceNeedTestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
The maximum fee for contract days should not grow bigger than the max fee for the default placement (full days). This is currently in place only for PRESCHOOL_DAYCARE and PREPARATORY_DAYCARE placements.
> Don't allow fees due to surplus attendance grow too big

- evaka-base/dd-jmxfetch/conf.yaml
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunnerTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobRunnerTest.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
- service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiAsyncJobs.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobPool.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/AsyncJobConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaResetService.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
This makes the runner implementation slightly more complicated, but usage is simpler because we no longer need to inject multiple runners in tests or real code, or care about which runner to call specifically. The pool concept also enables some future possibilities (e.g. *global* concurrency limit across all evaka-service instances).
> Move from N async job runners model to 1 runner, N pools

- frontend/src/citizen-frontend/messages/api.ts
- frontend/src/citizen-frontend/messages/state.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/resources/db/migration/V292__message_sent_nullable.sql
- service/src/main/resources/migrations.txt
When an employee sends a message, there's a period during which the message sending can be undone. This was implemented by adjusting message state in the db in an async job that was scheduled to run after the undo period expires.
This PR fixes two problems:
- The citizen saw unread message count bubble as soon as the employee hit the send button even _before the undo time expired_
- If the message was a reply, the citizen saw that the thread contained unread messages, and saw the message by opening the thread after the undo period expired. _The thread moved to the top of the list only after the async job was run._
After this PR, both the unread count bubble and the message (new message or reply) are visible only after the async job has run.
Keep `message`'s `sent_at` timestamp as `NULL` …
> Fix message visibility during undo period

- frontend/src/lib-components/Notifications.tsx
- frontend/src/lib-components/i18n.tsx
- frontend/src/lib-customizations/defaults/components/i18n/en.tsx
- frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
The toast is shown in all the 3 frontends.
In employee mobile it looks like this:
> Show a warning when there's no internet connection

- keycloak/Dockerfile
- keycloak/evaka-logging/pom.xml
- keycloak/evaka-review-profile/pom.xml
- Update Evaka Keycloak to version 20.0.3.
> VP-778: Update Evaka Keycloak to version 20.0.3.

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt
Before this change, blocked guardians were able to see the decision count in a notification bubble, and the decision data also ended up in the browser in a HTTP response (but was not shown in the UI).
> Hide decisions from blocked guardians

- apigw/src/enduser/__tests__/csrf.ts
- apigw/src/shared/__tests__/saml-slo.ts
- apigw/src/shared/auth/ad-saml.ts
- apigw/src/shared/auth/suomi-fi-saml.ts
- apigw/src/shared/dev-api.ts
- apigw/src/shared/test/gateway-tester.ts
The custom types didn't provide any type safety since we just did a type assertion and assumed the types were correct. Embrace the unknown typing instead, and validate/cast the data.
> Replace weak custom Profile types with validation code

- frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
- service/src/main/resources/db/migration/V293__staff_attendance_realtime_index.sql
- service/src/main/resources/migrations.txt
Allow arrival after a non work departure.
Example: If employee departs 1400, allow arriving 1500. This leaves a gap in the attendance data between 14-15
> Allow arrival after a departure

- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/SystemControllerTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
We are going to create employees with employee numbers from integration, and on first login to eVaka external id should be set correctly.
> Fix null external id on first login

- frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx
- frontend/src/employee-mobile-frontend/child-attendance/api.ts
- frontend/src/employee-mobile-frontend/child-info/AttendanceChildPage.tsx
- frontend/src/lib-common/generated/api-types/attendance.ts
- frontend/src/lib-components/atoms/RoundIcon.tsx
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- Adds a medium sized chip to mobile child list item and a large sized one to child detailed page depicting the child's age
- Additional styling changes to enable word break in order to solve pre-existing issues in child list item spacing and responsiveness
- An additional size for the mobile icon to lower font size for 2-digit ages
> Mobile age chip

- frontend/src/e2e-test/pages/employee/messages/messages-page.ts
- frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts
- frontend/src/employee-frontend/api/person.ts
- frontend/src/employee-frontend/components/ApplicationPage.tsx
- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/lib-components/employee/messages/MessageEditor.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Prefills the recipient and subject line for messages sent by service workers. Also removes some potentially slow queries introduced in the previous PR, as they are now unnecessary.
> EVAKA-4694 Prefill message and recipient selector

- frontend/src/employee-frontend/api/unit.ts
Returning Promise<Result<T>> but then rejecting the promise resulted in stuck spinners and uncaught promise errors
> Add missing Failure wrapping to some API calls

- apigw/src/shared/auth/ad-saml.ts
- apigw/src/shared/config.ts
Turku uses ADFS instead of AzureAD. Hardcoded userId (objectidentifier claim) is not available in ADFS. NameIdFormat by default is unspecified in ADFS. Therefor made both configurable through environment variables AD_USER_ID_KEY, AD_NAME_ID_FORMAT.
Turku ADFS encrypts SAML responses. Added environment variable to be able to define passport to decrypt responses, AD_DECRYPT_ASSERTIONS
Old hardcoded values are used as defaults. Should not require any changes from other cities.
> SAML nameIdFormat and userId configurable in AD SAML messages for apigw

- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
- Preschool start date was used for both preschool and preschool connected daycare despite the application form having separate preferred start dates for both
- Earlier functionality relegated to fallback if no preferred start date for connected daycare is found
> Changed placement plan draft creation to use correct preferred start date from application

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Tampere uses sometimes different units for preschool and preschool daycare placements. With this change we can get correct unit to preschool daycare placement after decision is accepted.
This also works for our family daycare placements because we already select correct unit in placement plan, which is then copied to decision.
> Add placement unit from decision support

- frontend/package.json
- frontend/src/citizen-frontend/children/ResponsiveWholePageCollapsible.tsx
- frontend/yarn.lock
Use just react-focus-lock for focus locking to avoid a fight between the managers when a modal is used when a focus lock is already active.
> Avoid focus lock manager fight

- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/template/EvakaTemplateProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/template/ITemplateProvider.kt
`Liittyvä_varhaiskasvatuspäätös` is wrong term for Tampere, and propably for others too.
Don't know if `TemplateProvider` was the correct interface for this...
> Refactor decision filename generator to support customization

- frontend/src/citizen-frontend/map/UnitListItem.tsx
I noticed hovering over a unit in the map view's unit list was a bit off.
Before: 
After:
> Fix map view unit list hover highlight

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
Also cap preschool/preparatory max price with `useContractDaysAsDailyFeeDivisor = false`
> Fix preschool/preparatory invoice capping with contract surplus days

- frontend/src/employee-frontend/components/common/CareTypeLabel.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/TerminatedPlacements.tsx
- frontend/src/employee-frontend/types/index.ts
- frontend/src/lib-common/generated/api-types/placement.ts
- frontend/src/lib-customizations/common.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
Change the placement type chip to "Liittyvä" when only connected daycare is terminated and preschool continues. It was "Esiopetus ja liittyvä varhaiskasvatus" which is obviously wrong in this case.
> Show terminated connected daycare correctly in unit groups page

- frontend/src/employee-frontend/components/reports/Decisions.tsx
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/reports/DecisionsReport.kt
- Fix counts of preschool/preparatory only decisions
- Add count of connected daycare only decisions
- Fix 1st/2nd/3rd/unfulfilled unit preference counts and total count (count applications, not decisions)
> Decision report fixes

- frontend/src/citizen-frontend/messages/MessagesPage.tsx
- frontend/src/e2e-test/pages/citizen/citizen-messages.ts
- frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts
- frontend/src/lib-common/api-types/vtjclient.ts
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/CitizenFeatures.kt
Citizens are no longer able to compose new messages if none of their children are actively placed.
> EVAKA-4694 Disallow sending new messages without actively placed child

- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlCitizen.kt
The messaging section was opened too early for citizens who received a message relating to an application. It was visible already before the received message was actually readable (before the undo grace period has passed). Now shows the messaging section only after a message actually is readable.
> EVAKA-4694 Show messaging section only once a message is readable

- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
Also, filter returned group acls by the unit instead of returning all group acls for each employee.
> Don't delete attendances in other units on upsert

- frontend/src/e2e-test/pages/employee/applications/application-edit-view.ts
- frontend/src/e2e-test/pages/mobile/list-page.ts
- frontend/src/e2e-test/pages/mobile/mobile-nav.ts
- frontend/src/e2e-test/specs/5_employee/feature-flag-preschool-application-service-need-option.spec.ts
- frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
- frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
- frontend/src/e2e-test/specs/6_mobile/staff.spec.ts
- frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
- frontend/src/employee-frontend/components/common/InputWarning.tsx
- Avoid a misclick by wait for a validation error to hide before attempting to click an element under it.
- Avoid `page.goto()` navigation in employee mobile
Also refactor navigation between pages in employee mobile e2e a bit.
> Fix flaky e2e tests

- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/components/reports/PlacementSketching.tsx
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/reports/PlacementSketchingReport.kt
Adds to placement sketching report:
- optional filtering by application sent date (date range)
- default filters produce same result as before changes
- 5 new columns:
- does child have additional information (allergy, diet or other) in application (yes/no)
- child moving date as provided in the application (and child details not restricted)
- child corrected address details as provided in the application (and child details not restricted)
- street address
- postal code
- city
> Additions to placement sketching report

- frontend/src/e2e-test/pages/employee/applications/application-read-view.ts
- frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts
- frontend/src/employee-frontend/components/application-page/ApplicationNoteBox.tsx
- frontend/src/employee-frontend/components/application-page/ApplicationNotes.tsx
- adds an icon to the notes created from an application
- removes the delete and edit buttons
> EVAKA-4694 Clearly mark application notes created from messages

- frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts
- frontend/src/employee-frontend/components/messages/MessageContext.tsx
Employees having both the service worker and messaging roles could not navigate from applications to the relevant message threads. This change fixes that issue.
> EVAKA-4694 Fix bug where you couldn't navigate to message threads

- frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx
- frontend/src/lib-common/api-types/reservations.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
Before this change, whenever a child was backup placed in another group in the same unit as their regular group, the week calendar would show a blank cell on that day. Now we show a message that the child is in another group instead.
> Show a message when a child is backup placed in the same unit

- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/components/reports/DuplicatePeople.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/reports/DuplicatePeopleReport.kt
Adds a conditional filter for the duplicate people report that can be used to ignore intentionally duplicated persons:
- visibility of filter is conditional on employee side feature flag `duplicatePerson`
- if feature is not activated, report functions as before and no filters are visible (all persons evaluated for duplicated data)
- if feature is activated, a filter for showing intentionally duplicated persons is visible and is set to false as default
> Duplicate people report changes to support intentional duplicates

- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
mapTo nullable + one() expects *one row* where the value is nullable.
mapTo non-nullable + singleOrNull() expects 0-1 rows where the value is not nullable.
The actual SQL query here uses the latter semantics
> Fix nullability in query

- service/src/main/resources/db/migration/V305__foreign_key_indexes.sql
- service/src/main/resources/migrations.txt
In our application we should usually have an index for most foreign keys, especially when person table is the key target. Very small tables were omitted, and also foreign keys pointing to tables where we never delete anything (e.g. evaka_user).
This should speed up nightly empty person cleanup operation, which currently consumes 100% database CPU for ~10 minutes in production.
> Add various foreign key indexes

- service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsBatchRefreshService.kt
The old queries didn't use an index (because we have no index on claimed_by = NULL) and had to search *all* async jobs. The correct way is to use the removeUnclaimedJobs query, which also has a "completed_at IS NULL" condition that can use a suitable index.
One of the queries also removed completed jobs, which is unnecessary since we have a separate cleanup mechanism that handles this.
> Use correct query to delete unclaimed async jobs

- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/components/reports/ManualDuplicationReport.tsx
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/reports/ManualDuplicationReportController.kt
Adds a new filter to the manual duplication report for selecting one of two view modes:
- show only cases where the person has already been duplicated
- show only cases without a duplicated person
> Improve manual duplication report

- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
- service/src/main/resources/db/migration/R__child_absences_functions.sql
Use daily service time as default reservation time on attendance reservation report
> Use daily service time as default reservation time on report

- service/Dockerfile
Old evaka-srv image: 362.93 MB
New evaka-srv image: 374.66 MB
> Use Temurin Java 17 Ubuntu 22.04 base image

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotifications.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/JobSchedule.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
- service/src/main/resources/db/migration/V311__income_notification.sql
- service/src/main/resources/migrations.txt
- Send a 2 week and a 1 week warning about income about to expire, and 0 day notification that income has expired
- Income is outdated if the end date is within 2 weeks of today AND today there is a placed child for the income person and the placement is invoiced and there is no invoice statement newer than 1 month and same kind income notification has not been sent during past month
> Outdated income statement notification email

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationSummaryIntegrationTests.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
Currently after citizen accepts (or rejects) decision, application disappears from unit supervisor UI. In Tampere unit supervisor should still see preschool application, even after the decision has been made. With this change and following override we are able to get correct list for unit supervisors at child page:
```
Action.Application.READ -> {
@Suppress("UNCHECKED_CAST")
sequenceOf(
HasUnitRole(UserRole.UNIT_SUPERVISOR).inPlacementPlanUnitOfApplication(onlyAllowDeletedForTypes = setOf(ApplicationType.PRESCHOOL)) as ScopedActionRule<in T>
)
}
Action.Child.READ_APPLICATION -> {
@Suppress("UNCHECKED_CAST")
action.defaultRules.asSequence() + sequenceOf(
HasUnitRole(UserRole.UNIT_SUPERVISOR).inPlacementUnitOfChild() as ScopedActionRule<in T>
)
}
```
> Child application summaries for unit supervisor

- apigw/src/enduser/app.ts
- apigw/src/enduser/mapRoutes.ts
- apigw/src/shared/config.ts
- frontend/src/citizen-frontend/map/api.ts
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- Move Digitransit API calls to apigw
- Use API key from the environment (Added to infra in https://github.com/espoon-voltti/evaka-infra/pull/657)
- Refactor to call mocked digitransit API (in dev-api) when run locally or in e2e tests
> Move Digitransit API calls to server and add API key

- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
If plan is 08:00 - 15:39 and arrival is 15:39 upkeep job tries to put departure to 15:39 which gives us error `staff_attendance_start_before_end`. This fixes it so departure will be then 20:00.
> Fix staff attendance upkeep when arrival is plan departure

- frontend/src/employee-frontend/api/applications.ts
- frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
- frontend/src/employee-frontend/components/applications/ApplicationsPage.tsx
- frontend/src/employee-frontend/types/application.ts
- frontend/src/lib-common/generated/api-types/application.ts
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Unit name sorting of paged application queries whether the unit name is from the top unit preference or the placement plan.
> Add sorting the application list by unit name

- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
Now uses unit language instead of head of family language.
> Use the unit language when generating voucher value decision pdfs

- frontend/src/e2e-test/pages/employee/child-information.ts
- frontend/src/e2e-test/specs/5_employee/child-information.spec.ts
- frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
- frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx
- frontend/src/lib-common/generated/api-types/daycare.ts
- frontend/src/lib-common/generated/api-types/pis.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/PersonQueriesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/ChildQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/ChildController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V316__move_language_at_home.sql
- service/src/main/resources/migrations.txt
- service/src/test/kotlin/fi/espoo/evaka/vtjclient/service/VtjClientServiceTest.kt
- service/src/test/kotlin/fi/espoo/evaka/vtjclient/service/persondetails/VTJPersonDetailsServiceTest.kt
- Move the `language_at_home` and  `language_at_home_details` columns from the `person` table to the `child` table
- API changed to reflect the above
- Move the language at home fields to the additional details section in the UI
> Allow employee to edit language at home info

- frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
-If user selects from staff attendance day modal an attendance type which requires selecting a group, and then switches to another that does not require a group, the group id must be removed
-Allow deleting an attendance without a group id
> Fix staff realtime attendance group handling

- frontend/webpack.config.js
The previous fix wasn't enough, but it worked as long as Sentry plugin wasn't used (= locally, pull requests). For some reason, the Sentry plugin injects some code when enabled, which broke things in our master build.
> Another fix for service-worker.js, broken by Sentry in master

- frontend/src/employee-frontend/components/vasu/sections/VasuEvents.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/vasu/fi.ts
- frontend/src/lib-customizations/defaults/employee/i18n/vasu/sv.ts
If one or more of the guardians have given permission to share the vasu / leops as stated in the document, their names are shown in the events section.
Nothing is shown before at least one guardian has given permission.
> EVAKA-4785 Show which guardian has approved vasu/leops

- frontend/src/lib-common/generated/language.ts
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/Languages.kt
Not present in ISO 639-1 / 639-2, but it's included in ISO 639-3.
> Add Dari language to ISO languages list

- frontend/src/citizen-frontend/applications/Applications.tsx
- frontend/src/citizen-frontend/applications/ChildApplicationsBlock.tsx
Moves the `AddButton` hiding logic for duplicated children up a level to prevent the creation of the entire child fragment for the same page.
> Hide duplicated children from applications block (citizen frontend)

- frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
The test no longer made any sense, because editing future attendances is not allowed. However, for some reason the test *worked* randomly
> Fix flaky E2E test

- proxy/files/etc/nginx/conf.d/nginx.conf.template
A previous fix tried to increase the limit in api gateway, where it had no effect because it only limited the *parsed request body* size, but parsing was disabled for multipart requests.
The actual current limit comes from nginx and its default (1 MB), which was used because the limit was only increased in the config for `/attachments` and not `/citizen/attachments`.
The true final limit is still 10 MB which evaka-service applies to all requests. These limits should probably be harmonized a bit more...
> Fix attachment size limit for citizens

- service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/MockKoskiServer.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/application/persistence/DatabaseForm.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiClient.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/JacksonConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/service/persondetails/MockPersonDetailsService.kt
- service/src/main/kotlin/fi/espoo/evaka/webpush/WebPush.kt
- service/src/test/kotlin/fi/espoo/evaka/identity/ExternalIdTest.kt
- service/src/test/kotlin/fi/espoo/evaka/shared/domain/HelsinkiDateTimeTest.kt
- service/src/test/kotlin/fi/espoo/evaka/varda/VardaUnitModelTest.kt
- service/src/test/kotlin/fi/espoo/evaka/varda/integration/VardaClientTest.kt
- expose a builder instead of the mapper. This lets different parts of the application configure *extra features* as needed, while still having good defaults
- enable Kotlin singleton support. For some reason this is disabled by default, and all singleton deserializations have been broken for a while
- deprecate defaultJsonMapper(). We no longer use it, but let's keep the deprecation for a while to avoid breaking other builds
- use JDBI Json support instead of instantiating a custom mapper in queries
> Unify and improve Jackson mapper configuration

- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
- service/src/main/resources/db/migration/R__koski_views.sql
- filter to remove persons that have at least one duplicate from Koski study right selection
- integration test to check that a study right is sent for the duplicate but not the original
> Hide the original child of a duplication case from Koski integration

- frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
- frontend/src/citizen-frontend/calendar/CalendarEventCount.tsx
- frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
- frontend/src/citizen-frontend/calendar/CalendarListView.tsx
- frontend/src/citizen-frontend/calendar/CalendarNotifications.tsx
- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/citizen-frontend/calendar/WeekElem.tsx
- frontend/src/citizen-frontend/calendar/api.ts
- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/DailyRepetitionTimeInputGrid.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/IrregularRepetitionTimeInputGrid.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/RepetitionTimeInputGrid.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/WeeklyRepetitionTimeInputGrid.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/form.ts
- frontend/src/citizen-frontend/calendar/utils.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
- frontend/src/lib-common/generated/api-types/reservations.ts
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
Show children in the calendar only on the days they actually are eligible for daycare.
Rules for eligibility:
- Placement exists
- Operation day in the placement's unit
- Not a holiday (unless placed to a 24/7 unit)
The image below shows an example (only Thu-Sun). 
Placements:
- **K**: normal unit
- **P**: week 1: 24/7 unit, week 2: no placement, week 3: normal unit
Calendar:
- Week 1: Holiday on 1.6. => **K** is no eligible, weekend => **K** is not eligible
- Week 2: **P** has no placement => not eligible
- Week 3: **P** is in a normal unit => not eligible in the weekend
> Make citizen calendar more accurate

- service/src/integrationTest/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesController.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
When daily service times are adjusted, all reservations are cleared from under the new daily service times.
After this change, reservations inside holiday periods are kept.
> Keep holiday period reservations when creating/updating daily service times

- frontend/src/employee-frontend/components/holiday-periods/HolidayPeriodForm.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Allow holiday periods of 15 weeks (was 8 weeks).
Also relax validation when updating a holiday period, because no reservations or absences are cleared on update.
> Allow longer holiday periods

- frontend/src/employee-frontend/components/unit/tab-unit-information/DaycareAclAdditionModal.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffOccupancyCoefficientQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/UnitAcl.kt
Bug fix for reported staff occupancy coefficient issue:
- staff occupancy coefficients are no longer removed with corresponding daycare access
- matching change to fix UI state management logic after removal of delete
- test expectation changes
> Removes deleting staff occupancy coefficient information with daycare ACL removal

- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
If a day on a closed holiday period doesn't already have a reservation, the citizen is not allowed to add one. Overriding existing absences was already impossible.
UI changes that show this to the users coming later.
> Don't allow reservations on closed holiday period's empty days

- frontend/src/citizen-frontend/applications/queries.ts
- frontend/src/e2e-test/pages/citizen/citizen-applications.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts
-Invalidate form on draft save to force update on reopening the application
> Invalidate application form on draft save

- frontend/src/e2e-test/specs/5_employee/assistance-need-decisions-report.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AssistanceNeedDecisionAccessControlTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
Allow VEOs to see assistance need decisions of children they have access to
Allow unit supervisors to see assistance need decisions with selected unit as a unit they work in now
> Allow SEOs and unit supervisors to see assistance need decisions

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/IncomeControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotifications.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- Do not send income notification if there is unhandled income statement
- Create unknown income starting the day after expiration (not the start of the next month)
> Income notification changes

- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/citizen-frontend/calendar/TimeRangeInput.tsx
- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts
- frontend/src/citizen-frontend/calendar/reservation-modal/form.ts
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-calendar.spec.ts
- frontend/src/lib-common/form/hooks.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
- Minor fixes to backend logic that computes properties for each calendar day
- Group no-times holiday reservations and reservation not required children in calendar
- Reuse reservation modal's form elements and reset logic in day modal.
> Support non-required reservations in calendar day modal

- frontend/src/employee-frontend/components/unit/unit-reservations/attendanceEditState.spec.ts
- frontend/src/employee-mobile-frontend/staff-attendance/StaffMarkArrivedPage.tsx
- frontend/src/lib-common/local-time.spec.ts
- frontend/src/lib-common/local-time.ts
Validate arrival time on frontend. Previously it was possible to send invalid time strings like 9:00 (should have been 09:00)
> Fix time validation

- service/src/main/resources/db/migration/V322__move_unit_manager.sql
Repeatable migrations are run *after* the main migrations, so having the DROP VIEW in R__old_daycare_acl_view.sql is not enough
> Drop old view in migration

- .dockerignore
See fcd1973:
- file evaka-bom/settings.gradle.kts shouldn't be ignored.
- folder service/buildSrc doesn't exist anymore.
> Fix .dockerignore

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/EvakaClock.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/HelsinkiDateTime.kt
`clock.now().plusSeconds(MessageService.SPREAD_MESSAGE_NOTIFICATION_SECONDS)` is not the correct calculation, because the messages are scheduled up to `SPREAD_MESSAGE_NOTIFICATIONS_SECONDS` starting from the *moment the original job is executed*, which is *not* `clock.now()` since clock.now() is never updated after the start of the test.
Let's try using mutable clock and `tick()` and see if this style is better.
> Fix flaky integration test

- service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
- URLs are now correctly env-specific
- Some missing URLs were added to english texts
> Use baseUrl instead of hard-coded URLs in Espoo e-mails

- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/citizen-frontend/calendar/TimeRangeInput.tsx
- frontend/src/citizen-frontend/calendar/api.ts
- frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts
- frontend/src/citizen-frontend/calendar/reservation-modal/form.ts
- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
- frontend/src/lib-common/form/fields.ts
- frontend/src/lib-common/generated/api-types/reservations.ts
- frontend/src/lib-components/atoms/form/TimeInput.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
Limits allowed citizen reservation inputs by validating them against corresponding combined unit operation hours.
- adds unit operation times to child-day response objects (child + day -> placement -> unit)
- adds combined unit operation times to citizen frontend reservation time validations
- mass reservation per mode
- one reservation per date period -> combined validation range over selected children and all days in range
- one reservation per weekday -> combined validation range over selected children and all days of week in range
- one reservation per date -> combined validation range over selected children
- calendar day reservation editing
- modifies time input styling to allow longer validation error messages (citizen frontend only)
- time inputs scale based on info content
- …
> Use unit operation times to validate and limit child reservations (citizen frontend)

- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
Fixes issue where regular placement unit times were used to validate citizen reservations even during a backup care period.
> Prioritize backup care for daily operation time resolution

- frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx
If a citizen created an income statement, saved it and reopened it, never-ending spinner was shown
> Fix income statement reload spinner issue

- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/DailyRepetitionTimeInputGrid.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/IrregularRepetitionTimeInputGrid.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/RepetitionTimeInputGrid.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/WeeklyRepetitionTimeInputGrid.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts
- frontend/src/citizen-frontend/calendar/reservation-modal/form.ts
- frontend/src/citizen-frontend/jest.config.ts
- frontend/src/citizen-frontend/utils/mocks/fileMock.js
- frontend/src/citizen-frontend/utils/mocks/styleMock.js
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
- frontend/src/e2e-test/specs/0_citizen/feature-flag-citizen-reservations-intermittent-shif-care.spec.ts
- frontend/src/lib-common/form/fields.ts
- frontend/src/lib-common/generated/api-types/reservations.ts
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
- citizens with children that have intermittent shift care service needs can now:
- make attendance reservations without time or day restrictions
- only holiday period days without survey answers are unavailable
- weekends are always visible in citizen calendar
- 2-part reservations are now enabled for all children; any reservable day can now have a 2-part reservation as well
- day modal display of reservations for a child is split on separate rows
- intermittent shift care reservations are exempt of time restrictions based on unit operation hours
- those reservations that exceed unit operation hours are marked with shift care notification text
**Note! Since many of the reservability changes are on the backend, disabling the feature will require both:**
- feature flag = false
- no …
> Citizen intermittent shift care

- frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Solves the issue of expanded week calendar overflowing due to long missing holiday reservation texts for all 7 days.
> Fix intermittent shift care employee week calendar overflow

- frontend/src/employee-frontend/components/absences/MonthCalendarCell.tsx
Fixes the issue where there was no way to re-enable reservations for intermittent shift care children that had `Lomavaraus puuttuu` markings on weekends. This can now be done from the monthly calendar as weekends are always visible for children with intermittent shift care regardless of the operation hours of their primary placement unit.
> Enable weekends/holidays on absence calendar for intermittent shift care

- frontend/src/employee-frontend/components/application-page/ApplicationDecisionsSection.tsx
If application is in `WAITING_DECISION` state, the decision exists in the database, but has not "been made yet" and is not visible to the citizen. Thus, it makes no sense to be able to respond to it.
> Don't allow responding to an unfinished decision as employee

- frontend/src/e2e-test/pages/employee/reports.ts
- frontend/src/e2e-test/specs/5_employee/missing-head-of-family-report.spec.ts
- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/components/reports/MissingHeadOfFamily.tsx
- frontend/src/employee-frontend/components/reports/queries.ts
- frontend/src/employee-frontend/query.ts
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/MissingHeadOfFamilyReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/MissingHeadOfFamilyReport.kt
- Add a filter to include/exclude foster children
- Drop area and unit columns
- Show one row per child
- For each child, list date ranges that are missing a head of family instead of showing the day count
Technical changes:
- Use react-query, `renderResult` and form framework
- The SQL query now uses multiranges to compute date ranges neatly
> Update the "Missing head of family" report

- .github/dependabot.yml
Packages in the same group will be updated in a single PR.
Dependabot announcement: https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
> Configure dependabot package groups

- frontend/package.json
- frontend/yarn.lock
Revert https://github.com/espoon-voltti/evaka/pull/3895 because dev build fails. Root cause https://github.com/downshift-js/downshift/issues/1521
> revert downshift upgrade

- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiUpdateService.kt
This query already took ~30 seconds before the recent assistance model changes, and this is an acceptable trade-off for the functionality (= diffing based on real data vs for example timestamps only).
However, the view is currently much slower since Postgres doesn't seem to optimize out the unused assistance model...this problem will probably correct itself once we get rid of the old model
> Increase Koski pending query timeout

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
- Fix case where if there is a gap in parentship a duplicate fee decision child was tried to be created. 
- Two different cases: one for adult fee decision generation, one for child fee decision generation
- Test for both
> Evaka fix fee decision duplicate child

- frontend/src/employee-frontend/components/child-information/Assistance.tsx
Create `children/{childId}/assistance` request only when user has `READ_ASSISTANCE` permission.
Related to https://github.com/espoon-voltti/evaka/pull/3886
> Fix assistance ui to create request only when has permission

- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/citizen-frontend/calendar/TimeRangeInput.tsx
- frontend/src/citizen-frontend/calendar/api.ts
- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/DailyRepetitionTimeInputGrid.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/RepetitionTimeInputGrid.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts
- frontend/src/citizen-frontend/calendar/reservation-modal/form.ts
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
- frontend/src/e2e-test/specs/0_citizen/feature-flag-citizen-reservations-intermittent-shif-care.spec.ts
- frontend/src/e2e-test/utils/page.ts
- frontend/src/lib-common/form/fields.ts
- frontend/src/lib-common/generated/api-types/reservations.ts
- frontend/src/lib-components/atoms/form/TimeInput.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
Use the type system to differentiate between two cases:
1. The child is in "normal daycare", and can make reservations within the placement unit's opening hours
2. The child is in intermittent shift care and can make any reservations with no limits.
This, along with some other frontend typing changes, fixes various bugs in the time range validation of citizen reservations.
Other changes:
- Better naming (naming is hard)
- Use unit's operation times instead of both operation times and days in the reservation backend
> Fix citizen reservation time range validation

- frontend/src/citizen-frontend/personal-details/NotificationSettingsSection.tsx
- frontend/src/e2e-test/pages/citizen/citizen-personal-details.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-personal-details.spec.ts
- frontend/src/lib-common/generated/api-types/pis.ts
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonalDataControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentNotificationService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/PersonalData.kt
- Add 2 new email message types: decision and informal document.
- Add info bubbles
- Show a warning if outdated income notification is unchecked
- Add `sv` and `en` translations
> Citizen email notification settings, part 2

- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
Feedback in ticket was to the header on children page but I noticed some other pre-school terms in use and fixed those as well,
> Fix remaining citizen preschool texts to pre-primary

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/JdbiExtensionsTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/JdbiExtensions.kt
Serialization/deserialization should generally be symmetric (= serialising and then deserialising the output should work).
This fix makes daterange ser/deser symmetric, but unfortunately dates and dateranges don't work exactly the same way, because the former uses PostgreSQL JDBC driver internal formatting/parsing and the latter uses LocalDate default ISO formatting/parsing and they don't agree 100%.
> Fix non-symmetrical ser/deser for daterange types

- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Citizen calendar is currently showing generic absent message for all absence types (except sickleave in day modal and free absence in calendar view). This adds planned absence to calendar view and day modal.
Uses feature flag added in https://github.com/espoon-voltti/evaka/pull/3951 (yes name of the feature flag is pretty weird).
There are some hackish styles because our planned absence says "Sopimuksen mukainen poissaolo" which is pretty lengthy for the calendar.
> Show planned absence for citizen

- frontend/package.json
In CI, `yarn type-check` didn't catch all type errors. This is probably happens because `webpack` is run first, and its TypeScript configuration is different becaese it uses `ts-loader`.
Use `tsc --build --force .` to force building (i.e. type-checking) every file, even if they have already been build.
> Force type-checking of already built files

- service/src/main/kotlin/fi/espoo/evaka/s3/DocumentService.kt
empty string = `Content-Length: 0` *and* `Content-Type: text/plain`, which seems to sometimes cause Spring Boot to fail the whole request if the client has set `Accept` or other headers so that content type negotation fails.
null body = `Content-Length: 0` without making any claims about the content type.
In both cases nginx will override these headers with actual values from S3.
> Don't use empty string to mean empty body

- frontend/src/employee-frontend/components/child-information/assistance/AssistanceFactorForm.tsx
- frontend/src/employee-frontend/components/child-information/assistance/AssistanceFactorSection.tsx
- frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceForm.tsx
- frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceSection.tsx
- frontend/src/employee-frontend/components/child-information/assistance/OtherAssistanceMeasureForm.tsx
- frontend/src/employee-frontend/components/child-information/assistance/OtherAssistanceMeasureSection.tsx
- frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceForm.tsx
- frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceSection.tsx
- frontend/src/lib-components/molecules/date-picker/DateRangePicker.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Limitations:
- the validation doesn't see rows filtered out by permission rules (= rows existing in db but not returned by backend), e.g. pre-preschool rows when applicable -> validation says yes, save button won't work
- the validation error for assistance factor doesn't appear if the factor number is invalid. This is a limitation that could be fixed by changing the form structure, but then other assistance measures would have to work differently
- if the underlying rows are refreshed *while a form is open*, the form won't see the new refreshed rows and may validate incorrectly. This is a limitation of the validation approach where the rows go to the *initial form state*
> Validate overlaps in frontend assistance forms

- frontend/src/employee-mobile-frontend/auth/api.ts
- frontend/src/employee-mobile-frontend/common/service-worker.tsx
- service/src/main/kotlin/fi/espoo/evaka/webpush/WebPushController.kt
We don't want to allow upsert subscriptions for *other* mobile devices, so get the id from AuthenticatedUser instead
> Remove explicit id parameter

- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/sv.tsx
Enables JSX or string format for city customizations on all extensible info sections for this decision.
**NOTE: this requires changes in customizations that have already implemented info content in string or JSX format. Customized content has to be wrapped in a function and the issue doesn't seem to show as a type error**
> Use ReactNode functions to define decision info entries

- frontend/src/citizen-frontend/calendar/TimeRangeInput.tsx
- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts
- frontend/src/citizen-frontend/calendar/reservation-modal/form.ts
- frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceExternalPersonModal.tsx
- frontend/src/lib-common/form/fields.ts
- frontend/src/lib-common/form/form.ts
- frontend/src/lib-common/form/hooks.ts
- frontend/src/lib-common/form/memoize.ts
- frontend/src/lib-common/form/types.ts
- frontend/src/lib-components/atoms/form/TimeInput.tsx
Allow form fields to assign errors to their subfields. Use this to simplify `limitedLocalTimeRange` field and related components.
The actual beef of this PR: Show a validation error if reservation start = end.
> Validate that reservation start and end time are different + refactoring

- service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentNotificationService.kt
- service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
As all emails are in 3 languages, ignore the `language` parameter altogether and use correct links for the language used. Refactor link generation so that there's less repetition.
Contais a small breaking change: Adds `childId` parameter to `IEmailMessageProvider.pedagogicalDocumentNotification`
> Use correctly translated email links

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobRunnerTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/espoo/EspooScheduledJobs.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/EnvConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/ScheduledJobConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/JobSchedule.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobRunner.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
We can't easily have duplicate `ScheduledJobRunner` instances for city-specific jobs, but instead need to supply *all possible jobs* to a single instance. Redesign how jobs are declared and configured, and pass a list of JobSchedule objects to `ScheduledJobRunner` which may come from different sources.
> Redesign job scheduler to support multiple job types

- service/src/main/kotlin/fi/espoo/evaka/timeline/TimelineController.kt
`order by` got lost after late refactoring to reuse existing queries where possible
> fix timeline api sorting

- frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/AttendanceSummaryTable.tsx
- frontend/src/lib-common/generated/api-types/children.ts
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/children/ChildControllerCitizenTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
Summary should be based on only unit operational days and absences because they are used for invoicing.
> Fix child attendance summary

- frontend/src/lib-components/molecules/ThreadListItem.tsx
Opening a thread required two taps on iPhone because `:hover` styles made delete button to appear. More info about this browser quirk: https://stackoverflow.com/a/50500578
Delete button in thread list is always hidden on touch devices. Touch device detection is done with media query `@media (pointer: coarse)`
Deleting thread is still possible in thread view.
> Hide delete button in thread list on touch devices

- frontend/src/lib-common/generated/api-types/reports.ts
- service/src/main/kotlin/fi/espoo/evaka/espoo/EspooScheduledJobs.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
DO NOT MERGE before ESP is ready 
- Send data from 40 days ago instead of yesterday
- for each day, add is_holiday and is_weekday flags
> Send Patu changes from 40 days ago instead of yesterdays

- frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts
- frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceExternalPersonModal.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/attendanceEditState.spec.ts
- frontend/src/employee-mobile-frontend/staff-attendance/MarkExternalStaffMemberArrivalPage.tsx
- frontend/src/lib-common/generated/api-types/attendance.ts
- frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffOccupancyCoefficient.kt
Adds checkboxes to external staff member addition forms for selecting whether added person has any effect on staff occupancy (mobile & desktop). Previously externals were assumed to always have staff occupancy effect.
Includes:
- UI modifications to add checkboxes
- translation modifications to remove references to assumed occupancy effect
- API changes to allow relaying the user's selection
- desktop UI logic to implicitly interpret attendance specific occupancy effect from earlier attendance markings
- test additions
> Staff occupancy effect selection for external staff

- frontend/src/e2e-test/dev-api/data-init.ts
- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/dev-api/index.ts
- frontend/src/e2e-test/pages/employee/units/unit-groups-page.ts
- frontend/src/e2e-test/pages/employee/units/unit-month-calendar-page.ts
- frontend/src/e2e-test/specs/5_employee/month-calendar.spec.ts
- frontend/src/employee-frontend/components/absences/MonthCalendarTable.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx
- frontend/src/lib-common/generated/api-types/daycare.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/AbsenceServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
During term breaks:
- Show "Ei toimintaa" in week calendar
- Hide the absence triangles in month calendar
> Preschool/club term breaks, part 2 (employee frontend)

- frontend/src/e2e-test/specs/5_employee/income.spec.ts
- frontend/src/lib-components/molecules/date-picker/DateRangePicker.spec.tsx
- frontend/src/lib-components/molecules/date-picker/DateRangePicker.tsx
- frontend/src/lib-components/molecules/date-picker/DateRangePickerLowLevel.tsx
If start passes end, set end to start. If end precedes start, set start to end.
https://github.com/espoon-voltti/evaka/assets/70927/6384e804-6ff1-4301-a676-020e8147aa70
> Adjust DateRangePicker start/end logic

- service/src/main/resources/db/migration/V358__rename_old_application_document_index.sql
- service/src/main/resources/db/migration/V359__really_create_application_document_index.sql
- service/src/main/resources/migrations.txt
IF NOT EXISTS + new index had the same name as old -> no index was created, and *all* queries with a predicate looking inside the document had to do a sequential scan of all data.
> Recreate application document index correctly

- frontend/src/citizen-frontend/messages/MessageEditor.tsx
- frontend/src/citizen-frontend/messages/MessagesPage.tsx
- frontend/src/citizen-frontend/messages/ThreadListItem.tsx
- frontend/src/citizen-frontend/messages/ThreadView.tsx
- frontend/src/citizen-frontend/messages/api.ts
- frontend/src/citizen-frontend/messages/queries.ts
- frontend/src/citizen-frontend/messages/state.tsx
- frontend/src/lib-common/api-types/messaging.ts
- frontend/src/lib-components/i18n.tsx
- frontend/src/lib-components/molecules/ToggleableRecipient.tsx
- frontend/src/lib-components/utils/TestContextProvider.tsx
- frontend/src/lib-customizations/defaults/components/i18n/en.tsx
- frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
`staffAnnotation` string had to be passed into data-deserialization and it was appended to the `name` field of message recipients.
`staffAnnotation` is appended to the recipient `name` in the components that display recipients. This removes the need to pass the translation property into the data layer.
In citizen views the staff annotation is still visible in message thread views as it was before:
> Move staff annotation from datamodel into components

- service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
JDBI has a default fetch size of 0, which means *all results are buffered in memory*...even if we fetch results using `Sequence`/`Iterable`/`Iterator`, that won't enable streaming unless fetch size is set.
> Set fetch size in BI queries

- service/src/main/resources/db/migration/V360__remove_application_form_fk.sql
- service/src/main/resources/migrations.txt
Deleting old applications that had rows in `application_form` didn't work, because we still had a foreign key without cascade.
> Fix application deletes

- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/espoo/EspooActionRuleMapping.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- Disable Patu report in default permissions
- Allow unit supervisors to see occupancy report for any unit
- Disallow placement guarantee report for service workers and directors
> Add Espoo-specific permission customizations

- frontend/src/citizen-frontend/messages/queries.ts
- frontend/src/citizen-frontend/messages/state.tsx
- frontend/src/employee-mobile-frontend/common/BottomNavbar.tsx
- frontend/src/employee-mobile-frontend/common/unit.tsx
- frontend/src/employee-mobile-frontend/messages/UnreadMessagesPage.tsx
- frontend/src/employee-mobile-frontend/messages/api.ts
- frontend/src/employee-mobile-frontend/messages/queries.ts
- frontend/src/employee-mobile-frontend/messages/state.tsx
- frontend/src/employee-mobile-frontend/query.ts
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Use react-query in employee-mobile-frontend messaging. Notably, unread counts are now updated when evaka is opened on the phone, which gives better visibility to new messages.
Additionally, small UX improvements:
- Raise a thread to the top after replying in employee views (was already like this for citizens)
- Don't overlay a spinner on bottom navbar when reloading unread counts
> Messaging improvements, part 1

- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
When two (or more) decisions for the same month were being replaced with one, only one of the old decisions would be refunded. Fix to refund all old decisions
> Fix voucher value report problem with one decision replacing two

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Adds a feature flagged option to use the preferred start date as the due date for applications that are sent more than 4 months before the preferred start date. Espoo config sets the flag as FALSE.
Only the non-urgent, non-transfer, early education application branch is changed.
There is no migration for existing 4+ month applications to update their due dates.
Note: as adding an attachment forces a recalculation of the application's due date, depending on configuration-specific attachment sending rules there may be scenarios where existing 4+ month applications are recalculated with the new logic. This was tested and confirmed with Tampere config as a shift care application accepts attachments (without being marked urgent) and ends up changing the due date.
> Application duedate rework

- frontend/src/employee-frontend/components/child-information/PedagogicalDocumentRow.tsx
- frontend/src/lib-components/i18n.tsx
- frontend/src/lib-components/molecules/FileUpload.tsx
- frontend/src/lib-components/utils/TestContextProvider.tsx
- frontend/src/lib-customizations/defaults/components/i18n/en.tsx
- frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
Instead of giving a list of MIME content types, `FileUpload` components can now be configured to allow more general file types: images, documents, video, audio and csv. Localization takes into account the allowed file types.
> Enhance file upload type handling

- service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBiHttpClient.kt
We're streaming a very large request, and immediately after we have sent the last byte, we start reading a response. By default the read timeout is only 15 seconds, but if the other end is still processing the last chunk we sent, it may take longer than that for it to respond.
There's no reason to use a small timeout here, so increase it to 5 minutes.
> Greatly increase response read timeout in BI requests

- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/DatabaseConfig.kt
eVaka doesn't have UI to modify every database so we have been using flyway after migrate scripts to populate the data. This has been working great: every environment we have has the exactly same data and it is well documented and versioned through git.
We are going to use service for multiple municipalities, so we would like to have different after migrate scripts for every municipality. This little change adds support for it.
Example configuration with application.yml:
```
evaka:
database:
flyway:
additional_locations: db/data/tampere
```
> Add flyway additional locations support

- .github/workflows/build.yml
- apigw/README.md
- compose/README.md
- compose/compose-e2e
- compose/compose-integration
- compose/db.sh
- compose/docker-compose.e2e.yml
- compose/test-e2e
- frontend/.dockerignore
- frontend/Dockerfile
- frontend/build-docker.sh
- keycloak/README.md
- keycloak/compose-keycloak
- service/README.md
To use `frontend/Dockerfile` we first need to copy frontend customization files to correct location and then use `docker build`. This changes Dockerfile so that we can provide customization files with just docker (which is great because we can just use `docker compose up` and everything works).
Downside to this (for Espoo) is that `docker build -t evaka/frontend` doesn't anymore work and requires additional command line parameter: `--build-context customizations=src/lib-customizations/espoo`. This can be fixed with high-level docker bake file, but I left that out of this commit because bake files aren't currently used.
Note: I think this requires a little change to `voltti-actions` but I don't have write access to it so here it goes:
```
diff --git a/docker-build-registry/action.yml …
```
> Add frontend build context support

- frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/ValueOrNoRecord.tsx
- frontend/src/employee-frontend/components/application-page/ApplicationStatusSection.tsx
- frontend/src/employee-frontend/components/common/Filters.tsx
- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- frontend/src/employee-frontend/components/person-profile/income/IncomeItemHeader.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ReservationModalSingleChild.tsx
- frontend/src/employee-frontend/components/vasu/components/ValueOrNoRecord.tsx
- frontend/src/employee-frontend/state/application-ui.tsx
- frontend/src/employee-frontend/state/customers.tsx
- frontend/src/employee-frontend/state/i18n.tsx
- frontend/src/employee-frontend/state/invoicing-ui.tsx
- frontend/src/employee-frontend/state/person.tsx
- frontend/src/employee-frontend/state/title.tsx
- frontend/src/employee-frontend/state/ui.tsx
- frontend/src/employee-frontend/state/unit.tsx
- frontend/src/employee-frontend/state/units.tsx
- frontend/src/employee-frontend/state/user.tsx
- frontend/src/employee-mobile-frontend/common/i18n.tsx
- frontend/src/employee-mobile-frontend/common/service-worker.tsx
- frontend/src/employee-mobile-frontend/common/unit.tsx
- frontend/src/employee-mobile-frontend/messages/state.tsx
- frontend/src/lib-components/assistance-need-decision/AssistanceNeedDecisionReadOnly.tsx
- frontend/src/lib-components/assistance-need-decision/AssistanceNeedPreschoolDecisionReadOnly.tsx
- frontend/src/lib-components/atoms/ExternalLink.tsx
- frontend/src/lib-components/atoms/InternalLink.tsx
- frontend/src/lib-components/molecules/Tabs.tsx
- frontend/src/lib-components/molecules/date-picker/DatePicker.spec.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/types.d.ts
> Use React.JSX instead of deprecated global JSX namespace

- frontend/src/employee-frontend/components/child-information/DailyServiceTimesSection.tsx
- frontend/src/employee-frontend/components/child-information/daily-service-times/DailyServiceTimesForms.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesController.kt
-  show warning when creating new service times if already exists active or upcoming times
- when changing end date only remove reservations from the extension period
> Daily service times fixes

- frontend/src/citizen-frontend/navigation/shared-components.tsx
Notification count display was broken when count number was 3 or more digits long.
Notification count display works OK with 3+ digit numbers
> Make notification count component dynamic width, fixes #4207

- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/lib-components/i18n.tsx
- frontend/src/lib-components/layout/flex-helpers.ts
- frontend/src/lib-components/messages/MessageEditor.tsx
- frontend/src/lib-components/messages/SelectorNode.ts
- frontend/src/lib-components/molecules/MessageBoxes.tsx
- frontend/src/lib-components/utils/TestContextProvider.tsx
- frontend/src/lib-customizations/defaults/components/i18n/en.tsx
- frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
It was not possible to send message threads marked as sensitive.
Employee front-end gains support for sending message threads marked as sensitive. This feature (displaying the sensitivity checkbox) is behind a feature flag `sensitiveMessaging` which is set false in all Espoo production and staging environments, but defaults to true in order to have it enabled during localhost development.
> Add flags to employee message editor

- service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
`StaffAttendanceId` was used for both `staff_attendance` and `staff_attendance_realtime` database tables.
> Add StaffAttendanceRealtimeId

- frontend/src/employee-mobile-frontend/common/BottomNavbar.tsx
Bottom navbar is often unmounted and mounted again when browsing through different mobile views. Don't refresh the unread messages count on every mount, just when the window gains focus (i.e. eVaka is "opened").
> Reduce unread messages count queries

- frontend/src/employee-frontend/components/messages/UndoMessageNotification.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/notes/ApplicationNoteQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
- service/src/main/resources/db/migration/V366__message_delete_cascades.sql
- service/src/main/resources/migrations.txt
- Add `on delete cascade`s to simplify deletion and possibly improve performance
- Avoid fetching a long list of IDs and then later deleting based on passing it back
- Introduce assumptions to improve performance (e.g. `limit 1` vs `distinct`)
> Message undo optimization

- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
Make the language selection hiding in the preschool assistance decision editor work similar to the daycare assistance decision editor with the same feature flag
> Add language selection hiding to the preschool assistance decision editor

- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
When a voucher value decision's validity has been first reduced, and then it's completely annulled later in the same month, the period for which the decision's validity was reduced would not be refunded properly. Fix the "validity updated after last freeze" check to also include annulled decisions. It should be safe to do so, since we know that that the validity can't be changed after the decision has been annulled, so the annulment must have happened after the validity update, which has happened after the last freeze, and thus the annulled decision is in scope for corrections
> Fix a bug in the voucher value decision report

- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Payments.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PaymentService.kt
This is needed by the Turku payment integration to rummage the DB for stuff which is not suitable for being included in the Payment objects
> Pass a database connection as a parameter to the payment integration

- frontend/src/citizen-frontend/messages/MessagesPage.tsx
- frontend/src/citizen-frontend/messages/RedactedThreadView.tsx
- frontend/src/citizen-frontend/messages/ThreadListItem.tsx
- frontend/src/citizen-frontend/messages/ThreadView.tsx
- frontend/src/e2e-test/pages/citizen/citizen-messages.ts
- frontend/src/e2e-test/pages/employee/messages/messages-page.ts
- frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
- frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
- frontend/src/employee-frontend/components/messages/ThreadList.tsx
- frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx
- frontend/src/employee-mobile-frontend/messages/ReceivedThreadsList.tsx
- frontend/src/employee-mobile-frontend/messages/SentMessagesList.tsx
- frontend/src/lib-common/generated/api-types/messaging.ts
- frontend/src/lib-components/messages/MessageCharacteristics.tsx
- frontend/src/lib-components/messages/MessageEditor.tsx
- frontend/src/lib-components/messages/ThreadListItem.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Display of redacted versions on sensitive message threads was not implemented.
When citizen is logged-in with weak authentication they see a prompt to login with strong authentication when trying to view message threads marked as sensitive.
After strong authentication the lock icons are removed from sensitive threads and instead their title is appended with "(Sensitive message thread)"
This change also adds end-to-end tests for sending and viewing sensitive messages.
> Sensitive messages citizen views

- frontend/src/lib-common/generated/api-types/invoicing.ts
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/PaymentQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Payments.kt
Add unit care type to Payment objects and fetch it appropriately from the DB along the other payment data. This is backwards compatible for anyone who doesn't need the new field.
> Add unit care type to payment data

- frontend/src/citizen-frontend/App.tsx
- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-mobile-frontend/App.tsx
styled-components v6 caused a lot of React warnings about unknown DOM attributes, because styled-components now passes all props through.
Restore styled-components v5 behavior by using a library function to check whether a prop is allowed for a given HTML element.
The real fix would be to rename all custom props so that they are prefixed with `$`.
> Avoid React warnings for invalid DOM attributes

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/ChildDailyNoteAccessControlTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/RuleCacheTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlDecision.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/ActionRule.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsEmployee.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsMobile.kt
Old implementation had this query structure:
```
SELECT ...
FROM foo
JOIN (
SELECT ...
UNION ALL
SELECT ...
UNION ALL
SELECT ...
) acl
```
This didn't generate good query plans when checking for permissions for a single target (= the common case). The union queries effectively fetched acl information for *all possible targets* for the current user, regardless of which targets we're interested in.
New implementation has this query structure:
```
SELECT ...
FROM foo
JOIN (
SELECT ...
) acl
UNION ALL
SELECT ...
FROM foo
JOIN (
SELECT ...
) acl
UNION ALL
SELECT ...
FROM foo
JOIN (
SELECT ...
) acl
```
This can generate an optimal query plan, where the database effectively does three separate checks, but each of them is optimal for a single target. The repetition in the query is minimized by …
> Improve access control performance - part 2

- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
This can happen if a mobile pin session in the frontend has timed out.
> Return 404 instead of 500 if a requested thread is not accessible

- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
- Income notification is not sent if there is an unhandled income statement created during last 1 month
> Income notification change

- frontend/src/citizen-frontend/decisions/decisions-page/ApplicationDecision.tsx
- frontend/src/citizen-frontend/decisions/decisions-page/AssistanceDecision.tsx
- frontend/src/citizen-frontend/decisions/decisions-page/AssistancePreschoolDecision.tsx
- frontend/src/citizen-frontend/decisions/decisions-page/Decisions.tsx
- frontend/src/citizen-frontend/navigation/DesktopNav.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
It was hard to navigate the decisions page with a screen reader.
- "Skip to main content" link works on decisions page
- amount of decisions waiting for confirmation is announced in main menu
- decisions page headings contains info about decisions waiting for confirmation
- decisions are listed from newest to oldest under each child
- `<br/>`elements are hidden from screen reader
> Evaka improve decisions a11y

- frontend/src/citizen-frontend/messages/MessageEditor.tsx
- frontend/src/citizen-frontend/messages/MessagesPage.tsx
- frontend/src/e2e-test/pages/citizen/citizen-messages.ts
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
- frontend/src/e2e-test/utils/page.ts
- frontend/src/lib-components/atoms/form/MultiSelect.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Selecting children for a new message now adds to available recipients instead of reducing. If multiple children are selected, a message can be sent to all of their groups, for example. Howevew, selecting children in different units is not allowed.
> Update citizen's new message recipient logic

- frontend/src/employee-frontend/components/messages/MessageComponents.tsx
> Fix employee message list style

- frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx
Same pseudo-class targeting problem as in #4357.
Before:
After:
> Fix unit week calendar's style

- frontend/src/citizen-frontend/messages/ThreadView.tsx
- frontend/src/citizen-frontend/messages/state.tsx
- frontend/src/e2e-test/pages/citizen/citizen-messages.ts
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
- frontend/src/employee-frontend/components/messages/api.ts
- frontend/src/employee-frontend/components/messages/queries.ts
- frontend/src/employee-mobile-frontend/messages/ThreadView.tsx
- frontend/src/employee-mobile-frontend/messages/state.tsx
- frontend/src/lib-components/messages/MessageReplyEditor.tsx
Both employee-frontend and citizen-frontend now hide the reply editor after sending. employee-mobile-frontend already did this.
Refactor MessageReplyEditor to use MutateButton. This causes less flickering in the UI when sending the reply. Refactor it to also empty the reply contents after sending. This lets us remove that logic from message contexts.
> Hide reply editor after sending a reply

- frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
- frontend/src/employee-mobile-frontend/messages/ThreadView.tsx
- frontend/src/lib-common/messaging.ts
Show the child name(s) after the parent's name instead of always showing them after the sender's name.
> Format account and child names consistently

- frontend/src/citizen-frontend/messages/ThreadView.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/lib-components/i18n.tsx
- frontend/src/lib-components/messages/MessageEditor.tsx
- frontend/src/lib-components/messages/MessageReplyEditor.tsx
- frontend/src/lib-components/utils/TestContextProvider.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- frontend/src/lib-customizations/defaults/components/i18n/en.tsx
- frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
- Placeholder in citizen message editor was misleading in sensitive message threads.
- Sensitive messaging was behind a feature flag not enabled in Espoo production.
- "Note! Do not enter sensitive information here." is no-longer shown in the message placeholder in sensitive message threads.
- Sensitive messaging feature flag was removed and it's now enabled everywhere
> Evaka enable sensitive messaging

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/old/VardaResetService.kt
- If creating the varda child record failed, it resulted in varda_service_need.varda_child_id being null. This was used to wipe old child data out during reset, so some varda_service_need rows were not deleted. To ensure all child varda data is deleted during reset use evaka_child_id instead
> Ensure all varda info is wiped for child to be reset

- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
this was forgotten when removing 15 months limit and is needed to regenerate voucher value decisions after revert to v1
> extend nightly generation to start from finance min date

- apigw/src/enduser/keycloak-citizen-saml.ts
This affects validation only, because the profile is currently still parsed separately and this parsing code used the right property name
> Fix keycloak email property name in zod validation

- frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
It was possible to add an absence (e.g. sick leave) for a day which already contains attendance records. This may affect billing in a way that should not be allowed.
Creating absence markings for a day with existing attendance record is no more possible via `POST /citizen/absences`. Instead the API will return a HTTP 400 - Invalid Request with error code `ATTENDANCE_ALREADY_EXISTS` and the UI will react to this error by displaying 
> There is already attendance record for the selected days
> It is not possible to add an absence for a child on a day that already has an attendance record.
> Disallow adding absence on days which already contain attendance records

- frontend/src/employee-frontend/components/invoice/InvoiceRowsSectionRow.tsx
- Only accept as many characters as is really stored
- Give the first two invoice correction inputs as much room as available
Same in read only view:
> Improve invoice correction editor layout

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
Refactor all citizen related queries to use the `application` table directly instead of `application_view`. Then fix the start date shown to citizen to never use placement plan's start date.
It was not enough to just remove the placement plan's date from the query, because the decision is created at the same time as the placement plan, so the application's state also needs to be checked to decide which date to use.
While at it, change on action rule to also query `application` directly.
> Hide placement plan date from citizen

- frontend/src/e2e-test/specs/0_citizen/citizen-income.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/controller/IncomeControllerCitizenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotifications.kt
Send outdated income notifications to fridge parents instead of guardians.
> Send outdated income notifications to fridge parents

- frontend/webpack.config.js
`assets` is not a path to a directory but a *glob*, so we need to use some kind of a wildcard that finds all the files.
> Fix sentry upload

- frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
- frontend/src/employee-frontend/components/document-templates/queries.ts
- frontend/src/lib-common/generated/api-types/document.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/document/DocumentTemplateIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateController.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
- Return document templates of the language that matches the placement unit's language.
- Allow having incomplete documents of the same type as long as the template is different.
Documentation: https://github.com/espoon-voltti/evaka/wiki/Lapsen-sivu#lapsen-pedagogiset-lomakkeet
> Document template fixes

- frontend/src/employee-frontend/components/absences/MonthCalendarCell.tsx
Warning should not be visible if there is an absence.
#4490 for month calendar.
> Fix backup care required warning visibility

- frontend/src/employee-frontend/components/timeline/renderers.tsx
- frontend/src/lib-common/generated/api-types/timeline.ts
- service/src/main/kotlin/fi/espoo/evaka/timeline/TimelineController.kt
Partnership metadata in timeline view had a link to the originating application even if the originating application was not accessible for the viewing user.
Link to application in timeline view is only show if user has view access to the application and thus can open it. Otherwise it'll simply show the application type and create timestamp as static text.
> Only link to application if current user can open the application

- frontend/src/e2e-test/pages/employee/applications/application-read-view.ts
- frontend/src/e2e-test/pages/employee/messages/messages-page.ts
- frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
- frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
- frontend/src/e2e-test/specs/7_messaging/municipal-messaging.spec.ts
- frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts
- frontend/src/e2e-test/utils/page.ts
- frontend/src/employee-frontend/components/application-page/ApplicationNotes.tsx
- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
- frontend/src/lib-common/generated/api-types/messaging.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Avoid disclosing the names of all recipients to senders of municipal messages.
The fix is to hide the actual names of recipients from _all_ sent messages. `recipientNames` is the set of names the sender chose when sending the message, so always show that list. It may contain names of children, groups, units, areas or the name of the municipality. The point is that whoever sent the message, they were permitted to see that name when sending, so it's safe to show.
> Hide the actual names of the recipients of sent messages

- service/src/main/kotlin/fi/espoo/evaka/pis/PartnershipQueries.kt
Endpoint `PUT /partnerships/{id}/retry` was failing with HTTP 500 caused by an SQL syntax error.
Typo in SQL statement is fixed and endpoint works as intended.
> Fix typo in partnership retry SQL statement

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUnitIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
- service/src/test/kotlin/fi/espoo/evaka/varda/VardaUnitModelTest.kt
Hei järjestelmätoimittajat,
Muistutuksena:
Kesäkuussa Vardan toimipaikan asiointikieli -tietokenttä muutettiin toimintakieleksi. Vuoden alusta lähtien (1.1.2024) kentän nimi muuttuu rajapinnassa: asiointikieli_koodi à  toimintakieli_koodi. Tällä hetkellä rajapinnassa on molemmat käytössä ja asiointikielestä on redirect toimintakieleen. Ilmoitamme järjestelmätoimittajille, kun muutos on Vardan testiympäristössä testattavissa.
Kerrottehan, mikäli muutosta ei ole mahdollista toteuttaa annetussa aikataulussa ja sillä on osaltanne vaikutuksia varhaiskasvatustietojen integraatioihin Vardassa.
Yhteistyöterveisin,
Opetushallituksen Varda-tiimi
[varda@opintopolku.fi](mailto:varda@opintopolku.fi)
> Field rename in varda units api

- apigw/package.json
- apigw/yarn.lock
dd-trace 4.21.0 leaks memory, see https://github.com/DataDog/dd-trace-js/issues/3887
Reverts espoon-voltti/evaka#4519
> Revert "Bump dd-trace from 4.20.0 to 4.21.0 in /apigw"

- apigw/Dockerfile
- apigw/src/enduser/app.ts
- apigw/src/enduser/mapRoutes.ts
- apigw/src/enduser/publicRoutes.ts
- apigw/src/enduser/routes.ts
- apigw/src/index.ts
- apigw/src/internal/app.ts
- apigw/src/shared/auth/dev-auth.ts
- apigw/src/shared/routes/csp.ts
- apigw/src/shared/routes/saml.ts
After switching to ES modules, the instrumentation of external libraries (like express) no longer works. Use a module loader provided by dd-trace to fix this, as described here: https://github.com/DataDog/dd-trace-js/issues/2221#issuecomment-1198215673
Also initialize the tracer as early as possible to instrument all code.
> Fix apigw datadog tracing

- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
Employee created reservations could only override citizen created absences.
Employee created reservations also override employee created absences.
> Employees can override also employee created absences with reservations

- apigw/src/enduser/app.ts
- apigw/src/internal/app.ts
- apigw/src/shared/routes/saml.ts
This fixes a bug where a unified gateway (undefined gatewayRole) redirected the user to the citizen home page even when using authentication mechanisms meant for the employee-side app
> Fix default page url after failed login/logout

- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
Added handling to remove placements future absences and reservations that are not in the period range. Operation is done when creating an overlapping future placement, deleting existing placement or editing existing placements period end date that is in future.
> Bugfix remove future absences and reservations for placement

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
Fixed outdated incomes query to include fridge partners that have null end date. Also replaced placement validity  daterange() comparison with BETWEEN to make the query faster (same result, time spent 30s -> 9s).
> Fix outdated incomes query to include fridge partners that have null end date

- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/espoo/EspooActionRuleMapping.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
It was possible to create service times in other municipalities than Espoo.
Like reading service times, also creating service times permission is only enabled in Espoo.
> Make creating service times permission enabled only in Espoo

- service/build.gradle.kts
Gradle commands like `./gradlew flywayMigrate` don't currently work, because Flyway Postgres support package is not in the Gradle build classpath
> Fix Flyway Gradle plugin

- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
`fc_head.head_of_child` and `fp.person_id` have the exactly same value in this join, but using the latter basically makes this a "2-table join" instead of a "3-table join".
Previously postgres decided to sometimes use a query plan that caused a massive combinatory explosion (> 250 million rows) and almost all of the rows were later thrown away
Also, use `between_start_and_end` since we have a scenario where the table contains a *date column* and we're checking it against a *date range parameter*.
> Improve performance of expiring incomes query

- frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsentBeforehand.tsx
- frontend/src/employee-mobile-frontend/child-attendance/api.ts
- frontend/src/lib-common/generated/api-types/attendance.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/AbsenceControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/AbsenceController.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V375__absence_modified_at_drop_default.sql
- service/src/main/resources/migrations.txt
When absences are added, keep reservations in the confirmed range but delete them from the unconfirmed range.
There are many ways to add absences, so this change touches many places in the code.
While at it, refactor many tests to avoid using global test data. Also make some other refactorings related to absences.
> Keep correct reservations when marking absences

- frontend/src/employee-frontend/api/attachments.ts
Fix a bug which causes attachments whose file names contain semicolons to be undownloadable by employees due to missing URL encoding
> Fix URL encoding bug in employee attachment download

- frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/sections/CitizenVasuHeader.tsx
If the document name has long words, having all the information side-by-side is not feasible on mobile -> arrange vertically instead
**Old:**
**New:**
> Fix citizen vasu mobile layout

- apigw/src/enduser/dev-sfi-auth.ts
- apigw/src/enduser/suomi-fi-saml.ts
- apigw/src/shared/auth/index.ts
- apigw/src/shared/proxy-utils.ts
- apigw/src/shared/service-client.ts
- frontend/proxy/files/etc/nginx/proxy_params.template
- service/src/integrationTest/kotlin/fi/espoo/evaka/ServerSmokeTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/auth/FuelRequestSigning.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/AuthenticatedUserJsonDeserializer.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/JwtToAuthenticatedUser.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/JwtTokens.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/RequestToAuthenticatedUser.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/HttpFilterConfig.kt
Send the same user fields in HTTP headers that are already sent in JWT. Read the fields from headers, but fall back to JWT if the headers don't exist. If the headers exist, JWT payload can be empty, but the JWT needs to be valid in either case.
In integration tests, use empty cached JWT and send user fields in headers only.
Also, stop creating sessions where user's type is `ENDUSER`. Always use `CITIZEN_STRONG` instead.
After this has been deployed to production, the fallback of reading user fields from JWT can be removed and apigw can start sending an empty JWT which can be cached for a longer time. The support for for `ENDUSER` user type can also be removed.
> JWT refactor, part 1

- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
hopefully fixes flaky test by making sure lists are returned in a defined sort order
```
AttendanceReservationsControllerIntegrationTest > generates the correct result in all cases() FAILED
org.opentest4j.AssertionFailedError at AttendanceReservationsControllerIntegrationTest.kt:294
```
> try fixing flaky integration test

- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
- Exclude children from second part of the union that are in backup care
- Improve performance (60ms->7ms in busy unit) by moving conditions inside unions
> Fix mobile occupancy for same unit backup care

- frontend/src/e2e-test/specs/5_employee/reservation-calendar-child-date-modal.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/AbsenceDay.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ChildDateModal.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ChildDayReservation.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ChildReservationsTable.tsx
- frontend/src/lib-common/generated/api-types/reservations.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
It was not possible to distinguish between staff made absence records and citizen made absence records.
Employee week view shows an asterisk and tooltip info on absence records that are made by staff.
> Indicate staff made absence records in week calendar

- frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts
- frontend/src/e2e-test/pages/employee/units/unit-groups-page.ts
- frontend/src/employee-frontend/components/unit/UnitDataFilters.tsx
fixes issue "Yksikön kalenterisivun yläreunan päivämäärä menee vuoteen 2020 kun sitä lähtee muokkaamaan"
> replace deprecated datepicker to improve unit page date filter ux

- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
Replace employee_child_daycare_acl usage with `ruleViaChildAcl`, or manual `cfg.aclQueries` usage.
This *very likely* affects the performance of all changed queries, hopefully positively because `ruleViaChildAcl` tends to give better query plans than using `employee_child_daycare_acl`
> Replace remaining employee_child_daycare_acl usage in rules

- .github/workflows/build.yml
- apigw/Dockerfile
- frontend/Dockerfile
- keycloak/Dockerfile
- service/Dockerfile
Use `YEAR-WEEK` as `CACHE_BUST` build arg for Docker builds to force clean builds each week. This way we should get base image and operating system updates at least once a week.
> Bust Docker caches in GitHub Actions

- apigw/Dockerfile
- frontend/Dockerfile
- keycloak/Dockerfile
- service/Dockerfile
The `CACHE_BUST` arg must come *after* the `FROM` line to effectively bust the cache, see
https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact.
> Fix cache busting in Dockerfiles

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/dev-api/types.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-calendar.spec.ts
- frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
- frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
- frontend/src/lib-common/generated/api-types/calendarevent.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEvent.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventController.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V383__calendar_event_timestamps.sql
- service/src/main/resources/migrations.txt
Changes:
- `calendar_event` table
- adds `modified_at` column
- depicts latest endpoint originating update to the row 
- adds `content_modified_at` column
- depicts latest endpoint originating update to the row, attendees or times
- used to inform user of general event state
- renames columns `updated` ->  `updated_at`, `created` -> `created_at`
- migration for existing data rows
- integration testing for `content_modified_at` updates
- compatibility changes for test fixture helpers
- adds `contentModifiedAt` to calendar event DTO and timestamp parsing to frontend API function
> Content modification timestamp for calendar events

- frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
- frontend/src/citizen-frontend/calendar/CalendarListView.tsx
- frontend/src/citizen-frontend/calendar/DayElem.tsx
- frontend/src/citizen-frontend/calendar/MonthElem.tsx
- frontend/src/citizen-frontend/calendar/MonthlyHoursSummary.tsx
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-monthly-summary.spec.ts
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
It was hard for citizen to track how many hours they have spent of their monthly service need.
Each month has an expandable time usage summary for children that have an hourly based service need. Display of the ℹ️ expand info button behind a front-end feature flag `timeUsageSummary` which defaults to `false` in production environment.
Mobile citizen calendar view
Desktop citizen calendar view
> Citizen monthly time usage summary

- frontend/src/e2e-test/specs/5_employee/reservation-calendar-child-date-modal.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/ChildDateModal.tsx
In week calendar edit modal the available absence types are limited to common cases unless there's an existing absence of a different type. Rare cases should be added through the month calendar which is generally used by less people.
> limit selectable absence types in week calendar

- frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx
- frontend/src/employee-mobile-frontend/child-attendance/api.ts
- frontend/src/employee-mobile-frontend/child-attendance/queries.ts
- frontend/src/employee-mobile-frontend/child-info/ArrivalAndDeparture.tsx
- frontend/src/employee-mobile-frontend/child-info/AttendanceChildPage.tsx
- frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildAbsent.tsx
- frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildComing.tsx
- frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- Return all attendances that overlap current day, because frontend needs them for validations
- Instead move the 30min logic inside status calculation function (if last attendance started yesterday and ended more than 30min ago then child is seen as COMING instead of DEPARTED
- After marking a full day absence it was not possible to cancel it, because the button reused "return-to-coming" endpoint which no longer deletes absences. Created a new endpoint specific for cancelling today's full day absence.
- Fixed bug in merging over night attendances
- Fixed bug in displaying 'yesterday' label before arrival time
- Fixed bug where full day absence could be marked although child had been present today after overnight absence
> mobile bugfixes

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/SoapStackIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/sficlient/MockSfiMessagesClient.kt
- service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiAsyncJobs.kt
- service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesClient.kt
- service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- Make async jobs more serial so that email and sfi sending jobs are planned after pdf generation
- This way pdf does not need to be generated twice, but sfi job can use the pdf from s3
- Sfi sending now plans AsyncJob.SendMessage instead of calling sfiClient, so that the ratelimit is shared correctly together with other sfi messages
- Remove second argument from sfiClient? It is now always null and apparently should never be used
> respect sfi rate limit and do not generate decision pdf twice

- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/FamilyController.kt
- service/src/main/kotlin/fi/espoo/evaka/sensitive/GetChildSensitiveInfoQueries.kt
- fetch data (just a few rows for a child) in CTEs, then do set operations based on the data
- do sorting in Kotlin code since there's no advantage to doing it in SQL and we're already doing so in some cases
- also fixes a bug where `LOCAL_SIBLING` did not check the validity period correctly (the *sibling's* `fc2` date range was not checked and the targeted child `fc1` was checked twice)
These changes give a massive performance increase, and the old ~1s query changes into a <10ms query.
> Improve family contacts query

- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/FamilyController.kt
addDefaultPriorities is sensitive to ordering, so we need to sort twice or change its implementation.
Fixes flaky ordering caused by non-deterministic ordering
> Sort before adding default priorities

- frontend/src/citizen-frontend/calendar/AttendanceInfo.tsx
- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/MonthlyHoursSummary.tsx
- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-monthly-summary.spec.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-show-service-usage.spec.ts
- frontend/src/lib-common/reservations.ts
- frontend/src/lib-components/typography.ts
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
It was not possible to track service time usage per day in citizen front-end.
Citizen day view displays used service time and highlights attendances that exceed planned time.
The new service time usage component is only used when feature flag `timeUsageInfo` is enabled and child's `ServiceNeed` contains a `daycareHoursPerMonth` value.
Child departure after reservation end; Both ends of attendance exceed reserved time
No reservation / absence provided -> using monthly service time divided by 21
> Show used service time and warnings in citizen day view

- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/test/kotlin/fi/espoo/evaka/reservations/UsedServiceTests.kt
- Add `evaka.planned_absence.enabled_for_hour_based_service_needs` env variable to...
- ... use the same planned absence logic with hour based service need that is already in use with contract days: If an absence is marked to a reservable (unlocked) calendar day, change it to a planned absence
- Compute 0 hours as used service for days with planned absences. With all other absence types, use the reservation, or the month's average if a reservation doesn't exist.
> Hour based service need changes

- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/AsyncJobConfig.kt
This config is pessimistic, but should keep us under a 14/s sending quota when 2 service instances are in use.
> Throttle e-mail jobs and limit concurrency

- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobPool.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/AsyncJobConfig.kt
- service/src/main/resources/db/migration/V386__async_job_permit.sql
- service/src/main/resources/migrations.txt
Since we don't actually need to accurately limit cluster-wide *concurrency* of executed jobs, it's enough to throttle *claiming of jobs* and not their execution. This kind of simple per-pool "work permit" (= global lock) held while claiming a job should be enough.
> Add async job permit mechanism for cluster-wide throttling

- frontend/src/employee-frontend/components/reports/PlacementSketching.tsx
- frontend/src/lib-common/generated/api-types/reports.ts
- service/src/main/kotlin/fi/espoo/evaka/reports/PlacementSketchingReport.kt
Changes the `hasAdditionalInfo` boolean field of the report to `additionalInfo` containing the actual additional info from the application document.
NB! Previously the existence of additional info has been evaluated by checking all of the additional info fields (diet, allergies, other info). The new replacement field contains only the contents of the "other info" field as this was deemed the only actually useful information for the report.
> Change report field from yes/no to actual content of otherInfo

- frontend/src/citizen-frontend/applications/ApplicationCreation.tsx
- frontend/src/lib-customizations/types.d.ts
Add an experimental feature flag to hide option to create a club application in citizen UI (Not used in treVaka Vesilahti/Hämeenkyrö etc.)
> Add an experimental feature flag to hide option to create a club application in citizen UI

- frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
- frontend/src/citizen-frontend/calendar/MonthElem.tsx
- frontend/src/citizen-frontend/calendar/MonthInfoOpenHook.ts
- frontend/src/citizen-frontend/calendar/MonthlyHoursSummary.tsx
- frontend/src/citizen-frontend/calendar/hooks.spec.ts
- frontend/src/citizen-frontend/calendar/hooks.ts
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-show-service-usage.spec.ts
- frontend/src/lib-components/messages/MessageEditor.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
It was hard for citizens to notice when reservations or realized attendance exceeds service need.
Monthly summaries display a warning icon when a child has exceeded service need. If reservations exceed service need, the info box is initially open.
> Warn citizen about exceeding service need in calendar view month summary

- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsMobile.kt
- rename `EmployeeChildAclConfig` and use it for mobile devices in rules where the permission is given via a child
- replace `mobile_device_daycare_acl_view` in other rules
This should greatly reduce the performance impact of many permission checks. For example, `inPlacementUnitOfChildOfChildImage` checks currently have a worst case duration of >1 s (!!), which is crazy considering we're checking the permission for one mobile device to access one child image.
> Replace mobile_device_daycare_acl_view in most places

- frontend/src/citizen-frontend/calendar/hooks.ts
Summary became visible if alert logic was triggered even when `timeUsageInfo` was disabled
Summary is not show if feature flag `timeUsageInfo` is disabled
> Hide month hours summary when featureflag is disabled

- apigw/src/enduser/keycloak-citizen-saml.ts
- apigw/src/enduser/suomi-fi-saml.ts
- apigw/src/internal/ad-saml.ts
- apigw/src/internal/keycloak-employee-saml.ts
- apigw/src/shared/saml/index.ts
Invalid profiles will now return an error instead of just a warning.
Also fixes employee number lower case transformation, because we now use the profile parsed by zod and not the original value
> Use zod for parsing, not just validation

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/DbTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
Json vs not json is just about preserving type information and having the Json-qualifier on the type.
Also, add some documentation and tests.
> Reimplement bindJson so it supports nullable types

- frontend/src/employee-frontend/components/unit/unit-reservations/ChildDayCommons.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ChildDayReservation.tsx
Css layout of having both reservations and attendances fixed on chromium, chrome, firefox and safari
> Fix css problems on different browsers

- frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts
- frontend/src/citizen-frontend/calendar/reservation-modal/form.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-start-after-holiday-deadline.spec.ts
- frontend/src/lib-common/generated/api-types/reservations.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
It was not possible to create reservations during a holiday period if there was no "NO_TIMES" reservations for the dates.
It's possible to add reservations during a holiday period if child's first placement started after holiday period deadline
> Allow reservations when placement starts after holiday period deadline

- service/entrypoint.sh
- service/evaka-bom/build.gradle.kts
- service/gradle/libs.versions.toml
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ExceptionHandler.kt
- upgrade to Spring Boot 3.2
- force old Jetty version to keep Apache CXF and Javalin happy. We don't use Spring Boot's embedded Jetty
- fix exception handler incompatibility
- update launcher class name in Docker entrypoint
> Spring boot 3.2

- frontend/src/employee-frontend/components/reports/ExceededServiceNeeds.tsx
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ExceededServiceNeedsReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ExceededServiceNeedsReport.kt
It was tiresome to open the group calendar view with correct dates to inspect what is causing the service need exceed
There's a direct link to the group calendar week view on each row of the report.
> Service need exceeded report group calendar links

- frontend/src/employee-frontend/components/reports/ExceededServiceNeeds.tsx
Exceed amount was missing from csv export
It's there
> Include exceed amount in csv export

- frontend/src/citizen-frontend/calendar/reservation-modal/form.ts
This extra check is unnecessary and causes extra confusion. If the end of the reservable range is on a non-operational day, it's still ok to submit reservations and the backend will just ignore the days when reservations should not be added.
> Remove extra check from reservable min/max range

- frontend/src/employee-frontend/components/child-documents/statuses.ts
- frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
- frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
- frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
- frontend/src/employee-frontend/components/vasu/templates/VasuTemplatesPage.tsx
- frontend/src/employee-frontend/generated/api-clients/vasu.ts
- frontend/src/lib-common/generated/api-types/document.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/AsyncJobConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateController.kt
- service/src/main/resources/db/migration/V390__add_migrated_document_types.sql
- service/src/main/resources/migrations.txt
- Admin can trigger migration of curriculum_documents to document_templates and child_documents
- Migration can be ran repeatedly (although some orphan document_templates may be left as garbage) so that we can iterate the logic after checking results with real data 
- For now only admin sees the created documents and templates so that the results can be validated after each iteration
- Only published vasus&leops in COMPLETED state are migrated so the final migration run should be done during summer after current season has ended
> Vasu&Leops migration part 1

- frontend/src/employee-frontend/generated/api-clients/attachment.ts
- frontend/src/employee-frontend/generated/api-clients/pis.ts
- frontend/src/employee-mobile-frontend/generated/api-clients/attachment.ts
- frontend/src/employee-mobile-frontend/generated/api-clients/pis.ts
- service/codegen/src/main/kotlin/evaka/codegen/api/ApiFiles.kt
- service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
- service/codegen/src/main/kotlin/evaka/codegen/api/Controllers.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/TermsController.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/PairingsController.kt
- service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/HttpFilterConfig.kt
Prepare public API endpoints for the new path prefix scheme where each API endpoint unambiguously belongs to exactly one frontend and AuthenticatedUser type (`/citizen`, `/citizen/public`, `/employee`, `/employee/public`, `/employee-mobile`, `/employee-mobile/public`)
> API path prefix preparations

- frontend/src/lib-common/generated/api-types/reservations.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ExceededServiceNeedsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
- service/src/test/kotlin/fi/espoo/evaka/reservations/UsedServiceTests.kt
- Subtract 4 hours also from reserved minutes for five-year-olds
- Make "is day in future" computation consistent
- While at it, remove an unused `attendanceMinutes` field
> Used service fixes

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/UriUtils.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/Varda.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaClient.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
- service/src/test/kotlin/fi/espoo/evaka/varda/integration/VardaClientTest.kt
Supports henkilo, lapsi, varhaiskasvatuspaatos, varhaiskasvatussuhde, maksutieto + huoltajat. Still missing support for toimipaikat.
Allows dry-runs of varda updates with useful logging via manually triggered async jobs.
> Initial new Varda integration

- frontend/src/e2e-test/generated/api-types.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/MissingHolidayReservationsRemindersTest.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/PersonalData.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/MissingHolidayReservationsReminders.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
- Send missing holiday reservation email reminder to those guardians or foster parents that have a daycare placed child during a holiday with a reservation deadline day after tomorrow
- On espoo prod for 27.3.2024 the getChildrenWithWithMissingReservations was Execution Time: 102.383 ms
> Send missing holiday reservation reminders

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/generated/api-types.ts
- frontend/src/e2e-test/pages/employee/documents/child-document.ts
- frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
- frontend/src/employee-frontend/components/child-information/queries.ts
- frontend/src/employee-frontend/generated/api-clients/document.ts
- frontend/src/employee-mobile-frontend/generated/api-clients/document.ts
- frontend/src/lib-common/generated/api-types/document.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V394__child_document_content_modification_info.sql
- service/src/main/resources/migrations.txt
- Child document employee read view and edit view split to separate components/routes.
- Added `content_modified_at` and `content_modified_by` columns.
- If `content_modified_at` is within 15 min, then the employee in `content_modified_by` owns the lock. If someone else tries to update the content, an error is shown.
- When entering the edit view, a `PUT /child-documents/{documentId}/lock` request is made, which tries to acquire a lock and then returns info about the current lock holder, so that in a failure case a detailed error can be shown.
> write lock for child documents

- service/src/main/resources/application.yaml
It was possible to request static resources from `tomcat-docbase` directory by e.g. `GET http://localhost:9099/api/internal/foobar.txt`. All these requests failed with HTTP 404 as the docbase directory is empty causing just unnecessary filesystem IO.
Static resource serving is disabled in Spring Boot, so it doesn't even try to lookup files from the empty docbase directory.
> Disable static resource serving from service

- service/src/main/kotlin/fi/espoo/evaka/varda/new/Varda.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
- Tarkistetaan, että Varda-integraation alkupäivä on vähintään 1.1.2019 (Vardan pään vaatimus)
- Ei luoda `lapsi`-tietueita, joilla ei ole yhtään `varhaiskasvatuspaatos`-tietuetta
- Asetetaan `palveluseteli_arvo`-kentän arvoksi 0 maksupäätösten tapauksessa (vastaa vanhan Varda-integraation toimintaa)
- Ei päivitetä `maksutieto`-tietueita jos vain huoltajat ovat muuttuneet, koska historiallisia huoltajuussuhteita ei tallenneta, eikä haluta lähettää sellaisen lapsen tietoja uudestaan jonka huoltajat ovat muuttuneet.
> Korjauksia uuteen Varda-integraatioon (ei vielä käytössä)

- frontend/src/lib-components/i18n.tsx
- frontend/src/lib-components/molecules/modals/LoginErrorModal.tsx
- frontend/src/lib-components/utils/TestContextProvider.tsx
- frontend/src/lib-customizations/defaults/components/i18n/en.tsx
- frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
- Työntekijät deaktivoidaan 45 päivän inaktiivisuuden jälkeen (oli 3kk)
- Käyttäjä deaktivoidaan vaikka hänellä ei olisi rooleja/luvituksia
- Deaktivoinnissa tyhjennetään myös pin-koodi (roolien ja luvitusten poiston sekä deaktivoiduksi merkitsemisen lisäksi)
- Deaktivoitu käyttäjä voi kirjautua sisään jolloin käyttäjä aktivoituu automaattisesti ja se voidaan luvittaa uudelleen
> Muutoksia työntekijöiden deaktivointiin

- frontend/src/e2e-test/pages/employee/messages/messages-page.ts
- frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
- frontend/src/e2e-test/specs/7_messaging/municipal-messaging.spec.ts
- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/messages/queries.ts
- frontend/src/employee-frontend/generated/api-clients/messaging.ts
- frontend/src/employee-frontend/query.ts
- frontend/src/employee-mobile-frontend/generated/api-clients/messaging.ts
- frontend/src/lib-common/generated/api-types/messaging.ts
- frontend/src/lib-components/i18n.tsx
- frontend/src/lib-components/utils/TestContextProvider.tsx
- frontend/src/lib-customizations/defaults/components/i18n/en.tsx
- frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
- refactor MessageEditor from lib-components to employee-frontend since it is not used elsewhere and does not seem to be close to reusable anyway
- fetch and display recipient count (number of guardians)
- if 3 or more recipients, display warning and require confirmation before sending
- not implemented for employee-mobile in this PR
> Näytetään viestin vastaanottajamäärä ja varoitetaan jos enemmän kuin kaksi

- frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
Ei-whitelistatut IP-osoitteet voivat nyt tehdä 50 pyyntöä 5 sekunnin aikaikkunassa (ennen oli 20 per 2 sekunnin ikkuna).
Laskukaava on myös dokumentoitu konfiguraation viereen.
> HTTP-pyyntöjen rate limittien kasvatus ja parempi dokumentointi

- .github/workflows/release.yml
- bin/changelog.js
`bin/changelog.js STARTDATE ENDDATE` lukee GitHub pull requestien tiedot stdin:stä JSON-muodossa, valikoi annettuna päivämäärävälinä mergetyt (inklusiivinen), ja koostaa niistä labelien perusteella muutoslokin Markdown-muodossa.
PR sisältää myös uuden CI-jobin, joka luo eVakasta uuden GitHub releasen joka sunnuntai klo 23:00 UTC. Releasen kuvaukseksi tulee muutosloki kuluvan viikon ajalta.
Esimerkki: Komento
```
gh pr -R espoon-voltti/evaka list \
--base master \
--state merged \
--limit 100 \
--json title,labels,closedAt,number,url \
| bin/changelog.js 2024-04-08 2024-04-14
```
tuottaa:
---
- Näytetään viestin vastaanottajamäärä ja varoitetaan jos enemmän kuin kaksi [#4993](https://github.com/espoon-voltti/evaka/pull/4993)
- Muutoksia työntekijöiden deaktivointiin …
> Skripti muutoslokin muodostamiseksi

- .github/workflows/build.yml
Sunnuntai-iltaisin ajetun ajastetun buildin imaget saavat samat tagit kuin aiemmin buildatut "varsinaiset" imaget, koska tagina käytetään commit id:tä. Tämä vaikeuttaa tuotantoonvientiä maanantaisin, koska ajossa olevaa imagea ei enää löydy. Siispä ei enää buildata automaattisesti sunnuntaisin.
Imaget päivittyvät silti maanantain ensimmäisissä buildeissa, koska cache bust -mekanismi pakottaa dockerin tekemään uuden buildin alusta asti.
> Poistetaan sunnuntain ajastettu build

- .github/workflows/release.yml
- Lisää `target`-syötteen, jolla voi asettaa kohdehaaran tai commit id:n
- Asettaa releasen nimen eksplisiittisesti
- Antaa kaikille syötteille oletusarvot, jotta cronin kautta ajo toimii varmasti
> Julkaisu-workflown hienosäätöä

- frontend/src/citizen-frontend/generated/api-clients/children.ts
- service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
Use `yyyy` instead of `YYYY` (in `YYYY-MM`) for formatting years to the input `Mon Apr 01 2024 00:00:00 GMT+0300 (Eastern European Summer Time)`; see:
https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md
> Korjaus sopimuspäivälaskurin näkymiseen

- keycloak/evaka-logging/pom.xml
- keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/EvakaLoggingEventListenerProvider.java
- keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/EvakaLoggingEventListenerProviderFactory.java
- keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/PreprocessMode.java
- keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/Preprocessor.java
- keycloak/evaka-logging/src/test/java/com/espoo/keycloak/events/PreprocessorTest.java
The behaviour should remain the same, but the implementation should be more robust:
- replace a large amount of booleans with simpler enums
- move most "business logic code" to a separate Preprocessor class, which is independently testable without any actual "Keycloak integration"
- use composition in the ListenerProvider so we can remove a lot of copy-paste code and just preprocess the log event before passing it forward
- use inheritance in ListenerProviderFactory so we can remove a lot of copy-paste code. We just need to wrap any ListenerProviders returned by the factory
- fix thread-safety bug: a static shared mutable MessageDigest was used for SHA-256 calculation, which is not thread-safe. If creating a new MessageDigest for every calculation ends up being a performance problem, some …
> Keycloak-lokituskoodin parannuksia

- frontend/src/e2e-test/specs/5_employee/income.spec.ts
> Testi lisätty että uuden asiakkaan tulotietomuistutus näkyy profiilisivulla

- frontend/src/employee-frontend/components/Reports.tsx
Enää raportti ei näy millekään käyttäjälle ellei `jamixIntegration`-flagi ole päällä.
> Siiretään Ruokailijamäärät-raportti feature flagin taakse

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
- Varda-ajo ei enää kaadu jos `varda_state`-taulussa on lapsi jolta puuttuu sekä henkilötunnus että OPH OID.
- Lokitusta parannettu
> Korjauksia Varda-integraatioon

- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
assistance_need = vanha tuen malli, jota ei kuulu käyttää mihinkään ja pitäisi oikeasti jo poistaa
daycare_assistance = yksi uuden tuen mallin tauluista
assistance_action -taulussa on start_date/end_date eikä valid_during, ja oikeasti katsottiinkin virheellisesti eri taulua
"Muut toimet" -osiota (other_assistance_measure) ei kuulu katsoa mutta katsottiin
> Raakaraportti katsoo tuen tasoa vakassa ja tukitoimia nyt oikein

- frontend/src/e2e-test/specs/5_employee/income.spec.ts
- frontend/src/lib-common/generated/api-types/mealintegration.ts
- frontend/src/lib-common/generated/api-types/reports.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/mealintegration/MealType.kt
- service/src/main/kotlin/fi/espoo/evaka/mealintegration/MealTypeMapper.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/MealReportController.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/MealReportUtil.kt
- service/src/test/kotlin/fi/espoo/evaka/reports/MealReportTests.kt
Kaikkialla oli käytössä Kangasalan `MealType` -> `mealID` mapperi
Kullekkin kunnalle on mahdollista määrittää oma `MealType` -> `mealID` mapperi
> Kuntakohtaiset ruokatilausintegraation ateriatunnisteet

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/generated/api-types.ts
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/jamix/JamixIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/jamix/JamixQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/MealReportUtil.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/EnvConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
- service/src/test/kotlin/fi/espoo/evaka/reports/MealReportTests.kt
Lähetetään seuraavan viikon ateriatilaukset Jamixiin ajastetussa jobissa (oletuksena joka tiistai klo 02:25).
Integraation saa päälle konfiguroimalla seuraavat Spring propertyt:
- `evaka.job.send_jamix_orders.enabled = true`
- `evaka.integration.jamix.enabled = true`
- `evaka.integration.jamix.url`: Jamix-rajapinnan URL operaation nimeen asti, esim. `https://fi.jamix.cloud/japi/pirnet/`
- `evaka.integration.jamix.user`: HTTP Basic Auth -käyttäjätunnus
- `evaka.integration.jamix.password`: HTTP Basic Auth -salasana
> Jamix-integraatio

- compose/README.md
Hei,
huomasin että service moduuli ei buildaantunut enää java 17 versiolla joten ajattelin päivittää ohjeeseen oikean version.
> Päivitä compose ohjeen java versio

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/generated/api-types.ts
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
- frontend/src/employee-frontend/components/unit/tab-groups/groups/group/GroupUpdateModal.tsx
- frontend/src/lib-common/generated/api-types/daycare.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/jamix/JamixIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareGroupQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/DaycareService.kt
- service/src/main/kotlin/fi/espoo/evaka/jamix/JamixQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V409__jamix_customer_number.sql
- service/src/main/resources/migrations.txt
Jamix-tilausten luonti tarvitsee asiakas-ID:n, mutta Jamixin käyttöliittymä tarjoaa vain asiakasnumeron. Tästä eteenpäin ryhmän tietoihin kirjataan asiakasnumero, jonka eVaka osaa muuntaa asiakas-ID:ksi ennen kuin tilauksia aletaan luoda.
> Jamix-integraatio: Käsitellään asiakasnumeroita

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaQueries.kt
Jos lapsella ei ole OPH OID:tä, tehdään `/v1/hae-henkilo`-apikutsu henkilötunnuksen perusteella. Varda kuitenkin näyttää rajoittavan (ainakin) henkilötunnuksellisia hakuja 500 kappaleeseen per vuorokausi, jolloin migraationopeus ei voi käytännössä olla kuin ~400, jotta jäisi varaa myös kokonaan uusien lapsten viennille.
Vanhan integraation `varda_organizer_child`-taulu sisältää lasten OPH OID:t, joten kopioidaan migratoiduille lapsille OID sieltä.
> Migratoidaan myös lasten OPH OID:t vanhasta Varda-integraatiosta uuteen

- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
Läsnäolovaraustaulukko skaalautuu nyt järkevästi pieniresoluutioisella näytöllä.
ja sama normaalinäytöllä
> Yksikön viikkonäkymän läsnäolokalenterin UI korjaus

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/Varda.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaClient.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
Käytetään hetullisille lapsille `/v1/henkilot/`-rajapintaa, jota Varda nykyään suosittelee käytettävän. Deprekoitua `/v1/hae-henkilo/` -rajapintaa käytetään enää vain hetuttomien lasten kanssa, koska täten voidaan kiertää Vardan nimivalidaatio, joka ei välttämättä mene läpi lapsille, joiden tiedot eivät päivity VTJ:stä.
Nostetaan samalla lasten vientimäärä max 5000:een per ajo.
> Käytetään eri Varda-rajapintaa hetullisten henkilöiden hakuun

- frontend/src/e2e-test/specs/5_employee/child-information.spec.ts
- frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
- frontend/src/employee-frontend/components/reports/MealReport.tsx
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-common/generated/api-types/specialdiet.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/jamix/JamixIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/ChildQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/MealReportUtil.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
- service/src/main/kotlin/fi/espoo/evaka/specialdiet/SpecialDietController.kt
- service/src/main/kotlin/fi/espoo/evaka/specialdiet/SpecialDietQueries.kt
- service/src/main/resources/db/migration/V412__special_diet_foreing_key.sql
- service/src/main/resources/migrations.txt
- service/src/test/kotlin/fi/espoo/evaka/jamix/JamixServiceTest.kt
- service/src/test/kotlin/fi/espoo/evaka/reports/MealReportTests.kt
Tämä muutos lisää 10 minuutin välein ajettavan erityisruokavaliosynkronoinnin Jamix API -> eVaka.
Tämä muutos poistaa Jamix -> eVaka erityisruokavalio synkronoinnista listan siivouksen: Aikaisemmin kaikki POISTA-sanan sisältävät tiedot jätettiin tuomatta eVakaan ja sanat "ätarkasta", "tsek" ja "tsekattava" poistettiin näkyvistä.
Tämä muutos poistaa `special_diets` tietokantataulusta `name` sarakkeen koska Jamix:in nimi tietueet voivat sisältää arkaluontoista tietoa jota emme halua eVakaan.
Käyttöönotto:
Aseta Spring property:
```
evaka.job.sync_jamix_diets.enabled = true
```
> Jamix diet sync

- frontend/src/employee-frontend/components/applications/ApplicationsFilters.tsx
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Hakemushaun valinta "Näytä myös, jos yksikköön on haettu 2. tai 3. toiveena" vaikuttaa nyt myös palvelualue-filtteriin.
> Hakemuksia voi hakea myös toissijaisten toiveiden palvelualueiden perusteella

- service/build.gradle.kts
- service/evaka-bom/build.gradle.kts
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaClient.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
Edellinen kirjasto Fuel käytti pohjalla Javan sisäänrakennettua HTTP-kirjastoa, jossa on monia vajavaisuuksia. Uusi OkHttp-kirjasto tukee mm. Host-headerin yliajamista ja PATCH-kutsujen tekemistä.
> Vaihdetaan Varda-integraation käyttämä HTTP client -kirjasto

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaClient.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
Mikäli jokin toinen lähdejärjestelmä on syöttänyt dataa Vardaan, ja se menee päällekkäin eVakassa olevan datan kanssa, poistetaan vanha data tai asetetaan se päättymään eVakan Varda-datan alkupäivää edeltävään päivään.
Mikäli `evaka.integration.varda.start_date` on asetettu, mikään eVakan Varda-data ei ulotu tätä kauemmas menneisyyteen joten olemassaolevat data katkaistaan päättymään tätä päivää edeltävänä päivänä.
> Päätetään edellisen vaka-järjestelmän Varda-tiedot normaalin Varda-päivityksen yhteydessä

- service/src/main/kotlin/fi/espoo/evaka/reports/MealReportUtil.kt
- service/src/test/kotlin/fi/espoo/evaka/reports/MealReportTests.kt
Esiopetuksen lounastilaukset menivät väärällä ateriakoodilla jos lapsella ei ollut varauksia.
Esiopetuksen lounastilauksessa käytetään oikeaa ateriakoodia myös silloin kun tilataan ns. vakiotilaus, eli aamupala, lounas ja välipala.
> Ruokatilausintegraatio: lounaan ateriatyyppi esiopetuksessa

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
Jos varda-yksikön päivitys epäonnistui jollekin yksikölle, varda-yksikön tunnus jäi tyhjäksi, eikä kyseisen yksikön tilaa haettu tietokannasta oikein.
> Korjaus Varda-yksiköiden vientiin virhetilanteen jälkeen

- service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/Rectangle.kt
- service/src/main/resources/WEB-INF/templates/address-page/address-page.html
- service/src/test/kotlin/fi/espoo/evaka/shared/domain/RectangleTest.kt
Sijainti ja koko säädetään asettamalla seuraava Spring property:
```
evaka.person_address_envelope_window_position = x,y,w,h
```
- `x`: Ikkunan vasemman reunan etäisyys millimetreinä paperin vasemmasta reunasta
- `y`: Ikkunan yläreunan etäisyys millimetreinä paperin yläreunasta
- `w`: Ikkunan leveys millimetreinä
- `h`: Ikkunan korkeus millimetreinä
Jos arvoa ei ole annettu, käytetään arvona `21,55,72,30`, mikä vastaa iPost-ohjeistuksen vastaanottajan osoitteen paikkaa. iPostia käytetään esim. kirjeenä toimitettavissa Suomi.fi-viesteissä.
**HUOM:** Ikkunan reunoille kannattanee jättää hieman tilaa, jottei nimi ja osoite ala täsmälleen ikkunan reunasta vaan hieman sen sisäpuolelta.
> Säädettävä sijainti ja koko henkilön osoitesivun kirjekuori-ikkunalle

- frontend/src/citizen-frontend/calendar/AttendanceInfo.tsx
- frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
- frontend/src/citizen-frontend/calendar/MonthElem.tsx
- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
- frontend/src/citizen-frontend/calendar/hooks.ts
- frontend/src/e2e-test/specs/5_employee/month-calendar.spec.ts
- frontend/src/employee-frontend/components/absences/MonthCalendarTable.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
Lippu on päällä kaikissa tuntipohjaisia palveluntarpeita käyttävissä kunnissa, joten sitä ei enää tarvita.
> Poistetaan `timeUsageInfo` feature flag

- service/src/main/resources/db/migration/R__child_absences_functions.sql
Säännöllisen (ma-pe) varhaiskasvatusajan ei tule sisältää viikonloppuja
> Korjaus päivittäiseen säännölliseen varhaiskasvatusaikaan

- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Normaalisti poissaolot vähentävät tilapäisen vakan päiviä, mutta Tampereen 2024 kesäkerhoja varten ei pitäisi vähentää. Tämä muutos voidaan todennäköisesti poistaa syksyllä.
> Lisätty konfigurointimahdollisuus tilapäisen osa-aikaisen vakan laskukäsittelyyn

- frontend/src/employee-frontend/components/reports/MealReport.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Lisätty "Koko viikko" valinta ruokailijaraporttiin. Kun tämä valittu, niin front-end hakee kaikkien viikonpäivien raportin ja näyttää ne allekkain.
> Koko viikon ruokailijaraportti

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaPlacementsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUnitIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaClient.kt
- service/src/main/resources/db/migration/V417__varda_unit_remove_id.sql
- service/src/main/resources/migrations.txt
- service/src/test/kotlin/fi/espoo/evaka/varda/VardaUnitModelTest.kt
eVakassa oleva yksikkö kohdistuu oikeaan Varda-yksikköön OID:n perusteella. Tämä korjaa Varda-päivityksen yksiköille, jotka on luotu eVakan ulkopuolella, kunhan niiden OID on tiedossa. Jos yksikölle ei ole asetettu OID:ta, luodaan Vardaan uusi yksikkö ja tallennetaan saatu OID. Tämä logiikka on lähempänä sitä, miten lapsen päivitys toimii.
> Varda-yksikköpäivitys perustuu nyt OID:hen

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceBasicsController.kt
Palse-arvon lisääminen palvelutarpeelle jolla ei ollut ennestään yhtään palse-arvoa epäonnistui, koska servicellä tuli null pointer exception
> Korjaus null pointer exceptioniin palse-arvojen luonnissa

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/PersonalData.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Lisätty uusi tausta-ajo sähköposti-ilmoituksen lähettämisestä talouspäätöksen (maksupäätös, arvopäätös) päämiehelle, mikäli tämä ei ole estänyt päätösten lähettämisestä aiheutuvia sähköposti-ilmoituksia asetuksissaan.
Koska kuntalaisen käyttöliittymässä näytetään ainoastaan `Lähetetty` -tilassa olevat talouspäätökset, sähköposti-ilmoitukset on asetettu lähtemään sekä automaattisista, että manuaalisista talouspäätösten siirtymistä `Lähetetty` -tilaan.
HUOM! Vaatii kuntakohtaisen sähköpostikonfiguraation päivittämisen ja oman viestipohjan toteuttamisen.
> Kuntalaisen sähköposti-ilmoituksen lähettäminen uusista talouspäätöksistä

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
- Lähetetään notifikaatio kunnallisista tiedotteista heti (SES:n quotan puitteissa). Aiemmin kunnallisten tiedotteiden notifikaatioiden lähettäminen jaettiin tasaisesti 12 tunnin ajalle.
- Sähköpostin lähetys ei enää epäonnistu vaikka vastaanottajan osoitteen alussa tai lopussa olisi tyhjää
> Parannuksia sähköpostien lähetykseen

- service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Jos async jobeja on paljon ajossa, aiemmin oli mahdollista että Jamix-ruokavaliosynkkejä jäi ajoon monta peräkkäin. Nyt ajamattomat jobit poistetaan ensin.
> Pidetään enintään yksi Jamix-ruokavaliosynkki kerrallaan

- frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
- frontend/proxy/files/etc/nginx/keycloak-proxy.conf.template
Uusi ympäristömuuttuja frontend-imageen: `KEYCLOAK_ADMIN_ALLOWLIST`, esim. `KEYCLOAK_ADMIN_ALLOWLIST=1.2.3.4,5.6.7.8`
> Lisätty keycloak admin-konsolin piilottaminen

- frontend/src/e2e-test/pages/employee/finance/finance-page.ts
- frontend/src/e2e-test/specs/4_finance/payments.spec.ts
- frontend/src/employee-frontend/components/payments/Actions.tsx
- frontend/src/employee-frontend/components/payments/PaymentFilters.tsx
- frontend/src/employee-frontend/components/payments/PaymentsPage.tsx
- frontend/src/employee-frontend/generated/api-clients/invoicing.ts
- frontend/src/lib-common/generated/action.d.ts
- frontend/src/lib-common/generated/api-types/invoicing.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/PaymentsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/PaymentController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/PaymentQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Payments.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PaymentService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- service/src/main/resources/db/migration/V419__payment_confirmed_state.sql
- service/src/main/resources/db/migration/V420__payment_constraint_change.sql
- service/src/main/resources/migrations.txt
Lisätty palvelusetelien maksatuksen käyttöliittymään `Tarkastettu`-tila manuaalisen tarkastamisen kirjanpitoa varten. Tilasiirtymä `Luonnos` -> `Tarkastettu` ei sisällä automaattisia tarkastuksia maksuaineiston laadusta. Lisätty filtteri tilan omaavien aineistojen näyttämiseen ja napit tilaan ja tilasta siirtymisiin. 
Käyttöoikeudet: pääkäyttäjä (ADMIN) ja talouden käyttäjä (FINANCE_ADMIN)
> Tarkastettu-tila palvelusetelien maksuaineistojen maksatukselle eVakasta

- frontend/src/employee-frontend/components/reports/FuturePreschoolersReport.tsx
- frontend/src/employee-frontend/components/reports/queries.ts
- frontend/src/lib-common/generated/api-types/reports.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/FuturePreschoolersReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/FuturePreschoolersReport.kt
Yksiköt monistuivat raportilla, koska tietokantakyselyyn oli jäänyt vanha ryhmäkohtainen paikkojen lukumäärän laskenta. Nyt ryhmien paikat lasketaan yhteen.
Lasten nykyisten yksiköiden raporttiin käytettiin väärää kyselyä. Käli korjattu käyttämään oikeaa dataa.
> Tulevien esikoululaisten raportin bugikorjaus

- frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReport.tsx
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedDecisionsReport.kt
Tuen päätösten raportille on lisätty sarake, jossa näkyy päätösnumero sekä etuliite VK tai EO joka kertoo onko kyseessä varhaiskasvatuksen vai esiopetuksen tuen päätös. Etuliite on tarvittaessa kustomoitavissa (mukaanlukien tyhjäksi stringiksi, jos joku ei jostain syystä halua sitä lainkaan näkyviin).
> Tuen päätösten raportille lisätty päätösnumero ja onko kyseessä varhaiskasvatus vai esiopetus

- frontend/src/employee-frontend/components/document-templates/queries.ts
- frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
- frontend/src/employee-frontend/generated/api-clients/document.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
- service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
- service/codegen/src/main/kotlin/evaka/codegen/api/Controllers.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
- service/src/integrationTest/resources/application-integration-test.yaml
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateController.kt
- service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- service/src/main/resources/application-local.yaml
Samalla poistetaan kaikki lomakepohjaa käyttävät lomakkeet ja niiden asianhallintaprosessit. Julkaisun perumisen jälkeen lomakepohjan voi myös poistaa.
Toiminnallisuus vaatii sekä frontend että backend feature flagin, joita ei kuulu laittaa päälle tuotantoympäristössä:
frontend: `forceUnpublishDocumentTemplate: true`
service env: `EVAKA_NOT_FOR_PROD_FORCE_UNPUBLISH_DOCUMENT_TEMPLATE_ENABLED`
> Pääkäyttäjä voi testiympäristössä peruuttaa lomakepohjan julkaisun

- service/src/integrationTest/kotlin/fi/espoo/evaka/jamix/JamixIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/children/ChildrenQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
- service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/AclQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/specialdiet/SpecialDietQueries.kt
Kun Jamix erityisruokavalioiden synkronoiinti aiheutti jonkin eVakan lapsen erityisruokavalion asetuksen tyhjäksi, siitä jäi vain systeemin lokille viesti joka kertoi kuinka monen lapsen erityisruokavalio oli nollaantunut.
Kunkin yksikön johtajille lähetetään sähköpostilla varoitus jossa on eVaka lapsen tunniste ja aikaisemmin asetettu ruokavalio. Sähköpostit lähetetään vain sellaisista lapsista joilla on voimassaoleva sijoitus.
> Lähetetään varoitus yksikönjohtajille ERV nollaantumisesta

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Kantakyselyyn tehty muutos rikkoi kerhohakemusten hakemisen käyttöliittymään, koska niissä ei ole kannassa extendedCare- json-kenttää. Korjattu toimimaan oikein myös kerhohakemuksille ja mahdollisille muille tapauksille, joissa ko. kenttää ei löydy.
> Korjattu vuorohoidon näyttäminen yksikön johtajalle hakemuslistan tooltipissä

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaClient.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
Toisessa kunnassa päivähoidossa olleiden lasten auki jääneitä Varda-datoja pitää joskus merkitä päättyneeksi. Jostain syystä Vardassa on tietueita, joiden `lahdejarjestelma`-kenttää ei ole asetettu, ja Varda ei suostu päivittämään tällaisten tietueiden voimassaolopäivää, jolle `lahdejarjestelma`-kenttää aseteta samalla.
Tämän muutoksen myötä eVaka asettaa `lahdejarjestelma`-kentän mikäli siihen on tarvetta. Arvoksi asetetaan eVakaan konfiguroitu lähdejärjestelmäkoodi, joka on sinäänsä väärin, koska data ei ole alunperin eVakasta, mutta ei siihen oikein mitään muutakaan voi asettaa 🤷
> Korjaus Varda-tietueiden voimassaoloajan päättämiseen

- frontend/src/employee-frontend/components/reports/MealReport.tsx
Näytettiin väärää viikon päivää
Näytetään oikea viikonpäivä
> Ruokailijaraportin viikonpäivän näytön korjaus

- frontend/src/citizen-frontend/messages/MessageEditor.tsx
> Suurempi tekstikenttä kuntalaisen uusi viesti dialogiin

- frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReportDecision.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
Muutetaan vaka- tuen päätösten logiikka samanlaiseksi kuin esiopetuksessa eli jos nyt hyväksyttävää päätöstä myöhempänä on toinen hyväksytty päätös, niin asetetaan päätös päättymään sitä edellisenä päivänä.
> Vaka- tuen päätöksiin automaattinen päättymispäivä jos tulevaisuudessa on jo toinen päätös

- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
- frontend/src/citizen-frontend/calendar/queries.ts
- frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts
- frontend/src/citizen-frontend/calendar/reservation-modal/form.ts
- frontend/src/citizen-frontend/generated/api-clients/reservations.ts
- frontend/src/e2e-test/generated/api-clients.ts
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
- frontend/src/employee-frontend/components/unit/queries.ts
- frontend/src/employee-frontend/generated/api-clients/reservations.ts
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
Luodaan automaattisesti poissaoloja seuraavissa tapauksissa:
- Kuntalainen tekee toistuvia varauksia tai varauksen yksittäiselle päivälle
- Henkilökunta tekee toistuvia varauksia 
Poissaolojen luonnin säännöt on [dokumentoitu wikissä](https://github.com/espoon-voltti/evaka/wiki/L%C3%A4sn%C3%A4%E2%80%90-ja-poissaolot#poissaolojen-syntyminen-p%C3%A4iv%C3%A4n-l%C3%A4sn%C3%A4oloajasta).
Kuntalaisen kalenteri myös näyttää nyt ensisijaisesti varauksen, kun se ennen näytti ensisijaisesti poissaolon. Poissaolo näytetään vain jos varauksia ei ole lainkaan.
Feature flagin `automaticFixedScheduleAbsences` takana.
> Automaattinen poissaolojen luonti varausten luonnin yhteydessä

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/IsCitizenTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/ActionRule.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGlobalRole.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsEmployee.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsMobile.kt
`isPermittedForSomeTarget` on vain toimintojen näkyvyyteen käytetty käyttöoikeustarkistus, joka oli aiemmin liian salliva, koska se ei yleensä käynyt tietokannassa ajamassa sääntöjen "jälkimmäistä puolta".
Esim. `IsCitizen(allowWeakAuth = false).guardianOfChild()` säännön kanssa tarkistus katsoi vain kirjautumisen tason `IsCitizen(allowWeakAuth)` (a.k.a "Params" toteutuksessa), eikä käynyt kannassa tarkistamassa huoltajuussuhteita `.guardianOfChild()` (a.k.a "Query" toteutuksessa).
Ongelma on korjattu kirjoittamalla toteutus osittain uudestaan ja siirtämällä tarkistusvastuu Params-tyypistä Query-tyyppiin. Koodin määrä vähenee hieman koska voidaan uudelleenkäyttää samaa `queryForParams`-funktiota joka on jo tehty `getAuthorizationFilter`-tarkistusta varten.
> isPermittedForSomeTarget-käyttöoikeustarkastus ei ole enää liian salliva

- frontend/src/employee-frontend/components/finance-basics/ServiceNeedItem.tsx
- frontend/src/employee-frontend/components/finance-basics/VoucherValueEditor.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceBasicsController.kt
- UI validoi nyt ettei palse-arvojen voimassaolojen väleihin saa jäädä aukkoja
- Back end siirtää lisätyn arvon alkamispäivää aiemmaksi, jos sen ja edellisen väliin jäisi aukko
- Korjattu ongelma jossa viimeisin palse-arvo ei ollut editoitavissa tai poistettavissa jos sille oli asetettu päättymispäivä
- Uuden arvon alkamispäivä asetetaan nyt automaattisesti edellisen arvon päättymispäivää seuraavaan päivään, jos edellisen arvon päättymispäivä oli asetettu
> Korjauksia palse-arvoeditoriin

- frontend/src/citizen-frontend/App.tsx
- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-mobile-frontend/App.tsx
- frontend/src/lib-components/atoms/EnvironmentLabel.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
Uusi frontend feature flag `environmentLabel`. Arvon tulisi olla esim `'Staging'` ja tuotannossa `null`.
> Näytetään testiympäristöissä ympäristön nimi jotta erottuu selkeämmin tuotannosta

- frontend/src/employee-mobile-frontend/messages/MessagesPage.tsx
Kun käyttäjä käytti selaimen back-ominaisuutta mobiiliviestinnän viestiketjunäkymässä, sovellus jumittui viestillä "Tietojen haku epäonnistui".
Kun viestiketjunäkymässä painaa back ja ryhmän tunniste vaihtuu, viestinnän ui state vaihdetaan takaisin `list`iksi, jolloin virheellinen viestiketjun lataaminen ei käynnisty.
> Korjaus henkilökunnan mobiiliviestintään back-napin käyttöön

- frontend/src/employee-frontend/components/invoice/InvoiceDetailsSection.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
Uusi optional frontend feature flag invoiceDisplayAccountNumber - voi laittaa falseksi tai jättää asettamatta muualla kuin Espoossa.
> Piilotetaan laskunäkymästä tili ja laskulaji niiltä kunnilta jossa niitä ei käytetä

- service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
Tuen päätökset -raportti näyttää sekä varhaiskasvatuksen että esiopetuksen tuen päätöksiä, mutta raportin linkin näkyvyys valikoitiin vain varhaiskasvatuksen tuen päätöksien perusteella.
Kts. `/employee/reports/assistance-need-decisions`
> Korjaa tuen päätökset -raportin linkin esiopetuksen tuen päätöksille

- service/src/integrationTest/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
Lapselle luodaan poissoloja automaattisesti päivittäisten vaka-aikojen perusteella. Poissolot luodaan vain niille päiville, joina yksikkö on auki. Ennen tätä muutosta kaikille lapsille käytettiin normaaleja aukioloaikoja, jolloin vuorohoitolapsille ei koskaan generoitu poissaoloja viikonlopuille. Tämän muutoksen jälkeen vuorohoitolapsille käytetään yksikön vuorohoitoaikoja aukiolopäivien päättelyyn, jolloin poissaolot generoituvat oikein myös viikonlopuille.
> Otetaan vuorohoito huomioon päivittäisten vaka-aikojen poissaolojen luonnissa

- frontend/src/employee-frontend/components/vasu/templates/MigrateTemplateModal.tsx
- frontend/src/employee-frontend/components/vasu/templates/VasuTemplatesPage.tsx
- frontend/src/employee-frontend/generated/api-clients/vasu.ts
- frontend/src/lib-common/generated/api-types/vasu.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/DocumentMigratorTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateController.kt
Käynnistäessään opetussuunnitelmapohja-->lomakepohja migraation, pääkäyttäjä syöttää myös tehtäväluokan, jota käytetään asianhallintaprosessin migratoimiseen.
> Lisätään metadatan käsittely vasumigraatioon

- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionCitizenController.kt
Endpoint käytti READ_UNREAD_ASSISTANCE_NEED_DECISION_COUNT actionia kun piti käyttää READ_UNREAD_ASSISTANCE_NEED_PRESCHOOL_DECISION_COUNT. Kyseinen endpoint ei kuitenkaan ole tietoturvakriittinen ja molemmissa on ainakin oletuksena samat oikeudet.
> Korjaus käyttöoikeuksiin

- service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt
Ennen:
Migratoidaan päättyneistä vasuista viimeisin huoltajalle julkaistu versio
Jälkeen:
Migratoidaan kaikista viimeisin versio
> Migratoidaan myös julkaisemattomat vasut/leopsit

- .github/dependabot.yml
- compose/docker-compose.yml
- keycloak/.dockerignore
- keycloak/Dockerfile
- keycloak/dd-fetch/pom.xml
Keycloak:issa ei ollut Datadog instrumentointia. Eikä meillä ollut tapaa yhdistää Keycloakin logituksia proxyn request logituksiin.
Keycloak:in logituksiin tulee Datadogin `trace_id` ja `span_id` metadatat näkyviin. Tämän lisäksi requestit trackataan Datadogiin, kunhan Datadog agent asetukset asetetaan infran puolelta ympäristömuuttujilla kohdilleen.
> Datadog seurannan lisäys Keycloak:iin

- frontend/src/lib-common/generated/api-types/vasu.ts
- service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
child_document json:ssa olevat child/guardian id:t eivät välttämättä löydy person taulusta jos hetuttomia on yhdistelty
> Varaudutaan rikkinäisiin henkilöviitteisiin vasu-migraatiossa

- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-start-after-holiday-deadline.spec.ts
- frontend/src/e2e-test/specs/0_citizen/feature-flag-citizen-reservations-intermittent-shif-care.spec.ts
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
Jos lapsen sijoitustyyppi sisältää maksullisen ja maksuttoman osuuden, kuluvan päivän ja tulevaisuuden kokopäivän poissaoloja ei näytetty oikein kuntalaiselle, vaan ensisijaisesti näytettiin varaus.
> Korjataan koko päivän poissaolon näyttäminen kuntalaiselle

- apigw/src/shared/service-client.ts
- frontend/src/employee-frontend/components/ApplicationPage.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ChildDateModal.tsx
- frontend/src/employee-frontend/generated/api-clients/assistance.ts
- frontend/src/employee-frontend/generated/api-clients/attendance.ts
- frontend/src/employee-frontend/generated/api-clients/messaging.ts
- frontend/src/employee-frontend/generated/api-clients/reservations.ts
- frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx
- frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
- frontend/src/employee-mobile-frontend/generated/api-clients/messaging.ts
- frontend/src/lib-common/generated/api-types/attendance.ts
- frontend/src/lib-common/generated/api-types/messaging.ts
- frontend/src/lib-common/generated/api-types/reservations.ts
- service/codegen/src/main/kotlin/evaka/codegen/api/Controllers.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/MockDvvModificationsService.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/SpringMvcConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/MockVardaIntegrationEndpoint.kt
Jos API:sta palauttaa ylätason nullin, Spring palauttaa aina väkisin tyhjän responsen (`Content-Length: 0` ja mahdollisesti `Content-Type: application/json`), eikä esim. `null` joka toimisi JSON-deserialisoinnissa oikein:
- axios tulkitsee sen tyhjänä merkkijonona ja frontissa arvoksi tulee `''`
- Fetch API heittää virheen jos yrittää kutsua `.json()`
Jotta vältytään yllätyksiltä varsinkin axioksen kanssa, kielletään ylätason nullit ja vaaditaan aina jonkinlainen wrapperi.
> Kielletään nullable API response-sisällöt koska Spring toimii oudosti niiden kanssa

- frontend/src/employee-mobile-frontend/App.tsx
- frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx
Tänään- nav link osoitti polkuhierarkiassa paikkaan jonka alle myös Seuraavat päivät -route kuuluu, joten se pysyi aktiivisena.
> Mobiilissa Tänään ja Seuraavat päivät näkyy yhtä aikaa aktiivisina

- frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionReservationModal.tsx
Estää ylimääräisten keskusteluaikojen näyttämisen varausmodaalissa, mikäli kuntalainen on jo varannut lapselle ajan.
> Estä ylimääräisten keskusteluaikojen näyttäminen varausmodaalissa 

- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
Varaukset ja poissaolomerkinnät jotka henkilökunta oli tehnyt mobiilisovelluksen kautta näytettiin virheellisesti kuntalaisen tekeminä varauksina yksikön viikkokalenterissa.
Tällaiset varaukset näytetään henkilökunnan tekeminä.
> Näytetään henkilökunnan mobiilista luodut varaukset henkilökunnan luomina

- frontend/src/citizen-frontend/income-statements/ChildIncomeStatementEditor.tsx
- frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
- frontend/src/citizen-frontend/income-statements/types/body.ts
- frontend/src/citizen-frontend/income-statements/types/form.ts
- frontend/src/e2e-test/pages/citizen/citizen-income.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
- Jos kuntalaisen tulotiedoissa valitaan muu kuin suostumus korkeimpaan maksuun, on päättymispäivä pakollinen ja maksimissaan 1v alkupäivästä päivästä
- Valitaan suostumus korkeimpaan oletusarvoisesti
- Lapsen tulotietojen loppupäivä pysyy valinnaisena
> Tulotietojen päättymispäivä pakolliseksi jos muu kuin suostumus korkeimpaan

- frontend/src/e2e-test/pages/employee/units/unit.ts
- frontend/src/e2e-test/specs/5_employee/unit-calendar-events.spec.ts
- frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
- frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/DiscussionSurveyView.tsx
- frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/survey-editor/DiscussionSurveyForm.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Tuki keskustelukyselyjen otsikon, lisätietojen ja varaustilanteen näyttämiselle tiivistetysti kasvattajan viikko/kuukausi -kalenterissa ja siitä avautuvassa lisätietomodaalissa.
> Tuki keskustelukyselyjen tietojen näyttämiselle kasvattajan kalenterissa

- frontend/src/e2e-test/specs/5_employee/preschool-absence-report.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReport.kt
1. Raportti laski poissaolot yksikön aukiolopäivien ulkopuolelta
2. Raportti laski liittyvän/täydentävän varhaiskasvatuksen poissaolot
> Korjauksia esiopetuksen poissaoloraporttiin

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Ennen tätä muutosta eVaka antoi ilmaisen heinäkuun, jos sijoitus alkoi viimeistään edellisen vuoden syyskuussa.
Tämän muutoksen jälkeen oletuksena aloituksen pitää olla edellisen vuoden elokuussa, mutta sen voi konfiguroida syyskuuksi käyttämällä `FeatureConfig`:in kenttää `freeJulyStartOnSeptember`. Samalla konfiguroidaan Espoo käyttämään syyskuuta.
> Ilmaisen heinäkuun saa jos aloitus oli elokuussa + ilmaisuuden sääntö konfiguroitavaksi

- frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
- frontend/src/citizen-frontend/calendar/DayView.tsx
Ruudunlukijan käyttäjälle ei ollut selvää, että mikä päivä on auki kun siirrytään seuraavaan / edelliseen päivään
Ruudunlukija lausuu valitun päivän kun päivää vaihdetaan. Tämä muutos korjaa myös väärin muotoillun päivän nimen kalenteritaulukon päiväväsoluissa.
> Kuntalaisen kalenterin päivämodaalin saavutettavuusparannuksia

- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementQueriesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementType.kt
Jos haluaa poistaa tietokannasta kertaluontoisesti kaikki kertyneet turhat varaukset ja poissaolot, voi ajaa seuraavat queryt:
```
DELETE FROM attendance_reservation ar
WHERE ar.date > now()::date AND NOT EXISTS(
SELECT FROM placement pl
WHERE pl.child_id = ar.child_id AND daterange(pl.start_date, pl.end_date, '[]') @> ar.date
AND pl.type IN (
'DAYCARE',
'DAYCARE_PART_TIME',
'DAYCARE_FIVE_YEAR_OLDS',
'DAYCARE_PART_TIME_FIVE_YEAR_OLDS',
'PRESCHOOL_DAYCARE',
'PRESCHOOL_DAYCARE_ONLY',
'PRESCHOOL_CLUB',
'PREPARATORY_DAYCARE',
'PREPARATORY_DAYCARE_ONLY',
'TEMPORARY_DAYCARE',
'TEMPORARY_DAYCARE_PART_DAY',
'SCHOOL_SHIFT_CARE'
)
);
```
```
DELETE FROM absence ab
WHERE ab.date > now()::date AND (
(ab.category = 'BILLABLE' AND NOT EXISTS(
SELECT FROM placement pl
WHERE pl.child_id = ab.child_id AND …
```
> Varausten ja poissaolojen siivous sijoitusten muuttuessa

- frontend/src/e2e-test/specs/5_employee/income.spec.ts
- frontend/src/employee-frontend/components/person-profile/income/IncomeItemEditor.tsx
- Ei aseteta nykyistä päivää automaattisesti aloituspäiväksi
- Aina kun alkupäivää muuttaa asetetaan loppupäivä siitä vuoden päähän
- Alku- ja loppupäivä on pakollisia
> Parannuksia tulotietojen aikavälin valintaan

- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedVoucerCoefficientEndOutdatedTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/vouchercoefficient/AssistanceNeedVoucherCoefficientQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Palvelusetelikerroin päätetään automaattisesti yöllisessä ajossa jos
a) sijoitus on päättynyt eilen, tai
b) sijoitus on vaihtunut toiseen yksikköön tästä päivästä alkaen.
> Päätetään palvelusetelikertoimia automaattisesti sijoituksen päättyessä/muuttuessa

- frontend/src/employee-frontend/components/document-templates/template-editor/TemplateSectionModal.tsx
- frontend/src/lib-components/document-templates/question-descriptors/CheckboxGroupQuestionDescriptor.tsx
- frontend/src/lib-components/document-templates/question-descriptors/CheckboxQuestionDescriptor.tsx
- frontend/src/lib-components/document-templates/question-descriptors/DateQuestionDescriptor.tsx
- frontend/src/lib-components/document-templates/question-descriptors/GroupedTextFieldsQuestionDescriptor.tsx
- frontend/src/lib-components/document-templates/question-descriptors/RadioButtonGroupQuestionDescriptor.tsx
- frontend/src/lib-components/document-templates/question-descriptors/StaticTextDisplayQuestionDescriptor.tsx
- frontend/src/lib-components/document-templates/question-descriptors/TextQuestionDescriptor.tsx
Ohjeet ovat välillä hyvinkin pitkiä ja rivinvaihdoilla saa luettavuutta parannettua.
> Lisää lomakepohjien ohjeteksteihin monirivituen

- service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationService.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
Normaalitilanteessa lapsella on sijoitus kalenteritapahtuman aikana, mutta jos tapahtuman ajankohdassa on virhe (esim. vuosiluku menneisyydessä) niin aiemmin sähköposti lähetettiin sijoituksen voimassaolosta riippumatta.
> Ei lähetetä sähköpostia kalenteritapahtumista jos sijoitus on päättynyt

- service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationService.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Sähköposteja tulee lähettää yksi per async job, jotta sähköposteja ei lähetetä liian nopeasti eikä virhetilanteissa montaa kertaa per vastaanottaja. Suurin osa sähköpostia lähettävistä jobeista toimi jo näin, ja tämä PR korjaa loput.
> Korjauksia sähköpostien lähetykseen

- service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
Keskustelukyselyjen ilmoituspostit kohdennettiin sijoituksen, ei ryhmäsijoituksen kautta. Muutos kohdistaa ryhmätason kyselyt ryhmäsijoituksella ja parantaa lähetyksen integraatiotestausta.
> Korjaus uuden keskustelukyselyn huoltajakutsujen kohdentamiseen

- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
If exists an unhandled income statement from the past year with an open ended end date or an end date that is after the expiration date of the income do not send a notification.
> Tulotietomuistutuksen lähetyslogiikan muutos

- frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx
- frontend/src/employee-frontend/components/income-statements/queries.ts
- frontend/src/employee-frontend/query.ts
- frontend/src/lib-common/generated/api-types/incomestatement.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
Lisätään tuloselvitykset-listaan uusi sarake "Tulotieto päättyy", jossa on henkilön viimeisimmän tulotiedon päättymispäivä. Jos tulotietoa ei ole tai päättymispäivä on tyhjä, näytetään "-".
> Lisätään tulotiedon päättymispäivä tuloselvitykset-listaan

- service/src/main/kotlin/fi/espoo/evaka/daycare/CaretakerQueries.kt
Kyselystä puuttuu overlap-tarkistus jonka takia intersektio (`*`-operaattori) voi palauttaa tyhjän daterangen, jota ei tueta koska FiniteDateRange ei pysty kuvaamaan sellaista
> Bugikorjaus käyttöastekyselyyn

- frontend/src/citizen-frontend/calendar/AttendanceInfo.tsx
- frontend/src/citizen-frontend/calendar/MonthlyHoursSummary.tsx
Kun käyttäjä vaihtoi päivänäkymän modaalin päivältä toiselle, front-end kaatui virheeseen
> Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
jos käyttäjällä oli selaimen automaattikäännös käytössä ja "Käytetty palveluntarve" muuttui `usedServiceRanges.length > 0` tyyppisestä `usedServiceRanges.length === 0` tyyppiseksi tai toisinpäin.
Frontti ei kaadu, koska React ei koita poistaa sellaisia `TextNode`ja Dom:ista jotka selaimen käännöstoiminto on hävittänyt sieltä.
> Parannuksia päivämodaalin yhteensopivuuteen selaimen käännöstoiminnon kanssa

- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
Korjaa osapäivän poissaolojen käsittelyn Päiväkohtaiset lapsen tulo- ja lähtöajat -raportilla sekä yksikön reealiaikaisen käyttöasteen graafissa.
> Korjataan osapäivän poissaolojen käsittely raportilla ja yksikön käyttöastegraafissa

- frontend/src/lib-components/atoms/form/MultiSelect.tsx
https://github.com/user-attachments/assets/04c72327-1543-4934-961a-ffbab9768396
Ms Edge selaimen automaattikäännösominaisuutta käyttäessä koko front-end sovellus kaatui kun MultiSelect:in drop-down suljetaan.
Kun Ms Edgen automaattikäännosominaisuuden käyttö havaitaan, MultiSelect käyttää tyhjiä aria live viestejä joka workaroundaa [react-selectin ongelman](https://github.com/JedWatson/react-select/issues/5816)
> MultiSelect-komponentin yhteensopivuus selaimen automaattikäännöksen kanssa

- frontend/src/e2e-test/pages/employee/reports.ts
- frontend/src/e2e-test/specs/5_employee/child-attendance-reservation-report.spec.ts
- frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx
- frontend/src/employee-frontend/components/reports/queries.ts
- frontend/src/employee-frontend/generated/api-clients/reports.ts
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-common/time-range-endpoint.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportByChildTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
- Näytetään myös poissaolevat lapset ja lapset ilman varauksia
- Näytetään vain tulossa olevat lapset jos kellonaikasuodatus on päällä
- Näytetään oikein lapset joilla on osapäivän poissaolo
- Lisätty Hae-nappi josta varsinainen raportin haku tehdään
> Korjauksia lapsikohtaiset läsnäoloajat -raporttiin

- frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
- frontend/src/citizen-frontend/income-statements/types/form.ts
- frontend/src/e2e-test/pages/citizen/citizen-income.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- Oletusarvoisesti ei ole mikään tulotyyppi valittuna
- Jos muu kuin suostumus ja päivämääräväli yli vuoden näytetään ohje että väli voi olla maksimissaan vuosi 
- Aloituspäivä voi olla maksimissaan vuoden menneisyydessä
> Kuntalaisen tuloselvityksen parannuksia

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaClient.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
Hetuttomat lapset pitää luoda Vardaan käsin eVakan ulkopuolella, ja näin saatu OPH OID kopioida eVakassa lapsen tietoihin. Tähän mennessä eVakan Varda-integraatio on sitten löytänyt hetuttoman lapsen tiedot Vardan `POST /v1/hae-henkilo/`-rajapintaa käyttäen ja voinut sitä kautta saadun "kahvan" perusteella lähettää lapsen tiedot Vardaan.
`POST /v1/hae-henkilo/` ei jostain syystä enää löydä tällä tavoin luotuja lapsia, joten käytetään tästedes `POST /v1/henkilot/`-rajapintaa. Kyseinen rajapinta vaatii hetun tai OID:n lisäksi henkilön nimen, mutta vaikuttaa siltä että nimen ei tarvitse täsmätä Vardassa olevaan nimeen kun OID on annettu, joten nimen muuttuminen ei aiheuta Varda-viennin epäonnistumista.
> Lähetetään hetuttomat lapset Vardaan eri tavalla

- frontend/src/e2e-test/specs/5_employee/preschool-absence-report.spec.ts
- frontend/src/employee-frontend/components/reports/PreschoolAbsenceReport.tsx
Kyseisellä raportilla ainoastaan toteuma kiinnostaa, ei suunnitelma.
> Poistaa esiopetuksen poissaoloraportilta tulevaisuuden poissaolot

- frontend/src/e2e-test/pages/employee/units/unit-calendar-page-base.ts
- frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
- frontend/src/employee-frontend/components/unit/queries.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
- frontend/src/employee-frontend/generated/api-clients/attendance.ts
- frontend/src/lib-common/generated/api-types/attendance.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
Jos käyttäjällä oli avoin läsnäolokirjaus toisessa yksikössä, uuden kirjauksen tallennus epäonnistui ilman virheviestiä
Käyttäjälle näytetään varoitusviesti läsnäolokirjausdialogissa kun valittuna on avoimen kirjauksen päivä tai sitä myöhempi päivä. Varoitusviesti sisältää linkin suoraan k.o. yksikön kalenteriin oikealle päivälle.
> Varoitetaan toisessa yksikössä olevista avoimista kirjauksista

- frontend/src/lib-customizations/espoo/featureFlags.tsx
Itse ominaisuus on toteutettu PR:ssä #5300
> Automaattinen poissolojen luonti varausten luonnin yhteydessä päälle Espoon tuotannossa

- frontend/src/e2e-test/pages/employee/finance/finance-page.ts
- frontend/src/e2e-test/specs/4_finance/income-staments.spec.ts
- frontend/src/employee-frontend/components/common/Filters.tsx
- frontend/src/employee-frontend/components/income-statements/IncomeStatementFilters.tsx
- frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx
- frontend/src/employee-frontend/components/income-statements/queries.ts
- frontend/src/employee-frontend/query.ts
- frontend/src/lib-common/generated/api-types/incomestatement.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
- service/src/main/resources/db/migration/V436_income_statement_and_income_indexes.sql
- service/src/main/resources/migrations.txt
* Lisätään tuloselvitykset-listaan uusi sarake "Tulotieto päättyy", jossa on henkilön viimeisimmän tulotiedon päättymispäivä. Jos tulotietoa ei ole tai päättymispäivä on tyhjä, näytetään "-". Listan voi järjestää tämän sarakkeen mukaan.
* Tuloselvitykset-listan hakufiltterien päivittäminen tapahtuu Hae-nappia painamalla. Tällä vältetään turhia hakuja taustajärjestelmään.
* Teknisiä parannuksia tuloselvityslistan suorituskykyyn.
Edellinen versio (#5604) aiheutti niin paljon tietokantakuormaa, että se piti revertoida.
> Näytetään tulotiedon päättymispäivä tuloselvitykset-listassa, versio 2

- frontend/package.json
- frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
- frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
- frontend/src/employee-frontend/components/common/AutosaveStatusIndicator.tsx
- frontend/src/employee-frontend/components/reports/Occupancies.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraphPlanned.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraphRealized.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyGraph.tsx
- frontend/src/employee-frontend/utils/use-autosave.ts
- frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx
- frontend/src/employee-mobile-frontend/staff-attendance/StaffMarkArrivedPage.tsx
- frontend/src/lib-common/date.spec.ts
- frontend/src/lib-common/date.ts
- frontend/src/lib-common/helsinki-date-time.spec.ts
- frontend/src/lib-common/helsinki-date-time.ts
- frontend/yarn.lock
- Käytetään `HelsinkiDateTime`, `LocalDate` ja `LocalTime` -luokkia ajan ja päivämäärän tekstimuunnoksiin joka paikassa
- Lisätään muutama testi ja kojataan pieni bugi `HelsinkiDateTime`-toteutuksessa
- Otetaan date-fns:n virallinen aikavyöhyketuki `@date-fns/tz` käyttöön
> Parannuksia päivämäärien ja aikojen käsittelyyn

- frontend/package.json
- frontend/src/lib-common/helsinki-date-time.ts
- frontend/yarn.lock
Uudempi `@date-fns/tz`-kirjasto toimii vasta Chrome Mobile versio 95:llä ja uudemmilla (vuodelta 2021). Ainakin Espoossa näyttää olevan yhä vanhempia selaimia käytössä.
This reverts commit 125e54e07ca00aea0a1b9e3a501c2aca4c5834c2.
> HOTFIX: Vaihdetaan takaisin `date-fns-tz`-kirjastoon

- frontend/src/e2e-test/pages/mobile/staff-page.ts
- frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
- frontend/src/employee-frontend/generated/api-clients/attendance.ts
- frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
- frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx
- frontend/src/employee-mobile-frontend/staff-attendance/queries.ts
- frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsEmployee.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsMobile.kt
Jos käyttäjällä oli avoin läsnäolokirjaus toisessa yksikössä, uuden kirjauksen tallennus epäonnistui ilman virheviestiä
Käyttäjälle näytetään varoitusviesti läsnäolokirjaus näkymässä ja "Kirjaudu läsnäolevaksi" nappi ei ole aktiivinen.
> Varoitetaan toisessa yksikössä olevista avoimista kirjauksista mobiilissa

- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReport.kt
Raportilla ei saa näkyä poissaolot, jos esiopetus on tauolla.
> Korjataan esiopetuksen poissaoloraportti opetustauoilla

- frontend/src/e2e-test/pages/employee/reports.ts
- frontend/src/e2e-test/specs/5_employee/non-ssn-children-report.spec.ts
- frontend/src/employee-frontend/components/reports/NonSsnChildren.tsx
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/NonSsnChildrenReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/NonSsnChildrenReportController.kt
Hettutomat lapset -raportin Varda-tiedot eivät päivittyneet oikein, koska raportti käytti vanhan Varda-integraation tietokantatauluja.
Otetaan uuden integraation tiedot käyttöön, ja näyteään raportilla viimeisin onnistunut Vardaanvientiaika.
> Näytetään Varda-tila oikein Hetuttomat lapset -raportilla

- frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
- frontend/src/citizen-frontend/calendar/DayElem.tsx
- frontend/src/employee-frontend/components/Header.tsx
- frontend/src/lib-components/atoms/buttons/LinkButton.tsx
- frontend/src/lib-components/layout/Container.tsx
- frontend/src/lib-components/molecules/DatePickerDeprecated.tsx
- frontend/src/lib-components/molecules/Tabs.tsx
Taskina lisätä focus-tyyli kalenterinäkymään. Ominaisuus toteutettu aikaisemmin, hajonnut styled-components -kirjaston päivityksen 5 -> 6 yhteydessä ( https://styled-components.com/docs/faqs#nested-syntax-handling ), selector ei kohdistu oikein ilman &-merkkiä.
Osassa focus-tyyli toimi ainakin osittain tästä huolimatta.
Ennen | Jälkeen
--- | ---
Käyty läpi muutkin kohdat joissa focus- yms user-action pseudo-selectorit jääneet "piiloon" päivityksen myötä. Muokatun Tabs-komponentin desktop-näkymä ei tällä hetkellä käytössä.
Ennen | Jälkeen
--- | ---
DayElem | 
Header | 
LinkButton | 
Container / TitleContainer | 
DatePicker | 
(edit) DatePickerissä oli pelkkä alleviivaus korostettuna, nyt samanlainen focus kuin muissa inputeissa
> Focus-tyylien palauttaminen

- frontend/src/e2e-test/pages/employee/units/unit-calendar-page-base.ts
- frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
- frontend/src/employee-frontend/components/unit/queries.ts
- frontend/src/employee-frontend/components/unit/tab-unit-information/Occupancy.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupanciesForSingleDay.tsx
- frontend/src/employee-frontend/generated/api-clients/occupancy.ts
- frontend/src/lib-common/generated/api-types/occupancy.ts
- frontend/src/lib-components/atoms/dropdowns/TreeDropdown.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancy.kt
- Parannetaan puu-valitsimen ulkonäköä
- Näytetään oletuksena suunnitelma (ennen näytettiin toteuma)
- Piilotetaan lakkautetut ryhmät ryhmävalikosta
- Sallitaan useamman kuin yhden ryhmän valinta yhtä aikaa:
> Yksikön täyttö- ja käyttöastegraafin parannuksia

- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
- frontend/src/employee-frontend/generated/api-clients/attendance.ts
- service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Työntekijän desktop-versio varoitti myös samassa yksikössä olevista avoimista kirjauksista
Varoitus näytetään vain toisessa yksikössä olevista avoimista korjauksista.
Tämä muutos korjaa myös näppäilyvirheen open attendances routen pathissä ja sallii avoimien kirjausten haun pääkäyttäjälle
> Varoitetaan avoimista kirjauksista vain jos ne ovat toisessa yksikössä

- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- Hakemus on kiireellinen -> Hakemus on kiireellinen (ei koske siirtohakemuksia)
- Korjattu väärä ruotsinnos
> Tekstipäivityksiä

- frontend/package.json
- frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionReservationModal.tsx
- frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionSurveyModal.tsx
- frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceApplications.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/notes/NotesModal.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/DaycareAclAdditionModal.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/EmployeeAclRowEditModal.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceExternalPersonModal.tsx
- frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
- frontend/src/lib-components/molecules/modals/BaseModal.tsx
- frontend/src/lib-components/molecules/modals/ModalBackground.tsx
- frontend/yarn.lock
Modaalit kuten päiväkirjan yksittäisen päivän tarkastelu, “Ilmoita läsnäolo”, ja “Ilmoita poissaolo” ja poiston varmistukset (esim. Tuloselvityksen ja hakemuksen poiston varmistus) pitäisi olla suljettavissa Esc-näppäimellä.
> Lisätään modaalien sulkeminen esc-näppäimellä

- frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/DayElem.tsx
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-calendar.spec.ts
Päiväeditoria suljettaessa kohdistus hävisi kalenterista
Asetetaan kohdistus kalenterissa oikealle päivälle kun päiväeditori-modaali suljetaan
https://github.com/user-attachments/assets/6450913e-131d-4816-a7b6-35bfe3f41b57
https://github.com/user-attachments/assets/d914a966-15d5-4797-bf34-6c987f76f37b
> Päiväeditorin sulkeminen kohdistaa kalenteripäivään

- frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
Tulostettaessa pedagoginen arvio selaimen tulostustoiminnolla, saattoivat toimintopainikkeet ja asiakirjan julkaisun tila jäädä tulosteessa muun sisällön päälle:
Korjauksen jälkeen toimintopainikkeet ja asiakirjan julkaisun tila tulostetaan lomakkeen loppuun:
Korjaus, jossa julkaisun tila olisi näytetty asiakirjan lopussa ja nappeja ei olisi näytetty ollenkaan, olisi ollut hieman työläämpi korjaus, joten siksi korjattu näin.
> Näytetään pedagogisen arvion toimintopainikkeet tulosteessa lomakkeen lopussa eikä sisällön päällä

- frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
- frontend/src/lib-common/generated/api-types/placement.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerationForDataChangesIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerationForDataChangesIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/FiveYearOldDaycarePlacementsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/Placement.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementTermination.kt
- service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationController.kt
- service/src/main/resources/db/migration/V441__placement_modification_user_and_timestamp.sql
- service/src/main/resources/migrations.txt
> Näytetään työntekijälle sijoituksen viimeisimmän muokkauksen aikaleima ja tekijä

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/generated/api-types.ts
- frontend/src/e2e-test/pages/employee/assistance-need-decision/assistance-need-decision-edit-page.ts
- frontend/src/e2e-test/specs/5_employee/assistance-need-decision.spec.ts
- frontend/src/employee-frontend/components/child-information/AssistanceNeedDecisionSection.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionEditPage.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
- frontend/src/lib-common/generated/api-types/assistanceneed.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/espoo/bi/EspooBiTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AssistanceNeedDecisionsReportTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AssistanceNeedDecisionAccessControlTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecision.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V442__assistance_need_decision_no_end_date.sql
- service/src/main/resources/migrations.txt
> Tuen päätöksen tukipalveluiden voimassaoloaika valinnaiseksi

- frontend/src/e2e-test/pages/employee/units/unit-month-calendar-page.ts
- frontend/src/e2e-test/specs/5_employee/month-calendar.spec.ts
- frontend/src/employee-frontend/components/absences/StaffAttendance.tsx
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/StaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/StaffAttendanceService.kt
Aikaisemmin jos *Henkilökuntaa paikalla* -kenttään syötetyn arvon tyhjensi, tällä ei ollut mitään vaikutusta. Sen sijaan kentässä aikaisemmin ollut arvo jäi voimaan.
Korjauksen jälkeen kentän tyhjentäminen poistaa *Henkilökuntaa paikalla* -tiedon. Jos samalle päivälle on olemassa ei-kasvatusvastuullisten henkilöiden paikallaolotieto, ei *Henkilökuntaa paikalla* tietoa voi poistaa. Tässä tilanteessa kentän tyhjentäminen antaa *Henkilökuntaa paikalla* -tiedolle arvon 0.
> Henkilökunnan ei-reaaliaikaisen läsnäolokirjauksen voi tyhjentää

- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
- service/src/main/resources/db/migration/V443__calendar_event_indexes.sql
- service/src/main/resources/migrations.txt
- replace NOT MATERIALIZED with MATERIALIZED. A single guardian has a small amount of children and a relatively small amount of placements, so we *want* to materialize to prevent the query planner from trying to be too clever
- replace useless calendar_event.type index
- add missing indexes (calendar_event_time.calendar_event_id is the most important)
> Parannetaan kalenteritapahtumien tietokantakyselyiden suorituskykyä

- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/FamilyDaycareMealReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/FamilyDaycareMealReport.kt
Toisella perhepäivähoitajalla varahoidossa oleva lapsi nousee perhepäivähoidossa olevien lasten ateriaraportille.
Aiemmin ateriamääriä ei huomioitu raportissa, jos siirtyi toiselle perhepäivähoitajalle varahoitoon.'
Kuvassa näkyy vanha ja uusi toiminnallisuus.
> Toisella perhepäivähoitajalla varahoidossa oleva lapsi nousee perhepäivähoidossa olevien lasten ateriaraportille

- frontend/src/citizen-frontend/messages/MessageEditor.tsx
Ennen muutosta viestieditori skrollasi muun sivun mukana.
Muutoksen jälkeen viestieditori pysyy paikallaan oikeassa alakulmassa.
> Kuntalaisen uuden viestin editori pysyy paikallaan skrollatessa

- service/build.gradle.kts
- service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/config/XroadSoapClientConfig.kt
Se aiheutti OWASP-virheen, eikä koko riippuvuutta edes tarvita.
> Estetään `org.opensaml`-riipuvuuden asentaminen servicessä

- frontend/src/lib-components/atoms/form/MultiSelect.tsx
Käytettävyysparannus kuntalaisen uuden viestin luomisen vastaanottajavalintaan.
Kytketään päälle `react-select` komponentin toiminnallisuus, joka mahdollistaa tehtyjen valintojen poiston käyttäen `Backspace` ja `Delete` näppäimiä ([github](https://github.com/JedWatson/react-select/blob/a8b8f4342cc113e921bb238de2dd69a2d345b5f8/packages/react-select/src/Select.tsx#L1591-L1601)). Vaikuttaa `Multiselect`-komponenttiin (23 käyttöpaikkaa).
> Aktivoi valintojen poisto backspace ja delete näppäimillä monivalintakomponentissa

- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/messages/MessagesPage.tsx
- frontend/src/citizen-frontend/messages/ThreadList.tsx
- frontend/src/citizen-frontend/utils/focus.ts
- frontend/src/e2e-test/pages/citizen/citizen-messages.ts
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
- frontend/src/e2e-test/utils/page.ts
- frontend/src/lib-components/atoms/buttons/LegacyButton.tsx
Ennen muutosta:
Uuden viestin lähetyksen jälkeen focus meni päätasolle.
Muutoksen jälkeen:
Asetetaan kohdistus "Uusi viesti" -nappiin, josta toiminto avattiin.
https://github.com/user-attachments/assets/b3223ef3-fd59-4161-99dc-56e1b145a25c
> Viestinäkymän kohdennuksen palautus

- frontend/src/citizen-frontend/messages/ThreadView.tsx
- frontend/src/lib-common/utils/scrolling.ts
- frontend/src/lib-components/atoms/form/TextArea.tsx
- frontend/src/lib-components/messages/MessageReplyEditor.tsx
Ennen muutosta:
https://drive.google.com/file/d/1-eL2YvbmqrWjgKcJ5yJHGw7ihkD2lxDQ/view
Muutoksen jälkeen:
https://github.com/user-attachments/assets/09c58d35-5667-4fa7-862b-07b1be0ae8dc
Ts. periaatteena on, että ruutua vieritetään niin, että viestieditorin alareuna on ruudun alareunan tasalla. Tämä mahdollistaa mahdollisimman monen viestiketjun aikaisemman viestin näkymisen viestieditorin ollessa auki.
Jos viestieditori mahtuu ruudulle ilman vierittämisen tarvetta, vieritystä ei kuitenkaan tapahdu:
https://github.com/user-attachments/assets/24911ab8-cc9d-4a33-afe6-2a199ec45371
> Kuntalaisen vastatessa viestiin viestikenttä avautuu ruudulle näkyviin kokonaisuudessaan

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/DaysInRangeSqlTest.kt
- service/src/main/resources/db/migration/V444__better_days_in_range.sql
- service/src/main/resources/migrations.txt
> Parannetaan `days_in_range` SQL-funktiota, korjataan samalla regressio

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
Ennen muutosta ryhmän päättymispäivää ei huomioitu lähetettäessä henkilökunnan kopioita tiedotteista, joten tiedotteet päätyivät myös päättyneen ryhmän postilaatikkoon.
Muutoksen jälkeen päättymispäivä huomioidaan, ja ryhmän päättymispäivästä alkaen tiedotteet eivät mene ryhmän postilaatikkoon. Ryhmän alkamispäivää ei edelleenkään huomioida, joten tiedotteet menevät ryhmiin, jotka on jo perustettu, mutta joiden alkupäivä on tulevaisuudessa.
> Tiedotteita ei lähetetä suljettuihin ryhmiin

- frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
Testattu espoon stagingissa, lokitettu arvo näyttää esim. tältä: `Root=1-67077aac-078f7c753dea42f761b4ad78`
> Lokitetaan X-Amzn-Trace-Id (AWS trace ID) proxy:ssä

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Ryhmän lakkautuspäivällä tarkoitetaan ryhmän viimeistä toiminnassaolopäivää. Tästä syystä tiedotteiden lähetyksen pitää olla mahdollista vielä sinä päivänä.
> Korjaus tänään lakkautettaviin ryhmiin lähetettäviin tiedotteisiin

- frontend/src/citizen-frontend/calendar/TimeRangeInput.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
- frontend/src/lib-components/atoms/buttons/icon-only-button-visuals.tsx
- frontend/src/lib-components/atoms/form/InputField.tsx
- frontend/src/lib-components/atoms/form/TimeInput.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
*"Merkitse poissaolevaksi"-toiminnosta feedback ruudunlukijalle*:
Kun käyttäjä valitsee “Merkitse poissaolevaksi”, painettu nappi poistuu DOMista ja näppäimistö fokus siirtyy sivun päätasolle ja ruudunlukija sanoo tämän seurauksena sivun otsikon “Varhaiskasvatus, Web content”.
*Läsnäolorivin lisäämisestä ei kerrota ruudunlukijalle*:
Kun käyttäjä valitsee ➕  - Lisää [toinen aikaväli], näppäimistö focus tulee siirtää ilmestyvään ajanjakson alkukenttään. Tämän lisäksi toisen aikavälin input-kenttien ruudunlukijalle näkyviä labeleita täytyy parantaa.
> Läsnäolomodaalin saavutettavuusparannuksia

- service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationService.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Lapsen nimi ja keskustelun aihe poistettu seuraavista sähköposteista:
- keskusteluajan varausilmoitus
- keskusteluajan peruutusilmoitus
- keskusteluajan muistutus
> Keskustelun aihe ja lapsen nimi poistettu keskusteluajan sähköposteista

- frontend/src/citizen-frontend/map/api.ts
Ennen: jos yksikkö-array oli tyhjä, syntyi virheellinen kysely joka tehtiin silti Digitransit API:in
Nyt: jos yksikkö-array on tyhjä, ei tehdä kyselyä vaan palautetaan heti tyhjä lopputulos
> Estetään tyhjät kyselyt Digitransit API:in

- frontend/src/employee-frontend/components/UnitFeaturesPage.tsx
Sivun asettelua on muutettu siten, että vaakasuuntainen vierityspalkki on koko ajan näkyvissä.
Video pieneltä 1024x768 -kokoiselta näytöltä:
https://github.com/user-attachments/assets/72f2a360-dab4-4416-b9f4-926664451939
Näkymä isolla näytöllä:
> Skrollauksen helpottaminen Toimintojen avaus -sivulla 

- service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Jos paperihakemus on luotu käyttäen "Piilota hakemus huoltajalta" -toimintoa, näkyy siitä muodostettu päätös kuitenkin huoltajalle. Tämä korjaa siihen liittyvän laskurin, joka näkyy palvelun ylänavigaatiossa.
> Korjattu piilotetun hakemuksen päätökset-laskuri

- frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/times-calendar/CalendarEventTimeReservation.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Teksti- ja ikoniparannuksia, sekä päivitys pois deprekoitujen komponenttien käytöstä.
> Parannuksia keskusteluaikojen kasvattajan käyttöliittymän muokkaustyökalujen indikointiin

- frontend/src/e2e-test/pages/employee/units/unit-calendar-page-base.ts
- frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
> Korjaus kasvatusvastuullisuustiedon päivitykseen tuntikirjauksen yhteydessä

- frontend/src/citizen-frontend/generated/api-clients/pis.ts
- frontend/src/citizen-frontend/personal-details/NotificationSettingsSection.tsx
- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/generated/api-types.ts
- frontend/src/e2e-test/pages/citizen/citizen-personal-details.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-personal-details.spec.ts
- frontend/src/lib-common/generated/api-types/pis.ts
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/emailclient/EmailTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonalDataControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationService.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/NewCustomerIncomeNotification.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotifications.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/PersonalData.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/PersonalDataQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonalDataControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/MissingHolidayReservationsReminders.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/MissingReservationsReminders.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V453__email_message_type.sql
- service/src/main/resources/migrations.txt
- migratoitu kantaan `enabled_email_types text[]` tilalle `disabled_email_types email_message_type[] not null`
- yhdistetty osa tyypeistä keskenään, jotta kuntalaiselle ei tule liian pitkää listaa valintoja
- ei-kunnalliset (johtajan lähettämät) tiedotteet lasketaan jatkossa kuuluvan henkilökunnan lähettämiin viesteihin
> Korjauksia ja parannuksia sähköpostinotifikaatioiden blokkaukseen

- frontend/src/e2e-test/pages/employee/reports.ts
- frontend/src/e2e-test/specs/5_employee/ended-placements-report.spec.ts
- frontend/src/e2e-test/specs/5_employee/starting-placements-report.spec.ts
- frontend/src/employee-frontend/components/Reports.tsx
- frontend/src/employee-frontend/components/reports/EndedPlacements.tsx
- frontend/src/employee-frontend/components/reports/StartingPlacements.tsx
- frontend/src/lib-common/generated/api-types/reports.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/StartingPlacementsReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/EndedPlacementsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/StartingPlacementsReport.kt
Henkilötunnustiedot poistettu molemmilta raporteilta. Tarvittaessa ne ovat nähtävissä seuraamalla lapsen nimen linkkiä lapsen tiedot sivulle.
Lisätty myös yksinkertaiset testit raporttien toiminnan varmistamiseen.
> Poistettu henkilötunnuksen näkyminen Varhaiskasvatuksessa aloittavat/lopettavat raporteilta

- frontend/src/employee-frontend/components/reports/Raw.tsx
- frontend/src/lib-common/generated/api-types/reports.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/RawReportControllerTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
Lisäksi korjaa "Palveluntarve merkitty" -kentän, jos esim. palveluntarve kulkeutuu hakemukselta sijoitukselle (jolloin `service_need` -taulun `confirmed_by` & `confirmed_at` on `null`).
> Lisätään raakaraportille palveluntarve

- frontend/src/citizen-frontend/messages/MessageEditor.tsx
- frontend/src/citizen-frontend/messages/MessagesPage.tsx
- frontend/src/citizen-frontend/messages/ThreadView.tsx
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/SystemControllerCitizenTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlCitizen.kt
Viestien toiminnallisuuteen on tehty seuraavia muutoksia.
- Kuntalaisella on pääsy viestihistoriaan aina, kun kuntalaisen lapselle löytyy sijoitus eVakasta. Sijoitus voi olla tulevaisuudessa, voimassa oleva tai päättynyt.
- Uuden viestin kirjoittaminen on sallittua kaksi viikkoa ennen sijoituksen alkua sijoituksen loppupäivään asti. Vastaanottajien on liityttävä tällaiseen sijoitukseen.
- Varasijoituksen aikana on mahdollista lähettää viesti varsinaiseen yksikköön. Varasijoitusyksikköön voi viestittää kaksi viikkoa ennen varasijoitusta varasijoituksen loppuun asti.
- Vanhoihin viestiketjuihin vastaaminen on estetty, mikäli kuntalaisella ei enää ole em. sääntöjen perusteella oikeutta lähettää viestiä kaikille viestiketjun vastaanottajille.
> Muutoksia viestien näkyvyyteen ja sallittuihin vastaanottajiin

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
Sen sijaan että jokaisen lapsen kohdalla kysyttäisiin "onko tämän lapsen lasku ilmainen tässä kuussa", kysytään aluksi "anna kaikki tämän kuun ilmaiset lapset" ja käytetään sitä dataa laskujen generoinnissa.
Tämä mahdollistaa laskujen generoinnin ajamisen tietokantatransaktion ulkopuolella.
> Parannetaan `InvoiceGenerationLogicChooser`-rajapintaa

- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
- service/src/main/resources/db/migration/R__application_view.sql
- service/src/main/resources/db/migration/V456__legacy_assistance_need_tables.sql
- service/src/main/resources/migrations.txt
Nämä taulut ovat olleet käyttämättömänä 2023 syksystä lähtien. Poistetaan myös `application_view` sarake joka ei ole käytössä ja on katsonut muutenkin väärää taulua
> Poistetaan vanhat käyttämättömät tuen tarpeen tietokantataulut

- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
- frontend/src/lib-components/assistance-need-decision/AssistanceNeedDecisionReadOnly.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/sv.tsx
Muuttaa toimivaltatekstin kustomoinnin käyttämään ReactNode funktiota.
Vaatii kaikkien kuntien tekstikustomoinnin `assistanceNeedDecision.jurisdictionText` käännösavaimen muuttamisen funktio-muotoon `employee` ja `citizen` käyttöliittymiin (fi,sv).
> Mahdollistettu varhaiskasvatuksen tuen päätöksen toimivalta-tekstin muotoilu

- .github/workflows/validate-labels.yml
- bin/validate-labels.js
Pull request labels drive the weekly changelog generation, which in turn aids in demo preparations. Having correct labels is important.
Add a workflow that enforces our label rule:
Each pull request must have exactly one of the following labels:
- `no-changelog`
- `breaking`
- `enhancement`
- `bug`
- `tech`
- `dependencies`
Other labels are ignored in validation.
> Validate pull request labels

- frontend/src/citizen-frontend/calendar/CalendarMonthView.tsx
- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/DayElem.tsx
- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
- frontend/src/citizen-frontend/calendar/hooks.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-show-service-usage.spec.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-start-after-holiday-deadline.spec.ts
- frontend/src/lib-components/molecules/TimedToast.tsx
- frontend/src/lib-components/molecules/Toast.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
_Ennen muutosta_:
Kuntalaisen kalenterinäkymä oli skrollattavissa haetun ajanjakson (nykyhetkestä kuukausi taaksepäin -> n.vuosi eteenpäin) verran.
_Muutoksen jälkeen_:
Saavutettavuusraportin ehdotusten pohjalta näytetään kalenterissa kuukausi kerrallaan.
- kalenteria voi navigoida sen ylläolevista napeista
- siirretty poissa- ja läsnäolojen palkki sivun alalaidasta kalenterin yläpuolelle
- näytetään myös mahdolliset edellisen ja seuraavan kuukauden päivät kalenterilla, jos niitä osuu kuukauden ensimmäiselle ja viimeiselle viikolle
- menneisyyden päivistä poistettu haalea overlay, vaihdettu taustaväri kontrastiltaan riittävän harmaaksi
- vaihdettu notifikaation box-shadow outlineksi - saavutettavuus korjaus toastin erottumiseksi taustasta
> Kalenterin kuukausinäkymä

- frontend/src/e2e-test/pages/employee/units/unit-discussion-survey-page.ts
- frontend/src/e2e-test/specs/5_employee/unit-calendar-events.spec.ts
- frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/DiscussionSurveyView.tsx
- frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/InviteeSection.tsx
- frontend/src/employee-frontend/components/unit/tab-calendar/queries.ts
- frontend/src/employee-frontend/generated/api-clients/calendarevent.ts
- frontend/src/lib-common/generated/api-types/calendarevent.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEvent.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventController.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
Keskusteluaikavarausten näkymän osallistujaosion lapsiluetteloa on parannettu ja lisätty varauksen omaaville nappi kaikkien varattujen aikojen poistamiseen.
Tämä mahdollistaa varausten poistamisen myös menneisyydestä. Ainoastaan tulevaisuudessa olevista poistettavista varauksista lähetetään peruutus-sähköpostit huoltajille.
> Kasvattajalle mahdollisuus poistaa lapsen kaikki yhden kyselyn keskusteluaikavaraukset kerralla

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/generated/api-types.ts
- frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
- frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
- frontend/src/e2e-test/specs/7_messaging/municipal-messaging.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/DraftQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/AclQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Muutoksen jälkeen työntekijä ei näe viestiketjuja, jotka on lähetetty aikaisemmin kuin viikkoa ennen ryhmään luvitukseen päivämäärää. Yksikön esimies näkee kuitenkin edelleen koko ryhmäpostilaatikon viestihistorian.
> Rajoitetaan uuden työntekijän näkemiä ryhmäpostilaatikon viestejä

- service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/MockSfiMessagesRestEndpoint.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClientIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClient.kt
`/v1/change-password`:
- palauttaa 400 jos access token on vanhentunut -> okhttp:n authenticator-mekanismi ei toimi koska se vaatii 401-koodin
- ei näytä käyttävän Authorization-headeria ollenkaan
:arrow_down: 
Skipataan access token cache kokonaan ja haetaan aina uusi ennen salasanan vaihtoa
> Korjataan väärinymmärrys Suomi.fi REST salasanan vaihdossa

- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
https://github.com/espoon-voltti/evaka/pull/5681 part2, nyt menee oikeasti 7-18 eli päivän ensimmäinen klo 7.00 ja viimeinen klo 17.50.
> Korjaus Jamix-synkronoinnin aikatauluun

- frontend/Dockerfile
Yritän selvittää outoa ongelmaa frontendin docker build cachessa, joka tulee kyseiseltä riviltä.
Dokumentointi sanoo: "If you specify multiple source files, either directly or using a wildcard, then the destination must be a directory (must end with a slash /)."
Korjataan rivi dokumentaation mukaiseksi, jos se vaikka samalla korjaisi ym. ongelman.
> Korjataan frontend docker copy -komento

- frontend/src/employee-frontend/components/payments/PaymentsPage.tsx
- frontend/src/lib-customizations/employee.tsx
- frontend/src/lib-customizations/types.d.ts
Tällä hetkellä maksatuksen eräpäivän oletus on kovakoodattuna nykyinen päivä + 10 arkipäivää. Tampereella tämä pitää olla nykyinen päivä.
> Lisätään maksatukseen eräpäivän konfigurointi

- frontend/src/employee-frontend/components/archive-metadata/MetadataSection.tsx
Asetettu `display: none` ao. komponentin printtityyliin.
> Piilotetaan arkistoitavat metatiedot lomakkeiden tulosteista

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
Deduplikoidaan lapset oikein, jotta laskut joissa yhdellä lapsella on monta riviä näkyvät oikein. Jos laskulla on vain yksi lapsi, hänen tietonsa näytetään hakutuloksissa. Muuten näytetään teksti "Useita lapsia".
> Palautetaan lapset oikein laskuhaussa

- frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
Saavutettavuusongelma, enterin käyttö datepickerissä.
_Ennen muutosta:_
Kun painaa enteriä käytettäessä datepickeriä näppäimistöllä, focus siirtyy datepickerin tekstikenttään ilman että päivä tulee valituksi. Jos yrittää navigoida edellinen/seuraava kuukausi -näppäimillä, focus siirtyy myös tekstikenttään ilman että kuukausi vaihtuu.
https://github.com/user-attachments/assets/432d477c-268c-4e4f-ad45-69bc272b0bfc
_Muutoksen jälkeen:_
Päivän valinta ja kuukausien selaaminen enterillä onnistuu.
https://github.com/user-attachments/assets/767d8ef9-1a8a-49e7-bbcd-9453aed3553a
(EDIT) Testeissä on monessa kohtaa käytäntö, jossa datepickerin tekstikenttään "kirjoitetaan" päivämäärä ja painetaan enter. Tämän odotetaan sulkevan datepickerin. Jotta enterillä kuitenkin pystyisi navigoimaan …
> Korjataan päivän valinta enterillä

- frontend/src/lib-customizations/espoo/citizen.tsx
Yksinkertaistettiin linkkiä poistamalla päivämäärä, koska ei se ei ole enää tarpeellinen.
> Tekstimuutoksia Espoon tuloselvitykselle

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/generated/api-types.ts
- frontend/src/lib-common/generated/api-types/invoicing.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/ReplacementInvoicesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Invoices.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
- service/src/main/resources/db/migration/V461__replacement_invoices.sql
- service/src/main/resources/migrations.txt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClientTest.kt
Lisätty oikaisulaskugeneraattori sekä mahdollisuus ajaa oikaisulaskujen generointi yöllisessä ajossa esim. testiympäristöissä. Oikaisulaskut eivät vielä näy missään käyttöliittymissä.
> Oikaisulaskut, osa 1: Laskujen yöllinen generointi (ei vielä käytössä)

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
Laskuhaku ei toiminut, jos jossain löydetyistä laskuista ei ollut lainkaan rivejä. Tällaisia laskuja ei tällä hetkellä pitäisi muodostua, mutta historiallisesti näin on saattanut olla.
> Korjaus laskuhakun tuloksiin, kun löydetyissä laskuissa ei ole yhtään riviä

- frontend/src/citizen-frontend/messages/MessageEditor.tsx
- frontend/src/citizen-frontend/messages/MessagesPage.tsx
- frontend/src/citizen-frontend/messages/ThreadView.tsx
- frontend/src/lib-common/generated/api-types/messaging.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
Tannoisten muutosten (https://github.com/espoon-voltti/evaka/pull/5839) jälkeen kuntalainen ei pystynyt vastaamaan erityisopettajalta tulleeseen viestiin. Yleisemmin vastaaminen oli sallittua vain sellaisiin viesteihin, jotka oli lähetetty ryhmätililtä tai yksikön johtajalta.
Muutoksen jälkeen viesteihin vastaaminen on sallittua silloin, kun viestiketjun jokainen osallistuja on jokin seuraavista:
- sellaisen päiväkodin henkilöstön jäsen, johon on voimassa oleva tai kahden viikon sisällä alkava sijoitus
- ryhmätili ryhmään, johon on voimassa oleva tai kahden viikon sisällä alkava ryhmitys.
> Salli vastaaminen erityisopettajan ja muun päiväkotihenkilöstön viesteihin

- service/src/integrationTest/kotlin/fi/espoo/evaka/jamix/JamixIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/jamix/JamixQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
> Ei tehdä tilauksia Jamixiin suljetuista yksiköistä/ryhmistä

- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/HolidayPeriodAttendanceReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/HolidayPeriodAttendanceReport.kt
Lomakyselyraportilla oletetaan kiinteän aikataulun lasten (kerho, pelkkä esiopetus, valmistava opetus) olevan poissa lomajaksojen aikana (ei toimintaa).
> Loma-ajan läsnäoloraportin opetustauolla olevien lasten suodatus

- apigw/Dockerfile
- apigw/entrypoint.sh
Kontin IP-osoite haettiin curl-työkalulla AWS:n metadatapalvelusta. Curl-työkalu toi mukanaan [haavoittuvan libldap](https://security-tracker.debian.org/tracker/CVE-2023-2953)-riippuvuuden.
IP-osoite haetaan suoraan kontista hostname-komennolla. Muutos poistaa curl-riippuvuuden ja yksinkertaistaa koodia.
> Poistetaan curl IP-osoitteen hakemisesta

- frontend/Dockerfile
Tämä muutos poistaa proxyn Docker imagesta nginx-module-image-filter paketin jota ei käytetä eVakassa
> Käyttämättömän proxy moduulin poisto

- service/src/main/resources/db/migration/V464__scheduled_tasks_priority.sql
- service/src/main/resources/migrations.txt
Lisätään sarake `priority`. Kirjasto toimii ilmankin, mutta jossain tulevaisuuden versiossa sarake vaaditaan, joten se kannattaa luoda jo nyt.
Ks. [db-schedulerin päivitysohjeet](https://github.com/kagkarlsson/db-scheduler?tab=readme-ov-file#versions--upgrading)
> db-scheduler-kirjaston päivityksen vaatima tietokantamuutos

- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/DocumentHtmlGenerator.kt
Nimettyjä tekstikenttiä kysymys saattoi leikkaantua pois pdf:ltä. Muutettu niin että rivittyy tarvittaessa useammalle riville.
Kaikki pdf:t voi generoida uudelleen ajamalla seuraavan SQL:n:
```
INSERT INTO async_job(type, payload, retry_count, retry_interval)
SELECT 'CreateChildDocumentPdf',
jsonb_build_object(
'user', NULL,
'documentId', document_id
),
3,
interval '5 minutes'
FROM (
SELECT id AS document_id
FROM child_document
WHERE document_key IS NOT NULL
) documents;
```
> Korjaus pedagogisen lomakkeen pdf-generointiin

- frontend/src/employee-frontend/components/placement-tool/PlacementToolPage.tsx
- frontend/src/employee-frontend/components/placement-tool/queries.ts
- frontend/src/employee-frontend/generated/api-clients/application.ts
- frontend/src/employee-frontend/query.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolController.kt
Ehdottavan esiopetuksen työkalu vaatii tulevan esiopetuskauden olemassaolon. Muutoksen jälkeen puuttuva esiopetuskausi estää CSV:n latauksen ja näyttää pääkäyttäjälle varoituksen.
> Tarkistus seuraavan esiopetuskauden olemassaolosta ehdottavan EO:n työkaluun

- apigw/src/shared/middleware/csrf.ts
- frontend/src/citizen-frontend/api-client.ts
- frontend/src/citizen-frontend/messages/utils.ts
- frontend/src/employee-frontend/api/client.ts
- frontend/src/employee-frontend/components/messages/utils.ts
- frontend/src/employee-mobile-frontend/client.ts
HTML-lomakkeilla ei voi asettaa custom-headereita -> custom headerin läsnäolo riittää CSRF-tarkistukseksi eikä arvolla oikeasti ole väliä
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#employing-custom-request-headers-for-ajaxapi
> Kevennetään CSRF-tarkistusta OWASP-suositusten mukaisesti

- frontend/Dockerfile
`nginx-module-njs` ja `nginx-module-xslt` paketeilla on riippuvuus libxml2-kirjastoon, jossa on korjaamattomia haavoittuvuuksia. Poistetaan kyseiset moduulit, koska ne eivät ole käytössä Evakassa.
> Poistetaan käyttämättömiä nginx moduuleita

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/children/ChildrenQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/FinanceDecisionUtils.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
- Haetaan kanssavelalliset kahdella SQL-queryllä kaikille maksupäätöksille, sen sijaan että tehtäisiin yksi SQL-query per maksupäätös.
- Rajataan poissaolohakua lasten ID:illä, jolloin indeksien käytön pitäisi olla tehokkaampaa. Haku myös kohdistuu vain niihin lapsiin, joiden poissoloista ollaan oikeasti kiinnostuneita.
- Valmistaudutaan yksittäisen päämiehen laskujen generointiin rajaamalla myös muuta haettua dataa lasten ID:illä
> Laskujen generoinnin suorituskykyparannuksia

- frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/lib-components/atoms/buttons/AsyncButton.tsx
- frontend/src/lib-components/atoms/buttons/async-button-behavior.ts
**_Ennen muutosta:_**
Kun tallennetaan läsnä-/poissaoloja kuntalaisen kalenterinäkymässä, näytölle tuleva notifikaatio peittää toimintoja desktopilla ja mobiilissa.
https://github.com/user-attachments/assets/25ea76df-e589-4aab-80ca-e133b9f21d46
https://github.com/user-attachments/assets/cd706aaf-d0ae-4e8a-b3e8-767a355bd6df
_**Muutoksen jälkeen:**_
Poistettu erillinen notifikaatio ja pidennetty "Tallennettu"-tilan näyttämistä onnistuneen tallennuksen jälkeen (parametrillä muokattavissa, default 2,5s).
Muutettu myös screenReaderOnly-toiminnallisuutta AsyncButton-komponentissa jonka tarkoitus on välittää esim. voice-overille napin tilaa.
Macilla kokeiltaessa onnistuneen tallennuksen tilaa ei lausuttu alkuperäisellä setupilla ("ladataan" tuli enimmäkseen läpi sen sijaan), muokkauksen jälkeen …
> Päiväeditorin tallennuksen indikointi ilman notifikaatiota

- frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposalRow.tsx
- frontend/src/lib-common/generated/api-types/placement.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementPlanIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlan.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanQueries.kt
Ehdottava esiopetussysteemi menee seuraavassa järjestyksessä:
1. Ehdottavat esiopetushakemukset tuodaan järjestelmään ("optimointityökalu")
2. Palveluohjaus siirtää hakemukset johtajille
3. Johtajat tarkastavat hakemukset, mutta eivät hyväksy (hylätä voivat jolloin käsittely siirretään takaisin normaalin käytännön mukaisesti palveluohjaukselle)
4. Palveluohjaus siirtää hakemukset takaisin itselle käsittelyyn, ja lähettää sitten asiakkaille yhtenä massana sopivana ajankohtana ennen esiopetuksen hakuajan alkamista
Tässä muutoksessa halutaan estää vaiheessa 3 johtajia hyväksymästä hakemuksia, jotta ne voidaan sitten palveluohjauksen toimesta lähettää yhtenä massana.
> Ehdottavan esiopetushakemuksen hyväksymisen esto johtajalta

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotifications.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- Send expired outcome notification one day after expiration instead the day of the expiration
- Separate email sending from expired income creation to fix a potential bug
> Lähetetään tulotietomuistutus vasta tulotiedon loppumisen jälkeisenä päivänä

- compose/e2e/playwright.Dockerfile
- compose/e2e/playwright/bin/run-tests.sh
- compose/e2e/playwright/bin/wait-for-url.sh
- frontend/Dockerfile
`curl`illa on riippuvuus `openldap`-kirjastoon, jossa on korjaamattomia haavoittuvuuksia. Poistetaan `curl` `frontend` imagesta ja lisätään se `playwright`-imageen, jossa sitä tarvitaan. `playwright` image on käytössä vain GitHubissa testejä ajettaessa, joten haavoittuvuudella ei ole siellä merkitystä.
> Poistetaan curl frontend-imagesta

- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
Lisätty työntekijöiden deaktivointiin tarkistus, jossa jätetään jo valmiiksi epäaktiiviset työntekijät käsittelemättä.
> Ei deaktivoida valmiiksi epäaktiivisia työntekijöitä uudelleen

- frontend/src/citizen-frontend/navigation/MobileNav.tsx
Kun Firefoxin sositepalkki piiloutuu scrollatessa, päänavigaation nappuloiden aktiivinen alue ei siirtynyt alaspäin, vaikka niiden visuaalinen esitys siirtyikin viewportin "uuteen alalaitaan".
`<nav>` elementin sijainti ennen scrollausta
`<nav>` elementin sijainti scrollauksen ja osoitepalkin piiloutumisen jälkeen
Tämä johti siihen, että "Läsnäolot / Poissaolot / Keskustelut" nappia painaessa aktivoituikin Viestit, Lapset tai Valikko painike, riippuen mistä kohtaa leveyssuunnassa nappia painoi.
Päämenu on ankkuroitu alalaitaan `position: fixed` säännöllä ja se pitää nappien hitboxit oikeassa kohdassa myös mobiili Firefox selaimella skrollauksen jälkeen.
> Korjataan päänavigaation sijainti Firefox mobiiliselaimella

- frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendanceEditPage.tsx
- frontend/src/lib-components/assistance-need-decision/AssistanceNeedPreschoolDecisionReadOnly.tsx
- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
Jos henkilökunnan läsnäolon tyypiksi valitsee mobiilin muokkaa kirjauksia näkymässä joko koulutus tai muu työasia, piilotetaan kasvatusvastuullisuus-rasti ja tulkitaan aina ei-kasvatusvastuulliseksi. Lisätty myös mobiilin täyttöastelaskentaan lisävarmistus joka myös jättää huomiotta tämän tyyppiset kirjaukset.
> Korjaus kasvatusvastuullisuuteen / täyttöasteeseen mobiilissa

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/ReplacementInvoicesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
Oikaisulaskuja muodostetaan 12 kuukautta taaksepäin viimeisestä laskutetusta kuukaudesta. Päätellään viimeinen laskutettu kuukausi lähetetyistä laskuista sen sijaan että käytettäisiin aina edeltävää kuukautta.
> Korjataan viimeisen laskutetun kuukauden päättely

- frontend/src/lib-common/generated/api-types/invoicing.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
Maksupäätöksien hakuun on lisätty uusi hakuehto: ei avoimia tuloselvityksiä. Kun se on valittuna, sellaisia maksupäätöksiä ei näytetä, joihin liittyy avoimia tuloselvityksiä. Tuloselvityksistä huomioidaan koko jääkaappiperheen selvitykset, jotka koskevat ajanjaksoa alkaen 14 kuukautta sitten kuluvaan päivään asti.
> Maksupäätöksien hakuun uusi hakuehto: ei avoimia tuloselvityksiä

- frontend/src/employee-frontend/components/child-information/fee-alteration/FeeAlterationList.tsx
- frontend/src/employee-frontend/components/person-profile/income/IncomeItemHeader.tsx
Korjannut tulotietojen sivua niin, että sarakkeet pysyvät suorina.
Alkuperäiinen: 
Korjattu:
> Tulotietojen sivun ulkonäön bugikorjaus

- frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
**Ennen:** Jos request epäonnistui mihin tahansa muuhun virheeseen kuin yhtäaikaiseen muokkaamiseen, lapsen dokumenttia yritettiin tallentaa ikikieriössä.
**Jälkeen:** Näytetään sen sijaan virheviesti ja yritetään uudestaan 5 sekunnin välein:
> Korjataan lapsen dokumentin muokkausnäkymän tallennuskäyttäytyminen virhetilanteissa

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/application/notes/ApplicationNoteQueries.kt
Aiemmin tehdyssä muutoksessa sijoitusehdotuksen hylkäämisen syy kirjattiin erilliseksi muistilapuksi hakemukselle. Tämä muutos vaihtaa syyn kirjaamispaikan palveluohjauksen sisäiseen muistilappuun. Mikäli muistilapulla on jo sisältöä, syy kirjataan aiemman sisällön perään rivinvaihdolla erotettuna. Syyn lisäksi lapulle kirjataan hylkäyksen tehneen käyttäjän nimi ja tapahtuman aika.
> Sijoitusehdotuksen hylkäämisestä luotava muistilappu siirtyy palveluohjauksen muistilapuksi

- frontend/src/e2e-test/dev-api/index.ts
- frontend/src/e2e-test/generated/api-clients.ts
- service/codegen/src/main/kotlin/evaka/codegen/api/ApiFiles.kt
> Mocked time -tuki generoiduille dev-API-clienteille

- service/src/main/resources/db/migration/V470__cascade_citizen_user_delete.sql
- service/src/main/resources/migrations.txt
> Poistetaan citizen_user-taulun rivi jos person-taulun rivi poistuu

- frontend/src/citizen-frontend/generated/api-clients/incomestatement.ts
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt
poistetaan tilapäinen takaisinpäinyhteensopivuus
> Tehdään tuloilmoituksen draft-parametrista pakollinen

- service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
Tuloilmoitukset näkyivät asiakkaan sivujen kautta talouden käyttäjille jo luonnostilassa ollessaan. Lisäksi korjattu validointilogiikkaa joka estää luomasta useaa ilmoitusta jotka alkavat samana päivänä.
> Korjaus tuloilmoitusluonnosten näkyvyyteen virkailijoille

- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
Ennen kuin lapsi on merkitty saapuneeksi, näytetään pelkästään päivän varaukset. Saapuneeksi merkitsemisen jälkeen varaukset näytetään suluissa toteutuneen ajan alla.
> Varaukset näytetään kuntalaisen kalenterissa toteumien yhteydessä

- frontend/src/e2e-test/specs/6_mobile/reservations.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
Kun lapselle, jolla on esiopetus + täydentävä vaka -sijoitus, ilmoitetaan läsnäoloajaksi kokonaan esiopetuksen ajalle sijoittuva aikaväli, näkyi tämä "Tulevat varaukset ja poissaolot"-sivulla virheellisesti poissaolona. Korjauksen jälkeen kyseinen tapaus näytetään oikein, ja näkyvillä on ilmoitettu läsnäolon aikaväli.
> Korjaus läsnäolon näkyvyyteen mobiilissa

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
Mahdollistaa UTF with BOM enkoodausta käyttävien (Excel) CSV-tiedostojen käytön työkalussa.
> Lisätään ehdottavan EO:n sijoitustietojen syöttöön tuki Excel-peräisille CSV-tiedostoille (BOM)

- frontend/src/e2e-test/pages/employee/reports.ts
- frontend/src/e2e-test/specs/5_employee/holiday-period-attendance-report.spec.ts
- frontend/src/employee-frontend/components/reports/HolidayPeriodAttendanceReport.tsx
- frontend/src/employee-frontend/generated/api-clients/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/HolidayPeriodAttendanceReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/HolidayPeriodAttendanceReport.kt
Aiemmin raportti on näyttänyt vain koko yksikön tuloksia. Tämä muutos mahdollistaa tulosten näyttämisen myös käyttäjän valitsemille yksikön ryhmille.
> Lomakyselyraportin tuki ryhmäkohtaisille tuloksille

- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/DVVBatchRefreshServiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
> Parannuksia osoitteiden vertailuun

- frontend/src/e2e-test/pages/employee/reports.ts
- frontend/src/e2e-test/specs/5_employee/assistance-need-and-actions-report.spec.ts
- frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
- frontend/src/employee-frontend/components/reports/queries.ts
- frontend/src/employee-frontend/generated/api-clients/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportControllerTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportController.kt
Tukitoimi pitäisi laskea raportille mukaan vain jos lapsella on jokin raportilla valittu tuen taso.
Esim. jos näytetään varhaiskasvatuksen tuen tasot, esiopetuksen tuen tasollisia lapsia ei pitäisi laskea mukaan raportille.
> Korjataan tukitoimien laskenta raportissa

- frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
- frontend/src/employee-frontend/components/child-information/ChildDocumentsSection.tsx
Käyttöliittymä näyttää turhaan luontikontrollit, vaikka käyttäjällä olisi vain lukuoikeus. Asiakirjan lisääminen ei voi onnistua ilman luonnin käyttöoikeutta.
> Piilota pedagogisten asiakirjojen luonti käyttäjiltä, joilla vain lukuoikeus

- apigw/src/shared/service-client.ts
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
- service/src/main/resources/db/migration/V472__employee_ssn.sql
- service/src/main/resources/migrations.txt
> Lisätään sisäinen rajapinta palvelutuottajien suomi.fi-kirjautumiselle

- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Oikaisulaskuja ei generoida jos niitä ei ole otettu käyttöön, joten jobi on turvallista ajaa.
> Oikaisulaskujen generointijobi oletuksena päälle

- service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/process/ArchivedProcesses.kt
Jos palautetaan valmis-tilassa oleva asiakirja aiempaan asiakirjan tilaan niin perutaan asiaprosessihistoriasta COMPLETED tila sen sijaan että lisättäisiin uusi INITIAL tila.
Dokumentaatio: https://github.com/espoon-voltti/evaka/wiki/Asianhallintaprosessit,-metatiedot-ja-arkistointi
> Muutetaan pedagogisten asiakirjojen asianhallinnan tilahistoria lineaariseksi

- frontend/src/employee-frontend/components/invoice/ReplacementDraftInfo.tsx
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- Annetaan Talouden työntekijä (ulkoinen) -roolille oikeus muodostaa päämiehen oikaisulaskut 
- Tehdään lisätiedot-kentästä pakollinen jos oikaisun syy on Muu
> Pieniä korjauksia oikaisulaskuihin

- frontend/src/employee-frontend/components/reports/Invoices.tsx
- frontend/src/employee-frontend/components/reports/queries.ts
- frontend/src/employee-frontend/generated/api-clients/reports.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/InvoicingReportTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ReportSmokeTests.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/InvoiceReport.kt
Laskujen täsmäytysraportin päivävalitsin on aiheuttanut kyselyitä mitä merkitystä valitulla päivällä on saman kuukauden sisällä. Ei mitään koska raportti toimii kuukausitasolla, joten vaihdetaan käyttöön kuukausivalitsin.
> Muutetaan laskujen täsmäysraportin päivävalitsin kuukausivalitsimeen

- frontend/src/lib-components/i18n.tsx
- frontend/src/lib-components/molecules/date-picker/DatePicker.spec.tsx
- frontend/src/lib-components/molecules/date-picker/DatePickerDay.tsx
- frontend/src/lib-components/molecules/date-picker/DatePickerInput.tsx
- frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
- frontend/src/lib-components/molecules/date-picker/DateRangePicker.spec.tsx
- frontend/src/lib-components/utils/TestContextProvider.tsx
- frontend/src/lib-customizations/defaults/components/i18n/en.tsx
- frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
_Ennen muutosta_
Päivämäärävalitsin oli vaikeasti navigoitavissa ruudunlukijan/avusteisen kanssa. 
_Muutoksen jälkeen_
Lisätty erillinen ikoni valitsimen avaamiseen ja asetettu sille aria-haspopup- ja aria-expanded -attribuutit.
Input-kentästä pääsee myös valitsimeen painamalla nuoli alas -näppäintä.
Korvattu erillinen ruudunlukijan ohjeteksti asettamalla se inputin aria-labeliin suoraan.
Videolla käyttöä ensin hiirellä ja sitten näppäimistöllä:
https://github.com/user-attachments/assets/972d33a4-0247-403a-a46e-f2805d239e76
> Päivämääräkentän saavutettavuus

- frontend/src/citizen-frontend/map/api.ts
Hakuun tuli CSRF-headerien vaatimus apigw-muutoksissa, mutta kutsut tehdään suoraan raakana axios-clientilla käyttämättä yleistä valmiiksi konfiguroita clienttia ja headeria ei asetettu
> Korjataan regressio kartan hakutoiminnossa

- frontend/src/employee-frontend/components/applications/ApplicationsFilters.tsx
- frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
- frontend/src/employee-frontend/components/common/Filters.tsx
- frontend/src/employee-frontend/state/application-ui.tsx
- frontend/src/lib-common/generated/api-types/application.ts
- frontend/src/lib-customizations/common.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationSearchIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Jatkava lapsi -ehto täyttyy jos hakemuksen ensimmäinen hakutoive on sama yksikkö, jossa lapsella on voimassaoleva sijoitus tänään.
Dokumentaatio: https://github.com/espoon-voltti/evaka/wiki/Hakemukset
> Lisätään "jatkava lapsi"-huomio hakemushakuun

- apigw/src/shared/service-client.ts
- frontend/src/lib-common/generated/api-types/shared.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementPlanIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/UserRole.kt
- `END_USER`, `CITIZEN_WEAK`, `MOBILE` on käyttäjätyyppejä eikä rooleja
- `GROUP_STAFF` on nykyään `STAFF` yksikkötasolla + erillinen ryhmäluvitus
- nämä on yhä tietokannan `user_role`-enumissa: `MOBILE`, `GROUP_STAFF`. Enumista poistaminen on hankalaa
- `employee.roles` ja `daycare_acl.role` -sarakkeissa on check constraintit jotka on jo nyt ajan tasalla eikä nyt poistettavia rooleja ole sallittu niissä pitkään aikaan
> Poistetaan vanhat turhat käytöstä poistuneet roolit

- frontend/src/lib-components/molecules/date-picker/DatePicker.tsx
Oletustoteutus ei tuntuisi tällä hetkellä toimivan, esim. Kerhon lukukausi -sivun Haku lukukaudelle alkaa -kenttä.
> Korjataan päivämäärävalitsimen virheviestit

- frontend/src/employee-frontend/components/unit/tab-groups/TerminatedPlacements.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
Aikaisemmin irtisanottujen listalla näytettiin lapset kahden viikon ajan irtisanoutumisilmoituksen tekemisestä alkaen. Näiden lisäksi listalla näytetään nyt siirron saaneet lapset alkaen siitä hetkestä, kun huoltaja on ottanut uuden paikan vastaan, siihen asti, kunnes uusi sijoitus alkaa.
> Siirron saaneiden lasten näkyminen irtisanottujen listalla

- frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts
- frontend/src/e2e-test/specs/5_employee/assistance-need-decision.spec.ts
- frontend/src/lib-customizations/espoo/citizen.tsx
- frontend/src/lib-customizations/espoo/employee.tsx
Espoolle varhaiskasvatuksen tuen päätökselle muutettu otsikko "Perustelut lapsen tuen tasolle" -> "Perustelut lapsen tuen tasolle ja tuen järjestelyt loma-aikoina".
Korvattu tyhjällä teksti "Loma-aikoina tuen järjestämisen tapa ja paikka voi muuttua".
> Tekstimuutoksia varhaiskasvatuksen tuen päätökselle Espoossa

- apigw/src/app.ts
`req.session` oli undefined koska sessio-middlewarea ei ollut tässä routessa
> Korjataan palvelutuottajien Keycloak-uloskirjautuminen toimimaan myös Keycloakin puolella oikein

- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
Sama teksti kuin PDF:llä: https://github.com/espoon-voltti/evaka/blob/27095aa3fb59b95340789dcc900f62f6cfc1ef73/service/src/main/resources/WEB-INF/templates/assistance-need/decision.properties#L4
Enkkuversion muutin vastaamaan esiopetuksen vastinetta: https://github.com/espoon-voltti/evaka/blob/27095aa3fb59b95340789dcc900f62f6cfc1ef73/frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx#L1677
> Korjataan tuen päätöksen otsikko

- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/UnitAcl.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/AclQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
Kun työntekijä luvitettiin toiseen ryhmään aiemman ryhmän lisäksi, katosivat aiemman ryhmän viikkoa vanhemmat viestit näkyvistä. Kyseinen virhe on korjattu, ja aiemman ryhmän viestien näkyvyyteen ei tule muutosta uusiin ryhmiin luvituksen yhteydessä.
Syynä virheeseen oli, että taustalla uuteen ryhmään luvituksen yhteydessä ensin poistettin luvat kaikkiin yksikön ryhmiin, joihin työntekijällä oli ennestään oikeus, ja välittömästi perään annettiin luvat kaikkiin haluttuihin ryhmiin. Näin kaikkien ryhmien luvitushetkeksi tuli nykyhetki, ja viestien näkyvyys on siitä viikko taaksepäin.
Ennen tätä korjausta tehtyjen ryhmäluvitusten aiheuttamien viestien näkyvyysongelmien korjaaminen taannehtivasti ei ole mahdollista.
> Korjaus ryhmäpostilaatikon näkyvyyteen kun työntekijä luvitettiin toiseen ryhmään

- frontend/src/employee-frontend/components/reports/TitaniaErrors.tsx
- frontend/src/employee-frontend/components/reports/queries.ts
- frontend/src/employee-frontend/generated/api-clients/reports.ts
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-common/generated/api-types/shared.ts
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/TitaniaErrorsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt
- service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaService.kt
- service/src/main/resources/db/migration/V477__titania_errors_id.sql
- service/src/main/resources/migrations.txt
- Korjattu Titaniasta tulevan datan validointi
- Lisätty mahdollisuus poistaa yksittäinen rivi raportilta
Dikumentaatio: https://github.com/espoon-voltti/evaka/wiki/Titania-ty%C3%B6aikaintegraatio
> Titania raportin jatkokehitys

- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Päättyvien sijoitusten listalla näkyivät virheellisesti yksikön lapset, joilla on ollut menneisyydessä siirtohakemus johonkin yksikköön. Tässä korjauksessa rajoitetaan näkyvyyttä seuraavin ehdoin:
- siirtohakemukseen liittyvän päätöksen alkupäivä on tulevaisuudessa
- siirtohakemukseen liittyvän päätöksen pitää kohdistua toiseen yksikköön kuin nykyinen sijoitus, ja
- lapsella pitää olla sijoitus toiseen yksikköön nykyisen sijoituksen loppumisen jälkeen.
> Korjaus lasten näkymiseen päätyvien sijoitusten listalla

- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
Osakuun sijoitusten osalta raportille ilmestyi joskus muutaman sentin pyöristysvirheitä tuen kertoimen osuuteen. Korjataan ongelma käyttämällä pelkkää perusosaa jos lapsen tuen kerroin on 1.
> Pyöristyskorjaus palveluseteliraportin perusosan ja tuen kertoimen vaikutuksen laskentaan

- frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/lib-components/atoms/form/InputField.tsx
- frontend/src/lib-components/molecules/date-picker/DateRangePicker.tsx
- frontend/src/lib-components/molecules/date-picker/DateRangePickerLowLevel.tsx
_Ennen muutosta_
Päivämääräkentän validointivirhe (esim. "Pakollinen tieto") jää ruudunlukijalta huomioimatta.
_Muutoksen jälkeen_
Ruudunlukija lausuu virheen kun validointi tapahtuu. Lisättiin 'alert'-role infoStatuksen ollessa tyyppiä "warning".
Samalla asetettiin daterangepickerin roleksi "group", joka toteuttaa fieldset/legend -yhdistelmän toiminnon ruudunlukijan näkökulmasta.
Lisätty myös semanttiset puutokset aria-required ja aria-invalid.
> Päivämääräkentän validointivirhe ruudunlukijalle

- apigw/src/app.ts
Tällä hetkellä näistä tulee CSRF-virhe, koska route ei osu ja mennään normaaliin API-käsittelyyn jossa CSRF-header on pakollinen.
Muutoksen jälkeen CSP-raportit tulee taas läpi ja CSRF-virheet vähenee
> Korjataan CSP-raporttiendpointin polku

- apigw/src/app.ts
- apigw/src/enduser/keycloak-citizen-saml.ts
- apigw/src/enduser/suomi-fi-saml.ts
- apigw/src/internal/ad-saml.ts
- apigw/src/internal/dev-sfi-auth.ts
- apigw/src/internal/keycloak-employee-saml.ts
- apigw/src/shared/auth/dev-auth.ts
- apigw/src/shared/auth/index.ts
- apigw/src/shared/config.ts
- apigw/src/shared/dev-api.ts
- apigw/src/shared/routes/saml.ts
- apigw/src/shared/saml/index.ts
- apigw/src/shared/test/gateway-tester.ts
- frontend/src/citizen-frontend/navigation/DesktopNav.tsx
- frontend/src/citizen-frontend/navigation/MobileNav.tsx
- frontend/src/citizen-frontend/navigation/const.ts
- frontend/src/e2e-test/config.ts
- frontend/src/e2e-test/generated/api-clients.ts
- frontend/src/e2e-test/generated/api-types.ts
- frontend/src/e2e-test/utils/user.ts
- frontend/src/employee-frontend/api/auth.ts
- frontend/src/employee-frontend/components/login-page/Login.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/dev-data/employees.sql
- napin näkyvyys on feature flagin takana, eikä tuotannossa muutenkaan toimi vielä koska kellään työntekijällä ei ole hetua kannassa
- vanha Suomi.fi:lle metadatassa ilmoitettu `/api/application/auth/saml`-polku valitsee oikean toteutuksen RelayState-parametrin polun perusteella
- tulevaisuudessa voidaan ilmoittaa Suomi.fi:lle erilliset polut `/api/citizen/auth/sfi` ja `/api/employee/auth/sfi`
> Palvelutuottajien suomi.fi -kirjautuminen (ei vielä käytössä)

- frontend/src/e2e-test/specs/5_employee/non-ssn-children-report.spec.ts
- service/src/main/kotlin/fi/espoo/evaka/espoo/EspooActionRuleMapping.kt
specsi:
- Hetuttomat- raportti pois talouden näkymästä
- Palveluseteliyksiköt ja perhepäivähoitajien ateriaraportti pois hallinnon näkymästä
- Perhekonfliktit raportti pois johtajan ja veon näkymästä 
- Perhetietojen muokkaus pois johtajan roolilta (ts. pois lisäys ja muokkausmahdollisuus puolisotiedosta ja päämiehen alle 18-v. lasten tiedoista, jätetään vain katselu)
> Espoo: käyttöoikeusmuutoksia

- frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
- frontend/src/lib-common/generated/api-types/document.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Työntekijät jotka voivat lukea pedagogisen asiakirjan voivat myös ladata sen pdf:nä silloin kun viimeisimmät muutokset on julkaistu ja pdf on ehditty generoida.
> Pedagogisen asiakirjan lataaminen PDF:nä

- frontend/src/citizen-frontend/navigation/DesktopNav.tsx
- frontend/src/citizen-frontend/navigation/Header.tsx
- frontend/src/citizen-frontend/navigation/MobileNav.tsx
- frontend/src/citizen-frontend/navigation/utils.ts
Hyväksyttävien paikkapäätöksien ja lukemattomien tuen päätöksien ilmoitusmerkki henkilön nimen vieressä toimii tällä hetkellä hieman eri tavalla työpöytä- ja mobiiliresoluutioilla (työpöytä ei näytä ilmoitusmerkkiä ollenkaan ja mobiili ei näytä lukemattomia tuen päätöksiä). Tämä yhtenäistää toteutukset eli jatkossa ilmoitusmerkki näkyy sekä hyväksyttävistä paikkapäätöksistä että lukemattomista tuen päätöksistä kaikilla resoluutioilla.
> Korjataan huoltajien käyttöliittymään lukemattomien päätöksien ilmoitusmerkki

- service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
`MockEvakaClock` käyttöön ja yhteiskäyttöisten testifikstuurien poisto.
Irroitettu muutoksesta https://github.com/espoon-voltti/evaka/pull/6148.
> Refaktoroidaan päätöksen luonnin integraatiotestit

- apigw/Dockerfile
Tällä hetkellä apigw:n konttiin laitetaan sovelluksen koodit `evaka`-käyttäjän kotihakemistoon kirjoitusoikeuksilla. Tämän muutoksen myötä koodit säilötään jatkossa `/project`-hakemistoon, joihin käyttäjällä ei ole kirjoitusoikeuksia.
Tämän pitäisi myös nopeuttaa kontin rakentamista, koska poistettu `chown`-komento vei lähes puolet ajasta.
Huom! tämä muuttaa oletustyöhakemiston `evaka`-käyttäjän kotihakemistosta `/project`-hakemistoon.
> Korjataan apigw:n kontin tiedosto-oikeudet

- frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
- frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx
- frontend/src/lib-common/generated/api-types/attachment.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/attachment/Attachment.kt
Palveluohjaus ei pystynyt lisäämään yleisiä liitteitä hakemukselle. Ainoastaan kiireellisyyteen tai vuorohoitoon liittyviä liitteitä oli mahdollista lisätä.
Hakemuksen Lisätiedot-kohdassa on vapaa kenttä liitetiedostoille.
Editointinäkymä
Lukunäkymä
Nämä uuden tyyppiset liitteet eivät tule kuntalaisen puolelle näkyviin, koska kuntalaisen puolella näytetään vain käyttäjän itsensä lisäämät liitteet.
> Lisätty tuki palveluohjauksen sisäisille liitteille hakemuksilla

- frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Tarve uudelleenjärjestää hakemuksen hakutoiveet on noussut esim puhelussa asiakkaan kanssa. Palveluohjaaja on joutunut poistamaan hakutoiveet ja lisäämään ne takaisin halutussa järjestyksessä.
Työntekijän puolelle hakemuksen editointiin on lisätty kuntalaisen puolta vastaavat painikkeet uudelleenjärjestää hakutoiveet.
> Lisätty palveluohjaukselle mahdollisuus muuttaa hakemuksen hakutoiveiden järjestystä

- frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx
- frontend/src/lib-components/atoms/form/MultiSelect.tsx
- frontend/src/lib-components/molecules/MessageBoxes.tsx
_Ennen muutosta_
Ruudunlukija ei reagoi eri hakemusten validointivirheisiin lähetettäessä/tarkistettaessa. 
_Muutoksen jälkeen_
Ruudunlukija listaa validointivirheet. Lisättiin role-attribuutti MessageBoxesin wrapperiin. Lisätty myös pakollisen hakutoiveen validointi onBlurilla, mikäli käyttäjä navigoi osion läpi ilman valintaa.
> Hakemusten lähetyksen validointi ruudunlukijalla

- frontend/src/e2e-test/pages/employee/reports.ts
- frontend/src/employee-frontend/components/reports/VardaChildErrors.tsx
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/reports/VardaErrorsReport.kt
`MA003` on Varda-virheistä vähiten hyödyllinen, koska se korjautuu yleensä itsestään kunhan Varda hakee uudet tiedot VTJ:stä.
> Lisätään MA003-suodatin Varda-lapsivirheet -raportille

- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
- frontend/src/lib-components/assistance-need-decision/AssistanceNeedPreschoolDecisionReadOnly.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Vastaava kuin varhaiskasvatuksen tuen päätöksellä. Espoon PDF:ssä tekstiä ei näytä olevan, joten jätetty oletuksena tyhjäksi. Muut kunnat voivat sen lisätä halutessaan. Esim. Tampereella teksti on "Perusopetuslain 17 §:n mukaan tämä päätös voidaan panna täytäntöön muutoksenhausta huolimatta.".
Muokattu samalla toimivalta-tekstin tyyppi tukemaan esim. rivinvaihtoja.
> Lisätään esiopetuksen tuen päätökselle vastuuvapauslauseke

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
1. Osapäiväisen erikoiskäsittely pois: hakemus luodaan aina täydentävällä varhaiskasvatuksella, jonka huoltaja voi myöhemmin hylätä
2. Parannettu puutteellisten perhetietojen käsittelyä.
> Korjauksia esiopetussijoitusten tuontiin

- frontend/src/citizen-frontend/messages/MessageEditor.tsx
- frontend/src/lib-components/atoms/form/MultiSelect.tsx
Lisätty required -attribuutit kuntalaisen viestieditorin otsikko- ja viestikenttiin, jotta ruudunlukija osaa myös listata ne pakollisina.
> Uusi viesti -dialogin pakolliset kentät

- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueries.kt
Näytettiin tekninen `updated_at` aikaleima
Näytetään aikaleima `modified_at` sarakkeesta
> Tulotiedot: poimitaan viimeksi muokattu päivämäärä oikeasta tietueesta

- frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
Kuntalaisen näkemä johtajan poissaoloilmoitus on muutettu muotoon: 
> NN ei ole tavoitettavissa aikavälillä 13.1.2025 - 14.1.2025
> Päivitys suomenkielisiin poissaoloviesteihin

- frontend/src/citizen-frontend/messages/MessageEditor.tsx
Napit jää piiloon desktop-näkymässä
Mobiili versio
Napit aina näkyvissä desktop versiossa
Jos käytössä korkeampi resoluutio, viestimodaali täyttää koko sivun (kuten henkilökunnan puolella)
Mobiili muutosten jälkeen
> Kuntalainen: Viestieditorin responsiivisuusparannus

- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
Korjaa ehdottavan esiopetushakemuksen kautta luotujen sijoitusten näkyminen yksikön johtajille.
> Päivitetään ryhmittämättömien lasten lista sisältämään sijoitukset 7kk asti

- frontend/src/e2e-test/specs/5_employee/income.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/IncomeIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/IncomeController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueries.kt
Ennen katkaisu tehtiin vain toistaiseksi voimassaoleville.
> Katkaistaan myös määräaikainen päällekkäinen tulotieto automaattisesti uutta luotaessa

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/PaymentsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/PaymentQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Payments.kt
Jos maksu merkitään tarkastetuksi (tai lähetetään), ei pitäisi luoda enää uutta luonnosta.
> Korjataan maksuluonnosten tuplaantuminen

- frontend/src/citizen-frontend/messages/MessageEditor.tsx
- frontend/src/e2e-test/pages/citizen/citizen-messages.ts
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
- frontend/src/e2e-test/utils/page.ts
Viestiin on mahdollista valita vain sellaisia vastaanottajia, jotka ovat sallittuja jokaiselle viestiin valituista lapsista. Esimerkiksi samaa viestiä ei voi lähettää kahteen eri ryhmäpostilaatikkoon.
> Kuntalainen: Kaikkien viestin vastaanottajien pitää olla sallittuja kaikille valituille lapsille

- frontend/src/employee-frontend/components/invoice/AbsencesModal.tsx
Laskun poissaolokoosteen tooltipissä näkyi HTML-koodia
Tooltipin rivitys toimii oikein, eikä HTML-koodi ole näkyvissä käyttäjälle
> Henkilökunta: Korjaus poissaolokoosteen tooltippiin

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/generated/api-types.ts
- frontend/src/e2e-test/pages/employee/units/unit-calendar-page-base.ts
- frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
- frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
- frontend/src/lib-common/generated/api-types/attendance.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileUnitControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancyTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaServiceTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
- service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaQueries.kt
- service/src/main/resources/db/migration/V487__staff_attendance_realtime_modified.sql
- service/src/main/resources/migrations.txt
- service/src/test/kotlin/fi/espoo/evaka/titania/TitaniaHelpersTest.kt
Erilliset kentät saapumisen ja lähtemisen tallennukselle. Muokkaustiedot näytetään vain jos ne eroaa luontitiedoista.
> Lisätään työaikakirjaukseen luonti/muokkaustiedot

- frontend/src/citizen-frontend/applications/editor/unit-preference/UnitPreferenceSection.tsx
- frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Ennen esimerkiksi vuorohoidon lisääminen hakemukselle ei poistanut jo valittuja hakutoiveita, jotka eivät tarjoa vuorohoitoa, mikäli hakutoiveet osio oli suljettuna. Nyt validaatiologiikka ajetaan aina. Lisäksi näytetään varoitusviesti, jos hakutoiveista poistetaan yksikköjä automaattisesti.
> Korjataan hakutoiveiden validointi

- frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx
- frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx
- frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
- frontend/src/citizen-frontend/attachments.ts
- frontend/src/citizen-frontend/income-statements/ChildIncomeStatementAttachments.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementAttachments.tsx
- frontend/src/citizen-frontend/messages/MessageEditor.tsx
- frontend/src/employee-frontend/api/attachments.ts
- frontend/src/employee-frontend/components/IncomeStatementPage.tsx
- frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
- frontend/src/employee-frontend/components/child-information/PedagogicalDocumentRow.tsx
- frontend/src/employee-frontend/components/child-information/fee-alteration/FeeAlterationEditor.tsx
- frontend/src/employee-frontend/components/invoice/ReplacementDraftInfo.tsx
- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/person-profile/income/IncomeItemEditor.tsx
- frontend/src/employee-frontend/components/placement-tool/PlacementToolPage.tsx
- frontend/src/employee-frontend/components/placement-tool/api.ts
- frontend/src/lib-components/molecules/FileUpload.tsx
Ennen tarvittiin paljon boilerplatea:
```tsx
const onUpload = (file, progress) => saveFooAttachment(file, progress).then((result) => {
if (result.isSuccess) {
setState({ id: result.value, name: file.name, ... });
return result.value
}
})
const onDelete = (id) => deleteAttachment({ attachmentId: id }).then((result) => {
if (result.isSuccess) setState({ id: result.value, ... })
})
<FileUpload
onUpload={onUpload}
onDelete={onDelete}
...
/>
```
Nyt riittää:
```tsx
<FileUpload
uploadHandler={fooAttachment}
onUploaded={(attachment) => setState({ ...attachment, ... })}
onDeleted={(id) => setState({ id, ... })}
/>
```
> Yksinkertaistetaan `FileUpload`-komponentin käyttöä

- frontend/src/citizen-frontend/applications/editor/contact-info/SecondGuardianSubSection.tsx
- frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
- frontend/src/lib-common/api-types/application/ApplicationFormData.ts
- frontend/src/lib-common/generated/api-types/application.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationForm.kt
- service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
Ehdottavan esiopetuksen hakemuksille tulee tällä hetkellä teksti "Sovittu yhdessä: Sovittu yhdessä", vaikka tämä ei pidä paikkaansa, koska hakemukset luodaan automaattisesti järjestelmän toimesta. Luodaan uusi tyyppi tällaisia hakemuksia varten.
> Ehdottavan esiopetuksen hakemuksen sovittu yhdessä tiedon poisto

- frontend/src/e2e-test/specs/5_employee/paper-application.spec.ts
- frontend/src/employee-frontend/components/ChildInformation.tsx
- frontend/src/employee-frontend/components/PersonProfile.tsx
- frontend/src/employee-frontend/components/Search.tsx
- frontend/src/employee-frontend/components/child-information/CreateApplicationModal.tsx
- frontend/src/employee-frontend/components/common/PersonSearch.tsx
- frontend/src/employee-frontend/components/person-profile/FosterChildren.tsx
- frontend/src/employee-frontend/components/person-profile/person-fridge-child/FridgeChildModal.tsx
- frontend/src/employee-frontend/components/person-profile/person-fridge-partner/FridgePartnerModal.tsx
- frontend/src/employee-frontend/components/person-search/CreatePersonModal.tsx
- frontend/src/employee-frontend/components/reports/DuplicatePeople.tsx
- frontend/src/employee-frontend/constants.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/main/resources/db/migration/V488__no_head_of_self.sql
- service/src/main/resources/migrations.txt
- estetään lasta olemasta itsensä päämies (vanhat vialliset päämiessuhteet poistuvat)
- henkilön oletusnäkymä on lapsi, jos henkilö on alle 13v ja aikuinen jos vähintään 13v
- napista voi tarvittaessa vaihtaa moodia jos henkilö on 10-17v
- paperihakemuksella hakija on vähintään 10v eikä voi olla sama henkilö kuin lapsi jota hakemus koskee
- jääkaappipuoliso on vähintään 13v
- ei voi olla itsensä puoliso
- jääkaappilapsi on alle 18v
- ei voi olla itsensä lapsi
- sijaishuollettava on alle 18v
- ei voi olla itsensä huollettava
> Päivitetään ikärajoja ja parannetaan validointeja

- frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
Tämä testi oli mennyt rikki, kun muutettiin viestit osio näkyväksi ja estettiin vain viestiin vastaus
> Korjaus foster-parents e2e testiin

- frontend/src/employee-frontend/components/reports/TampereRegionalSurvey.tsx
- frontend/src/employee-frontend/components/reports/queries.ts
- frontend/src/employee-frontend/generated/api-clients/reports.ts
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/TampereRegionalSurveyTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/TampereRegionalSurvey.kt
Täydentää Tampereen seutuselvitysraportille toisen CSV:n ikäjaotteluarvojen toimittamiseen. Muokkaa myös raportin käyttöliittymää niin, että eri CSV-tiedot ladataan erillisillä napeilla, sillä kyselyt ovat suurissa kunnissa raskaita.
Huom. Sisältää Kuusikkovertailuraportin hoitopäivälaskentamalliin perustuvan kyselyn, joka on testattu suorituskyvyltään hitaaksi, mutta kuitenkin hieman kuusikkovertailun pahimpia skenaarioita nopeammaksi.
> Tampereen Seutuselvitysraportti osa 2: ikäjaotteluarvojen CSV

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Jos esimerkiksi laskutusjärjestelmän vaihdon yhteydessä uudet laskunumerot ovat pienempiä kuin vanhassa, ei nykyinen toteutus riitä. Tämä mahdollistaa monipuolisemman laskunumeron valinnan kuntakohtaisesti.
**Päivitysohje**
vanhan asetuksen poisto (`FeatureConfig`):
```
invoiceNumberSeriesStart = xyz,
```
uuden toteutuksen lisäys:
```
@Bean
fun invoiceNumberProvider(): InvoiceNumberProvider = DefaultInvoiceNumberProvider(xyz)
```
> Lisätään monipuolisempi seuraavan laskunumeron valinta

- frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
> Päivitys tuloselvityksen tekstiin

- frontend/src/employee-frontend/components/reports/Invoices.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/InvoicingReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/InvoiceReport.kt
Laskujen täsmäytysraportti olisi selkeämpi, jos valittu kuukausi näyttäisi kyseisen kuukauden täsmäytyksen. Tällä hetkellä raportilla kun valitsee ajanjaksoksi tammikuun, niin raportti tuottaa joulukuun laskujen täsmäytyksen.
Eli vaihdetaan raportti hakemaan tiedot laskutuskauden mukaan.
> Muutetaan laskujen täsmäytysraportin hakuehto

- frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx
> Johtaja saa poistaa henkilökunnan luvituksia

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
> Merkitään hakemus salassapidettäväksi jos siinä on liite

- frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
- frontend/src/employee-mobile-frontend/messages/MessageEditor.tsx
- frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Ennen muutosta aloittavien ryhmä näkyi satunnaisesti joko ensimmäisenä tai viimeisenä. Muutoksen jälkeen vastaanottajat järjestetään samalla periaatteella kuin työpöytäversiossa.
Lisäksi muutettin alottavien ryhmän nimi näkymään muodossa "Ryhmän nimi (aloittavat lapset)" sekä työpöytäversiossa että mobiilissa.
> Näytä aloittavien ryhmä viimeisenä mobiilin vastaanottajavalinnassa

- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Poistetaan seuraava teksti:
> Listan tarvittavista liitteistä löydät lomakkeen alaosasta kohdasta “Tuloihin ja varhaiskasvatusmaksuihin liittyvät liitteet”.
Poistetaan myös:
> Toimita tarkemmat yrityskohtaiset tiedot liitteinä.
> Tuloselvityksen tekstikorjauksia

- apigw/src/app.ts
- apigw/src/shared/middleware/error-handler.ts
- apigw/src/shared/routes/saml.ts
- virheelliset auth-kutsut kiinni heti apigw:ssä -> ei enää Spring-virheitä `no GET endpoint /citizen/auth/...`
- anti-CSRF-virheet pois lokeilta kokonaan
- korjataan bugi SAML logout-käsittelyssä jossa ei huomioitu try/catch -blokkia ennen mahdollisesti tulevia virheitä, jotka lensi ylätasolle yleiseen virhelokitukseen
> Vähennetään apigw:stä tulevia turhia virhehälyjä

- frontend/src/citizen-frontend/income-statements/ChildIncomeStatementAttachments.tsx
- frontend/src/citizen-frontend/income-statements/ChildIncomeStatementEditor.tsx
- frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
- frontend/src/citizen-frontend/income-statements/ChildIncomeStatementView.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementAttachments.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
- frontend/src/e2e-test/pages/citizen/citizen-child-income.ts
- frontend/src/e2e-test/pages/citizen/citizen-income.ts
- frontend/src/employee-frontend/components/IncomeStatementPage.tsx
- frontend/src/lib-common/income-statements/attachments.ts
- frontend/src/lib-common/income-statements/body.ts
- frontend/src/lib-common/income-statements/form.ts
- frontend/src/lib-components/molecules/FileUpload.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- Fokusoidaan tiedostonlatauskenttä kun käyttäjä kuntalainen klikkaa Puuttuvat liitteet -listan elementtiä
- Näytetään työntekijälle myös tieto puuttuvista liitteistä:
> Tuloselvityksen saavutettavuus- ja UI-parannuksia

- frontend/src/employee-frontend/components/archive-metadata/MetadataSection.tsx
- frontend/src/lib-common/generated/api-types/process.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataController.kt
> Lisätään metatietoihin asiakirjan id ja (hakemuksen) saapumistapa

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/ReplacementInvoicesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
Virheen johdosta siirretyn 0-oikaisulaskun tilalle saattoi generoitua uusi 0-oikaisulasku kuten kuvassa:
> Korjataan virhe 0-oikaisulaskujen generoinnissa

- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
Ennen toimi näin vain sopimuspäivälapsilla, nyt kaikilla (erityisesti tuntiperustaiset)
> Estetään sopimuspoissaolojen muuttaminen suljetulta ajalta

- frontend/src/employee-frontend/components/reports/TampereRegionalSurvey.tsx
- frontend/src/employee-frontend/components/reports/queries.ts
- frontend/src/employee-frontend/generated/api-clients/reports.ts
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/TampereRegionalSurveyTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/TampereRegionalSurvey.kt
Laajentaa Tampereen seudun seutuselvityksen tueksi laadittua raporttia valikoimalla vuosittaisia tilastoarvoja. Viimeinen suunniteltu osa raporttikokonaisuudesta.
> Tampereen Seutuselvitysraportti osa 3: vuosittaisten arvojen CSV

- frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts
- frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt
Näytetään tuen päätökset vain jos lapsella on sijoitus nyt, tulevaisuudessa tai alle kuukausi menneisyydessä.
> Piilotetaan tuen päätökset huoltajalta jos lapsen asiakkuus on päättynyt

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/generated/api-types.ts
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
- frontend/src/employee-frontend/components/reports/Raw.tsx
- frontend/src/employee-frontend/components/unit/queries.ts
- frontend/src/employee-frontend/components/unit/tab-groups/groups/GroupModal.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/group/GroupUpdateModal.tsx
- frontend/src/lib-common/generated/api-types/daycare.ts
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/RawReportControllerTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareGroupQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/DaycareService.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V501__aromi_customer_id.sql
- service/src/main/resources/migrations.txt
Aromi-ruokatilauksia varten tarvitaan tekstimuotoinen ryhmäkohtainen asiakastunnus. Muutoksen myötä se on mahdollista lisätä ryhmää luotaessa ja muokatessa. PR parantaa myös ryhmien luonnin käytettävyyttä estämällä nimettömien ryhmien luomisen ja pakottamalla ryhmätietojen päivityksen uuden ryhmän luonnin jälkeen.
Aromi-tunnuksen syöttäminen on näkyvillä ainoastaan käyttöliittymän lipun `aromiIntegration` aktivoineille konfiguraatioille. Espoon konfiguraatioon lippu asetettu päälle lokaaliin (default) ja pois stagingissa sekä prodissa.
Tunnus on lisätty myös raakaraportille, jotta sen kokonaistilannetta voidaan tarkastella yksikkönäkymää korkeammalta tasolta.
> Lisätty Aromi-ruokatilausten asiakastunnus ryhmille ja nostettu se näkyville raakaraportille

- frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
- frontend/src/employee-frontend/components/IncomeStatementPage.tsx
- frontend/src/lib-common/generated/api-types/incomestatement.ts
- frontend/src/lib-common/income-statements/body.ts
- frontend/src/lib-common/income-statements/form.ts
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
- service/src/main/resources/db/migration/V502__income_statement_gross_no_income.sql
- service/src/main/resources/migrations.txt
> Lisätään ei tuloja -vaihtoehto tuloselvityslomakkeeseen

- frontend/src/employee-frontend/components/Units.tsx
- frontend/src/employee-frontend/state/units.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
ja korjataan sorttaus osoitteen mukaan
> Lisätään yksikköhakuun kunta-sarake

- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
Ennen oli vain edelliseen päivään asti
> Vanhempainvapaata voi pitää vielä lapsen toisena syntymäpäivänä

- frontend/src/employee-frontend/components/reports/csv.spec.ts
- frontend/src/employee-frontend/components/reports/csv.ts
- Käytetään kenttien erottimena puolipistettä (suomenkielisen Excelin oletus)
- Lisätään tiedoston alkuun BOM `U+FEFF` (Excel käyttää sitä tiedoston enkoodauksen arpomiseen)
> Raporttien CSV-latauksen korjauksia

- frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
- frontend/src/citizen-frontend/applications/editor/validations.ts
- frontend/src/lib-common/form-validation.ts
- frontend/src/lib-components/i18n.tsx
- frontend/src/lib-components/utils/TestContextProvider.tsx
- frontend/src/lib-customizations/defaults/components/i18n/en.tsx
- frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
Täydentävän varhaiskasvatuksen aloituspäivämäärä pitää olla samalla toimintakaudella kuin valittu esiopetuksen aloituspäivämäärä.
> Lisätään esiopetushakemukselle täydentävän varhaiskasvatuksen aloituspäivämäärän validointi

- frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/AttendanceSummaryTable.tsx
- frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceNeedAndDailyServiceTimeSection.tsx
- frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/queries.ts
- frontend/src/lib-common/generated/api-types/placement.ts
- frontend/src/lib-common/generated/api-types/serviceneed.ts
- service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/Placement.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeed.kt
- service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedQueries.kt
Näytetään laskuri vain jos sijoituksen yksiköllä on varaukset-toiminto päällä.
> Korjataan sopimuspäivälaskurin näkyvyys

- frontend/src/e2e-test/pages/mobile/staff-page.ts
- frontend/src/e2e-test/specs/6_mobile/planned-staff-attendances.spec.ts
- frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
- frontend/src/employee-mobile-frontend/App.tsx
- frontend/src/employee-mobile-frontend/common/BottomNavbar.tsx
- frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
- frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendanceEditPage.tsx
- frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
- frontend/src/employee-mobile-frontend/staff-attendance/StaffMarkDepartedPage.tsx
- frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx
- frontend/src/employee-mobile-frontend/staff-attendance/StaffPreviousAttendancesPage.tsx
- frontend/src/lib-common/generated/api-types/attendance.ts
- frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
> Näytetään tulevien päivien suunnitellut työvuorot työntekijän mobiilissa

- service/sarmamodel/build.gradle.kts
xjctool ei ollut yhteensopiva modernien `jaxb` versioiden kanssa (#6504)
> Korvataan xjctool Gradle plugin suoralla xjc käytöllä

- frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposals.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Jos yksikön johtajalla on kymmeniä tai satoja sijoitusehdotuksia läpikäytävänä (esim. ehdottavan esiopetuksen prosessi), jää vahvista-nappi tällä hetkellä helposti piiloon taulukon loppuun. Korjattu muuttamalla vahvista-nappi näkymään aina taulukon päällä riippumatta rivien määrästä.
> Sijoitusehdotusten massahyväksynnän parantaminen

- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Osa johtajista oli luullut, että aloituspvm on se oikea pvm, milloin siirto toteutuu.
> Muutetaan yksikön siirtohakemusten listauksen sarakkeen nimi

- service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
Tällä hetkellä esiopetushakemusten tuonti luottaa oletuspalveluntarpeeseen. Tämä ei kuitenkaan käy Tampereella, koska oletuspalveluntarve täytyy olla toimintamuodon maksimilaskun määrä, jotta sopimuksen ylityksen laskutus toimii oikein.
> Lisätään palveluntarpeen konfigurointimahdollisuus esiopetushakemusten tuontiin

- frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
- frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-income.spec.ts
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
_Ennen muutosta:_
Tulotietojen voimassaolon aika oli ennen maksuperusteen valintaa, joka saattoi mm. muuttaa voimassaolon kenttien pakollisuutta.
_Muutoksen jälkeen:_
Voimassaolokenttä asetettu maksuperusteen mukaan ao. valinnan alle.
> Muutos tuloselvityksen täytön järjestykseen

- frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx
- frontend/src/lib-common/api-types/application/ApplicationFormData.ts
**Ennen**: Uuden yksikön lisäys saattoi järjesti aiemmin valitut yksiköt aakkosjärjestykseen.
https://github.com/user-attachments/assets/39bf2e80-036a-47f1-8b26-0936fab596bd
**Jälkeen**:
https://github.com/user-attachments/assets/89ce069a-2dc1-4100-82f3-bef525f9a388
> Säilytetään hakutoiveiden järjestys

- frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx
- frontend/src/citizen-frontend/applications/editor/verification/ApplicationVerificationView.tsx
- frontend/src/citizen-frontend/applications/editor/verification/ServiceNeedAttachments.tsx
- frontend/src/citizen-frontend/applications/editor/verification/ServiceNeedSection.tsx
- frontend/src/citizen-frontend/applications/read-view/ApplicationReadViewContents.tsx
- frontend/src/e2e-test/pages/citizen/citizen-applications.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts
- service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
**Ennen:**
Hakemuksen liitteet näkyivät toiselle huoltajalle, mutta hän ei saanut niitä auki (vaan sai virheilmoituksen).
**Jälkeen:**
Hakemuksen liitteitä ei näytetä lainkaan toiselle huoltajalle.
> Piilotetaan hakemuksen liitteet toiselta huoltajalta

- frontend/src/employee-frontend/components/reports/Raw.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Työntekijän käyttöliittymällä näkyvä nimi muutetaan kentällä tunnetuksi termiksi käyttöönottoa varten. Näkyvillä ainoastaan `aromiIntegration` lipun aktivoineille.
Muutospaikat:
- ryhmän luonti
- ryhmän muokkaus
- raakaraportti
> Muutetaan Aromin asiakastunnuksen nimi vastuuyksikkökoodiksi 

- lefthook.yml
Add `–-no-warn-ignored` flag so that eslint doesn't error when `staged_files` contains an ignored file (e.g. files generated by codegen).
> Fix precommit when modifying generated files

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/ReplacementInvoicesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Asettamalla `FeatureConfig.minimumInvoiceAmount` voi määrittää pienimmän loppusumman laskulle. Tätä pienemmät laskut jätetään luomatta. Jos oikaisulasku jää alle minimin, generoidaan nollaoikaisulasku.
> Konfiguroitava minimilasku

- frontend/src/citizen-frontend/applications/ChildApplicationsBlock.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/application/DecisionMessageProcessor.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/IMessageProvider.kt
- Lisätään mahdollisuus hyväksyä automaattisesti esikoulupäätökset kysymättä huoltajan vahvistusta (feature flag)
- Muutetaan kuntalaisen käyttöliittymän hakemuslistausta näyttämään tilaksi "Vahvistettavana huoltajalla", kun hakemusta ei ole hylätty ja hakemukseen liittyy käsittelemättömiä päätöksiä
> Mahdollistetaan esikoulupäätösten hyväksyntä ilman huoltajan vahvistusta

- frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt
Loma-ajan kyselyn muistutus ja vastaus nappi oli näkyvissä kuntalaiselle vaikka yhdellekkään lapselle ei ollut tarjolla valittavaa vastausta
Turhia kyselyitä ja niiden muistutuksia ei näytetä
> Estetään loma-ajan kyselyn turha näkyminen kuntalaiselle

- frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx
Lapsen ikä "Ryhmää odottavat lapset" kohdassa lasketaan väärästä päivämäärästä (=sijoituksen alkupäivästä), vaikka oikea toiminnallisuus olisi tietysti ryhmityksen puuttumisen alkupäivä.
> Korjataan ryhmää odottavien lasten ikäsarake

- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
> Tuloselvityksen tekstimuutos

- frontend/src/e2e-test/pages/employee/finance/finance-page.ts
- frontend/src/e2e-test/specs/4_finance/invoices.spec.ts
- frontend/src/employee-frontend/components/invoices/Actions.tsx
- frontend/src/employee-frontend/components/invoices/InvoiceFilters.tsx
- frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
- frontend/src/employee-frontend/components/invoices/queries.ts
- frontend/src/employee-frontend/generated/api-clients/invoicing.ts
- frontend/src/lib-common/generated/action.d.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Työntekijän puoli:
Lähetettyjen laskujen listaan lisätty samanlaiset checkboxit kuin luonnosten listaan. -> Valitse lähetetty lasku(t) ja lähetä uudelleen.
Modaalin tekstit/ux hieman draftimaiset.
https://github.com/user-attachments/assets/16d11697-e2d1-4581-9f6c-08696aebc822
> Laskujen uudelleenlähetys

- frontend/package.json
- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/DiscussionTimeExport.tsx
- frontend/src/citizen-frontend/calendar/DiscussionTimeExportButton.tsx
- frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionSurveyModal.tsx
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/e2e-test/pages/citizen/citizen-discussion-surveys.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-discussion-surveys.spec.ts
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- frontend/yarn.lock
Lisää kuntalaisen kalenterin päivämodaaliin ja keskusteluaikavarausmodaaliin napin, joka tuottaa validin ical ics tapahtuman, jonka voi liittää omaan ical-tuen sisältävään kalenterisovellukseensa. Nappi näytetään tehdyille aikavarauksille, jotka eivät ole menneisyydessä.
Kalenteritapahtumaan tulee:
- Otsikko: keskustelukyselyn nimi
- Aikaväli: keskusteluaikavarauksen aika
- Sijainti: keskustelukyselyn yksikkö + ryhmä
> Lisätään kuntalaiselle mahdollisuus ladata keskusteluaikavaraus ulkopuoliseen kalenteriin

- apigw/src/app.ts
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
- servicessä oli muutama käyttämätön endpoint taaksepäin yhteensopivuuden takia
- apigw:ssä oli paljon rewritejä taaksepäin yhteensopivuuden takia
- Jostain syystä apigw:ssä oli yhä /internal/auth/status, jota ei näytetä käytettävän missään
> Siivotaan käyttämättömiä endpointteja

- apigw/src/shared/__tests__/saml-slo.ts
- apigw/src/shared/config.ts
- apigw/src/shared/saml/index.ts
On macOS, it seems that colima virtual machine may be a few milliseconds behind the host machine's clock, which makes dummy-idp logins fail. Fix this by allowing a bit of clock skew in SAML validation.
> Sallitaan pieni kellopoikkeama dummy-idp:lle lokaalissa kehityksessä

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/generated/api-types.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts
- service/build.gradle.kts
- service/evaka-bom/build.gradle.kts
- service/src/integrationTest/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentService.kt
- service/src/main/kotlin/fi/espoo/evaka/document/archival/DocumentMetadataUtils.kt
- service/src/main/kotlin/fi/espoo/evaka/document/archival/SärmäHttpClient.kt
- service/src/main/kotlin/fi/espoo/evaka/document/archival/SärmäMockClient.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/test/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceTest.kt
Särmän APIn HTTP 200 tulkittiin onnistuneeksi arkistoon vienniksi, vaikka todellisuudessa HTTP 200 saattoi sisältää response bodyssä virheviestin "validaatio failure"
Särmän API response pyydetään `response_format` `"URL-ENCODED"` muodossa ja tästä parsitaan `status_code` tieto. Lisätty myös integraatiotestit
> Luetaan Särmän vastauskoodi oikeasta paikasta

- frontend/src/employee-frontend/components/document-templates/template-editor/TemplateSectionView.tsx
Osion toimintonapit menivät alueen ulkopuolelle kun osion infoteksti oli avattuna
> UI-korjaus lomakepohjaeditoriin

- service/src/integrationTest/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentService.kt
Meille ei jäänyt pitkäaikaisesti talteen Särmään muodostuneen arkistoidun asiakirjan tunnistetta.
Särmään luodun asiakirjan tunniste logitetaan
> Logitetaan Särmään muodostuneen asiakirjan sisäinen tunniste

- service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
Tuloselvityksen listaus ei huomioinut, että puolisosuhteen päättymispäivämäärä voi olla `NULL`.
> Korjataan tuloselvityslistauksen alue-sarakkeen haku

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/generated/api-types.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/TampereRegionalSurveyTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/TampereRegionalSurvey.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Tunnistetaan kouluilla tapahtuvan täydentävän esiopetuksen yksiköt "Koulun yhteydessä" lipun perusteella Tampereen seutuselvityksen tilastoinnissa.
> Tampereen seuturaportoinnin "koulun yhteydessä"- filtterin käyttöönotto

- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
_Ennen muutosta:_
Kun työntekijän mobiilissa muokkaa tulevia varauksia (ja vaikkei muuttaisi mitään) ja painaa vahvista, muuttuvat aikavälin merkinnät henkilökunnan tekemiksi.
_Muutoksen jälkeen:_
Tarkistetaan backendilla mitkä varaukset ovat muuttuneet ja muokataan vain niitä.
(Poikkeuksena jos samalla päivällä on kaksi varausta ja työntekijä muokkaa yhtä tai lisää niistä toisen, tulevat molemmat merkityksi henkilökunnan tekemiksi)
> Varauksen muokkaaminen työntekijän mobiilissa ei muuta koko aikaväliä henkilökunnan merkinnöiksi

- frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposals.tsx
Ennen muutosta toimintopalkki oli koko ruudun levyinen ja tökerön näköinen vieriessään pystysuunnassa.
Muutoksen jälkeen toimintopalkki on yhtä leveä kuin varsinaiselle sisällölle varattu tila, ja se tarrautuu taulukon päälle näkyviin ainoastaan silloin, kun on valittu vähintään yksi hakemus hyväksyttäväksi.
https://github.com/user-attachments/assets/b7caeef4-7905-46e1-bfac-7b8b3a0b3bfe
> Korjaus sijoitusehdotusten toimintopalkin vieritykseen

- frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Esim. eskarihakemuksella voidaan sanoa "Valitse yksi vaihtoehto" ja kerhohakemuksella "Laita 1-3 kerhoa toivomaasi järjestykseen.".
> Lisätään hakemukselle tuki muuttaa yksikön valinnan ohjeteksti hakemuksen tyypin mukaan

- frontend/src/e2e-test/specs/5_employee/income.spec.ts
hypoteesi: liian nopea peruuta-napin klikkaus keskeyttää liitteen poistamisen, joten odotetaan jo ennen sitä että liite poistuu
> Korjataan flaky e2e testi

- .github/renovate.json5
- .github/workflows/release.yml
Changes in this PR:
- Make a release on Friday evening
- Update dependencies during the weekeend
This way, each release has about week-old dependency updates, and dependency updates are deployed in environments in the beginning of the week, which helps pinpoint potential problems to dependency updates instead of eVaka's own code.
As an unrelated change, also configure renovate to pin dependencies to exact versions. This way the actual used package versions are recorded in package.json in addition to lockfile.
> Change release and dependency update schedules

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Ennen korjausta ryhmän tai yksikön aloittaville lapsille lähetetty viesti lähetettiin virheellisesti myös sellaisille lapsille, jotka jo ennestään ovat kyseisessä ryhmässä, mutta joilla oli uusi sijoitus tulevaisuudessa samaan ryhmään. Näitä lapsia ei kuitenkaan näkynyt viestieditorin vastaanottajien valintapuussa. Tällaisia lapsia ovat tyypillisesti esikoululaiset, jotka jatkavat tulevan kesän samassa ryhmässä.
> Korjaus aloittavien lasten viestintään

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SanityChecksTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/SanityChecks.kt
- Sama lapsi päällekkäisillä maksupäätöksillä (Espoon tuotanto: 44 kpl)
- Varasijoitus sijoitusten ulkopuolella (146)
- Varaus sijoitustyypillä joka ei salli varauksia (6784)
> Lisää sanity checkejä

- frontend/src/citizen-frontend/calendar/CalendarEventExportButton.tsx
- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionSurveyModal.tsx
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Laajentaa ics-tiedoston lataamisen keskusteluaikojen lisäksi koko päivän tai useamman päivän kalenteritapahtumiin yksittäisen kalenteripäivän näkymässä. Parantaa samalla VTIMEZONE käsittelyä kohdentamalla aikavyöhykkeen paremmin.
> Lisätään kuntalaiselle mahdollisuus ladata kalenteritapahtuma ulkopuoliseen kalenteriin

- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Aiemmin vain pääkäyttäjä pystyi tarkastelemaan em. tietoja.
> Sallitaan lapsen läsnä- ja poissaolotietojen näkyminen henkilökunnalle

- service/settings.gradle.kts
Gradle antaa esim. `assemble`-komennolla varoituksen: "Configuring project ':sficlient' without an existing directory is deprecated.".
Projekti on poistettu https://github.com/espoon-voltti/evaka/pull/6405.
> Korjataan gradle-varoitus

- frontend/src/citizen-frontend/children/sections/ChildDocumentsSection.tsx
- frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts
- frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt
Aiemmin työntekijän tietoja ei tallennettu ollenkaan, eikä niitä siten voitu näyttääkään.
Kuntalaisen puolelta piilotetaan tällaisessa tapauksessa vastaajan nimi.
> Lisätään työntekijätiedot lomakkeen vastaaja-kenttään

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/generated/api-types.ts
- frontend/src/e2e-test/pages/employee/documents/document-templates.ts
- frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
- frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
- frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
- frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
- frontend/src/lib-common/generated/api-types/document.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/document/DocumentTemplateIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
- service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
- service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentService.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V521__document_template_archiveable.sql
- service/src/main/resources/migrations.txt
- service/src/test/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceTest.kt
Asiakirjojen arkistoitavuus määräytyi kovakoodatusti asiakirjatyypin perusteella. Vain tietyt asiakirjatyypit (`VASU`, `LEOPS`, `HOJKS`, `MIGRATED_VASU`, `MIGRATED_LEOPS`) voitiin lähettää ulkoiseen arkistoon. Asiakirjan tyyppi tarkastettiin vasta kun `AsyncJob` ajettiin
Asiakirjapohjiin on lisätty uusi flägi `archiveExternally`, joka määrittää, voidaanko asiakirjapohjan mukainen asiakirja arkistoida ulkoiseen järjestelmään. Muutoksen myötä:
- Dokumenttipohjan editoriin on lisätty checbox "Siirrettävä ulkoiseen arkistoon ennen poistoa"
- Yksittäisen asiakirjan "Arkistoi" toiminta on deaktivoitu asiakirjoille, joiden pohjaa ei ole merkitty ulkoisesti arkistoitavaksi
- Tietokantamigraatio asettaa flägin arvoksi `TRUE` niille asiakirjatyypeille, joilla oli aiemmin kovakoodattu tuki …
> Lisää asiakirjapohjiin ulkoisen arkistoinnin mahdollistavan flägin

- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/lib-common/generated/api-types/messaging.ts
- frontend/src/lib-common/generated/api-types/placement.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementType.kt
Lisättiin sijoitustyyppi filtteriksi massaviestintään. Sijoitustyypit ryhmiteltiin kolmeen kategoriaan: kerho, esiopetus ja  varhaiskasvatus. Slack-drafti ryhmittelystä:
Näyttää ui:ssa tältä:
https://github.com/user-attachments/assets/18002e16-4c4c-4737-afcb-e1f79c4be722
> Massaviestinnän lisäfiltteri sijoitustyyppi

- frontend/src/citizen-frontend/income-statements/IncomeStatementComponents.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
- frontend/src/e2e-test/pages/citizen/citizen-income.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- Sallitaan *Tallenna ja jatka myöhemmin* ja *Lähetä* -nappien painaminen aina.
- Jos lomake on tilassa, jossa em. toimintoa ei voi suorittaa, ruutu skrollaa napin painalluksesta ensimmäiseen virheelliseen kenttään.
- Piilotetaan *Lomakkeelta puuttuu...* teksti heti kun lomakkeella ei enää ole virheitä.
- Kun voimassaolon päättymispäivä on pakollinen, sen pitää olla vuoden sisällä alkupäivästä. Tähän liittyen lisättiin esto, että yli vuoden päässä olevia päättymispäiviä ei pysty valitsemaan.
- Poistettiin em. liittyen infolaatikko, koska lomaketta ei enää saa tilaan, jossa päättymispäivä olisi yli vuoden päässä. Jos käsin syöttämällä antaa virheellisen päättymispäivän, tästä tulee päivämäärävalitsinkomponentin oma virheilmoitus "Valitse aikaisempi päivä".
- Korjattu alareunan …
> Parannuksia tuloselvityslomakkeen puuttuvien tietojen korostukseen

- frontend/src/lib-common/generated/api-types/nekku.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
- service/src/main/resources/db/migration/V525__nekku_special_diet_type_additions.sql
- service/src/main/resources/migrations.txt
Varaudutaan deserialisoimaan ja tallentamaan kantaan myös muut Nekun tuntemat erityisruokavalion kenttätyypit kuin aiemmin käsitellyt kaksi, vaikka normaalitilanteessa varhaiskasvatuksen erityisruokavaliossa ei pitäisi muita olla
> Korjaus Nekun erityisruokavalioiden kenttätyyppien käsittelyyn

- service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
Huoltaja voi ilmoittaa kolmea eri poissaolotyyppiä:
1) Sairaus (`SICKLEAVE`)
2) Poissaolo (`OTHER_ABSENCE`)
3) Vuorotyöpoissaolo (`PLANNED_ABSENCE`), käytössä vain Espoolla.
Jos lapsella on palveluntarpeena sopimuspäivät tai tuntiperustainen, tallentuu poissaoloksi tällä hetkellä "Sopimuksen mukainen poissaolo" (`PLANNED_ABSENCE`) kun valitaan poissaolotyypiksi vaihtoehto 2. Lisäksi jos lapsi on esiopetuksessa ja täydentävässä varhaiskasvatuksessa, tallentuu kyseinen poissaolo sekä esiopetukseen (`NONBILLABLE`) että varhaiskasvatukseen (`BILLABLE`). Sopimuksen mukaisen poissaolon tallennus esiopetukseen on väärin, jonka tämä muutospyyntö korjaa.
Vaihtoehto 3 pitäisi edelleen toimia samalla tavalla kuin ennenkin eli valittu Vuorotyöpoissaolo tallentuu sekä esiopetukseen että liittyvään …
> Korjataan maksuttoman poissaolon tyyppi

- frontend/src/e2e-test/pages/employee/messages/messages-page.ts
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
- frontend/src/employee-frontend/components/messages/queries.ts
- frontend/src/employee-frontend/generated/api-clients/messaging.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
Lisätään myös työntekijän puolelle mahdollisuus merkitä säikeen viimeinen luettu viesti lukemattomaksi.
> Merkitse viesti lukemattomaksi (työntekijä)

- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/children/sections/placement-termination/PlacementTerminationForm.tsx
- frontend/src/e2e-test/pages/employee/units/unit-week-calendar-page.ts
- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-frontend/components/person-profile/PersonFeeDecisions.tsx
- frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx
- frontend/src/employee-mobile-frontend/App.tsx
- frontend/src/lib-components/molecules/date-picker/DatePickerDay.tsx
- frontend/src/lib-components/molecules/date-picker/DatePickerInput.tsx
- frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
Sen lisäksi että `DatePicker` saa nyt kokonaan oman [stacking contextin](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Stacking_context), ja siten näkyy myös modaalien ulkopuolella, se myös asemoituu automaattisesti inputin yläpuolelle jos alapuolella ei ole tilaa. `react-focus-lock` palauttaa fokuksen kun päivämäärävalitsin suljetaan, joten myös saavutettavuus säilyy.
Ennen:
Jälkeen:
> Korjataan päivämäärävalitsimen näyttö modaalien sisällä

- frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
Salassapitoperuste ja -aika kentät olivat muokattavissa vain uutta lomakepohjaa luodessa `TemplateModal`issa
Kentät ovat muokattavissa myös `TemplateContentEditor`in `BasicsEditor`issa.
> Salassapitoperuste ja -aika kentät dokumenttipohjaeditoriin

- service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
Jos Nekun asiakasnumeroita päivitättäessä havaitaan että jollekin ryhmälle asetettu asiakasnumero on poistunut Nekusta, yksikön johtajalle lähetetään sähköpostissa tieto tilanteesta ja ryhmistä joita se koskee
> Lähetetään yksikön johtajalle sähköposti jos ryhmän Nekku-asiakasnumero poistuu

- frontend/src/employee-frontend/components/person-profile/FosterChildren.tsx
- frontend/src/employee-frontend/components/person-profile/PersonApplications.tsx
- frontend/src/employee-frontend/components/person-profile/PersonDecisions.tsx
- frontend/src/employee-frontend/components/person-profile/PersonDependants.tsx
- frontend/src/employee-frontend/components/person-profile/PersonFamilyOverview.tsx
- frontend/src/employee-frontend/components/person-profile/PersonFeeDecisions.tsx
- frontend/src/employee-frontend/components/person-profile/PersonFinanceNotesAndMessages.tsx
- frontend/src/employee-frontend/components/person-profile/PersonFridgeChild.tsx
- frontend/src/employee-frontend/components/person-profile/PersonFridgePartner.tsx
- frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx
- frontend/src/employee-frontend/components/person-profile/PersonInvoiceCorrections.tsx
- frontend/src/employee-frontend/components/person-profile/PersonInvoices.tsx
- frontend/src/employee-frontend/components/person-profile/PersonProfile.tsx
- frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx
- frontend/src/employee-frontend/components/person-profile/income/IncomeList.tsx
- frontend/src/employee-frontend/components/person-profile/queries.ts
- frontend/src/employee-frontend/components/person-profile/state.tsx
Sen sijaan että aikuisen sivulla haettaisiin piilossa olevien osioiden data heti, haetaan data vasta kun osiot avataan. Muutetaan myös moni paikka käyttämään react-queryä, joka on esiehto tälle toiminnallisuudelle.
Alla olevista kuvista näkee HTTP requestien määrät kun aikuisen sivu avataan pääkäyttäjän roolilla (talouden muistiinpanot ja viestit sekä perheen tietojen kooste ovat auki oletuksena).
**Ennen:**
**Jälkeen:**
> Haetaan aikuisen sivun tiedot kun niitä tarvitaan

- frontend/src/lib-common/generated/action.d.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationControllers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt
Henkilökunta saa nähdä omien ryhmien hakemukset, mutta hyväksyä maksimissaan viikon pituiset hakemukset.
Yksikön johtaja saa hyväksyä yli viikon pituiset hakemukset.
> Lisätään henkilökunnalle käyttöoikeudet esiopetuksen poissaolohakemuksiin

- frontend/src/e2e-test/pages/employee/reports.ts
- frontend/src/e2e-test/specs/5_employee/assistance-need-and-actions-report.spec.ts
- frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
- frontend/src/employee-frontend/generated/api-clients/reports.ts
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportControllerTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportController.kt
Raportille lisätty:
- 2 laskurisaraketta kaikkiin näkymiin:
- Aktiiviset varhaiskasvatuksen tuen päätökset 
- Aktiiviset esiopetuksen tuen päätökset
- näkymäfiltteri yksikön järjestämismuodon mukaan
- monivalinta-hakufiltteri toimintamuodon (sijoitustyyppi) mukaan
- käyttää mukautuksen sijoitustyyppilistausta 
Lisätty integraatiotestit hakumuutoksille ja e2e testit kaikille muutoksille.
> Lasten tuen tarpeet ja tukitoimet -raportin lisäykset

- service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
- service/src/main/resources/db/migration/V534__fix_nekku_special_diet_choices.sql
- service/src/main/resources/migrations.txt
Korjataan ongelma, jossa Nekku-erikoisruokavaliokenttien poistaminen epäonnistuu, jos niitä on käytetty jonkun lapsen erikoisruokavaliossa. Nyt erikoisruokavaliokenttien päivitys onnistuu ja poistetut valinnat poistuvat myös lapsilta.
> Korjataan Nekku-erikoisruokavaliovalinnat poistumaan, jos vastaavat kentät eivät ole enää valittavissa

- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceController.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/test/kotlin/fi/espoo/evaka/shared/logging/AuditIdTest.kt
Osa 1/x
Muokattu apien audit-lokitusta, lisätty lapsen/lasten id:t lokieventin `objectId`-parametriin.
Lisätty mahdollisuus yhdistää useamman tyypin AuditId saman parametrin arvoksi.
> Lapsen id audit-lokiin

- frontend/src/e2e-test/specs/8_access/access.spec.ts
- frontend/src/employee-frontend/components/child-information/ChildInformation.tsx
Käyttöliittymään pitää erikseen lisätä näkyvyys uusille osioille roolikohtaisesti. Korjaa muutoksen https://github.com/espoon-voltti/evaka/pull/6997 näkymisen käyttöliittymään.
> Korjataan esiopetuksen poissaolohakemuksien näkyminen henkilökunnalle

- service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationControllers.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
Esim. jos lapsella on palveluntarpeena sopimuspäivät, pitäisi maksullisen poissaolon tyypiksi tulla `PLANNED_ABSENCE`.
Käytetään toteutuksena samaa kuin huoltaja itse tekisi poissaolot.
> Korjataan esiopetuksen poissaolohakemuksen poissaolotyypit

- service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
Korjataan Nekun integraatiotestit toimimaan vaikka tuotantokoodin tuottamat rivit olisivat satunnaisesti eri järjestyksessä
> Korjataan Nekun integraatiotestejä

- service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
Päiväkodin seuraavalle aukiolopäivälle pitää tehdä tarkennustilaus. Korjaa myös sen jos Nekkutilauksia yritetään tehdä viikonlopulle, vaikka yksikön operaatiopäivät eivät sitä salli. Korjauksissa mukana tarkennustilaus ja viikkotilaus.
> Päiväkodin seuraavalle aukiolopäivälle pitää tehdä tarkennustilaus

- service/src/main/kotlin/fi/espoo/evaka/espoo/EspooScheduledJobs.kt
Myös oletuksena yöllisessä ajossa olevien jobien ajoaikatauluja voi säätää ympäristömuuttujilla. Näin ollen Linkity-jobit voidaan siirtää yöllisiin ajoihin.
> Tekninen: Ajetaan Linkity-jobit yöllisessä ajossa

- frontend/src/citizen-frontend/index.tsx
- frontend/src/employee-frontend/index.tsx
- frontend/src/employee-mobile-frontend/index.tsx
- frontend/webpack.config.js
- frontend/yarn.lock
Aiemmin tuotantobuildeihin otettiin mukaan *kaikki* polyfillit, jotka tarvittiin toteuttamaan stabiilit ES- ja web-ominaisuudet [package.jsonissa listatuille tuetuille selaimille](https://github.com/espoon-voltti/evaka/blob/b65c71034efd7004c9842c5ef331f42aa59ea2ee/frontend/package.json#L159-L171):
* Kaikissa fronteissa `import 'core-js/stable'`
* `@babel/present-env`-konffi: `useBuiltins: 'entry'`
Nyt sen sijaan sisällytetään polyfillit vain niille ominaisuuksille joita koodissa oikeasti käytetään:
* Ei eksplisiittisiä `core-js` importteja
* `@babel/present-env`-konffi: `useBuiltins: 'usage'`
Tämä on valmistelua vite-tuotantobuildia varten, koska vitessä polyfillaus toimii näin.
> Sisällytetään polyfillit käytön perusteella

- frontend/vite.config.ts
Redirect from `/employee/mobile` to `/employee/mobile/`. Service worker is served from `/employee/mobile/service-worker.js`, so its scope is `/employee/mobile/`. Without the trailing slash, the service worker doesn't work because it's "out of scope".
Also redirect from `/employee` to `/employee/` for consistency.
While at it, use `text/javascript` which is the correct content type for JavaScript.
> Varmistetaan service workerin toiminta lokaalissa kehityksessä

- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
Erillinen `ChildAudit`-lokitustapa eventteihin joissa on korkeampi tarve seurata lapsen tietojen käsittelyä. Pohjana `Audit` enum classin `log`-funktio, johon vaihdettu tarkoituksen ohjaamiseksi `objectId`-parametrin nimeksi `childId`. Lopulliseen lokitukseen mapataan kuitenkin `childId` parametriin `objectId`.
> Audit-lokiin objectId pakolliseksi valittuihin tapahtumiin

- frontend/src/e2e-test/pages/employee/units/unit-month-calendar-page.ts
- frontend/src/e2e-test/specs/5_employee/month-calendar.spec.ts
- frontend/src/employee-frontend/components/absences/MonthCalendarCell.tsx
- frontend/src/employee-frontend/components/absences/UnitCalendarDayCellTooltip.tsx
- frontend/src/lib-common/generated/api-types/absence.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceController.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayQuestionnaireQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayQuestionnaires.kt
Yksikön kuukausikalenteriin lisätty loma-ajan puuttuvien varausten huomautusta vastaava merkintä puuttuville poissaolokyselyn vastauksille. Ominaisuus fronttilipun takana.
> Tieto päiväkirjalle jos huoltajat eivät ole vastanneet poissaolokyselyyn

- service/src/main/kotlin/fi/espoo/evaka/document/archival/DocumentMetadataUtils.kt
- service/src/test/kotlin/fi/espoo/evaka/document/archival/DocumentMetadataUtilsTest.kt
Asian sulkemispäivä jätettiin määrittelemättä metadatassa jos prosessihistoriasta ei löytynyt sulkemispäivää.
- Jos sulkemispäivää ei ole saatavilla prosessihistoriasta, käytetään lomakkeen voimassaolon päättymispäivää
- Jos sekään ei ole saatavilla, lasketaan seuraava heinäkuun 31. päivä asiakirjan luontipäivästä
Lisätty myös testejä metadatan muodostuksen logiikalle.
> Arkistointi metadata: Asian päättymispäivä logiikan parannus

- frontend/src/employee-frontend/components/unit/tab-groups/groups/GroupModal.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/group/GroupUpdateModal.tsx
Toteuttaa trimmauksen Aromin vastuuyksikkökoodin arvolle sekä uuden ryhmän luonnissa että ryhmää muokatessa siten, että:
- tallennettu versio ei sisällä koskaan välilyöntejä syötetyn arvon alussa tai lopussa
- koodikenttään voi syöttää tai liittää vapaasti tekstiä välilyönnit mukaanlukien
- tyhjän koodiarvon varoituslaatikko näkyy myös, jos trimmauksen jälkeinen arvo = tyhjä arvo
> Trimmaa Aromin vastuuyksikkökoodi ennen tallennusta

- frontend/src/employee-frontend/components/child-documents/ChildDocumentReadView.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Lisää ohjetekstin vahvistusikkunaan kun työntekijä palauttaa lasten asiakirjan takaisin luonnokseksi:
> Lisää ohjeteksti lasten asiakirjan luonnospalautuksen vahvistusikkunaan

- frontend/src/e2e-test/pages/employee/documents/child-document.ts
- frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
- frontend/src/employee-frontend/components/child-documents/ChildDocumentReadView.tsx
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
Muuttaa:
- käyttöoikeuslaajennos yksikön johtajalle ja ryhmän henkilökunnalle vastauksettomien kuntalaisen lomakkeiden palauttamiseen luonnokseksi
-  HUOM! sivuvaikutuksena oikeus tulee myös VEO:lle, tarkistettu PO:lta -> tämä OK
Palauttamisen oikeuttaminen antaa mahdollisuuden jo lähetettyjen, mutta vastaamattomien lomakkeiden palauttamiseen editoitavaksi -> henkilökunta voi vastata kuntalaisen puolesta tapauksissa, joissa kuntalainen ei käytä eVakaa.
> Lisätään yksikön johtajalle ja ryhmän henkilökunnalle oikeus palauttaa lähetetty kuntalaisen lomake luonnokseksi

- frontend/src/employee-frontend/components/child-information/AbsenceApplicationsSection.tsx
- frontend/src/lib-common/generated/action.d.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationControllers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/OperationalDays.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt
Henkilökunta saa hyväksyä maksimissaan viiden päivän hakemukset huomioiden esiopetuksen toimintapäivät.
> Korjataan esiopetuksen poissaolohakemuksen käsittelyn käyttöoikeudet

- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/DaycareEditIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/JdbiExtensions.kt
Jos karttakoordinaatit-kentän tyhjensi ja tallensi, tallentui tietokantaan `0, 0`.
> Korjataan yksikön karttakoordinaattien tyhjennys

- frontend/src/employee-frontend/components/reports/Decisions.tsx
- frontend/src/employee-frontend/generated/api-clients/reports.ts
- frontend/src/lib-common/generated/api-types/application.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ReportSmokeTests.kt
- service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/DecisionsReport.kt
Yksikkö voi tarjota sekä varhaiskasvatusta että esiopetusta. Tämän avulla hakutoiveiden määriä saa listattua erikseen näiden osalta.
> Lisätään päätökset-raportille hakemuksen tyypin mukaan suodatus

- service/sarmamodel/src/main/schema/yleinen/yleinen-1.0.xsd
Särmän skeema tiedosto `yleinen-1.0.xsd` perustui Särmän testiympäristöön tehtyyn kenttien järjestykseen.
Skeema perustuu Särmän tuotantoympäristön kenttiin.
> Särmän metadata skeeman päivitys

- frontend/.dockerignore
- frontend/.yarn/patches/unplugin-npm-1.0.1-70bc9bb0e2.patch
- frontend/Dockerfile
- frontend/package.json
- frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
- frontend/src/lib-customizations/espoo/appConfigs.ts
- frontend/src/lib-customizations/espoo/citizen.tsx
- frontend/src/lib-customizations/espoo/employee.tsx
- frontend/src/lib-customizations/espoo/employeeMobile.tsx
- frontend/vite.config.ts
- frontend/yarn.lock
Suurin käyttäjiin mahdollisesti vaikuttava muutos on, että lopullinen JavaScript-koodi käyttää ES-moduuleita, joita kaikki yleisimmät selaimet ovat tukeneet viimeistään vuodesta 2020. (Näin vanhojen selainten käyttö olisi itsessäänkin jo tietoturvariski käyttäjälle.)
`yarn build` nopeutuu Viten johdosta useista minuuteista kymmeniin sekunteihin. Sen myötä myös esim. docker-composen pystytys lokaalisti sekä frontin CI build nopeutuvat huomattavasti. `yarn build`:in muistinkäyttö myös pysyy NodeJS:n rajoissa eikä muistiasetuksia tarvitse korottaa.
Siirtymäajan jälkeen voidaan poistaa webpackin konfiguraatio ja siihen liittyvät riippuvuudet. Viten konfigurointi on paljon yksinkertaisempaa kuin webpackin, mikä osaltaan myös helpottaa jatkossa ylläpitoa.
> Käytetään Viteä tuotantobuildiin

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
- service/src/main/resources/db/migration/V541__holiday_questionnaire_constraints.sql
- service/src/main/resources/migrations.txt
Yksikön kuukausikalenterin muutoksesta ilmentyi ongelma kalenterin tietojen lataamisessa, jos kalenterissa näytettävän kuukauden ajalla listattavalle lapselle oli poissolokyselyn vastauksessa `open_ranges` kentän arvona tyhjän listan sijaan `null`. Uusiin vastauksiin tällaista tilannetta ei muodostu, mutta vanhat vastaukset ovat jääneet migratoimatta.
Migratoidaan siis kaikkiin nykyisiin vastauksiin `null` -> tyhjä lista ja lisätään `not null` rajoite. Lisätään samalla sama rajoite muokkaaja, kyselyn id ja lapsen id kenttiin.
> Migratoidaan vanhat poissaolokyselyn vastaukset ja lisätään rajoituksia

- frontend/src/employee-frontend/components/person-profile/PersonFamilyOverview.tsx
> Korjataan nimettömän henkilön näyttäminen perheen tietojen koosteessa

- frontend/src/citizen-frontend/login/WeakLoginFormPage.tsx
- frontend/src/citizen-frontend/personal-details/LoginDetailsSection.tsx
- frontend/src/lib-components/atoms/form/InputField.tsx
- frontend/src/lib-components/i18n.tsx
- frontend/src/lib-components/molecules/PasswordInputF.tsx
- frontend/src/lib-components/utils/TestContextProvider.tsx
- frontend/src/lib-customizations/defaults/components/i18n/en.tsx
- frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
Lisää uuden komponentin salasanojen syöttämiselle, jossa mukana kirjoitetun sisällön näyttämisen kytkevä nappi. Komponentti otettu käyttöön kuntalaisen tunnuksella kirjautumisen käyttöliittymässä.
> Lisää kuntalaiselle mahdollisuus näyttää salasana sitä syötettäessä

- service/src/integrationTest/kotlin/fi/espoo/evaka/process/MigrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/process/Migration.kt
- Vanhan datan osalta kaikilla käyttäjillä ei välttämättä vielä ole `evaka_user`-riviä johon `archived_process_history`-taulusta viitataan, joten luodaan puuttuvat käyttäjät lennossa.
- Käytetään useampaa aikaleimaa kun päätellään milloin hakemus on siirtynyt `COMPLETED`-tilaan.
- Käytetään päätöksen hyväksyjää (kuntalainen tai henkilökunta) hakemuksen `COMPLETED`-tilaan siirtäjänä.
- Siirretään mitätöidyt maksu- ja arvopäätökset aina `COMPLETED`-tilaan
> Korjauksia metadatamigraatioon

- frontend/src/employee-frontend/components/applications/ApplicationsFilters.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
- frontend/src/employee-frontend/components/child-information/backup-care/BackupCareForm.tsx
- frontend/src/employee-frontend/generated/api-clients/daycare.ts
- frontend/src/employee-frontend/state/invoicing-ui.tsx
- frontend/src/lib-common/generated/api-types/daycare.ts
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
Korjaa täyttö- ja käyttöasteraporttia, koska yksikön toimintamuodoksi ei tarvitse pelkästään varasijoitustoiminnallisuutta varten lisätä päiväkotia.
> Lisätään esiopetusta järjestävät yksiköt varasijoituksiin

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
Mahdollistetaan pelkän esiopetushakemuksen tekeminen esiopetuspaikan osoittamisessa poistamalla oletus palveluntarpeen asettaminen.
HUOM! esiopetus ja liittyvä varhaiskasvatus hakemuksen saa yhä muodostumaan asettamalla ympäristömuuttujaan `EVAKA_PLACEMENT_TOOL_SERVICE_NEED_OPTION_ID` soveltuvan palveluntarpeen id:n
> Poistetaan esiopetuspaikan osoituksesta oletus palveluntarve

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/generated/api-types.ts
- frontend/src/employee-frontend/components/child-information/assistance/AssistanceActionForm.tsx
- frontend/src/employee-frontend/components/child-information/assistance/AssistanceActionRow.tsx
- frontend/src/employee-frontend/components/common/LabelValueList.tsx
- frontend/src/employee-frontend/generated/api-clients/assistance.ts
- frontend/src/employee-frontend/generated/api-clients/reports.ts
- frontend/src/lib-common/generated/api-types/assistanceaction.ts
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceAction.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V542__assistance_action_option_validity.sql
- service/src/main/resources/dev-data/dev-data.sql
- service/src/main/resources/migrations.txt
Kannassa oleviin kuntakohtaisiin tukitoimivaihtoehtoihin on lisätty kategoria (vaka/esiopetus) käyttöliittymässä ryhmittelyä varten sekä optionaaliset voimassaolon alku ja loppupäivät.
Oletuksena kategoria on vanhoille tukitoimille DAYCARE. Muuta se tarvittaessa. Esim Espoossa:
```
UPDATE assistance_action_option
SET category = 'PRESCHOOL'
WHERE value = 'PART_TIME_SPECIAL_EDUCATION';
```
Jos joku tukitoimi poistuu käytöstä, aseta päättymispäivä. Esim espoossa:
```
UPDATE assistance_action_option
SET valid_to = '2025-07-31'::date
WHERE value = 'PART_TIME_SPECIAL_EDUCATION';
```
Luo uudet lakimuutoksen mukaiset sekä mahdolliset muut kuntakohtaiset tukitoimet:
```
INSERT INTO assistance_action_option (value, name_fi, display_order, category, valid_from, valid_to) VALUES …
```
> Tuetaan tukitoimivaihtoehtojen muuttumista

- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt
Tämä on apukeino yksiköiden kloonaamistapauksiin, jolla säilytetään sama tuen päätös järjestelmästä johtuvista yksikön kloonaamistarpeista aiheutuville sijoitusvaihdoksille.
- aiemmin sijoituksen vaihtuminen tai päättäminen on aina päättänyt myös tuen päätöksen (vaka & eo) seuraavan yön huoltoajossa
- muutoksen jälkeen tuen päätös katkaistaan vain, jos päättyneen sijoituksen viereinen uusi voimassa oleva sijoitustyypille merkityksellinen sijoitus ei ole merkilleen samannimiseen yksikköön kuin tuen päätös
> Estetään tuen päätöksen automaattikatkaisu jos lapsi jatkaa edelleen samannimisessä yksikössä kuin päätöksen yksikkö

- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
- frontend/src/employee-frontend/components/person-profile/PersonFinanceNotesAndMessages.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
`Asiakastietosivun avaus ei tulisi merkata talouden viestejä luetuksi. `
-> poistettu toteutus.
`Sen sijaan jos viestiketjun avaa viestintäpuolelle joko talouden viestintä kohdasta tai hakemuksen sivupalkista, viestiketjun tulee merkkaantua luetuksi.`
-> siirretty merkitseminen luetuksi viestiketjun vaihdosta viestiketjun sivulle. Eli nyt mikä tahansa linkki suoraan yksittäiseen viestiketjuun merkitsee sen luetuksi.
  `Lisäksi jos jommassa kummassa näkymässä (hakemuksen viestit / asiakkaan talouden viestit) vastaa viestiin "inline editorilla" viestiketjun tulee merkaantua henkilökunnan puolella luetuksi.`
-> lisätty viestiketjun automaattinen merkitseminen luetuksi kun viestiin vastataan.
> Korjataan viestiketjun merkitseminen luetuksi

- frontend/src/e2e-test/pages/employee/guardian-information.ts
- frontend/src/e2e-test/specs/5_employee/income.spec.ts
- frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx
- frontend/src/employee-frontend/components/person-profile/income/IncomeNotifications.tsx
- frontend/src/employee-frontend/components/reports/HolidayPeriodAttendanceReport.tsx
- frontend/src/employee-frontend/components/reports/HolidayQuestionnaireReport.tsx
- frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/DiscussionSurveyView.tsx
- frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/survey-editor/DiscussionTimesForm.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Muutetaan tulotietojen muistutusviestit haitariin, jossa näytetään oletuksena 10 muistutusviestiä. Viestäjä näytetään lisää "Näytä lisää" napilla ja näytetään vähemmän "Piilota" napilla. Napit lisäävät ja vähentävät 10 viestiä kerrallaan.
> Muutetaan tulotietojen muistutusviestit haitariin

- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Tämän tuotantoonviennin jälkeen metadatamigraatio ajetaan seuraavana yönä. Se jää päälle ja esim. TOS-numeroiden lisääminen vanhoihin lomakepohjiin aiheuttaa täytettyjen lomakkeiden migratoinnin seuraavana yönä.
> Konfiguroidaan yöllinen metadatamigraatioajo päälle kaikissa kunnissa

- frontend/src/citizen-frontend/children/sections/absence-applications/NewAbsenceApplicationForm.tsx
- frontend/src/citizen-frontend/children/sections/absence-applications/NewAbsenceApplicationPage.tsx
- frontend/src/citizen-frontend/children/sections/absence-applications/queries.ts
- frontend/src/citizen-frontend/generated/api-clients/absence.ts
- frontend/src/e2e-test/pages/citizen/citizen-new-absence-application.ts
- frontend/src/e2e-test/specs/absence-application/absence-application.spec.ts
- frontend/src/lib-components/molecules/date-picker/DateRangePicker.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationControllers.kt
- service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt
Lisätään esiopetuksen poissaolohakemukseen poissaolon aikavälin validointi. Esiopetuksen poissaoloa ei voi hakea, jos poissaolon aikaväli ei osu edes osaksi esiopetuksen sijoituksen sisälle. Poissaolohakemus linkkiä ei myöskään näytetä jos lapsella on jo loppunut esiopetuksen sijoitus.
> Korjataan esiopetuksen poissaolohakemus

- frontend/src/citizen-frontend/decisions/decisions-page/ApplicationDecision.tsx
- frontend/src/e2e-test/pages/citizen/citizen-decisions.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts
Päätöksen kohdalla näytetään sama metadata kuin päätökseen johtaneen hakemuksen kohdalla, koska hakemus ja päätös ovat osa samaa asianhallintaprosessia.
> Näytetään hakemuspäätöksen asianhallinnan metadata kuntalaiselle

- frontend/src/citizen-frontend/applications/editor/contact-info/ChildSubSection.tsx
- frontend/src/citizen-frontend/applications/editor/contact-info/GuardianSubSection.tsx
- frontend/src/citizen-frontend/applications/editor/verification/UnitPreferenceSection.tsx
- frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionSurveyModal.tsx
- frontend/src/lib-common/names.ts
- frontend/src/lib-components/molecules/PersonNames.tsx
- Only require the name fields that are actually needed by the given format
- Remove the `usePersonName` hook. Pass `placeholders` to `formatPersonName` instead.
This also allows to remove some duplication: `formatPersonName` is now the only place that actually renders names + formats to string.
> Refaktoroidaan henkilön nimen formatointia

- apigw/Dockerfile
Aiheutti ECR-hälyn eikä ole enää käytössä. Käytetty aikoinaan HOST_IP:n päättelyssä.
> Tekninen: Poistetaan jq apigw-imagesta

- frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
- frontend/src/lib-components/atoms/Chip.tsx
- frontend/src/lib-components/document-templates/ChildDocumentStateChip.tsx
- frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
Muutetaan hyväksytty/hylätty -status labelit:
_hyväksytty -> myönnetty
hylätty -> ei myönnetty_
Lisätty _nowrap_ statuksen chip-komponentille.
> Päivitetään päätöksen tila -tekstejä

- frontend/yarn.lock
CI ei toimi dependabotin [PR](https://github.com/espoon-voltti/evaka/pull/7424):ssä, joten siksi uusi PR.
> Bump form-data from 4.0.0 to 4.0.4 in /frontend

- apigw/yarn.lock
Will fix https://github.com/espoon-voltti/evaka/security/dependabot/306
> Bump form-data from 4.0.2 to 4.0.4 in /apigw

- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementTermination.kt
Korjattu ongelma, jossa "Huoltaja irtisanonut" -merkintä ei näkynyt, jos huoltaja irtisanoi sijoituksen viimeiselle päivälle ja lapsella alkoi heti seuraavana päivänä uusi sijoitus (ts. seuraavana päivänä alkanut sijoitus on se joka varsinaisesti irtisanottiin). Tyypillinen tällainen tilanne on keväällä esiopetuksen ja sitä seuraavan liittyvän varhaiskasvatuksen saumakohdassa.
> Sijoituksen viimeiseen päivään irtisanominen ei näy huoltajan irtisanomana

- frontend/src/citizen-frontend/messages/MessagesPage.tsx
- frontend/src/citizen-frontend/messages/ThreadList.tsx
- frontend/src/citizen-frontend/messages/ThreadListItem.tsx
Näppäimistönavigoinnilla viestieditoriin tulee näkyviin apunäppäimiä, kuten “Takaisin listaan”. Painettaessa tätä nappia intuitiivinen kohdistuksen kohde olisi listassa se viesti josta nappia painettiin.
> Korjataan kohdistus kun viestiketju suljetaan

- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
Tällä hetkellä kun järjestelmän kautta lataa talouden päätöksen, tulee tiedostonimeksi `download.pdf`. Muutoksen jälkeen tulee vastaava nimi kuin mikä lähetetty suomi.fi-viestit -palveluun.
> Lisätään talouden päätöksien lataamiseen tiedostonimi

- frontend/.dockerignore
Jos eVakaa käytetään git-submodulena jossain muussa kunnassa ja lokaalin kehittämisen helpottamiseksi frontendin kustomoinnit liitetään mukaan symbolisella linkillä, linkki rikkoo joissain tapauksissa docker-buildin.
Poistetaan ylimääräiset tiedostot docker-kontekstista, jotta ne eivät sotke buildia. Nämä muutokset vastaavat osittain `.gitignore`-tiedostoa.
> Korjataan frontend docker-kontin konteksti

- frontend/src/e2e-test/pages/employee/child-information.ts
- frontend/src/e2e-test/specs/5_employee/child-information.spec.ts
- frontend/src/employee-frontend/components/child-information/BackupCare.tsx
- frontend/src/employee-frontend/components/child-information/backup-care/BackupCareForm.tsx
- frontend/src/employee-frontend/generated/api-clients/daycare.ts
- frontend/src/employee-frontend/queries.ts
- frontend/src/lib-common/generated/api-types/daycare.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/backupcare/BackupCareIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareController.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
Tarkistetaan yksikön aukiolo varasijoitusta tehdessä. Yksikön tulee olla auki koko varasijoituksen ajan, jotta sijoituksen voi tehdä.
Yksikölle voi olla määriteltynä avaus- ja sulkeutumispäivämäärä:
- Jos yksiköllä on avaus- ja sulkeutumispäivämäärä, tarkistetaan että varasijoitus on näiden päivämäärien sisällä
- Jos yksiköllä ei ole avauspäivämäärää, tarkistetaan että varasijoitus loppuu ennen sulkeutumispäivämäärää
- Jos yksiköllä ei ole sulkeutumispäivämäärää, tarkistetaan että varasijoitus alkaa avauspäivämäärän jälkeen
- Jos yksiköllä ei ole avaus- ja sulkeutumispäivämäärää, oletetaan että yksikkö on auki riippumatta varasijoituksen ajankohdasta
> Lisätään tarkistus yksikön aukiololle varasijoituksen luomiseen

- frontend/src/employee-frontend/components/reports/ServiceNeeds.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Jatkoa muutokselle https://github.com/espoon-voltti/evaka/pull/7434. Lasten palveluntarpeet ja iät yksiköissä -raportista löytyi vielä yksi muutettava teksti.
> Muutetaan sijoituksen tyypin käyttöliittymäteksti

- frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
> Korjataan kuntalaisen tuloselvitys lomakkeen napit näkymään kokonaan pienillä ruuduilla

- frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx
- frontend/src/citizen-frontend/applications/editor/ApplicationFormClub.tsx
- frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx
- frontend/src/citizen-frontend/applications/editor/ApplicationFormPreschool.tsx
- frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx
- frontend/src/citizen-frontend/applications/editor/service-need/ServiceNeedSection.tsx
- frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-club-application.spec.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-preschool-application.spec.ts
- frontend/src/lib-components/molecules/date-picker/DatePicker.spec.tsx
- frontend/src/lib-components/molecules/date-picker/DatePicker.tsx
- frontend/src/lib-components/molecules/date-picker/DatePickerDay.tsx
- frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
- frontend/src/lib-components/molecules/date-picker/DateRangePicker.spec.tsx
- frontend/src/lib-components/molecules/date-picker/DateRangePicker.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationUpdateIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
Disabloidaan kalenterista aloituspäivän valinnalle lomakaudet tai ylipäätään esiopetuskausien (tai pidennetyn esiopetuskauden) ulkopuoliset päivät esiopetusilmoittautumisen yhteydessä.
> Esiopetukseen ilmoittautuessa kalenterin rajaaminen

- frontend/src/citizen-frontend/navigation/utils.ts
- frontend/src/lib-common/generated/api-types/children.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/children/ChildControllerCitizenTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/children/Children.kt
- service/src/main/kotlin/fi/espoo/evaka/children/ChildrenQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt
Muutetaan huoltajan oikeuksia siten, että heillä on pääsy pedagogisiin dokumentteihin vain jos lapsella on aktiivinen tai tuleva sijoitus. Sijoituksen päätyttyä huoltaja ei pysty lukemaan tai lataamaan pedagogisia dokumentteja tai liitteitä
> Piiloitetaan pedagogiset dokumentit huoltajalta lapsen sijoituksen loputtua

- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
- service/src/test/kotlin/fi/espoo/evaka/reservations/UsedServiceTests.kt
Ylöspäin pyöristäminen aiheutti jämäminuutteja, jotka näkyivät huoltajille sopimusylityksinä poissaolokuukausina. Alaspäin pyöristämällä pienennetään pyöristysvääristymän aiheuttamaa vahinkoa.
> Muutetaan tuntiperusteisten varausten päivittäiskeskiarvolaskenta pyöristämään alaspäin

- service/src/main/resources/db/migration/V547__relax_weak_credentials_check.sql
- service/src/main/resources/migrations.txt
Käyttäjän kevytkirjautumisen voi nyt estää näin:
```
UPDATE citizen_user SET
username = NULL, username_updated_at = current_timestamp,
password = NULL, password_updated_at = current_timestamp
WHERE id = <person_id>;
```
Myöhemmin tälle voidaan kehittää käyttöliittymä.
> Mahdollistetaan käyttäjän kevytkirjautumisen deaktivointi kannan tasolla

- frontend/src/lib-customizations/espoo/featureFlags.tsx
"Arkistoi"- nappi oli näkyvissä vain staging ja dev ympäristöissö
Ominaisuus on käytettävissä myös tuotannossa
> Otetaan yksittäisen asiakirjan arkistointi käyttöön myös tuotannossa

- service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
**Aiemmat viestin sisällöt:**
```
Subject: Esiopetuksen poissaolohakemus hyväksytty
Lapsesi esiopetuksen poissaolohakemus ajalle PP.KK.VVVV - PP.KK.VVVV on
hyväksytty ja poissaolot on merkitty eVakaan. Lue lisää eVakasta.
```
tai
```
Subject: Esiopetuksen poissaolohakemus hylätty
Lapsesi esiopetuksen poissaolohakemus ajalle PP.KK.VVVV - PP.KK.VVVV on
hylätty. Lue lisää eVakasta.
```
**Uusi sisältö:**
```
Subject: Esiopetuksen poissaolohakemus käsitelty
Lapsesi esiopetuksen poissaolohakemus käsitelty. Lue lisää eVakasta.
```
> Poistetaan mahdollisesti arkaluontoiset tiedot eskarin poissaolohakemuksen ilmoitussähköpostista

- frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx
- frontend/src/citizen-frontend/calendar/hooks.ts
- frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
- frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
1. Kun painetaan “poista” (toisen aikavälin poisto), ruudunlukijalle ei lausuta poiston onnistumisesta mitään. Ruudunlukijalle voisi välittää esim. “Toinen aikaväli poistettu”.
2. Sanoo nyt “alkaa-muokkaa”  ja “päättyy-muokkaa”. Voisi olla parempi että sanoisi “ ilmoita aloitusaika-muokkaa” ja “ ilmoitus loppumisaika - muokkaa ”.
> Ilmoita läsnäolo -modaalin saavutettavuusparannuksia

- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/AsyncJobConfig.kt
- service/src/main/resources/db/scripts/archive_closed_child_documents.sql
- service/src/main/resources/db/scripts/archive_closed_child_documents_simple.sql
Asiakirjojen vienti ulkoiseen arkistoon tapahtui "main"-async job poolissa, ja ainoa työkalu asiakirjan viemiseen arkistoon oli yksittäisen asiakirjan sivulla oleva "Arkistoi"-nappi.
Koska suurten asiakirjamäärien vienti arkistoon kestää tunnin tai pidempään, ajetaan ne erillisessä "bulk"-poolissa. Näin normaalit async jobit, kuten "VTJ-synkronointi", ajautuvat edelleen ilman odottelua.
Lisätty myös SQL-skriptit, joilla käynnistetään suljettujen asiakirjojen vienti.
> Asiakirjojen arkistoon vienti erillisessä async job bulk-poolissa

- frontend/src/employee-frontend/components/child-information/AssistanceNeedDecisionSection.tsx
- frontend/src/employee-frontend/components/child-information/AssistanceNeedPreschoolDecisionSection.tsx
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Ennen tämän muutoksen käyttöönottoa kannattaa olla luotuna `Muu päätös` tyyppiset asiakirjapohjat, joilla tuen päätökset jatkossa tehdään. 
Jo avatut vanhan malliset tuen päätökset käsitellään loppuun ja migratoidaan lähiaikoina uuteen formaattiin: https://github.com/espoon-voltti/evaka/pull/7355
> Estetään vanhan mallisten tuen päätösten avaaminen

- frontend/src/e2e-test/specs/5_employee/month-calendar.spec.ts
- service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
Ei näytetä puuttuvien poissaolokyselyn vastauksien huomautusia yksikön kuukausikalenterissa, jos lapsen sijoitus on alkanut kyselyn vastaamisajan päättymisen jälkeen.
> Korjataan puuttuvien poissaolokyselyn vastauksien huomautuset

- frontend/src/citizen-frontend/App.tsx
- frontend/src/e2e-test/specs/0_citizen/citizen-discussion-surveys.spec.ts
- frontend/src/lib-components/Notifications.tsx
Muutos pyrkii sijoittamaan ilmoitukset kuntalaisen käyttöliittymissä niin, että ne eivät peitä tärkeitä navigaatiopainikkeita ja jäävät modaaliverhon taakse.
> Parannetaan ilmoitusten sijoittamista kuntalaisen käyttöliittymissä

- frontend/src/citizen-frontend/AccessibilityStatement.tsx
- frontend/src/citizen-frontend/router.tsx
- frontend/src/e2e-test/specs/0_citizen/citizen-links.spec.ts
Saavutettavuusselosteen router-määrityksestä jäänyt puuttumaan `auth: null`, jotta näkyisi ilman kirjautumistakin
> Korjataan kuntalaisen saavutettavuusselosteen näkyvyys

- frontend/src/e2e-test/pages/employee/placement-draft-page.ts
- frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts
- frontend/src/e2e-test/specs/5_employee/child-information-placements.spec.ts
- frontend/src/employee-frontend/components/child-information/placements/CreatePlacementModal.tsx
- frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
- frontend/src/employee-frontend/components/placement-draft/PlacementDraft.tsx
- frontend/src/employee-frontend/components/placement-draft/PlacementDraftRow.tsx
- frontend/src/employee-frontend/components/unit/queries.ts
- frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Tarkistaa että muokattavan tai luotavan esikoulusijoituksen päivämäärät osuvat jollekin esiopetus- tai liittyvälle kaudelle
- Lapsen profiilisivun sijoitusnäkymän sijoituksen muokkausnäkymässä muokatessa tai uutta sijoitusta luotaessa
- Hakemusta sijoitettaessa
> Validoi luotavan tai muokattavan esiopetussijoituksen päivämäärät

- frontend/src/employee-frontend/components/reports/NekkuOrders.tsx
Näytetään Nekku-tilausraportin filttereissä vain ne yksiköt ja ryhmät, jotka ovat auki valitulla ajanjaksolla
> Rajataan Nekku-tilausraportin filtterit auki oleviin yksiköihin ja ryhmiin

- frontend/src/e2e-test/specs/5_employee/units.spec.ts
- frontend/src/employee-frontend/components/Units.tsx
Jos käyttäjällä on käyttöoikeus vain yhteen voimassaolevaan yksikköön ja yhteen tai useampaan suljettuun yksikköön, ei tehdä uudelleenohjausta voimassaolevaan yksikköön jotta pääsee navigoimaan myös suljettuihin yksiköihin.
> Korjataan yksiköt-sivun uudelleenohjaus ainokaiseen yksikköön

- service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
Päätöksentekijä listauksessa oli kaikki työntekijät, joilla oli rooli `UNIT_SUPERVISOR` tai `SPECIAL_EDUCATION_TEACHER` missä tahansa yksikössä, riippumatta yksikön palveluntuottajatyypistä.
Tämä mahdollisti myös yksityisten palveluseteliyksiköiden työntekijöiden valitsemisen päätöksentekijäksi.
Päätöksentekijäksi kelpuutetaan vain ne työntekijät, joilla on vaadittu rooli yksikössä, jonka `provider_type` ei ole `PRIVATE_SERVICE_VOUCHER`.
Yksityisten palveluseteliyksiköiden työntekijät eivät enää näy päätöksentekijäehdokkaina lapsiasiakirjoissa.
Muutos vaikuttaa sekä päätöksentekijäehdokkaiden listaukseen että päätöksentekijän validointiin päätösehdotuksen yhteydessä.
> Estetään palveluseteliyksikön työntekijän valitseminen päätöksentekijäksi

- frontend/src/e2e-test/specs/5_employee/assistance-need-and-actions-report.spec.ts
- frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
Ladattavalla raportilla näytetään tyhjänä soluna. Yhteensä-rivillä näytetään lasten määrä joilla on korotettu kerroin eikä kertoimien summaa.
> Näytetään oletuspalvelusetelikertoimet viivana lapsikohtaisella tukitoimiraportilla

- service/src/main/kotlin/fi/espoo/evaka/espoo/archival/DocumentMetadataUtils.kt
- service/src/test/kotlin/fi/espoo/evaka/document/archival/DocumentMetadataUtilsTest.kt
- Arkistoon siirrettävässä metadatassa käytettiin asian avaamispäivässä suoraan `documentMetadata.createdAt`, vaikka todellinen päivämäärä tulisi ensisijaisesti etsiä process historyn kautta
- Luotu keskitetty `getCreationDate()`, joka toteuttaa logiikan luontipäivämäärän hakemiseksi
- `getCaseFinishDate` ja `createCaseFile` funktiot käyttävät nyt molemmat tätä
- Kaikki funktiot käyttävät nyt johdonmukaisesti samaa logiikkaa: ensisijaisesti prosessihistorian INITIAL merkintää, fallbackinä `documentMetadata.createdAt`
> Arkistometadata: Keskitetty, process history pohjainen luontipäivämäärän poimintalogiikka

- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReport.kt
Lasketaan valmistavan esiopetuksen läsnäolojen poikkeama käyttäen valmistavan opetusaikaa. Aiemmin poikkeama laskettiin virheellisesti käyttäen esiopetuksen opetusaikaa.
> Korjataan esiopetuksen poissaoloraportin laskenta

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Lisää ajastetun ajon siivouskyselyille, jotka poistavat sellaiset vuorohoitoyksiköiden tulevaisuuden varaukset, jotka eivät enää perustu vuorohoitopalveluntarpeeseen. Tällaisia varauksia voi jäädä järjestelmään, jos vuorohoidon palveluntarve katkaistaan, korvataan vuorohoidottomalla palveluntarpeella tai  palveluntarpeen vuorohoitomerkintä poistetaan takautuvasti.
Poistettavat varaukset:
- arkipyhille osuvat varaukset
- yksikön normaaliaukiolopäivien ulkopuoliset varaukset
- pelkästään normaaliaukiolotunnit ylittävää varausta EI poisteta
> Lisätään yöllinen ajo poistuneen vuorohoidon tarpeen jälkeiseen varausten siivoamiseen tulevaisuudesta
