espoon-voltti/evaka

frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Application text changes for 2024

---

frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx

https://github.com/espoon-voltti/evaka/pull/4425 part2. I didn't notice there were also some other logic to hide data already returned by backend.

Show groups from all placements

---

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
service/src/main/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyService.kt

The "update from VTJ" button in the frontend can now update children in addition to guardians.

Support updating children from VTJ

---

frontend/src/employee-frontend/components/reports/ChildAgeLanguage.tsx

Fix child language report total row

---

service/gradle/libs.versions.toml
service/owasp-suppressions.xml

Revert owasp bump because of problems with 9 version

---

service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt

Fix planned absence counter

---

service/src/main/kotlin/fi/espoo/evaka/varda/old/VardaResetService.kt

Properly clean all child's varda service need data on reset

---

frontend/package.json
frontend/yarn.lock

Upgrade to @types/react 18.2.41

---

service/evaka-bom/build.gradle.kts

Fixes CVE-2023-46589 & CVE-2023-6481

Owasp fixes

---

compose/docker-compose.yml
keycloak/Dockerfile
keycloak/evaka-logging/pom.xml
keycloak/evaka-review-profile/pom.xml

Bump keycloak from 22.0.4 to 23.0.1

---

service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt
service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt

Change working day to 7 hours 39 minutes

---

.github/workflows/build.yml

Dependency check cache fix

---

.github/workflows/build.yml

 Use latest dependency-check cache

---

service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizen.kt

Cancel all active transfer applications on placement termination

---

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageReceiversIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageAccountQueries.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt

Don't return closed units as municipal message receivers

---

frontend/src/employee-frontend/components/application-page/ApplicationNoteBox.tsx

Application note component got stuck in submitting state after used saved edit to a note.
Application note submit state is correctly cleared after save is done.

Disable submitting state after save is done

---

frontend/src/lib-customizations/espoo/citizen.tsx

Espoo application text change

---

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PartnershipsControllerIntegrationTest.kt

There was no test coverage for `PUT /partnerships/{partnershipId}/retry`
There is an integration test for it.

Add integration test for PUT /partnerships/{partnershipId}/retry

---

frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx

Reverts employee mobile attendance page age icon broken positioning changes.

Revert broken age icon positioning

---

frontend/src/e2e-test/pages/employee/units/unit.ts
frontend/src/employee-frontend/components/unit/unit-details/CreateUnitPage.tsx
frontend/src/employee-frontend/components/unit/unit-details/UnitDetailsPage.tsx

Don't submit unit editor on enter key

---

frontend/src/employee-frontend/App.tsx
frontend/src/employee-frontend/components/EmployeeRoute.tsx
frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
frontend/src/employee-frontend/components/vasu/sections/VasuHeader.tsx
frontend/src/employee-frontend/state/title.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Page title is default file name while printing to PDF.

Update child document and assistance decision page titles

---

frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
frontend/src/lib-components/assistance-need-decision/AssistanceNeedPreschoolDecisionReadOnly.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/resources/WEB-INF/templates/assistance-need-preschool/decision.html
service/src/main/resources/WEB-INF/templates/assistance-need-preschool/decision.properties
service/src/main/resources/WEB-INF/templates/assistance-need-preschool/decision_sv.properties

Add preschool assistance decision legal instructions text

---

frontend/src/lib-customizations/espoo/featureFlags.tsx

Enable new employee-mobile features in Espoo prod

---

frontend/src/lib-customizations/espoo/featureFlags.tsx

Disable confirmed day reservations in employee-mobile

---

keycloak/Dockerfile
keycloak/evaka-logging/pom.xml
keycloak/evaka-review-profile/pom.xml

Bump keycloak from 23.0.1 to 23.0.3

---

frontend/src/e2e-test/specs/6_mobile/confirmed-day-reservations.spec.ts
frontend/src/employee-mobile-frontend/child-attendance/ChildSubListItem.tsx
frontend/src/lib-common/generated/api-types/reservations.ts
frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt

Adds support for holiday periods and related null time reservations for confirmed days view.

Confirmed days support for holiday periods

---

frontend/src/lib-customizations/espoo/featureFlags.tsx

Enable confirmed day reservations in Espoo prod

---

apigw/src/shared/config.ts
apigw/src/tracer.ts

Add support for datadog profiling in apigw

---

frontend/src/lib-customizations/defaults/employee/i18n/sv.tsx

Add preschool assistance decision legal instructions text (sv)

---

compose/db.sh
compose/db/Dockerfile
compose/db/entry/init_evaka.sh

Bump Postgres to v15 in compose

---

apigw/Dockerfile

Run apigw as non-privileged user in container

---

frontend/src/employee-frontend/components/reports/Occupancies.tsx
frontend/src/lib-common/generated/api-types/occupancy.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt
service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt

Adds under & over 3y fields to occupancy report.

Occupancy report under over 3y

---

service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt

Fix confirmed days stats child count

---

frontend/src/lib-components/messages/MessageEditor.tsx

Fix expanding info layout

---

frontend/src/citizen-frontend/applications/editor/unit-preference/PreferredUnitBox.tsx
frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx
frontend/src/e2e-test/pages/citizen/citizen-applications.ts
frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts

Do not remove preferred units from application

---

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageReceiversIntegrationTest.kt

This test made assumptions about the order of area receivers *and* daycare receivers inside them.
Let's do the same assertions in a different way without relying on list ordering

Fix flaky integration test

---

compose/db/Dockerfile

Use Postgres 16 in compose

---

service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyServiceIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MockVtjClientService.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/PersonServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/vtjclient/service/persondetails/MockPersonDetailsService.kt

VTJ access tests

---

.github/dependabot.yml

Group testing-library deps in dependabot

---

frontend/src/employee-frontend/components/absences/MonthCalendarTable.tsx

add service needs to child tooltip on employee frontend group calendar monthly view

add service needs to child tooltip on monthly group calendar

---

service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUnitIntegrationTest.kt
service/src/main/resources/db/migration/R__triggers.sql

Disallow overriding the updated timestamp

---

.github/dependabot.yml

Watch frontend/Dockerfile with dependabot

---

frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
frontend/src/employee-frontend/components/unit/unit-reservations/ReservationModalSingleChild.tsx

fix bug with irregular reservations spanning non-operational days

---

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

Change assistance needs and actions report permissions

---

frontend/src/citizen-frontend/applications/editor/ApplicationFormPreschool.tsx
frontend/src/lib-common/api-types/application/ApplicationFormData.ts

Minimal changes to remove preschool club options from new preschool applications.

Remove preschool club from application

---

service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt

Fix warnings about unused code

---

frontend/src/employee-frontend/components/unit/TabCalendar.tsx
frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventController.kt

month calendar shows events for whole month

---

keycloak/Dockerfile
keycloak/evaka-logging/pom.xml
keycloak/evaka-review-profile/pom.xml

Upgrade to Keycloak 23.0.4

---

service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/shared/auth/AclQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt

Tidy up AssistanceActionIntegrationTest

---

service/src/main/kotlin/fi/espoo/evaka/messaging/MessagePushNotifications.kt
service/src/main/kotlin/fi/espoo/evaka/webpush/WebPush.kt

Log less when web push fails due to expiration

---

service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementTermination.kt

fix bug with group placement dates when terminating placements

---

frontend/src/lib-common/generated/api-types/attendance.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
service/src/main/resources/db/migration/V376__departed_automatically.sql
service/src/main/resources/migrations.txt

Mark round the clock as departed after 12 hours

---

frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts
frontend/src/e2e-test/specs/5_employee/reservation-calendar-child-date-modal.spec.ts
frontend/src/employee-frontend/api/unit.ts
frontend/src/employee-frontend/components/unit/queries.ts
frontend/src/employee-frontend/components/unit/unit-reservations/ChildDateModal.tsx
frontend/src/lib-common/generated/api-types/reservations.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/Audit.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/AbsenceCalculator.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
service/src/main/kotlin/fi/espoo/evaka/shared/domain/HelsinkiDateTime.kt
service/src/test/kotlin/fi/espoo/evaka/reservations/AbsenceCalculatorTests.kt

Logic documented here https://github.com/espoon-voltti/evaka/wiki/L%C3%A4sn%C3%A4%E2%80%90-ja-poissaolot#poissaolojen-syntyminen-p%C3%A4iv%C3%A4n-l%C3%A4sn%C3%A4oloajasta

Absence calculation

---

.github/workflows/analyze.yml
.github/workflows/build.yml
.github/workflows/e2e.yml

Update Github Actions

---

service/vtjclient/src/main/resources/wsdl/VTJHenkilotiedotKatalogi.xsd

Update to latest VTJ henkilotiedot wsdl

---

apigw/src/enduser/routes/auth-status.ts
apigw/src/internal/routes/auth-status.ts
apigw/src/shared/auth/index.ts
apigw/src/shared/express.ts
frontend/src/citizen-frontend/auth/api.ts
frontend/src/lib-common/api-types/employee-auth.ts

CSRF overhaul part 1: generate session-scoped anti-CSRF tokens

---

frontend/src/employee-mobile-frontend/staff-attendance/StaffMarkArrivedPage.tsx

enable staff mark arrived with mobile on all groups of unit

---

frontend/src/lib-components/molecules/MessageBoxes.tsx

minor design update for MessageBox

---

service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileUnitControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/AbsenceControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancyTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

Enhance `DevEmployee` creation

---

frontend/proxy/files/etc/nginx/proxy_params.template

HOTFIX: Re-enable passing Authorization header to apigw

---

apigw/README.md
apigw/package.json
apigw/src/enduser/__tests__/csrf.ts
apigw/src/enduser/app.ts
apigw/src/enduser/routes/auth-status.ts
apigw/src/internal/__tests__/csrf.ts
apigw/src/internal/app.ts
apigw/src/internal/routes/auth-status.ts
apigw/src/shared/middleware/csrf.ts
apigw/src/shared/middleware/error-handler.ts
apigw/src/shared/test/gateway-tester.ts
apigw/yarn.lock
frontend/src/citizen-frontend/api-client.ts
frontend/src/citizen-frontend/auth/api.ts
frontend/src/citizen-frontend/auth/state.tsx
frontend/src/employee-frontend/App.tsx
frontend/src/employee-frontend/api/client.ts
frontend/src/employee-frontend/state/user.tsx
frontend/src/employee-mobile-frontend/auth/api.ts
frontend/src/employee-mobile-frontend/auth/state.tsx
frontend/src/employee-mobile-frontend/client.ts

CSRF overhaul part 2: redesign CSRF protection mechanism

---

frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/dev-api/types.ts
frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts
frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
frontend/src/lib-common/generated/api-types/attendance.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaQueries.kt
service/src/test/kotlin/fi/espoo/evaka/titania/TitaniaHelpersTest.kt

Show (*) and a tooltip on automatically closed staff attendances

---

service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SanityChecksTest.kt
service/src/main/kotlin/fi/espoo/evaka/shared/db/SanityChecks.kt
service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt

add first sanity checks

---

frontend/src/employee-frontend/components/employees/DaycareRolesModal.tsx
frontend/src/employee-frontend/components/employees/EmployeePage.tsx
frontend/src/lib-components/atoms/dropdowns/TreeDropdown.tsx

fix daycare links and ordering in admin's employee acl view

---

frontend/src/citizen-frontend/calendar/api.ts
frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts
frontend/src/employee-frontend/api/invoicing.ts
frontend/src/employee-frontend/components/absences/UnitCalendarDayCellTooltip.tsx
frontend/src/employee-mobile-frontend/child-attendance/api.ts
frontend/src/lib-common/generated/api-types/absence.ts
frontend/src/lib-common/generated/api-types/reservations.ts
frontend/src/lib-common/utils/absences-date-range.spec.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/ServiceNeedTestFixtures.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
service/src/test/kotlin/fi/espoo/evaka/reservations/UsedServiceTests.kt

Used service calculation for citizen calendar

---

service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt

Always shows the data correctly for citizens and fixes a few flaky tests.

Sort reservations and attendances in citizen calendar

---

service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt

Use correct service need hours in month summary

---

service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationQueriesSmokeTest.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
service/src/main/kotlin/fi/espoo/evaka/shared/db/Predicate.kt
service/src/main/kotlin/fi/espoo/evaka/shared/db/Search.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/ActionRule.kt
service/src/test/kotlin/fi/espoo/evaka/shared/db/PredicateTest.kt

Application search permissions

---

frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/VasuPage.tsx
frontend/src/lib-components/layout/StickyFooter.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

improve mobile ui on citizen vasu permission question

---

service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt

Consider all assistance data in raw report has_assistance_need

---

service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt

HOTFIX: Only include children with placements in citizen calendar

---

service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaControllerTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaServiceTest.kt
service/src/main/kotlin/fi/espoo/evaka/titania/Titania.kt
service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaController.kt
service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaService.kt

The Titania integration was not logging new employee creation properly, so fix that

Log new employee creation in the Titania integration

---

apigw/src/shared/logging.ts

This fixes "Unknown error" in logs in some scenarios

Get error name from the name field if possible

---

service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
service/src/main/resources/db/migration/V384__read_at_partial_index.sql
service/src/main/resources/migrations.txt

Optimize unread count query

---

frontend/src/e2e-test/specs/5_employee/child-information-assistance.spec.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Add mention about koski to other assistance measure text

---

service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/MockDvvModificationsService.kt
service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceClient.kt

Remove DVV product code from API requests

---

frontend/src/citizen-frontend/map/UnitDetailsPanel.tsx
frontend/src/lib-customizations/types.d.ts

Route planner is not available for treVaka Hämeenkyrö

Add the ability to hide route planner link

---

frontend/src/lib-common/generated/api-types/invoicing.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/NewCustomerIncomeNotificationIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/NewCustomerIncomeNotification.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotifications.kt
service/src/main/kotlin/fi/espoo/evaka/pis/PersonalData.kt
service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
service/src/main/resources/db/migration/V385__new_customer_income_notification_type.sql
service/src/main/resources/migrations.txt

feat: income notifications for new customer

---

frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/dev-api/index.ts
frontend/src/e2e-test/specs/0_citizen/citizen-finance-decisions.spec.ts

Fix some imports in e2e-test

---

frontend/src/citizen-frontend/calendar/ReservationModal.tsx
frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts
frontend/src/citizen-frontend/calendar/reservation-modal/form.ts

Citizen reservation modal validation fixes

---

service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
service/src/main/kotlin/fi/espoo/evaka/application/persistence/daycare/DaycareFormV0.kt
service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBi.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

Club form fixes

---

apigw/entrypoint.sh
apigw/src/index.ts
apigw/src/shared/auth/index.ts
apigw/src/shared/auth/jwt.ts
apigw/src/shared/config.ts
apigw/src/shared/logging.ts

Remove support for GATEWAY_ROLE / gatewayRole in apigw

---

frontend/src/employee-frontend/components/unit/unit-reservations/ChildDateModal.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt

display backend validation error in child date modal

---

apigw/src/shared/auth/dev-auth.ts
apigw/src/shared/routes/saml.ts
frontend/src/lib-components/i18n.tsx
frontend/src/lib-components/molecules/modals/LoginErrorModal.tsx
frontend/src/lib-components/utils/TestContextProvider.tsx
frontend/src/lib-customizations/defaults/components/i18n/en.tsx
frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt

better error message on inactive user login

---

frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
frontend/src/employee-frontend/components/unit/unit-reservations/ChildDayCommons.tsx
frontend/src/employee-frontend/components/unit/unit-reservations/ChildDayReservation.tsx
frontend/src/employee-frontend/components/unit/unit-reservations/ChildReservationsTable.tsx
frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
frontend/src/employee-frontend/components/unit/unit-reservations/attendance-elements.tsx

Tested on chromium, chrome, firefox and safari

Make unit week view tables responsive

---

apigw/src/shared/routes/saml.ts

fix deactivated user error

---

service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
service/src/main/resources/application.yaml

Move fiveYearsOldDaycareEnabled to FeatureConfig

---

frontend/src/e2e-test/generated/api-types.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/FamilyControllerTest.kt
service/src/main/kotlin/fi/espoo/evaka/pis/controllers/FamilyController.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt

Ignore conflicts in family contacts query

---

service/owasp-suppressions.xml

Suppress CVE

---

frontend/src/citizen-frontend/calendar/DayView.tsx
frontend/src/citizen-frontend/calendar/ReservationModal.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Show extra info for shift care children

---

frontend/src/citizen-frontend/generated/api-clients/daycare.ts
frontend/src/employee-frontend/generated/api-clients/daycare.ts
frontend/src/employee-frontend/generated/api-clients/invoicing.ts
frontend/src/employee-frontend/generated/api-clients/occupancy.ts
frontend/src/employee-frontend/generated/api-clients/pis.ts
frontend/src/employee-frontend/generated/api-clients/placement.ts
frontend/src/employee-frontend/generated/api-clients/reports.ts
frontend/src/employee-mobile-frontend/generated/api-clients/daycare.ts
frontend/src/employee-mobile-frontend/generated/api-clients/invoicing.ts
frontend/src/employee-mobile-frontend/generated/api-clients/occupancy.ts
frontend/src/employee-mobile-frontend/generated/api-clients/pis.ts
frontend/src/employee-mobile-frontend/generated/api-clients/placement.ts
frontend/src/employee-mobile-frontend/generated/api-clients/reports.ts
service/codegen/src/main/kotlin/evaka/codegen/api/ApiFiles.kt
service/codegen/src/main/kotlin/evaka/codegen/api/TsCodeGenerator.kt
service/codegen/src/main/kotlin/evaka/codegen/api/TsRepresentation.kt
service/codegen/src/main/kotlin/evaka/codegen/api/TypeMetadata.kt

Better query path parameters codegen

---

service/gradle/libs.versions.toml

Fixes a Spring CVE that doesn't apply to us but it's easier to just upgrade

Upgrade Spring Boot to fix CVE

---

frontend/src/employee-frontend/components/unit/unit-reservations/ChildDateModal.tsx
frontend/src/lib-common/form/fields.ts

validate against 00:00 end time in week calendar modal

---

service/src/integrationTest/kotlin/fi/espoo/evaka/espoo/bi/EspooBiTest.kt
service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBi.kt
service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBiModels.kt
service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBiTable.kt

Add more fields/tables to Espoo BI

---

frontend/src/e2e-test/pages/employee/finance/finance-page.ts
frontend/src/e2e-test/specs/4_finance/payments.spec.ts
frontend/src/employee-frontend/api/invoicing.ts
frontend/src/employee-frontend/components/payments/Actions.tsx
frontend/src/employee-frontend/components/payments/PaymentsPage.tsx
frontend/src/employee-frontend/components/payments/payments-state.ts
frontend/src/employee-frontend/generated/api-clients/invoicing.ts
frontend/src/employee-mobile-frontend/generated/api-clients/invoicing.ts
frontend/src/lib-common/generated/action.d.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/PaymentsIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/Audit.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/PaymentController.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/data/PaymentQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

Make it possible to delete individual draft payments in the payment UI

Make it possible to delete draft payments

---

service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt

hide sibling basis details from other guardian

---

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Fix to correct quotes so the string interpolation will work

Fix quotes in the frontend i18n file

---

frontend/src/employee-frontend/components/child-information/Placements.tsx
frontend/src/lib-common/generated/api-types/shared.ts
service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/EmployeeFeatures.kt

Use `EmployeeFeatures` for placement creation permission check

---

service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileUnitControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
service/src/main/kotlin/fi/espoo/evaka/shared/domain/TimeInterval.kt
service/src/main/kotlin/fi/espoo/evaka/shared/domain/TimeRange.kt
service/src/main/kotlin/fi/espoo/evaka/shared/domain/TimeRangeEndpoint.kt
service/src/test/kotlin/fi/espoo/evaka/shared/domain/TimeIntervalTest.kt

Add support for mignight endtime for `TimeInterval`, add `overlaps()`, and use it for child attendance stuff.

Use range operations for child attendances

---

apigw/src/internal/ad-saml.ts

Add employee number to lower case transformation

---

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt

Staff auto-departure always 12h after arrival and not at 20:00 (unless it's deduced from plan times)

Staff auto-departure fixes

---

frontend/src/lib-components/molecules/FileUpload.tsx
frontend/src/lib-customizations/defaults/components/i18n/en.tsx
frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
service/src/main/resources/application.yaml

Support file uploads up to 25 MB

---

frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceExternalPersonModal.tsx
frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
frontend/src/lib-common/form-validation.ts
frontend/src/lib-components/i18n.tsx
frontend/src/lib-components/utils/TestContextProvider.tsx
frontend/src/lib-customizations/defaults/components/i18n/en.tsx
frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt

No staff attendances in future

---

service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt

Fix citizen calendar service need SQL query

---

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FinanceDecisions.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/FeeDecisionGeneratorV2.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/SharedLogic.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/VoucherValueDecisionGeneratorV2.kt

preserve finance decision id when unchanged

---

frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/dev-api/index.ts
frontend/src/e2e-test/generated/api-clients.ts
frontend/src/e2e-test/generated/api-types.ts
frontend/src/e2e-test/pages/employee/reports.ts
frontend/src/e2e-test/specs/5_employee/assistance-need-and-actions-report.spec.ts
frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
frontend/src/lib-common/generated/api-types/reports.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportControllerTest.kt
service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportController.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

- Fix report unit view table layout (missing age TD)
- Add E2E tests for area and child rows
- Show hightened voucher coefficient counts and values on report
- Fix report viewer role permissions

Assistance need and actions report fixes

---

frontend/src/employee-frontend/components/absences/GroupMonthCalendar.tsx
frontend/src/employee-frontend/components/absences/MonthCalendarCell.tsx
frontend/src/employee-frontend/components/absences/MonthCalendarTable.tsx
frontend/src/employee-frontend/generated/api-clients/absence.ts
frontend/src/employee-mobile-frontend/generated/api-clients/absence.ts
frontend/src/lib-common/generated/api-types/absence.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceController.kt
service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
service/src/main/kotlin/fi/espoo/evaka/reports/ExceededServiceNeedsReport.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
service/src/test/kotlin/fi/espoo/evaka/reservations/UsedServiceTests.kt

Fix used service calculation for intermittent shift care children

---

service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt

Automatically set end date for daycare assistance decisions from placements.

Add scheduled job EndActiveDaycareAssistanceDecisions

---

frontend/src/lib-common/useRouteParams.ts

Simplify useRouteParam's return type

---

frontend/src/employee-frontend/components/document-templates/queries.ts
frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
frontend/src/employee-frontend/generated/api-clients/document.ts
frontend/src/employee-mobile-frontend/generated/api-clients/document.ts
frontend/src/lib-common/generated/api-types/document.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/document/DocumentTemplateIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/Audit.kt
service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateController.kt
service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateQueries.kt

editable document template basics

---

frontend/src/employee-frontend/components/reports/Occupancies.tsx

fix header row on occupancy report

---

frontend/src/e2e-test/pages/mobile/staff-page.ts
frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceExternalPersonModal.tsx
frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
frontend/src/employee-frontend/generated/api-clients/attendance.ts
frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendanceEditPage.tsx
frontend/src/employee-mobile-frontend/staff-attendance/StaffMarkArrivedPage.tsx
frontend/src/lib-common/generated/api-types/attendance.ts
frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

Staff occupancy effect on arrival

---

frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReportPreschoolDecision.tsx

Fix marking assistance need preschool decision as opened

---

.github/dependabot.yml

Fix github-actions path in dependabot config

---

service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt

HTML-escape event title in calendar notification

---

frontend/src/employee-mobile-frontend/messages/api.ts

Attachment download in employee mobile didn't work
It works

Fix mobile attachment urls

---

frontend/src/employee-frontend/components/Units.tsx
frontend/src/employee-frontend/components/child-information/placements/CreatePlacementModal.tsx
frontend/src/employee-frontend/components/employees/EmployeePage.tsx
frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx
frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx
frontend/src/employee-frontend/components/reports/PlacementGuarantee.tsx
frontend/src/employee-frontend/components/unit/queries.ts
frontend/src/employee-frontend/generated/api-clients/daycare.ts
frontend/src/employee-mobile-frontend/generated/api-clients/daycare.ts
service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt

no closed units in admin mass acl selection

---

service/gradle/libs.versions.toml

Upgrade to Spring Boot 3.2.4

---

frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts
frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
frontend/src/lib-common/generated/api-types/assistanceneed.ts
frontend/src/lib-components/assistance-need-decision/AssistanceNeedPreschoolDecisionReadOnly.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/espoo/bi/EspooBiTest.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecision.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionController.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
service/src/main/resources/db/migration/V388__preschool_assistance_decision_valid_to.sql
service/src/main/resources/migrations.txt

https://github.com/espoon-voltti/evaka/pull/4854 for preschool.

Add scheduled job EndActivePreschoolAssistanceDecisions

---

frontend/src/lib-components/atoms/buttons/SkipToContent.tsx
frontend/src/lib-components/molecules/ScreenReaderButton.tsx

-1000px can be visible on large screens and we already use -10000px in some other places

Move screen reader -specific stuff from left to leeeeeft

---

keycloak/Dockerfile
keycloak/evaka-logging/pom.xml
keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/EvakaLoggingEventListenerProvider.java
keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/EvakaLoggingEventListenerProviderFactory.java
keycloak/evaka-review-profile/pom.xml
keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java
keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff
keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java.diff
keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/diffs.sh

Upgrade to Keycloak 24.0.1

---

service/src/main/resources/db/migration/V389__resync_personal_accounts_with_acl.sql
service/src/main/resources/migrations.txt

data fix after https://github.com/espoon-voltti/evaka/pull/4880 is in prod

re-sync personal messaging accounts with daycare ACL

---

service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt

vasu migration fix: swap checkbox labels

---

service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/SoapStackIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionController.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionService.kt
service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
service/src/main/kotlin/fi/espoo/evaka/pdfgen/PdfGenerator.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/MockSfiMessagesClient.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiAsyncJobs.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesClient.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/resources/WEB-INF/templates/shared/layout.html

This reverts previous revert commit 697814ce6b9a3a8475167bd41fb87193576d1557. Also removes any remaining sendAdress passing to PDFs.

improve assistance decision sending logic

---

frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/VasuPage.tsx

vasu permission dialog expansion fix

---

keycloak/theme/evaka/login/idp-review-user-profile.ftl
service/evaka-bom/build.gradle.kts

Add missing theme template

---

frontend/src/lib-common/generated/api-types/sensitive.ts
service/src/main/kotlin/fi/espoo/evaka/sensitive/ChildSensitiveInformation.kt
service/src/main/kotlin/fi/espoo/evaka/sensitive/GetChildSensitiveInfoQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/config/JacksonConfig.kt
service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt

Clean up some legacy code

---

frontend/src/employee-frontend/components/finance-basics/FinanceBasicsPage.tsx
frontend/src/employee-frontend/components/finance-basics/PlacementTypeItem.tsx
frontend/src/employee-frontend/components/finance-basics/ServiceNeedItem.tsx
frontend/src/employee-frontend/components/finance-basics/ServiceNeedsSection.tsx
frontend/src/employee-frontend/components/finance-basics/queries.ts
frontend/src/employee-frontend/query.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Service need options are expandable but empty, voucher value listings coming there next

List placement types and service need options under finance basics

---

frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx

Tampere region is not using `DAYCARE_PART_TIME`

Hide part time daycare radio from application if not supported

---

frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
frontend/src/lib-common/generated/api-types/placement.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt

hide technical placement update time

---

frontend/src/citizen-frontend/applications/ChildApplicationsBlock.tsx
frontend/src/e2e-test/pages/citizen/citizen-applications.ts
frontend/src/e2e-test/specs/0_citizen/citizen-applications-list.spec.ts
frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

hide preferred unit from citizen applications list

---

frontend/src/employee-mobile-frontend/child-info/ArrivalAndDeparture.tsx

Fixes E2E test flakiness and weird UX

Don't use mutable reverse

---

service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt

Use correct function name

---

frontend/package.json
frontend/yarn.lock

Bump downshift from 8.5.0 to 9.0.4 in /frontend

---

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt

Voucher value report fix

---

service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/DocumentMigratorTest.kt
service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt

Bugikorjaus vasumigraatioon

---

keycloak/Dockerfile
keycloak/evaka-logging/pom.xml
keycloak/evaka-review-profile/pom.xml

Keycloakin päivitys versioon 24.0.2

---

service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt

Näytetään yksikön kalenterissa puuttuva lomavarausindikaatio vain jos yksiköllä on varaukset päällä

---

service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt

Kun tuleva sijoitus poistetaan poistetaan ainoastaan siihen osuvat varaukset

---

service/evaka-bom/build.gradle.kts

Spring-päivitys versioon 6.1.6

---

frontend/src/employee-frontend/components/child-documents/statuses.ts
frontend/src/lib-common/generated/api-types/document.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt

Uudet dokumenttityypit: Vasu ja leops

---

service/src/main/resources/db/migration/V396__vasu_leops_types.sql
service/src/main/resources/migrations.txt

Lisää tietokantamigraation joka jäi puuttumaan PR:stä https://github.com/espoon-voltti/evaka/pull/5003

Lisätty vasu- ja leops- `document_type`:t

---

service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt

Lisätty lapsen ID päätöksen hyväksymis/hylkäämis lokiviestiin

---

service/src/main/resources/db/migration/V398__application_other_guardian.sql

Korjaus tietokantamigraatioon V398

---

service/build.gradle.kts
service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/childimages/ChildImageTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeAlterationQueriesTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueriesTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueriesTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGeneratorIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt

Korjaus kääntäjävaroituksiin + kaikki varoitukset on jatkossa virheitä

---

keycloak/Dockerfile
keycloak/evaka-logging/pom.xml
keycloak/evaka-review-profile/pom.xml

Keycloak-päivitys versioon 24.0.3

---

frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx

Import rikkoo muut kuin Espoon käännökset.

Korjaus käyttöliittymän kääntämiseen

---

service/src/main/kotlin/fi/espoo/evaka/assistance/Assistance.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecision.kt
service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimes.kt
service/src/main/kotlin/fi/espoo/evaka/decision/DecisionStatus.kt
service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayQuestionnaires.kt
service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeAlterations.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Incomes.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
service/src/main/kotlin/fi/espoo/evaka/note/child/daily/ChildDailyNote.kt
service/src/main/kotlin/fi/espoo/evaka/pairing/Pairing.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlan.kt
service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
service/src/main/kotlin/fi/espoo/evaka/setting/SettingType.kt
service/src/main/kotlin/fi/espoo/evaka/user/EvakaUser.kt
service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
service/src/main/resources/db/migration/V400__drop_child_consent_type.sql
service/src/main/resources/migrations.txt

- DatabaseEnum kaikille tietokantaenumeille (paitsi unit_language)
- child_consent_type pois, koska sitä ei käytetä enää

Lisätty puuttuvat DatabaseEnum-toteutukset

---

frontend/src/citizen-frontend/applications/editor/verification/ServiceNeedSection.tsx
frontend/src/e2e-test/pages/citizen/citizen-applications.ts
frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt

Piilotetaan hakemuksen tuen tarpeen kuvaus toiselta huoltajalta

---

frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx

Tehdään formin tilan pakkopäivitys vain lukutilassa

Yksikköeditori kadottaa muutokset välilehteä vaihtaessa

---

service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt

Vain tyyppiä koulutus tai työasia olevat läsnäolomerkinnät katkaistaan automaattisesti työvuorosuunnitelman mukaan

Korjaus henkilökunnan työvuorojen automaattikatkaisuun

---

docs/diagrams/src/evaka-application.puml
frontend/src/citizen-frontend/applications/ChildApplicationsBlock.tsx
frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponse.tsx
frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponseList.tsx
frontend/src/citizen-frontend/decisions/decisions-page/ApplicationDecision.tsx
frontend/src/citizen-frontend/decisions/decisions-page/Decisions.tsx
frontend/src/citizen-frontend/generated/api-clients/application.ts
frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/dev-api/index.ts
frontend/src/e2e-test/specs/0_citizen/citizen-applications-list.spec.ts
frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts
frontend/src/lib-common/generated/action.d.ts
frontend/src/lib-common/generated/api-types/application.ts
service/codegen/src/main/kotlin/evaka/codegen/actionenum/Definitions.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt

Lapsen muut huoltajat ja sijaishuoltajat saa nähdä hakemukset/päätökset

---

frontend/src/lib-common/generated/api-types/invoicing.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/Helpers.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/decision/DecisionController.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
service/src/test/kotlin/fi/espoo/evaka/invoicing/service/PdfGenerationTest.kt

Turvakieltoesto ei koske päätöstiedostoja joissa ei ole henkilöiden osoitetietoja

---

frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx

Katsotaan oletusarvo luvituksista

Henkilökunnan läsnäolokirjauksen kasvatusvastuullisuuden parempi oletusarvo

---

frontend/package.json
frontend/src/lib-common/api-types/application/ApplicationFormData.ts

Kytketään päälle eslint-sääntö no-constant-binary-expression

---

service/src/main/resources/db/migration/V405__employee_pin_locked_not_null.sql
service/src/main/resources/migrations.txt

Pinkoodin lukittu-tila ei voi olla null

---

.github/workflows/release.yml

Tämä välttää kauan sitten avattujen PR:ien puuttumisen muutoslokilta.

Haetaan enemmän PR:iä julkaisua luodessa

---

frontend/src/employee-frontend/components/employees/EmployeePage.tsx
frontend/src/employee-frontend/components/employees/queries.ts
frontend/src/lib-common/generated/api-types/pis.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt

Paritus poistetaan myös käyttäjän deaktivoinnin yhteydessä

Pääkäyttäjä voi poistaa käyttäjän henkilökohtaisen mobiililaitteen parituksen

---

service/Dockerfile
service/build.gradle.kts
service/gradle/libs.versions.toml

- päivitetään kuin muutkin gradle-riippuvuudet -> helppo päivittää ja toimii dependabotin kanssa

Ladataan DataDog agent gradlella

---

service/Dockerfile

Vaihdetaan evaka-service käyttämään Azul Zulu OpenJDK JRE nykyisen Eclipse Temurin JDK:n sijaan (koskee vain ydintä)

---

keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java
keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff
keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java.diff

Korjaus Keycloak-rekisteröintiin

---

frontend/src/citizen-frontend/applications/queries.ts
frontend/src/citizen-frontend/generated/api-clients/serviceneed.ts
frontend/src/employee-frontend/generated/api-clients/attendance.ts
frontend/src/employee-frontend/generated/api-clients/serviceneed.ts
frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
frontend/src/employee-mobile-frontend/generated/api-clients/serviceneed.ts
frontend/src/employee-mobile-frontend/units/queries.ts
service/codegen/src/main/kotlin/evaka/codegen/api/Controllers.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedController.kt

Bugikorjaus tyhjään request param listaan ja lint/validaatiosääntö codegeniin

---

frontend/src/employee-frontend/components/reports/MealReport.tsx
frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
frontend/src/lib-common/generated/api-types/daycare.ts
frontend/src/lib-common/generated/api-types/reports.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/DaycareEditIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
service/src/main/kotlin/fi/espoo/evaka/reports/MealReportController.kt
service/src/main/kotlin/fi/espoo/evaka/reports/MealReportQueries.kt
service/src/main/kotlin/fi/espoo/evaka/reports/MealReportUtil.kt
service/src/test/kotlin/fi/espoo/evaka/reports/MealReportTests.kt

Tämä muutos lisää tiedot erityisruokavalioista yksikkökohtaiseen ruokailijaraporttiin. Jokainen ateria joka tilataan erityisruokavaliota noudattaville lapsille tulee raportissa omalle rivilleen. 
Tämä muutos lisää myös yksikkötestit ruokalijaraporttiin ja organisoi koodin helpommin testattavaksi.

Tieto erityisruokavalioista ruokailijaraporttiin

---

frontend/src/employee-frontend/components/ApplicationPage.tsx

Paperihakemukselle ei ladattu palveluntarpeita valittavaksi.

Korjaus paperihakemuksen palveluntarpeen valintaan

---

frontend/Dockerfile

Also upgrade `nginx-opentracing` and `dd-opentracing-cpp`

Bump nginx from 1.25.1 to 1.26.0 in /frontend

---

service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/note/group/GroupNoteController.kt

Muutama paikka lokitti vääriä asioita audit-lokiin.

Korjauksia audit-lokitukseen

---

frontend/src/citizen-frontend/personal-details/PersonalDetailsSection.tsx
frontend/src/e2e-test/pages/citizen/citizen-personal-details.ts
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx

- pakollisuustähti puhelinnumerolle
- ei sähköpostiosoitetta -valittuna ennen sähköpostiosoitteen asetusta

Kuntalaisen omat asetukset -parannuksia

---

frontend/src/employee-frontend/components/invoice/InvoiceDetailsSection.tsx
frontend/src/lib-common/generated/api-types/invoicing.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/Helpers.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueriesTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionsIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/InvoicingReportTest.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Invoices.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/resources/db/migration/V413__invoiced_fee_decision.sql
service/src/main/resources/migrations.txt
service/src/test/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClientTest.kt

Huom: Ei vaikuta takautuvasti menneisiin laskuihin

Tallennetaan ja näytetään laskuun liittyvät maksupäätökset

---

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessagePushNotificationsTest.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessagePushNotifications.kt

Notifikaatioita ei lähetetä jos kyse on "staff copy" -viestistä, jollainen syntyy esim. tiedotteita lähetettäessä

Ei lähetetä push-notifikaatioita mobiiliin tiedotteista

---

service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt

Vääriä asioita päätyi audit-lokiin.

Korjaus audit-lokitukseen

---

frontend/src/e2e-test/pages/employee/messages/messages-page.ts
frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
frontend/src/e2e-test/specs/7_messaging/municipal-messaging.spec.ts
frontend/src/employee-frontend/components/messages/MessageEditor.tsx
frontend/src/employee-frontend/components/messages/MessagesPage.tsx
frontend/src/employee-mobile-frontend/messages/MessageEditor.tsx
frontend/src/lib-common/generated/api-types/messaging.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

- Näytetään henkilökunnan vistinnässä vastaanottajan lisäfiltterit
- Filtterit näytetään vain kun viestiä lähetetään henkilökohtaiselta tai kunnalliselta tililtä
- Lisäfilttereitä ei ole toteutettu mobiilinäkymään

Näytetään viestinnässä vastaanottajan lisäfiltterit kun viestiä lähetetään henkilökohtaiselta tai kunnalliselta tililtä

---

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessagePushNotificationsTest.kt

fix: add missing parameter to push notification test

---

service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt

Maksupaatos-tietueiden päivämäärien on oltava lapsen varhaiskasvatuspaatos-tietuieden aikavälien sisällä. Ennen tätä muutosta tarkasteltiin kaikkien palveluntarpeiden aikaväliä. Tämän muutoksen jälkeen se tehdään per lapsi.

Korjaus Varda-virheisiin MA005-MA007

---

apigw/src/enduser/suomi-fi-saml.ts

Lokitetaan varoitus jos Suomi.fi lähettää meille virheellisen hetun

---

service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobRunner.kt

Muutoksen jälkeen scheduled jobit aloittaa ylätason spanin ja jokainen scheduled job -tyyppi tulee tähän valikkoon valittavaksi:

Scheduled jobit näkyy omina spaneina DataDogissa

---

frontend/proxy/files/bin/proxy-entrypoint.sh
frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
frontend/proxy/files/internal/security.txt.template
frontend/proxy/files/internal/security.txt.template.license

- luodaan security.txt Ruby erb-templatella eikä nginxin konfiguraatiolla
- Expires = käynnistyspäivä + 3kk
- ajetaan erb:tä `-T -` -optiolla, jolloin nämä toimii: `<-%` (poista vasen indentaatio) ja `-%>` (poista rivinvaihto)

Luodaan security.txt template-mekanismilla ja generoidaan sinne Expires-kenttä

---

service/src/integrationTest/kotlin/fi/espoo/evaka/assistance/AssistanceQueriesTest.kt
service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceQueries.kt

Päätetään tuen kerroin vain eilen päättyneen sijoituksen mukaan, ei koko historiaa.

Muutos tuen kertoimien päättämiseen

---

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/FamilyControllerTest.kt
service/src/main/kotlin/fi/espoo/evaka/pis/controllers/FamilyController.kt

Hide children from profile page contacts

---

frontend/src/employee-frontend/components/finance-basics/VoucherValueEditor.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

- Korjattu väärä sarakkeen otsikko
- Korjattu alle kolmivuotiaan arvon laskenta kertoimen muuttuessa

Korjaus palse-arvoeditorin ongelmiin

---

service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt

Korjattu off-by-one -virhe joka tuli PR:ssä #5169

Korjattu tuen tarpeen päätöksen hyväksyminen

---

keycloak/Dockerfile
keycloak/evaka-logging/pom.xml
keycloak/evaka-review-profile/pom.xml
keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff
keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java.diff

Päivitetään Keycloak versioon 24.0.4

---

service/src/main/resources/db/migration/V416__shift_care_operation_times_improvements.sql

Hotfix: Korjaus migratioon V416 (vuorohoidon aukioloajat)

---

frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt

Näytetään kuukausikalenterissa vain lapsen mahdolliset toimintapäivät

---

frontend/src/e2e-test/generated/api-clients.ts
frontend/src/e2e-test/generated/api-types.ts
frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts
frontend/src/e2e-test/specs/0_citizen/citizen-preschool-application.spec.ts
frontend/src/e2e-test/utils/application-forms.ts
frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
frontend/src/lib-common/api-types/application/ApplicationFormData.ts
frontend/src/lib-common/generated/api-types/application.ts
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationForm.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

Poistetaan oletusarvoinen ei sähköpostiosoitetta -valinta hakemukselta

---

frontend/src/lib-customizations/espoo/featureFlags.tsx

Keskusteluajanvaraukset käyttöön Espoon staging-ympäristössä

---

frontend/src/employee-frontend/components/invoice/InvoiceRowsSection.tsx
frontend/src/lib-common/generated/api-types/invoicing.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/Helpers.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Invoices.kt
service/src/test/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClientTest.kt

Jotta voidaan käyttää laskutusintegraatiossa eri koodia kunnalliselle ja ostopalvelulle.

Lisätty yksikön järjestämismuoto laskutustietoihin

---

frontend/proxy/files/etc/nginx/dd-config.json.template

https://github.com/DataDog/dd-opentracing-cpp/blob/master/doc/configuration.md#application-version

Lisätty frontend-kontin versio Datadog-integraatioon

---

service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt

Päiväkohtaiset lapsen tulo- ja lähtöajat raportin pitää vuorohoitoyksiköllä sisältää viikonloput

---

service/.gitignore

Kotlin v2 keeps some local temporary sessions here, which should never be committed

Ei huomioida Kotlin-kääntäjän sessiokansiota git-versioinnissa

---

frontend/src/employee-frontend/components/absences/MonthCalendarTable.tsx
frontend/src/lib-common/generated/api-types/absence.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt

toimi oikein viikkokalenterissa, nyt myös kuukausikalenterissa

Satunnaisen vuorohoidon varasijoitustarpeessa huomioidaan sijoitusyksikön vuorohoidon aukioloajat

---

frontend/src/e2e-test/pages/mobile/message-editor.ts
frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
frontend/src/employee-mobile-frontend/messages/MessageEditor.tsx
frontend/src/employee-mobile-frontend/messages/queries.ts
frontend/src/lib-components/molecules/ConfirmedMutation.tsx
frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts

Varoitetaan mobiilissakin jos viestillä on yli 2 vastaanottajaa

---

service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/process/ArchivedProcessQueriesTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt

Espoo: muutetaan organisaation nimi metadatassa

---

frontend/src/e2e-test/pages/mobile/top-nav.ts
frontend/src/e2e-test/specs/5_employee/system-notifications.spec.ts
frontend/src/employee-frontend/components/system-notifications/SystemNotificationsPage.tsx
frontend/src/employee-mobile-frontend/common/TopBar.tsx
frontend/src/employee-mobile-frontend/common/top-bar/queries.ts
frontend/src/employee-mobile-frontend/query.ts
frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
frontend/src/lib-icons/fontawesome.d.ts
frontend/src/lib-icons/free-icons.ts
frontend/src/lib-icons/pro-icons.ts

Tilapäiset ilmoitukset työntekijän mobiilissa

---

frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
service/src/main/resources/WEB-INF/templates/daycare/voucher/decision_sv.properties
service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.html
service/src/main/resources/WEB-INF/templates/shared/common.html
service/src/main/resources/WEB-INF/templates/shared/common.properties
service/src/main/resources/WEB-INF/templates/shared/common_sv.properties

- Päivitetään maksupäätösten linkki tulorajaohjeistukseen
- Päivitetään maksupäätösten tulorajaohjeistustekstejä
- Päivitetään muiden päätösten tekstejä

Espoo: Tekstikorjauksia

---

frontend/src/employee-frontend/components/finance-basics/ServiceNeedItem.tsx
frontend/src/employee-frontend/components/finance-basics/VoucherValueEditor.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Käyttäjä saa nyt parempaa palautetta palse-arvojen ylläpito-UI:n kenttien ongelmista suoraan käyttöliittymässä

Lisätty validointeja palse-arvojen ylläpito-UI:hin

---

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt

Ei yritetä poistaa henkilöä jolla on tuen tarpeen päätös

---

frontend/src/employee-frontend/components/reports/EndedPlacements.tsx
frontend/src/lib-common/generated/api-types/reports.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/reports/EndedPlacementsReport.kt

Lopettavien lasten raportilla näytetään nyt viimeisenä päättyvän sijoituksen yksikkö ja alue

Lisää päättyvän sijoituksen yksikkö ja alue varhaiskasvatuksessa lopettavien lasten raportille

---

keycloak/Dockerfile
keycloak/evaka-logging/pom.xml
keycloak/evaka-review-profile/pom.xml
keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff
keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java.diff

Päivitetään Keycloak versioon 24.0.5 (vain ydin)

---

frontend/src/employee-frontend/components/unit/TabApplications.tsx
frontend/src/lib-common/generated/api-types/application.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt

Jos kuntalainen on rastittanut hakemukselta vuorohoitokohdan, johtajalle näytetään yksikön hakemuslistan tooltipissä siitä ilmoitus

Vuorohoito näytetään hakemuksen tooltipissä jos se on valittu hakemukselle

---

frontend/.sentryclirc
frontend/Dockerfile
frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
frontend/src/lib-customizations/espoo/appConfigs.ts

Migrate sentry

---

frontend/src/lib-customizations/espoo/citizen.tsx

Korjataan linkki kuntalaisen tulotietojen ilmoituksessa (Espoo)

---

apigw/Dockerfile
apigw/entrypoint.sh

Fix host IP

---

frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx

Ei näytetä suljettuja yksiköitä tuen päätöksen lomakkeilla

---

frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template

Kerätään access logeja vain API-poluista ja Keycloakin realms-poluista

---

frontend/src/e2e-test/specs/5_employee/child-information-placements.spec.ts
frontend/src/employee-frontend/components/child-information/placements/CreatePlacementModal.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Sijoituksen päättymispäivä oletusarvoisesti tyhjäksi mutta pakolliseksi

---

service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt

Korjaus lasten läsnäolojen automaattikatkaisuun

---

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Lyhennetään vanhempainvapaa -teksti mahtumaan yksikön viikkonäkymässä

---

service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
service/src/main/resources/WEB-INF/templates/assistance-need-preschool/decision.properties
service/src/main/resources/WEB-INF/templates/assistance-need-preschool/decision_sv.properties
service/src/main/resources/WEB-INF/templates/assistance-need/decision.properties
service/src/main/resources/WEB-INF/templates/assistance-need/decision_sv.properties
service/src/main/resources/WEB-INF/templates/preparatory/decision.properties
service/src/main/resources/WEB-INF/templates/preparatory/decision_sv.properties
service/src/main/resources/WEB-INF/templates/preschool/decision.properties
service/src/main/resources/WEB-INF/templates/preschool/decision_sv.properties
service/src/main/resources/WEB-INF/templates/shared/daycare-correction.html
service/src/main/resources/WEB-INF/templates/shared/daycare-correction_sv.properties

Espoo: päivityksiä päätösten ja sähköpostien teksteihin

---

service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/SoapStackIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/MockSfiMessagesRestEndpoint.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClientIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/InMemoryStore.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/RestSchema.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClient.kt
service/src/main/kotlin/fi/espoo/evaka/shared/config/SfiConfig.kt

- REST-pohjainen toteutus SfiMessagesClient -interfacelle
- uudet env-muuttujat EVAKA_INTEGRATION_SFI_REST_ENABLED / EVAKA_INTEGRATION_SFI_REST_USERNAME / EVAKA_INTEGRATION_SFI_REST_PASSWORD
- osa vanhoista env-muuttujista on REST API:ssa pakollisia vaikka ei olleet SOAP API:ssa

Suomi.fi viestit REST-pilottitoteutus

---

service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt

Ei näytetä suljettuja yksiköitä toimintojen avauksissa

---

frontend/src/employee-frontend/components/applications/ApplicationActions.tsx
frontend/src/lib-components/molecules/modals/InfoModal.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Vahvistetaan hakemuksen poistaminen käsittelystä

---

frontend/src/employee-frontend/components/person-profile/PersonFeeDecisions.tsx
frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx

Järjestetään talouspäätökset päämiehen sivulla voimassaoloajan mukaan

---

frontend/src/employee-frontend/components/Reports.tsx

Raportit aakkosjärjestykseen

---

service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt

Jos varauksia tekee pitkälle ajalle, joka ylittää loma-ajan, on kuntalainen voinut tehdä varauksia aikojen kanssa loma-ajalle. Estetään tämä muuttamalla ajalliset varaukset ajattomiksi automaattisesti.

Ei sallita kuntalaisen tehdä varauksia aikojen kanssa avoimille loma-ajoille

---

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt

Annetaan koko kuun alennus kun kuukaudessa on vähemmän toimintapäiviä kuin päivähinnan jakaja ja kaikille toimintapäiville on merkitty maksuton poissaolo.

Korjaus laskujen luontiin (kiinteä päivähinnan jakaja + lyhyt kuukausi + maksuttomat poissaolot)

---

frontend/src/e2e-test/pages/employee/units/unit-week-calendar-page.ts
frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
frontend/src/lib-common/generated/api-types/attendance.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

Henkilökunta voi editoida ainoastaan omia läsnäolojaan

---

service/src/main/kotlin/fi/espoo/evaka/reports/NonSsnChildrenReportController.kt

Käytetään oikeaan ACL-funktiota

Korjaus raportin ACL-koodiin

---

service/gradle/libs.versions.toml

Päivitetään Gradle OWASP plugin versioon 10.0.1

---

service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClientIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/RestSchema.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClient.kt

Lisätään osoitesivun tuki Suomi.FI REST -pilottikoodiin

---

keycloak/Dockerfile
keycloak/docker-compose.yml
keycloak/evaka-logging/pom.xml
keycloak/evaka-review-profile/pom.xml
keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff
keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java.diff

Päivitetään Keycloak versioon 25.0.1

---

frontend/Dockerfile
frontend/proxy/files/bin/proxy-entrypoint.sh
frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
frontend/proxy/files/etc/nginx/dd-config.json.gomplate.license
frontend/proxy/files/etc/nginx/dd-config.json.template
frontend/proxy/files/etc/nginx/keycloak-proxy.conf.template
frontend/proxy/files/etc/nginx/nginx.conf.template
frontend/proxy/files/etc/nginx/proxy_params.template
frontend/proxy/files/internal/security.txt.gomplate.license
frontend/proxy/files/internal/security.txt.template

Korvataan Ruby sapluunat Gomplatella 

---

service/gradle/libs.versions.toml

Bump org.owasp.dependencycheck from 10.0.1 to 10.0.2

---

frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Tekstin selvennys liittyen loma-ajan lukitsemiseen, ks. #5326

Loma-ajan infotekstin muutos kuntalaisille

---

frontend/src/e2e-test/pages/employee/units/unit.ts
frontend/src/e2e-test/specs/5_employee/unit-editor.spec.ts
frontend/src/e2e-test/utils/page.ts
frontend/src/employee-frontend/components/unit/unit-details/CreateUnitPage.tsx
frontend/src/employee-frontend/components/unit/unit-details/UnitDetailsPage.tsx
frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
frontend/src/lib-common/generated/api-types/daycare.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt

Estetään yksikön sulkeminen jos sille on sijoituksia tai varasijoituksia sulkemispäivän jälkeen

---

frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx

Pieni tekstikorjaus suomenkieliseen käännökseen,

Tekstikorjaus keskusteluajan perumiseen

---

frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx
frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
frontend/src/employee-frontend/types/unit.ts
frontend/src/lib-common/generated/api-types/placement.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt

Aiemmin näkyi tyhjää jos oletuspalveluntarve oli käytössä.

Lisätty oletuspalveluntarve näkyviin ryhmät-taulukoihin

---

frontend/src/employee-mobile-frontend/child-attendance/ChildReservationList.tsx
frontend/src/employee-mobile-frontend/child-attendance/ChildSubListItem.tsx
frontend/src/lib-common/generated/api-types/reservations.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt

Vastaava kuin Tulossa-näkymässä.

Lisätty varasijoituksen ikoni mobiilin Seuraavat päivät -näkymään

---

frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx

Näytetään työntekijän mobiilin lapsilistassa ikoni myös Huom-muistiinpanosta

---

frontend/src/e2e-test/specs/0_citizen/citizen-start-after-holiday-deadline.spec.ts
service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriod.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt

Sallitaan varausten luonti lapsille jotka siirtyvät palveluseteliyksiköstä kunnalliseen

Sallitaan varausten luonti lapsille jotka eivät ole voineet vastata lomakyselyyn

---

frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx

Siirretään henkilökunnan läsnäolot lasten alapuolelle viikkokalenterissa

---

frontend/src/employee-frontend/components/unit/TabCalendar.tsx

Muutetaan "ei ryhmää" oletusvalinnaksi yksikön kalenterissa

---

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

Käytetään kunnallisen tiedotteen otsikkoa sähköpostiherätteen kuvauksessa

---

frontend/src/employee-frontend/components/reports/FamilyContacts.tsx
frontend/src/employee-frontend/generated/api-clients/reports.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/reports/FamilyContactReport.kt

Yhteystietokoosteessa voi valita päivämäärän jolta tiedot haetaan

---

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Viitataan hakijaan/aikuiseen eikä huoltajaan työntekijöiden hakemusnäkymässä jotta pätee kaikissa tapauksissa

---

frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionEditPage.tsx
frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Tämä olisi alunperin pitänyt olla radio buttoneita eikä checkboxeja. Vanhan datan takia sitä ei pysty enää muuttamaan, joten lisätty fronttiin validaatiovirhe mikäli jatkossa yrittää valita useamman kuin yhden.

Tuen päätöksellä saa valita vain yhden tuen tason

---

frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
frontend/src/employee-mobile-frontend/staff-attendance/StaffListItem.tsx
frontend/src/lib-common/generated/api-types/attendance.ts
service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt

Näytetään kasvatusvastuullisuus-ikoni mobiilissa

---

service/src/main/kotlin/fi/espoo/evaka/messaging/MessagePushNotifications.kt

Testi olisi kiva, mutta vaikuttaa hankalalta assertoida kun viesti on encryptattu

Lisätään mobiilin uusi viesti -notifikaatioon lähettäjän nimi

---

service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt

Poistetaan myös PDF samalla jos pääkäyttäjä poistaa julkaistun lomakeluonnoksen

---

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
frontend/src/citizen-frontend/calendar/CalendarPage.tsx

Riippuen mistä modaalin päädyttiin joko suljetaan se tai palataan takaisin päivä-modaaliin

Kuntalaisen poissaolo-modaalin peruuta-nappi palaa sinne mistä tultiin

---

service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizen.kt

Siivotaan varaukset ja poissaolot kun kuntalainen irtisanoo sijoituksen tai sen liittyvän osuuden

---

service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt

Espoo: esiopetuksen tuen päätösten TOS-numero

---

service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt

Nopeudet pelkän haun osalta (= mitä deletoidaan):
Vanha kysely: 20min+
Uusi kysely: 15s

Inaktiivisten henkilöiden poistokyselyn optimointi

---

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx

Kuntalaisen poissaolomodaalin päättymispäivän maksimiarvolle validaatio käyttöliittymään

---

service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt

Lisätty dokumentaatio:
https://github.com/espoon-voltti/evaka/wiki/L%C3%A4sn%C3%A4%E2%80%90-ja-poissaolot#lasten-l%C3%A4sn%C3%A4olojen-automaattinen-katkaiseminen

Automaattikatkaistaan myös päivälasten läsnäolot vuorohoitoyksiköissä

---

keycloak/Dockerfile
keycloak/dummy-suomifi/gradle/libs.versions.toml
keycloak/evaka-logging/pom.xml
keycloak/evaka-review-profile/pom.xml
keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff
keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java.diff

Päivitetään Keycloak versioon 25.0.2 (Espoo)

---

service/src/integrationTest/resources/application-integration-test.yaml
service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailConfig.kt
service/src/main/kotlin/fi/espoo/evaka/shared/config/AwsConfig.kt
service/src/main/resources/application-local.yaml

Oikeissa AWS-ympäristöissä SDK osaa selvittää sen itse ja lokaalisti meillä on hardkoodattu arvo koodissa eikä enviä muutenkaan käytetä

Poistetaan manuaalinen AWS SDK region-konffi

---

frontend/src/lib-components/atoms/EnvironmentLabel.tsx

Tyyliparannus ympäristöindikaattoriin

---

service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt

Testejä joilla varmistetaan ettei VEO näe tekemiään lapsen dokumentteja / päätöksiä jos lapsi ei ole enää sijoitettuna omaan yksikköön

Veo ei saa nähdä omia lapsen dokumentteja jos lapsi ei ole sijoitettuna omaan yksikköön

---

service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt

Vasuissa luettu tila perustui siihen onko antanut suostumuksen jakaa tiedot

Migratoidaan vasuista huoltajien lukukuittaukset

---

frontend/src/employee-frontend/components/vasu/templates/VasuTemplatesPage.tsx
frontend/src/lib-common/generated/api-types/vasu.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuTemplateTest.kt
service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplate.kt
service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateQueries.kt

Näytetään onnistuneesti migratoitujen dokumenttien määrät

---

service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt

Tuetaan puutteellisia vastauksia sisältävää vanhaa dataa vasumigraatiossa

---

service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModifications.kt
service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsBatchRefreshService.kt
service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt

Parannuksia muutostietopalvelun hetujen null-käsittelyyn

---

frontend/src/employee-frontend/components/person-profile/income/IncomeItemHeader.tsx

Tulotiedon editoiminen avaa tulotiedon näkyviin

---

compose/docker-compose.yml
keycloak/docker-compose.yml

Vaikuttaa vain paikalliseen ympäristöön, koska AWS-ympäristöissä envit tulee infrasta

Käytetään Keycloakin Hostname v2 -konfiguraatiota paikallisessa ympäristössä

---

frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt

Ruotsinkieliset käyttöliittymätekstit ja Espoon sähköpostipohjatekstit.

Keskusteluaikavarausten kuntalaisen ruotsinnokset

---

frontend/src/citizen-frontend/calendar/DailyServiceTimeNotifications.tsx
frontend/src/citizen-frontend/generated/api-clients/dailyservicetimes.ts
frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/generated/api-types.ts
frontend/src/e2e-test/specs/0_citizen/citizen-daily-service-times.spec.ts
frontend/src/employee-frontend/components/child-information/DailyServiceTimesSection.tsx
frontend/src/employee-frontend/components/child-information/daily-service-times/DailyServiceTimesForms.tsx
frontend/src/lib-common/generated/api-types/dailyservicetimes.ts
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceGenerationIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimes.kt
service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesCitizenController.kt
service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesController.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/resources/db/migration/V427__less_columns_in_daily_service_time_notifications.sql
service/src/main/resources/migrations.txt

Näytetään kuntalaiselle vain huomautus. Läsnäolot poistetaan vain automaattisesti luotavien poissaolojen päiviltä epäsäännöllisen ajan tapauksessa.

Ei poisteta varauksia kun päivittäinen varhaiskasvatusaika muuttuu

---

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueriesTest.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
service/src/main/kotlin/fi/espoo/evaka/shared/Tracing.kt
service/src/main/kotlin/fi/espoo/evaka/shared/data/DateSet.kt
service/src/main/kotlin/fi/espoo/evaka/shared/data/RangeBasedSet.kt
service/src/main/kotlin/fi/espoo/evaka/shared/utils/Kotlin.kt

Korjataan laskugeneroinnin suorituskyky, ja parannellaan koodia

---

service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt

Henkilökunnan mobiilista ei pystynyt muokkaamaan tai poistamaan loma-ajalle sijoittuvia varauksia
Muokkaus ja poisto onnistuu

Sallitaan varausten muokkaus henkilökunnan mobiilista myös loma-ajalla

---

service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt

Iso kysely + generate_series = hidas
Haetaan datat koko rangen perusteella (= nopeita kyselyitä jotka osuu indekseihin), ja lasketaan Kotlin-koodin puolella asiat

Käyttö/täyttöastekyselyn tekninen parannus

---

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx

Lisätty validaatiovirheeseen aria-vinkit ruudunlukijaa varten

Saavutettavuusparannus kuntalaisen poissaolodialogin validointivirheeseen

---

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ExceededServiceNeedsReportTest.kt
service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
service/src/main/kotlin/fi/espoo/evaka/reports/ExceededServiceNeedsReport.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
service/src/test/kotlin/fi/espoo/evaka/reservations/UsedServiceTests.kt

Käytetyn palveluntarpeen keskiarvon laskennassa käytetään nyt 21:n sijaan todellista toimintapäivien määrää päiville, joilla on poissaolotyyppi `FORCE_MAJEURE`, `FREE_ABSENCE` tai `PARENTLEAVE`. Tällöin lapset, joilla on täysi kuukausi hyvitettyjä poissaoloja, eivät nouse palveluntarpeen ylitykset -raportille eivätkä näytä ylitettyjen tuntien varoitusta yksikön päiväkirjalla tai kuntalaisen kalenterissa vaikka kuukaudessa olisi yli 21 toimintapäivää.

Korjaus käytetyn tuntimäärän keskiarvolaskentaan ilmaisten läsnäolojen tapauksessa

---

compose/e2e/playwright.Dockerfile
keycloak/Dockerfile
service/Dockerfile

Dockerfile muotoilu korjauksia

---

service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt

Yksikön päättymispäivä on inklusiivinen eli viimeinen päivä kun on yhä toiminnassa

---

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
frontend/src/citizen-frontend/calendar/CalendarPage.tsx
frontend/src/citizen-frontend/calendar/DayView.tsx
frontend/src/citizen-frontend/calendar/ReservationModal.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Varoitetaan kuntalaista jos on merkitsemässä poissaoloa suljetun lomakyselyn ajalle

---

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt

Poistetaan deaktiivisen työntekijän oikeudet 8 viikon jälkeen

---

service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeAlterationQueries.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueries.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/DraftQueries.kt
service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentQueries.kt
service/src/main/kotlin/fi/espoo/evaka/reports/DuplicatePeopleReport.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt

`json`-tyypille ei meidän projektissa ole tarvetta vaan aina pitäisi käyttää `jsonb`:tä

Käytetään `jsonb_build_object` aina `json_build_object` sijaan

---

frontend/src/citizen-frontend/attachments.ts
frontend/src/citizen-frontend/generated/api-clients/messaging.ts
frontend/src/citizen-frontend/messages/MessageEditor.tsx
frontend/src/citizen-frontend/messages/MessagesPage.tsx
frontend/src/citizen-frontend/messages/state.tsx
frontend/src/e2e-test/pages/citizen/citizen-messages.ts
frontend/src/e2e-test/pages/employee/messages/messages-page.ts
frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
frontend/src/employee-frontend/components/messages/MessageEditor.tsx
frontend/src/lib-common/generated/api-types/messaging.ts
frontend/src/lib-components/molecules/FileUpload.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/Audit.kt
service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt

Kuntalainen voi lisätä uuteen viestiin liitteen jos lapsi on vuorohoidossa

---

frontend/src/employee-frontend/components/document-templates/template-editor/DocumentTemplatesPage.tsx
frontend/src/lib-common/generated/api-types/document.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/document/DocumentTemplateIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateQueries.kt

Näytetään luotujen dokumenttien määrä lomakepohjat-listassa

---

service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecision.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecision.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt

Piilotetaan muutama sensitiivinen tieto lokitukselta virhetilanteissa

---

frontend/src/e2e-test/generated/api-clients.ts
frontend/src/e2e-test/pages/employee/holiday-term-periods.ts
frontend/src/e2e-test/specs/5_employee/holiday-term-period.spec.ts
frontend/src/employee-frontend/components/holiday-term-periods/HolidayAndTermPeriodsPage.tsx
frontend/src/employee-frontend/components/holiday-term-periods/HolidayPeriodForm.tsx
frontend/src/employee-frontend/generated/api-clients/holidayperiod.ts
frontend/src/lib-common/generated/api-types/holidayperiod.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriod.kt
service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodController.kt
service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

Tarvittaessa poista ja luo uusi

Lomakauden aikaväliä ei voi muokata jälkeenpäin

---

frontend/src/e2e-test/specs/5_employee/holiday-term-period.spec.ts
frontend/src/employee-frontend/components/holiday-term-periods/HolidayAndTermPeriodsPage.tsx

Järjestetään loma-ajat uusimmasta vanhimpaan

---

frontend/src/employee-frontend/components/unit/unit-reservations/ChildDateModal.tsx

Korjataan turhat varoitukset päiväkirjamodaalissa

---

frontend/src/employee-frontend/components/applications/ApplicationActions.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
service/src/main/kotlin/fi/espoo/evaka/process/ArchivedProcesses.kt

Käsittelystä poistetun hakemuksen voi palauttaa saapuneisiin

---

service/src/main/kotlin/fi/espoo/evaka/shared/Tracing.kt

- makeCurrent must be used
- record the whole exception instead of just setting the error state

Korjaus OpenTelemetryn spanien käyttöön

---

frontend/package.json
frontend/src/employee-frontend/components/unit/queries.ts
frontend/src/employee-frontend/components/unit/tab-unit-information/Occupancy.tsx
frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupanciesForSingleDay.tsx
frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraphPlanned.tsx
frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraphRealized.tsx
frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/chart-commons.ts
frontend/src/employee-frontend/generated/api-clients/occupancy.ts
frontend/src/employee-frontend/index.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
frontend/yarn.lock
service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt
service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt

Visualisoidaan olemassa olevan raportin data

Päivän käyttöastegraafin suunnitelma

---

frontend/src/e2e-test/pages/employee/guardian-information.ts
frontend/src/e2e-test/specs/5_employee/income.spec.ts
frontend/src/e2e-test/utils/page.ts
frontend/src/employee-frontend/components/person-profile/income/IncomeItemEditor.tsx

Perutaan tulotiedon loppupäivän pakollisuus

---

service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/MockSfiMessagesRestEndpoint.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/RestSchema.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClient.kt

Päivitetään Suomi.fi REST AccessTokenResponse uuden speksin mukaiseksi

---

frontend/src/citizen-frontend/calendar/CalendarListView.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx

Tehdään kuntalaisen mobiiliin läsnä/poissaolojen lisäys -napista helpommin huomattava

---

frontend/package.json
frontend/src/employee-mobile-frontend/child-info/ImageEditor.tsx
frontend/yarn.lock

Kuvan rajaus tehtiin väärin jos käyttäjä ei muuttanut kuvan rajausta
Kuvan rajaus tehdään oikein myös silloin kun käyttäjä ei manuaalisesti rajaa kuvaa

Korjaus lapsen kuvan lisäykseen

---

.github/workflows/build.yml

Poista käyttämätön ECR_REGISTRY muuttuja

---

.github/workflows/build.yml

Fix uploading frontend files

---

frontend/src/employee-frontend/components/reports/EndedPlacements.tsx

Varhaiskasvatuksessa lopettavat lapset raportille lisätty aluefiltteri

Varhaiskasvatuksessa lopettavat lapset raportille lisätty aluefiltteri

---

.github/workflows/build.yml

Korjaa CI:n frontend tiedotojen lähetys

---

frontend/src/e2e-test/pages/employee/finance/finance-page.ts
frontend/src/e2e-test/specs/4_finance/invoices.spec.ts
frontend/src/employee-frontend/components/invoice/Actions.tsx
frontend/src/employee-frontend/components/invoice/InvoicePage.tsx
frontend/src/employee-frontend/components/invoice/InvoiceRowsSection.tsx
frontend/src/employee-frontend/components/invoice/InvoiceRowsSectionRow.tsx
frontend/src/employee-frontend/components/person-profile/PersonInvoiceCorrections.tsx
frontend/src/employee-frontend/generated/api-clients/invoicing.ts
frontend/src/lib-common/generated/action.d.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

Poistetaan turha feature joka konfliktoi tulevan oikaisulaskut-featuren kanssa

Laskuluonnoksen rivejä ei voi enää muokata manuaalisesti

---

service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt

Suorituskykyparannus lasten läsnäolohakuun (käytössä mobiilissa)

---

service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt

Suorituskykyparannus yksikön kuukausikalenteriin

---

service/src/integrationTest/kotlin/fi/espoo/evaka/jamix/JamixIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/kotlin/fi/espoo/evaka/specialdiet/SpecialDietController.kt
service/src/main/kotlin/fi/espoo/evaka/specialdiet/SpecialDietQueries.kt

Yksi sähköpostityyppi jäi puuttumaan PR:ssä #5569

Lisää korjauksia sähköpostien lähetykseen

---

frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionReservationModal.tsx
frontend/src/e2e-test/pages/citizen/citizen-discussion-surveys.ts
frontend/src/e2e-test/specs/0_citizen/citizen-discussion-surveys.spec.ts
service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEvent.kt
service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventController.kt
service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt

Palautetaan kuntalaisen näkymään ainoastaan suoraan kuhunkin sijoitukseen ja ryhmäsijoitukseen osuvat keskusteluajat ilman toisiintumista.

Usean kyselyn aikaisen sijoituksen aiheuttamien keskusteluaikaongelmien korjaus kuntalaiselle

---

frontend/src/e2e-test/pages/employee/reports.ts
frontend/src/e2e-test/specs/5_employee/child-attendance-reservation-report.spec.ts
frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Lasten läsnäoloraporttiin tuntifiltteri

---

service/src/main/kotlin/fi/espoo/evaka/shared/config/SpringMvcConfig.kt

Ei heitetä virhettä jos pyynnössä ei ole Accept-headeria

---

frontend/src/e2e-test/pages/employee/units/unit.ts
frontend/src/e2e-test/specs/5_employee/unit-calendar-events.spec.ts
frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/DiscussionSurveyView.tsx
frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/survey-editor/form.tsx

Lisätty tuki useiden sijoitusten ryhmittelyyn ja käsittelyyn lapsittain. Lisätty myös usean sijoituksen testidataa.

Korjaa monta sijoitusta omaavien lasten näyttäminen kasvattajille keskustelukyselyissä

---

frontend/src/e2e-test/pages/employee/employees.ts
frontend/src/e2e-test/specs/5_employee/employees.spec.ts
frontend/src/employee-frontend/components/employees/EmployeeList.tsx
frontend/src/employee-frontend/components/employees/EmployeesPage.tsx
frontend/src/employee-frontend/components/employees/queries.ts
frontend/src/lib-common/generated/api-types/pis.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerSearchIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt

Henkilökuntalistaan lisätty "piilotetaan deaktivoidu"-filtteri

---

frontend/src/lib-customizations/espoo/featureFlags.tsx

Espoo: keskusteluvaraukset tuotantoon

---

frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx
frontend/src/citizen-frontend/applications/editor/ApplicationFormPreschool.tsx
frontend/src/citizen-frontend/income-statements/ChildIncomeStatementEditor.tsx
frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx
frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx
frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx
frontend/src/employee-frontend/components/reports/ChildAttendanceReport.tsx
frontend/src/employee-frontend/components/reports/CustomerFees.tsx
frontend/src/employee-frontend/components/reports/ExceededServiceNeeds.tsx
frontend/src/employee-frontend/components/reports/FamilyContacts.tsx
frontend/src/employee-frontend/components/reports/MissingHeadOfFamily.tsx
frontend/src/employee-frontend/components/reports/PreschoolAbsenceReport.tsx
frontend/src/employee-frontend/components/unit/unit-reservations/ChildDateModal.tsx
frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx
frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsent.tsx
frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx
frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx
frontend/src/employee-mobile-frontend/common/top-bar/LoggedInUser.tsx
frontend/src/employee-mobile-frontend/messages/ThreadView.tsx
frontend/src/employee-mobile-frontend/messages/state.tsx
frontend/src/lib-common/query.ts

Ennen:
```ts
useQueryResult(
queryOrDefault(myQuery, [])(cond ? param : undefined)
)
```
Jälkeen:
```ts
useQueryResult(cond ? myQuery(param) : constantQuery([]))
```

Paremmat tyypitykset queryille + `queryOrDefault` pois

---

frontend/src/employee-frontend/components/absences/MonthCalendarCell.tsx
frontend/src/employee-frontend/components/absences/MonthCalendarTable.tsx
frontend/src/lib-components/layout/Table.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Yksikön kuukausikalenterissa voi valita rivin kaikki päivät yhdellä klikkauksella

---

frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template

Korjataan liitetiedostojen maksimikoon rajoitus

---

service/src/main/resources/db/migration/V433__child_document_template_index.sql
service/src/main/resources/migrations.txt

- `getTemplateSummaries` dokumenttien määrien laskeminen 100+ ms seq scan → <10 ms index only scan
- tämä kysely ajetaan aina lapsen tiedot -sivulla (riippumatta katsotaanko dokumentteja vai ei)

Suorituskykyparannus lapsen tiedot -sivulle

---

frontend/src/citizen-frontend/messages/MessagesPage.tsx
frontend/src/e2e-test/pages/citizen/citizen-messages.ts
frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
frontend/src/lib-components/Notifications.tsx
frontend/src/lib-components/molecules/TimedToast.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Onnistuneen viestin lähetyksen jälkeen ruudulle notifikaatio, joka toimii ruudunlukijalla. Sulkeutuu 10s sisään automaattisesti, hoverilla voi tauottaa.
https://github.com/user-attachments/assets/da1660ca-f6a1-4552-825b-ba53bd9f4120

Viestin lähetyksestä indikaatio ruudunlukijalle

---

service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt

- `/employee/occupancy/units/{unitId}/day/planned` ja `/employee/reports/attendance-reservation/{unitId}`
- Pitäisi käyttää `between_start_and_end`-funktiota jotta päivämäärärajaus onnistuu käyttämään indeksiä
- Esimerkkikesto kyselylle: 2s -> 80ms

Suorituskykyparannus läsnäolotietojen hakuun

---

apigw/src/shared/service-client.ts

Tämä on apigw<->service endpoint eikä ole jostain syystä system-käyttäjän endpoint, joten se jäi huomaamatta aiemmin kun prefixit laitettiin paikoilleen.

Yhden API-polun korjaus

---

keycloak/Dockerfile
keycloak/dummy-suomifi/gradle/libs.versions.toml
keycloak/evaka-logging/pom.xml

Päivitetään Keycloak versioon 25.0.5

---

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt

- Ei poisteta aikuista jolla on assistance_need_preschool_decision_guardian taulussa rivi
- Ei poisteta lasta jolla on pedagogical_document taulussa rivi

Ei yritetä poistaa inaktiivista huoltajaa tai lasta jolla on pedadoc tai tuen päätös

---

service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt

`IsEmployee` toteuttaa vastaavat.

Poistetaan käyttämättömiä metodeita

---

service/src/main/resources/db/migration/V435__archived_process_fix_trigger.sql
service/src/main/resources/migrations.txt

`trigger_refresh_updated` -> `trigger_refresh_updated_at`

Käytetään oikeaa triggeriä `archived_process`-taulussa

---

frontend/src/employee-frontend/components/unit/tab-groups/Groups.tsx

Varhaiskasvatussihteeri voi nähdä ryhmien kalenterin menneisyyteen

---

frontend/src/e2e-test/specs/5_employee/child-information.spec.ts
frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx

1. järjestys kuntoon
2. id pois nimestä
3. suodatus hakee vain nimen alusta

Parannuksia erityisruokavalion valintaan

---

frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/resources/application-espoo_evaka.yaml

- Päätöksiin oikea postilokero
- Isyys/vanhempainvapaa -> vanhempainvapaa

Tekstikorjauksia

---

frontend/src/employee-frontend/components/reports/FuturePreschoolersReport.tsx

lisätään toimintayksikön id ladattavalle tulevat esikoululaiset raportille

---

frontend/src/citizen-frontend/messages/ThreadView.tsx
frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts

Lisätty notifikaatio onnistuneesta viestin lähetyksestä viestiketjuun. Käyttää #5616 ominaisuutta.
https://github.com/user-attachments/assets/8fda094f-3f4a-4c51-aa2e-7d557aad65aa

Viestiketjuun vastaamisesta indikaatio ruudunlukijalle

---

service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt

Muutettu kovakoodattu 31.7. konfiguroitavaksi. Tampereella asetetaan arvoon 15.8.

Lisätään mahdollisuus konfiguroida varhaiskasvatuksen oletuspäättymispäivämäärä

---

service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt

Poistetaan asiakasmaksutiimi osoite tulotietomuistutukselta

---

apigw/src/shared/service-client.ts
frontend/src/employee-mobile-frontend/auth/api.ts
frontend/src/employee-mobile-frontend/generated/api-clients/pairing.ts
frontend/src/lib-common/generated/api-types/pairing.ts
frontend/src/lib-common/generated/api-types/pis.ts
service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
service/src/main/kotlin/fi/espoo/evaka/pairing/MobileDevicesController.kt
service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt

Muutetaan pin-login endpoint system-tyyppiseksi

---

apigw/.dockerignore
apigw/Dockerfile
apigw/jest.config.js
apigw/package.json
apigw/src/shared/__tests__/logging.ts
apigw/src/shared/__tests__/saml-certificates-test.ts

- Korjataan tyypitykset testeissä
- Ajetaan tyyppitarkistus CI:ssä
- Modernisoidaan jestin konfiguraatio

apigw:n testeihin liittyviä korjauksia

---

frontend/src/e2e-test/pages/mobile/staff-page.ts
frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
frontend/src/employee-mobile-frontend/App.tsx
frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendanceEditPage.tsx
frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx
frontend/src/employee-mobile-frontend/staff-attendance/StaffPreviousAttendancesPage.tsx
frontend/src/employee-mobile-frontend/staff-attendance/queries.ts
frontend/src/lib-components/layout/ListGrid.tsx
frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt

Aiempien päivien kirjausten muokkaus mobiilissa

---

apigw/src/enduser/mapRoutes.ts
apigw/src/index.ts
apigw/src/shared/auth/jwt.ts
apigw/src/shared/config.ts
apigw/src/shared/middleware/error-handler.ts

- paremmat virheet jos pakollinen muuttuja puuttuu ("SOME_VARIABLE must be set", eikä vaan "Configuration parameter was not provided")
- yksi megalista jossa on kaikki tuetut envimuuttujat
- kaikki envimuuttujat dokumentoitu
- varoitukset deprekoitujen envimuuttujien käytöstä

Parempi apigw:n konfiguraatiomekanismi ja dokumentaatio

---

service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
service/src/main/kotlin/fi/espoo/evaka/shared/data/RangeBasedMap.kt
service/src/main/kotlin/fi/espoo/evaka/shared/data/RangeBasedSet.kt
service/src/test/kotlin/fi/espoo/evaka/shared/data/DateMapTest.kt
service/src/test/kotlin/fi/espoo/evaka/shared/data/DateSetTest.kt
service/src/test/kotlin/fi/espoo/evaka/shared/data/DateTimeMapTest.kt
service/src/test/kotlin/fi/espoo/evaka/shared/data/DateTimeSetTest.kt

Parannuksia RangeBasedSet/RangeBasedMap -datarakenteisiin

---

keycloak/Dockerfile
keycloak/dummy-suomifi/gradle/libs.versions.toml
keycloak/evaka-logging/pom.xml

Päivitetään Keycloak versioon 25.0.6

---

frontend/src/citizen-frontend/calendar/queries.ts
frontend/src/citizen-frontend/generated/api-clients/reservations.ts
frontend/src/employee-frontend/components/unit/queries.ts
frontend/src/employee-frontend/generated/api-clients/reservations.ts
frontend/src/lib-customizations/espoo/featureFlags.tsx
frontend/src/lib-customizations/types.d.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

Feature flag on päällä kaikissa kunnissa.

Tekinen: Poistetaan `automaticFixedScheduleAbsences` feature flag

---

frontend/src/employee-frontend/components/reports/CustomerFees.tsx

Maksumäärät olivat raportilla sentteinä
Maksumäärät ovat raportilla euroina

Muutetaan asiakasmaksut csv raportti käyttämään euroja senttien sijaan

---

frontend/src/citizen-frontend/income-statements/ChildrenIncomeStatements.tsx
frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Näytetään tuloselvityksen luontipäivä kuntalaiselle

---

frontend/src/e2e-test/pages/employee/child-information.ts
frontend/src/e2e-test/specs/5_employee/service-applications.spec.ts
frontend/src/employee-frontend/components/child-information/ServiceApplicationsSection.tsx
frontend/src/employee-frontend/components/child-information/placements/service-needs/ServiceNeedReadRow.tsx
frontend/src/employee-frontend/generated/api-clients/serviceneed.ts
frontend/src/lib-common/generated/api-types/serviceneed.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplication.kt
service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationController.kt
service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationQueries.kt

Palveluntarpeen muutoshakemuksen hyväksyntä luo uuden palveluntarpeen

---

frontend/src/employee-frontend/components/child-information/ServiceApplicationsSection.tsx
frontend/src/lib-common/generated/api-types/serviceneed.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplication.kt
service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationController.kt
service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationQueries.kt

Palveluntarpeen muutoshakemus sallii vaihdon osapäiväisen/kokopäiväisen sijoituksen välillä

---

service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanQueries.kt

Ei lasketa huoltajalla vahvistettavana olevia hakemuksia yksikön hakuprosessi-välilehden huomio-lukumäärään

---

service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationQueries.kt
service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt

Lokitetaan personId:t henkilöiltä joihin kohdistuu VTJ MUTP päivitys

---

frontend/src/employee-mobile-frontend/settings/SettingsPage.tsx

Korjataan työntekijän mobiilin navigaatiopalkki asetukset sivulla

---

frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
frontend/src/e2e-test/pages/citizen/citizen-income.ts
frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts

Näytetään kuntalaisen tuloselvityksessä voimassaoloaikainfotekstivalidointi oikein

---

service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt

ei näytetä päivälapsia läsnäolevina viikonloppuisin

Työntekijän mobiliin seuraavat päivät näkymä ottaa huomioon lapsen toimintapäivät (vuorohoitopalveluntarve)

---

service/src/main/kotlin/fi/espoo/evaka/placement/PlacementType.kt
service/src/main/kotlin/fi/espoo/evaka/reports/MealReportUtil.kt
service/src/test/kotlin/fi/espoo/evaka/reports/MealReportTests.kt

Esiopetuksessa oleville lapsille tilattiin esiopetuksen lomapäiville aamupala, lounas ja välipala
Ei tilata mitään ruokia esiopetuslapsille esiopetuksen loma-aikana

Ei tilata ruokia esiopetuslapsille loma-aikana

---

service/gradle.properties
service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt

On jo "normikonffissa", mutta laitetaan kaikkiin niin mahdolliset ongelmat jää varmasti aikaisemmin kiinni

Lisätään validateMigrationNaming-asetus kaikkiin flyway-konfiguraatioihin

---

service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

Käyttöliittymässä tämä vaatimus jo oli.

Vahvan tunnistautumisen vaatimus palveluntarpeen muutoshakemuksen luontirajapintaan

---

service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt

Lisätään integraatiotesti joilla tarkistetaan tietokantaskeeman rakennetta

---

service/build.gradle.kts
service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/SoapStackIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/MockPasswordStore.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/MockSfiMessagesRestEndpoint.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClientIntegrationTest.kt
service/src/integrationTest/resources/application-integration-test.yaml
service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/MockSfiMessagesClient.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesClient.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/PasswordStore.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/RestSchema.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClient.kt
service/src/main/kotlin/fi/espoo/evaka/shared/config/AwsConfig.kt
service/src/main/kotlin/fi/espoo/evaka/shared/config/SfiConfig.kt
service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt

- evaka-service lukee ja päivittää itse SSM:ssä olevaa salasanaa (vaatii infrassa IAM-oikeudet)
- ajastettu jobi joka ajaa päivityksen säännöllisesti
- SSM parametrien labeleihin perustuva vikasietoinen päivitys

Salasanan rotatointi Suomi.fi viestit REST-toteutukseen + tiukempi integraatio SSM:n kanssa

---

frontend/src/employee-frontend/generated/api-clients/placement.ts
frontend/src/employee-frontend/state/child.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareQueries.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt

Parannetaan joidenkin sijoitus- ja varahoitokyselyiden suorituskykyä

---

service/owasp-suppressions.xml

OWASP: ohita CVE-2024-9329

---

README.md

Lisätään readme-tiedostoon rekisteröity tavaramerkki

---

service/build.gradle.kts
service/evaka-bom/build.gradle.kts
service/src/main/kotlin/fi/espoo/evaka/shared/data/DateSet.kt
service/src/main/kotlin/fi/espoo/evaka/shared/data/DateTimeSet.kt
service/src/main/kotlin/fi/espoo/evaka/shared/data/RangeBasedSet.kt
service/src/main/kotlin/fi/espoo/evaka/shared/data/TimeSet.kt
service/src/test/kotlin/fi/espoo/evaka/shared/ArbExtensions.kt
service/src/test/kotlin/fi/espoo/evaka/shared/data/DateSetPropertyTest.kt
service/src/test/kotlin/fi/espoo/evaka/shared/data/DateTimeSetPropertyTest.kt
service/src/test/kotlin/fi/espoo/evaka/shared/data/RangeBasedSetPropertyTest.kt

Parannetaan RangeBasedSet-tietorakenteiden suorituskykyä binäärihaulla

---

frontend/src/employee-frontend/components/absences/StaffAttendance.tsx

Yksikkökalenterissa henkilökunnan ei-reaaliaikaiset läsnäolot voi merkitä vain toimintapäiville

---

frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/NewServiceApplicationPage.tsx
frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceApplications.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Palveluntarpeen muutoshakemuksen infotekstit

---

frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/generated/api-types.ts
frontend/src/e2e-test/pages/employee/child-information.ts
frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
frontend/src/e2e-test/specs/5_employee/child-information-assistance.spec.ts
frontend/src/employee-frontend/components/child-information/AssistanceNeedVoucherCoefficientSection.tsx
frontend/src/employee-frontend/components/child-information/assistance-need/voucher-coefficient/AssistanceNeedVoucherCoefficientRow.tsx
frontend/src/employee-frontend/components/child-information/assistance/AssistanceFactorRow.tsx
frontend/src/employee-frontend/components/child-information/assistance/AssistanceFactorSection.tsx
frontend/src/lib-common/generated/api-types/assistance.ts
frontend/src/lib-common/generated/api-types/assistanceneed.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedVoucherCoefficientEndOutdatedTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/espoo/bi/EspooBiTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
service/src/main/kotlin/fi/espoo/evaka/assistance/Assistance.kt
service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/vouchercoefficient/AssistanceNeedVoucherCoefficient.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/vouchercoefficient/AssistanceNeedVoucherCoefficientController.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/vouchercoefficient/AssistanceNeedVoucherCoefficientQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
service/src/main/resources/db/migration/V445__assistance_need_voucher_coefficient_modified_by.sql
service/src/main/resources/migrations.txt

Palvelusetelikerroin- ja tukikerroinriveihin on lisätty viimeisen muutoksen aika sekä viimeinen muokkaaja tooltipina.

Viimeinen muokkaaja ja viimeisen muutoksen aika lisätty palvelusetelikertoimeen ja tukikertoimeen

---

frontend/src/citizen-frontend/messages/MessagesPage.tsx
frontend/src/citizen-frontend/messages/ThreadView.tsx

Ennen muutosta, jos jo näkyviin valitun viestin valitsi viestilistasta uudelleen, kohdistus siirtyi viestilistaan, pois itse viestistä.
Muutoksen jälkeen kohdistus siirtyy viestiin, samalla tavalla kuin viestiä ensimmäisellä kerralla valittaessa.

Viestin uudelleenvalinta kohdistaa sen samoin kuin ensimmäisellä kerralla

---

frontend/src/employee-frontend/components/unit/TabCalendar.tsx

Näytetään ryhmän tapahtumakalenterissa myös vuorohoidon toimintapäivät

---

frontend/src/employee-frontend/components/child-information/Guardians.tsx
frontend/src/employee-frontend/generated/api-clients/pis.ts
frontend/src/employee-frontend/state/child.tsx
frontend/src/lib-common/generated/api-types/pis.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt

Yhdistetään kaksi huoltajien tietojen hakuendpointtia ja korjataan samalla flaky E2E-testi

---

frontend/src/citizen-frontend/messages/MessagesPage.tsx
frontend/src/citizen-frontend/messages/ThreadList.tsx
frontend/src/e2e-test/pages/citizen/citizen-messages.ts
frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Lisätty notifikaatio viestiketjun poistamisesta.
https://github.com/user-attachments/assets/ca277058-0b47-4faf-913c-c246c505a3ae

Viestiketjun poistamisesta indikaatio ruudunlukijalle

---

frontend/src/employee-frontend/components/reports/MealReport.tsx
frontend/src/employee-frontend/components/reports/queries.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Vahvistusdialogi jamix-uudelleenlähetykseen

---

service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportControllerTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt

Kun hakemus viedään pidemmälle kuin lähetetty-tilaan:
1. piilotetaan hakemus huoltajalta
2. ei lähetetä viestiä uudesta hakemuksesta

Lisätty optimointityökaluun mahdollisuus viedä hakemus päätöksen valmisteluun asti

---

service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
service/src/main/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt

csv-tiedoston `lapsen_id`-kentässä voidaan nyt tuoda henkilö-id:n lisäksi hetuja (esim. uudet asiakkaat).

Lisätty optimointityökaluun tuki hetuille

---

frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Kuntalaisen irtisanomistekstin parannus

---

service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt

Henkilökunnan kalenterin kuukausinäkymässä näytettiin virheellisesti palvelutarpeen ylitysmerkintä ja toteumatunnit lapsille, jotka oli sijoitettu pelkkään esiopetukseen, tai muuhun sijoitustyyppin, johon ei vaadita läsnäoloilmoitusten tekemistä etukäteen.

Korjaus pelkkään esiopetukseen sijoitettujen lasten toteumalaskentaan

---

TRADEMARK.md

Tavaramerkkiseloste

---

service/service-lib/src/main/kotlin/fi/espoo/voltti/logging/MdcKey.kt
service/service-lib/src/main/resources/fi/espoo/voltti/logging/logback/default-appender-sanitized.xml
service/service-lib/src/main/resources/fi/espoo/voltti/logging/logback/default-appender.xml
service/src/main/kotlin/fi/espoo/evaka/shared/auth/AuthenticatedUser.kt
service/src/main/kotlin/fi/espoo/evaka/shared/auth/RequestToAuthenticatedUser.kt

Lokitetaan mobiililla pin-kirjautuneen työntekijän id hash

---

service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataController.kt

Ei huomioida päätösluonnoksia hakemusprosessin metatiedoissa

---

frontend/src/lib-common/generated/api-types/webpush.ts
frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsencePushNotificationsTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/absence/AbsencePushNotifications.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
service/src/main/kotlin/fi/espoo/evaka/webpush/PushNotificationCategory.kt
service/src/main/resources/db/migration/V447__push_notification_new_absence.sql
service/src/main/resources/db/migration/V448__push_notification_new_absence_defaults.sql
service/src/main/resources/migrations.txt

Notifikaatio henkilökunnan mobiiliin uusista kuluvan päivän poissaoloista

---

service/evaka-bom/build.gradle.kts

Ei pitäisi vaikuttaa evakaan joka tapauksessa

CVE-2024-38816: Päivitetään springframework

---

TRADEMARK.md

Korjaus tavaramerkkitekstiin

---

frontend/src/citizen-frontend/child-documents/queries.ts
frontend/src/citizen-frontend/children/sections/ChildDocumentsSection.tsx

Lapsen vaihtaminen kuntalaisen näkymässä ei päivittänyt pedagogisia asiakirjoja

---

apigw/src/internal/mobile-device-session.ts

Tietoturvakorjaus mobiilin pin-kirjautumiseen

---

docs/diagrams/src/koski-integration.puml

Lisätään Koski-integraation PlantUML-kaavio

---

service/src/main/kotlin/fi/espoo/evaka/shared/data/DateMap.kt
service/src/main/kotlin/fi/espoo/evaka/shared/data/DateTimeMap.kt
service/src/main/kotlin/fi/espoo/evaka/shared/data/DateTimeSet.kt
service/src/main/kotlin/fi/espoo/evaka/shared/data/RangeBasedMap.kt
service/src/main/kotlin/fi/espoo/evaka/shared/data/RangeBasedSet.kt
service/src/main/kotlin/fi/espoo/evaka/shared/domain/HelsinkiDateTime.kt
service/src/test/kotlin/fi/espoo/evaka/shared/ArbExtensions.kt
service/src/test/kotlin/fi/espoo/evaka/shared/data/DateMapPropertyTest.kt
service/src/test/kotlin/fi/espoo/evaka/shared/data/DateSetPropertyTest.kt
service/src/test/kotlin/fi/espoo/evaka/shared/data/DateTimeMapPropertyTest.kt
service/src/test/kotlin/fi/espoo/evaka/shared/data/DateTimeSetPropertyTest.kt
service/src/test/kotlin/fi/espoo/evaka/shared/data/RangeBasedMapPropertyTest.kt
service/src/test/kotlin/fi/espoo/evaka/shared/data/RangeBasedSetPropertyTest.kt

Parannetaan RangeBasedMap-tietorakenteiden suorituskykyä binäärihaulla

---

service/src/main/resources/WEB-INF/templates/club/decision.properties

Espoo: Kerhopäätöksen tekstimuutos

---

service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt

Näytetään ryhmitystä odottavat lapset vain jos sijoitus on seuraavan kuuden kuukauden aikana

---

service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt

Varda määrää varhaisimman sallitun päättymispäivän Vardaan lähetettävälle datalle. Yleensä se on 1.1.2019, mutta maksutietojen osalta 1.9.2019. eVaka asettaa *edellisen lähdejärjestelmän* lähettämälle datalle päättymispäivän, mikäli se menisi päällekkäin eVakassa olevan datan kanssa. Jos asetettava päättymispäivä olisi pienempi kuin varhaisin Vardan sallima päättymispäivä, eVaka sen sijaan poistaa edellisen lähdejärjestelmän datan.
Tämä prosessi ei toiminut oikein maksutietojen osalta, sillä eVaka ei aiemmin ottanut huomioon maksutietojen erillistä varhaisinta sallittua päättymispäivää. Nyt ottaa.

Käsitellään edellisten Varda-lähdejärjestelmien maksutiedot oikein

---

frontend/src/employee-mobile-frontend/App.tsx
frontend/src/employee-mobile-frontend/child-attendance/AttendanceList.tsx
frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx
frontend/src/employee-mobile-frontend/child-attendance/ChildList.tsx
frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx
frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsent.tsx
frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsentBeforehand.tsx
frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx
frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx
frontend/src/employee-mobile-frontend/child-attendance/actions/MarkReservations.tsx
frontend/src/employee-mobile-frontend/child-info/AttendanceChildPage.tsx
frontend/src/employee-mobile-frontend/child-info/ChildButtons.tsx
frontend/src/employee-mobile-frontend/child-info/ChildInfoPage.tsx
frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildComing.tsx
frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildDeparted.tsx
frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildPresent.tsx
frontend/src/employee-mobile-frontend/child-notes/ChildNotes.tsx
frontend/src/employee-mobile-frontend/messages/NewChildMessagePage.tsx

Lapsen näkymien ei tarvitse olla osa GroupRouteria.

Refaktoroidaan employee-frontendin routet

---

frontend/src/employee-frontend/components/common/Filters.tsx
frontend/src/employee-frontend/components/fee-decisions/FeeDecisionFilters.tsx
frontend/src/employee-frontend/components/income-statements/IncomeStatementFilters.tsx
frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx
frontend/src/employee-frontend/components/invoices/InvoiceFilters.tsx
frontend/src/employee-frontend/components/payments/PaymentFilters.tsx
frontend/src/employee-frontend/components/unit/queries.ts
frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionFilters.tsx
frontend/src/employee-frontend/state/invoicing-ui.tsx
frontend/src/lib-common/generated/api-types/incomestatement.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt
service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt

Vastaavasti kuin muillakin talouden välilehdillä.

Lisätään tuloselvitykset-listaan yksikön mukaan suodatus

---

service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentServiceTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/s3/S3DocumentServiceIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/SoapStackIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClientIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionService.kt
service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentService.kt
service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImage.kt
service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImageController.kt
service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentService.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
service/src/main/kotlin/fi/espoo/evaka/pis/service/MergeService.kt
service/src/main/kotlin/fi/espoo/evaka/s3/DocumentKey.kt
service/src/main/kotlin/fi/espoo/evaka/s3/DocumentService.kt
service/src/main/kotlin/fi/espoo/evaka/s3/S3DocumentService.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClient.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

Parempi S3-rajapinta evaka-servicessä

---

service/src/main/resources/db/migration/V456__legacy_assistance_need_tables.sql

Korjataan rikkinäinen migraatio

---

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Hakemushakunäkymän sarakkeen tekstikorjaus

---

frontend/src/lib-common/uri.spec.ts
frontend/src/lib-common/uri.ts

Lisätään query-parametrien tuki uri-builderiin

---

service/src/main/resources/db/migration/V457__drop_enabled_email_types.sql
service/src/main/resources/migrations.txt

Saa mergetä kunhan https://github.com/espoon-voltti/evaka/pull/5835 on tuotannossa ongelmitta

Poistetaan deprekoitu sarake person.enabled_email_types

---

frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/NewServiceApplicationPage.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Palveluntarpeen muutoshakemuksessa lisätiedot vaaditaan jos ei kuun ensimmäinen päivä

---

frontend/src/employee-frontend/components/unit/TabApplicationProcess.tsx

Nostetaan "käsittelyä odottavat palveluntarpeen muutoshakemukset" osio ylimmäiseksi

---

service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationController.kt
service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

Muut kielet voidaan lisätä myöhemmin, toiminnallisuus ei ole vielä Espoossa käytössä.

Sähköpostinotifikaatio käsitellystä palveluntarpeen muutoshakemuksesta

---

frontend/src/e2e-test/pages/mobile/list-page.ts
frontend/src/e2e-test/specs/6_mobile/child-attendances.spec.ts
frontend/src/employee-mobile-frontend/App.tsx
frontend/src/employee-mobile-frontend/child-attendance/AttendanceList.tsx
frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx
frontend/src/employee-mobile-frontend/child-attendance/ChildList.tsx
frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx
frontend/src/employee-mobile-frontend/child-attendance/ChildNotesSummary.tsx
frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsent.tsx
frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx
frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx
frontend/src/employee-mobile-frontend/child-attendance/queries.ts
frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildComing.tsx
frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildDeparted.tsx
frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
frontend/src/lib-common/generated/api-types/attendance.ts
frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt

next pr:
- remove deprecated endpoint (left for now to avoid errors after deployment on critical functionality)

Usean lapsen sisäänkirjaaminen mobiilissa yhtä aikaa

---

frontend/src/citizen-frontend/applications/editor/unit-preference/SiblingBasisSubSection.tsx
frontend/src/citizen-frontend/applications/editor/validations.ts
frontend/src/citizen-frontend/applications/editor/verification/UnitPreferenceSection.tsx
frontend/src/e2e-test/utils/application-forms.ts
frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx
frontend/src/lib-common/api-types/application/ApplicationFormData.ts
frontend/src/lib-common/generated/api-types/application.ts
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationForm.kt
service/src/main/kotlin/fi/espoo/evaka/application/persistence/club/ClubFormV0.kt
service/src/main/kotlin/fi/espoo/evaka/application/persistence/daycare/DaycareFormV0.kt

Huoltajat usein toivovat, että lapsi pääsisisi samaan kouluun sisaruksen kanssa ja tätä tietoa ei ole muuten helposti saatavilla esiopetuspuolella.

Lisätään esiopetushakemukselle "sisaruksen koulu" lisätieto

---

README.md

Päivitetty yhteystietosähköpostilinkit

Yhteystietosähköpostien päivitys

---

service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt

Tuen tarpeen päätöksen validointikorjaus

---

service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaQueries.kt

Lisätään pois jäänyt sijoitustyyppi Vardaan vietävien listalle.

Lisätään pelkän täydentävän varhaiskasvatuksen sijoitustyyppi Vardaan vietävien listalle

---

frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
frontend/src/lib-common/generated/api-types/attendance.ts
service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt

kun https://github.com/espoon-voltti/evaka/pull/5888 on tuotannossa

Poistetaan deprekoitu endpoint

---

frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx
frontend/src/lib-common/generated/api-types/incomestatement.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt
service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt

Asiakas, Tyyppi ja Muistiinpano -kenttiin.

Lisätään tuloselvitykset-listaan uusia järjestämismahdollisuuksia

---

frontend/src/employee-frontend/components/reports/PreschoolApplicationReport.tsx
frontend/src/lib-components/layout/Table.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

- raportin seliteteksti päivitetty
- raportin sarakeleveyksien parannukset
- raportti ladattavissa csv:nä

Ehdottavan esiopetusken raportin parannuksia

---

frontend/src/e2e-test/pages/employee/messages/messages-page.ts
frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx
frontend/src/employee-frontend/components/messages/types-view.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt

Tavallisista viesteistä ei enää mene kopiota vaikka koskisi koko ryhmää vaan ainoastaan tiedotteista.

Kopiot tiedotteista muille johtajille ja veoille

---

service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsencePushNotificationsTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt

Kuntalainen voi merkitä poissaoloja vain toimintapäiville

---

frontend/src/employee-frontend/components/application-page/ApplicationDecisionsSection.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Lähettämättömän päätöksen tila näkyy hakemuksella väärin

---

frontend/src/employee-frontend/components/child-information/queries.ts
frontend/src/lib-common/query.ts

Dokumenttinäkymä ei lataa uudelleen vaan säilyttää scroll-position välilehteä vaihtaessa

---

service/owasp-suppressions.xml

Ohitetaan CVE joka koskee vain vanhoja Spring-versioita

---

apigw/src/shared/routes/saml.ts
apigw/src/shared/saml/index.ts

Korjattu regressio SAML-kirjautumisen RelayState-validaatiossa

---

service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt

Korjattu yksikön hakemuksien haun käyttöoikeustarkastus

---

frontend/src/e2e-test/specs/5_employee/holiday-period-attendance-report.spec.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/HolidayPeriodAttendanceReportTest.kt
service/src/main/kotlin/fi/espoo/evaka/reports/HolidayPeriodAttendanceReport.kt

Aiemmin lomakyselyraportin `Paikallaolevista tukitoimelliset` sarakkeeseen valittiin varauksen tehneet tuen kertoimen omaavat lapset. Muutoksen jälkeen sarakkeessa näkyy varhaiskasvatuksen tai esiopetuksen tuen tason omaavat varauksen tehneet lapset.

Lomakyselyraportti tarkastelee lapsen tuen tasoa tukitoimellisten näyttämiseksi

---

service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaServiceTest.kt
service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaService.kt

Päällekkäisten työvuorosuunnitelmien tarkistuksessa ei huomioida muiden työntekijöiden suunnitelmia.

Titania työvuorosuunnitelmien tarkistuksen korjaus

---

frontend/src/employee-mobile-frontend/settings/NotificationSettings.tsx
frontend/src/lib-common/generated/api-types/webpush.ts
frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventPushNotificationsTest.kt
service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventController.kt
service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventPushNotifications.kt
service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
service/src/main/kotlin/fi/espoo/evaka/webpush/PushNotificationCategory.kt
service/src/main/resources/db/migration/V466__push_notification_calendar_event_reservation.sql
service/src/main/resources/db/migration/V467__push_notification_calendar_event_reservation_defaults.sql
service/src/main/resources/migrations.txt

Mobiilinotifikaatio varatusta/perutusta keskusteluajasta

---

frontend/src/e2e-test/specs/6_mobile/absences.spec.ts
frontend/src/e2e-test/specs/6_mobile/notes.spec.ts
frontend/src/e2e-test/specs/6_mobile/pin-login.spec.ts

Korjattu testit jotka eivät menneet läpi jos ajoi viikonloppuna

Käytetään mock clockia e2e testeissä

---

apigw/src/shared/logging.ts
apigw/src/shared/middleware/error-handler.ts
apigw/src/shared/routes/saml.ts
apigw/tsconfig.json

Kevennetään SAML-virhelokitusta

---

frontend/src/lib-components/assistance-need-decision/AssistanceNeedPreschoolDecisionReadOnly.tsx

Poistetaan dollarimerkki esiopetuksen tuenpäätökseltä

---

frontend/src/e2e-test/pages/mobile/list-page.ts
frontend/src/e2e-test/specs/6_mobile/child-attendances.spec.ts
frontend/src/employee-mobile-frontend/App.tsx
frontend/src/employee-mobile-frontend/child-attendance/ChildList.tsx
frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx
frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx
frontend/src/employee-mobile-frontend/child-attendance/queries.ts
frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildPresent.tsx
frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
frontend/src/lib-common/generated/api-types/attendance.ts
frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
frontend/src/lib-customizations/espoo/featureFlags.tsx
frontend/src/lib-customizations/types.d.ts
service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/AbsenceCalculator.kt

Usean lapsen lähteneeksi merkitseminen

---

frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceNeedAndDailyServiceTimeSection.tsx
frontend/src/lib-common/generated/api-types/children.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/children/ChildControllerCitizenTest.kt
service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/children/Children.kt

"Palveluntarpeen muutoshakemukset"-osio ei näkynyt ollenkaan kevytkirjautumisella. Nyt näkyy + luontinapissa on lukko-ikoni ilmaisemaan vahvan tunnistautumisen vaatimusta.

Korjataan palveluntarvemuutoshakemuksen näkyvyys kevytkirjautumisella

---

frontend/src/citizen-frontend/applications/editor/service-need/AssistanceNeedSubSection.tsx
frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx
frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
frontend/src/citizen-frontend/applications/editor/unit-preference/PreferredUnitBox.tsx
frontend/src/lib-components/atoms/buttons/button-visuals.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
frontend/src/lib-customizations/espoo/citizen.tsx

Sisältää muutoksia, jotka saattavat vaatia muissa kunnissa muutoksia käännöksiin.
Vanha:
```
applications: {
editor: {
shiftCare: {
instructions2: _INSTRUCTIONS2_,
attachmentsMessage: {
text: _TEXT_,
subTitle: _SUBTITLE_
}
},
assistanceNeeded: _ASSISTANCE_NEEDED_
}
}
```
Muuta muotoon:
```
applications: {
editor: {
shiftCare: {
attachmentsMessage: {
DAYCARE: (
<P>_TEXT_</P>
),
PRESCHOOL: (
<>
<P>_INSTRUCTIONS2_</P>
<P>_TEXT_</P>
</>
)
},
attachmentsSubtitle: _SUBTITLE_,
},
assistanceNeeded: {
DAYCARE: _ASSISTANCE_NEEDED_
PRESCHOOL: _ASSISTANCE_NEEDED_
CLUB: _ASSISTANCE_NEEDED_
}
}
}
```
Muut avaimet voi jättää ennalleen.

Espoon hakemusten tekstipäivityksiä (saattaa rikkoa buildit)

---

frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt

Palveluntarpeen muutoshakemuksen käännökset

---

frontend/src/employee-frontend/components/ApplicationPage.tsx
frontend/src/employee-frontend/components/archive-metadata/MetadataSection.tsx
frontend/src/lib-common/generated/api-types/process.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataController.kt

Näytetään hakemuksen salassapidettävyys metatiedoissa oikein

---

frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts

Poistettu turha employee puolen viestin lähetys ja pidennetty hieman tuota `msDelayPerCharToTypeSlowly` kirjoitusnopeutta

Parannus satunnaisesti epäonnistuvaan istunnon aikakatkaisun e2e testiin

---

frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
service/src/main/resources/application-espoo_evaka.yaml

Palveluohjauksen hakemuksen vastaanottamissähköpostiin muutos
Barninvalskoordinatorer => servicesakkunnig
Ja kaikilla kielillä viestilinkkikorjaukset Jiralapun https://voltti.atlassian.net/browse/EVAKA-4894 mukaan.

Palveluohjauksen hakemuksen viestiin muutos

---

apigw/src/app.ts

Korjataan regressioita apigw:n poluissa

---

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

...jotta se kuvaa toimintaa paremmin.

Päivitetään sijoitusten hahmotteluraportin nimi

---

frontend/src/e2e-test/pages/employee/employees.ts
frontend/src/e2e-test/specs/5_employee/employees.spec.ts
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/resources/dev-data/employees.sql

UUID:n formaatti on `xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx`, missä `x`:t voivat olla mitä tahansa heksadesimaalimerkkejä, mutta `M`:llä ja `N`:llä on erikoismerkitys. Frontin UUID-validaatio tarkastaa nykyään erikoismerkityksen osittain, joten korjataan testidatan UUID:t sellaisiksi että validaatio menee läpi.

Käytetään standardimallisia UUID:itä testidatassa

---

service/evaka-bom/build.gradle.kts
service/owasp-suppressions.xml

Kirjastopäivityksiä joilla korjataan CVE-hälyjä

---

service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobPool.kt

Epäonnistuneet jobit näkyy tämän jälkeen vähän paremmin DataDogissa

Kerrotaan async jobien virheet OpenTelemetrylle

---

frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
frontend/src/citizen-frontend/income-statements/IncomeStatementComponents.tsx
frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
frontend/src/e2e-test/pages/citizen/citizen-child-income.ts
frontend/src/e2e-test/specs/0_citizen/citizen-child-income-statement.spec.ts
frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt

Vain liitteitä ja lisätietoja saa muokata tuloilmoituksen lähetyksen jälkeen

---

service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
service/src/main/kotlin/fi/espoo/evaka/application/DecisionMessageProcessor.kt
service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt

Kun huoltajalle tallennetaan hyväksyttäväksi paikkapäätös, lähetetään sähköposti-ilmoitus.

Lisätään sähköposti-ilmoitus uudesta paikkapäätöksestä

---

frontend/src/e2e-test/pages/employee/units/unit.ts
frontend/src/e2e-test/specs/5_employee/unit-editor.spec.ts
frontend/src/e2e-test/utils/page.ts
frontend/src/employee-frontend/components/unit/queries.ts
frontend/src/employee-frontend/components/unit/unit-details/UnitClosingDateModal.tsx
frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
frontend/src/employee-frontend/generated/api-clients/daycare.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt

Kun yksikölle ollaan lisäämässä päättymispäivämäärää, saattaa muut tiedot olla epävalideja. Tämän avulla ongelman voi kiertää.

Lisätään modaali yksikön päättymispäivän asettamiselle

---

frontend/src/employee-frontend/components/reports/PlacementSketching.tsx
frontend/src/employee-frontend/components/reports/queries.ts

Esim. kahdella tuhannella rivillä käyttöliittymä toimi tahmeasti kun käyttäjä vaihtoi filttereitä.

Korjataan sijoitusten hahmotteluraportin suorituskyky

---

.github/workflows/build.yml

Remove old frontend files bucket

---

frontend/src/employee-frontend/components/employees/EmployeesPage.tsx
frontend/src/employee-frontend/components/employees/queries.ts
frontend/src/lib-common/generated/api-types/pis.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerSearchIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
service/src/main/kotlin/fi/espoo/evaka/shared/auth/UserRole.kt

Käyttäjien haku roolien mukaan

---

service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt

Ehdottavan esiopetuksen hakemuksista on puuttunut viittauket mahdollisiin toisiin huoltajiin. Lisätään k.o. viittaukset

Lisätään toiset huoltajat ehdottavan esiopetuksen hakemuksiin

---

frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx

Englanninkielisen hakemuksen palveluntarpeen nimet käännetty englanniksi

Englanninkielisen hakemuksen palveluntarpeen nimet käännetty englanniksi

---

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageAccountQueries.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

> Sinulle on saapunut uusi viesti eVakaan **lähettäjältä Pupujussikat**. Lue viesti täältä: ...

Lisätään lähettäjän nimi sähköpostinotifikaatioihin eVaka-viesteistä

---

service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt

Espoo: talousprosessien TOS-numerot konfiguraatioon

---

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

Päivitys tuentarpeen päätökset raportin käyttöoikeuksiin

---

service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt

periaatteessa revertoidaan https://github.com/espoon-voltti/evaka/pull/3112 koska tätä logiikkaa ei ilmeisesti enää haluta

Ei enää poisteta tulevia sijoituksia kun luodaan kerhosijoitus

---

service/src/integrationTest/kotlin/fi/espoo/evaka/outofoffice/OutOfOfficeIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

Rebaseissa commit oli hävinnyt, ja tässä palautetaan em. korjaus

Korjaus poissaolojaksojen oikeuksiin

---

frontend/src/e2e-test/specs/5_employee/assistance-need-decisions-report.spec.ts
frontend/src/e2e-test/specs/5_employee/assistance-need-preschool-decision.spec.ts
service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGlobalRole.kt

Päätökset eivät olleet näkyvissä hallinnon roolille
Päätökset ovat saatavilla hallinnon roolille jos he ovat merkattu päätöksen tekijäksi

Korjaus tuen päätösten näkyvyyteen

---

frontend/src/employee-frontend/components/out-of-office/OutOfOfficeEditor.tsx
frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/outofoffice/OutOfOfficeController.kt

Päättymispäivän pitää kuitenkin olla kuluva päivä tai tulevaisuudessa.

Salli johtajan poissaolojaksojen alkaminen menneisyydessä

---

frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
frontend/src/lib-common/generated/api-types/daycare.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/DaycareEditIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/service/DaycareService.kt
service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
service/src/main/resources/db/migration/V485__preschool_manager.sql
service/src/main/resources/migrations.txt

Lisätään yksikön tietoihin ei-pakolliset esiopetuksen johtajan tiedot (nimi, puh., email) ja näytetään ne esiopetuspäätöksillä. Jos niitä ei ole asetettu, käytetään yksikön johtajan tietoja.

Esiopetuksen johtajan tiedot

---

frontend/src/employee-frontend/components/fee-decisions/FeeDecisionFilters.tsx
frontend/src/employee-frontend/components/income-statements/IncomeStatementFilters.tsx
frontend/src/employee-frontend/components/invoices/InvoiceFilters.tsx
frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
frontend/src/employee-frontend/components/payments/PaymentFilters.tsx
frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionFilters.tsx
frontend/src/employee-frontend/state/invoicing-ui.tsx

Siirretään tila takaisin contextiin jotta ei häviä navigoitaessa

Korjaus talouden hakufiltterien säilymiseen

---

frontend/src/employee-frontend/components/common/Filters.tsx

Tehdään hakemisesta nopeampaa nyt kun se ei enää käynnisty automaattisesti

Talous- ja hakemushaut voi käynnistää painamalla entteriä

---

frontend/src/citizen-frontend/messages/ThreadView.tsx

Korjaus pitkien linkkien/sanojen ruudun yli menemiseen kuntalaisen mobiilin viesteissä

---

frontend/webpack.config.js

Laitetaan sentry webpack pluginiin tarkempi lokitus päälle

---

frontend/src/lib-components/assistance-need-decision/AssistanceNeedPreschoolDecisionReadOnly.tsx

Päätös erityisestä tuesta: Poistettu $-merkki Muu laillinen edustaja- tiedon edestä.

Päätös erityisestä tuesta: Poistettu $-merkki Muu laillinen edustaja- tiedon edestä.

---

frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx
frontend/src/lib-common/api-types/application/ApplicationFormData.ts

Poistetaan hakemukselta liittyvän aloituspäivä jos poistetaan liittyvä

---

apigw/src/app.ts

Otettu erilleen alkuperäisestä PR:stä #6218

Lisätään puuttuva mobiilisessioiden refresh-endpoint

---

frontend/src/e2e-test/pages/employee/employees.ts
frontend/src/e2e-test/specs/5_employee/employees.spec.ts
frontend/src/employee-frontend/components/employees/EmployeesPage.tsx
frontend/src/employee-frontend/components/employees/queries.ts
frontend/src/employee-frontend/components/login-page/Login.tsx
frontend/src/employee-frontend/generated/api-clients/pis.ts
frontend/src/employee-frontend/utils/roles.tsx
frontend/src/lib-common/generated/api-types/pis.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt

Uuden palvelutuottajatyöntekijän luonti hetulla

---

service/src/main/kotlin/fi/espoo/evaka/reports/UnitsReport.kt

Ei näytetä suljettuja yksiköitä yksiköt raportilta

---

frontend/src/employee-frontend/components/reports/ChildDocumentsReport.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Näytetään pedagogiset asiakirjat raportilla vain yksiköt joissa toiminto on käytössä

---

service/src/integrationTest/resources/application-integration-test.yaml
service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonalDataControllerCitizen.kt
service/src/main/resources/application-local.yaml

Kuntalaisen kevytkirjautumisen endpointteja ei tarvi erikseen piilottaa, vaan frontin feature flag riittää

Poistetaan turha ympäristömuuttuja

---

frontend/src/employee-frontend/components/placement-tool/PlacementToolPage.tsx
frontend/src/employee-frontend/components/placement-tool/api.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolController.kt
service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt

Tarkistus onko lapsille jo tuotu hakemus ettei samoja hakemuksia luoda uudestaan.

Lisätään ehdottavan esiopetushakemuksen luontiin tarkistus olemassa olevista hakemuksista

---

service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt

Keskustelu suoritetaan aina varsinaisessa yksikössä.

Korjataan keskustelukyselyiden sähköpostimuistus jos lapsi on varahoidossa

---

frontend/src/lib-customizations/espoo/featureFlags.tsx

Palvelutuottajien uusi kirjautuminen Espoon tuotantoon päälle

---

frontend/src/citizen-frontend/personal-details/LoginDetailsSection.tsx
frontend/src/citizen-frontend/personal-details/PersonalDetails.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/WeakCredentialsIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonalDataControllerCitizen.kt

Kuntalaisen kevytkirjautumisen pikkukorjauksia

---

frontend/src/lib-customizations/espoo/featureFlags.tsx

Kuntalaisten uusi kevytkirjautuminen Espoon tuotantoon päälle

---

frontend/src/citizen-frontend/async-rendering.tsx
frontend/src/employee-frontend/components/async-rendering.tsx
frontend/src/employee-mobile-frontend/async-rendering.tsx
frontend/src/lib-components/async-rendering.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Näytetään selkeämpi virhe jos oikeudet puuttuvat

---

frontend/src/employee-frontend/components/unit/TabCalendar.tsx

Korjataan yksikön viikkokalenterin näkyvyystarkistus

---

service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt

Poistetaan huoltajuussuhteet joissa lapsi on jo täysi-ikäinen

---

frontend/src/employee-frontend/components/employees/DaycareRolesModal.tsx
frontend/src/employee-frontend/components/employees/EmployeePage.tsx
frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx
frontend/src/employee-frontend/components/unit/tab-unit-information/acl-modals/AddAclModal.tsx
frontend/src/employee-frontend/components/unit/tab-unit-information/acl-modals/EditAclModal.tsx
frontend/src/employee-frontend/generated/api-clients/daycare.ts
frontend/src/lib-common/generated/api-types/daycare.ts
frontend/src/lib-common/generated/api-types/pis.ts
frontend/src/lib-common/generated/api-types/shared.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerSearchIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
service/src/main/kotlin/fi/espoo/evaka/shared/auth/AclQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
service/src/main/resources/db/migration/V493__acl_end_date.sql
service/src/main/resources/migrations.txt

Luvituksen ennalta asetettu loppupäivä

---

apigw/src/enduser/routes/auth-weak-login.ts
frontend/src/citizen-frontend/personal-details/LoginDetailsSection.tsx
frontend/src/citizen-frontend/personal-details/PersonalDetailsSection.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonalDataControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt

Kirjautumisen pikkukorjauksia, osa 3

---

compose/docker-compose.yml

Päivitettiin s3-mock, jotta saadaan S3 käynnistymään myös uusimmalla M4 prossulla.

Päivitys s3-mock versiolle

---

frontend/src/citizen-frontend/calendar/DayView.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Lisätään muokkaa useampaa päivää -linkki kuntalaisen kalenterin päivämodaaliin

---

frontend/src/citizen-frontend/calendar/calendar-elements.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Näytetään kuntalaisen kalenterissa ilmoittamattomat poissaolot

---

frontend/src/employee-frontend/components/reports/Raw.tsx
frontend/src/lib-common/generated/api-types/reports.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/RawReportControllerTest.kt
service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt

Kotikunta on kunnan suomen- tai ruotsinkielinen nimi henkilön kielestä riippuen.

Kotikunta-tieto raakaraportille

---

frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx
frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx
frontend/src/citizen-frontend/applications/editor/validations.ts
frontend/src/citizen-frontend/applications/editor/verification/ApplicationVerificationView.tsx
frontend/src/lib-customizations/types.d.ts

Tällä hetkellä järjestelmä vain kehottaa käyttäjää lisäämään liitteet.

Lisätään mahdollisuus konfiguroida hakemuksen liitteet pakollisiksi

---

service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt

Korjaus virheeseen siirrettäessä hakemusta sijoitettaviin

---

frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReport.tsx
frontend/src/lib-common/generated/api-types/assistanceneed.ts
frontend/src/lib-common/generated/api-types/reports.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecision.kt
service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedDecisionsReport.kt

Lisätään filttereitä tuen päätökset raporttiin

---

frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
frontend/src/employee-mobile-frontend/messages/ThreadView.tsx

Korjataan pitkän linkin rivitys viesteissä työntekijäpuolella

---

frontend/src/e2e-test/specs/5_employee/application-details.spec.ts
frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt

Hakemus on tarkistettava jos huoltajat eivät ole sopineet hakemisesta yhdessä

---

compose/db/Dockerfile

Poistetaan samalla käyttämättömän pgextwlist-laajennuksen kääntäminen.

Päivitetään Postgres versioon 17 composessa

---

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/NonSsnChildrenReportTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
service/src/main/kotlin/fi/espoo/evaka/varda/UriUtils.kt
service/src/main/kotlin/fi/espoo/evaka/varda/Varda.kt
service/src/main/kotlin/fi/espoo/evaka/varda/VardaClient.kt
service/src/main/kotlin/fi/espoo/evaka/varda/VardaQueries.kt
service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt

- Uudelleennimetään Varda-integraation tiedostoja ja luokkia
- Siivotaan koodia
- Ajetaan Varda-päivitys oletuksena joka päivä klo 23

Vanhojen Varda-integraatioiden poiston viimeistely

---

service/gradle.properties
service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentQueriesTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentsControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ManualDuplicationReportTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/shared/auth/AclIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AttachmentAccessControlTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/test/TestData.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
service/src/main/resources/db/migration/V497__application_primary_preferred_unit.sql
service/src/main/resources/migrations.txt

Lisätään generated-sarake ja foreign key constraint hakemuksen ykkösyksikölle

---

frontend/src/citizen-frontend/calendar/CalendarNotifications.tsx
frontend/src/citizen-frontend/calendar/holiday-modal/FixedPeriodSelectionModal.tsx
frontend/src/citizen-frontend/calendar/holiday-modal/OpenRangesSelectionModal.tsx
frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts
frontend/src/lib-common/generated/api-types/holidayperiod.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt

Mikäli lapsella on päättynyt sijoitus tai päätyy kesken jonkun valittavan jakson, huoltaja ei voi valita koko jaksoa.

Korjataan poissaolokyselyn valittavat jaksot

---

frontend/src/e2e-test/pages/employee/messages/messages-page.ts
frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts
frontend/src/employee-frontend/components/Header.tsx
frontend/src/employee-frontend/components/messages/GroupMessageAccountList.tsx
frontend/src/employee-frontend/components/messages/MessageBox.tsx
frontend/src/employee-frontend/components/messages/MessageContext.tsx
frontend/src/employee-frontend/components/messages/MessageEditor.tsx
frontend/src/employee-frontend/components/messages/MessagesPage.tsx
frontend/src/employee-frontend/components/messages/Sidebar.tsx
frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
frontend/src/employee-frontend/components/messages/ThreadList.tsx
frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx
frontend/src/employee-frontend/components/messages/types-view.ts
frontend/src/employee-frontend/generated/api-clients/messaging.ts
frontend/src/lib-common/generated/api-types/messaging.ts
frontend/src/lib-common/generated/api-types/shared.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/Audit.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

Kansiot täytyy luoda kantaan käsin jotta feature tulee käyttöön (insert into message_thread_folder ...)

Palveluohjauksen viestien kansiointi

---

frontend/src/citizen-frontend/messages/MessageEditor.tsx
frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt

Kuntalainen voi lähettää useaa lasta koskevan viestin vaikka lapset olisivat saman yksikön eri ryhmissä

---

service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
service/src/main/kotlin/fi/espoo/evaka/reports/PreschoolApplicationReport.kt
service/src/main/resources/db/migration/R__application_view.sql

Otetaan PR:ssä #6337 lisätty sarake käyttöön kyselyissä.

Käytetään hakemusten generoitua saraketta SQL-kyselyissä

---

service/src/main/kotlin/fi/espoo/evaka/reports/SextetReport.kt

Kuusikkoraportin suorituskykykorjaus

---

frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/lib-common/generated/api-types/invoicing.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueriesTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueriesTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/FinanceDecisionUtils.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Incomes.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt

Uusi logiikka koskee vain 1.3.2025 tai myöhemmin alkavia päätöksiä

Uusi tulotieto aiheuttaa aina uuden maksu/arvopäätöksen

---

service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt
service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt

Korjataan päivälapset käyttö- ja täyttöasteet raportilla

---

frontend/src/citizen-frontend/login/WeakLoginFormPage.tsx
frontend/src/citizen-frontend/personal-details/LoginDetailsSection.tsx

Korjataan bugi jonka takia salasanassa ei voinut olla välilyöntejä alussa tai lopussa

---

frontend/src/employee-frontend/components/archive-metadata/MetadataSection.tsx
frontend/src/lib-common/generated/api-types/process.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataController.kt

Metadataprosessien nimet

---

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt

Ei lasketa arkistoituja viestejä lukemattomien viestien määrään

---

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt

Jos lapsi aloitti kesken kuun sopimuspäiväpalveluntarpeella, ja tätä edeltävällä ajalla oli ei-laskutettava sijoitus (kuten kerho), sopimuspäivien ylityspäivät laskettiin väärin.

Korjaus laskun muodostukseen sopimuspäiväläisen aloittaessa kesken kuun

---

frontend/src/employee-frontend/components/reports/CsvFormation.spec.ts
frontend/src/employee-frontend/components/reports/ExceededServiceNeeds.tsx
frontend/src/employee-frontend/components/reports/Occupancies.tsx
frontend/src/employee-frontend/components/reports/ReportDownload.tsx

Käytetyn kirjaston CSV-muodostuksessa on bugi, joka estää lainausmerkin `"` poikkeuttamisen ja rikkoo CSV-rakenteen lainausmerkin omaavassa sisällössä.
Ongelma vaikutti kaikkeen käyttöliittymän kautta ladattavaan CSV-sisältöön.

Korjattu lainausmerkkien käsittely raportti-CSV:n muodostuksessa

---

service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/shared/domain/OperationalDaysIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/shared/domain/OperationalDays.kt

Siten huoltaja voi mm. ilmoittaa poissaoloja viikonlopuille vaikka oma yksikkö ei olisi silloin muutenkaan auki.

Satunnaisessa vuorohoidossa jokainen päivä on toimintapäivä

---

frontend/src/citizen-frontend/decisions/decisions-page/Decisions.tsx

Järjestetään kuntalaisen talouspäätökset ensisijaisesti voimassaoloajan mukaan

---

frontend/src/employee-frontend/components/unit/TabApplications.tsx
frontend/src/employee-frontend/components/unit/TabWaitingConfirmation.tsx
frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx

UI-viilauksia yksikkösivun notifikaatiopalloihin

---

frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx

Piilotetaan toimimaton mahdollisuus siirtää lähetetty viesti kansioon

---

frontend/src/citizen-frontend/generated/api-clients/application.ts
frontend/src/citizen-frontend/generated/api-clients/assistanceneed.ts
frontend/src/citizen-frontend/generated/api-clients/attachment.ts
frontend/src/citizen-frontend/generated/api-clients/childimages.ts
frontend/src/citizen-frontend/generated/api-clients/document.ts
frontend/src/e2e-test/generated/api-clients.ts
frontend/src/employee-frontend/generated/api-clients/aromi.ts
frontend/src/employee-frontend/generated/api-clients/assistanceneed.ts
frontend/src/employee-frontend/generated/api-clients/attachment.ts
frontend/src/employee-frontend/generated/api-clients/decision.ts
frontend/src/employee-frontend/generated/api-clients/document.ts
frontend/src/employee-frontend/generated/api-clients/invoicing.ts
frontend/src/employee-frontend/generated/api-clients/pis.ts
frontend/src/employee-mobile-frontend/generated/api-clients/attachment.ts
frontend/src/employee-mobile-frontend/generated/api-clients/childimages.ts
frontend/src/lib-common/uri.spec.ts
frontend/src/lib-common/uri.ts
service/codegen/src/main/kotlin/evaka/codegen/api/ApiFiles.kt

Base urlin kauttaviivoja ei saa escapeta

Korjaus latauslinkkeihin

---

frontend/src/e2e-test/pages/employee/employees.ts
frontend/src/e2e-test/specs/5_employee/employees.spec.ts
frontend/src/employee-frontend/components/employees/EmployeeList.tsx
frontend/src/employee-frontend/components/employees/queries.ts
frontend/src/lib-common/generated/api-types/pis.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/vtjclient/VtjClientServiceTest.kt
service/src/main/kotlin/fi/espoo/evaka/pis/Employee.kt
service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
service/src/main/resources/db/migration/V504__nullable_last_login.sql
service/src/main/resources/migrations.txt

Pääkäyttäjä voi poistaa vielä kirjautumattoman hetullisen palveluntuottajakäyttäjän

---

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageReceiversIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt

Ennen muutosta lapsi näkyi aloittavien listalla myös silloin, kun sijoitus muuttui, mutta ryhmä pysyi samana. Muutoksen jälkeen lapsi näytetään aloittavien ryhmässä vain silloin, kun lapsi vaihtaa sellaiseen ryhmään, jossa lapsi ei ennestään ollut.

Muutos henkilökunnan viestinnän vastaanottajalistalla näkyviin sijoitusta muuttaviin lapsiin

---

service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/LinkityServiceTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/MockLinkityClient.kt
service/src/main/kotlin/fi/espoo/evaka/linkity/Linkity.kt
service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityClient.kt
service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityQueries.kt
service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityService.kt

Toteutus tämän speksin pohjalta: https://linkity-dev-agent.frendsapp.com/api/docs/index.html?urls.primaryName=Linkity%20eVaka%20API

Espoon työaikakirjausten lähetys Linkityyn

---

frontend/src/citizen-frontend/applications/editor/contact-info/GuardianSubSection.tsx
frontend/src/e2e-test/pages/citizen/citizen-applications.ts
frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt

Jos käyttäjällä on jo vahvistettu sähköpostiosoite, ei sallita sen muuttamista hakemuksen kautta

---

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt

Korjaa #6475:ssä tulleen bugin

Lähetetään tulotietomuistutukset palveluseteliyksiköiden asiakkaille

---

frontend/src/citizen-frontend/generated/api-clients/incomestatement.ts
frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
frontend/src/citizen-frontend/income-statements/queries.ts
frontend/src/lib-common/generated/api-types/incomestatement.ts
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/Audit.kt
service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

Näytetän kuntalaiselle varoitus jos puoliso ei ole koskaan toimittanut tuloselvitystä

---

service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt

Järjestetään laskut päämiehen sivulla uusimmasta vanhimpaan

---

frontend/src/employee-frontend/components/unit/TabCalendar.tsx

Helpotetaan yksikkökalenterin ajanjakson valitsemista

---

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

huom: tarkistakaa onko sääntö yliajettu kuntakohtaisesti eli tarvitseeko muuttaa myös sinne

Ei-kunnallisissa yksiköissä vain pääkäyttäjä voi luvittaa henkilökuntaa yksiköihin

---

frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/generated/api-types.ts
frontend/src/e2e-test/pages/employee/documents/document-templates.ts
frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
frontend/src/employee-frontend/components/archive-metadata/MetadataSection.tsx
frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
frontend/src/lib-common/generated/api-types/document.ts
frontend/src/lib-common/generated/api-types/process.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/document/DocumentTemplateIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateQueries.kt
service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentService.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/DocumentHtmlGenerator.kt
service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataController.kt
service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/resources/db/migration/V505__confidentiality_duration_and_basis.sql
service/src/main/resources/migrations.txt
service/src/test/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceTest.kt

Salassapitoaika ja -peruste

---

service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/LinkityServiceTest.kt
service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
service/src/main/kotlin/fi/espoo/evaka/espoo/EspooAsyncJob.kt
service/src/main/kotlin/fi/espoo/evaka/espoo/EspooScheduledJobs.kt
service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/config/EnvConfig.kt

Espoon työvuorojen haun ajastus (ei vielä käytössä)

---

frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
frontend/src/citizen-frontend/income-statements/ChildIncomeStatementView.tsx
frontend/src/citizen-frontend/income-statements/IncomeStatementAttachments.tsx
frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
frontend/src/e2e-test/pages/citizen/citizen-income.ts
frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
frontend/src/employee-frontend/components/IncomeStatementPage.tsx
frontend/src/lib-common/generated/api-types/incomestatement.ts
frontend/src/lib-common/income-statements/body.ts
frontend/src/lib-common/income-statements/form.ts
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt

Korjataan samalla lapsen tuloselvityksen liitteiden näyttö ja lisäys.

Siirretään yrittäjyyden kysyminen alemmas, ei kysytä pää-/sivutoimisuutta

---

frontend/src/employee-frontend/components/finance-basics/ServiceNeedItem.tsx
frontend/src/employee-frontend/components/finance-basics/VoucherValueEditor.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceBasicsController.kt

Korjauksia palveluseteliarvojen editoriin

---

frontend/src/citizen-frontend/generated/api-clients/messaging.ts
frontend/src/citizen-frontend/messages/ThreadView.tsx
frontend/src/citizen-frontend/messages/queries.ts
frontend/src/e2e-test/pages/citizen/citizen-header.ts
frontend/src/e2e-test/pages/citizen/citizen-messages.ts
frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
service/src/main/kotlin/fi/espoo/evaka/Audit.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt

Kohdistuu viestiketjun viimeisimpään vastaanotettuun viestiin.

Kuntalainen voi merkitä viestin lukemattomaksi

---

service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
service/src/main/resources/db/migration/V507__replaced_invoice_id_unique.sql
service/src/main/resources/migrations.txt

Tätä kautta toivottavasti selviää jatkossa mistä niitä tulee.

Estetään hyvityslaskuduplikaattien muodostuminen

---

service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt

Poistetaan vanhan testauskoodin jäänne

---

frontend/src/e2e-test/pages/employee/reports.ts
frontend/src/e2e-test/specs/5_employee/sextet-report.spec.ts
frontend/src/employee-frontend/components/reports/Sextet.tsx
frontend/src/employee-frontend/components/reports/queries.ts
frontend/src/employee-frontend/generated/api-clients/reports.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/SextetReportTest.kt
service/src/main/kotlin/fi/espoo/evaka/reports/SextetReport.kt

Lisää myös taulukon loppuun summarivin.

Lisätään kuusikkoraporttiin suodatus yksikön järjestämismuodolla

---

service/src/main/kotlin/fi/espoo/evaka/shared/sftp/SftpClient.kt

Kirjasto toimii hieman eri tavalla riippuen siitä onko palvelimen portti 22 vai ei (jos portti on 22 -> alias on pelkkä host, muuten `[host]:port`. Tämän muutoksen myötä alias on aina `host:port`.

Korjataan SFTP-yhteys

---

apigw/src/enduser/mapRoutes.ts
frontend/src/citizen-frontend/map/api.ts
frontend/src/e2e-test/generated/api-clients.ts
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

Digitransit APIn v2 käyttöönotto

---

frontend/src/employee-frontend/components/reports/TampereRegionalSurvey.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Lisää tiedon tilastointipäivästä kunkin arvon CSV-otsakkeeseen. Näin tuloksia on helpompi vertailla muiden raportointilähteiden kanssa.

Lisätty tilastointipäiväykset seutuselvitysraportin tuloksiin

---

frontend/src/employee-frontend/components/reports/Applications.tsx
frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReport.tsx
frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx
frontend/src/employee-frontend/components/reports/ChildAgeLanguage.tsx
frontend/src/employee-frontend/components/reports/ChildrenInDifferentAddress.tsx
frontend/src/employee-frontend/components/reports/Decisions.tsx
frontend/src/employee-frontend/components/reports/DuplicatePeople.tsx
frontend/src/employee-frontend/components/reports/EndedPlacements.tsx
frontend/src/employee-frontend/components/reports/FamilyConflicts.tsx
frontend/src/employee-frontend/components/reports/FamilyDaycareMealCount.tsx
frontend/src/employee-frontend/components/reports/Invoices.tsx
frontend/src/employee-frontend/components/reports/ManualDuplicationReport.tsx
frontend/src/employee-frontend/components/reports/MissingServiceNeed.tsx
frontend/src/employee-frontend/components/reports/Occupancies.tsx
frontend/src/employee-frontend/components/reports/PartnersInDifferentAddress.tsx
frontend/src/employee-frontend/components/reports/PlacementCount.tsx
frontend/src/employee-frontend/components/reports/PlacementGuarantee.tsx
frontend/src/employee-frontend/components/reports/PresenceReport.tsx
frontend/src/employee-frontend/components/reports/ServiceNeeds.tsx
frontend/src/employee-frontend/components/reports/VoucherServiceProviderUnit.tsx
frontend/src/employee-frontend/components/reports/queries.ts

`useQueryResult` ja `renderResult` käyttöön useimmissa raporteissa.

Modernisoidaan raporttien fronttikoodia

---

frontend/src/e2e-test/pages/mobile/staff-page.ts
frontend/src/e2e-test/specs/6_mobile/planned-staff-attendances.spec.ts
frontend/src/employee-mobile-frontend/App.tsx
frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx
frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPlannedAttendancesPage.tsx
frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts

Työntekijän omat tulevat vuorot
Päivityksiä yksikön tulevat vuorot listaan

Tulevat työvuorot mobiiliin - osa 2

---

frontend/src/lib-customizations/espoo/featureFlags.tsx

Espoo: enabloidaan usean lapsen lähteneeksi merkitseminen

---

frontend/src/employee-frontend/components/messages/MessageEditor.tsx

Lisätään mahdollisuus viestiä koulunkäyntiä lykänneille, vuotta vanhemmille lapsille.

Massaviestintään mahdollisuus lähettää viesti vanhemmille lapsille

---

service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt

Ennen muutosta, jos lähetettiin viesti koko yksikölle, viesti lähetettiin myös lapsille, jotka on sijoitettu yksikköön, mutta joita ei ole vielä ryhmitetty. Näitä lapsia ei kuitenkaan näytetty vastaanottajien valintapuussa. Korjauksen jälkeen viesti lähetetään vain ryhmitetyille lapsille, yhdenmukaisesti sen kanssa mitä vastaanottajien valintapuussa näkyy.
Kunnan tiedotteita lähetettäessä toiminnassa ei ole muutosta. Vastaanottajien valintapuussa ei näytetä yksittäisiä lapsia, ja viestien lähetys tehdään edelleen myös sijoitetuille mutta vielä ryhmittämättömille lapsille.

Korjaus viestien lähettämiseen ryhmittämättömille lapsille

---

frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Korjataan hakemustekstin lihavointi

---

service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt

Korjaus Nekku erikoisruokavalion mappaukseen

Korjaus Nekku erikoisruokavalion mappaukseen

---

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Selkeämpi johtajalle mitä https://github.com/espoon-voltti/evaka/pull/6529 listaa.

Muutetaan yksikön siirtohakemusten listauksen otsikko

---

service/gradle/libs.versions.toml

Spring-boot päivitys 3.4.1 -> 3.4.3

Spring-boot päivitys 3.4.1 -> 3.4.3

---

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FinanceDecisions.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/FeeDecisionGeneratorV2.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/SharedLogic.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/VoucherValueDecisionGeneratorV2.kt
service/src/test/kotlin/fi/espoo/evaka/invoicing/service/generator/FeeDecisionGeneratorV2Test.kt

Korjaus tulotietovertailusta syntyviin turhiin luonnoksiin

---

frontend/src/citizen-frontend/calendar/holiday-modal/OpenRangesSelectionModal.tsx
frontend/src/citizen-frontend/calendar/holiday-modal/RangesSelector.tsx

- Korjattu liian tarkka päivämäärävalintojen validointi, jotta myös ensimmäinen valinta toimii  
- Levennetty modaalia, jotta päivämäärän valinnan komponentit mahtuvat aukeamaan paremmin
- Lisätty päivämäärävalitsimiin alustus nykyisen valinnan tai kyselykauden aloituksen mukaan

Korjaus avoimen välin poissaolokyselyyn vastaamiseen

---

frontend/src/citizen-frontend/messages/ThreadList.tsx
frontend/src/citizen-frontend/messages/ThreadView.tsx
frontend/src/e2e-test/pages/citizen/citizen-messages.ts
frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
frontend/src/e2e-test/specs/7_messaging/municipal-messaging.spec.ts
frontend/src/e2e-test/specs/7_messaging/out-of-office.spec.ts
frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts

Korjaus kuntalaisen viestinnän nappien asetteluun

---

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/TampereRegionalSurveyTest.kt
service/src/main/kotlin/fi/espoo/evaka/reports/TampereRegionalSurvey.kt

Raporttiin on testikäytössä saatu palautetta ja tilastoitavien kohteiden keräämistä on tarkennettu lähemmäksi aiempaa manuaalista käytäntöä.
Kuukausittaiset lukemat:
- rajataan kuukausittaisen perhepäivähoidon tarkastelu vain kunnallisiin toimijoihin
- rajataan perhepäivähoito pois kuukausittaisen osa/täysiaikaisen varhaiskasvatuksen tarkastelusta
Ikäjaottelut:
- otetaan täydentävä varhaiskasvatus huomioon vain, jos se järjestetään vaka-yksikössä
Vuosittaiset lukemat:
- rajataan täydentävä varhaiskasvatus tuen lukemien ulkopuolelle
Testitapauslisäykset:
- kaikki muutetut poiminnat
- vuorohoidon hoitopäivälaskennan lisätesti päivälasten osalta

Seutuselvitysraportin muutoksia

---

frontend/src/employee-frontend/components/unit/tab-groups/groups/group/GroupUpdateModal.tsx

Ryhmälle voi nyt valita tyhjän Nekku-asiakasnumeron sen jälkeen kun ryhmän Nekku-yksikkö on jo aiemmin valittu

Mahdollistetaan Nekku-asiakasnumeron poistaminen ryhmältä

---

frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
frontend/src/employee-frontend/components/child-information/person-details/queries.ts
frontend/src/employee-frontend/generated/api-clients/nekku.ts
frontend/src/lib-common/generated/api-types/daycare.ts
frontend/src/lib-common/generated/api-types/nekku.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/daycare/ChildQueries.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/ChildController.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuController.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
service/src/main/resources/db/migration/V512__nekku_diet.sql
service/src/main/resources/migrations.txt

Jos Nekku-integraatio on kytketty päälle, lapsen tiedoissa näkyy valitsin Nekku-ruokatilauksissa käytettävälle lapsen ruokavaliolle.

Lisätty lapsen tietoihin valitsin Nekku-ruokatilausten ruokavaliolle

---

frontend/src/e2e-test/pages/mobile/child-messages-page.ts
frontend/src/e2e-test/pages/mobile/child-page.ts
frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
frontend/src/employee-mobile-frontend/App.tsx
frontend/src/employee-mobile-frontend/child-info/ChildButtons.tsx
frontend/src/employee-mobile-frontend/common/ChildNameBackButton.tsx
frontend/src/employee-mobile-frontend/generated/api-clients/messaging.ts
frontend/src/employee-mobile-frontend/messages/ChildMessagesPage.tsx
frontend/src/employee-mobile-frontend/messages/MessagesPage.tsx
frontend/src/employee-mobile-frontend/messages/ReceivedThreadsList.tsx
frontend/src/employee-mobile-frontend/messages/ThreadView.tsx
frontend/src/employee-mobile-frontend/messages/queries.ts
frontend/src/employee-mobile-frontend/pairing/components.tsx
frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt

Lapseen liittyvät viestit henkilökunnan mobiilissa

---

service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt

Korjataan puuttuva import

---

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FinanceDecisions.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Incomes.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/FeeDecisionGeneratorV2.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/SharedLogic.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/VoucherValueDecisionGeneratorV2.kt
service/src/test/kotlin/fi/espoo/evaka/invoicing/service/generator/FeeDecisionGeneratorV2Test.kt

Muutetaan logiikkaa jotta vältetään siirtymäaikana turhat luonnokset

Korjaus tulojen vertailuun talouspäätöksissä

---

frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx

Näytetään yksikön ruoka-ajat myös Nekku integraation ollessa aktiivinen

Näytetään yksikön ruoka-ajat myös Nekku integraation ollessa aktiivinen

---

service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuController.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt

Rajoitetaan @JsonValue -annotaation käyttö Nekku-APIn käyttämiin enum-luokkiin ja erotetaan niistä vastaavat eVakan sisäiset enum-luokat joista voidaan generoida enum-tyypit myös front endiin

Jaa Nekku-integraation enum-luokat APIn ja eVakan käyttämiin enumeihin

---

frontend/src/employee-frontend/state/invoicing-ui.tsx

Yksikköjä yritettiin hakea ennen kirjautumista

Korjaus regressioon talouden kyselyissä

---

frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts

"Sähköposti vaatii vielä speksin!"

Lisätään testi että täytettävästä lomakkeesta lähtee sähköpostiviesti

---

frontend/src/lib-common/generated/api-types/nekku.ts
service/codegen/src/main/kotlin/evaka/codegen/api/TsRepresentation.kt
service/codegen/src/test/kotlin/evaka/codegen/api/TsRepresentationTest.kt

Codegen kieltää JsonValue-annotoitujen enumien käytön API:n enum-tyypeissä

---

service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/LinkityServiceTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/MockLinkityClient.kt
service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
service/src/main/kotlin/fi/espoo/evaka/linkity/Linkity.kt
service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityClient.kt
service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityQueries.kt
service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityService.kt

Tekninen: Linkity-rajapinnan muutosten huomioiminen

---

frontend/src/employee-frontend/components/application-page/ApplicationNoteBox.tsx
frontend/src/employee-frontend/components/application-page/ApplicationPage.tsx

Korjataan hakemuksen ja muistiinpanojen resetoituminen palveluohjaajan vaihtaessa selaimen välilehteä

---

frontend/src/e2e-test/generated/api-types.ts
frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
frontend/src/lib-common/generated/api-types/document.ts
frontend/src/lib-common/generated/api-types/shared.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/document/DocumentTemplateIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/DocumentHtmlGenerator.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/kotlin/fi/espoo/evaka/shared/domain/Languages.kt
service/src/main/kotlin/fi/espoo/evaka/shared/domain/UiLanguage.kt
service/src/main/resources/db/migration/V515__document_template_language_en.sql
service/src/main/resources/migrations.txt
service/src/test/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceTest.kt

Aiemmin oli valittavissa vain suomi ja ruotsi.

Lisätään lomakepohjille englannin kielen tuki

---

service/src/main/kotlin/fi/espoo/evaka/aromi/AromiService.kt

Lisää normaalitoimintaa kuvaavaa lokitusta Aromi-integraation keräykseen ja lähetykseen.

Lisätään lokitusta Aromi-integraatioon

---

service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt

https://github.com/espoon-voltti/evaka/pull/6593 sisältämä korjaus aiheutti uuden bugin

Korjaus kuntalaiselle näkyvään hakemuksen tilaan

---

frontend/src/employee-frontend/components/reports/Units.tsx
frontend/src/lib-common/generated/api-types/reports.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/reports/UnitsReport.kt

Lisätään yksikköraportille yksikön laskennallinen kapasiteetti

---

frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx

Lasketaankin ikä tänään eikä ryhmityksen alkupäivänä

Korjataan ryhmää odottavien lasten ikäsarake (v2)

---

frontend/src/e2e-test/pages/employee/documents/child-document.ts
frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
frontend/src/lib-components/document-templates/question-descriptors/CheckboxGroupQuestionDescriptor.tsx

Näytetään sama järjestys kuin lomake-editorilla, vaikka vastaus olisikin datassa eri järjestyksesä.

Korjataan asiakirjan monivalinnan vastausten järjestys

---

frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
frontend/src/lib-common/generated/api-types/daycare.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/daycare/ChildQueries.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/ChildController.kt
service/src/main/resources/db/migration/V517__nekku_eats_breakfast.sql
service/src/main/resources/migrations.txt

Nekku-integraation ollessa kytkettynä lisätty lapsen tietoihin checkbox tiedolle syökö lapsi päiväkodissa aamiaista, vaikka olisikin aamiaisaikaan ilmoitettu läsnäolevaksi.

Lisätään lapsen tietoihin Nekku-integraation ei syö aamiaista -tiedon syöttö

---

frontend/src/citizen-frontend/income-statements/ChildrenIncomeStatements.tsx
frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Piilotetaan kuntalaisen lasten tulotieto-osio jos lapsia ei ole

---

frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/generated/api-types.ts
frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt

Luo 1 viikon ruokatilaukset eVakasta Nekkuun

Luo 1 viikon ruokatilaukset eVakasta Nekkuun

---

frontend/src/e2e-test/pages/employee/finance/finance-page.ts
frontend/src/e2e-test/specs/4_finance/invoices.spec.ts

Poistettiin ylimääräinen steppi testitilanteen setupissa joka failaa ajoittain

Korjattu e2e-testi laskuille

---

frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/generated/api-types.ts
frontend/src/e2e-test/specs/0_citizen/citizen-pedagogical-documents.spec.ts
frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts
frontend/src/e2e-test/specs/5_employee/child-information-assistance.spec.ts
frontend/src/e2e-test/specs/5_employee/pedagogical-document.spec.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/LinkityServiceTest.kt
service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentController.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt

Korjaukset ovat osittain hakuammuntaa, koska kaikkia virheitä ei saa toistumaan lokaalissa ympäristössä edes kelloa siirtämällä tai aikavyöhykettä vaihtamalla. Mutta testit ovat nyt parempia joka tapauksessa!

Korjataan ajohetken päivämäärästä tai kellonajasta riippuvia testejä

---

frontend/src/e2e-test/pages/mobile/staff-page.ts
frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx
frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPlannedAttendancesPage.tsx
frontend/src/lib-common/generated/api-types/attendance.ts
service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt

Jos työvuoroon liittyy kommentti, näytetään se mobiilisovelluksessa:
- henkilökunnan tulevissa työvuoroissa
- yksittäisen henkilön tulevissa työvuoroissa
- yksittäisen henkilön kuluvan päivän näkymässä info-pallon takana

Näytetään työvuoron kommentti

---

service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt

Luodaan joka päivä tarkennetut Nekku-tilaukset seuraavalle päivälle

Luodaan joka päivä tarkennetut Nekku-tilaukset seuraavalle päivälle

---

frontend/src/employee-frontend/components/document-templates/template-editor/DocumentTemplatesPage.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Lisätään filttereitä lomakepohjat sivulle

---

service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/resources/db/migration/V518__more_child_document_constraints.sql
service/src/main/resources/migrations.txt

Lisätään constraintteja child_document tauluun

---

frontend/src/employee-frontend/components/messages/types-view.ts

Järjestetään talouden viestinnän näkymät samaan järjestykseen muiden viestintätyyppien kanssa viestit-sivun sivupalkissa.

Talouden viestinnän näkymien uudelleenjärjestys

---

service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/DbTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/JdbiExtensionsTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/JdbiReflectionTest.kt
service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
service/src/main/kotlin/fi/espoo/evaka/shared/db/Search.kt

Viides ja viimeinen osa poistaa lopulta vanhan SQL-kysely-API:n.

Käytetään uutta SQL query API:a, osa 5

---

frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/generated/api-types.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

Nekku: Lapsi ei syö aamupalaa vähennykset tilauksesta. Mukaan myös 10 prosentin vähennys normaaleista tilauksista.

Nekku: Lapsi ei syö aamupalaa vähennykset tilauksesta. Mukaan myös 10 prosentin vähennys normaaleista tilauksista.

---

frontend/src/citizen-frontend/calendar/CalendarNotifications.tsx
frontend/src/citizen-frontend/calendar/queries.ts
frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
frontend/src/citizen-frontend/child-documents/queries.ts
frontend/src/citizen-frontend/children/sections/ChildDocumentsSection.tsx
frontend/src/citizen-frontend/generated/api-clients/document.ts
frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts
frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
frontend/src/lib-common/generated/api-types/document.ts
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizenIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt

Lomakkeen lähetyksen jälkeen palataan automaattisesti kalenterisivulle ja näytetään ilmoitus onnistuneesta tallennuksesta.

Lisätään kalenterisivulle ilmoitus vastaamattomasta lomakkeesta

---

frontend/src/e2e-test/pages/employee/reports.ts
frontend/src/e2e-test/specs/5_employee/ended-placements-report.spec.ts
frontend/src/employee-frontend/components/reports/EndedPlacements.tsx
frontend/src/lib-common/generated/api-types/reports.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/reports/EndedPlacementsReport.kt

lisätään lapsen syntymäaika ja jatkaa varhaiskasvatuksessa yksikön nimi raporttiin

Varhaiskasvatuksessa lopettavien lasten raportin laajennus

---

frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
frontend/src/lib-customizations/espoo/employee.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/espoo/EspooActionRuleMapping.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

Oikeuden voi määrittää kuntakohtaisella kustomisaatiolla

Laskujen uudelleen lähetys on oletuksena estetty ja näytetään selkeämpi varoitus

---

apigw/yarn.lock

Reverts espoon-voltti/evaka#6769

Revert "Update dependency dd-trace to v5.47.0"

---

service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizen.kt

Kun kuntalainen lähettää lomakkeen, generoidaan pdf uudelleen.

Korjataan kuntalaisen täytettävän lomakkeen pdf-generointi

---

frontend/src/employee-frontend/components/reports/CustomerFees.tsx
frontend/src/employee-frontend/generated/api-clients/reports.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/CustomerFeesReportTest.kt
service/src/main/kotlin/fi/espoo/evaka/reports/CustomerFeesReport.kt

Muutettu samalla valintaboksien tyhjä valinta "Valitse" -> "Kaikki".

Lisätään asiakasmaksut-raportille suodatus toimintamuodon mukaan

---

frontend/src/employee-frontend/components/employees/EmployeePage.tsx
service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt

Käyttäjän ei pitäisi pystyä luvittamaan itseään yksikköön.

Korjataan yksikköroolin lisääminen itselle

---

frontend/src/employee-frontend/components/reports/ServiceNeeds.tsx
frontend/src/employee-frontend/generated/api-clients/reports.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceNeedReportTest.kt
service/src/main/kotlin/fi/espoo/evaka/reports/ServiceNeedReport.kt

1. palvelualue
2. järjestämismuoto
3. toimintamuoto

Lisätään suodattimia lapsen palveluntarpeet ja iät -raportille

---

frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts

Lisätään testitapaus lomavaraukseen maksuttomalle sijoitustyypille 

---

service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt

Nekku tuotehaulle lokikorjaus

---

service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt

Nekku: Ei tehdä tyhjää tilausta, jos lapsia ei ole ryhmässä.

Nekku: Ei tehdä tyhjää tilausta, jos lapsia ei ole ryhmässä.

---

frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts

Korjattu ohjeteksti vastaamaan nykyisen pituista varmistuskoodia. Entinen teksti 12-merkkinen, nykyään 6-merkkinen.

Korjattu kasvattajan mobiilin parituksen ohjeteksti vastaamaan nykyisen pituista varmistuskoodia

---

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/NewCustomerIncomeNotificationIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt

Korjataan uusien asiakkaiden tulotietomuistutus kun saman perheen aloittavia lapsia on useita

---

frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
frontend/src/employee-frontend/components/unit/tab-groups/child-documents/CreateChildDocumentsModal.tsx
frontend/src/employee-frontend/components/unit/tab-groups/child-documents/queries.ts
frontend/src/employee-frontend/generated/api-clients/document.ts
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt

Kun lomakkeita luodaan ryhmälle, poistetaan vaihtoehdoista ne lapset joille on jo luotuna kyseinen lomake.

Korjataan kuntalaisen lomakkeiden duplikaatit

---

service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt

Regressiotestejä tulevalle muutokselle https://github.com/espoon-voltti/evaka/pull/6870

Lisätään poissaolojen tallennukseen testejä

---

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt

Lomakkeet 3: Päätösesityksen voi perua / palauttaa korjattavaksi muutkin kuin pääkäyttäjä

---

service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt

Lisätään Nekku-ruokatilauksiin lapselle käyttöliittymässä valitut erikoisruokavaliot sekä alle 1-vuotiialle lisäksi automaattisesti alle 1-vuotiaan ruokavalio

Lisätään Nekku-ruokatilauksiin erikoisruokavaliot

---

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
service/src/main/resources/db/migration/V524__sfi_events.sql
service/src/main/resources/migrations.txt

Valmistautumista SFI paluukanava/events -integraatioon

SFI events -tietokantataulut

---

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReportTest.kt
service/src/main/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReport.kt

Lisätään valmistavan opetuksen lapset esiopetuksen poissaoloraportille

---

service/src/main/resources/db/migration/V526__fix_sfi_message_event_type_enum.sql
service/src/main/resources/migrations.txt

Fix sfi_message_event_type enum values

---

frontend/src/citizen-frontend/generated/api-clients/systemnotifications.ts
frontend/src/citizen-frontend/login/LoginPage.tsx
frontend/src/e2e-test/pages/citizen/citizen-header.ts
frontend/src/e2e-test/pages/employee/SystemNotificationsPage.ts
frontend/src/e2e-test/specs/5_employee/system-notifications.spec.ts
frontend/src/employee-frontend/components/system-notifications/SystemNotificationsPage.tsx
frontend/src/employee-frontend/components/system-notifications/queries.ts
frontend/src/employee-frontend/generated/api-clients/systemnotifications.ts
frontend/src/employee-mobile-frontend/generated/api-clients/systemnotifications.ts
frontend/src/lib-common/generated/api-types/systemnotifications.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/systemnotifications/SystemNotificationsControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/systemnotifications/SystemNotificationsController.kt
service/src/main/resources/db/migration/V529__citizen_system_notification_i18n.sql
service/src/main/resources/migrations.txt

Kielistetyt tilapäiset ilmoitukset kuntalaiselle

---

frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/generated/api-clients.ts
frontend/src/e2e-test/generated/api-types.ts
frontend/src/e2e-test/pages/employee/child-information.ts
frontend/src/e2e-test/specs/5_employee/child-information-nekku.spec.ts
frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
frontend/src/employee-frontend/components/child-information/person-details/NekkuSpecialDiet.tsx
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

Lisätään e2e-testejä Nekku-erikoisruokavalioiden muokkaamisen käyttöliittymään

Lisätään e2e-testejä Nekku-erikoisruokavalion käsittelyyn

---

service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt

Muutetaan Nekku-tilausten kokoamisen toiminnallisuutta niin, että jos jonkin lapsen jollekin aterialle ei löydy täsmäävää tuotetta, ateria jätetään tilaamatta sen sijaan että heitettäisiin poikkeus.

Nekku-tilaus tehdään vaikka kaikille aterioille ei löytyisi tuotteita

---

service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt

Lisää lokitusta ajastuspalveluun

---

frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
frontend/src/lib-common/generated/api-types/document.ts
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/DocumentHtmlGenerator.kt
service/src/main/resources/db/migration/V530__child_document_decision_number.sql
service/src/main/resources/migrations.txt

Muu päätös: päätösnumero

---

frontend/src/citizen-frontend/Footer.tsx

Piilotetaan footer tulosteista

---

service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/MissingReservationsRemindersTest.kt

Testi validoi, että kaukana tulevaisuudessa olevasta sijoituksesta ei lähde muistutusviestejä, vaikka läsnäoloilmoitus puuttuisikin.

Tekninen: testi tulevaisuuden sijoituksia koskeville muistutuksille

---

service/service-lib/src/main/kotlin/fi/espoo/voltti/auth/JwtTokenDecoder.kt
service/service-lib/src/test/kotlin/fi/espoo/voltti/logging/loggers/AppMiscLoggersTest.kt
service/service-lib/src/test/kotlin/fi/espoo/voltti/logging/loggers/AuditLoggerTest.kt
service/service-lib/src/test/kotlin/fi/espoo/voltti/logging/utils/TestAppender.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentService.kt
service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt
service/src/main/kotlin/fi/espoo/evaka/shared/message/IMessageProvider.kt

Muu päätös: suomi.fi viesti

---

service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportTest.kt
service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt

Jätetään huomioimatta lapset, joilla ei ole lähtöaikaa, kun toteuma tyyppi on valittuna.

Korjataan päiväkohtaiset lapsen tule- ja lähtöajat raportti

---

service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationControllers.kt
service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationService.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt

Kun hakemus on käsitelty, lähetetään sähköpostia hakemuksen tehneellä huoltajalle.

Lisätään esiopetuksen poissaolohakemuksen käsittelyyn sähköposti-ilmoitus

---

frontend/src/e2e-test/pages/employee/guardian-information.ts
frontend/src/e2e-test/specs/5_employee/income.spec.ts
frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx
frontend/src/employee-frontend/components/person-profile/income/IncomeList.tsx
frontend/src/employee-frontend/components/person-profile/income/IncomeNotifications.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Kaikki tulotietomuistutukset yhteen listaan päämiehen sivulla

---

frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
frontend/src/e2e-test/pages/employee/documents/child-document.ts
frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Lisätty:
- vahvistus kuntalaiselle lomakkeen lähettämisestä lähetysnapin painalluksesta
- vahvistuksen tekstit

Vahvistus kuntalaisen lomakkeen lähetykseen

---

frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
frontend/src/citizen-frontend/calendar/ChildSelector.tsx
frontend/src/citizen-frontend/calendar/ReservationModal.tsx
frontend/src/citizen-frontend/calendar/reservation-modal/form.ts
frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
frontend/src/e2e-test/specs/absence-application/absence-application.spec.ts
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt

Jos huoltaja tekee yli viikon pituisen poissaolon esiopetuksessa olevalle lapselle, kehotetaan käyttämään erillistä poissaolohakemusta.

Lisätään kehotus käyttää esiopetuksen poissaolohakemusta

---

frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx

No attendance -> Registration missing

Korjaus käännökseen

---

frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateController.kt

"Virallisia" lomakepohjia ei voi luoda englanninkielisinä

---

frontend/src/citizen-frontend/index-vite.html
frontend/src/employee-mobile-frontend/index-vite.html

Nämä unohtuivat viten käyttämistä html-sivuista.

Lisätään puuttuvat viewport meta-tagit

---

service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt

Nekku tilaus ei muodostu, jos operaatiopäiviä ei ole asetettu ja lomapäivien huomiointi tilauksissa
Huomioidaan myös arkipyhät ja JAO yksikön aukiolo arkipyhinä.

Nekku tilaus ei muodostu, jos operaatiopäiviä ei ole asetettu ja lomapäivien huomiointi tilauksissa

---

service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

Lisätään yksikön johtajalle oikeus listata poissaolokyselyt

---

apigw/Dockerfile
service/Dockerfile

Muutetaan `ENV variable value` muotoon `ENV variable=value`.

Tekninen: korjataan Dockerfile-tiedostojen ENV lauseiden muodot

---

service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaServiceTest.kt
service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaService.kt

Esim.
suunnitelma:
```
06:30 - 13:00
13:00 - 14:00
14:00 - 14:09
```
toteuma:
```
06:26 - 14:05
```
Vastaus pitäisi olla `06:30 - 14:09` (tällä hetkellä tulee `06:30 - 14:00`).

Korjataan Titania-integraatioon toteuman pyöristys jos leimaus on lähellä kahta suunnitelmaa

---

service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt

Tällä hetkellä sijoituksen päivitys logittaa vain päivitetyn sijoituksen id:n.
Tämä muutos lisää sekä lapsen että yksikön id:n (vastaavasti kuten sijoituksen lisäämisessä ja poistamisessa) ja sijoituksen mahdollisesti muutetun alku- ja loppupäivämäärän.

Parannetaan sijoituksen päivityksen logitusta

---

frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceForm.tsx
frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceRow.tsx
frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceSection.tsx
frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceForm.tsx
frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceRow.tsx
frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceSection.tsx
frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
frontend/src/lib-common/generated/api-types/assistance.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/assistance/Assistance.kt
service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceController.kt
service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
service/src/main/kotlin/fi/espoo/evaka/koski/Oppija.kt

Esiopetuksen tuen tason lakimuutokset

---

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/NewCustomerIncomeNotificationIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt

Tarkistetaan uusien asiakkaiden tulotiedot ja tulotietoselvitykset ennen tulotietomuistutuksen lähettämistä

Lisätään uusien asiakkaiden tulotietojen ja tulotietoselvitysten tarkistus

---

frontend/src/employee-mobile-frontend/App.tsx
frontend/src/employee-mobile-frontend/child-attendance/AttendanceList.tsx
frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx
frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
frontend/src/lib-components/molecules/Tabs.tsx

- Korjataan "Tänään"-nappi henkilökunnan listanäkymässä
- Korjataan aktiivisen sivun/välilehden korostus kaikissa näkymissä

Korjauksia kasvattajan mobiilin linkkeihin

---

frontend/src/employee-frontend/components/messages/SingleThreadView.tsx

Jatkoa muutokselle https://github.com/espoon-voltti/evaka/pull/6841

Korjataan viestit-sivun käyttö pienillä resoluutioilla

---

frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
frontend/src/employee-frontend/index.css
frontend/src/lib-components/atoms/DisableableLink.tsx

Nappulat muutetaan linkkeihin, jotta ne rivittyvät automaattisesti oikein ja käyttävät HTML:ssä a tagia button tagin sijaan.

Muutetaan "Lapsen asiakirjat" käyttämään linkkejä nappuloiden sijaan

---

frontend/src/employee-frontend/components/employees/EmployeePage.tsx
frontend/src/employee-frontend/components/employees/queries.ts
frontend/src/employee-frontend/generated/api-clients/pis.ts
frontend/src/lib-common/generated/api-types/pis.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/Audit.kt
service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

Lisätään pääkäyttäjälle mahdollisuus muuttaa palveluntuottajan sähköpostiosoitetta työntekijän sivulla.

Palveluntuottajan sähköpostiosoitteen muokkaaminen pääkäyttäjänä

---

frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Käyttöönotoissa käyttäjillä on ollut hankaluuksia tietää mitä kenttiä mikäkin integraatio käyttää.

Lisätään yksikköeditoriin integraatio-ikonit

---

frontend/src/citizen-frontend/navigation/DesktopNav.tsx
frontend/src/citizen-frontend/navigation/MobileNav.tsx
frontend/src/employee-frontend/components/Header.tsx
frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx
frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
frontend/src/lib-components/atoms/NavLink.tsx
frontend/src/lib-components/molecules/Tabs.tsx

Korjataan linkkien aktiivisuus kuntalaisen (mobiili+desktop) ja henkilökunnan (desktop) käyttöliittymissä

---

service/src/main/kotlin/fi/espoo/evaka/document/archival/DocumentMetadataUtils.kt

Lisätään arkistoitavaan asiakirjaan "creation.created" luontipäivämäärä ja erotetaan luontipäivämäärän määrittämisen logiikka erilliseksi funktioksi, jota voi helposti uudelleenkäyttää.

Lisätään arkistoitavan asiakirjan luontipäivämäärä

---

frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
frontend/src/employee-frontend/components/document-templates/forms.ts

Asianhallinnan tehtäväluokka on jatkossa pakollinen luotaessa vasu, leops, hojks tai muu päätös tyyppisiä lomakepohjia.

Asianhallinnan tehtäväluokka osittain pakolliseksi

---

service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt

Poistetaan kalenterin puuttuvan poissaolokyselyvastauksen indikaattori ilmaisilta sijoituksilta

---

frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt

Päivitetään lomakepohjien tyypien tekstejä ja infotekstejä. Päivitetään myös asiakirjasähköpostit.

Päivitetään lomakepohjien tyypit

---

.github/workflows/build.yml
bin/split-integration-tests.sh

- Yksinkertaistetaan hieman testien löytämistä
- Tulostetaan CI:ssä mitkä testit ajetaan

Parannetaan integraatiotestien ajamista CI:ssä

---

frontend/src/employee-frontend/components/child-information/AssistanceNeedVoucherCoefficientSection.tsx
frontend/src/employee-frontend/components/child-information/assistance-need/voucher-coefficient/AssistanceNeedVoucherCoefficientForm.tsx
frontend/src/employee-frontend/components/child-information/assistance-need/voucher-coefficient/AssistanceNeedVoucherCoefficientRow.tsx
frontend/src/employee-frontend/components/child-information/assistance/AssistanceActionRow.tsx
frontend/src/employee-frontend/components/child-information/assistance/AssistanceFactorForm.tsx
frontend/src/employee-frontend/components/child-information/assistance/AssistanceFactorRow.tsx
frontend/src/employee-frontend/components/child-information/assistance/AssistanceFactorSection.tsx
frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceForm.tsx
frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceRow.tsx
frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceSection.tsx
frontend/src/employee-frontend/components/child-information/assistance/OtherAssistanceMeasureForm.tsx
frontend/src/employee-frontend/components/child-information/assistance/OtherAssistanceMeasureRow.tsx
frontend/src/employee-frontend/components/child-information/assistance/OtherAssistanceMeasureSection.tsx
frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceForm.tsx
frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceRow.tsx
frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceSection.tsx
frontend/src/lib-common/generated/api-types/assistanceaction.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceController.kt
service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceQueries.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceAction.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionQueries.kt

ja hiotaan / yhtenäistetään ulkoasua

Näytetään muokkaustiedot kaikissa tuen osioissa

---

frontend/src/e2e-test/pages/employee/units/unit-calendar-page-base.ts
frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
frontend/src/employee-frontend/components/unit/TabCalendar.tsx
frontend/src/employee-frontend/components/unit/tab-calendar/AttendanceGroupFilterSelect.tsx
frontend/src/employee-frontend/components/unit/unit-reservations/ChildReservationsTable.tsx
frontend/src/lib-common/generated/api-types/reservations.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt

Yksikön viikkokalenterissa voi valita ryhmäksi lapset joilla on vuorohoitoa

---

frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceNeedTable.tsx
frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts
frontend/src/employee-frontend/components/child-information/placements/ServiceNeeds.tsx
frontend/src/employee-frontend/components/child-information/placements/service-needs/MissingServiceNeedRow.tsx
frontend/src/employee-frontend/components/reports/MissingServiceNeed.tsx
frontend/src/employee-frontend/generated/api-clients/reports.ts
frontend/src/employee-frontend/types/unit.ts
frontend/src/lib-common/generated/api-types/placement.ts
frontend/src/lib-common/generated/api-types/reports.ts
frontend/src/lib-common/generated/api-types/serviceneed.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/MissingServiceNeedReportTest.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationForm.kt
service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
service/src/main/kotlin/fi/espoo/evaka/reports/MissingServiceNeedReport.kt
service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeed.kt
service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedQueries.kt

Lisää:
- puuttuvan palveluntarpeen näyttämisen kuntalaisen näkymään
- oletuspalveluntarpeen näyttämisen työntekijän näkymään
- oletuspalveluntarpeen näyttämisen `Puuttuvat palveluntarpeet` raportille

Oletuspalveluntarpeen näyttämisen parannuksia

---

frontend/src/citizen-frontend/calendar/ReservationModal.tsx
frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Vastaamattomien päivien huomautus kuntalaisen kalenterin loma-aika vastauksiin

---

frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
frontend/src/lib-common/generated/api-types/document.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
service/src/main/resources/db/migration/V544__child_document_decision_unit.sql
service/src/main/resources/migrations.txt

Tallennetaan lomakepohjaisen päätöksen aloitushetken yksikkö kun päätös hyväksytään

---

frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/generated/api-types.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentDecisionExpirationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ChildDocumentDecisionsReportTest.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt

dokumentaatio: https://github.com/espoon-voltti/evaka/wiki/Lomakepohjat-ja-lapsen-asiakirjat#p%C3%A4%C3%A4t%C3%B6sten-voimassaolon-katkaisu

Vanhentuneiden päätösten katkaisu yöllisessä ajossa

---

frontend/src/citizen-frontend/decisions/decisions-page/FinanceDecision.tsx
frontend/src/citizen-frontend/decisions/queries.ts
frontend/src/citizen-frontend/generated/api-clients/caseprocess.ts
frontend/src/e2e-test/generated/api-clients.ts
frontend/src/e2e-test/pages/citizen/citizen-decisions.ts
frontend/src/e2e-test/specs/0_citizen/citizen-finance-decisions.spec.ts
service/src/main/kotlin/fi/espoo/evaka/caseprocess/ProcessMetadataController.kt
service/src/main/kotlin/fi/espoo/evaka/caseprocess/ProcessMetadataControllerCitizen.kt
service/src/main/kotlin/fi/espoo/evaka/caseprocess/ProcessMetadataQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt

Maksu- ja arvopäätösten asianhallinnan metadatat katsottavissa "Näytä lisätiedot"-haitarista.

Näytetään maksuihin liittyvien päätösten asianhallinnan metadata kuntalaiselle

---

frontend/src/citizen-frontend/calendar/CalendarMonthView.tsx
frontend/src/citizen-frontend/calendar/CalendarPage.tsx
frontend/src/citizen-frontend/calendar/hooks.ts
frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
frontend/src/e2e-test/specs/0_citizen/citizen-show-service-usage.spec.ts

Korjataan kuntalaisen kalenterin tuntikooste päivittämään tuntisuunnitelman automaattisesti kun kuntalainen ilmoittaa läsnäoloja.

Korjataan kuntalaisen kalenterin kuukauden tuntikoosteen päivitys

---

frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/generated/api-types.ts
frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts
frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
frontend/src/employee-frontend/components/document-templates/forms.ts
frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
frontend/src/lib-common/generated/api-types/document.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/document/DocumentTemplateIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentDecisionExpirationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentServiceIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ChildDocumentDecisionsReportTest.kt
service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateController.kt
service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateQueries.kt
service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/resources/db/migration/V546__end_decision_when_unit_changes_config.sql
service/src/main/resources/migrations.txt
service/src/test/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceTest.kt
service/src/test/kotlin/fi/espoo/evaka/document/archival/DocumentMetadataUtilsTest.kt

Päätöspohjassa valitaan katkeaako päätös yksikön vaihtuessa

---

service/src/main/kotlin/fi/espoo/evaka/caseprocess/Migration.kt

Migraatioita yritettiin 1000 rivin klöntteinä. Jos mitään riviä ei pystynyt migratoimaan (esim. puuttuneen metadatakonfiguraation takia), yöllisten ajojen suoritus jäi ikuiseen silmukkaan. Lisäongelmana vielä ajamatta olevien yöllisten ajojen suoritusta ei päästy koskaan aloittamaan.
Korjauksen jälkeen migraatioita yritetään edelleen 1000 rivin klöntteinä. Toteutuneista migraatioista pidetään nyt kirjaa, ja jos toteutuneita migraatioita tapahtuu, otetaan käsittelyyn seuraava klöntti. Tämä korjaa ikuisen silmukan. Ongelmaksi jää, että jos syystä tai toisesta ensimmäinen tietokantakysely palauttaa 1000 riviä, joita ei pystytä migratoimaan, mutta näiden jälkeen löytyisi rivejä, jotka olisivat migratoitavissa, niin nämä rivit jäävät migratoimatta.

Korjaus yöllisten ajojen metadatamigraation jumiutumisongelmaan

---

service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt

Päätöstyyppisen dokumentin muistutussähköpostin tekstimuutos

---

frontend/src/employee-frontend/components/messages/MessageContext.tsx
frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
frontend/src/lib-common/generated/api-types/messaging.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt

Linkki tulee näkyviin jos viestiketju on aloitettu hakemuksen kautta.

Lisätään linkki hakemukseen palveluohjauksen viestiketjuissa

---

frontend/src/citizen-frontend/calendar/ReservationModal.tsx
frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx

Useita korjauksia:
1. lisää/poista-painikkeista ei välitetä tietoa ruudunlukijalle
2. "Valitse lapset" puuttuva fieldset/legend
3. "Valitse miten kellonaika..." puuttuva labelin kohdistus
4. "Alkaa-päättyy" puuttuva fieldset/legend

Korjataan ilmoita läsnäoloja -modaalin saavutettavuutta

---

frontend/src/citizen-frontend/AccessibilityStatement.tsx
frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx
frontend/src/citizen-frontend/applications/read-view/ApplicationReadView.tsx
frontend/src/citizen-frontend/applications/read-view/ApplicationReadViewContents.tsx
frontend/src/citizen-frontend/calendar/CalendarPage.tsx
frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
frontend/src/citizen-frontend/children/ChildHeader.tsx
frontend/src/citizen-frontend/children/ChildPage.tsx
frontend/src/citizen-frontend/children/sections/absence-applications/NewAbsenceApplicationPage.tsx
frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/NewServiceApplicationPage.tsx
frontend/src/citizen-frontend/decisions/assistance-decision-page/AssistanceDecisionPage.tsx
frontend/src/citizen-frontend/decisions/assistance-decision-page/AssistancePreschoolDecisionPage.tsx
frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
frontend/src/citizen-frontend/income-statements/ChildIncomeStatementView.tsx
frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
frontend/src/citizen-frontend/login/LoginPage.tsx
frontend/src/citizen-frontend/login/WeakLoginFormPage.tsx
frontend/src/citizen-frontend/messages/MessagesPage.tsx
frontend/src/citizen-frontend/personal-details/PersonalDetails.tsx

Suurimmalta osalta sivuista puuttuui title-tagin asettaminen.

Lisätään sivun title vastaamaan valittua pääsivua

---

frontend/src/citizen-frontend/personal-details/PersonalDetailsSection.tsx
frontend/src/lib-components/atoms/dropdowns/Select.tsx

Siirretään kohdistus automaattisesti ensimmäiseen syöttökenttään.

Korjataan omien tietojen muokkauksen kohdistus

---

frontend/src/e2e-test/specs/5_employee/unit-application-process.spec.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionResolutionIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt

Näytetään hakemus yksikön hakemusprosessi-sivulla kunnes huoltaja on ottanut kantaa kaikkiin hakemukseen liittyviin päätöksiin.

Näytetään hakemus yksikön sivulla kunnes kaikkiin päätöksiin on otettu kantaa

---

frontend/src/employee-frontend/components/unit/tab-groups/notes/NotesModal.tsx
frontend/src/employee-mobile-frontend/child-notes/GroupNotesTab.tsx
frontend/src/lib-common/generated/api-types/note.ts
frontend/src/lib-components/employee/notes/StaticStickyNote.tsx
frontend/src/lib-components/employee/notes/notes.d.ts
frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/main/kotlin/fi/espoo/evaka/note/group/GroupNote.kt
service/src/main/kotlin/fi/espoo/evaka/note/group/GroupNoteQueries.kt

Lisätään muokattu viimeksi päivämäärä ryhmämuistiinpanoihin

---

service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedVoucherCoefficientEndOutdatedTest.kt
service/src/main/kotlin/fi/espoo/evaka/assistanceneed/vouchercoefficient/AssistanceNeedVoucherCoefficientQueries.kt

Korjataan palvelusetelikertoimen automaattikatkaisu, jotta se käsittelee oikein katkaisupäivänä alkavat palvelusetelikertoimet

Korjataan palvelusetelikertoimen automaattikatkaisu

---

service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt

Henkilöä ei poisteta ei-aktiivisena, jos henkilölle on lähetetty lapsen asiakirja

Lisätään tarkistus lapsen asiakirjoille ei-aktiivisten henkilöiden poistamiseen

---

frontend/src/lib-customizations/types.d.ts

Poistetaan väärä tieto ServiceApplication feature flagista

Poistetaan väärä tieto ServiceApplication feature flagista

---

apigw/README.md
apigw/package.json
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/evaka-bom/build.gradle.kts

Paremmat dokumenttipohjan otsikot

---

frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/generated/api-types.ts
frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
frontend/src/lib-common/generated/api-types/daycare.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/DaycareEditIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuOrderIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuQueryIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt
service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/resources/db/migration/V551__daycare_nekku_order_reduction_percentage.sql
service/src/main/resources/migrations.txt

Lisätään yksikkökohtaisesti säädettävä Nekun tilausvähennysprosentti, jonka arvo on oletuksena kaikilla yksiköillä kymmenen prosenttia

Lisätään yksikkökohtainen Nekun tilausvähennysprosentti

---

service/evaka-bom/build.gradle.kts

Liittyy [spring boot 3.5.5 päivitykseen](https://github.com/espoon-voltti/evaka/pull/7648).

Poistetaan ylimääräiset versiomääritykset

---

frontend/src/citizen-frontend/calendar/CalendarMonthView.tsx
frontend/src/citizen-frontend/calendar/MonthElem.tsx
frontend/src/citizen-frontend/children/ChildHeader.tsx
frontend/src/citizen-frontend/messages/ThreadList.tsx
frontend/src/e2e-test/pages/citizen/citizen-children.ts
frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts

Kohdistaa ruudunlukijan/näppäimistöselaajan automaattisesti ensisijaiseen sivuotsikkoon kuntalaisen välilehdillä.

Lisää ruudunlukijan automaattinen kohdistus sivusisältöön kuntalaisen välilehdille

---

service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt

Lukemattomien viestien lukumäärässä huomioidaan vain viestit, jotka käyttäjä saa nähdä.

Henkilökunta: Lukemattomien viestien lukumäärä huomioi viestien näkyvyyssäännöt

---

service/src/main/kotlin/fi/espoo/evaka/varda/VardaClient.kt

Rate limit to max 2 varda requests per second

---

service/src/main/kotlin/fi/espoo/evaka/document/childdocument/DocumentHtmlGenerator.kt

Päätöksentekopäivämäärä puuttui lomakkeelta, lisätty speksin mukaisesti.

Päätöksentekopäivämäärä muiden päätösten pdf-tiedostoihin

---

service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
service/src/main/kotlin/fi/espoo/evaka/varda/VardaClient.kt
service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
service/src/main/resources/application-local.yaml

Decrease varda api rate limit and log rate wait

---

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Korjaus huoltajien täytettävät dokumentit-toiminnon nimeen

---

service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/NewCustomerIncomeNotificationIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt

Tulotietomuistutus lähetetään vain maksullisille sijoituksille

---

frontend/src/e2e-test/specs/5_employee/guardian-income-statements.spec.ts
frontend/src/employee-frontend/components/fee-decision-details/IncomeSection.tsx
frontend/src/employee-frontend/components/fee-decisions/FeeDecisionFilters.tsx
frontend/src/employee-frontend/components/person-profile/FosterChildren.tsx
frontend/src/employee-frontend/components/person-profile/PersonFridgeChild.tsx
frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx
frontend/src/employee-frontend/components/person-profile/PersonInvoiceCorrections.tsx
frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx

- Trimmataan lapsen oid
- Näytetään lapsen nimi Sukunimi Etunimi -järjestyksessä

Pieniä parannuksia oid-inputtiin ja lasten nimien ulkoasuun

---

service/src/main/kotlin/fi/espoo/evaka/reports/NekkuOrderReport.kt

Lisätään Nekku tilausraporttiin järjestys myös ruoka-ajan mukaan

Lisätään Nekku tilausraporttiin järjestys myös ruoka-ajan mukaan

---

service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt

Koski-integraation korjaus liittyen lapsikohtainen tuki + pidennetty oppivelvollisuus

---

frontend/src/e2e-test/pages/employee/child-information.ts
frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Varmistusvalinta lapsen dokumentin luontidialogiin

---

frontend/src/employee-frontend/components/child-documents/ChildDocumentReadView.tsx
frontend/src/employee-frontend/components/person-profile/PersonDecisions.tsx
frontend/src/employee-frontend/components/person-profile/queries.ts
frontend/src/employee-frontend/generated/api-clients/decision.ts
frontend/src/lib-common/generated/action.d.ts
frontend/src/lib-common/generated/api-types/decision.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
frontend/src/lib-customizations/espoo/featureFlags.tsx
frontend/src/lib-customizations/types.d.ts
service/src/integrationTest/kotlin/fi/espoo/evaka/document/archival/ArchivalServiceIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
service/src/main/kotlin/fi/espoo/evaka/decision/Decision.kt
service/src/main/kotlin/fi/espoo/evaka/decision/DecisionController.kt
service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt
service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchivalIntegrationClient.kt
service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchivalService.kt
service/src/main/kotlin/fi/espoo/evaka/espoo/archival/SärmäChildDocumentClient.kt
service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
service/src/main/resources/db/migration/V555__decision_archived_at.sql
service/src/main/resources/migrations.txt

Vastaava toteutus tässä vaiheessa kuin asiakirjoilla: AsyncJob jonka voi käynnistää käyttöliittymän kautta.

Lisätään päätösten arkistointi

---

frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx

Uudelleennimetään tuen raportit

---

frontend/src/e2e-test/pages/employee/reports.ts
frontend/src/e2e-test/specs/5_employee/assistance-need-and-actions-report.spec.ts
frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
frontend/src/employee-frontend/generated/api-clients/reports.ts
frontend/src/lib-common/generated/api-types/reports.ts
service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportController.kt

Korjaa samalla, että raportti näyttää vain valitun tyypin (varhaiskasvatus tai esiopetus) tukitoimia.

Lisätään tuen tarpeet ja tukitoimet raportille näytettävien tukitoimien valitsin

---

service/evaka-bom/build.gradle.kts

Päivitetään logback versioon 1.5.19

---

frontend/src/employee-frontend/components/reports/NonSsnChildren.tsx
frontend/src/lib-common/generated/api-types/reports.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/reports/NonSsnChildrenReportTest.kt
service/src/main/kotlin/fi/espoo/evaka/reports/NonSsnChildrenReportController.kt

Hetuttomat lapset raportti: lisätään sarake "Viety Koskeen viimeeksi"

---

frontend/src/e2e-test/dev-api/fixtures.ts
frontend/src/e2e-test/generated/api-types.ts
frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/survey-editor/DiscussionSurveyForm.tsx
frontend/src/lib-common/generated/api-types/calendarevent.ts
frontend/src/lib-common/generated/api-types/nekku.ts
frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTestData.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTestUtils.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuOrderIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuQueryIntegrationTest.kt
service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuSyncIntegrationTest.kt
service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEvent.kt
service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuClient.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
service/src/main/resources/db/migration/V562__calendar_event_nekku_unordered_meals.sql
service/src/main/resources/migrations.txt

Lisätty kalenteritapahtumien luontiin mahdollisuus Nekku-integraation ollessa käytössä kertoa, että tämän tapahtuman osallistujille ei tilata valittuja aterioita

Lisätty kalenteritapahtumiin mahdollisuus Nekku-aterioiden tilausvähennykseen
