espoon-voltti/evaka

- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiClient.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
Organizer OID (= Espoo) makes more sense than organization OID (can be
something else than Espoo with at least private daycares).
Might fix private daycare Koski uploads, which return 403 forbidden at the moment.
> Use organizer OID as Koski caller id

- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/StaffAttendanceController.kt
The permissions are too strict, and normal staff should be able to upsert the attendance counts
> Allow unit staff to upsert attendances

- frontend/e2e-test/test/e2e/specs/2_employee-2/paper-application.spec.ts
Left in `test.only` by mistake. This pr removes this and all tests will be run.
> EVAKA-HOTFIX removed test.only that was left in by mistake

- message-service/buildSrc/src/main/kotlin/Version.kt
- message-service/src/main/kotlin/fi/espoo/evaka/msg/config/DatabaseConfig.kt
- service/buildSrc/src/main/kotlin/Version.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/DaycareService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/DatabaseConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/JdbiExtensions.kt
* upgrade PostgreSQL driver
* borrowed connections longer than 1 minute are considered leaked and will be logged by HikariCP
* PostgreSQL TCP connections with no activity in 15 minutes are timed out -> in practice this sets a maximum limit to query durations, but also reveals connections that are stuck due to network problems and were effectively leaked and never returned to the pool
> Add PostgreSQL leak checking and TCP timeouts

- frontend/packages/employee-frontend/src/components/ChildInformation.tsx
- Should be h1 instead of h2, like in PersonProfile and other top-level pages
None
1. Run app
1. Looks correct, compared to person profile & reports page
```
```
> [EVAKA-HOTFIX] Fix ChildInformation title size

- apigw/Dockerfile
- There is some weird issue that results in 'EPERM: operation not permitted' _only_ in CI
- Testing if pinning nodejs to a version that was known to build succesfully works
None
1. CI Docker build works
1. Local Docker build works
- ~[ ] Tests have been written for the change (e2e, integration tests)~
- ~[ ] The change conforms to the UX specifications~
```
```
> [EVAKA-HOTFIX] apigw: fix CI Docker build

- .circleci/config.yml
- apigw/Dockerfile
Reverts hotfix in #21
- CI: upgrade _remote_ Docker engine to 19.03.13
- CircleCI remote Docker engine [defaults to 17.09.0-ce](https://circleci.com/docs/2.0/configuration-reference/#setup_remote_docker), explicitly upgrade to [19.03.13](https://circleci.com/docs/2.0/building-docker-images/#docker-version)
- **NOTE:** Still haven't figured out what the exact issue is with the `nodejs` + Docker engine version combination is but this at least fixes the situation and allows us to still use the latest 12.x Node.js releases
- Related: <https://discuss.circleci.com/t/docker-build-fails-with-nonsensical-eperm-operation-not-permitted-copyfile/37364/12> and <https://discuss.circleci.com/t/cgo-docker-build-failing-at-link-stage-operation-not-permitted/37100>
None
None
- ~[ ] Tests have been written …
> [EVAKA-HOTFIX] CI: Upgrade Docker engine to 19.03.13

- message-service/src/main/kotlin/fi/espoo/evaka/msg/config/DatabaseConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/DatabaseConfig.kt
Fix time unit order in conversions (correct form is `destUnit.convert(src, srcUnit)`) :facepalm: 
Both parameters ended up being 0 (disabled) because of this mistake.
> Fix pool configuration parameters

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SpringTxTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt
- it's not enough to catch RuntimeException, because Kotlin checked
exceptions work differently and might not be catched
- if rollback fails, add it to suppressed exceptions instead of
replacing the original application exception
- don't call rollback after a failed commit. Spring documentation
explains that after commit returns, the transaction is already
finished, even in error scenarios
> Fix withSpringTx rollback behaviour

- service/README.md
- service/build.gradle.kts
- service/gradle.properties
Sometimes it was painful to develop E2E tests against dev DB because it was easiest to just clean the database after failed E2E test in order to avoid duplicate data entries when running the test again. But that strategy may have lost some valuable development data (e.g. fee decisions invoices, placements). So:
- Added possibility to run dev server against integration test database
- Added comments to `gradle.properties` to easily configure flyway to take effect in integration test DB
So if you want to develop E2E tests against integration test DB just start the server with `./gradlew bootRunTest`
To clean integration test database:
- edit `gradle.properties` (configs are commented out in the file)
- run `./gradlew flywayClean`
- restart the server
> EVAKA-3882 Better E2E test development flow

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/reports/Occupancies.tsx
Report now has a mode which outputs capacity sum and caretaker count for each day in separate columns to better support calculating different averages and other statistics from the data.
Might be easiest to test in staging env.
```
```
> EVAKA-3885: new output mode for occupancy report

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/application-page/ApplicationEditView.tsx
- frontend/packages/employee-frontend/src/components/application-page/ApplicationReadView.tsx
Application was missing the info if the application was a part time or full time application. This PR adds the missing info to the read and edit views.
> EVAKA 3941 add parttime and fulltime info to application in employee frontend

- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/Oppija.kt
Apparently the provider affects access control, so it needs to be included when submitting study rights to purchased or voucher daycares
> Add provider type to Koski study rights when required

- frontend/packages/employee-frontend/src/components/application-page/ApplicationEditView.tsx
Assistance need field was broken when upgrading to new components. This PR fixes the problem (the old component used value directly when the new one uses an event).
> EVAKA-HOTFIX fixed broken assistance need in application edit view

- frontend/packages/employee-frontend/src/components/application-page/ApplicationDecisionsSection.tsx
- frontend/packages/employee-frontend/src/components/application-page/ApplicationReadView.tsx
- frontend/packages/employee-frontend/src/components/application-page/DecisionResponse.tsx
- frontend/packages/employee-frontend/src/components/decision-draft/DecisionDraft.tsx
When accepting decision on behalf of the enduser the acceptance date selector was using decisions maximum date and that could lead to situations where employees could accept decisions much further into the future that should be possible.
Changed the date selectors maximum date to use the endusers preferred start date + two weeks (the same as the enduser can choose).
> Evaka 3948 fix dates on applications decision section

- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/MockKoskiServer.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiClient.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiQueries.kt
Apparently voiding actually removes the study right, so the study right OID can't be used afterwards. On our side, the study right key (child+unit+type) will be reused if the study right is activated (= a new placement is created), which led to update requests to voided (= removed) study rights.
* make sure voiding is a one-shot operation (never void a voided study right)
* if a voided study right is reactivated on our side, make sure we send a new study right instead of trying to update an old one
* update mock Koski server to be more realistic in these scenarios
> [EVAKA-3961] Fix Koski study right voiding

- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/Oppija.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/Timeline.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
- service/src/main/resources/db/migration/R__koski_views.sql
- service/src/test/kotlin/fi/espoo/evaka/koski/KoskiTest.kt
- service/src/test/kotlin/fi/espoo/evaka/shared/TimelineTest.kt
- service/src/test/kotlin/fi/espoo/evaka/shared/domain/TimeTest.kt
Implement temporary interruptions (holiday / unplanned absence) in Koski preparatory study rights:
- only periods of longer than 7 days are considered (exactly 7 day periods are *not*)
- only in preparatory study rights
- only from 2020 term onwards
- public holidays and weekends are effectively skipped in calculations: a 5-day absence followed by a weekend and one public holiday Monday is a 5-day absence, **not** a 8-day absence
- add (naive) Timeline data structure, and do all period calculations with it
> [EVAKA-3838] Koski preparatory interruptions

- compose/proxy/nginx.conf
- frontend/yarn.lock
- proxy/nginx.conf.template
- proxy: prevent index.html caching harder
- Samsung Internet does not respect a Cache-Control: max-age=0 header alone and we anyway want to never cache index.html to prevent users from using older versions of the app accidentally
- NOTE: Setting no-store works at least with some older browsers to mitigate against browser history lists caching the page but there's no golden bullet for all browsers. This is just trying slightly harder.
- frontend: update Sentry SDK
- Some new performance/tracing capabilities
None
1. Run `master` version of compose-e2e stack -> `Cache-Control: max-age=0` and browser might cache `index.html` with refreshes
1. Run branch version of stack -> `Cache-Control: no-cache` and `no-store` and browser _never_ caches `index.html`
```
```
> [EVAKA-HOTFIX] proxy: prevent index.html caching harder

- message-service/buildSrc/src/main/kotlin/Version.kt
- service/buildSrc/src/main/kotlin/Version.kt
This simply changes the generated bytecode version, but doesn't
otherwise affect the compilation. But this should provide a clear error
if somebody tries to compile with a too old Java version
> Bump target Java version to 11

- frontend/packages/employee-frontend/src/components/ApplicationPage.tsx
- frontend/packages/employee-frontend/src/components/application-page/ApplicationEditView.tsx
Second guardian VTJ information was missing when editing application in the employee app. This fixes it with the same logic that is used in the application read view.
> EVAKA-3867 Fixed missing VTJ guardian when editing application

- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
- service/src/test/kotlin/fi/espoo/evaka/pis/service/PersonServiceTest.kt
Fix `/person/{personId}/ssn` endpoint hang when a VTJ update happens. When `getUpToDatePerson` decided to do a VTJ query, there were two nested transactions that both wanted to update the same row in the `person` table -> deadlock + hang until 15 minute DB connection read timeout
The simplest fix was to run "add SSN to person row" and "get updated person data" as separate operations, so nested transactions don't happen. In the future, we should probably refactor the internal API so that VTJ queries never run inside an outer transaction, to avoid connection starvation and potential dead locks.
> [EVAKA-3964] Fix SSN add endpoint hang

- .circleci/config.yml
- apigw/README.md
- apigw/src/enduser/services/map.ts
- apigw/src/shared/config.ts
- compose/.default.gmaps.env
- compose/.gitignore
- compose/README.md
- compose/compose-e2e
- compose/docker-compose.e2e.yml
- frontend/README.md
- frontend/e2e-test/package.json
- frontend/eslint-plugin/package.json
- frontend/package.json
- frontend/packages/employee-frontend/package.json
- frontend/packages/enduser-frontend/README.md
- frontend/packages/enduser-frontend/package.json
- frontend/packages/enduser-frontend/src/config.ts
- frontend/packages/lib-common/package.json
- frontend/packages/maintenance-page/README.md
- frontend/packages/maintenance-page/package.json
- apigw: remove default Google Maps API key
- All Google Maps APIs require authentication even in local development and backend keys can only be restricted by IP addresses -> not restricable to local environments -> can't have a key in a public repository
- Remove default keys (which weren't even working as they've been restricted to frontend APIs only) from apigw configs
- Fail fast before going to Google's APIs and throw an error to indicate missing configuration when hitting Maps endpoints
- As the endpoints are such a minor feature (only used in the enduser frontend's front page street address search), running apigw shouldn't fail without the keys and we don't want to complicate local development even further anyway
- Allow configuring a valid set of keys for compose-e2e stack via …
> [EVAKA-3912] Remove default apigw Google API keys, update frontend keys

- frontend/packages/employee-frontend/src/components/absences/AbsenceTable.tsx
- frontend/packages/employee-frontend/src/components/absences/Absences.scss
- frontend/packages/employee-frontend/src/components/absences/Absences.tsx
- frontend/packages/employee-frontend/src/components/absences/ColorInfo.scss
* center date columns
* left align non-date columns
* use 100% table width
* fix horizontal centering of absence cells
* add table scrollbar on small screens (not the best solution, but
better than the table going off screen)
* remove extra "dot row", replace with empty space
* add margin to color legend elements
Before vs after:
> [EVAKA-3958] Improve absence editor styles

- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/ParentshipQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/PartnershipQueries.kt
Only fetch family relations that are relevant, otherwise `Period` initialization fails as the code expects that all of the relations are within the decision generation period.
> Hotfix: finance decision generation

- frontend/packages/employee-frontend/src/index.scss
Default fonts from browser stylesheets were used in some elements, because they did not inherit the font from parents.
For example, on my machine the input element in the absence editor used:
* Ubuntu Sans in Firefox
* Arial in Chrome
After this change, it inherits Open Sans as expected.
> Inherit font by default in some elements

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/DecisionGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DecisionGenerator.kt
Fix a bug where finance decisions have wrong validity periods when two with identical contents are merged into one.
> Hotfix: merged finance decision validity periods

- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiPayloadIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiClient.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
A **cumulative total** of 31 days or more absence days **counting only sequences longer than one week** leads to resignation in preparatory education **only in terms starting from 2020**...a lot of conditions :wink: 
Also update the "verbal grading" text.
> Koski preparatory absences can lead to resignation

- service-lib/src/main/resources/fi/espoo/voltti/logging/logback/default-appender-sanitized.xml
- service-lib/src/test/kotlin/fi/espoo/voltti/logging/logback/AppenderTest.kt
- service-lib/src/test/kotlin/fi/espoo/voltti/logging/logback/Utils.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- no sanitization with SSNs inside UUIDs
- add case insensitivity in order to catch typo'd SSNs
> EVAKA-3942 Improve SSN sanitizing

- service/src/main/kotlin/fi/espoo/evaka/daycare/service/CaretakerService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/ParentshipService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/PartnershipService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
Since converting database query functions from various Spring implementations into Jdbi some of the catch blocks never caught the database exceptions since Jdbi obviously does not throw Spring's `DataIntegrityViolationException`s. Change the catch blocks to catch all throwables extending `Exception` since it doesn't really matter if we pass unrelated exceptions to `mapPSQLException` as well.
> Fix PSQLException handling

- frontend/packages/employee-frontend/src/components/fee-decision-details/FeeDecisionDetailsPage.tsx
- frontend/packages/employee-frontend/src/components/invoice/InvoicePage.tsx
`/invoices` has an extra redirect so it didn't lead to an empty page, but `/decisions` is an old URL that hasn't existed for some time now. Both URLs are now correct
> Fix empty page caused by incorrect redirect URL

- service/src/main/kotlin/fi/espoo/evaka/application/DecisionMessageProcessor.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
* `scheduleImmediateRun` must be called after the transaction planning the jobs has been committed
* `runAfterCommit` only works inside Spring transactions, and is no-op otherwise
> Fix invalid async job runner usage

- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTestHelpers.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiPayloadIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/VTJBatchRefreshServiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunnerTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/DecisionMessageProcessor.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsBatchRefreshService.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailAsyncJobs.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/messaging/FeeDecisionGenerationJobProcessor.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/messaging/InvoicingAsyncJobs.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiClient.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/FamilyInitializerService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/VTJBatchRefreshService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
We still have an open transaction in the runner, but async jobs are
expected to acquire a database connection themselves if they want to do
db stuff
> Remove handle parameter from async jobs

- frontend/packages/employee-frontend/src/components/placement-draft/PlacementDraft.tsx
Previously, if the placement plan's start date is for example moved to the future, units that open later in the future would not appear in the unit list.
> Update placement plan unit list on date change

- service/src/integrationTest/kotlin/fi/espoo/evaka/vtjclient/service/PersonStorageServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/controllers/VtjController.kt
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/service/persondetails/PersonStorageService.kt
This prevents certain transaction deadlock situations, since we're not creating nested transactions.
> Use JDBI handle argument in all PersonStorageService functions

- service/src/main/kotlin/fi/espoo/evaka/identity/SSNUtils.kt
Since SSNs are removed from logs, log just the century character.
> Improve SSN invalid century loggin

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
When filtering applications by area, instead of always using the first preference use the placement unit when available.
> Filter applications by placement unit with area filter

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/reports/Applications.tsx
- frontend/packages/employee-frontend/src/components/reports/AssistanceActions.tsx
- frontend/packages/employee-frontend/src/components/reports/AssistanceNeeds.tsx
- frontend/packages/employee-frontend/src/components/reports/ChildAgeLanguage.tsx
- frontend/packages/employee-frontend/src/components/reports/ChildrenInDifferentAddress.tsx
- frontend/packages/employee-frontend/src/components/reports/EndedPlacements.tsx
- frontend/packages/employee-frontend/src/components/reports/FamilyConflicts.tsx
- frontend/packages/employee-frontend/src/components/reports/MissingHeadOfFamily.tsx
- frontend/packages/employee-frontend/src/components/reports/MissingServiceNeed.tsx
- frontend/packages/employee-frontend/src/components/reports/Occupancies.tsx
- frontend/packages/employee-frontend/src/components/reports/PartnersInDifferentAddress.tsx
- frontend/packages/employee-frontend/src/components/reports/StartingPlacements.tsx
Fixed `ReactSelect` components in multiple report pages. Some of the reports did not have proper value and placeholder props. Also removed empty options and used `{value: xxx, label: yyy}` instead of `{id: xxx, label: yyy}` options.
> Evaka 3988 fix broken report dropdowns

- frontend/e2e-test/test/e2e/specs/5_employee/backup-care.spec.ts
- frontend/packages/employee-frontend/src/components/unit/tab-groups/MissingGroupPlacements.tsx
- frontend/packages/employee-frontend/src/components/unit/tab-groups/missing-group-placements/GroupPlacementModal.tsx
Filter missing group placements by time range. At the moment such filtering is done for missing group placements, but not for backup cares. This leads to an inconsistent UX due to [how](https://github.com/espoon-voltti/evaka/blob/a28f087bb88136e03ac392817cfb3223ea5c9e0c/frontend/packages/employee-frontend/src/components/unit/tab-groups/MissingGroupPlacements.tsx#L134-L136) missing group placements are mapped to backup cares in the frontend.
> EVAKA-3977: Make backup care placements use the regular group placement form

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/DbTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt
For example, if T is List<Foo>, T::class.java simply returns generic List<Object> due to type erasure. Using a local GenericType object class and instance retains reified type information of any generic type parameters of T.
This also means every call site will have an anonymous dummy class, but it shouldn't cause problems.
> Work around generic parameter type erasure in mapJsonColumn

- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/PlannedOccupancyTest.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
Changed planned occupancy logic (now uses 'prepare for the worst case scenario' principle) and unified it between unit view and report:
- If child has overlapping placement and placement_plan to different units, child counts into both units
- If child has overlapping placement and placement_plan to same unit, the one with higher capacity need wins
```
```
> EVAKA-4012: improve and unify planned occupancy logic

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/child-information/placements/CreatePlacementModal.tsx
- frontend/packages/employee-frontend/src/components/common/FormModal.tsx
- frontend/packages/employee-frontend/src/components/placement-draft/PlacementDraft.tsx
- frontend/packages/employee-frontend/src/components/placement-draft/UnitCard.tsx
- frontend/packages/employee-frontend/src/components/placement-draft/UnitCards.tsx
- frontend/packages/employee-frontend/src/components/shared/UnderRowStatusIcon.tsx
- frontend/packages/employee-frontend/src/components/shared/atoms/buttons/Button.tsx
- frontend/packages/employee-frontend/src/components/shared/atoms/buttons/InlineButton.tsx
- frontend/packages/employee-frontend/src/components/shared/atoms/form/InputField.tsx
- frontend/packages/employee-frontend/src/state/placementdraft.tsx
- frontend/packages/employee-frontend/src/types/application.ts
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
A child should never be placed into a ghost unit.
* Frontend logic updates: In the relevant forms, disable submit button and display a warning when a ghost unit is selected.
* UI updates: Add `UnderRow` to `Button` and `InlineButton` in order to display warnings under buttons.
* Backend update: Add the `ghostUnit` flag to the return data of `/api/internal/public/units`.
Attached some images for a quick reference.
> EVAKA-3831: Block placement to a ghost unit: Disable submit button and warn user

- .circleci/config.yml
- message-service/README.md
- message-service/src/main/kotlin/fi/espoo/evaka/msg/config/SfiSoapClientConfig.kt
- message-service/src/main/kotlin/fi/espoo/evaka/msg/service/sfi/SfiClientService.kt
- message-service/src/test/kotlin/fi/espoo/evaka/msg/service/sfi/SfiClientServiceTest.kt
- service-lib/src/main/kotlin/fi/espoo/voltti/logging/loggers/AppMiscLoggers.kt
- service-lib/src/test/kotlin/fi/espoo/voltti/logging/loggers/AppMiscLoggersTest.kt
- message-service: only log SFI errors once, don't abuse audit logs
- All message sending errors are handled and _logged_ by the async job handler, no need to double or even triple log them
- Don't log errors as audit logs -- errors are only interesting and required as audit events when relating to authentication & authorization (e.g. failed attack attempts)
- Don't log errors while handling them in the SOAP client, they will be logged by the client's users
- Include all relevant data in log messages where possible
- I don't love losing the metadata from single messages but as we now have tracing IDs I find this an acceptable compromise to avoid noise
- service-lib/logging: add support for meta-field in misc logs
- Extend all other `Klogger` methods to allow setting the meta-field to …
> [EVAKA-4008] message-service: log errors once, don't abuse audit logs

- apigw/src/enduser/routes.ts
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/views/applications/daycare-application/daycare-application.vue
- frontend/packages/enduser-frontend/src/views/applications/daycare-application/form-components/summary/application-daycare-summary.vue
- frontend/packages/enduser-frontend/src/views/applications/daycare-application/form-components/summary/application-summary.vue
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
Application preview should list uploaded attachments and (in some cases) an info box about the benefits of doing so.
> EVAKA-3464 show attachments on application preview

- service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiPayloadIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaClientIntegrationMockHttpsServer.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiClient.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaTokenProvider.kt
Use common FuelManager for Koski calls and Varda token fetching.
Requires certificates installed on environments before update.
Varda and Koski should work as before.
```
```
> Use FuelManager for varda token fetch

- frontend/e2e-test/README.md
- frontend/packages/enduser-frontend/src/store/index.ts
- frontend/packages/enduser-frontend/src/store/modules/auth.ts
- frontend/packages/enduser-frontend/src/views/applications/application-list.vue
- Both will be loaded by their respective views when rendered
- Applications page actually has to load both to link to decisions from applications but at least it's one request less
- E2E: docs for known cleanup issue
- For some reason, Testcafe doesn't actually run Fixture.after when running with --stop-on-first-fail / stopOnFirstFail -> test data created with dev-API isn't actually cleared when a test fails, requiring a full reset of the local database (or manually going through everything)
None
Before PR:
1. Don't authenticate
1. Navigate directly to `/applications` in enduser-frontend
1. See **two** requests to `/api/application/enduser/v2/applications` after authentication
From PR branch:
1. Don't authenticate
1. Navigate directly to `/applications` in enduser-frontend
1. See **only …
> [EVAKA-4014] enduser: don't load applications & decisions upon auth

- frontend/packages/employee-frontend/src/components/attendances/AttendanceGroupSelectorPage.tsx
- frontend/packages/employee-frontend/src/components/attendances/AttendanceList.tsx
- frontend/packages/employee-frontend/src/components/attendances/AttendancePageWrapper.tsx
Changed `<a>`-tags to react routers `<Link>` elements to fix whole page reloads in the mobile attendances.
> EVAKA-HOTFIX Changed a-tags to <Link> elements to fix whole page reloads

- apigw/src/enduser/app.ts
- apigw/src/enduser/routes/auth-status.ts
- apigw/src/internal/app.ts
- apigw/src/shared/routes/auth/status.ts
If a request has a CSRF header but no session is active, we want 401
from the authentication check instead of 403 from the CSRF token check.
/auth/status endpoint is a special case that needs the csrf middleware,
because it generates a CSRF token into the session if there isn't any.
> Do CSRF checks after authentication checks

- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/DuplicatePeopleReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/DuplicatePeopleReport.kt
Do not rely on name only when matching duplicate people.
> Use date of birth when matching duplicate people

- frontend/packages/enduser-frontend/src/store/modules/forms.ts
- frontend/packages/enduser-frontend/src/views/applications/daycare-application/daycare-application.vue
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
Once an application is sent, the preferred start date can only be moved forward. Prevent it from both backend and in the UI
```
```
> Evaka fix prevent making start date earlier

- apigw/src/shared/service-client.ts
- service/src/main/kotlin/fi/espoo/evaka/pis/SystemIdentityController.kt
If an Espoo AD profile had no e-mail, `/system/employee-identity` returned status 400 even though e-mail is not really mandatory in the underlying data model.
> Make Espoo AD email optional again

- compose/proxy/nginx.conf
- proxy/nginx.conf.template
Unset `client_max_body_size` in proxy for `*/attachments` paths.
> EVAKA-3464 proxy max body size

- frontend/e2e-test/test/e2e/pages/reports.ts
- frontend/e2e-test/test/e2e/specs/5_employee/application-report.spec.ts
- frontend/packages/employee-frontend/src/components/Reports.tsx
- frontend/packages/employee-frontend/src/components/reports/Applications.tsx
- frontend/packages/employee-frontend/src/components/reports/common.tsx
- Preserve selected care area when adjusting dates
- Add E2E tests for application report
None
Go to Reports section and select application report. Select area (e.g. Espoonlahti) and 
adjust from and to dates in datepicker. The area you selected should remain selected.
```
```
> EVAKA-3985: Preserve filtered area in application report

- frontend/e2e-test/test/e2e/pages/employee/applications/application-list-view.ts
- frontend/e2e-test/test/e2e/specs/2_employee-2/application-search.spec.ts
- frontend/e2e-test/test/e2e/specs/5_employee/unit-editor.spec.ts
- frontend/packages/employee-frontend/src/components/applications/ApplicationsFilters.tsx
- frontend/packages/employee-frontend/src/components/common/Filters.tsx
Fixes: application search unit filter last unit cannot be deselected
```
```
> Evaka: fix deselect last unit in application unit filter

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaChildrenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaFeeDataIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaOrganizerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaPlacementsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUnitIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaChildren.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaOrganizer.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaPlacements.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
Instead of doing Varda integration in large transactions that are open during http calls, open small ones for specific updates so that there's a greater chance of consistency between Varda and our database.
> Use smaller transactions in Varda integration

- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
Previously the connection would immediately close after the new varda update thread is created.
> Run varda update in an async job

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
Delete derived decisions from Varda if the data is incomplete. The reasoning is that if there's a placement without a corresponding service need it's unlikely that the data is very reliable anyway. Some of these cases have been placements that span only one day months after the child has actually been in daycare.
Also, do not include decisions that only have a temporary service need for the duration. Temporary daycare should be handled separately.
> Varda derived decisions changes

- apigw/src/internal/__tests__/mobile-device-session.ts
- apigw/src/internal/mobile-device-session.ts
- apigw/src/shared/service-client.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/pairing/PairingIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/MobileDeviceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/Pairing.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/PairingQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/PairingsController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/SystemIdentityController.kt
- service/src/main/resources/db/migration/V25__mobile_device_token.sql
- service/src/main/resources/migrations.txt
Instead of directly using the mobile device id in the cookie, use a separate token that can be rotated without having to remove+add actual rows in the mobile_device table.
> [EVAKA-4006] Use a separate token in long term mobile cookie

- frontend/packages/employee-frontend/src/components/unit/MobilePairingModal.tsx
Removed the period after the mobile pairing url. This came up when doing the pairing with the users.
> EVAKA-HOTFIX Removed the period after the mobile pairing url

- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaChildrenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaFeeDataIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaOrganizerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaPlacementsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/MockVardaIntegrationEndpoint.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- service/src/main/resources/db/migration/V27__varda_fee_data_references.sql
- service/src/main/resources/migrations.txt
Base Varda fee data on the actual decision data in Varda instead of doing unreliable pairing with evaka placement data. Since Varda requires fee data to match its decision data this increases reliability of the fee data integration and also prevents the old bug where identical fee data was sent to Varda multiple times.
Clean up related fee data from Varda when deleting a Varda decision. Currently, deleting Varda decisions fails every time they have overlapping fee data in Varda.
Improve the mock Varda client so that the stored data matches the actual operations.
> Improve Varda fee data reliability

- apigw/src/internal/__tests__/mobile-device-session.ts
- apigw/src/internal/app.ts
Requests that require CSRF tokens don't play nice with mobile refresh mechanism -> restrict refresh to /auth/status which is already used to create fresh CSRF state.
From the frontend point of view, this changes responses in expired session scenarios from 403 (Forbidden due to CSRF error) to 401 (Unauthorized due to expired session).
> Only refresh mobile sessions with /auth/status

- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/domain/TimeIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaPlacementsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaPlacements.kt
Send all placements that overlap with decisions to ghost units instead of only placements to the same unit since children should never be placed to a ghost unit.
It might be a good idea to remove the requirement that decision and placement units match altogether.
> Fix Varda placements for decisions to ghost units

- frontend/e2e-test/test/e2e/dev-api/index.ts
- frontend/e2e-test/test/e2e/pages/admin/application-details-page.ts
- frontend/e2e-test/test/e2e/specs/5_employee/application-details.spec.ts
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/Acl.kt
Previously if an application's placement plan was applied (i.e. its decisions were accepted) unit supervisors couldn't read the application unless the applicant had applied to the unit.
> Fix an accepted application's read rights

- frontend/e2e-test/test/e2e/dev-api/data-init.ts
- frontend/e2e-test/test/e2e/dev-api/fixtures.ts
- frontend/e2e-test/test/e2e/dev-api/index.ts
- frontend/e2e-test/test/e2e/specs/5_employee/application-details.spec.ts
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
If the applicant (guardian) has non-disclosure order, do not
automatically send decision to second guardian, even if he/she
didn't have non-disclosure order.
In this case, service worker contacts the guardian to determine where
and how to send the decision.
- Create an application with first guardian having non-disclosure order and second guardian not having one.
- Handle the application all the way to the decision phase
- Make sure the second guardian does not receive the decision as a Suomi.fi message
> EVAKA-4098: Improve decision sending if non-disclosure order in place

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/service/persondetails/VTJPersonDetailsService.kt
- service: incl. exceptions in logs where available
- By providing the exception object to the logger, it can create the 'exception' and 'stackTrace' fields which in turn makes debugging much easier
- This was missing from a few places where exceptions are available, like VTJ error handler
- service: log max fee add failure at debug level
- This is not an actual error but removing it completely loses valuable debug information -> change log level from error to debug
> Service: exceptions to logs where available, change max fee log level

- frontend/packages/enduser-frontend/src/localization/app/en.json
- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/localization/app/sv.json
- frontend/packages/enduser-frontend/src/views/applications/daycare-application/daycare-application.vue
- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/PreschoolTerms.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/DevDataInitializer.kt
- service/src/main/resources/db/migration/V28__preschool_term.sql
- service/src/main/resources/db/migration/V29__preschool_term.sql
- service/src/main/resources/dev-data/preschool-terms.sql
- service/src/main/resources/migrations.txt
- model preschool terms in database
- use them when validating preferred start date
- minimum possible vue changes to validate that preferred start date for preschool cannot be between 5.6.2021 - 31.7.2021 (inclusive).
- next PR: replace other hard-codings
**When deploying run following:**
```
-- 2020-2021
INSERT INTO preschool_term (finnish_preschool, swedish_preschool, extended_term, application_period)
VALUES (
'[2020-08-13,2021-06-04]',
'[2020-08-18,2021-06-04]',
'[2020-08-01,2021-06-04]',
'[2020-01-08,2020-01-20]'
);
-- 2021-2022
INSERT INTO preschool_term (finnish_preschool, swedish_preschool, extended_term, application_period)
VALUES (
'[2021-08-11,2022-06-03]',
'[2021-08-11,2022-06-03]',
'[2021-08-01,2022-06-03]',
'[2021-01-08,2021-01-20]'
);
```
> EVAKA-4040: preschool terms

- frontend/e2e-test/test/e2e/pages/admin/application-workbench-page.ts
- frontend/e2e-test/test/e2e/specs/1_application/club-application.spec.ts
- frontend/e2e-test/test/e2e/specs/1_application/daycare-application.spec.ts
- frontend/e2e-test/test/e2e/specs/2_employee-2/application-transitions.spec.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/placement-draft/PlacementDraft.tsx
- frontend/packages/employee-frontend/src/types/placementdraft.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementPlanIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanDraft.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
User should be notified about restricted details when they are creating a placement draft.
> EVAKA-FIX: notice restricted details on placement draft dialog

- frontend/e2e-test/test/e2e/specs/4_invoicing/invoices.spec.ts
For now we shouldn't assume invoice rows to always be in the same order
> EVAKA_FIX: flaky invoicing test

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
Service managers accidentally delete parentships when head of family changes. This causes errors in invoicing. Change the delete confirmation text to tell what the correct procedure is.
> Add advisory text that instead of deleting a parentship to a mod & add

- bin/add-license-headers.sh
- compose/docker-compose.keycloak.yml
- compose/keycloak/configuration/entrypoint-configuration.sh
- compose/keycloak/configuration/entrypoint-realm.sh
- compose/keycloak/configuration/evaka.json.license
- compose/keycloak/ldap/Dockerfile
- compose/keycloak/ldap/README.md
- compose/keycloak/ldap/ldap-docker-compose.yaml
- compose/keycloak/ldap/ldap.conf.license
- frontend/packages/employee-frontend/src/utils/placements.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/SystemIdentityControllerTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/PreschoolTerms.kt
- service/src/main/resources/dev-data/preschool-terms.sql
- reuse: update to 0.12.1 and fix script
- Accidentally assumed a local `reuse` installation for the `addheader` command in our helper script instead of using the Docker container used for `lint` -> use the Docker container for all `reuse` actions
- Update `reuse` to 0.12.1 to add support for `.ts` and `.tsx`
- Add missing license headers
> Add missing licenses, update reuse tool

- .circleci/config.yml
- frontend/e2e-test/test/e2e/pages/citizen/citizen-homepage.ts
- CI: Only push built tags for proxy (with `ecr-push`)
- Update to the latest `voltti/builder-aws` to use the fixed version of `ecr-push` that only pushes the tags it creates instead of pushing all local tags
- Local cache can contain tags from other builds when Docker Layer Caching is active and we obviously don't want to push any other tags (and spend time doing so)
- CI: Large image build speedup with Docker Layer Caching
- Even though the cost of DLC is a bit ridiculous, both API gateway and service image builds currently benefit pretty significantly from layer caching (~30-40s vs 1-2s Docker builds)
- CI: Checkout and base image build small speedups
- CI: Update Slack orb & remove config duplication (matrix jobs, inline once-used aliases, parametrize jobs instead of duplicating)
- …
> CI: ensure only built proxy tags are pushed, general updates

- frontend/packages/enduser-frontend/src/localization/app/fi.json
- frontend/packages/enduser-frontend/src/localization/app/sv.json
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
When user downloads an attachment, we use the file's UUID instead of it's original name and hence lose the file extension. Now it's parsed from the original name and appended to UUID. 
Also fixed some missing translations related to attachments.
> EVAKA-HOTFIX: include file extension to attachment name

- frontend/packages/employee-frontend/src/components/absences/AbsenceCell.tsx
Apparently staff in the original daycare should not mark absences during
the backup care period. Maybe supervisors could be allowed to do this,
but we don't handle this scenario at all in the UI, so it's probably
better to just disable it.
If we want to add support for supervisors later, we need to gracefully
handle the scenario where a cell has backup care *and* 0-2 absences.
Right now we don't even display absences if they exist, because the
backup care "takes over" the cell.
> Disable editing of absence cells with backup care

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
Send temporary placements separately from other decisions derived from placements since their deduction is quite unreliable and they behave differently compared to regular placements. There is a real risk of the temporary decisions sent to Varda overlapping with regular decisions but it's difficult and unreliable to prevent it without implementing temporary placements differently.
> Add support for temporary placements to Varda integration

- .circleci/config.yml
- message-service/README.md
- message-service/build.gradle.kts
- message-service/buildSrc/src/main/kotlin/Version.kt
- service-lib/build.gradle.kts
- service/README.md
- service/build.gradle.kts
- service/buildSrc/src/main/kotlin/Version.kt
- this one doesn't run a separate Java subprocess -> faster and more CI-friendly
- implement ktlintApplyToIdea by hand since the new plugin doesn't have such a task
> Switch to a different ktlint gradle plugin

- apigw/src/shared/routes/auth/saml/index.ts
- apigw/src/shared/service-client.ts
- frontend/e2e-test/package.json
- frontend/e2e-test/test/e2e/dev-api/index.ts
- frontend/packages/citizen-frontend/package.json
- frontend/packages/citizen-frontend/src/index.tsx
- frontend/packages/employee-frontend/package.json
- frontend/packages/employee-frontend/src/index.tsx
- frontend/packages/enduser-frontend/package.json
- frontend/packages/enduser-frontend/src/main.ts
- frontend/packages/lib-common/src/api.ts
- frontend/yarn.lock
- Safari, IE and older browsers (e.g. Chrome 45 on OS X) don't support `ScrollToOptions` (and equivalent for other scroll methods) at all or `behavior: smooth` when other options are available -> all the browser are still supported, so include a conditional polyfill
- Include polyfill in enduser, employee & citizen frontends
- Polyfill is only applied when `scrollBehavior` isn't supported (`'scrollBehavior' in document.documentElement.style`)
- [`seamless-scroll-polyfill`](https://github.com/magic-akari/seamless-scroll-polyfill) appears to have fixed most of [`smoothscroll-polyfill`](https://github.com/iamdustan/smoothscroll)'s open issues (like SVG support) + adds official TypeScript typings which is nice
- Also update axios to the latest version (0.21.1) that contains vulnerability …
> Smooth scroll polyfill for Safari & IE, update axios

- frontend/packages/employee-frontend/src/components/unit/unit-details/UnitEditor.tsx
- frontend/packages/lib-components/src/molecules/DatePicker.tsx
Tweak css to fit inputs on the same line.
Before:
> EVAKA-FIX: unit editor datepicker widths

- frontend/README.md
- frontend/e2e-test/test/e2e/specs/0_citizen/citizen-decisions.spec.ts
- frontend/e2e-test/test/e2e/specs/1_application/application-attachment.spec.ts
- frontend/e2e-test/test/e2e/specs/1_application/application-validations.spec.ts
- frontend/e2e-test/test/e2e/specs/1_application/transfer-preschool-application.spec.ts
- frontend/e2e-test/test/e2e/specs/2_employee-2/application-search.spec.ts
- frontend/e2e-test/test/e2e/specs/2_employee-2/employee-reads-application.spec.ts
- frontend/e2e-test/test/e2e/specs/5_employee/application-details.spec.ts
- frontend/e2e-test/test/e2e/specs/5_employee/placement-sketching-report.spec.ts
- frontend/eslint-plugin/index.js
- frontend/eslint-plugin/rules/no-duplicate-testcafe-hooks.js
- E2E: Fix duplicate test hooks not being triggered
- Testcafe only allows setting a single hook (of each type) per fixture
- See: https://github.com/DevExpress/testcafe/issues/5839 (not exactly the same thing but the only mention of this I can find)
- E2E: Prevent broken Testcafe hooks with ESLint
- To prevent the above from happening again, create a custom ESLint rule (`no-duplicate-testcafe-hooks`) for catching the issue/"feature"
- Custom ESLint rule documentation
> E2E: fix and add linting for broken Testcafe hooks

- frontend/packages/enduser-frontend/src/components/common/file-upload.vue
- When user has uploaded at least one file and then opens the file picker to upload another but cancels, the input's value is cleared (i.e. the `FileList` is emptied) but the change-event is still triggered -> don't assume the list is always non-empty
- This doesn't affect user uploads, just causes unnecessary errors (and Sentry alerts)
> Fix user canceling second upload causing an error

- service/src/main/kotlin/fi/espoo/evaka/application/DecisionMessageProcessor.kt
- service/src/main/kotlin/fi/espoo/evaka/application/enduser/ApplicationSerializer.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/FamilyInitializerService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- remove ACL check which recently caused problems in prod. We check permissions in the original REST API handling code anyway
- also remove unused user parameter from SEND_DECISION async job
- audited `user: AuthenticatedUser` parameters in async jobs, and it looks like they are now just used in VTJ queries (= "who made the request")
> Remove unnecessary ACL check from DECISION_CREATED async job

- compose/compose-keycloak
- compose/docker-compose.keycloak.yml
- compose/keycloak/.gitignore
- compose/keycloak/configuration/evaka.json
Use <https://github.com/espoon-voltti/evaka-keycloak-theme> project in docker-compose for KeyCloak.
When `./compose-keycloak up` is executed first time the evaka theme should be enabled on <http://localhost:8080/auth/realms/evaka/account>.
> Initial theme installation for KeyCloak

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/common/Select.tsx
- frontend/packages/employee-frontend/src/components/unit/unit-details/UnitEditor.tsx
* Require finance decision handler only for units that are invoiced by municipality
* Require OPH OIDs when unit is marked to be sent to Varda or Koski
> Unit editor validation improvements

- frontend/packages/employee-frontend/src/components/attendances/AbsenceSelector.tsx
- frontend/packages/employee-frontend/src/components/attendances/AttendanceChildComing.tsx
- frontend/packages/employee-frontend/src/components/attendances/AttendanceChildPresent.tsx
After these changes the back button should always return the user to the last page user was before coming to the child page. In practice what this accomplishes is that when user clicks on a child in the list view and marks them present (or does other state transitions) the `history.goBack()` call will return the user to the list page instead of returning to the child page.
> EVAKA-HOTFIX Removed history manipulation from attendance marking

- frontend/e2e-test/test/e2e/pages/reports.ts
- frontend/e2e-test/test/e2e/specs/5_employee/placement-sketching-report.spec.ts
- frontend/packages/employee-frontend/src/components/reports/PlacementSketching.tsx
Child CAN have two applications, if both parents submit one, so instead of child id the application id must be used
> Ensure placement sketching row has unique key

- frontend/packages/employee-frontend/src/App.tsx
- frontend/packages/lib-common/src/utils/idleTracker.ts
This "idle tracker" triggers an /auth/status call if the browser window
becomes visible after being non-visible *and* there is 20 minutes or
more since the last request to backend.
On mobile devices where a valid long term token is available, this means
if you open the browser after it has been hidden, the session is
refreshed and the user can immediately continue (assuming network
connectivity is ok).
On desktop devices, this can do a "force logout" if the session has
already disappeared, but this can actually be better than the current
situation where the application just stops working or throws errors
everywhere.
I'm not 100% happy with the idleTracker abstraction, but it works and we can change it later if necessary.
> Add a mechanism that can refresh mobile sessions

- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/Helpers.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
Use decision approver instead of the unit's finance decision handler as decision handler for relief fee decisions.
> Ignore unit decision handler for relief decisions

- compose/docker-compose.keycloak.yml
`REALM` parameters was missing form KeyCloak docker-compose that caused the container to fail. This adds the correct parameter.
> Add missing realm to keycloak docker-compose

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/unit/tab-groups/Groups.tsx
- service/src/main/kotlin/fi/espoo/evaka/reports/ChildAgeLanguageReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/FamilyContactReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/OccupancyReport.kt
These reports should not be visible for finance admin role.
They were already restricted from the frontend, but this change will also
prevent accessing backend endpoints.
- Child age and language report
- Family contact report
- Occupancy report
> EVAKA-4119: Restrict visibility of certain reports from finance admin

- frontend/e2e-test/test/e2e/pages/citizen/citizen-decisions.ts
- frontend/packages/citizen-frontend/src/applications/ApplicationCreation.tsx
- frontend/packages/citizen-frontend/src/decisions/decision-response-page/DecisionResponse.tsx
- frontend/packages/citizen-frontend/src/decisions/decisions-page/ApplicationDecisionsBlock.tsx
- frontend/packages/citizen-frontend/src/header/DesktopNav.tsx
- frontend/packages/citizen-frontend/src/header/Header.tsx
- frontend/packages/citizen-frontend/src/header/Logo.tsx
- frontend/packages/citizen-frontend/src/header/MobileNav.tsx
- frontend/packages/employee-frontend/src/components/placement-draft/UnitCard.tsx
- frontend/packages/lib-components/src/atoms/buttons/Button.tsx
- frontend/packages/lib-components/src/atoms/buttons/InlineButton.tsx
- frontend/packages/lib-components/src/atoms/buttons/button-commons.tsx
- frontend/packages/lib-components/src/layout/ButtonContainer.tsx
- frontend/packages/lib-components/src/molecules/modals/FormModal.tsx
Make button sets match the UX spec. In short, buttons are in a horizontal layout and fit their content as before, but they expand to take full width of the container and are in a vertical layout when the view gets narrow enough.
Also,
* make the menu in mobile header sticky so that users can't scroll past it
* use `em` for scaling button text
* use `px` in header margins
> Citizen buttons in mobile

- frontend/packages/citizen-frontend/src/applications/editor/AdditionalDetailsSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ContactInfoSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/EditorSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/FeeSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ServiceNeedSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/UnitPreferenceSection.tsx
- frontend/packages/lib-components/src/atoms/buttons/AddButton.tsx
- frontend/packages/lib-components/src/layout/Container.tsx
Collapsible sections for citizen application editor sections. There is already support for validation error indicators.
Also fix `AddButton` styles when `reversed` prop is on.
> Application editor collapsible sections

- frontend/packages/lib-components/src/colors.ts
The removal of `EspooColours` broke them because of misleading naming.
> Fix absence colors

- proxy/nginx.conf.template
Browsers fetch manifests without credentials, so in practice basic auth blocks the manifest completely
I think there's still something wrong, because "Add to home screen" functionality on mobile Chrome shows a spinner for some time (30 seconds?) and then clearly times out. But the manifest and logo are fetched correctly, so it's not clear what the problem is.
> Disable manifest basic auth

- frontend/e2e-test/test/e2e/dev-api/index.ts
- frontend/e2e-test/test/e2e/pages/employee/applications/application-read-view.ts
- frontend/e2e-test/test/e2e/specs/2_employee-2/application-transitions.spec.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/application-page/ApplicationDecisionsSection.tsx
- frontend/packages/employee-frontend/src/types/decision.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- Employee: prevent download attempts for pending decision PDFs
- Replace link with a warning message (see screenshot below)
- The more robust solution would be to do a separate pre-download step (like in enduser-frontend file upload) but this is such an edge case, I felt this to be a satisfactory solution
- Add a simple E2E test case for the new logic
- Service: return 404 instead of throwing an exception when attempting to download a pending decision PDF
- A delay in processing is a valid state as PDF generation is done in a separate async job
- 429 with some arbitrary retry time could've also worked but 404 feels more semantically correct as there's no way of knowing when the user should retry
- Service: create new Dev API endpoint for triggering decision PDF generation (allows for …
> Employee: prevent downloads of pending decision PDFs

- frontend/packages/employee-frontend/src/components/child-information/service-need/ServiceNeedForm.tsx
Show service need hours warning only when the hours go above a part day placement type's threshold since every other placement type gives the right to have less hours per week.
The only exception here is temporary daycare since it can't be part week and it's placement type should always be in sync with service need hours.
> EVAKA-4110 Fix part week placement service need warning

- frontend/e2e-test/package.json
- frontend/e2e-test/test/e2e/pages/employee/units/unit-page.ts
- frontend/e2e-test/test/e2e/specs/5_employee/backup-care.spec.ts
- frontend/packages/employee-frontend/src/components/unit/UnitDataFilters.tsx
This test accidentally depended on the date when the test is executed, and stopped working today when the backup care fixture changed from the future to the past.
> Fix backup care e2e test failure

- service-lib/build.gradle.kts
JUnit 5 ("jupiter") tests were not detected or executed. The tests were updated to use JUnit 5 at some point, but the runner configuration was not added so they haven't been executed for a while.
> Enable JUnit 5 test runner in service-lib

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
Some tests broke because `LocalDate.now().plusMonths(4)` was not within the 2020 preschool term anymore.
> Fix time dependant integration tests

- service-lib/src/main/kotlin/fi/espoo/voltti/logging/loggers/AppMiscLoggers.kt
- service-lib/src/test/kotlin/fi/espoo/voltti/logging/loggers/AppMiscLoggersTest.kt
- service/README.md
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiClient.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- Log Varda and Koski error metadata correctly
- #417 added metadata to Varda logs but the missing `mapOf("meta" to meta)` was missed, resulting in logs where the meta-fields were actually top-level fields
- The KLogger extensions don't actually map directly to the meta-field in our JSON logs but need an extra mapOf(meta to arg) wrapped around them
- Unify Koski error logging with Varda and instead of outputting the whole multi-line error response, log the relevant fields in "meta"
- As a "lesson learned" from the above, map `KLogger` meta-arguments directly to meta-fields
- There isn't a use case for overwriting any other fields than the freeform "meta" (as everything else is provided by the loggers and/or is structured data)
- Handle the extra meta-mapping inside the logger extensions …
> Cleanup Varda and Koski error logs, KLogger extensions

- service/reports/sql/zero_fee_children_by_year.sql
The query to use when getting the biannual report manually.
> EVAKA-4128 add sql for zero fee children report

- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/LocationServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ApplicationsReport.kt
- Fix applications report closing date condition
- Remove opening dates from applicable units queries
Do not use opening and closing dates in applicable units queries. The new application periods should replace them.
Also, fix applications report's closing date condition.
> Stop using opening dates with application periods

- frontend/packages/employee-frontend/src/components/child-information/ServiceNeed.tsx
- frontend/packages/employee-frontend/src/components/child-information/service-need/ServiceNeedRow.tsx
- frontend/packages/employee-frontend/src/components/common/FormActions.tsx
- frontend/packages/employee-frontend/src/components/unit/TabGroups.tsx
- frontend/packages/employee-frontend/src/components/unit/tab-groups/Groups.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/FamilyContactReport.kt
- service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedController.kt
Service worker should not be allowed to
- Create or modify groups in a daycare
- Place children into groups (or transfer them within groups)
- Retrieve family contact details report
- Add or edit service needs
All these actions are unit supervisor's duty. However, service worker is allowed to list groups,
children in groups, service need etc.
For some endpoints, there was even wider set of roles allowed, cleaned those as well.
> EVAKA-4135: Restrict certain access rights from service worker

- frontend/packages/lib-components/src/atoms/buttons/AsyncButton.tsx
- The actual height of the spinner is `height` + (`border-width` x 2), i.e. not 24px (which is the container's height/width) but 24px + 2px + 2px = 28px
- Instead of increasing the containers size and therefore altering the other elements of the button (namely the text/content), reduce spinner size by 4px so it actually is 24px
Before:
After:
> lib-components: fix AsyncButton spinner clipping

- frontend/e2e-test/test/e2e/pages/employee/units/units-page.ts
- frontend/e2e-test/test/e2e/specs/5_employee/units.spec.ts
- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/Units.tsx
- frontend/packages/employee-frontend/src/state/units.tsx
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
Hide closed units from units page list unless the "include closed" checkbox is checked. Also, leave out units with closing date before the query date in application units queries.
> Hide closed units

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/PendingDecisionEmailServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
It is common to have two simultaneous pending decisions as preschool and preschool daycare is applied together.
Instead of sending a reminder email per pending decision only send one per guardian if any pending decisions exists. 
REMINDER: delete current pending SEND_PENDING_DECISION_EMAIL async jobs when deploying this to staging
> Only send one pending decision email per guardian

- frontend/packages/employee-frontend/src/components/person-profile/PersonFridgeChild.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/ParentshipControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/ParentshipController.kt
If there is a parentship relation created, removing it should not be
done on light terms. This change will restrict unit supervisors from
removing created parentship relation. If there is a need to remove this
relation, it should be done by either `ADMIN` or `FINANCE_ADMIN` (given
they know whether the change on parentship will have an effect on the
fee decisions).
> EVAKA-4133: Restrict removing parentship from unit supervisor

- frontend/packages/citizen-frontend/src/applications/editor/validations.ts
Summary:
Prevent form check error if the user selects `Children under 18 living in the same address` and immediately deselects.
> Filter empty other children on submit citizen application

- frontend/packages/citizen-frontend/src/applications/editor/contact-info/GuardianSubSection.tsx
Now that DatePicker supports alerts, this box doesn't look great. Let's remove it.
> Remove an unnecessary alert box from citizen-frontend

- proxy/nginx.conf.template
* leaflet configuration specifies `a`/`b`/`c` domain prefixes to support parallel loading of tiles
> Add CSP directives needed for map

- frontend/packages/citizen-frontend/src/localization/en.tsx
Added so ad hoc english translations for things that were still in finnish.
Still missing the translation for this:
```
CLUB: function EditorHeadingInfoClubText() {
return (
<>
<P>
Hakuaika syksyllä käynnistyviin kerhoihin on maaliskuussa. Jos
lapsenne saa kerhopaikan, saatte päätöksen siitä
huhti-toukokuun aikana. Päätös tehdään yhden toimintakauden
ajaksi (elokuusta toukokuun loppuun). Päätös kerhopaikasta
tulee Suomi.fi-palveluun tai postitse, mikäli ette ole ottanut
palvelua käyttöön.
</P>
<P>
Kerhohakemuksen voi jättää myös hakuajan ulkopuolella ja sen
jälkeen, kun kerhojen toimintakausi on jo alkanut. Hakuaikana
saapuneet hakemukset käsitellään kuitenkin ensin, ja hakuajan
ulkopuolella tulleet hakemukset käsitellään
saapumisjärjestyksessä. Kerhohakemus kohdistuu yhdelle …
```
> EVAKA-HOTFIX added some ad hoc english translations

- proxy/nginx.conf.template
- Missed config update when swapped from enduser-frontend to citizen-frontend being the root route
- The flow goes: "/decisions" request -> "location /" matches, rewrites to "/citizen/decisions" -> static handler fails to find file -> static error handler rewrites to "/citizen/index.html"
1. Go to https://evaka.test.espoon-voltti.fi/decisions -> 404
1. Wait for CI to deploy to dev
2. Open https://evaka.dev.espoon-voltti.fi/decisions -> redirects correctly
Compose's proxy is a bit different due to the mounting vs. S3 proxying difference so can't really be tested against it.
> Proxy: redirect non-file citizen URLs to index.html

- frontend/e2e-test/.testcaferc.json
- frontend/e2e-test/injected.js
- frontend/e2e-test/test/e2e/dev-api/fixtures.ts
- frontend/e2e-test/test/e2e/dev-api/index.ts
- frontend/e2e-test/test/e2e/dev-api/types.ts
- frontend/e2e-test/test/e2e/pages/citizen/citizen-map.ts
- frontend/e2e-test/test/e2e/specs/0_citizen/citizen-map.spec.ts
- frontend/e2e-test/test/e2e/utils/helpers.ts
- frontend/packages/citizen-frontend/src/map/MapBox.tsx
- frontend/packages/citizen-frontend/src/map/MapView.tsx
- frontend/packages/citizen-frontend/src/map/SearchInput.tsx
- frontend/packages/citizen-frontend/src/map/SearchSection.tsx
- frontend/packages/citizen-frontend/src/map/UnitDetailsPanel.tsx
- frontend/packages/citizen-frontend/src/map/UnitListItem.tsx
- frontend/packages/citizen-frontend/src/map/api.ts
- frontend/packages/citizen-frontend/webpack.config.js
- frontend/packages/lib-common/src/utils/helpers.ts
- frontend/packages/lib-components/src/atoms/Chip.tsx
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/MockDigitransit.kt
* add basic E2E tests for the map page. Not all functionality is tested
* add a flag for detecting frontend is running an E2E test
* digitransit API is replaced with static mock responses + configurable dev api. Using dev API to set the mock response guarantees the test data is local to the actual E2E test, instead of the test relying on some data in a completely different place
> [EVAKA-4115] Map page E2E tests

- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiPayloadIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiClient.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
Organization OID = "Espoo"
Organizer OID = "Espoo" or possibly "SomePrivateDaycareCompany Oy" (purchased/voucher)
:arrow_down: 
* use *organization* (not the *organizer*) as the "caller ID" when making Koski requests
* the manager of the preschool unit is working for the *organizer*, but the *organization* using eVaka confirms the studies -> swap OIDs in Koski data
> Minor Koski OID usage fixes

- service/src/integrationTest/resources/application-integration-test.yaml
- service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
Disable pending decision email sending by default to allow production dry run testing
> Disable pending decision email sending for testing

- frontend/packages/citizen-frontend/src/map/MapBox.tsx
Safari blocks all other content under address bar and navigation buttons which makes it impossible to scroll out. This should make the situation better even on tallest iphones.
> Make map box shorter in mobile

- frontend/packages/lib-components/src/atoms/form/InputField.tsx
Use `1rem` font size for inputs. This makes sure that inputs scale up with user's browser's font size and also disables automatic zooming on input focus on ios. Ios safari is automatically zoomed in on an input if its font size is smaller than `16px`.
> EVAKA-HOTFIX input text size

- frontend/packages/citizen-frontend/src/decisions/decision-response-page/DecisionResponse.tsx
- frontend/packages/employee-frontend/src/components/common/Filters.tsx
- frontend/packages/lib-components/src/atoms/form/Radio.tsx
This enables using any kind of `ReactNode` as a label for a `Radio` component. Non string type elements require a separate aria label for accessibility. Main motivation is to fix the citizen decision accept radio option.
Before: 
After:
> Allow non-string elements as labels for Radio

- frontend/packages/citizen-frontend/src/index.css
- frontend/packages/citizen-frontend/src/index.html
- frontend/packages/citizen-frontend/src/index.tsx
- Move base styles to `index.css`, out of `index.html`
- Inherit font styles for buttons, inputs etc. from global styles
- By default, browser styles would override e.g. font family configuration
- NOTE: Decided to exclude `min-width` for `html` as that's not really the business of the reset to configure
> Citizen: add basic CSS reset

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/PendingDecisionEmailServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
Do not send pending decision reminder emails for decisions older than 2 months
> Do not send pending decision reminder emails for old decisions

- frontend/packages/citizen-frontend/src/applications/ApplicationCreation.tsx
- frontend/packages/citizen-frontend/src/applications/editor/AdditionalDetailsSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/contact-info/ChildSubSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/contact-info/GuardianSubSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/service-need/AssistanceNeedSubSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/service-need/PreferredStartSubSection.tsx
- frontend/packages/citizen-frontend/src/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx
- frontend/packages/citizen-frontend/src/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
- frontend/packages/citizen-frontend/src/localization/en.tsx
- frontend/packages/citizen-frontend/src/localization/fi.tsx
- frontend/packages/citizen-frontend/src/localization/sv.tsx
- frontend/packages/lib-components/src/atoms/form/Checkbox.tsx
- frontend/packages/lib-components/src/atoms/form/Radio.tsx
- frontend/packages/lib-components/src/molecules/ExpandingInfo.tsx
Align Radio and Checkbox label content with the center of the icon. Also add a small margin to the top of ExpandingInfo's icon to align it with text and use a localized aria label.
> EVAKA radio and checkbox layout

- frontend/packages/citizen-frontend/src/applications/ChildApplicationsBlock.tsx
- frontend/packages/citizen-frontend/src/applications/editor/ApplicationEditor.tsx
- frontend/packages/lib-components/src/layout/flex-helpers.ts
Scroll to top of application verification view because smooth scrolling breaks if it happens during rendering.
Remove `flexWrap` prop from `FixedSpaceRow` since `FixedSpaceFlexWrap` should be used instead.
Fix `FixedSpaceFlexWrap` width, `width: 100%` actually makes the element too short.
> EVAKA-HOTFIX minor citizen improvements

- frontend/packages/employee-frontend/src/assets/i18n/fi.ts
- frontend/packages/employee-frontend/src/components/person-profile/income/IncomeItemBody.tsx
- frontend/packages/employee-frontend/src/types/income.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Incomes.kt
- service/src/main/resources/db/migration/V42__income_references_application.sql
- service/src/main/resources/migrations.txt
Let `income` reference `application` when it originates from one. 
Show employee that income is created from application. 
Postpone income creation to the point where enduser accepts decision.
> EVAKA-4122 tweak income from application

- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/domain/TimeIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
Alters the behavior of part months invoices for children in round the clock units. Previously the daily prices used in part month invoices would be calculated as a fraction of a units total operational day count, but now we use the same daily price for all units. In the case of round the clock units, which have more operational days that other units, it means that we only count as many operational days in a week as a "regular" unit would have. The code assumes that round the clock units mark absences only for the days that a child is supposed to come to daycare. That is the way that Espoo does things currently.
> EVAKA-4147 part month invoices for round the clock units

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunnerTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/Main.kt
* this is better for other cities, because they are explicitly required to provide an alternative implementation (vs. accidentally using a mock or Espoo client)
* also remove Spring stuff from AsyncJobRunnerTest since it's no longer needed. This makes it possible to put the mock client in `SharedIntegrationTestConfig`, which is now only used by bigger Spring tests
> Move Espoo client to profile-activated config

- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
In our terminology this can seem confusing, but it's the correct way from the Koski point of view.
This should fix the majority of current Koski upload errors, since permission checking works differently in Koski with the "purchased" type
> Private daycares should use "purchased" type in Koski

- compose/proxy/nginx.conf
- proxy/nginx.conf.template
We need to be able to allow form-action URLs for KeyCloak SAML authentication. Also cleared proxy parameters so there is no duplicates.
> Allow KeyCloak SAML requests

- proxy/nginx.conf.template
KeyCloak need bigger Nginx proxy buffers.
> Increase proxy buffers for KeyCloak to avoid gateway issues

- service-lib/src/main/kotlin/fi/espoo/voltti/logging/SsnMasker.kt
- service-lib/src/main/resources/fi/espoo/voltti/logging/logback/default-appender-sanitized.xml
- service-lib/src/test/kotlin/fi/espoo/voltti/logging/logback/AppenderTest.kt
Use a `ValueMasker` to hide ssns from all log fields. Uses the same regex used previously for masking `message` and `stackTrace` fields.
> EVAKA-HOTFIX hide ssn from log meta fields

- service/src/main/kotlin/fi/espoo/evaka/shared/Paging.kt
If there are no results, employee application list breaks with org.postgresql.util.PSQLException: ERROR: OFFSET must not be negative because page=0 whereas it should be 1. This fixes the default value to 1.
> Fix empty result pagination

- frontend/src/citizen-frontend/localization/fi.tsx
Use correct wording in instructions: Use "varhaiskasvatuspaikka" instead of "hoitopaikka".
> EVAKA-4140: Use correct wording in instructions

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailService.kt
- Invalid href value (missing protocol) caused links to be output as [link]link instead of being valid links
- Update "application received" email's Finnish and Swedish texts per new spec
> [EVAKA-4159] Fix application received email links and update texts

- frontend/src/employee-frontend/components/ChildInformation.tsx
- frontend/src/employee-frontend/components/PersonProfile.tsx
- frontend/src/employee-frontend/components/layouts.ts
- explicit layouts for each role, no default
- use role layout combination hotfix only when user has more than 1 role
> EVAKA-4168: hotfix child view role based layout

- frontend/src/citizen-frontend/applications/editor/unit-preference/PreferredUnitBox.tsx
- frontend/src/citizen-frontend/localization/en.tsx
- frontend/src/citizen-frontend/localization/fi.tsx
- frontend/src/citizen-frontend/localization/sv.tsx
- Link to espoo.fi for official documentation on service vouchers instead of wikipedia
- Use translations like with other links to allow separate links based on user language
- Also fix Swedish service voucher link in map view (linked to more general info page, although there's a service voucher specific page)
> [EVAKA-HOTFIX] Fix application editor service voucher links

- frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx
- frontend/src/citizen-frontend/applications/editor/ApplicationFormData.ts
- frontend/src/citizen-frontend/applications/editor/validations.ts
- frontend/src/citizen-frontend/decisions/api.ts
- frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponse.tsx
- frontend/src/lib-common/local-date.ts
- frontend/src/lib-components/molecules/date-picker/DatePickerDay.tsx
Change `parseFi` calls to `parseFiOrNull` and when using `parseFi` wrap them in a `try...catch`. This should help out with the sentry errors.
> EVAKA-HOTFIX handle parsefi throws better

- service/reports/sql/zero_fee_children_by_year.sql
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueAreaReportTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
- service/src/main/resources/db/migration/V46__voucher_value_report_snapshot_taken.sql
- service/src/main/resources/migrations.txt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
This PR has integration tests for voucher value report's different cases.
Also start using `WAITING_FOR_SENDING` and `WAITING_FOR_MANUAL_SENDING` statuses similarly as `SENT` when data from decisions that are in effect is needed. Since the database prevents multiple decisions with those statuses from being in effect simultaneously, they should all be treated similarly to prevent inconsistencies in invoicing or voucher value reporting.
Also add a `taken_at` timestamp to voucher value report snapshots that should be used in business logic instead of the more technical `created` timestamp.
> EVAKA-4016 tests for voucher value report

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
Use an `Instant` instead of `LocalDate` to set a fee decision's `approved_at` value to get an accurate timestamp.
> EVAKA-HOTFIX fee decision approved_at timestamp

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailService.kt
- No separate English message is sent but instead the texts should be prepended to the Finnish messages
- Decided to use the hr-element to split the sections
> [EVAKA-4159] Add English application received email texts

- apigw/generate-jwts.ts
- apigw/src/internal/app.ts
- apigw/src/shared/auth/ad-saml.ts
- apigw/src/shared/auth/index.ts
- apigw/src/shared/auth/jwt.ts
- apigw/src/shared/config.ts
- Rename espoo-ad-saml.ts as ad-saml.ts
- Remove the word "espoo" from code
- Parameterize externalId, logout url, entrypoint url
Requires https://github.com/espoon-voltti/evaka-infra/pull/365
> Generalize AD SAML code by making espoo specific things configurable

- apigw/src/pino-cli/__tests__/cli/bin.ts
- apigw/src/pino-cli/cli/index.ts
- apigw/src/pino-cli/test-utils/fixtures/log-messages.ts
- apigw/src/shared/routes/auth/saml/error-utils.ts
- apigw/src/shared/routes/auth/saml/index.ts
- compose/build.sh
- APIGW: add tracing support for all log types and request parameters to all logging calls (where available)
- Add initial `parentSpanId` support for access logs
- Include `parentSpanId`, `spanId` and `traceId` support in all pino-cli log types, not just access logs
- This will help in debugging some SAML issues that are hard to pinpoint due to duplicate events / double-clicking
- Compose: fix frontend build regression in build script
- The frontend build was accidentally removed during frontend build rework, add it back
- Remove unnecessary ICONS checks from compose build script
- Environment variables are already passed to all build commands and otherwise free & pro icons builds are identical
> [EVAKA-HOTFIX] Add tracing support for all APIGW log types, fix compose build script

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/PDFServiceTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
Do not give discounts for "planned absences". They are only used to indicate a child's schedule and are not actual absences.
> EVAKA-HOTFIX planned absences and discounts

- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/reports/VoucherServiceProviderUnit.tsx
- frontend/src/employee-frontend/components/reports/VoucherServiceProviders.tsx
- frontend/src/employee-frontend/types/reports.ts
- frontend/src/employee-frontend/utils/useSyncQueryParams.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
* Add an indicator for 'new' voucher report rows
* Store voucher report filters in url so that page refresh and navigation do not reset the filters
* Add unit name filter to area voucher report
* Enable estimated future voucher reports
* Add toggleable sorting by group name
* Remove the "coefficient" column from the report since it should show a coefficient that does not exist in our model yet
> EVAKA-4016 more voucher report UX improvements

- service/src/main/kotlin/fi/espoo/evaka/messaging/daycarydailynote/DaycareDailyNoteQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
Scheduled endpoint for deleting expired daycare daily notes made for children
- notes modified at least 12h ago for children placed in non round the clock daycares
- round the clock daycare notes will be deleted manually
- group note deletion will be added later with the editor implementation
> Endpoint for scheduled removal of expired child daycare daily notes

- frontend/src/employee-frontend/api/parentships.ts
- frontend/src/employee-frontend/components/person-profile/PersonFridgeChild.tsx
- frontend/src/employee-frontend/components/person-profile/person-fridge-child/FridgeChildModal.tsx
- frontend/src/employee-frontend/types/fridge.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/ParentshipControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionGeneratorController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/ParentshipQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/ParentshipController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/FamilyInitializerService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/ParentshipService.kt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
Check that new or updated fridge child-parent relationships are effective only before the child turns 18 and after the child has been born.
Data has to be updated manually so that it matches these constraints.
> Fridge child duration checks

- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
Added a test to verify that decisions to voucher units are sent to Varda.
> EVAKA-4075 voucher decisions to Varda

- service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
Round the clock unit supervisors should be able to open "extended care" attachments for applications with a placement proposal to their units.
> Allow round the clock unit supervisors to open application attachments

- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinNotificationEmailService.kt
Revert having simple way to handle unsupported languages, ie. to avoid eg.
```
Unexpected error (no Language value could be matched to the name et)
```
> EVAKA-FIX Parse bulletin notification language from string

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaFeeDataIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaFeeData.kt
- service/src/main/resources/db/migration/V49__varda_voucher_values.sql
- service/src/main/resources/migrations.txt
Send voucher value decisions to Varda. In essence the fee data integration stays the same, voucher value decision data is just included in the data sets with `UNION`.
> EVAKA-4027 send voucher decisions to Varda

- frontend/src/employee-frontend/api/family-overview.ts
- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/ChildInformation.tsx
- frontend/src/employee-frontend/components/child-information/FamilyContacts.tsx
- frontend/src/employee-frontend/types/family-overview.ts
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/FamilyContact.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/FamilyController.kt
- service/src/main/resources/db/migration/V53__create_family_contacts_table.sql
- service/src/main/resources/migrations.txt
Allow assigning priority to family contacts. If a child has no family contact priorities assigned, by default the guardian living with the child is assigned priority 1 and the other guardian is assigned priority 2. The family contacts section is added to service worker and unit supervisor layout so that they are able to read and edit the information.
> EVAKA-4031 child family contacts

- apigw/src/internal/__tests__/csrf.ts
- apigw/src/internal/mobile-device-session.ts
- apigw/src/internal/routes/auth-status.ts
- apigw/src/shared/auth/ad-saml.ts
- apigw/src/shared/auth/index.ts
- apigw/src/shared/auth/keycloak-saml.ts
- apigw/src/shared/auth/suomi-fi-saml.ts
- apigw/src/shared/routes/auth/saml/types.ts
- apigw/src/shared/service-client.ts
- apigw/src/shared/test/gateway-tester.ts
- frontend/src/e2e-test/specs/2_employee-2/employee-dailynote.spec.ts
- frontend/src/e2e-test/specs/6_mobile/attendances.spec.ts
- frontend/src/e2e-test/specs/6_mobile/dailynotes.spec.ts
- service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/SystemIdentityController.kt
- service/src/main/resources/db/migration/V54__employee_only_global_roles.sql
- service/src/main/resources/migrations.txt
* pass roles in two arrays to apigw, separating "global" and "scoped" roles. This separation will later be applied to frontend and service code as well to avoid mixing the two types of roles accidentally
* remove old leftover scoped roles from employee table `roles` column, which is supposed to only contain global roles
* add database constraint to prevent scoped roles from being added to the employee table
* refresh apigw session roles in /auth/status endpoint if they have been changed in the database. In practice this means a page reload is enough for changes in user roles to be applied in frontend (no longer needs logout + login!)
> Refresh user roles on page load + refactor role data model in apigw slightly

- .circleci/config.yml
- README.md
- CI: Don't run jobs for fork branches, only origin
- All jobs currently require secrets due to Slack notifications -> need to stop already at checkout
- **NOTE:** This does not prevent our actual workflow for fork pull requests where we push the references to origin as then `CIRCLE_BRANCH` will be our name for it, instead of `pull/[0-9]+` and the CircleCI setting "Build forked pull requests" will enable the builds (a bit confusingly, I admit)
- Docs: CI for forked PRs
> [EVAKA] CI workflow for forked PRs

- frontend/src/employee-frontend/assets/i18n/fi.ts
Change wording in Finnish translation:
`Kielellinen erityisvaikeus` --> `Kielellinen vaikeus`
> EVAKA-4182_change-wording-in-linguistic-challenge-translation

- service/src/main/resources/application-local.yaml
Add missing local vars `application.frontend.baseurl` and `application.frontend.baseurl.sv`
> EVAKA-HOTFIX: add missing local env vars

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/PendingDecisionEmailServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
- Pending decision reminder emails were being sent related to decisions that were already accepted. Fix the bug and add a test.
- To ease up further debugging do not clean up related finished async_job
- Fix svebi phone number
> Evaka hotfix pending email send

- frontend/src/e2e-test/pages/reports.ts
- frontend/src/e2e-test/specs/5_employee/application-report.spec.ts
- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/reports/Applications.tsx
- frontend/src/employee-frontend/types/reports.ts
- Add missing `PRIVATE_SERVICE_VOUCHER` translation to frontend.
- Add type safety `unitProviderType` access. Adding new values to `ProviderType` now properly triggers lint errors.
- Refactor application report test with proper setup and teardown.
> EVAKA-4155 Applications report voucher fix

- frontend/src/employee-frontend/components/messages/MessageList.tsx
Format receivers according to Figma.
> EVAKA-4171 format bulletin receivers in sent & draft lists

- compose/README.md
- compose/ecosystem.config.js
* Fix development environment URLs in `compose/README.md`
* Run `yarn` and `yarn clean` in the correct order in pm2. Now, any manual `yarn` runs are not required before `pm2 start`.
> Compose fixes

- evaka-bom/.gitignore
- evaka-bom/build.gradle.kts
- message-service/build.gradle.kts
- message-service/buildSrc/src/main/kotlin/Version.kt
- message-service/owasp-suppressions.xml
- message-service/settings.gradle.kts
- service-lib/build.gradle.kts
- service/build.gradle.kts
- service/buildSrc/src/main/kotlin/Version.kt
- service/owasp-suppressions.xml
- service/settings.gradle.kts
- service/vtjclient/build.gradle.kts
* doesn't apply to Gradle plugins, ktlint, or build script dependencies
* one place for dependency constraints -> better consistency between evaka-service and evaka-message-service
* allows downstream projects (e.g. trevaka) to depend on the BOM and get the same version constraints automatically
> Use a BOM module to constrain dependencies

- message-service/owasp-suppressions.xml
- No real risk in our context/use case (no OAuth + only server-to-server comms)
> OWASP: suppress msg-service non-risk vuln

- frontend/src/employee-frontend/components/reports/Applications.tsx
- missing column
- also caused the `r.total` sum column to align incorrectly
> Add missing sum column to applications report

- bin/add-license-headers.sh
The reuse tool assumes it can see the git repository root, so we need to
ensure we mount the whole git repository as a docker volume and not just
the working directory, which might be a git submodule and doesn't have a
.git directory.
> Support running add-license-headers.sh within a submodule

- service/src/main/kotlin/fi/espoo/evaka/vtjclient/config/KeyManagerConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/config/TrustManagerConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/config/XroadSoapClientConfig.kt
- service/src/test/kotlin/fi/espoo/evaka/vtjclient/config/KeyManagerConfigTest.kt
Trevaka requires basic authentication in the http request which is
possible with HttpComponentsMessageSender.
> Allow web service message sender customization

- frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx
- frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx
- frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
- frontend/src/employee-frontend/api/applications.ts
- frontend/src/lib-common/api-types/application/ApplicationDetails.ts
- service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
- service/src/main/resources/db/migration/V61__add_received_date_to_attachment.sql
- service/src/main/resources/db/migration/V62__add_indexes_to_attachment.sql
- service/src/main/resources/migrations.txt
- Add `receivedAt` to Attachment, use `updated` as the initial value
- `receivedAt` can later be updated by service workers to the actual date that may differ from the upload date
- Also add missing indexes to columns that are used in queries
>  EVAKA-4160 Add receivedAt and missing indexes to attachment

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
`urgent` might be null, default to false to fix non-nullable field.
> Fix maybe-null urgent flag in application summary query

- frontend/src/e2e-test/pages/employee/messaging/messages-page.ts
- frontend/src/e2e-test/specs/7_messaging/sending-and-receiving-bulletins.spec.ts
- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/messages/api.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/BulletinIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinControllerEmployee.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinQueries.kt
Let user choose sender from a dropdown instead of using free text input field. Under the hood, this `sender` is just a string and not a reference.
> EVAKA-4171 bulletin sender dropdown

- frontend/src/citizen-frontend/localization/fi.tsx
- frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx
- Fix Finnish `assistanceNeedInstructions`.
- The dimmed _attachment missing_ text was supposed to be on its own line.
Without attachments:
With attachments:
> Fix missing attachments positioning and Finnish assistance need instructions

- frontend/src/e2e-test/pages/employee/applications/application-read-view.ts
- frontend/src/e2e-test/specs/2_employee-2/application-attachments.spec.ts
- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
- frontend/src/employee-frontend/components/common/Attachment.tsx
Show `receivedAt` in attachment list by mapping received timestamp string to LocalDate while deserializing (wonder if we should have `LocalDateTime` too).
> EVAKA-4160 Show receivedAt in attachment list

- frontend/src/e2e-test/pages/citizen/citizen-application-editor.ts
- frontend/src/e2e-test/pages/employee/applications/application-edit-view.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationUpdateIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
Set application due date based on attachments for urgent applications
If the application is urgent:
- the due date should not be set at all if attachments are missing
- the due date is the day application is sent or the first attachment received date, whichever is later
> EVAKA-4160 urgent due date based on attachments

- frontend/src/employee-frontend/components/common/CheckedRowsInfo.tsx
- frontend/src/lib-components/atoms/buttons/AddButton.tsx
- frontend/src/lib-components/atoms/buttons/Button.tsx
- frontend/src/lib-components/atoms/buttons/InlineButton.tsx
- frontend/src/lib-components/typography.ts
- All dimmed text on white background should use #6e6e6e instead of #b1b1b1 to be contrast compliant.
- Same goes for disabled buttons
> WCAG contrast compliance tweaks

- frontend/src/employee-frontend/components/application-page/ApplicationNotes.tsx
- frontend/src/lib-components/atoms/buttons/AddButton.tsx
- frontend/src/lib-components/atoms/buttons/Button.stories.tsx
- frontend/src/lib-components/atoms/buttons/InlineButton.tsx
Fixes WCAG compliance on light grey background.
Design system: Button color is exceptionally #013C8c if it's on light grey background.
Also add `cursor: not-allowed;` to disabled AddButton. Update stories.
> Add support for darker inline and add buttons

- frontend/src/lib-components/.storybook/preview-head.html
> Apply global styles in storybook stories so that fonts work

- frontend/src/e2e-playwright/pages/employee/child-information.ts
- frontend/src/e2e-playwright/specs/5_employee/child-information.spec.ts
- frontend/src/e2e-playwright/utils/element.ts
- frontend/src/employee-frontend/components/child-information/DailyServiceTimesSection.tsx
- frontend/src/employee-mobile-frontend/assets/i18n/fi.ts
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceDailyServiceTimes.tsx
- UX improvements:
- Require at least one day to be selected in irregular times
- Show irregular time inputs only after checking the checkbox for that day
- Show time input errors only after they've been touched
- Mobile: Indicate not set daily service times
- Add employee side e2e tests
- Reduce duplication in employee-side code
> EVAKA-4157 Daily service times UX enhancements & E2E tests

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceUpkeepIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pairing/PairingIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueAreaReportTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/JdbiExtensionsTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/PreschoolTerms.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/ChildRecipientsController.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/Pairing.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/PairingQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/PairingsController.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/JdbiExtensions.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/HelsinkiDateTime.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/utils/Time.kt
- service/src/test/kotlin/fi/espoo/evaka/shared/domain/HelsinkiDateTimeTest.kt
- basically a wrapper for `Instant` with an implicitly defined but guaranteed Europe/Helsinki timezone
- consistent serialization with Jackson and JDBI, which takes care of interpreting the timestamp in the correct time zone. Serialization to/from a zoneless timestamp throws an error, so "local date time" type of values are not accidentally used
- `from()` functions always re-interpret the given timestamp in Europe/Helsinki
- `to*()` functions and serialization always guarantee the resulting value is in Europe/Helsinki
- switch to `HelsinkiDateTime` in pairing functionality as a demo
> Add experimental HelsinkiDateTime type

- frontend/src/e2e-test/pages/employee/applications/application-read-view.ts
- frontend/src/e2e-test/specs/2_employee-2/application-attachments.spec.ts
- frontend/src/employee-frontend/assets/i18n/fi.ts
- frontend/src/employee-frontend/components/common/Attachment.tsx
- frontend/src/lib-common/api-types/application/ApplicationDetails.ts
- service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Show that attachment is (or is not) uploaded by employee. For now this is indicated only in the application read view for the FileUpload component is too general for context dependant details like this (discussed & approved with UX).
> EVAKA-4160 show attachment uploader 

- message-service/build.gradle.kts
- message-service/buildSrc/build.gradle.kts
- service-lib/build.gradle.kts
- service/build.gradle.kts
- service/buildSrc/build.gradle.kts
- service/custom-ktlint-rules/build.gradle
- service/vtjclient/build.gradle.kts
JCenter should no longer be used:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
> Don't use jcenter repository

- message-service/owasp-suppressions.xml
- service-lib/README.md
- As we currently have no known cases nor a solution for the known issue with multiple Logback ConsoleAppenders theoretically corrupting eachother's JSON outputs, just document it in the (newly created) service-lib README
- message-service: suppress CVE-2021-29425
- Not high risk enough in message-service's context, suppressing
> [EVAKA] service-lib: add basic docs and known issues, suppress message-service vuln

- frontend/src/employee-frontend/api/person.ts
- frontend/src/employee-frontend/components/child-information/ChildApplications.tsx
- frontend/src/employee-frontend/components/person-profile/PersonApplications.tsx
- frontend/src/employee-frontend/types/application.ts
- service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/resources/db/migration/R__application_view.sql
Application list on child's and guardian's page should display the preferred start date given on application instead of the "estimated start date" calculated by application_view
slack discussion: https://voltti.slack.com/archives/CP6E9QKFE/p1618835024069300
> EVAKA-HOTFIX: display original preferred start date on child's application list

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailService.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/application/SendApplicationReceivedEmailAsyncJobs.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
Send citizen a confirmation email when club application is received. This is just a trivial extension to an existing feature.
> EVAKA-4195 Send email confirmation for club application

- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsBatchRefreshService.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
- Get vtj updates on all persons (has been agreed with DVV)
- When encountering an unknown modification, print out all the modifications in the group so that it can be ensured we handle at least one modification in the group.
> Evaka fix update every person vtj changes

- message-service/build.gradle.kts
- service/build.gradle.kts
- According to reports, the NIST NVD data feed issue is now resolved
- This reverts commit e67a8fa87e332a220456b31de7a9fd3623d7e95b
> [EVAKA-HOTFIX] Revert "EVAKA temporary fix for owasp dependency check"

- frontend/src/employee-frontend/components/unit/tab-groups/daycare-daily-notes/DaycareDailyNoteModal.tsx
Previous implementation was reading from the `note` itself which was only used for initial state.
Toggling any reminder off resulted in a) crash if working on a new note or b) reset of state for all the other toggles that were touched during that edit session.
> Fix reminder toggle in daily daycare note

- frontend/src/citizen-frontend/applications/editor/AdditionalDetailsSection.tsx
- frontend/src/citizen-frontend/applications/editor/FeeSection.tsx
- frontend/src/citizen-frontend/applications/editor/contact-info/ChildSubSection.tsx
- frontend/src/citizen-frontend/applications/editor/contact-info/ContactInfoSection.tsx
- frontend/src/citizen-frontend/applications/editor/contact-info/SecondGuardianSubSection.tsx
- frontend/src/citizen-frontend/applications/editor/service-need/ServiceNeedSection.tsx
- frontend/src/citizen-frontend/applications/editor/unit-preference/UnitPreferenceSection.tsx
- frontend/src/employee-frontend/components/child-information/assistance-action/AssistanceActionForm.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/AssistanceNeedForm.tsx
- frontend/src/employee-frontend/components/child-information/backup-care/BackupCareForm.tsx
- frontend/src/employee-frontend/components/child-information/service-need/ServiceNeedForm.tsx
- frontend/src/employee-frontend/components/group-caretakers/GroupCaretakersModal.tsx
- frontend/src/employee-frontend/components/invoice/InvoiceRowsSectionRow.tsx
- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/person-profile/person-fridge-child/FridgeChildModal.tsx
- frontend/src/employee-frontend/components/person-profile/person-fridge-head/PersonFridgeHeadForm.tsx
- frontend/src/employee-frontend/components/person-profile/person-fridge-partner/FridgePartnerModal.tsx
- frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/GroupModal.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/group/GroupTransferModal.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/missing-group-placements/GroupPlacementModal.tsx
- frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
- frontend/src/lib-common/form-state.d.ts
Using `Pick` instead of `Partial` prevents setting required properties to `undefined`. [TS Playground](https://www.typescriptlang.org/play?ts=4.2.3#code/LAKAlgdgLgpgTgMwIYGMYAICyBPAIkqJdAb1HXQGco4wUoAbbAVQgBMYFIZWAuS6yAHN0AH3QBXNhy6sy6APYAHKGHkQk9APx8qNCILlwYAR3FgjvfnoMgAvqFAo1VdAnny+OfIXQBeEnK6tAzMUpwQ3HyS7OHcADSGJmYWfABEALbwANZZYABWavKpoPYgoPQwUK7ycOmeeARE-sQAdG1u8qWOzlXiiqwEMABiNel+6AAUfQOwFHwACkhwKhoAPF6NAHwAlH6bASDkbrXjre2jcehtLdODFOilXSBOEC63sCO1ACrYijAAykgEBh-KsANLoGAAD1gbHuWRg2HkCCwDUImwmcneMDm6HmtCy6zRSEuYM2oF2vn2pEO1ROzWux3Sl2u2PujwcIGxn3SE2IRlM5kiEjCMkuQTojBYMRkUVFEVYlyUKjUGjlMoVtm2oG5oz5AuSwui0k12rKXP6gx5Pz+gOB+qSQssxtiiqswSl8qNXrdytU6no6pN3C1OstH1GNoBQJgDsFKRFGpDZqAA)
> Add type safety to form updates

- frontend/package.json
- frontend/src/e2e-playwright/browser.ts
- frontend/src/e2e-playwright/utils/index.ts
- frontend/src/e2e-test-common/config.ts
- use "standard" CI env variable instead of custom E2E_DEVELOPMENT
- set jest timeout to 60s in all Playwright tests automatically on CI
- disable jest timeouts locally in Playwright tests
- set playwright timeout to 30s or 5s depending on mode. This matches
the timeout used in our waitUntilX functions
> Apply nicer default config in Playwright tests

- bin/add-license-headers.sh
- 024d6dc44ce134e548af40ab2ced99ff444e49b7 introduced a "regression" with the bash argument parsing that causes the filename argument to be given twice to reuse -> shift it away
With `master` version of script, run:
```sh
touch file.txt
DEBUG=true ./bin/add-license-headers.sh
```
-> will show `file.txt file.txt` given as the last two args for `docker run`
Running with branch version gives the `file.txt` arg just once as it should.
> [EVAKA-HOTFIX] Drop duplicate filename argument in licensing script

- frontend/src/employee-mobile-frontend/components/attendances/AttendancePageWrapper.tsx
With a long child list, the last one was partially covered by the bottom navbar due to wrong `ContentArea` height.
> EVAKA-HOTFIX: Mobile attendance list height

- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/components/reports/Occupancies.tsx
- frontend/src/employee-frontend/components/reports/Raw.tsx
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/OccupancyReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
Add toggles for using new service needs to occupancy and raw reports. Implement the occupancy report with most of the computations done in kotlin code to make the implementation easier to read. If the performance hit is too big, revert back to the single database query.
The group occupancy reports are not implemented yet because they take a bit more work to implement and it's good to test the performance part first.
> EVAKA-4176 occupancy and raw report with new service needs

- apigw/src/shared/auth/ad-saml.ts
- apigw/src/shared/auth/keycloak-saml.ts
- apigw/src/shared/auth/suomi-fi-saml.ts
- apigw/src/shared/config.ts
This is part 2 of the SAML configuration hardenings/fixes as reported by a white hat. SLO fixes are in progress in #738 and `InResponseTo` checking will follow later.
- APIGW: Enable SAML audience checking
- Audience checking for SAML responses is one way to prevent attackers from reusing e.g. login responses intended for another SP (from a trusted IdP) to log into eVaka
- Without audience checking, eVaka would only check that the message came from a trusted IdP and would allow login/logout -> any user that can log in the IdP (AD mainly, in this case) can log into eVaka even if the IdP wouldn't permit it (e.g. missing AD role to access eVaka)
- Add new configuration for "eVaka SAML" (i.e. Keycloak), `EVAKA_SAML_ISSUER` for use as the expected audience (same for Suomi.fi and AD but they …
> [EVAKA-HOTFIX] Harden SAML configuration for replay attacks, audience confusion

- frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx
- frontend/src/citizen-frontend/applications/editor/validations.ts
- frontend/src/e2e-test/pages/citizen/citizen-application-editor.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application-create.spec.ts
So it turned out that actually, by the law, citizens must be able to choose their preferred start date to be as early as they wish - we shouldn't limit their choice at all.
> EVAKA-FIX: Remove unnecessary restrictions on preferred start time

- apigw/src/enduser/app.ts
- apigw/src/enduser/routes/auth-status.ts
- apigw/src/shared/auth/customer-saml.ts
- apigw/src/shared/auth/index.ts
- apigw/src/shared/auth/jwt.ts
- apigw/src/shared/config.ts
- apigw/src/shared/routes/auth/suomi-fi.ts
- apigw/src/shared/service-client.ts
- compose/docker-compose.e2e.yml
- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/auth/requireAuth.tsx
- frontend/src/citizen-frontend/auth/state.tsx
- frontend/src/citizen-frontend/header/DesktopNav.tsx
- frontend/src/citizen-frontend/header/MobileNav.tsx
- frontend/src/citizen-frontend/header/const.ts
- service/src/main/kotlin/fi/espoo/evaka/messaging/bulletin/BulletinControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/AuthenticatedUser.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/JwtTokens.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/UserRole.kt
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/controllers/VtjController.kt
Enable customer weak authentication.
=> new shell
```bash
cd evaka/compose
docker-compose up
```
=> new shell
```bash
pm2 start all
```
=> new shell
bring up the keycloak
=> <http://localhost:9099/messages> => weak login => create account or weak => come back to messages succesfully logged in
=> click decicions => fake strong login commences
> Customer weak login

- frontend/src/employee-frontend/components/employee/EmployeePinCodePage.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Confirm when navigating away from unsaved PIN:
- If tab is closed or back button pressed, use browser beforeunload support (https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event)
- If clicking another link, use react routed DOM support
Tested on latest chrome and firefox. On playwright chromium the popup disappears immediately.
The two cases shown on chrome and firefox:
> Confirm when navigating away from unsaved PIN

- frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
- service/src/main/kotlin/fi/espoo/evaka/serviceneednew/NewServiceNeed.kt
Service needs are split the same way as group placements. If a placement is created inside another, both service needs and group placements are shortened. Later it would be nice to copy them to the new placement inserted at the end, but this is a rare use-case and not trivial to implement so I left that out.
Unit supervisors may also now delete placements from their units which have not yet started.
> EVAKA-4176: splitting placements splits service needs

- frontend/package.json
- frontend/yarn.lock
Dependabot had an alert about this.
> EVAKA-FIX updated lodash to fix CVE-2021-23337

- service/src/main/kotlin/fi/espoo/evaka/daycare/CaretakerQueries.kt
The query would previously include caretakers from groups that have already ended as long as there was no ending date for the group caretaker amount.
> EVAKA-HOTFIX fix unit caretaker stats query

- frontend/src/lib-components/atoms/form/SimpleSelect.tsx
The arrow icon would previously prevent the option list from opening.
> EVAKA-HOTFIX make SimpleSelect arrow click-through

- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/header/Header.tsx
- frontend/src/citizen-frontend/styled.d.ts
- frontend/src/employee-frontend/state/StateProvider.tsx
- frontend/src/employee-frontend/styled.d.ts
- frontend/src/employee-mobile-frontend/App.tsx
- frontend/src/employee-mobile-frontend/styled.d.ts
- frontend/src/employee-mobile-frontend/tsconfig.json
- frontend/src/lib-common/theme.ts
- frontend/src/lib-common/themes/espoo-theme.ts
- frontend/src/lib-components/.storybook/preview.jsx
- frontend/src/lib-components/atoms/RoundIcon.stories.tsx
- frontend/src/lib-components/colors.stories.tsx
- frontend/src/lib-components/colors.ts
- frontend/src/lib-components/styled.d.ts
- frontend/src/lib-components/typography.ts
- frontend/src/lib-customizations/common.tsx
- frontend/src/lib-customizations/espoo/common.tsx
- frontend/src/lib-customizations/tsconfig.json
- frontend/src/lib-customizations/types.d.ts
Frontend styles needs to be customized for other installations. This first part takes care of component colors:
1. Introduced styled components theme into `lib-customizations` based on `lib-components/colors.ts` (which is now deprecated)
2. Added `ThemeProvider` for every app (citizen, employee, employee-mobile) that uses new theme from `lib-customizations`
3. Added examples how to refactor modules to support colors from `lib-customizations`:
- lib-components needs to be changed to use styled components theme: https://github.com/espoon-voltti/evaka/commit/d102e44bd127217d41b029c59f212fab6d2eae06
- other modules require only simple import change for now: https://github.com/espoon-voltti/evaka/commit/81338816af68f3cf98ceaa356ca940c9598bddba
I can finish step 3 if this POC is accepted.
> Customizable colors POC

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailService.kt
So it was requested to merge different language versions of our application emails to single messages. Order should always be FI, SV, EN.
> EVAKA-FIX: Application email contains all language versions

- apigw/src/shared/__tests__/saml-slo.ts
- apigw/src/shared/auth/suomi-fi-saml.ts
- apigw/src/shared/config.ts
Fixes internal-gw regression introduced in #738
- evaka-internal-gw won't have the required Suomi.fi configs set -> revert the changes introduced in 6a62fcd6b85550b4bf0669cb76ac404ea92b1f8f and don't required other SFI configs to be set when callback URL isn't set (baseline for all SAML configs)
> APIGW: Don't require SFI configs when disabled

- frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationUpdateIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationSummaryIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/test/TestData.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentQueries.kt
When `extendedCare` or `urgency` is cancelled when updating application, remove corresponding attachments that were uploaded by the same user
> EVAKA-FIX: remove attachments if irrelevant

- message-service/src/main/kotlin/fi/espoo/evaka/msg/async/AsyncJob.kt
- message-service/src/main/kotlin/fi/espoo/evaka/msg/async/AsyncJobQueries.kt
- message-service/src/main/kotlin/fi/espoo/evaka/msg/async/AsyncJobRunner.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
This information is now logged in log messages via ClaimedJobRef.toString, and separately in log message metadata.
> Log remaining attempts in AsyncJobRunner

- service/src/main/kotlin/fi/espoo/evaka/serviceneednew/NewServiceNeedQueries.kt
If a service need has part time hours but no part day or part week flag toggled, assume that it's part week as service needs migrated from Effica didn't have any part week indication.
Also, make the placement type requirements for different service needs more lenient in the migration.
> EVAKA-4176 more lenient service need migration

- frontend/src/lib-components/molecules/FileUpload.tsx
- `FileUpload` creates a pseudo-ID for new files for use in state comparisons until the actual file ID is received from `onUpload`
- Internally, `FileUpload` decides whether to show a progress bar and span instead of a download link based on the status of the upload process -> if `progress === 100` but the `FileObject` had not yet received its proper ID, users could attempt file download using the pseudo-ID, which would result in errors
- Instead of relying on a (rounded!) progress state, use a separate `uploaded` flag on `FileObject`s to signify that all of the upload processing is complete -- not just the data transfer
- `progress` is still useful for visualization purposes
- Unfortunately I couldn't figure out a sensible way to regression test this as the bug relies on either:
1. …
> [EVAKA-HOTFIX] Fix FileUpload allowing downloads for unfinished uploads

- proxy/files/etc/nginx/conf.d/nginx.conf.template
- nginx's built-in `$time_iso8601` only outputs full seconds instead of at a millisecond resolution (like other eVaka apps), which makes following logs inconvenient
- nginx currently has no alternative variable available (with ISO 8601 formatting)
- Use the `$msec` variable in combination with `$time_iso8601` and some regex mapping to generate better timestamps
> Proxy: log with millisecond resolution

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccountQueries.kt
- Don't allow an employee or person to access an inactive message account.
- This doesn't currently affect message sending, because person accounts are never inactive, and citizens cannot yet send messages to employees.
> EVAKA-4190 Forbid access to inactive accounts

- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/MergeService.kt
- service/src/main/resources/db/migration/R__ensure_empty_person_function.sql
When to persons are merged, move the duplicate person's sent and received messages to the master person's message account.
> EVAKA-4190 Move messages when merging persons

- frontend/src/citizen-frontend/map/SearchInput.tsx
Show all matching units instead of the first five in map search input dropdown.
> Show all matching units in map search input dropdown

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaDecisionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaFeeDataIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDecisions.kt
- service/src/main/resources/db/scripts/fee-decision-migration.sql
Use new service needs in Varda integration. Also, fix fee decision migration for preschool and preparatory children.
> EVAKA-4176 new service needs and Varda

- frontend/src/employee-frontend/components/messages/GroupMessageAccountList.tsx
- frontend/src/employee-frontend/components/messages/MessageDrafts.tsx
- frontend/src/employee-frontend/components/messages/MessageList.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/messages/Sidebar.tsx
- frontend/src/employee-frontend/components/messages/api.ts
- frontend/src/employee-frontend/components/messages/types-view.d.ts
- frontend/src/employee-frontend/components/messages/types.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/DraftQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/DraftContent.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/DraftQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageController.kt
- service/src/main/resources/db/migration/V88__draft_type_and_recipients.sql
- service/src/main/resources/migrations.txt
- Add drafts message box to accounts view
- Implement simple list view for drafts
- Separate displayable draft content from upsertable draft content
- Add missing message type to draft content
- Add recipient names to draft content for display purposes. The frontend can decide on the content and group the recipients eg. `["Hippiäiset", "Joni Juntunen"]` or `["Aallonhuipun päiväkoti"]`.
> EVAKA-4190 Initial draft view implementation

- frontend/.gitignore
- frontend/package.json
- frontend/src/citizen-frontend/jest.config.ts
- frontend/src/e2e-playwright/browser.ts
- frontend/src/e2e-playwright/jest-environment.js
- frontend/src/e2e-playwright/jest.config.ts
- frontend/src/employee-frontend/jest.config.ts
- frontend/src/lib-common/jest.config.ts
- frontend/yarn.lock
* split global jest config into separate "projects" so we can customize the configuration just for tests under src/e2e-playwright
* use jest-circus test runner, which has support for various lifecycle hooks
* implement a simple custom jest environment, which allows us to run code after a failing test
* expose screenshot function from `browser.ts` to the jest environment through a nodejs global object
* take screenshots after failed Playwright tests from all browser contexts and pages
> Take screenshots after failed Playwright tests

- frontend/src/employee-frontend/components/application-page/ApplicationDecisionsSection.tsx
- frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx
Hide decision response component when application is waiting for mailing, back end won't let user confirm or reject the decisions anyway.
> EVAKA-HOTFIX decision response when waiting for mailing

- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/auth/requireAuth.tsx
- /auth/status can sometimes take a long time, and we want the user to know we're still loading something
- move spinner from requireAuth up in the component hierarchy
- map doesn't use requireAuth but now gets the spinner, so the user sees a spinner if the first load after login takes a while
> Use a top-level spinner for /auth/status loading status

- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-frontend/components/messages/GroupMessageAccountList.tsx
- frontend/src/employee-frontend/components/messages/MessageDrafts.tsx
- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/messages/MessageList.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/messages/MessagesPageContext.tsx
- frontend/src/employee-frontend/components/messages/Sidebar.tsx
- frontend/src/employee-frontend/components/messages/api.ts
- frontend/src/employee-frontend/components/messages/types-view.ts
- frontend/src/employee-frontend/components/messages/types.ts
- frontend/src/employee-frontend/components/messages/useDraft.ts
- frontend/src/lib-common/utils/useDebouncedCallback.ts
- frontend/src/lib-common/utils/useRestApi.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/DraftQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/DraftContent.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/DraftQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/Message.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccountQueries.kt
- service/src/main/resources/db/migration/V91__message_draft_non_nullable.sql
- service/src/main/resources/migrations.txt
- Save message content as draft
- Open draft from the draft section
- Discard draft after message is sent or when manually discarded
- Move message state to context as it is needed to be refreshed from multiple places
- Fix pre-selection of sender and recipients
- Refactor message editor logic
- Handle receiver selection internally within the editor. Previously the receiver selection was passed from the outside and updated from within the editor creating a two-way data flow. Now the editor just gets the initial state and handles it from there by itself.
- Make all fields of draft content required.
> EVAKA-4190 Save message draft state automatically

- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/messages/SentMessages.tsx
- frontend/src/employee-frontend/components/messages/types.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/Message.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccountQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageService.kt
- service/src/main/resources/db/migration/V93__message_recipient_names.sql
- service/src/main/resources/migrations.txt
Save textual recipient name with message. Eg. `Aallonhuipun päiväkoti` or `Ryhmä 1, Karhula Veera` instead of `Karhula Viljami, Karhula Jami, Karhula Mukkelis-Makkelis, Karhula Veera`
> EVAKA-4190 Save and show textual recipient names with message

- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/messages/MessageList.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/messages/Sidebar.tsx
- frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- Keep message title in its container
- Make messages page occupy the full page height. Currently it is implemented by setting a fixed height to the page container, which is sub-optimal.
- Make accounts panel and message list scrollable.
- "Sticky" new message button
- Add a gap between accounts and new message button
> EVAKA-4190 Page layout fixes

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageReceiversIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/UnitAcl.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/DaycareService.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/Message.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccount.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccountQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/Person.kt
- Use person/employee ids instead of `AuthenticatedUser` when querying message accounts, because only the `id` was used.
- Use account id to reference message accounts, instead of `MessageAccount` that also contains the rarely needed account name.
- Rename `getMessageAccountFor*()` to `get*MessageAccount()`
- Rename `getAuthorizedMessageAccountsForEmployee()` to `getEmployeeDetailedMessageAccount()`
> EVAKA-4190 Refactor message account queries

- frontend/src/e2e-test-common/dev-api/fixtures.ts
- frontend/src/e2e-test/specs/5_employee/units.spec.ts
The default end date for placement fixtures was 2021-08-31, which is 3 months minus one day from today. This caused an E2E test to fail.
> EVAKA-HOTFIX Move placement fixtures back to the future

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageAccountQueries.kt
- Supervisors see all group accounts in their daycares
- Staff members only see their own groups' accounts (based on `daycare_group_acl`)
- Admins do **not** see all message accounts. Not sure if this is desirable.
> EVAKA-4190 Authorize daycare group message account access

- frontend/src/employee-frontend/api/child/assistance-actions.ts
- frontend/src/employee-frontend/components/child-information/AssistanceAction.tsx
- frontend/src/employee-frontend/components/child-information/assistance-action/AssistanceActionForm.tsx
- frontend/src/employee-frontend/components/child-information/assistance-action/AssistanceActionRow.tsx
- frontend/src/employee-frontend/constants.ts
- frontend/src/employee-frontend/types/child.ts
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceAction.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionController.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionService.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/R__koski_views.sql
- service/src/main/resources/db/migration/V97__assistance_action_option.sql
- service/src/main/resources/dev-data/espoo-dev-data.sql
- service/src/main/resources/migrations.txt
There are significant differences in assistance action options between installations. Also they are used for reports so simply creating union of all options (and hiding unnecessary options) is not smart here. So let's move options to database for full customization support. This is part 1 (i.e. edit works), ~~part 2 will add full support for the report (note: report will work correctly for previous hard-coded options)~~ it was agreed that you will add reports support.
Automatic database migration will only add options already in use, e.g. if some of the options are not currently used they will be missing. So after installing this change, you want to add all missing options with following SQL:
```
INSERT INTO assistance_action_option (value, name_fi, display_order) VALUES …
```
> Assistance action options to database

- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
Build on #950. 
Load accounts on context initialization too in order to always show unread messages count in header. This can later be replaced with a polling refresh
> EVAKA-4190 Load accounts on page load

- frontend/src/lib-customizations/citizen.tsx
- frontend/src/lib-customizations/espoo/citizen.tsx
- frontend/src/lib-customizations/types.d.ts
treVaka doesn't need sv support.
> Add citizen langs customization support

- frontend/src/employee-frontend/components/Header.tsx
- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/messages/SelectorNode.ts
- frontend/src/employee-frontend/components/messages/Sidebar.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
* Prevent sender-receiver conflicts in frontend: If sending message as `daycare X group Y`, disable selecting receivers from daycares other than `X` and groups other than `Y`.
* Use sidebar unit selection to filter available accounts upon opening the editor (also specify which daycare is selected in the title).
* Misc improvements:
* Minor refactoring
* Prevent choosing empty groups as the selected sender account (this is to rule out some edge cases this update would introduce, but could make sense otherwise too).
* Hide receiver selection from the sidebar.
Suggest doing everything in the frontend, as there doesn't seem to be a need to involve the backend in any of this.
> EVAKA-4190: Prevent sender-receiver conflicts

- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageControllerCitizen.kt
Enable messaging endpoints for weakly authenticated citizens.
> EVAKA-4190 Enable messaging for UserRole.CITIZEN_WEAK

- .circleci/config.yml
The old image has old Terraform version and does not use tfenv.
> Update builder image

- frontend/src/employee-frontend/components/finance-basics/FeeThresholdsItemEditor.tsx
- frontend/src/employee-frontend/components/finance-basics/FeesSection.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceBasicsController.kt
- service/src/main/resources/db/migration/V104__fee_thresholds_constraints.sql
- service/src/main/resources/dev-data/espoo-dev-data.sql
- service/src/main/resources/migrations.txt
* Add sibling discounts to fee thresholds editor.
* Insert dev data into `fee_thresholds` table instead of `pricing`.
* Add overlap constraint and `created` & `updated` columns to `fee_thresholds`
> EVAKA-4184 sibling discounts in fee thresholds editor

- frontend/src/e2e-test-common/dev-api/fixtures.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
E2E: Try to make sure that an active preschool term exists by moving the preferred start date to September if it's summer currently.
Integration: Change application validation to be parametrized with the current date.
> EVAKA-HOTFIX Fix failing tests that create preschool applications

- proxy/Dockerfile
We want to upgrade operating system packages on build so we will fix possible issues before upstream container.
Includes the fixed versions of packages with the following vulnerabilities:
- CVE-2021-3517: HIGH
- CVE-2021-3518: MEDIUM
- CVE-2021-3537: MEDIUM
- CVE-2021-22901: UNDEFINED
- CVE-2021-22898: UNDEFINED
> Update proxy OS packages on build

- frontend/src/employee-frontend/components/messages/SentMessages.tsx
- frontend/src/employee-frontend/components/messages/types.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/Message.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/message/MessageQueries.kt
Group sent messages by content id so that messages that are split to threads are only shown as one in the sent messages view.
> EVAKA-4190 Group sent messages by content_id

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/PDFServiceTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionAddress.kt
- service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/MessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/template/EvakaTemplateProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/template/ITemplateProvider.kt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/service/PdfServiceTest.kt
Refactor PDF templates to support customization.
Also moves hard-coded default address used for decisions into message provider.
> Add template provider for customization

- evaka-bom/build.gradle.kts
- service/build.gradle.kts
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceUpkeepIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/daily/DailyJobRunnerTest.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/DailyJobConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ScheduledOperationController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/daily/DailyJobRunner.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/daily/DailyJobs.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/daily/DailySchedule.kt
- service/src/main/resources/db/migration/V107__scheduled_tasks.sql
- service/src/main/resources/migrations.txt
- add daily job scheduler based on the `db-scheduler` library
- tasks executed by the daily job scheduler only plan a corresponding async job. All actual work happens in the async job executed by AsyncJobRunner
- switch endOfDayAttendanceUpkeep to use the new daily job scheduler
> Add daily job scheduler

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
Add CLUB to Varda unit types to avoid `UnableToProduceResultException: no VardaUnitType value could be matched to the name CLUB`
> EVAKA-FIX: add missing varda unit type

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/PersonQueriesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Search.kt
- service/src/main/resources/db/migration/V108__person_freetext_search.sql
- service/src/main/resources/migrations.txt
Precompute the tsvector used for person free text search search using a generated column `freetext_vec`, and index that column. Use the new column for person, application, invoice, fee decision and voucher value decision searches.
With a set of 100,000 generated persons, this change speeds up the person search request from 300-400 ms to about 50-80 ms on my machine (~75-85 % faster). I didn't test the the performance effect for other search endpoints, because they would have needed much more complicated test data.
This also fixes the value decision free text search that was broken. Add some simple regression tests for it, too.
> Speed up freetext searches

- .circleci/config.yml
- README.md
- apigw/entrypoint.sh
- bin/run-shellcheck.sh
- compose/run-after-db.sh
- frontend/init-pro-icons.sh
- message-service/entrypoint.sh
- proxy/files/bin/proxy-start.sh
- service/entrypoint.sh
- CI: add shell script linting with shellcheck
- Lint all shell scripts with the excellent shellcheck tool to avoid the most common mistakes (variable expansion, incorrect whitespace, unused variables etc)
- Fix minor issues in existing scripts found by the new script
- Ran in parallel to multiple slower jobs -> no increase in total workflow time
- Improve AWS metadata error logging in all image entrypoints
- Don't suppress error messages from `curl` when fetching host IP from AWS metadata during image startups, while still falling back to a default value
- Also ignore SC2155: we already handle the error case with the fallback value "UNAVAILABLE" and output error messages from `curl` to stderr (without crashing as that's not desirable here)
- Fix minor existing issues with all the shell …
> CI: Add shell script linting

- frontend/src/lib-components/atoms/form/Combobox.tsx
- E2E tests always click the Root element which had no click listener, but the clicks *usually* hit the input wrapper
- let clicks propagate from children to Root instead
- clicks from the menu are not propagated, so menu clicks don't trigger the Root listener
> Capture top-level clicks in Combobox

- frontend/src/employee-frontend/components/messages/Sidebar.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Show "no access" text instead of an empty panel when the user does not have access to any message accounts.
> Indicate no message account access

- frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx
- frontend/src/employee-frontend/components/vasu/api.ts
- frontend/src/lib-components/molecules/modals/FormModal.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
- Return child's actual vasu documents instead of mock data
- Navigate to vasu edit view from vasu list
- Initialize new vasu document and navigate to edit view if successful
Initialization has to be reworked to select the currently valid template and restrict to only one document per template.
> EVAKA-4203 Glue current WIP vasu implementations together

- message-service/Dockerfile
- service/Dockerfile
- Fixes missing `hostIp` field in service and message-service logs due to `curl` not being available in the images
- Install `curl` instead of `wget` which was replaced in the entrypoints in 31c52d6c47417e2ee6721395ac5a918e552b4337
- I was so sure I checked that `curl` was installed but apparently not...
> EVAKA-HOTFIX: Fix services failing to get HOST_IP

- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
- SKIP LOCKED can skip jobs too eagerly. With normal jobs this is not a huge problem, since they are retried. For nightly one-shot jobs this is not a good thing
- instead of skipping, require a successful lock
- use a transaction-local lock timeout to avoid long waits
- `define` is used instead of `bind`, because SET LOCAL is not a normal query and can't use normal bind parameters
> Improve async job contention handling

- frontend/src/lib-common/api.ts
The axios error's `response` property was incorrectly cast into a type that is never undefined although the property might sometimes be missing, like when there was a connection error, so remove the cast.
> EVAKA-HOTFIX axios connection error handling

- service/src/main/kotlin/fi/espoo/evaka/invoicing/integration/InvoiceIntegrationClient.kt
Joto uses longer cost center values.
> Remove cost center max length

- compose/.gitignore
- compose/README.md
- compose/db.sh
- compose/docker-compose.dbdump.yml
Developers have Postgres locally with different verisions and locals than we have in development environment (docker-compose) so to combat the issue here we dump the local development database with docker(-compose) instead of local tools.
> Dump local database using docker

- service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
Club units were excluded from occupancy query results although they shouldn't be.
> EVAKA-HOTFIX add club units to occupancy results

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt
Remove fields in `FeeDecisionDetailed` that aren't in use since https://github.com/espoon-voltti/evaka/pull/1021.
> EVAKA-4184 fee decision clean up

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/IncomeIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/IncomeController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueries.kt
Set applicationId to null on upsert
> EVAKA-FIX: remove income application id reference on update

- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/PersonQueriesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/identity/SSNUtils.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Search.kt
Use lower when matching ssn's.
> EVAKA-FIX: case-insensitive ssn when searching people

- docs/README.md
- docs/convert.sh
- docs/diagrams/src/evaka-container.puml
- docs/diagrams/src/evaka-context.puml
- Upgrade to latest PlantUML on up-to-date docker image
- Sync diagrams better with current implementation
- suomi.fi for private service providers 
- messaging and memos added
- Drop Vue from diagrams
To test, run convert.sh and compare generated images with ones on https://github.com/espoon-voltti/evaka/wiki/Yleinen-arkkitehtuuridokumentaatio
> EVAKA FIX update architecture diagrams

- .circleci/config.yml
- frontend/.testcaferc.json
- frontend/package.json
- frontend/src/e2e-test/specs/2_employee-2/employee-dailynote.spec.ts
- frontend/src/e2e-test/specs/5_employee/income.spec.ts
- message-service/build.gradle.kts
- service-lib/build.gradle.kts
- service/build.gradle.kts
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationUpdateIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
| Thing | Current | New |
|-|-|-|
| Branch workflow | ~23 min | **~17 min** :tada: |
| Service tests | ~13 min | **~3 min** :tada: |
| Frontend deploys | ~3 min | **~30 s** :rocket: |
| E2E tests | ~12 min (slowest) | ~9 min :+1: |
| Workspace attaching | 30 s - 2.5 min | **~2 s** :muscle: |
| Developers | :cry: | :smiley: |
- Parallelize E2E tests and service integration tests based on historical test timing data
- Total actual time (when all parallel tests are finished) is minimized
- Automatic test splitting means that we don't need to manually select which tests are run together for an optimal set (timings wise)
- New tests are randomly split until timings for them exist
- For E2E tests this has the additional benefit of somewhat ensuring that fixtures are independent as any two …
> [EVAKA] CI: refactor workflow for speed and parallelization

- docs/.gitignore
- docs/convert.sh
- docs/diagrams/src/evaka-container.puml
- Switch to produce png for main wiki need directly
- Fix puml source format to match latest generator
- Add private service provider role
- Add Koski and finance integrations
- Use generic terms instead of Espoo specific ones
> EVAKA FIX architecture diagrams update take 2

- .circleci/config.yml
- CI: split frontend job for 1.5 - 2 min faster total time as E2E tests can be started earlier
- Everything not directly upstream of the E2E tests will always finish before them
- Maintenance-page, storybook, linting and type-checking aren't necessary to start E2E testing
- Wastes an extra ~20s of CircleCI credit time as Yarn cache restoration + install from that cache needs to be run on both jobs but saves 1.5 - 2 minutes of real time (i.e. much more expensive developer time)
- In a void, parallelization would save 3 minutes but now service build + service image build become the next bottlenecks blocking full benefits of this
- CI: cache sentry-cli binaries
- No reason not to as these always take a few unnecessary seconds to re-download and more importantly cause a lot of noise in the …
> [EVAKA] CI: split frontend job to start E2E test faster

- frontend/src/employee-frontend/components/common/VasuStateChip.tsx
- frontend/src/lib-components/atoms/Chip.stories.tsx
- frontend/src/lib-components/atoms/Chip.tsx
- Add storybook story for `StaticChip`
- Fix `readableColor` parameter order in `StaticChip`
- Remove color override from `VasuStateChip`
> Fix static chip color and add story

- .circleci/config.yml
```
Error: Value for undeclared variable
A variable named "scheduled-api-calls_version" was assigned on the command
line, but the root module does not declare a variable of that name. To use
this value, add a "variable" block to the configuration.
```
> Remove old Terraform variable

- service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/DaycareService.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
- remove broken check. It never worked, because a daycare placement ID was passed where a daycare ID was expected
- query used in two places with different requirements -> refactor to two simple queries instead
> Clarify and refactor group placement query

- frontend/src/e2e-playwright/pages/employee/messages/messages-page.ts
Potential fix for flaky E2E: after pressing send, actually wait for the message editor to close. Previously we went immediately to the "sent messages" page and assumed the message was there, but there was no guarantee the REST request for sending the message had completed.
> Wait until message has actually been sent

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- Sorted applications should be in same order (see that state sorted application here are ordered based on the first name of the child even though applications are identical otherwise)
> Ensure applications are sorted in predictable order

- service/src/main/kotlin/fi/espoo/evaka/shared/job/JobSchedule.kt
- Espoo's X-Road instance has a daily downtime at 03:00 UTC which is 06:00 Helsinki time -> adjust schedule to never collide with the downtime
- DVV update goes through X-Road
> [EVAKA-HOTFIX] Adjust DVV update schedule to avoid downtime

- service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/SecurityConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/PermittedRoleActions.kt
- introduce an API for checking permissions based on the intended *action*, instead of hard-coding a list of roles in the REST controller code. Roles will become customizable in the near future, so we can't have `UserRole` lists scattered in controller code anymore
- convert `BackupCareController` to use the new API as an example
- actions are defined in multiple enums, one per "scope"
- prepare action enums and other boilerplate for all scopes currently used in `AccessControlList`
- `ADMIN` role gets permission for all actions *implicitly*. If necessary, this can be overridden in more complicated action permission checks by not calling `assertPermission`
> MVP of action-based permission checks

- frontend/src/lib-components/atoms/form/Combobox.tsx
Fix Combobox toggle button.
`getToggleButtonProps` applies toggling logic to the toggle button. The click event was propagated to `Root` component which was also toggling the menu. `stopPropagation` correctly prevents the double toggle no-op.
> Fix Combobox toggle button

- apigw/package.json
- apigw/src/shared/routes/auth/saml/index.ts
- apigw/yarn.lock
- Slightly less aggressive SAML error logging (will also need adjustments in alerting logic)
- Adjust SAML authentication failure logging to avoid triggering unnecessary error log alerting with the word "error"
- Also, authentication errors are completely normal and not usually something to alert about (at least for each event)
- Update passport-saml to 1.5.0
- Latest release in the 1.x.x major version
- 2.x.x and 3.x.x still aren't ready for prime time with their broken typings (mainly related to extended request/response types)
- Drop xml-crypto resolution
- passport-saml@1.5.0 resolves xml-crypto to 2.1.2, so no longer necessary to override it
> [EVAKA-HOTFIX] Less SAML authn failure noise in logs

- frontend/src/citizen-frontend/messages/ThreadListItem.tsx
> Properly indicate read state in citizen thread list

- service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuTest.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuController.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateController.kt
- Prevent updating template content if template is already in use 
- Validate that vasu content structurally matches the template content when saving
> EVAKA-4203 Validate vasu content when saving

- apigw/README.md
- compose/proxy/nginx.conf
- proxy/files/etc/nginx/conf.d/nginx.conf.template
- Google Maps has been fully replaced by OpenStreetMaps in eVaka, remove all mentions of it
- Well, except that one _link_ in employee-frontend but that doesn't need anything loaded/allowed in eVaka
- Remove all remaining Google URLs from CSPs accordingly
- Secret already removed from infra configs
> [EVAKA] Remove remains of Google Maps, update CSP

- evaka-bom/build.gradle.kts
- frontend/src/e2e-test-common/dev-api/fixtures.ts
- frontend/src/e2e-test/specs/2_employee-2/application-transitions.spec.ts
- message-service/buildSrc/src/main/kotlin/Version.kt
- service/buildSrc/src/main/kotlin/Version.kt
Spring Boot 2.5.2 upgrades Tomcat to a version that doesn't have CVE-2021-33037 vulnerability.
> Upgrade Spring Boot to 2.5.2

- evaka-base/Dockerfile
- In case we ever explicitly need to run e.g. apt-get dist-upgrade to update some vulnerable dependencies instead of just allowing cached base layers to be used, now the argument can be incremented and caches busted
- For example, now we want to update to at least systemd@245.4-4ubuntu3.10 instead of 3.6 included in ubuntu:20.04 (as of the time of this commit) to fix [CVE-2021-33910](https://ubuntu.com/security/CVE-2021-33910), we would increment the ARG value
- And obviously in this case, creating the new layer _before_ apt-get dist-ugprade, the result is the same
1. `cd evaka-base`
1. Initial build: `docker build .`
1. Next build w/ cache: `docker build .` -> should re-use all existing layers
1. Increment the new `ARG` value in `Dockerfile`
1. `docker build .` -> should **not** re-use …
> [EVAKA-HOTFIX] Add cache busting capability to base Docker image

- apigw/src/shared/auth/ad-saml.ts
- apigw/src/shared/config.ts
- apigw/src/shared/routes/auth/saml/index.ts
- Add `nameID` property for AD mock user
- Fixes "User unexpectedly missing nameID property" error (which just failed to create the 3rd party logout token but still created a valid session)
- AD mock (i.e. "dev login") doesn't use a proper SAML message but our 3rd party logout token system requires users to have a `nameID` property in order to generate the token -> add a dummy ID like already exists with the Suomi.fi mock user
- The alternative would be to disable logout tokens altogether for mock logins but as both internal-gw and enduser-gw share _default_ configs we cannot assume that AD mocking is enabled (default is `false`) on enduser-gw or vice versa -> would need to add knowledge about the active strategy to ther otherwise strategy-agnostic router or make a breaking change to …
> [EVAKA-HOTFIX] Add missing nameID for AD mock user, rename DEV_LOGIN to AD_MOCK

- .circleci/config.yml
- CI: ensure ECS deploys are successful
- Wait until all ECS services in the target environment's cluster have stabilized after deployed (meaning that new tasks have successfully replaced the old tasks within 10 minutes
- Log previous versions before deploying new versions so that developers can manually do a rollback if necessary
- In the longer term, we probably would like to drop deploys from CircleCI altogether (and maybe move the Espoo customized version to another repo) and/or use the Espoo deploy tool for deploys but this is the MVP setup to faster feedback loops on working eVaka versions:
- This will alert a lot quicker than Datadog (with its 15 min AWS metric delays)
- Prevents going forward to staging/prod with a broken version as a broken deploy job will block staging approvals …
> [EVAKA] CI: wait for ECS deploy to succeed, or fail

- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/AsyncJobConfig.kt
Add an env variable that can be used to disable async job runner. Useful when eg. enabling maintenance mode.
Also, see https://github.com/espoon-voltti/evaka-infra/pull/452
> Option to disable async job runner

- message-service/owasp-suppressions.xml
- service/owasp-suppressions.xml
These vulnerabilities should not be relevant for us since we do not use Apache Commons Compress to read untrusted 7z/zip/tar files.
https://nvd.nist.gov/vuln/detail/CVE-2021-35515
https://nvd.nist.gov/vuln/detail/CVE-2021-35516
https://nvd.nist.gov/vuln/detail/CVE-2021-35517
https://nvd.nist.gov/vuln/detail/CVE-2021-36090
> Add suppressions for irrelevant vulnerabilities

- evaka-bom/build.gradle.kts
- message-service/buildSrc/src/main/kotlin/Version.kt
- service/buildSrc/src/main/kotlin/Version.kt
Spring boot 3.5.3 has an upgraded version of Jetty without the CVE-2021-34429 vulnerability.
> Update spring boot to 2.5.3

- frontend/src/e2e-playwright/specs/0_citizen/citizen-applications-list.spec.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-club-application.spec.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-daycare-application.spec.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-header.spec.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-preschool-application.spec.ts
- frontend/src/e2e-playwright/specs/7_messaging/messaging.spec.ts
- frontend/src/e2e-playwright/utils/user.ts
Attempt to make logins in e2e tests more reliable:
* Wait for logout button to appear on enduser login
* Skip unnecessary navigations to login page on employee login
* Use separate browser contexts when logging in with different roles
* Do login in beforeEach hook in every citizen test so that individual tests don't have to care about logins
> Flaky e2e test logins

- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/SystemIdentityController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/JobSchedule.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Add a scheduled job that removes all roles from employees that haven't logged in last 3 months. For employees that do not have `last_login` data, use 1.6.2021 as a default since `last_login` has been tracked since May.
> EVAKA-4208 remove roles from inactive employees

- frontend/src/employee-frontend/api/child/assistance-needs.ts
- frontend/src/employee-frontend/components/child-information/AssistanceNeed.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/AssistanceNeedForm.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/AssistanceNeedRow.tsx
- frontend/src/employee-frontend/constants.ts
- frontend/src/employee-frontend/types/child.ts
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeed.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedController.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedService.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/R__koski_views.sql
- service/src/main/resources/db/migration/V124__assistance_basis_option.sql
- service/src/main/resources/dev-data/espoo-dev-data.sql
- service/src/main/resources/migrations.txt
See https://github.com/espoon-voltti/evaka/pull/926 for a very similar pull request.
After installing this change, you want to execute following SQL-script to make sure every option is still available in the UI:
```
INSERT INTO assistance_basis_option (value, name_fi, description_fi, display_order) VALUES
('AUTISM', 'Autismin kirjo', NULL, 10),
('DEVELOPMENTAL_DISABILITY_1', 'Kehitysvamma 1', NULL, 15),
('DEVELOPMENTAL_DISABILITY_2', 'Kehitysvamma 2', 'Käytetään silloin, kun esiopetuksessa oleva lapsi on vaikeasti kehitysvammainen.', 20),
('FOCUS_CHALLENGE', 'Keskittymisen / tarkkaavaisuuden vaikeus', NULL, 25),
('LINGUISTIC_CHALLENGE', 'Kielellinen vaikeus', NULL, 30),
('DEVELOPMENT_MONITORING', 'Lapsen kehityksen seuranta', NULL, 35),
('DEVELOPMENT_MONITORING_PENDING', 'Lapsen …
```
> Refactor assistance basis options to database

- service/src/main/resources/db/migration/V125__fee_thresholds_primary_key.sql
- service/src/main/resources/migrations.txt
Primary key constraint was probably accidentally left off the original migration.
> Make id column of fee_thresholds primary key

- message-service/gradle.properties
- service/gradle.properties
MaxPermSize option is already deprecated in Java 8 and removed in latest versions.
> Remove MaxPermSize option

- apigw/src/shared/config.ts
New KeyCloak versions removed option to use URL as Issuer so we use client-id instead.
> Use client-id instead URL for local SAML

- frontend/src/e2e-playwright/pages/citizen/citizen-applications.ts
- frontend/src/e2e-playwright/utils/element.ts
- frontend/src/e2e-playwright/utils/index.ts
- return last seen value in wait APIs
- implement a more low-level `waitForCondition` function that others use
- make sure attribute value is defined before comparing `!== 'someactualvalue'`
- try to remove collapsible click flakiness
> Minor E2E fixes

- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTestBase.kt
- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceClient.kt
Since we are still using the old env variable for dvv modifications url, I decide to use the new variable name for the new format. This PR needs to be merged into master before the new url is used.
> Prepare service for new version of dvv modifications url env variable

- frontend/package.json
- frontend/webpack.config.js
- frontend/yarn.lock
Benefits:
* Readable class names and component names in development for easier debugging.
* Bundle size reduces about 3 % because of more efficient JS template literal representation, more efficient CSS minification, and more efficient dead code removal.
Before (DOM):
After (DOM):
Before (React dev tools):
After (React dev tools):
> Use babel-plugin-styled-components

- frontend/src/citizen-frontend/messages/ThreadList.tsx
- frontend/src/e2e-playwright/specs/7_messaging/messaging.spec.ts
New message button caused problems with features available to non-pilot daycares. Temporarily hide new message button to buy some time to introduce a proper fix.
> Hotfix: Hide new message button

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/utils/FuelExtensions.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- Varda seems to send http 429 RETRY_AFTER values exceeding several hours. In those cases it is better to abort to avoid running out of threads.
- On some tables the varda_child_id is nullable so check for those
- Non invoiced units are not included in varda updates
> Varda improvements

- service/src/main/kotlin/fi/espoo/evaka/vtjclient/service/vtjclient/VtjClientService.kt
- service/src/test/kotlin/fi/espoo/evaka/vtjclient/service/VtjClientServiceTest.kt
It's completely expected that sometimes people are not found in VTJ when users input wrong SSNs. Other code handles the `null`s.
> EVAKA-HOTFIX do not throw when person not found in VTJ

- frontend/src/employee-frontend/api/unit.ts
- frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
- frontend/src/employee-frontend/components/unit/TabApplications.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
- frontend/src/employee-frontend/types/child.ts
- frontend/src/employee-frontend/types/unit.ts
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/backupcare/BackupCareIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCare.kt
- service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
https://github.com/espoon-voltti/evaka/pull/1017 part 2: add service needs to also group tables. Feature is enabled with `serviceNeedOptionsEnabled` so it won't affect current Espoo implementation.
> Add service needs to group tables

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- Only sync the children to varda whose old varda info has been reset to be able to switch in a controlled way from the old varda update service to the new
> Only varda sync children whose old info has been reset from varda

- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2IntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceV2.kt
- service/src/main/resources/db/migration/V135__remove_varda_service_need_option.sql
- service/src/main/resources/migrations.txt
- Varda update detects fee data changes for service needs which themselves were not changed. Filter out those changes which target daycares that are not varda daycares.
- Do not track service need option changes, only service need changes
> Filter out fee data targeting daycares that are not to sent to varda, and do not track service need option changes

- evaka-base/Dockerfile
- Not at all relevant for us but might as well update (i.e. cache bust Docker image) to appease ECR security scanners
- Fixed version of openssl (1.1.1f-1ubuntu2.8) has already been released for Ubuntu 20.04 (base image's base image)
> [EVAKA-HOTFIX] Base: update openssl to fix SM2 vulnerability

- frontend/src/employee-frontend/api/applications.ts
- frontend/src/employee-frontend/api/employees.ts
- frontend/src/employee-frontend/api/invoicing.ts
- frontend/src/employee-frontend/api/person.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationSummaryIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerSearchIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
Using POST methods in person searches so we do not get problematic entries into logs. The GET methods are replaced with POST-JSON equivalents.
This will change the internal API.
> Search people using POST methods instead GET

- frontend/src/citizen-frontend/calendar/CalendarModal.tsx
- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/DayElem.tsx
- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/citizen-frontend/calendar/api.ts
- frontend/src/lib-components/molecules/date-picker/DatePicker.tsx
- frontend/src/lib-components/molecules/date-picker/DatePickerDay.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenControllerTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
Add inline editor to citizen reservation day view where single day reservations can be updated quickly.
Also,
* Show month with first available end date when opening date picker in reservation modal
* Fix a bug in citizen reservation overwrite
* Show same reservations only once
> EVAKA-4240 citizen reservation inline editor

- frontend/src/lib-common/local-date.ts
The withMonth method blindly replaces month from date, so if created date is invalid it will break example e2e tests. This will change date to use date-fns setMonth so if day overflows we get last day of given month.
> Fix withMonth method

- frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
- frontend/src/citizen-frontend/income-statements/types/body.ts
- frontend/src/citizen-frontend/income-statements/types/form.ts
- frontend/src/employee-frontend/components/IncomeStatementPage.tsx
- frontend/src/lib-common/api-types/incomeStatement.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
- service/src/main/resources/db/migration/V138__income_statement_checkup_consent.sql
- service/src/main/resources/migrations.txt
- Make incomes register / kela consent optional in entrepreneur info
- Change Kela wording: A Kela checkup is not done for everyone
- Add a recommendation to accept the highest fee
- Add a note about the partner's responsibility to fill the income statement form, too
- Add a legal disclaimer about confidentiality
> EVAKA-4213 Income statement tweaks

- message-service/src/main/kotlin/fi/espoo/evaka/msg/properties/SfiSoapProperties.kt
- message-service/src/main/kotlin/fi/espoo/evaka/msg/service/sfi/SfiAccountDetailsService.kt
After a change in printing provider Suomi.fi messages requires a field called contact person that is currently not provided.
> EVAKA: Add suomi.fi contact person

- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
logback silently drops log messages if log meta contains anything that
can't be encoded to JSON using its internal default Jackson instance.
In this case, it attempted to encode AsyncJobType as an object and
failed to encode this field: `val payloadClass: KClass<T>`
Let's pass the type as string instead
> Fix async job runner logging

- frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
This seems like the easiest and simplest solution to the problem of urls without protocol being interpreted as relative urls.
I'm not sure if we even want to allow plain http :smile:
> Require protocol in unit url

- service/src/main/kotlin/fi/espoo/evaka/shared/domain/HelsinkiDateTime.kt
Fix setting child's departure time sometimes failing at the database level by fixing `HelsinkiDateTime`'s `withTime` method to update nano seconds as well.
> EVAKA-HOTFIX fix attendance arrival and departure time nanos

- apigw/src/internal/app.ts
Make evaka-ai internal by removing proxy so that authorization can be removed and deployment bucket won't be needed. UI won't be used for now.
> EVAKA-AI: remove api-gw proxy

- compose/db/postgresql.conf
The JIT actually makes some queries _slower_ in local and ci environments. The time to make just in time compilation dominates the query time when we don't have much data.
> Turn off Postgres JIT in local/ci

- frontend/src/employee-mobile-frontend/components/common/GroupSelector.tsx
There was a complaint that when the number of groups is large, it's not possible to select the desired group. As a solution, make the group selector scrollable. Height is limited for better readability.
> Employee mobile frontend: Make group selector scrollable

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Fix transfer application clean up to take 5yo daycare into account when checking daycare transfer applications. Also, make the clean up a bit more conservative so that new placement types do not cause the clean up to be overeager and cancel applications which should not be cancelled.
> EVAKA-HOTFIX transfer application clean up

- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt
- service/src/main/kotlin/fi/espoo/voltti/pdfgen/PDFService.kt
Currently specific fonts are required to be available in application resources even if not used in templates (see https://github.com/Tampere/trevaka/commit/15e731fec8bcf5107cc339af10be45c80459f545). This adds support to load all available fonts from `resources/ttf` directory.
As a side note this also fixes Montserrat bold for you because old implementation was
```
val montserrat = getResourcePath("ttf/Montserrat-Regular.ttf")
val montserratBold = getResourcePath("ttf/Montserrat-Regular.ttf")
```
but looking at your template files it seems that bold Montserrat is not even used so no harm here (fonts are embedded to PDF only if used)
> Add pdf fonts customization support

- service/src/main/resources/db/migration/R__dev_temp.sql
- service/src/main/resources/db/migration/V141__attendance_reservation.sql
- service/src/main/resources/migrations.txt
Move `attendance_reservation` creation to a permanent migration.
> EVAKA-4240 permanent attendance reservation migration

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaOrganizerChildrenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/Varda.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaOrganizerChild.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/MockVardaIntegrationEndpoint.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- send ssn or oid, not both
- parse varda errors with regex (structure varies too much to use data classes)
- replace UUID with ChildId where practical
- clean up old data classes (prefer translated keys over json properties)
> EVAKA-4000 fix oid sending and error parsing

- frontend/src/citizen-frontend/applications/editor/contact-info/ChildSubSection.tsx
- frontend/src/e2e-playwright/specs/0_citizen/citizen-daycare-application.spec.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-preschool-application.spec.ts
- frontend/src/e2e-playwright/utils/application-forms.ts
- frontend/src/employee-frontend/components/PersonProfile.tsx
- frontend/src/employee-frontend/components/person-profile/PersonFamilyOverview.tsx
- frontend/src/employee-frontend/types/family-overview.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/FamilyOverviewTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/PreschoolTerms.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/IncomeController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/FamilyController.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/FamilyInitializerService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/FamilyOverviewService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
* Add instructions about adding family memebers to applications
* Add dependants living in the same address as the applicant to application's "other children" list by default
* Fix family initialization not adding child's other guardian to the family
* Show family overview without income to unit supervisors
This PR does not fix cases where family initialization fails when the applicants partner is already the head of the family.
> EVAKA-4288 family initialization improvements

- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/AsyncJobConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
Add another AsyncJobRunner to a) try out the possibility b) separate varda processing to avoid blocking important jobs
> EVAKA-4000 Add vardaAsyncJobRunner

- service/src/main/resources/WEB-INF/templates/club/decision.properties
- service/src/main/resources/WEB-INF/templates/daycare/transfer/decision.properties
- service/src/main/resources/WEB-INF/templates/daycare/transfer/decision_sv.properties
- service/src/main/resources/WEB-INF/templates/daycare/voucher/decision.properties
- service/src/main/resources/WEB-INF/templates/daycare/voucher/decision_sv.properties
- service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.properties
- service/src/main/resources/WEB-INF/templates/preparatory/decision.properties
- service/src/main/resources/WEB-INF/templates/preparatory/decision_sv.properties
- service/src/main/resources/WEB-INF/templates/preschool/decision.properties
- service/src/main/resources/WEB-INF/templates/preschool/decision_sv.properties
- service/src/main/resources/WEB-INF/templates/shared/common.html
- service/src/main/resources/WEB-INF/templates/shared/common.properties
- service/src/main/resources/WEB-INF/templates/shared/common_sv.properties
- service/src/main/resources/WEB-INF/templates/shared/daycare-correction.html
* Remove (broken) part that details the required attachments for correction requests on preschool and preparatory decisions
* Fix the layout of address info on decision corrections part
* Clarify that the date following child name on decisions is the child's date of birth
* Update preparatory decision texts
> EVAKA-4273 finalize preparatory decisions

- service/src/main/kotlin/fi/espoo/evaka/shared/job/JobSchedule.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaDevController.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
- enable scheduled varda reset by default
- add param for max new children to process
> EVAKA-4000 schedule varda reset

- service/src/main/kotlin/fi/espoo/evaka/shared/utils/FuelExtensions.kt
- service/src/test/kotlin/fi/espoo/evaka/shared/utils/FuelExtensionsTest.kt
- Varda rate limiter causes thousands of varda requests to block on 429 RETRY_AFTER causing the async jobs to congest. Fail on 429 by default to avoid this
> Short circuit fuel retry on 429 to avoid blocking calls

- frontend/src/employee-frontend/components/invoices/Invoices.tsx
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
Prevent parallel invoice generation, refactor code:
- database lock blocks parallel operations. Explicit locking always adds a risk of deadlocks, but I think this is worth a try
- disable UI button during the operation to avoid multiple clicks
- simplify some JDBI mapping cases
- rename period to range in some places
*Note: depends on https://github.com/espoon-voltti/evaka/pull/1410*, so those commits are included but are not really meant to be a part of this pull request
> [EVAKA-4293] Prevent parallel invoice generation

- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/MockKoskiServer.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/Oppija.kt
- service/src/main/resources/db/migration/R__koski_views.sql
Add support for sending study rights belonging to SSN-less children *if* they have a person OID set in the database.
If both are set, SSN has priority, so OID is only used as a fallback.
> Identify SSN-less children with oid in Koski integration

- frontend/src/e2e-playwright/pages/citizen/citizen-applications.ts
- frontend/src/e2e-playwright/pages/citizen/citizen-decisions.ts
- frontend/src/e2e-playwright/pages/employee/finance/finance-page.ts
- frontend/src/e2e-playwright/pages/employee/messages/messages-page.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-map.spec.ts
- frontend/src/e2e-playwright/specs/5_employee/employee-pin.spec.ts
- frontend/src/e2e-playwright/utils/element.ts
Playwright's `isVisible` is still not perfectly atomic and may throw exceptions randomly
-> use `waitForSelector` under the hood whenever possible instead of polling `isVisible`. In the future we might be able to use locator `waitFor` API once that gets released in Playwright 1.16
> Reduce flakiness caused by repeated isVisible checks

- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiPayloadIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
Wrong: resignation date = first date when the child *is not present*
Correct: resignation date = last date when the child *is present*
There can't be two states on the same date, so fix some edge cases by prioritizing study right termination state over anything else (e.g. "present" state).
> Revert Koski incorrect off-by-one fix + fix original problem in a different way

- compose/e2e/playwright.Dockerfile
Remove `deb.nodesource.com` from apt sources, because its sertificate is outdated and we don't need it as a part of our own build.
> EVAKA-HOTFIX Fix playwright image build

- frontend/src/citizen-frontend/async-rendering.tsx
- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
- frontend/src/citizen-frontend/messages/MessagesPage.tsx
- frontend/src/citizen-frontend/messages/ThreadList.tsx
- frontend/src/employee-frontend/components/ApplicationPage.tsx
- frontend/src/employee-frontend/components/IncomeStatementPage.tsx
- frontend/src/employee-frontend/components/UnitFeaturesPage.tsx
- frontend/src/employee-frontend/components/application-page/VTJGuardian.tsx
- frontend/src/employee-frontend/components/async-rendering.tsx
- frontend/src/employee-frontend/components/child-information/ChildDetails.tsx
- frontend/src/employee-frontend/components/child-information/FridgeParents.tsx
- frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx
- frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
- frontend/src/employee-frontend/components/finance-basics/FeesSection.tsx
- frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx
- frontend/src/employee-frontend/components/messages/Sidebar.tsx
- frontend/src/employee-frontend/components/messages/ThreadList.tsx
- frontend/src/employee-frontend/components/person-profile/PersonFridgeHead.tsx
- frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx
- frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx
- frontend/src/employee-mobile-frontend/components/async-rendering.tsx
- frontend/src/employee-mobile-frontend/components/attendances/AttendancePageWrapper.tsx
- frontend/src/employee-mobile-frontend/components/staff/StaffPage.tsx
- frontend/src/lib-components/async-rendering.tsx
- Use translations for the active language in `renderResult()`
- Re-introduce `<UnwrapResult>`. `renderResult()` now uses it to be able to use the translations from the context. Hooks can only be called from components.
- `<UnwrapResult>` can be used directly for the cases where the loading or failure state rendering needs to be customized. `renderResult()` is more readable and should be used for the simple case.
> Refactor `renderResult()`

- frontend/src/citizen-frontend/calendar/WeekElem.tsx
Disable smooth scroll in e2e tests in mobile calendear, because it interferes with clicking a fixed positioned button.
> Fix a flaky e2e test

- frontend/src/e2e-playwright/specs/0_citizen/citizen-applications-list.spec.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-club-application.spec.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-daycare-application.spec.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-header.spec.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-income-statement.spec.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-preschool-application.spec.ts
This seems to avoid some flakiness in e2e tests.
> Remove redundant navigation in Playwright tests

- .circleci/config.yml
- README.md
- bin/add-license-headers.sh
- CI: implement REUSE license compliance checking in CI
- Use the official reuse-tool image as the executor
- Using our own wrapper should no longer really be necessary as there aren't any custom exceptions -> no need for custom logic
- Now that all files have licensing data available, this can finally be added to CI so that license headers will never be forgotten again
- Downside here is that now CI will nag on every commit until the headers have been added but the best solution honestly will be to just either configure the `add-license-headers.sh` script to pre-commit hooks or in IDEs -- a small pain now but saves a big pain later
- CI: update all images
- Nothing breaking, just keeping up-to-date
- CI: use smaller executors where possible
- And be explicit with `resource_class`
- Also, …
> CI: REUSE compliance checks

- frontend/src/employee-frontend/types/finance-basics.ts
It seems that webpack doesn't handle type-only imports from type-only modules very well, so tell it that we're importing and exporting a type here.
> Fix a re-export warning from webpack

- frontend/src/employee-frontend/components/messages/MessageEditor.tsx
Even though message draft receivers are saved and recovered correctly, a mistake in a hook causes them to clear on load.
> Message draft receiver bugfix

- .circleci/config.yml
We need to keep information about installs and deployments here in bucket.
This will write metadata files during install (for cleanup) and deployment (to see what version is installed)
> Write frontend install and deploy metadata 

- service/src/main/kotlin/fi/espoo/evaka/shared/utils/FuelExtensions.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaTokenProvider.kt
- service/src/test/kotlin/fi/espoo/evaka/shared/utils/FuelExtensionsTest.kt
Varda uses 429 RETRY_WAIT to control both the maximum number of requests per day as well as the frequency of the requests (too many req/s). In the latter case it is better to wait than fail, so use a threshold value for abort instead of always aborting
> Instead of aborting on any 429 response, use a treshold value

- service/src/integrationTest/kotlin/fi/espoo/evaka/childimages/ChildImageTest.kt
- service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImageController.kt
This avoids keeping the connection open while we are streaming just bytes from s3 to the client
> Explicitly scope the database connection

- frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx
- frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
- frontend/src/citizen-frontend/applications/editor/validations.ts
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/e2e-playwright/pages/mobile/child-attendance-page.ts
- frontend/src/e2e-test/pages/employee/mobile/child-page.ts
- frontend/src/employee-frontend/components/child-information/DailyServiceTimesSection.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ReservationModalSingleChild.tsx
- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkDeparted.tsx
- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkPresent.tsx
- frontend/src/employee-mobile-frontend/components/attendances/components.tsx
- frontend/src/employee-mobile-frontend/components/staff-attendance/ExternalStaffMemberPage.tsx
- frontend/src/employee-mobile-frontend/components/staff-attendance/MarkExternalStaffMemberArrivalPage.tsx
- frontend/src/employee-mobile-frontend/components/staff-attendance/StaffMarkArrivedPage.tsx
- frontend/src/employee-mobile-frontend/components/staff-attendance/StaffMarkDepartedPage.tsx
- frontend/src/employee-mobile-frontend/components/staff-attendance/components/staff-components.tsx
- frontend/src/lib-common/form-validation.ts
- frontend/src/lib-components/atoms/form/TimeInput.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Replace native browser time inputs with our own `TimeInput`. Also shorten the time validation info texts to not break the layout.
> EVAKA time inputs

- frontend/src/employee-mobile-frontend/App.tsx
- frontend/src/employee-mobile-frontend/api/auth.ts
- frontend/src/employee-mobile-frontend/components/ensureAuthenticated.tsx
- frontend/src/employee-mobile-frontend/components/mobile/MobileLander.tsx
- frontend/src/employee-mobile-frontend/state/user.tsx
- frontend/src/lib-components/molecules/FullScreenDimmedSpinner.tsx
- Move auth status from App level to UserContext
- Refactor auth status to use Result in order to handle errors gracefully and display loading status
- Fix FullScreenDimmedSpinner to actually use the whole screen estate
- Simplify RedirectToMainPage
> Fix promise rejection error when fetching auth status in mobile frontend

- frontend/src/employee-mobile-frontend/components/attendances/notes/ChildNotes.tsx
> Fix group note filtering, show currently selected group's notes only

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationDetailsService.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
When a new preschool daycare application is created for a child with just a preschool placement do not treat it as a transfer application even when the application's preferred unit is not the same as the placement's unit. With "ghost units" the application unit won't match anyway.
Be a bit more conservative with cancelling preschool daycare transfer applications and do not cancel applications for children with just a preschool placement.
> EVAKA-HOTFIX preschool daycare transfer applications

- frontend/src/e2e-test/specs/2_employee-2/employee-dailynote.spec.ts
- frontend/src/employee-frontend/components/unit/tab-groups/notes/NotesModal.tsx
Simplify default selected tab to show either child or group note tab regardless of note counts
> Simplify default selected note tab in desktop

- frontend/src/employee-frontend/components/child-information/PedagogicalDocuments.tsx
This change makes the create pedagogical document button visible to admins, unit supervisors,
staff, and special education teachers
> EVAKA-4290 Set the correct roles for who can create pedagogical documents

- frontend/src/citizen-frontend/pedagogical-documents/PedagogicalDocuments.tsx
- frontend/src/e2e-playwright/pages/citizen/citizen-pedagogical-documents.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-pedagogical-documents.spec.ts
- frontend/src/e2e-test-common/dev-api/fixtures.ts
- frontend/src/e2e-test-common/dev-api/types.ts
- frontend/src/lib-common/generated/api-types/pedagogicaldocument.ts
- frontend/src/lib-components/layout/Table.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentControllerCitizen.kt
Shows the preferred name or first names of the child on each document row if there are documents pertaining to more than one child.
This PR also removes the small gap between table columns and memoizes the Pedagogical Documents view on the citizen side.
> EVAKA-4290 Support multiple children on the Pedagogical Documents citizen view

- message-service/Dockerfile
- message-service/entrypoint.sh
- service/Dockerfile
- service/entrypoint.sh
Enable Java Datadog profiling using environment variable `DD_PROFILING_ENABLED`. Requires Datadog agent running on AWS node.
> Enable Java datadog profiling

- frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/notes/ChildDailyNoteForm.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/notes/NotesModal.tsx
- frontend/src/employee-frontend/utils/index.ts
- frontend/src/employee-mobile-frontend/components/attendances/AbsenceSelector.tsx
- frontend/src/employee-mobile-frontend/components/attendances/notes/ChildStickyNotesTab.tsx
- frontend/src/employee-mobile-frontend/components/attendances/notes/DailyNotesTab.tsx
- frontend/src/employee-mobile-frontend/components/attendances/notes/GroupNotesTab.tsx
- frontend/src/employee-mobile-frontend/components/common/GroupSelector.tsx
- frontend/src/employee-mobile-frontend/components/mobile/components.tsx
- frontend/src/lib-components/atoms/Chip.tsx
- frontend/src/lib-components/employee/notes/StickyNoteTab.tsx
- frontend/src/lib-components/molecules/modals/BaseModal.tsx
- frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- Add child/group name subheadings to desktop
- Use chips instead of radios in desktop
- DRY the desktop daily note form altogether
- Do not close the daily note on desktop after deleting the note
- Unify headings, labels and placeholders between mobile and desktop
- Unify margins between form components
> Fix some visual and usability issues in notes

- service/src/main/resources/db/migration/V168__varda_reset_child_timestamps.sql
- service/src/main/resources/migrations.txt
Add migration for timestamp fields
> EVAKA-4000 add timestamps to varda_reset_child

- frontend/src/lib-common/utils/file.ts
- frontend/src/lib-common/utils/helpers.ts
- frontend/src/lib-components/molecules/FileDownloadButton.tsx
On iOS, popups are blocked by default in Safari and confusing to use in
Chrome (suddenly a new tab and I can't go back to where I came from). So
instead of opening in a new tab (`_blank`) we now open attachments in
the same window. This way the user can now go back to the eVaka UI by
the browser's back button (or swiping).
The HTML5 download functionality has quite poor UX on iOS, as it
- on Safari it asks whether to download, but gives no indication of where the file went
- on Chrome it just looks like nothing happened
Due to this, we now open the attachments in the same window as the app
in this case as well.
> EVAKA-4290 Fix download attachment experience on iOS

- service/src/main/kotlin/fi/espoo/evaka/pairing/PairingsController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AuditQueries.kt
- service/src/main/resources/db/migration/V169__ensure_mobile_devices.sql
- service/src/main/resources/migrations.txt
- upsert immediately after pairing (vs only after refreshing mobile device session)
- use correct id column in mobile device upsert
- create missing evaka_user rows if any mobile devices are missing
> Fix `evaka_user` upsert for mobile devices

- .circleci/config.yml
Use versioned aws-builder image instead hash.
> Use versioned aws-builder image

- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/components/reports/VardaErrors.tsx
- frontend/src/employee-frontend/types/reports.ts
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/reports/VardaErrorsReport.kt
- Show varda error age in varda errors report.
- Age is calculated from either  
-- varda_reset_child.created if reset_timestamp is null (e.g. reset failed)
-- varda_service_need.created otherwise
> Evaka 4000 varda error report add created

- service/src/main/kotlin/fi/espoo/evaka/shared/job/JobSchedule.kt
Espoo already has this enabled in prod/staging, so this will mostly affect other Espoo environments and Tampere
> Enable FreezeVoucherValueReports by default

- frontend/src/employee-frontend/components/ai/AIPage.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/Occupancy.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyGraph.tsx
- frontend/src/employee-frontend/index.tsx
- typings say min/max should be numbers, even for type=time scales. In
reality type=time requires Date objects
- merge defaults.font instead of replacing it
- move datefn adapter side-effect to entry point
- `steppedLine` doesn't exist anymore and should be `stepped`. No idea
why type checks didn't catch this
- rename scale names. "xAxis"/"yAxis" seem to work based on some magic chartjs name mangling, but it's IMHO better to se "x"/"y" directly for clarity
- add explicit types to data/datasets props
> Fix broken charts

- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
Attendances in round the clock units can't be ended automatically so we need to expect that some are accidentally left un-ended.
- Ensure unit sees only attendances to itself
- Ensure endless attendance is visible for unit even if the placement (or backup placement) has ended
> EVAKA-FIX backup care attendances

- frontend/src/lib-components/layout/Container.tsx
Symmetrical 16px margins should be used by default in resolutions narrower than desktop. 32px horizontal margins should only be applied to desktop and above.
> Fix default horizontal margins in ContentArea

- frontend/src/citizen-frontend/map/UnitListItem.tsx
- frontend/src/lib-components/white-space.ts
Add missing 40px "XL" margin between 32 and 48. New X5L is now 120px.
All current margins of XL and above are now slightly narrower, but seemed to be good all around.
> Use design system margins

- frontend/src/employee-frontend/components/unit/tab-groups/groups/group/GroupTransferModal.tsx
- frontend/src/lib-components/atoms/dropdowns/Select.tsx
Fix `<Select/>` to require passing `getItemValue` prop when the type parameter is not a subtype of the type `string | number`.
> EVAKA-HOTFIX better props typing for Select

- frontend/src/lib-components/molecules/FileUpload.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
- service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImage.kt
- service/src/main/kotlin/fi/espoo/evaka/s3/ContentTypeUtils.kt
- Model allowed/known contentTypes as an enum class
- File extension must match the content type
- Render contentType/extension related error messages in the file upload component
> Whitelist and validate attachment file extensions

- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/applying/ApplyingRouter.tsx
- frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponseList.tsx
- Remove `/decisions` route from root level, always route to `/applying/decisions`
- Remove duplicate routes from root router, handle everything in `ApplyingRouter`
> Fix decisions routing in citizen frontend

- apigw/src/shared/config.ts
- apigw/src/shared/routes/auth/saml/index.ts
Use full URL in redirects. Requires `EVAKA_BASE_URL` environment variable in non-local environments.
> Use full URL in redirects

- service/src/main/resources/db/migration/R__koski_views.sql
There's never any reason to try to void a study right if we don't have an OID. I'm still not sure if this scenario is possible with the current code, but it's reasonable to do this anyway.
Based on production data investigation, this seems to be a problem with only legacy data where a row was inserted to `koski_study_right` without a valid OID. This should not be possible anymore, because we run the `INSERT` without OID and `UPDATE` with OID in the same transaction.
> Don't try to void study rights that were never sent

- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
Slightly modified version of https://github.com/espoon-voltti/evaka/pull/1611. The tests are updated slightly and the query is split into three distinct cases:
* children with a placement to the queried unit but no attendance or backup placement
* children with a backup placement to the queried unit but no attendance
* children with an ongoing or recently ended attendance to the queried unit
> Fix child attendances to round the clock backup care

- frontend/src/employee-frontend/components/Header.tsx
- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/lib-common/utils/useAxiosResponseInterceptor.ts
- frontend/src/lib-common/utils/useInterval.ts
- frontend/src/lib-common/utils/usePeriodicRefresh.ts
- Add `useInterval` hook for fetching unread message counts every minute
- Instead of manually tracking the unread count after opening the thread, just mark the thread read and refresh unread counts
- Simplify `unreadCount` logic in `Header`
- Also load message accounts only in the message context, do not expose refresh callback
- They are always needed in the header
- There is no use fetching them again after message page is mounted
> Refresh employee's unread message counts periodically

- frontend/src/employee-frontend/api/income-statement.ts
- frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx
- Display count of income statements awaiting handler
- Also hide pagination when there's nothing to paginate
- Refactor to useApiState and search params as object
> Display count of income statements awaiting handler

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/FamilyOverviewTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/resources/db/migration/V176__evaka_user_income_updated_by.sql
- service/src/main/resources/migrations.txt
- Add `evaka_user` rows for all `income.updated_by` references
- Add missing foreign key index to `income.updated_by`
- create new column first to verify that there are no broken references
- Add missing fk index
- Use inner joins on `income.updated_by`
> Add missing foreign key index to income.updated_by

- frontend/src/employee-frontend/components/ChildInformation.tsx
- frontend/src/employee-frontend/components/async-rendering.tsx
- frontend/src/employee-frontend/components/child-information/Assistance.tsx
- frontend/src/employee-frontend/components/child-information/AssistanceAction.tsx
- frontend/src/employee-frontend/components/child-information/AssistanceNeed.tsx
- frontend/src/employee-frontend/components/child-information/ChildApplications.tsx
- frontend/src/employee-frontend/components/child-information/ChildDetails.tsx
- frontend/src/employee-frontend/components/child-information/FeeAlteration.tsx
- frontend/src/employee-frontend/components/child-information/GuardiansAndParents.tsx
- frontend/src/employee-frontend/components/child-information/MessageBlocklist.tsx
- frontend/src/employee-frontend/components/child-information/PedagogicalDocuments.tsx
- frontend/src/employee-frontend/components/child-information/Placements.tsx
- frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx
- frontend/src/employee-frontend/components/child-information/assistance-action/AssistanceActionForm.tsx
- frontend/src/employee-frontend/components/child-information/assistance-action/AssistanceActionRow.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/AssistanceNeedForm.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/AssistanceNeedRow.tsx
- frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
- frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
- frontend/src/employee-frontend/components/child-information/placements/ServiceNeeds.tsx
- frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx
- frontend/src/employee-frontend/state/child.tsx
- frontend/src/lib-components/layout/Container.tsx
- Move most data out of `ChildContext` to be managed by the components that use the data
- Data that's used commonly by many components were left, but is now fetched by `ChildContextProvider`
- Add `React.memo`, `renderResult`, etc. usages to affected components
> Refactor child context

- apigw/src/shared/routes/auth/saml/index.ts
Skip error logging if logout relayState is falsy
> EVAKA-FIX avoid error on empty relayState

- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/citizen-frontend/calendar/api.ts
- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx
- frontend/src/lib-common/generated/api-types/reservations.ts
- frontend/src/lib-components/atoms/form/TimeInput.tsx
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
* Fix realtime occupancy graphic to be more intuitive.
* Make `<TimeInput>` slightly wider to fit the `Päättyy` placeholder.
* Also, I noticed that citizen calendar breaks if the child's placements end before the first reservable day, so that is also fixed.
> EVAKA-HOTFIX realtime occupancy graph and calendar fixes

- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Adds sv and en translations for the 'reservations and realized' header
on the calendar day view.
Also fixes the Swedish translation of 'Realized'.
> Fix Finnish only translation on calendar day view

- service/src/main/resources/db/migration/V177__income_statement_awaiting_handler_index.sql
- service/src/main/resources/migrations.txt
Supposedly fixes bad query performance as full table scan should not be needed anymore.
> Add missing hander is null index to income_statement

- service/owasp-suppressions.xml
Temporarily suppress CVE-2021-43466 regarding Thymeleaf, upgrade reminders are in place
> Temporarily suppress CVE-2021-43466 regarding Thymeleaf

- frontend/src/citizen-frontend/applications/editor/ApplicationFormClub.tsx
- frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx
- frontend/src/citizen-frontend/applications/editor/ApplicationFormPreschool.tsx
- frontend/src/citizen-frontend/applications/editor/validations.ts
When next year's club and preschool terms are added any start dates before the term's start are incorrectly interpreted as invalid.
Club and preschool applications get a sensible default start date, which the application validation function incorrectly interprets as an already filled start date.
Does not yet affect production since we haven't configured next year's terms yet.
> EVAKA-HOTFIX fix application start date validation

- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
- frontend/src/employee-frontend/types/reports.ts
- frontend/src/lib-common/generated/api-types/reports.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/Common.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt
- service/src/main/resources/dev-data/espoo-dev-data.sql
- Remove most assistance need bases from test data
- Rename `SMALLER_GROUP` action in test data
- Remove "esiopetus" from some assistance measures
Since bases/actions are configured using database rows, the report should use this information instead of relying on a static hard-coded list.
- Generated API types are not used, because our API generation doesn't handle `Map<K, V>` columns correctly and fixing this seems complicated.
These columns were always reported as 0: "other bases", "no bases", "other actions", "no actions". The "other" columns were broken because they assumed an option with `OTHER` value, but the database model uses non-empty `otherText` to model these cases. The "no" columns were broken because of incorrect handling of SQL NULL values.
- add assistance action measures …
> Update assistance need/action/measure data, fix and extend report

- frontend/src/employee-mobile-frontend/components/attendances/Absences.tsx
- frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts
Absences are now centered with an inline label and a horizontal line above them.
Before
After
> Fix child absence layout in employee mobile

- frontend/src/employee-mobile-frontend/components/attendances/child-info/ChildSensitiveInfo.tsx
- frontend/src/lib-common/generated/api-types/sensitive.ts
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/sensitive/ChildSensitiveInformation.kt
- service/src/main/kotlin/fi/espoo/evaka/sensitive/GetChildSensitiveInfoQueries.kt
Display type of current placement instead of all placements in child sensitive info
- previously the page would list all placements including placements from the past and future
- leave placementTypes temporarily for backward compatibility
- remove $placementSelector variable in PlacementQueries.kt for better autocomplete and IDE experience in general
> Fix placement type in child sensitive info

- frontend/src/citizen-frontend/personal-details/PersonalDetails.tsx
If the user's initial preferred name is empty and they don't select anything in the preferred name dropdown, the frontend sent and empty string. Fix by defaulting to the user's first name.
> EVAKA-HOTFIX: Fix initial person details save when the user's preferred name is empty

- frontend/package.json
- frontend/yarn.lock
Apparently the latest webpack version might reduce build times since some backwards compatibility features causing slowdowns were put behind a flag that is not on by default.
> Upgrade to webpack 5.64 + upgrade related deps

- frontend/src/citizen-frontend/header/DesktopNav.tsx
- frontend/src/citizen-frontend/header/MobileNav.tsx
- frontend/src/lib-components/async-rendering.tsx
This way we don't show the login button (or anything else) while loading the auth status.
This also fixes a flaky e2e test, caused by clicking the language select just when the auth status arrives and the user name is rendered, and thus hitting the user menu instead.
> Use <UnwrapResult> in citizen navi

- frontend/src/e2e-playwright/specs/6_mobile/messages.spec.ts
- frontend/src/e2e-playwright/specs/7_messaging/messaging.spec.ts
- frontend/src/employee-frontend/components/child-information/MessageBlocklist.tsx
- frontend/src/lib-common/generated/api-types/messaging.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageReceiversIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/ChildRecipientQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/ChildRecipientsController.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- Remove head_of_child JOINs from message receiver queries, because only the guardians are allowed to receive messages
- Move queries from controller to queries, use extension functions
> Send messages to guardians only

- frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx
This fixes a flaky e2e test. The button moves when data loading finishes and the click hits a wrong target.
> Show the add income button only when data has loaded

- service/src/main/kotlin/fi/espoo/evaka/shared/job/JobSchedule.kt
Run varda jobs every other day to bypass varda guardian delay
> EVAKA-4000 run reset every other day

- frontend/src/e2e-playwright/specs/6_mobile/absences.spec.ts
- frontend/src/e2e-playwright/specs/6_mobile/child-attendances.spec.ts
- frontend/src/e2e-playwright/specs/6_mobile/messages.spec.ts
- frontend/src/e2e-playwright/specs/6_mobile/notes.spec.ts
- frontend/src/e2e-playwright/specs/6_mobile/pin-login.spec.ts
- frontend/src/e2e-playwright/specs/6_mobile/staff.spec.ts
- frontend/src/e2e-playwright/utils/mobile.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/SystemControllerTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/MobileDeviceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/PairingQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V178__delete_mobile_devices_from_employee.sql
- service/src/main/resources/migrations.txt
Remove `mobile_device` table's link to the `employee` table, delete mobile devices from `employee` table and make `evaka_user` table's `type_id_match` constraint more constraining.
> Remove mobile devices from employee table

- apigw/src/internal/mobile-device-session.ts
- apigw/src/internal/routes/auth-status.ts
- apigw/src/shared/routes/auth/saml/index.ts
- apigw/src/shared/session.ts
express-session saves the session to the backing store (= Redis) lazily and asynchronously after the HTTP response has been sent. This introduces a possible race condition if we save something important
to the session, and assume the next request will see it immediately. This assumption is not true, because the backing store has latency, or might even return an error which is probably just logged and ignored since the HTTP response has already been sent.
In practice, CSRF tokens sometimes hit this race condition...the /auth/status endpoint saves the CSRF secret to the session, and returns HTTP 200 response which includes a CSRF cookie. If a new request comes in quickly enough, it will contain the CSRF cookie but the server will not see the CSRF secret in the session, leading to a "invalid …
> Ensure we wait until session is saved in /auth/status and after all req.logIn calls

- frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponse.tsx
- frontend/src/employee-frontend/components/absences/AbsenceModal.tsx
- frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
- frontend/src/employee-frontend/components/child-information/BackupPickup.tsx
- frontend/src/employee-frontend/components/child-information/CreateApplicationModal.tsx
- frontend/src/employee-frontend/components/child-information/VasuAndLeops.tsx
- frontend/src/employee-frontend/components/child-information/placements/CreatePlacementModal.tsx
- frontend/src/employee-frontend/components/group-caretakers/GroupCaretakersModal.tsx
- frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
- frontend/src/employee-frontend/components/person-profile/PersonFeeDecisions.tsx
- frontend/src/employee-frontend/components/person-profile/person-fridge-child/FridgeChildModal.tsx
- frontend/src/employee-frontend/components/person-profile/person-fridge-partner/FridgePartnerModal.tsx
- frontend/src/employee-frontend/components/person-search/AddVTJPersonModal.tsx
- frontend/src/employee-frontend/components/person-search/CreatePersonModal.tsx
- frontend/src/employee-frontend/components/person-shared/person-details/AddSsnModal.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/GroupModal.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/group/GroupTransferModal.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/group/GroupUpdateModal.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/missing-group-placements/BackupCareGroupModal.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/missing-group-placements/GroupPlacementModal.tsx
- frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposalRow.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ReservationModalSingleChild.tsx
- frontend/src/employee-frontend/components/vasu/templates/CopyTemplateModal.tsx
- frontend/src/employee-frontend/components/vasu/templates/CreateOrEditTemplateModal.tsx
- frontend/src/employee-frontend/components/vasu/templates/CreateQuestionModal.tsx
- frontend/src/lib-components/molecules/modals/FormModal.tsx
This enables more effective `React.memo()`, because passing props as objects virtually always create a new value identity.
> Use plain values instead of objects in `FormModal` props

- frontend/src/employee-frontend/components/absences/Absences.tsx
- frontend/src/employee-frontend/components/absences/StaffAttendance.tsx
Fix a bug in absence table that caused changing groups from the dropdown to update previous group's staff attendance values to the selected group.
Also, save staff attendance if user navigates away from the view before the debounced save callback is fired and disable the inputs when new values are being loaded.
> EVAKA-HOTFIX staff attendance in absence table

- frontend/src/e2e-playwright/pages/citizen/citizen-header.ts
- frontend/src/e2e-playwright/specs/0_citizen/citizen-header.spec.ts
If playwright was fast (or slow?) enough, it might have been possible that it clicked login button and then the language select button immediately before the page redirected to the login process. So let's wait until login is done before trying to select the language.
> Attempt to fix a flaky e2e test

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
Error MA003 should not result to new reset. MA003 means that Varda does not yet have the child's guardian data but will fetch it in the following 24 hours. Trying to reset the child again will result to Varda deleting their guardian data and therefore ensure that the reset will fail again. Hence we must consider MA003 as successful outcome for reset mechanism and then rely on our update mechanism. It will send the missing data on the next run.
> EVAKA-4000 add workaround for error MA003

- frontend/src/citizen-frontend/auth/requireAuth.tsx
- frontend/src/citizen-frontend/personal-details/PersonalDetails.tsx
- service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonalDataControllerCitizen.kt
Require strong auth for viewing the personal details page and updating the details. Currently the page can be accessed but update request will fail with 403.
Lock icons for _weak citizen_ are coming in #1726
> Citizen personal details only with strong auth

- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkAbsent.tsx
Unify user experience with mark arrived/departed when marking child absent. `history.go(-2)` takes the user back to group page.
> Unify user experience in mobile when marking child absent

- frontend/src/e2e-playwright/pages/employee/vasu/vasu.ts
- frontend/src/e2e-playwright/specs/5_employee/vasu.spec.ts
- frontend/src/e2e-playwright/utils/element.ts
- frontend/src/e2e-test-common/dev-api/index.ts
- frontend/src/employee-frontend/components/vasu/VasuPage.tsx
- frontend/src/employee-frontend/components/vasu/VasuStateTransitionButtons.tsx
- frontend/src/employee-frontend/components/vasu/api.ts
- frontend/src/employee-frontend/components/vasu/components/FollowupQuestion.tsx
- frontend/src/employee-frontend/components/vasu/sections/DynamicSections.tsx
- frontend/src/employee-frontend/components/vasu/templates/CreateQuestionModal.tsx
- frontend/src/employee-frontend/components/vasu/templates/api.ts
- frontend/src/employee-frontend/components/vasu/vasu-content.ts
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
After a Vasu document has been finalized, a followup question is added to what currently is question number 5.
The followup section renders as a text area and when a comment is added, the comment is rendered as a "log row" above the text area. Each "log row" is tagged with the date when it was created as well as the name of the author.
> Allow storing of many rows of followup comments in Vasu documents

- frontend/src/e2e-playwright/pages/employee/child-information-page.ts
- frontend/src/e2e-playwright/specs/5_employee/child-information-assistance-needs.spec.ts
- frontend/src/e2e-test-common/dev-api/fixtures.ts
- frontend/src/e2e-test-common/dev-api/index.ts
- frontend/src/e2e-test-common/dev-api/types.ts
- frontend/src/employee-frontend/components/child-information/assistance-need/AssistanceNeedForm.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/AssistanceNeedRow.tsx
- frontend/src/lib-common/generated/action.d.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- If child is or has been in preschool, hide pre preschool service needs from non admins
- Add E2E tests for child information page assistance needs
> Hide old assistance need information when child goes to preschool

- proxy/files/etc/nginx/conf.d/nginx.conf.template
- service/src/integrationTest/kotlin/fi/espoo/evaka/childimages/ChildImageTest.kt
- service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImageController.kt
- service/src/main/kotlin/fi/espoo/evaka/s3/DocumentService.kt
- service/src/main/kotlin/fi/espoo/evaka/s3/S3DocumentClient.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/AwsConfig.kt
- Add an internal nginx endpoint that can proxy any URL
- When a child image request comes, generate a presigned S3 URL
- Use [X-Accel-Redirect](https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/) to the internal endpoint to serve the presigned URL to the client through nginx only
This way, slow clients don't consume a thread from service while downloading a child image. nginx uses async i/o and is able to handle thousands of concurrent requests, whereas service chokes already for a few hundred.
> Serve child images through nginx

- .circleci/config.yml
Due to invalid syntax, it never even ran the `docker-compose build` command.
> Fix retrying of docker-compose build

- frontend/src/citizen-frontend/messages/ThreadListItem.tsx
- frontend/src/employee-frontend/components/messages/MessageComponents.tsx
- frontend/src/employee-mobile-frontend/components/messages/MessagePreview.tsx
- frontend/src/employee-mobile-frontend/components/messages/ThreadView.tsx
- frontend/src/lib-common/date.ts
Previously the date was always formatted as time.
Also unify formatting in all message components.
> Fix message date formatting in employee mobile thread view

- frontend/src/employee-frontend/api/reports.ts
- frontend/src/employee-frontend/components/reports/VardaErrors.tsx
- service/src/main/kotlin/fi/espoo/evaka/reports/VardaErrorsReport.kt
- Varda errors -report does not really need the date filter as it makes unclear if there are new errors before the selected value
> Remove unnecessary date filter from varda errors report

- frontend/src/employee-mobile-frontend/api/attendances.ts
- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkDeparted.tsx
- frontend/src/lib-common/generated/api-types/attendance.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
The now deleted `fetchChildrenAttendances` was very inefficient because it couldn't utilize indexes properly and fetching the data inside the `fetchChildrenBasics` query has an unnoticeable performance impact (checked in prod with `EXPLAIN ANALYZE`).
> Mobile child attendance query performance improvements

- frontend/src/employee-mobile-frontend/App.tsx
- frontend/src/employee-mobile-frontend/state/user.tsx
* Wait that auth status request completes before rendering components that use it. Fixes a bug where users were always redirected to employee mobile's default page no matter the initial url.
* Store employee mobile selected group in local storage.
> Employee mobile save selected group

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservableDaysCalculationUnitTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenControllerTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Cities have different thresholds, so make the threshold configurable.
Set threshold to 150 hours in Espoo which translates to Monday at 18:00 week before.
> Make citizen reservation threshold configurable

- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Many e2e tests logged a 500 internal server error to console because of a missing message account.
> Fix misleading 500 internal server errors in e2e tests

- frontend/src/e2e-playwright/pages/mobile/messages.ts
- frontend/src/e2e-playwright/specs/6_mobile/messages.spec.ts
- frontend/src/employee-mobile-frontend/components/common/BottomNavbar.tsx
- frontend/src/employee-mobile-frontend/components/common/GroupSelector.tsx
- frontend/src/employee-mobile-frontend/components/common/GroupSelectorBar.tsx
- frontend/src/employee-mobile-frontend/components/common/TopBarWithGroupSelector.tsx
- frontend/src/employee-mobile-frontend/components/messages/MessageEditorPage.tsx
- frontend/src/employee-mobile-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-mobile-frontend/components/messages/ThreadView.tsx
- frontend/src/employee-mobile-frontend/state/messages.tsx
In mobile messaging,
- Don't use personal accounts
- Don't show "All" in group selection
- Remove the caret from group selection if there is only one group
> EVAKA-4256 remove personal accounts from mobile messaging

- .circleci/config.yml
- apigw/package.json
- frontend/assetsTransformer.js
- frontend/eslint-plugin/index.js
- frontend/eslint-plugin/rules/no-duplicate-testcafe-hooks.js
- frontend/eslint-plugin/rules/no-testonly.js
- frontend/package.json
- frontend/src/e2e-playwright/jest-environment.js
- frontend/src/lib-common/utils/helpers.spec.ts
- frontend/webpack.config.js
The eslint config is now two part:
- The base config is used for JavaScript
- The override config is used for TypeScript files, and adds a TypeScript parser and TypeScript specific rules
> Enable ESLint also for .js files

- frontend/build.js
- frontend/package.json
- frontend/src/citizen-frontend/index-esbuild.html
- frontend/src/employee-frontend/index-esbuild.html
- frontend/src/employee-mobile-frontend/index-esbuild.html
- frontend/yarn.lock
`yarn dev` now uses esbuild. A clean build takes around 1 second, whereas with webpack it took around 1 minute.
`tsc  --watch` is run concurrently for type checking. `esbuild` itself doesn't check types at all.
If something is broken and it prevents your work, use `yarn dev:old` to start the old webpack dev-server.
Missing things for using `esbuild` also for production builds:
- Use `browserslist` to determine the esbuild target
- Upload a release to Sentry
Nice to have but still missing:
- Use `babel-plugin-styled-components`
> Use esbuild for bundling in development

- frontend/build.js
- frontend/package.json
- frontend/yarn.lock
Preserve symlinks under the customizations module. This makes it possible to symlink a customizations module to `lib-customizations/<city-name>` and still use symlinks inside the customizations module.
The `preserveSymlinks` option of esbuild doesn't seem to be enough if there's a path that has multiple symlinks along it.
> Resolve symlinks correctly under lib-customizations

- .github/dependabot.yml
Daily at first. Let's see how much spam we get.
> Enable dependabot for npm dependencies

- .github/dependabot.yml
Appears that dependabot doesn't support yarn v2 or newer after all:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem
https://github.com/dependabot/dependabot-core/issues/1297#issuecomment-804491821
> Disable dependabot for frontend deps

- frontend/src/employee-mobile-frontend/App.tsx
- frontend/src/employee-mobile-frontend/api/messages.ts
- frontend/src/employee-mobile-frontend/components/common/BottomNavbar.tsx
- frontend/src/employee-mobile-frontend/components/messages/MessageEditorPage.tsx
- frontend/src/employee-mobile-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-mobile-frontend/state/messages.tsx
- If user has active pin login, we should show unread messages notification only regarding the groups user has permissions for
- Fix a bug regarding selected group in messages page
- Remove some unnecessary code related to unread message counts
> EVAKA-4256 tweak unread message counts logic in mobile

- frontend/src/employee-frontend/components/vasu/components/VasuContainer.tsx
- frontend/src/employee-frontend/index.css
Printing `display: flex` causes issues where text may be rendered so
that the top half of a line of text is on one page and the bottom half
on the second page. This fixes that issue by using `display: block` and
`break-inside: avoid-page` to keep relevant blocks on a single page.
> EVAKA-4349 Ensures printing of vasu documents looks OK

- docs/diagrams/src/evaka-correcting-invoicing.puml
- docs/diagrams/src/evaka-monthly-invoicing.puml
- Add process diagram of invoicing; this is cut-n-paste conversion from "Laskutus" frame in "eVaka 2.0 kaaviot" Miro board
- Add initial process diagram for corrections in invoicing
- These are published on wiki
> EVAKA DOC add invoicing diagram sources

- frontend/src/employee-frontend/components/unit/unit-reservations/AbsenceDay.tsx
Use absence type translations in the reservation week view.
> EVAKA-FIX Use i18n with AbsenceDay

- frontend/src/e2e-playwright/pages/employee/finance/finance-page.ts
- frontend/src/e2e-playwright/specs/4_finance/value-decisions.spec.ts
Use `.check()` instead of `.click()` to check checkboxes/radio buttons. Playwrigh checks that they're actually checked, so this should be safer than clicking.
While at it, add some misc enhancements.
> Flaky test fix

- .circleci/template.yml
This fixes a regression in CI integration test job times caused by recompilation.
> Include sficlient in build cache

- frontend/src/citizen-frontend/messages/MessageEditor.tsx
Replace vh with percentage to avoid height problems with ios safari (experimental)
> EVAKA-FIX citizen message editor height in percentage

- frontend/src/e2e-playwright/pages/mobile/messages.ts
- frontend/src/e2e-playwright/specs/6_mobile/messages.spec.ts
- frontend/src/employee-mobile-frontend/App.tsx
- frontend/src/employee-mobile-frontend/components/messages/MessageEditorPage.tsx
- frontend/src/employee-mobile-frontend/components/messages/MessagePreview.tsx
- frontend/src/employee-mobile-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-mobile-frontend/state/messages.tsx
- Fix badly placed message context (it needs group id)
- Use selectedAccount instead of selectedGroup to ensure group selector works concisely
- Add e2e-test for supervisor clicking through message boxes
> EVAKA-4265 fix misplaced messages context

- frontend/src/employee-frontend/components/reports/Occupancies.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Mark cells where a occupancy percentage couldn't be calculated because of a missing caretaker count on occupancy report.
> Explanation for missing values on occupancy report

- frontend/src/e2e-playwright/pages/employee/vasu/vasu.ts
- frontend/src/e2e-playwright/specs/5_employee/vasu.spec.ts
- frontend/src/employee-frontend/components/common/VasuStateChip.tsx
- frontend/src/employee-frontend/components/vasu/sections/VasuEvents.tsx
Adds test for marking a vasu doc as reviewed and also refactors earlier test and `data-qa` attributes to preserve original
styling in the vasu document events list.
> Adds e2e test of moving a vasu doc to the reviewed state

- frontend/src/e2e-playwright/pages/employee/child-information.ts
- frontend/src/e2e-playwright/specs/5_employee/child-information.spec.ts
- frontend/src/e2e-playwright/specs/5_employee/service-need.spec.ts
- frontend/src/e2e-test-common/dev-api/fixtures.ts
- frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
- frontend/src/employee-frontend/components/child-information/placements/ServiceNeeds.tsx
- frontend/src/employee-frontend/components/child-information/placements/service-needs/MissingServiceNeedRow.tsx
- frontend/src/employee-frontend/components/child-information/placements/service-needs/ServiceNeedEditorRow.tsx
- frontend/src/employee-frontend/components/child-information/placements/service-needs/ServiceNeedReadRow.tsx
- frontend/src/lib-common/generated/api-types/serviceneed.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/ServiceNeedTestFixtures.kt
- service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeed.kt
- service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/resources/db/migration/V191__service_need_option_active_flag.sql
- service/src/main/resources/migrations.txt
A simple way to hide some service need options from the UI when the options shouldn't be selectable anymore but they also can't be deleted completely.
> EVAKA-4317 deactivating service need options

- frontend/src/employee-frontend/components/absences/AbsenceTable.tsx
- frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
- frontend/src/employee-frontend/components/common/AgeIndicatorIcon.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ReservationsTable.tsx
Add age symbols here and there.
> EVAKA-3458 use more age symbols

- frontend/src/e2e-playwright/pages/mobile/message-editor.ts
- frontend/src/e2e-playwright/specs/6_mobile/messages.spec.ts
- frontend/src/employee-mobile-frontend/components/messages/MessageEditorPage.tsx
- frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts
Instead of plain white page, tell user that message can't be sent.
> EVAKA-FIX: mobile message editor handles blocked guardians

- frontend/src/e2e-playwright/pages/mobile/list-page.ts
- frontend/src/e2e-playwright/specs/6_mobile/child-attendances.spec.ts
- frontend/src/employee-mobile-frontend/components/attendances/ChildListItem.tsx
Show group name when listing all children.
> EVAKA-4301 show child group info in mobile

- frontend/src/citizen-frontend/messages/ThreadView.tsx
- frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
before
after
long title will still be scrolled
>  Fix constantly visible (double) scroll bars in message thread views

- service/src/main/kotlin/fi/espoo/evaka/shared/db/DevDataInitializer.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/dev-data/lock-database-nowait.sql
We first wait for all queries to finish as an optimization before using any locks. However, it's still possible a new query is started
asynchronously after this check, so we still want to lock all database tables before executing the reset.
Locking uses NOWAIT, so we back away immediately if our locking attempt fails and retry after a delay. This avoids potential deadlocks that could happen if we used normal locking that would compete with other running queries.
In our E2E tests there are 4 typical scenarios:
1. no queries are running when `/reset-db` is called -> no waiting is needed, locking succeeds immediately, and reset works
2. a query is running when `/reset-db` is called -> we wait until the query finishes, then locking succeeds immediately, and reset works
3. a query is started …
> Lock all database tables before reset

- frontend/src/employee-frontend/components/absences/StaffAttendance.tsx
All data was sent to the backend correctly, but staff attendance inputs still showed the old numbers when changing groups. This created an illusion about multiple groups having the same data.
> EVAKA-HOTFIX: Reset staff attendance inputs when changing group

- frontend/src/employee-mobile-frontend/components/attendances/ChildListItem.tsx
- frontend/src/lib-components/employee/notes/StaticStickyNote.tsx
- frontend/src/lib-components/typography.ts
Checked that all `Bold` and `Light` usages were fine after removing the `color` property.
> Fix application tooltip contrast

- frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
- frontend/src/lib-components/typography.ts
`Italic` is needed for cases where text is not on white background (ie. in `Tooltip`).
Revert `Light` to include dimmed color.
> Add a separate Italic typography element

- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/ParentshipControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
Only use future terms that can be applied to as application default start date. Previously, the default start date would be the first term that starts in the future. Also, the effect of the order of the terms was implicit.
Also fix a flaky integration test.
> EVAKA better application default start date

- service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
- service/src/integrationTest/resources/application-integration-test.yaml
- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
Made this with env variable for the less amount of hassle in case all cities will take this later on as default way of working.
Also, fixed related test, that had feeDecision id as string instead of a string array.
> TREV-433 possibility to send fee decisions in advance with configurable date

- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
- service/src/main/resources/db/migration/V194__evaka_user_for_paper_application_guardians.sql
- service/src/main/resources/migrations.txt
If a paper application is created for a guardian who has not logged in to eVaka, they might not yet have a row in `evaka_user`. This causes errors later when application `guardian_id` is used as income `modified_by`.
Fix future cases by adding `evaka_user` upsert, and existing cases by upserting using a migration.
> Ensure evaka_user row is created for paper application guardians

- frontend/src/e2e-playwright/pages/employee/finance-basics.ts
- frontend/src/e2e-playwright/pages/employee/finance/finance-page.ts
- frontend/src/e2e-playwright/utils/page.ts
- frontend/src/employee-frontend/components/finance-basics/FeesSection.tsx
- frontend/src/lib-components/atoms/buttons/AsyncButton.tsx
This makes e2e faster, because animations took seconds and now they take milliseconds.
Some tests needed fixing that relied on seeing one of the transient `AsyncButton` states.
> Use shorter `AsyncButton` animations in e2e tests

- frontend/src/citizen-frontend/messages/ThreadView.tsx
- Increase `max-height` to fit roughly 5 rows of text
- Responsive layout
> Fix citizen thread header container

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaQueries.kt
Not all applications and placement proposals go through unit supervisors so this condition for finding a placement's application is unnecessarily strict. Just noticed this by accident.
> Varda: remove unnecessarily strict application condition

- frontend/src/employee-frontend/api/person.ts
- frontend/src/employee-frontend/components/Header.tsx
- frontend/src/employee-frontend/components/child-information/MessageBlocklist.tsx
- frontend/src/employee-frontend/components/messages/GroupMessageAccountList.tsx
- frontend/src/employee-frontend/components/messages/MessageContext.tsx
- frontend/src/employee-frontend/components/messages/MessagesPage.tsx
- frontend/src/employee-frontend/components/messages/Sidebar.tsx
- frontend/src/employee-frontend/components/messages/api.ts
- frontend/src/employee-mobile-frontend/api/messages.ts
- frontend/src/employee-mobile-frontend/components/messages/MessageEditorPage.tsx
- frontend/src/employee-mobile-frontend/components/messages/ThreadView.tsx
- frontend/src/employee-mobile-frontend/state/messages.tsx
- frontend/src/lib-common/generated/api-types/messaging.ts
- frontend/src/lib-components/employee/messages/MessageEditor.tsx
- frontend/src/lib-components/employee/messages/types.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageAccountQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
- Remove `nested` prefix from all property and variable names
- Rename `NestedMessageAccount` interface to `AuthorizedMessageAccount`
> Refactor NestedMessageAccount naming

- frontend/src/e2e-playwright/pages/employee/guardian-information.ts
- frontend/src/e2e-playwright/specs/4_finance/person-finance-decisions.spec.ts
- frontend/src/e2e-test-common/dev-api/fixtures.ts
- frontend/src/employee-frontend/components/person-profile/PersonFeeDecisions.tsx
- frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueAreaReportTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
- Fix value decision query result mapping
- Order person finance decisions by `sentAt` first and `validFrom` second
- Add e2e-test for person voucher value decisions
- Fix fee decision query result mapping
> EVAKA FIX finance decision queries after refactoring

- frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx
- frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
- frontend/src/employee-mobile-frontend/components/attendances/actions/MarkDeparted.tsx
- frontend/src/employee-mobile-frontend/components/attendances/components.tsx
- frontend/src/lib-components/atoms/form/InputField.tsx
- frontend/src/lib-components/atoms/form/TextArea.tsx
- frontend/src/lib-components/atoms/form/TimeInput.tsx
- frontend/src/lib-components/molecules/PinInput.tsx
* Use `1rem` font size in input placeholder and info texts and a darker orange with warning text.
* Add proper padding to input's right side when the input contains a button, icon or a symbol.
* Let info text continue to multiple rows, but do not let it stretch vertically.
* Fix input positioning when focus borders are added.
> EVAKA-4385 update input info visuals

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationQueriesSmokeTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
jsonb ->> returns the data as `text`, so we need to cast it to uuid to make sure it can be deserialized as ServiceNeedOptionId
> Make sure serviceNeedId is returned as uuid

- frontend/src/employee-mobile-frontend/components/common/PageWithNavigation.tsx
The recent refactoring of the views caused children to be hidden behind
the navigation bar in some instances.
> Fix child list items hidden behind nav bar

- frontend/src/e2e-playwright/specs/4_finance/invoices.spec.ts
- frontend/src/e2e-playwright/specs/5_employee/guardian-information-page.spec.ts
- frontend/src/e2e-test-common/dev-api/fixtures.ts
- frontend/src/lib-common/generated/api-types/invoicing.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/Helpers.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/InvoicingReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Invoices.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
- service/src/main/resources/db/migration/V196__invoice_area_id.sql
- service/src/main/resources/migrations.txt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/domain/InvoicesTest.kt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClientTest.kt
* `invoice` table: `agreement_type` replaced by `area_id`
* `Invoice` type: `agreementType: Int` replaced by `areaId: AreaId`
* `InvoiceDetailed` type: `areaId: AreaId` added so it has both. Agreement type is joined from care_area in queries
> Replace invoice agreement_type with area_id

- frontend/src/employee-frontend/components/common/LabelValueList.tsx
- frontend/src/lib-components/typography.ts
Having a <Checkbox> inside a <label> seems to break, because the <label> causes an unwanted automatic click in the child <input> element. Fix by preventing the label autoclick.
> Fix checkbox behavior in decision draft view

- frontend/src/employee-mobile-frontend/components/attendances/child-info/ImageEditor.tsx
Remove weird height and overflow settings from `ImageEditor`. Previously the canvas would (sometimes) only be 100px tall.
Also add some horizontal margin to allow scrolling the view if image is very narrow compared to the device screen.
> Fix ImageEditor layout

- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/MissingHeadOfFamilyReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/MissingHeadOfFamilyReport.kt
- do not show deceased children on missing head of family report
- tests for the report
> Do not show deceased children on missing head of family report

- frontend/src/e2e-test/pages/employee/finance/finance-page.ts
- frontend/src/e2e-test/specs/4_finance/invoices.spec.ts
- frontend/src/employee-frontend/components/invoice/InvoiceRowsSectionRow.tsx
- frontend/src/lib-common/generated/api-types/invoicing.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/codegen/src/main/kotlin/evaka/codegen/apitypes/Config.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/TestInvoiceProductProvider.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Invoices.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Placements.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClient.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/EspooInvoiceProducts.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceProductProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/JdbiExtensions.kt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClientTest.kt
Make invoice products configurable by moving them behind `InvoiceProductProvider` interface.
The product `FREE_OF_CHARGE` is also removed from the Espoo implementation since it's identical to the `ABSENCE` product so a data migration must be done before deploying this commit.
> Configurable invoice product provider

- service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/SoapStackIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt
The SOAP API requires printing provider + billing ID, even if printing is disabled. :man_shrugging:
> Fix Suomi.fi printing nullability

- frontend/src/employee-frontend/components/unit/unit-reservations/AbsenceDay.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ReservationsTable.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- Swap rows
- first row is for absence/reservation/service time
- second row is for attendance time
- Highlight attendance rows
- Highlight current day in table header
- Fix borders
> EVAKA-4378 Reservation calendar highlights and borders

- frontend/src/employee-frontend/api/unit.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/ChildDay.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ReservationsTable.tsx
- frontend/src/lib-common/api-types/reservations.ts
Highlight differences in expected and actual attendance times in week view.
The calculation is "best effort" based on two `HH:mm` local time strings without date part. This is only used for highlighting in the calendar so edge cases are expected and might not matter much. The functionality can be improved once the reservation data model supports reservations that span multiple days.
> Highlight attendance time differences in unit calendar week view

- frontend/src/employee-frontend/components/absences/PeriodPicker.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx
- frontend/src/lib-components/typography.ts
> Use Title typography component instead of H3 in unit calendar titles

- frontend/src/citizen-frontend/header/DesktopNav.tsx
- Remove min-width
- Use the same letter-spacing as in other headers and nav tabs
- 4px bottom border instead of 3px
- Align text in wrapped rows to center
- Add more padding to nav links on bigger screens
> Implement new citizen nav style

- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/citizen-frontend/calendar/WeekElem.tsx
- frontend/src/employee-frontend/components/absences/AbsenceTable.tsx
- frontend/src/employee-frontend/components/absences/utils.ts
- frontend/src/employee-frontend/components/invoice/AbsencesModal.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ReservationModalSingleChild.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ReservationsTable.tsx
- frontend/src/lib-common/date.ts
- frontend/src/lib-common/local-date.ts
Use date-fns locales when formatting dates with week days.
> Use date-fns locale in weekday formatting

- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/AbsenceServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimes.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/OperationalDays.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
- Use daily service times in reservation totals
- Daily service times are included only for operational days
- Move duplicate operational days code to one place
> EVAKA-4142 include daily service times in total reserved hours

- frontend/src/e2e-test/specs/5_employee/vasu.spec.ts
This hopefully removes the flakiness caused by Playwright being faster than React.
> Use `type()` instead of `fill()` in vasu e2e tests

- frontend/src/lib-components/atoms/form/TimeInput.tsx
Make room so that the right edge of wide numbers fits in the time input read view
> Fix time input right border cut off

- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
Use ISO day of week when doing operational day checks in reservations. In practice makes Sunday reservable.
> Fix reservation operational day check

- frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
Show only current service need in group tables.
Note: This doesn't affect Espoo because `groupsTableServiceNeedsEnabled` feature flag is false.
> Update group table service needs

- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/citizen-frontend/calendar/TimeRangeInput.tsx
- frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/ReservationModalSingleChild.tsx
- frontend/src/employee-mobile-frontend/api/attendances.ts
- frontend/src/employee-mobile-frontend/components/attendances/AttendanceDailyServiceTimes.tsx
- frontend/src/employee-mobile-frontend/components/attendances/ChildListItem.tsx
- frontend/src/employee-mobile-frontend/components/attendances/Reservations.tsx
- frontend/src/lib-common/generated/api-types/attendance.ts
- frontend/src/lib-common/reservations.ts
- frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/AbsenceServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/domain/HelsinkiDateTime.kt
- service/src/main/resources/db/migration/V205__single_date_reservations.sql
- service/src/main/resources/migrations.txt
Refactor reservation modal to only allow single date reservations. This is what users were already doing so it's more intuitive and it makes all kinds of calendar views simpler. Reservations starting at `00:00` or ending at `23:59` are combined with each other in employee mobile so that units that are open around the clock get a better picture of a child's real reservations.
> Refactor reservation model

- frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
Changing the decision handler should be possible even if "invoicedByMunicipality" is not checked
Before:
After:
> Move decision handler input to top level

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/NewInvoiceGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/NewDraftInvoiceGenerator.kt
Treat planned absences as other absences when the child has less attendances than `contractDaysPerMonth`. This way they affect invoicing if there are too many of them with respect to `contractDaysPerMonth`.
> Contract day invoicing with too many planned absences

- frontend/src/employee-frontend/components/unit/unit-reservations/ReservationsTable.tsx
- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
- sort in frontend instead of backend. There's no big advantage in sorting in backend. It's clearer to have the sort order close to the place where data is shown instead of making the sort order a "hidden" part of the API contract
- sort by last+first name
- format in last+first format
- show only one first name, so week/month calendar views are more consistent
> Minor week calendar fixes

- frontend/src/e2e-test/specs/8_access/access.spec.ts
- frontend/src/employee-frontend/components/ChildInformation.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/SecurityConfig.kt
`PermittedRoleActions` must now be provided by city-specific configuration
> Remove default role mappings

- service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
If a child starts in the middle of a month, consider the month as a full absence month if all operational days _starting from the start date_ are absences.
> Partial month + all days as absences

- frontend/src/e2e-test/pages/employee/holiday-periods.ts
- frontend/src/e2e-test/specs/5_employee/holiday-period.spec.ts
- frontend/src/employee-frontend/components/absences/AbsenceLegend.tsx
- frontend/src/employee-frontend/components/absences/Absences.tsx
- frontend/src/employee-frontend/components/holiday-periods/HolidayPeriodForm.tsx
- frontend/src/employee-frontend/components/holiday-periods/api.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx
- frontend/src/employee-frontend/types/absence.ts
- frontend/src/employee-mobile-frontend/components/attendances/AbsenceSelector.tsx
- frontend/src/employee-mobile-frontend/types/index.ts
- frontend/src/lib-common/generated/api-types/daycare.ts
- frontend/src/lib-common/generated/api-types/holidaypediod.ts
- frontend/src/lib-common/local-date.ts
- frontend/src/lib-customizations/common.tsx
- frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/holidaypediod/HolidayPeriod.kt
- service/src/main/kotlin/fi/espoo/evaka/holidaypediod/HolidayPeriodQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt
- service/src/main/resources/db/migration/V206__free_absence_type.sql
- service/src/main/resources/db/migration/V207__free_holiday_period.sql
- service/src/main/resources/migrations.txt
- Add FREE_ABSENCE absence type to be used with free summer holiday periods
- Support optional free period in admin's holiday period UI
> EVAKA-4162 Add optional free period to holiday period

- frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
- service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReport.kt
- don't do extra work in the query just to get zero counts for every possible action/measure/basis
- do more counting in less joins
- replace subquerys in column position (= basically lateral joins) with normal joins
> Improve assistance needs and actions report query

- frontend/README.md
- frontend/package.json
- frontend/unpack-pro-icons.sh
- frontend/yarn.lock
- Upgraded the packages from beta to release
- Fetched and uploaded the `6.0.0` packages to S3 as documented in the [README](https://github.com/espoon-voltti/evaka/tree/master/frontend#using-professional-icons)
> Upgrade font awesome from 6.0 beta to release

- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/calendar/ActionPickerModal.tsx
- frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/HolidayModal.tsx
- frontend/src/citizen-frontend/holiday-periods/CtaBanner.tsx
- frontend/src/citizen-frontend/holiday-periods/api.ts
- frontend/src/citizen-frontend/holiday-periods/state.tsx
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Shows the "report holiday" action in the citizen calendar view.
The action currently opens a modal with some dummy contents. The form itself will be implemented in future PRs.
> EVAKA-4162 Show 'report holiday' option when holiday banner is active

- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceUpkeepIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/daycare/service/AbsenceService.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancy.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
- service/src/main/resources/db/migration/V209__single_date_attendances.sql
- service/src/main/resources/migrations.txt
Split longer attendances by date. Employee mobile should work more or less like it used to. One difference is that departed children that arrived two days before are shown to have arrived the day before at 00:00 in the child's profile because finding the real arrival time in sql was not trivial for me.
> Refactor attendance database model

- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/HolidayPeriodBanner.tsx
- frontend/src/citizen-frontend/holiday-periods/state.tsx
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/e2e-test/pages/citizen/citizen-header.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts
Banner would be rendered on top of the sub navigation on applications page. Just hide the banner on non-relevant pages instead of trying to adapt the absolute-positioned map view to changing available viewport area.
> EVAKA-4162 Hide CTA banner on non-relevant pages

- frontend/src/employee-frontend/components/absences/AbsenceTable.tsx
- frontend/src/employee-frontend/components/absences/Absences.tsx
- frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
- frontend/src/employee-frontend/components/common/AgeIndicatorIcon.tsx
- frontend/src/employee-frontend/components/reports/VoucherServiceProviderUnit.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/ReservationsTable.tsx
- frontend/src/lib-components/atoms/Tooltip.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
* Delete the age indicator variant without a tooltip.
* Change default tooltip text to a shorter and more generic variant.
* Replace the word "hoito" in the tooltip texts in application and ungrouped children lists.
> EVAKA-4403 child age indicator tooltips

- frontend/src/citizen-frontend/LoginPage.tsx
Fixes `<div> cannot appear as a descendant of <p>` error on login page.
> Fix invalid DOM nesting on login page

- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/lib-common/generated/api-types/reservations.ts
- frontend/src/lib-common/reservations.ts
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
A time range with non-nullable `endTime` was used for citizen attendances although attendances might not have a end time set yet.
> Fix citizen reservations endpoint

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/specs/5_employee/backup-care.spec.ts
The real fix would be to replace acl_views (that use `current_date`) with parameterized queries / functions, but this is not currently easy to do
> Fix backup e2e tests with another +1 year hack

- frontend/src/citizen-frontend/income-statements/ChildrenIncomeStatements.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
- frontend/src/e2e-test/pages/employee/finance/finance-page.ts
- frontend/src/e2e-test/specs/4_finance/income-staments.spec.ts
- frontend/src/e2e-test/specs/5_employee/child-income.spec.ts
- frontend/src/employee-frontend/components/PersonProfile.tsx
- frontend/src/lib-customizations/common.tsx
- E2E tests for finance income statement list opening the correct profile page for child income statement and child income editor
- Hide citizen income statement Pagination page number if only 1
- Close person profile income section by default for admin
- Fix react missing key warnings related with translation mangling
> Income statement improvements and fixes

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
- service/src/main/resources/db/migration/V212__voucher_value_decision_annulment_and_validity_timestamps.sql
- service/src/main/resources/migrations.txt
Fix voucher value report so that it correctly refunds annulled decisions or decisions that have had their end date updated because a child has left daycare.
Couldn't come up with any new test cases, but I'm still unsure whether these changes take every single case into account.
> Fix voucher value report for annulled decisions

- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
- frontend/src/citizen-frontend/calendar/HolidayPeriodBanner.tsx
- frontend/src/citizen-frontend/calendar/WeekElem.tsx
- frontend/src/citizen-frontend/header/Header.tsx
- frontend/src/citizen-frontend/header/MobileNav.tsx
- frontend/src/citizen-frontend/header/const.ts
- frontend/src/citizen-frontend/index.css
- frontend/src/citizen-frontend/utils.ts
- frontend/src/lib-common/utils/scrolling.ts
The layout of the page was modified to always keep the header on top without using `position: sticky`. This is done by making the `main` element of the page scrollable, instead of scrolling the whole page including the header.
This MIGHT have an impact on the different pages in the citizen frontend. Everything I tested works, but I appreciate if you take it for a spin!
> EVAKA-4162 Make holiday banner sticky by modifying page layout

- .circleci/template.yml
Previously circle would deploy even if service test or integration test jobs failed.
> Require service test jobs for frontend install

- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationUpdateIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationSummaryIntegrationTests.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentsControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/ChildrenControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionResolutionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/ParentshipControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PartnershipsControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenControllerTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/AuthenticatedUser.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/AuthenticatedUserJsonDeserializer.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/AuthenticatedUserJsonSerializer.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/auth/JwtTokens.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/HttpFilterConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/SpringMvcConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt
- model strong vs weak authentication using `.authLevel` property
- restrict `/citizen/` paths to `AuthenticatedUser.Citizen`
- minor cleanups
> Remove AuthenticatedUser.WeakCitizen

- service/src/main/resources/application.yaml
The timeout must be longer than the ALB keep alive timeout (60s).
> Set evaka-service connection (and keep-alive) timeout to 70s

- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ApplicationsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ChildAgeLanguageReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ChildrenInDifferentAddressReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/Common.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/DecisionsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/DuplicatePeopleReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/EndedPlacementsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/FamilyConflictReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/FamilyContactReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/InvoiceReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/MissingHeadOfFamilyReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/MissingServiceNeedReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/OccupancyReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/PartnersInDifferentAddressReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/PlacementSketchingReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/PresenceReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceNeedReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/SextetReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/StartingPlacementsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/VardaErrorsReport.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/DatabaseConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
- migrations are *not* affected, since they are executed before this configuration is used
- 1 minute is a reasonable default for REST endpoints that are triggered by a user
- reports are an exception and use 10 minutes
- invoice generation also uses 10 minutes, although it would be surprising if any of the individual queries exceeded the 1 minute default timeout
> Use short statement/lock timeouts

- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/holiday-modal/FixedPeriodSelectionModal.tsx
- frontend/src/citizen-frontend/holiday-periods/api.ts
- frontend/src/citizen-frontend/holiday-periods/state.tsx
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts
- frontend/src/lib-common/api-types/holiday-period.ts
- frontend/src/lib-common/generated/api-types/holidayperiod.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayQuestionnaireQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayQuestionnaires.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
- service/src/main/resources/db/migration/V215__holiday_questionnaire_answer.sql
- service/src/main/resources/migrations.txt
Save holiday questionnaire answers to their own database table. Use the saved answers to prefill holiday modal. In the future, the saved answers can be utilized in holiday banner hiding logic and reporting.
Also tie absences created from the questionnaire to the questionnaire for easier detection when deleting previous answers.
> EVAKA-4162 Save holiday questionnaire answers

- frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts
- frontend/src/e2e-test/pages/employee/units/unit-diary-page.ts
- frontend/src/e2e-test/pages/employee/units/unit.ts
- frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
- frontend/src/e2e-test/specs/5_employee/unit-acl.spec.ts
- frontend/src/e2e-test/specs/5_employee/unit-editor.spec.ts
- frontend/src/e2e-test/specs/5_employee/units.spec.ts
- frontend/src/employee-frontend/components/UnitPage.tsx
- frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
- frontend/src/employee-frontend/components/unit/TabAttendances.tsx
- frontend/src/employee-frontend/components/unit/TabUnitInformation.tsx
- frontend/src/employee-frontend/components/unit/tab-attendances/GroupSelector.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
* Rearranges the tabs on the unit page.
* Makes the attendances tab the default (renamed from calendar to attendances).
* Moves the utilisation chart from the unit information tab to the unit attendances tab.
> EVAKA-4455 Reorder unit page tabs and move utilisation chart

- service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/Paging.kt
* Find a care area correctly for a child's own income statement
* Also consider guardianship and applications when finding a care area
* Make the query about 95 % faster
> Income statements awaiting handler list fixes

- frontend/src/citizen-frontend/messages/MessageEditor.tsx
Tested on my android device that had the bug.
- Fix message box staying under keyboard on some mobile devices
- Use correct max-width value
> EVAKA HOTFIX message box under mobile keyboard

- frontend/src/e2e-test/dev-api/index.ts
- frontend/src/e2e-test/utils/mobile.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/SystemControllerTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/MobileDeviceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/MobileDevicesController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/R__acl_views.sql
- service/src/main/resources/db/migration/V216__mobile_device_hard_delete.sql
- service/src/main/resources/migrations.txt
This is no longer needed, since the corresponding evaka_user row remains even after the mobile device is deleted, so "who did this" columns in various tables will still work.
> Remove mobile device soft delete functionality

- service/src/main/resources/db/migration/V216__mobile_device_hard_delete.sql
They are recreated after the migration, since R__acl_views.sql has changed
> Drop dependant views using cascade

- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/GuardianQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/db/migration/V217__guardian_blocklist.sql
- service/src/main/resources/migrations.txt
If a row is in `guardian_blocklist` table, the corresponding guardian<->child relation is never created when processing VTJ data
> Add guardian blocklist mechanism

- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt
Voucher value decision already sums child's and parent's incomes.
This adds same feature to fee decision.
> Add pdf variable for fee decision

- frontend/webpack.config.js
Enable browserslist by adding `useBuiltIns: 'entry'` option to `@babel/preset-env` config.
Previously the browserslist section was ignored and the whole `core-js` was imported. Now it just imports the required polyfills based on the target environment defined by browserslist.
I considered `useBuiltIns: usage` but we would need to be splitting bundles to gain any advantages. The bundle size just ended up being bigger.
```
// debug: true output
Using targets: {
"android": "97",
"chrome": "74",
"edge": "79",
"firefox": "67",
"ios": "12.2",
"opera": "60",
"safari": "12.1",
"samsung": "9.2"
}
```
Difference in bundle size was minimal, which is a good thing because only a handful of now redundant polyfills were removed.
before:
```
Entrypoint main [big] 1.86 MiB (20.8 MiB)
– …
```
> Enable browserslist

- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx
- frontend/yarn.lock
Show tooltip at nearest point in realtime staff attendance graph, which makes the tooltip less jumpy by following the cursor.
Also upgrade chart.js
> Show tooltip at nearest point in realtime staff attendance graph

- frontend/src/employee-frontend/api/unit.ts
- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx
- frontend/src/lib-common/generated/api-types/attendance.ts
- frontend/src/lib-common/generated/api-types/occupancy.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/FixtureBuilder.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancyTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffOccupancyCoefficient.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffOccupancyCoefficientQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancy.kt
- service/src/main/resources/db/migration/V220__staff_occupancy_coefficient.sql
- service/src/main/resources/migrations.txt
- Save occupancy coefficient to staff attendance rows
- Use row-level coefficient in calculations and occupancy graph
- Add table for saving employee specific coefficient per unit
- Saving employee coefficient will be implemented later, use default coefficient as a fallback for now
> EVAKA-4455 Row-level occupancy coefficient calculation

- frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
- frontend/src/citizen-frontend/calendar/CalendarListView.tsx
- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/HistoryOverlay.tsx
- frontend/src/citizen-frontend/calendar/RoundChildImages.tsx
- frontend/src/citizen-frontend/calendar/WeekElem.tsx
- frontend/src/citizen-frontend/map/UnitDetailsPanel.tsx
- frontend/src/employee-frontend/components/GroupCaretakers.tsx
- frontend/src/employee-frontend/components/SettingsPage.tsx
- frontend/src/employee-frontend/components/child-information/assistance-action/AssistanceActionForm.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/AssistanceNeedForm.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/AssistanceNeedRow.tsx
- frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
- frontend/src/employee-frontend/utils/index.ts
- frontend/src/lib-common/generated/api-types/reservations.ts
- frontend/src/lib-common/string.ts
- frontend/src/lib-components/layout/flex-helpers.ts
- frontend/src/lib-components/molecules/ExpandingInfo.tsx
- frontend/src/lib-components/molecules/date-picker/DatePickerDay.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenControllerTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
* Don't allow citizen to add reservations or absences if staff has marked absences.
* Make some frontend optimizations while at it.
* Add child pictures to the calendar and the day modal
Desktop calendar:
Mobile calendar:
Day modal:
> Citizen reservation fixes

- frontend/src/citizen-frontend/messages/MessageEditor.tsx
On Samsum A32 the mobile message editor text area does not respect min-height. Try to fix that according to the internet. Works still on iphone after the change:
> Try to fix message textarea min height bug on android

- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
`sv` and `en` were already ok, that's why they don't change.
> Front page text fix

- service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancy.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ChildAgeLanguageReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
- service/src/main/kotlin/fi/espoo/evaka/reports/ServiceNeedReport.kt
- Always use relative age when determining child age
- Use constant variable for family unit placement coefficient value
- Use service need occupancy coefficients with realtime occupancy
> EVAKA-HOTFIX use relative age in age calculation

- frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx
The child reservation table was not shown if the user has no access to
the daycare acl endpoint. This quickfix removes that issue, but the
employee attendance list is only visible to unit supervisors at this
point.
> EVAKA-4455 Quickfix to show child reservations

- frontend/src/citizen-frontend/income-statements/ChildIncomeStatementEditor.tsx
- frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
- frontend/src/citizen-frontend/income-statements/ChildIncomeStatementView.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx
- frontend/src/citizen-frontend/income-statements/types/body.ts
- frontend/src/e2e-test/pages/citizen/citizen-child-income.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-child-income-statement.spec.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Remove the radio selection about whether the child has income. The form can only be saved by adding info about the child's income.
> Disallow saving a highest-fee income statement for a child

- frontend/src/citizen-frontend/messages/ThreadListItem.tsx
- frontend/src/citizen-frontend/messages/ThreadView.tsx
Add missing parameter to citizen's message attachment button.
> EVAKA-FIX: open message attachments in browser

- frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
The same window.open method is used for opening the application read view itself, so use it here too.
[Figma](https://www.figma.com/file/UyFTAPt5kFhErtP56e7Ze8/eVaka-employee?node-id=894%3A1992)
> Add a "units on map" button to application read view

- .circleci/template.yml
Fixing broken caching reduces integration test job times by ~2 minutes since we no longer recompile all code in the test / integration test jobs.
> Speed up Gradle CI build

- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancySingleDay.tsx
- Extend the graph lines up to current time if there are employees still present
- Make the graph look more like the designs
> Realtime occupancy graph enhancements

- frontend/src/citizen-frontend/RequireAuth.tsx
Previously this was only done if the current page required strong authentication. If it required weak authentication, the browser was redirected directly to the weak authentication login, even if you previously had a strongly authenticated session.
> Always redirect to login page on session expiry

- apigw/src/internal/app.ts
- frontend/src/e2e-test/pages/employee/guardian-information.ts
- frontend/src/e2e-test/specs/5_employee/income.spec.ts
- frontend/src/employee-frontend/api/attachments.ts
- frontend/src/employee-frontend/components/person-profile/income/IncomeItemBody.tsx
- frontend/src/employee-frontend/components/person-profile/income/IncomeItemEditor.tsx
- frontend/src/employee-frontend/types/income.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/attachment/Attachment.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/IncomeController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Incomes.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- service/src/main/resources/db/migration/V227__income_attachments.sql
- service/src/main/resources/migrations.txt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
Provide FinanceAdmins with possibility to include attachments to manually inserted income data.
> EVAKA-4322 income attachments for finance admin

- frontend/src/employee-frontend/components/placement-draft/PlacementDraftRow.tsx
Add minDate to placement plan date picker to softly block making placement plans to history.
> EVAKA-FIX: Avoid placement plans to history

- frontend/src/lib-common/generated/api-types/invoicing.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceCorrectionsController.kt
The reference to an invoice was always supposed to be nullable, but the service types were just incorrect.
> Fix invoice correction invoice nullability

- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Weakly authenticated citizens were not able to POST answers to the holiday questionnaire, even when the 'require strong auth' setting was off.
> Allow weak logins to save answers to holiday questionnaires

- frontend/src/e2e-test/dev-api/index.ts
- frontend/src/e2e-test/pages/employee/units/unit.ts
- frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts
- `move-to-waiting-placement` starts an async job, which might deadlock with the next request(s). Fixing the deadlock is complicated, so wait for the async job to finish as a workaround. Note: there are other application-related tests that may still deadlock (e.g. when sending an application) so this is not a universal solution
- don't wait for a loading indicator to be visible...this only works when the test is slow
> Fix two E2E flakiness problems

- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancy.kt
Using UNION doesn't return any duplicate rows, so staff members who arrived and departed in the same minute only counted as one in the occupancy graphs.
> Include all staff attendances in realtime occupancy numbers

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
- service/src/main/resources/db/migration/V230__invoice_row_idx.sql
- service/src/main/resources/migrations.txt
- save row indexes and use them to sort invoice rows in queries
- row index is mostly a transparent low-level detail, and is not exposed in the `InvoiceRow` / `InvoiceRowDetailed` types
- gaps are allowed and are created if an invoice correction is deleted. This is not a problem, because the sort order is retained, and we never insert rows without first deleting all old ones
- currently the order comes in practice from the invoice_id index in `invoice_row`. In the migration, updating the entire `invoice_row` table in a single SQL statement didn't always result in the correct order, so loop each invoice individually and disable seq scan to try to use this index. This seemed to give correct results, at least based on tests in staging.
- add random shuffling to result lists in various tests …
> Save and use generated invoice row order

- frontend/src/lib-components/employee/messages/MessageEditor.tsx
The message window "avoided" the massive footer, which caused it to be quite small normally. This fix makes it use the available space much more efficiently.
> Make the message editing window use the available space

- frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts
Some application state transitions trigger async jobs that require this data. Even if we don't really care about the jobs, their failures can get propagated to the test, so it's better to make sure the jobs work.
> Flaky E2E fix: make sure service need defaults exist in application tests

- apigw/src/internal/routes/auth-status.ts
- frontend/src/lib-common/api-types/employee-auth.ts
This information will be later in a separate pull request to prevent using the wrong internal-gw session (mobile session in employee, or employee session in mobile)
> Add user type to apigw auth status response

- frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx
Staff attendances for one group would be shown in all groups where a
member of the staff had access. Now only show attendances in the
currently selected group on the group view.
> EVAKA-4406 Only show attendances for the selected group

- frontend/src/employee-frontend/components/Units.tsx
Calling the navigate hook directly during rendering is an error and shows a warning locally. Instead, we should either use useEffect or the Navigate component, and the latter is simpler in this case.
> Don't call navigate while rendering

- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageAccountQueries.kt
- service/src/main/resources/db/migration/V231__message_account_indexes.sql
- service/src/main/resources/migrations.txt
Currently we use a unique constraint per foreign key, but these indexes
are not partial indexes so they include nulls. Also, we have
separate (some_id, active) indexes, and they seem to only exist to allow
the database to do index-only scans based on (id, active) pairs without
needing to read the actual row data.
Replace both with partial indexes that include the active column, but
just include the column instead of using it as a key. Benefits:
- partial index -> no wasted space on NULLs
- active column included -> we can have the unique constraint *and*
index-only scans based on (id, active) pairs with just one index
**In staging this reduced the total size of these indexes in message_account by 84%**
> Improve message_account table indexes

- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/ChartTooltip.tsx
The measurements of width and height of the tooltip body always used the
previous tooltip's content and applied it to the next render. So for
cases where the utilization went from e.g. 15% to 0%, causing the
tooltip body to be slightly smaller, the caret was rendered as detached
from the tooltip itself.
The above issue is fixed by specifying a fixed width/height for the
tooltip, which works when we know the contents, but is not ideal if the
content would be radically different.
> EVAKA-4406 Fix issue where the tooltip positioning was slightly off

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
- When creating fee decisions from drafts, do not fail the whole batch if some have related fee decisions waiting for sending. Instead skip those.
- From the UI point of view this means that the skipped drafts will remain in the search results after the create fee decisions operation is done
> Do not fail whole fee decision batch if there are manual deps

- frontend/src/e2e-test/browser.ts
Some of our pages have a slightly broken layout that confuses Playwright, and it might take a massive screenshot (e.g. 160 000 pixels wide!) that won't happen in less than 5 seconds.
> Increase timeout when taking screenshots

- frontend/src/e2e-test/pages/employee/guardian-information.ts
- frontend/src/e2e-test/specs/5_employee/income.spec.ts
- frontend/src/employee-frontend/components/person-profile/income/IncomeItemEditor.tsx
- frontend/src/employee-frontend/components/person-profile/income/IncomeList.tsx
Attachments can be deleted directly while editing income so we should refresh data if editing itself is canceled
> EVAKA-FIX Reload incomes after cancelling edit

- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx
A bug caused the child count to be 0 if they still had not left the daycare.
> EVAKA-4406 Show correct child count also before they leave

- frontend/src/employee-mobile-frontend/App.tsx
- frontend/src/employee-mobile-frontend/components/staff-attendance/StaffAttendancesPage.tsx
Regression: `:tab` and `:employeeId` both match a path with an employee ID,
and the first route wins.
Previously React Router accepted `:tab(absent|present)`, which was enough
to distinguish it from `:employeeId`. This is no longer supported, so use
two hard-coded routes and pass the information via props instead.
> Fix ambiguous route in staff attendance router

- frontend/src/employee-mobile-frontend/api/unit.ts
- frontend/src/employee-mobile-frontend/components/common/BottomNavbar.tsx
- frontend/src/employee-mobile-frontend/components/messages/MessageEditorPage.tsx
- frontend/src/lib-customizations/employeeMobile.tsx
- frontend/src/lib-customizations/espoo/employeeMobile.tsx
- frontend/src/lib-customizations/types.d.ts
employee-mobile-frontend code imported these previously from employee customizations and by doing so pulled all the employee-frontend translations into the mobile bundle.
This fix reduces the main mobile bundle (main.js) size by ~20%
> Add feature flags to employee mobile customizations

- frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx
Previous change seems to be accidentally introduced here: https://github.com/espoon-voltti/evaka/blame/2c9943c60608da06bb1687f60b1ae7e2bb4db994/frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx#L139-L140
> EVAKA-FIX Use correct boolean when creating retroactive value decisions

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
All "real" queries already sort by row.idx, but the test didn't. It reused the base query, but the base query can't have ORDER BY because of the position it's used in.
**Fixes integration test flakiness**
> Sort by row.idx in test

- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionController.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedController.kt
- For a child in preschool (or after), assistance needs and actions from pre preschool are not shown to non admin. This fixes a bug that caused the filtering to happen to children not YET in preschool, but with a preschool placement
> Evaka fix allow assistance need showing for future preshooling

- frontend/src/e2e-test/pages/employee/messages/messages-page.ts
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
- For unknown reason a flaky test picked the wrong recipient from the list when using index, so use the selection text as selector instead
> Avoid flaky test by using better selector

- apigw/src/internal/routes/auth-status.ts
- apigw/src/shared/service-client.ts
- if `/auth/status` can't find the employee based on the id in an active session, the user is logged out. This fixes a problem in local environment where you might end up with HTTP status 500 and broken app if you have a session and the employee is deleted in the backend (e.g. you run a test that resets the db)
- as a side effect, removes a potential security hole where old sessions belonging to an employee that is deleted could still be used
- refactoring to improve error handling and type safety
> Improve error handling and type safety in internal-gw auth status endpoint

- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
One PR renamed the parameter and all uses, another PR added a new use site -> no merge conflict but the query doesn't work
> Fix parameter name

- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/async/AsyncJobQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobQueries.kt
On 11.5.2022 there was a case where older than one month of history
data would have been useful.
> Remove async jobs after six months instead of just one

- service/src/main/kotlin/fi/espoo/evaka/varda/VardaQueries.kt
Service voucher units have "invoiced_by_municipality" false, so voucher fee data was not sent to varda. Instead just check the unit type.
> Ensure that voucher fee data is sent to varda

- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
- service/src/main/resources/db/migration/V233__fix_voucher_value_decision_swedish_service_need_descriptions.sql
- service/src/main/resources/migrations.txt
When voucher value decisions were inserted into the database the Swedish service need descriptions were incorrectly saved, which meant that drafts and sent decisions were never considered equal.
> Fix unnecessary value decision draft generation

- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/ChartTooltip.tsx
> Fix chart tooltip positioning bug

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/employee-frontend/api/invoicing.ts
- frontend/src/lib-common/api-types/income.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Incomes.kt
- service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
The income dates were not even used anywhere so there is no reason to generate new finance decisions when income validity dates change.
> Fix unnecessary drafts being generated when income dates change

- frontend/src/lib-components/molecules/ThreadListItem.tsx
At least on some iOS devices the default color for HTML button text is *blue*
> Override default HTML button text color in ThreadListItem

- compose/proxy/nginx.conf
- proxy/files/etc/nginx/conf.d/nginx.conf.template
Our CSP config blocks inline scripts, so we need to explicitly whitelist this one
> Add inline "load-failed" script to CSP config

- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/MockKoskiServer.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiClient.kt
This effectively makes it an idempotent operation, so if a study right has been manually voided and the endpoint returns 404, no error is generated.
> Make Koski VOID operation consider status 404 a success

- evaka-bom/build.gradle.kts
- service/buildSrc/build.gradle.kts
- service/buildSrc/src/main/kotlin/Version.kt
- service/custom-ktlint-rules/build.gradle
Spring Boot 2.7.0 uses a newer version of Tomcat, which fixes a CVE
> Upgrade to Spring Boot 2.7.0

- frontend/src/employee-mobile-frontend/api/unit.ts
- frontend/src/employee-mobile-frontend/components/common/GroupSelector.tsx
- frontend/src/employee-mobile-frontend/components/common/GroupSelectorBar.tsx
- frontend/src/employee-mobile-frontend/components/messages/MessagesPage.tsx
- frontend/src/lib-common/generated/api-types/attendance.ts
- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
Implements the new design for the group selector in the employee mobile.
If the realtime staff attendances feature flag is on, the current
utilization will be shown next to the name of each group in the group
selector. In other cases a `present children / total children` count
will be shown.
> EVAKA-4406 Show utilization in group selector for realtime attendances

- .circleci/template.yml
Add retry logic to more places where docker pulls images from the registry.
> Avoid docker i/o timeouts in CI

- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
- service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
- Only cancel sent transfer applications when terminating
- Only clean up sent transfer applications during nightly cleanup. And because sent application cannot have placements nor decisions, no need to try to clean up those
> Only cancel sent transfer applications when terminating

- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileUnitControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
Doubles were truncated to integers, which caused the utilization percentage to differ on the unit list view vs the group selector.
> EVAKA-4406 Fix differing utilization on unit list view vs group select

- frontend/src/employee-mobile-frontend/components/UnitList.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileUnitControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
- Fix bug where utilization was calculated incorrectly if a child was placed in more than one group during their daycare unit placement
- Ensure that the utilization % always is formatted correctly on the supervisor's unit list view.
> Evaka 4406 more utilization fixes

- frontend/src/employee-mobile-frontend/components/UnitList.tsx
The utilization can sometimes be the string 'Infinity', which does not have `toFixed` defined.
> EVAKA-4406 Fix bug where we sometimes called 'toFixed' on a string

- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/applying/ApplyingRouter.tsx
- frontend/src/citizen-frontend/map/MapView.tsx
The page may be scrolled e.g. if the user is viewing the calendar and then navigating to the applying tab. This is bad because the second level menu is not shown in that case.
> Scroll the map page to top on mount

- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
Previous marking child as departed at midnight would fail because of a database constraint.
> Fix marking child departure at midnight

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUpdateServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaQueries.kt
Varda deduces the `urgent` flag from application date, so change the default to 15 days before service need start, which is one day before the point where the application would become urgent.
> Change Varda default application date

- frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
- frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
- frontend/src/employee-frontend/components/absences/AbsenceTable.tsx
- frontend/src/employee-frontend/components/absences/Absences.tsx
- frontend/src/employee-frontend/components/unit/TabAttendances.tsx
- frontend/src/employee-frontend/components/unit/TabUnitInformation.tsx
- frontend/src/employee-frontend/components/unit/tab-attendances/GroupSelector.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/Occupancy.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancySingleDay.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx
- frontend/src/employee-mobile-frontend/api/unit.ts
- frontend/src/employee-mobile-frontend/components/common/BottomNavbar.tsx
- frontend/src/employee-mobile-frontend/components/common/GroupSelector.tsx
- frontend/src/lib-customizations/espoo/featureFlags.tsx
- frontend/src/lib-customizations/types.d.ts
- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
- pass feature flag in frontend instead of accessing global variable
- handle unit-specific flags in queries where a global parameter was previously used
- set unit features in E2E test fixtures instead of overriding frontend feature flags
**Depends on [part 1](https://github.com/espoon-voltti/evaka/pull/2502), and must not be merged until part 1 is in production and feature flags have been added to relevant units**
> Make realtime staff attendance feature flag unit-specific - part 2

- frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
Fixes an issue where an employee who is present in one unit is shown as present in all units where they have access. This bug was present only in the employee mobile
> EVAKA-4406 Fix bug where employee was shown as present in all units

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionsIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
Faulty database query caused invoice corrections being invoiced multiple times.
> Fix invoice corrections being applied multiple times

- frontend/src/citizen-frontend/applications/ChildApplicationsBlock.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
EVAKA-4550: a guardian cannot see another's applications, so the inaccurate placeholder is removed.
> Remove "No applications" placeholder in citizen applications list

- frontend/src/employee-frontend/components/reports/Occupancies.tsx
- frontend/src/lib-components/layout/Table.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
Some small visual improvements to occupancy report's raw-format:
- dates are shown only once in the header
- borders and tooltips to data cells
> Occupancy report improvements part2

- frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx
An annulling voucher value decision cannot be viewed on the standalone value decision page; as such, the link to this page has been removed from the table.
(first row in the table below)
> Remove link for annulling voucher value decisions

- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
> Fix spelling of save in Swedish translation

- frontend/src/employee-frontend/components/MobilePairingModal.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx
- frontend/src/employee-mobile-frontend/components/mobile/PairingWizard.tsx
- frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/pairing/PairingIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pairing/PairingQueries.kt
- Removed lowercase characters from the available character pool for generating pairing codes
- Increased the code length to 12 (from 10) in order to keep the amount of possible combinations ≥ as before
- Device names in the unit view are sorted alphabetically
> Mobile pairing improvements

- frontend/src/employee-mobile-frontend/components/attendances/child-info/ChildSensitiveInfo.tsx
- frontend/src/lib-common/generated/api-types/sensitive.ts
- frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/sensitive/ChildSensitiveInformation.kt
- service/src/main/kotlin/fi/espoo/evaka/sensitive/GetChildSensitiveInfoQueries.kt
Adds the additional info field to the sensitive information view in the employee mobile, mirroring the information visible in the regular employee child information view.
> Add child additional info field to employee mobile

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
Empty finance decisions are only used for annulling other decisions so the contents do not matter.
> Merge any empty finance decisions if they are for the same person

- frontend/src/employee-frontend/api/invoicing.ts
- frontend/src/employee-frontend/components/fee-decisions/FeeDecisionsPage.tsx
- frontend/src/employee-frontend/components/invoices/invoices-state.ts
- frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionsPage.tsx
- frontend/src/employee-frontend/state/invoicing-ui.tsx
- frontend/src/lib-common/generated/api-types/invoicing.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
No need to do manual string serialization/deserialization, since we have today support for fully typed filters.
The main motivation for this change is to eventually remove all special cases which need `IncludeCodeGen`, and then remove the annotation completely.
> Use strongly typed filters in invoicing search APIs

- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/MockDvvModificationsService.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModifications.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyService.kt
Add children into a fridge family starting from the child's date of birth if a child has been added to someone according to DVV. Otherwise handle the event as usual. I don't know if silently ignoring children that are already in another family is a good idea, but that's what happened originally anyway.
> Add children directly into fridge families from dvv child info

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Lets you treat absences of type `FREE_ABSENCE` like an "ordinary" absence instead of giving a daily refund.
> Make effect of free absences on invoices configurable

- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
Do not include `staff_attendance.other_count` in staff count when calculating occupancy for employee mobile. Also fix the data types so that the decimals are included in the unit supervisor's unit list.
> EVAKA HOTFIX unit realized occupancy in supervisor mobile

- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/lib-common/utils/scrolling.ts
- frontend/src/lib-components/atoms/form/TimeInput.tsx
- frontend/src/lib-components/molecules/date-picker/DatePicker.tsx
- frontend/src/lib-components/molecules/date-picker/DatePickerInput.tsx
With some mobile devices, the soft keyboard that opens up when selecting an input in the reservation modal may sometimes overlap with the field. To work around this, whenever a field is focused into, the presence of a soft keyboard is detected with a viewport resize event and after which the input field is scrolled into middle of the view. For the calendar input, the scroll is top-aligned so that it's more likely the day picker will be visible.
> Scroll to reservation modal inputs manually after focus on devices with a soft keyboard

- frontend/src/citizen-frontend/child-documents/CitizenVasuAndLeops.tsx
- frontend/src/citizen-frontend/child-documents/PedagogicalDocuments.tsx
- frontend/src/citizen-frontend/child-documents/api.ts
- frontend/src/citizen-frontend/child-documents/state.tsx
- frontend/src/citizen-frontend/child-documents/vasu/VasuPage.tsx
- frontend/src/citizen-frontend/header/DesktopNav.tsx
- frontend/src/citizen-frontend/header/Header.tsx
- frontend/src/citizen-frontend/header/MobileNav.tsx
- frontend/src/e2e-test/pages/citizen/citizen-header.ts
- frontend/src/e2e-test/pages/citizen/citizen-pedagogical-documents.ts
- frontend/src/e2e-test/pages/employee/vasu/vasu.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-vasu.spec.ts
- frontend/src/lib-common/generated/api-types/shared.ts
- frontend/src/lib-components/atoms/RoundIcon.tsx
- frontend/src/lib-components/layout/Container.tsx
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/CitizenFeatures.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuControllerCitizen.kt
- Show total number of different unread documents on citizen front page
- Show number of unread vasu documents on citizen vasu listing heading
- It was agreed that the vasu unread state is the same as the given-permission-to-share -state, so that is used
> Vasu document read -support

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
Set the invoice maximum surplus day increase to maximum monthly fee before service need multiplier minus the child's monthly fee. Ensures that the invoice maximum is the price of a maximum service need.
> Maximum surplus days invoice increase

- service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentsIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AttachmentAccessControlTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
- service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImage.kt
- service/src/main/kotlin/fi/espoo/evaka/s3/ContentTypeUtils.kt
The `video/*` and `audio/*` patterns weren't used correctly when checking the file extension. While at it, refactor the checking code to be simpler.
> Fix file extension check for video and audio files

- apigw/src/enduser/routes.ts
- frontend/src/citizen-frontend/attachments.ts
- frontend/src/e2e-test/pages/citizen/citizen-applications.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts
- frontend/src/e2e-test/utils/page.ts
- frontend/src/employee-frontend/api/attachments.ts
- frontend/src/lib-components/employee/messages/MessageEditor.tsx
- frontend/src/lib-components/molecules/FileDownloadButton.tsx
- frontend/src/lib-components/molecules/FileUpload.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
Serve all uploaded attachments inline. Must test this in non-local environment for nginx not being configured in our compose stack.
> EVAKA-FIX serve attachments inline

- service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsBatchRefreshService.kt
- service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyService.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/service/VTJBatchRefreshService.kt
Instead of having two conflicting ways to automatically add children to families, improve the original one by adding children born within 3 months from their date of birth.
> Improve adding newly born children to families

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
- Remove IgnoreAbsences invoice login which should now have no use
- Do not add contract surplus day increases from absences with type `FREE_ABSENCE`
> EVAKA-4562 Tampere august invoicing fixes

- frontend/src/citizen-frontend/child-documents/vasu/components/CheckboxQuestion.tsx
- frontend/src/citizen-frontend/child-documents/vasu/components/FollowupQuestion.tsx
- frontend/src/citizen-frontend/child-documents/vasu/components/RadioGroupQuestion.tsx
- frontend/src/citizen-frontend/child-documents/vasu/sections/CitizenDynamicSections.tsx
- frontend/src/citizen-frontend/child-documents/vasu/vasu-content.ts
- frontend/src/e2e-test/pages/employee/vasu/pageSections.ts
- frontend/src/e2e-test/pages/employee/vasu/vasu.ts
- frontend/src/e2e-test/specs/5_employee/vasu.spec.ts
- frontend/src/employee-frontend/components/vasu/components/CheckboxQuestion.tsx
- frontend/src/employee-frontend/components/vasu/components/FollowupQuestion.tsx
- frontend/src/employee-frontend/components/vasu/components/RadioGroupQuestion.tsx
- frontend/src/employee-frontend/components/vasu/components/RadioGroupQuestionOption.tsx
- frontend/src/employee-frontend/components/vasu/sections/DynamicSections.tsx
- frontend/src/employee-frontend/components/vasu/templates/CreateParagraphModal.tsx
- frontend/src/employee-frontend/components/vasu/templates/CreateQuestionModal.tsx
- frontend/src/employee-frontend/components/vasu/templates/VasuTemplateEditor.tsx
- frontend/src/employee-frontend/components/vasu/use-vasu.ts
- frontend/src/employee-frontend/components/vasu/vasu-content.ts
- frontend/src/lib-common/api-types/vasu.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.ts
- service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- adds a new "label" field for checkbox questions to allow a separate question line and checkbox label
- adds question identifiers and dependencies to show certain questions only when other questions are filled in/selected
- adds an optionally enabled field next to radio buttons for specifying a date range
- adds option to continue numbering from previous question in a follow-up question
- new section in the default vasu for special support
_Pending Swedish translations._
> EVAKA-4469 Add special support section to vasu

- frontend/src/lib-components/atoms/buttons/AsyncButton.tsx
A promise may be rejected with an undefined error, and we have plenty of `Cannot use 'in' operator to search for 'message' in undefined` errors in Sentry getting thrown from this code.
> Don't assume error is always present

- frontend/src/citizen-frontend/AccessibilityStatement.tsx
- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/LoginPage.tsx
- frontend/src/citizen-frontend/applications/ApplicationCreation.tsx
- frontend/src/citizen-frontend/applications/Applications.tsx
- frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx
- frontend/src/citizen-frontend/applications/read-view/ApplicationReadViewContents.tsx
- frontend/src/citizen-frontend/applying/ApplyingRouter.tsx
- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/child-documents/ChildDocuments.tsx
- frontend/src/citizen-frontend/child-documents/PedagogicalDocuments.tsx
- frontend/src/citizen-frontend/child-documents/vasu/VasuPage.tsx
- frontend/src/citizen-frontend/children/ChildPage.tsx
- frontend/src/citizen-frontend/children/ChildrenPage.tsx
- frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponseList.tsx
- frontend/src/citizen-frontend/decisions/decisions-page/Decisions.tsx
- frontend/src/citizen-frontend/income-statements/ChildIncomeStatementEditor.tsx
- frontend/src/citizen-frontend/income-statements/ChildIncomeStatementView.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
- frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
- frontend/src/citizen-frontend/map/MapPage.tsx
- frontend/src/citizen-frontend/messages/MessagesPage.tsx
- frontend/src/citizen-frontend/personal-details/PersonalDetails.tsx
- frontend/src/lib-components/atoms/Main.tsx
- frontend/src/lib-components/atoms/buttons/SkipToContent.tsx
- frontend/src/lib-components/molecules/Tabs.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Adds `<main>` sections to all citizen pages; the `<main>` cannot be wrapped around the main router as footers, subnavigations, and return links are added within route components – the `<main>` should only contain the main content. With these, users can jump into the main content using the added links (active only when selected e.g. by using tab) and on the applications page there is a link to jump to the subnav as well.
> Add skip to content accessibility links

- service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
- service/src/main/resources/db/migration/R__koski_views.sql
In these two cases, Koski only accepts a single date range, but our data model allows any number of date ranges to exist. Instead of taking a blind min/max of the ranges, join them using Timeline and pick the largest one.
**This change invalidates Koski caches and causes a large amount of async jobs**
> Send more realistic assistance action date ranges when Koski accepts just one

- frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/lib-common/reservations.ts
- frontend/src/lib-components/molecules/date-picker/DatePicker.tsx
- frontend/src/lib-components/molecules/date-picker/DateRangePicker.tsx
Fixes issues in the reservation modal where native date pickers do not open the correct initial month for the end date because the min date was not updated accordingly with the start date. Additionally, the absence modal lacked similar checks too that caused issues down the line when creating date ranges.
> Fix reservation and absence modal min/max date

- frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
If an employee is first supervisor, then staff, she has a deactivated message account. Deactivated message accounts should not be used as recipients. With this fix citizen is only able to send messages to groups, not staff who worked previously as the unit's supervisor
> Only consider active message accounts as recipients

- evaka-bom/build.gradle.kts
- service/owasp-suppressions.xml
-Suppress CVE-2022-33915 for now
-bump spring boot version
> Bump spring boot to 2.7.1

- frontend/src/employee-frontend/utils/use-autosave.ts
If a save debounce happens while another save is happening, the first save will change the status to clean on completion, which is not correct as there is dirty data waiting to be saved from the second save. The language selection test happened to be timed in such a way that often the autosave status would be clean when it hadn't actually saved the language, because the first save debounce that happens on page load changed the status to clean when the language wasn't updated after all.
> Fix race condition in useAutosave w/ saving-dirty

- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceUpkeepIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Previously attendance upkeep would end attendances at midnight for every child that had a backup placement into another unit.
> Fix attendance upkeep not taking backup care into account

- frontend/src/employee-frontend/components/unit/TabAttendances.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/Occupancy.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancySingleDay.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancyTest.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancy.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/JdbiExtensions.kt
- service/src/main/kotlin/fi/espoo/evaka/units/UnitsView.kt
Fixes realtime occupancy graph not showing ongoing attendances that started yesterday. Also improve the graph's maximum time range for shift care units.
> Improve realtime occupancy graph for shift care units

- frontend/src/e2e-test/pages/employee/assistance-need-decision/assistance-need-decision-edit-page.ts
- frontend/src/e2e-test/specs/5_employee/assistance-need-decision.spec.ts
- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionEditPage.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionPage.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
- frontend/src/lib-common/generated/api-types/assistanceneed.ts
- frontend/src/lib-components/atoms/dropdowns/Combobox.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt
The assistance need decisions decision-maker report does not display rows that do not have a unit associated with the decision due to a JOIN in the query; as such, the unit is a required field. There are other required fields (from a non-technical aspect) as well, but those will be decided on later. Moreover, support for the validation field info was only added to the unit dropdown and some other easy cases; when other required fields are decided on the rest of the field infos can be implemented in the more complex cases.
> EVAKA-4469 Require unit field for assistance need decisions

- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/applying/ApplyingRouter.tsx
- frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
- frontend/src/citizen-frontend/calendar/CalendarListView.tsx
- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/HolidayPeriodCta.tsx
- frontend/src/citizen-frontend/calendar/WeekElem.tsx
- frontend/src/citizen-frontend/header/DesktopNav.tsx
- frontend/src/citizen-frontend/header/EvakaLogo.tsx
- frontend/src/citizen-frontend/header/MobileNav.tsx
- frontend/src/citizen-frontend/index.css
- frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
- frontend/src/employee-frontend/App.tsx
- frontend/src/employee-mobile-frontend/App.tsx
- frontend/src/lib-components/molecules/ReloadNotification.tsx
- frontend/src/lib-components/molecules/Toast.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- Fix main header nav links shifting when hovering due to font-weight changes, and make the notification count circle bold-like as well when needed
- Remove calculations for the page height and 100vh from body
- Remove footer from the applying map page (it went over the map)
- Fix scrolling to the current date in the calendar
- Modify toasts to depend on the parent component for their position
- Fix holiday period CTA toast on desktop to be relative to the calendar subheader
- Fix holiday period CTA toast on mobile to be below the main header if visible
- Make the reload toast be below the main header
- Add some missing aria labels
> Miscellanious UI tweaks

- service/owasp-suppressions.xml
Does not affect evaka; misidentification due to a too-eager CPE. See: https://github.com/jeremylong/DependencyCheck/issues/4671, https://github.com/advisories/GHSA-g7h7-rg53-h2g9, https://github.com/github/securitylab/issues/669#issuecomment-1186015526
> Suppress CVE-2022-31569

- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/DailyRepetitionTimeInputGrid.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/IrregularRepetitionTimeInputGrid.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/WeeklyRepetitionTimeInputGrid.tsx
- frontend/src/citizen-frontend/calendar/reservation-modal/utils.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/ReservationModalSingleChild.tsx
- frontend/src/lib-common/generated/api-types/reservations.ts
- frontend/src/lib-common/reservations.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenControllerTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
- Show days off in the reservation modal, if all selected children have days off during the selected days
- Show days off in the calendar view
- Show days off in the day view
- Fixed bug where unrelated placements ended up in the daily reservation data; if a child had multiple placements, the child's daily data would be copied as many times as there are placements
- Cause: placement start and end times were not checked to be relevant to the inspected date
> EVAKA-4287 daily service time citizen calendar

- .github/workflows/build.yml
- trigger build on pull request activity
- limit push events to master branch (`push` without branch restriction causes double builds in pull requests, because both `push` and `pull_reques` events are triggered)
- limiting push to main branch means CI no longer runs if a branch is pushed but a pull request is not made. This can be improved later by e.g. using a known prefix for branches which should be built
> Trigger build on pull request activity

- frontend/src/citizen-frontend/messages/MessagesPage.tsx
The message editor was being hidden using the internal state instead of the state in the search params, thus causing the new message button not working on subsequent uses.
> Fix message editor visibility toggling

- frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts
- frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
- frontend/src/employee-frontend/api/staff-attendance.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/attendance-elements.tsx
- frontend/src/lib-common/generated/api-types/attendance.ts
- frontend/src/lib-components/atoms/buttons/AsyncIconButton.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
- service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt
- Add browsing of days in the staff attendance details modal
- Add summary of the current day in the staff attendance details modal
- Show a warning if there is a gap between attendances  in the staff attendance details modal
- Fix details modal button to only be visible on days with other attendances
- Add a sum row of staff to the table (TBD: only excluding training and other work (current implementation) or only including present)
> EVAKA-4407 employee staff attendance desktop editor

- frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
When there is a future attendance, it must be that no open attendances may be made. When switching to the previous week after creating an open attendance, the future attendance flag would update (to true) before the actual form, causing the form validation hook to remove the newly-created open attendance as it seemed invalid (because it is an open attendance and there is a future attendance – even though there isn't).
> Fix attendance calendar navigation causing deletion

- frontend/src/employee-frontend/components/unit/TabAttendances.tsx
- frontend/src/lib-common/utils/useSyncQueryParams.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
The employee attendance calendar did not save the current date in the URL's state, thus losing the week state sometimes when navigating between pages. Also, the query param sync hook did not always work.
> Fix query param sync and add date to calendar params

- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
The phone number fields were never enabled for preparators mistakenly.
> EVAKA-4469 Enable phone fields for preparators

- frontend/src/citizen-frontend/messages/ThreadListItem.tsx
- frontend/src/lib-components/molecules/ThreadListItem.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
Buttons shouldn't have buttons inside them (in this case, a download button inside the message button), so the parent button was changed to a tabbable div and a screen-reader-only link inside the div was made to preserve the accessibility benefits the parent button gave.
> Fix button inside button semantics in messages

- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx
- Fix an exception being thrown if `staffData` is a zero-length array
- Round occupancy chart tooltip numbers to max 1 decimal
> Add unit occupancy chart tooltip rounding

- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/children/AssistanceNeedDecisionPage.tsx
- frontend/src/citizen-frontend/children/AssistanceNeedSection.tsx
- frontend/src/citizen-frontend/children/ChildPage.tsx
- frontend/src/citizen-frontend/children/ChildrenPage.tsx
- frontend/src/citizen-frontend/children/api.ts
- frontend/src/citizen-frontend/children/state.tsx
- frontend/src/citizen-frontend/header/DesktopNav.tsx
- frontend/src/citizen-frontend/header/Header.tsx
- frontend/src/citizen-frontend/header/MobileNav.tsx
- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/dev-api/types.ts
- frontend/src/e2e-test/pages/citizen/citizen-children.ts
- frontend/src/e2e-test/pages/citizen/citizen-header.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts
- frontend/src/lib-common/generated/api-types/assistanceneed.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AssistanceNeedDecisionAccessControlTest.kt
- service/src/main/kotlin/fi/espoo/evaka/Audit.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecision.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionCitizenController.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
- service/src/main/resources/db/migration/V252__assistance_need_decision_read.sql
- service/src/main/resources/migrations.txt
- Adds an unread assistance need decision count indicator to the header/navigation, the list of children page, the child page (collapsible's header), and in the table itself
- Marks decisions read when they are opened
> EVAKA-4469 citizen unread assistance need decisions

- apigw/src/enduser/routes/auth-status.ts
- frontend/src/citizen-frontend/RequireAuth.tsx
- frontend/src/citizen-frontend/applications/ApplicationCreation.tsx
- frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx
- frontend/src/citizen-frontend/applications/read-view/ApplicationReadView.tsx
- frontend/src/citizen-frontend/applying/ApplyingRouter.tsx
- frontend/src/citizen-frontend/auth/api.ts
- frontend/src/citizen-frontend/auth/state.tsx
- frontend/src/citizen-frontend/header/DesktopNav.tsx
- frontend/src/citizen-frontend/header/MobileNav.tsx
- frontend/src/citizen-frontend/header/const.ts
- frontend/src/citizen-frontend/holiday-periods/state.tsx
- frontend/src/citizen-frontend/personal-details/PersonalDetails.tsx
- frontend/src/lib-common/api-types/vtjclient.ts
- frontend/src/lib-common/generated/api-types/shared.ts
- frontend/src/lib-common/generated/api-types/vtjclient.ts
- service/src/main/kotlin/fi/espoo/evaka/vtjclient/controllers/VtjController.kt
The auth status endpoint always returned social security numbers and children even when weakly authenticated.
> Remove SSNs and children for weak auth citizens

- frontend/src/citizen-frontend/children/AssistanceNeedSection.tsx
- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/dev-api/types.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts
- frontend/src/employee-frontend/components/child-information/AssistanceNeedDecisionSection.tsx
- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
- frontend/src/lib-common/generated/api-types/assistanceneed.ts
- frontend/src/lib-components/assistance-need-decision/AssistanceNeedDecisionReadOnly.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AssistanceNeedDecisionsReportTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AssistanceNeedDecisionAccessControlTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecision.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
- service/src/main/resources/WEB-INF/templates/assistance-need/decision.html
- service/src/main/resources/db/migration/V254__multiple_assistance_need_levels.sql
- service/src/main/resources/migrations.txt
Instead of having just one assistance level for a decision, the decision should have the possibility of having more than one level (radio -> checkbox group).
> EVAKA-4469 Modify assistance need decisions to have multiple assistance levels

- frontend/src/citizen-frontend/child-documents/CitizenVasuAndLeops.tsx
- frontend/src/citizen-frontend/child-documents/vasu/VasuPage.tsx
- frontend/src/employee-frontend/components/vasu/components/MultiSelectQuestion.tsx
- frontend/src/lib-common/generated/api-types/vasu.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
- service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
- Make disclaimer about document sharing to other parties more prominent by adding it to the page of list of documents, and by creating a separate paragraph for the info box in the document itself
- Fix sticky footer to be the full width of the page
- Make child support level to be a multi select with max 2 selections instead of a radio (for LEOPS)
> Update LEOPS and vasu

- apigw/src/enduser/app.ts
- apigw/src/internal/app.ts
- apigw/src/shared/middleware/cache-control.ts
Using a regex causes Datadog to include it in all paths, which makes it more difficult to understand metrics. Use string.startsWith instead.
> Replace regex with simple middleware

- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt
Suomi.fi deduplicates messages based on IDs, so only the first guardian is being delivered the message.
> EVAKA-4469 Make assistance need decision message IDs unique

- service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Assistance need decision preparer/decision-maker dropdowns require access to the global employee list. Apparently the list of employees is not very secret internally, as one could use other organisational tools to access names and email addresses of the employees.
> EVAKA-4469 Allow reading of employees for special ed teachers

- frontend/src/e2e-test/specs/5_employee/assistance-need-decision.spec.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt
- service/src/main/resources/WEB-INF/templates/assistance-need/decision.properties
- service/src/main/resources/WEB-INF/templates/assistance-need/decision_sv.properties
- The official term does not contain "need", i.e., "tuen päätös" not "tuen tarpeen päätös"
- The email message and title shouldn't contain information that can tell the reader it is a decision regarding assistance
> EVAKA-4469 Update assistance need decision texts

- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/FixtureBuilder.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancyTest.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancy.kt
Leave out staff in training or other work from occupancy calculations since the staff is not actually present in a group. Also fix staff attendance total hours formatting.
> EVAKA-4407 realtime staff attendance type in occupancy calculation

- frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
The unit groups were sometimes inserted out-of-order (i.e., sometimes "daycareGroup2" was before "daycareGroup" in the table), which caused the first (and as such selected by default) group to be the "second group" in the employee mobile; one test assumed the first group is always the first group in the database, but when this didn't happen the wrong group was selected (by default) and no messages were displayed for this unrelated group.
> Fix flaky mobile messages e2e test

- frontend/src/employee-frontend/components/UnitPage.tsx
- frontend/src/lib-common/utils/useSyncQueryParams.ts
The main unit page reset the URL state, causing the calendar state to be reset on page load.
> Fix unit page resetting URL state

- frontend/src/lib-common/generated/api-types/messaging.ts
- frontend/src/lib-components/employee/messages/MessageEditor.tsx
- frontend/src/lib-components/employee/messages/types.ts
- frontend/src/lib-components/employee/messages/useDraft.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/DraftQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/DraftContent.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/DraftQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
This is a workaround for some E2E test flakiness caused by draft updates happening *after* a draft has been deleted.
> Use update instead of upsert for message drafts

- frontend/src/e2e-test/pages/employee/units/unit-diary-page.ts
- frontend/src/e2e-test/specs/5_employee/absence.spec.ts
- frontend/src/employee-frontend/components/absences/AbsenceModal.tsx
- frontend/src/employee-frontend/components/absences/AbsenceTable.tsx
- frontend/src/employee-frontend/components/absences/Absences.tsx
If every selected cell in the absence table only has one possible absence category, hide the category selection from the absence modal and use the only possible value.
> Do not show absence category selection if only one option is possible

- frontend/src/e2e-test/specs/0_citizen/citizen-child-income-statement.spec.ts
When there are no rows, the table is replaced with a warning – thus, no table element exists when there are 0 rows.
> Fix child income statement flaky e2e

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
- Make effect of unplanned absences in contract days invoicing configurable
- Add an optional maximum to contract days surpluses after which the invoice defaults to monthly maximum
- Add option to split contract day invoices by the number of operational days instead of contract days
> EVAKA-4557 Oulu invoicing changes

- frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
Fixes E2E test flakiness caused by asserting messages on the wrong group page
> Flaky E2E fix: make sure the correct group is selected

- frontend/src/lib-common/api.ts
There are many scenarios where we have an error and a response, but the response data is undefined. For some reason this happens frequently after the recent axios upgrade
> Handle undefined data gracefully

- frontend/src/employee-mobile-frontend/components/staff-attendance/StaffMarkArrivedPage.tsx
- frontend/src/employee-mobile-frontend/components/staff-attendance/StaffMarkDepartedPage.tsx
- frontend/src/lib-common/generated/api-types/attendance.ts
- frontend/src/lib-components/atoms/buttons/AsyncButton.tsx
- frontend/src/lib-customizations/espoo/employee-mobile-frontend/assets/i18n/fi.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
- service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
- **Remove debugging delay** that was accidentally merged, which delayed all AsyncButton successes by 1 second
- Prevent another request from being sent when the success state is visible, as it is possible the onSuccess handler will prevent the user from redoing the same action (e.g., via redirection)
- Show a warning for future staff attendances that will prevent the staff member from logging in
> Fix AsyncButton double-submissions

- apigw/src/enduser/app.ts
- apigw/src/internal/app.ts
- apigw/src/shared/routes/auth/saml/index.ts
This should solve unexpected occurences of `PayloadTooLargeError`, as well as enhance performance of proxied requests a bit.
> Only parse request body when it's actually needed

- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
The test `Decision is not sent automatically to the other guardian if the first guardian has restricted details enabled` used to be flaky because evaka-service would be running a family initialization async job at the same time with a guardian VTJ-query causing the one of the processes to fail because of a deadlock. I added a `runAllAsyncJobs` call to the end of the application actions endpoint in dev api to make sure that all the async jobs have been run before doing the next step in e2e test data initialization. But it turned out that `runAllAsyncJobs` was not reliable and it would sometimes return even though there were some async jobs still waiting to be run. I've now fixed it, but I'm not sure if my fix is bulletproof. There haven't been any issues with `runAllAsyncJobs` in ~100 …
> Fix flaky application decision e2e test

- apigw/src/shared/__tests__/saml-slo.ts
- apigw/src/shared/test/gateway-tester.ts
Previously JSON worked fine, since we had a global JSON parsing middleware installed. Now that the global middleware no longer exists, we *could* install the same middleware to the SAML endpoints, but in real SAML flows the data is not posted as JSON but in urlencoded format.
So, post data in tests using that format since we don't even need to support JSON.
> Fix apigw test regression: post SAML data in tests using urlencoded format

- frontend/src/e2e-test/pages/citizen/citizen-messages.ts
Clicking the button does not mean the reply has already been sent, and in the tests we generally don't refresh in a loop until we see data. This leads to race conditions where we might load the inbox on the receiving side before the server has actually processed the click.
> Fix flakiness in E2E messaging tests: make sure reply has actually been sent

- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/ChartTooltip.tsx
- frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx
* Fix the realtime occupancy graph's tooltip crashing the page when there's no data for the day by checking that a datapoint exists in the tooltip handler.
* Fix the tooltip causing recurring state update loops every time it's rendered.
* Extend the graph if children are currently present and it's past the graph's normal upper limit.
* Hide the graph on future dates since there is no data for those dates yet anyway.
> Fix realtime occupancy graph tooltip

- frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts
- frontend/src/e2e-test/specs/5_employee/assistance-need-decision.spec.ts
- frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
- frontend/src/lib-common/generated/api-types/assistanceneed.ts
- frontend/src/lib-components/assistance-need-decision/AssistanceNeedDecisionReadOnly.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/employee/assets/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecision.kt
- service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
- service/src/main/resources/WEB-INF/templates/assistance-need/decision.html
- service/src/main/resources/WEB-INF/templates/assistance-need/decision.properties
- service/src/main/resources/WEB-INF/templates/assistance-need/decision_sv.properties
- Remove emails from preparators
- Reorder assistance levels
- "Päätös tuesta" -> "Päätös tuesta varhaiskasvatuksessa"
- Add new jurisdiction text
- Update law clauses
> EVAKA-4590 Update assistance need decision

- service/src/main/resources/db/migration/R__message_account_access_view.sql
Secretary should be able send to every daycare group without having
access to them, but shouldn't see other staff messages like unit
supervisor. This commit breaks former and fixes latter.
We should discuss how to implement this later..
> Remove messages access from early childhood education secretary

- service/src/integrationTest/kotlin/fi/espoo/evaka/s3/DocumentServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
- service/src/main/kotlin/fi/espoo/evaka/s3/DocumentService.kt
Spring by default adds a `Content-Disposition: inline; filename="f.txt"` header if it's missing which breaks at least PDF files on some browsers.
> Use content-disposition header with inline attachments

- frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx
Default was unix timestamp which Excel didn't quite understand.
> Fix attendance reservation report time format in csv

- service/src/integrationTest/kotlin/fi/espoo/evaka/s3/DocumentServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImageController.kt
- service/src/main/kotlin/fi/espoo/evaka/s3/DocumentService.kt
Add the attachment's `Content-Disposition` header to evaka-service response since the Spring's default `inline; filename=f.txt` is still being added to the response headers. Tested that this works in staging this time.
> Add content-disposition header to service response

- frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
- service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/config/EnvConfig.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlCitizen.kt
- Calendar UI used to open on the day that first placement starts. Add a configurable number of days when the calendar opens prior to the first placement
> Add configurable amount of days when the citizen calendar opens

- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/SystemControllerTest.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
When employee gets a new contract or comes back to work
(or whatever) it gets a new external id in SSO for some reason but
employee number (should) stays the same.
Bad thing about this is (unline external id which seems uuid and
probably generated by system) employee number is set by human, so
there is possibility for human error to set same or wrong employee
number to employee.
> Fix employee login when external id changes

- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
When English was selected, the calendar page would overflow on certain window sizes because the word "attendance" required too much space.
> Fix overflowing citizen calendar

- service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
- We already handle shutdown gracefully if there are very few or no jobs. However, if a lot of pending jobs exist in the database, `runPendingJobs` kept claiming new ones even if we were trying to shut down. Detect this scenario and stop claiming jobs so the scheduled task can shut down in time
- Log an error if we ended up shutting down even if some job didn't terminate correctly
> Improve async job runner behaviour when shutting down (e.g. SIGTERM from Docker)

- frontend/src/employee-mobile-frontend/components/staff-attendance/MarkExternalStaffMemberArrivalPage.tsx
- service/src/main/resources/db/migration/V266__trim_external_staff_names.sql
- service/src/main/resources/migrations.txt
In case of substitute workers coming in, make sure to trim away any
whitespace from their names to avoid duplicates and hard to sort/find
persons.
> Trim external emplyee's names

- service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
The comment says `order by area ...` but this was not true because `a` is application and `ca` is area.
> Fix ordering in income statements query

- service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUnitIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
When unit was accidentally marked a closing date which was sent to varda, then the date was removed, it was not sent to varda because null value fields were dropped from the request payload. Allow sending null paattymis_pvm.
> Send null paattymis_pvm to varda

- frontend/package.json
- frontend/src/lib-components/atoms/buttons/IconButton.tsx
- frontend/yarn.lock
React-aria's `useButton` creates all kinds of empty interaction handlers even when no `onClick` or `onPress` is passed, which broke all uses of icon button where its parent element has the actual `onClick` handler. Also its benefits overall are not big enough to justify using it.
> Fix icon button event propagation

- frontend/src/lib-common/generated/api-types/occupancy.ts
- service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancyTest.kt
- service/src/main/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancy.kt
Overnight attendances are marked as ending on 23:59 on day 1 and
starting 00:00 on day 2, which caused the occupancy graph to drop down
to zero in the minute between 23:59 and 00:00.
This change removes the zero data point between 23:59 and 00:00, and
thus it is no longer rendered in the graph.
> EVAKA-4596 Remove gaps in occupancy graph for overnight attendances

- frontend/src/employee-frontend/components/vasu/sections/DynamicSections.tsx
Find questions using section and question names instead of indexes as finding by index broke down completely when sections were dynamically hidden by previous answers.
> Find questions using section and question name instead of indexes

- frontend/src/citizen-frontend/calendar/CalendarPage.tsx
- frontend/src/citizen-frontend/calendar/DayView.tsx
- frontend/src/citizen-frontend/calendar/ReservationModal.tsx
- frontend/src/citizen-frontend/calendar/api.ts
- frontend/src/citizen-frontend/calendar/calendar-elements.tsx
- frontend/src/citizen-frontend/calendar/utils.ts
- frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
- frontend/src/employee-frontend/components/unit/unit-reservations/ReservationModalSingleChild.tsx
- frontend/src/lib-common/generated/api-types/reservations.ts
- frontend/src/lib-common/reservations.ts
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/en.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/fi.tsx
- frontend/src/lib-customizations/espoo/citizen/assets/i18n/sv.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationCitizenControllerTest.kt
- service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
Children who had a placement, which ended and are waiting for the next placement to start were wrongly shown in the calendar. This change allows gaps in placements to be rendered correctly.
Also added an error message if the citizen tries to store a reservation that overlaps with non reservable days.
> Don't show children in between placements as reservable in the citizen calendar

- frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/FollowupQuestion.tsx
- frontend/src/e2e-test/pages/employee/vasu/vasu.ts
- frontend/src/e2e-test/specs/5_employee/vasu.spec.ts
- frontend/src/employee-frontend/components/vasu/components/FollowupQuestion.tsx
Before this change, an empty followup entry was created automatically to the end of the list. This change adds a button you have to click to add a new entry:
Also, followup entries with an empty text are not rendered anymore.
> Vasu followup enhancements

- frontend/src/e2e-test/dev-api/fixtures.ts
- frontend/src/e2e-test/pages/employee/child-information.ts
- frontend/src/e2e-test/specs/5_employee/backup-care.spec.ts
- frontend/src/e2e-test/specs/5_employee/child-information.spec.ts
- frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
- frontend/src/e2e-test/utils/page.ts
- frontend/src/employee-frontend/components/child-information/BackupCare.tsx
- frontend/src/employee-frontend/components/child-information/Placements.tsx
- frontend/src/employee-frontend/components/child-information/backup-care/BackupCareForm.tsx
- frontend/src/employee-frontend/components/child-information/backup-care/BackupCareRow.tsx
- frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
- frontend/src/employee-frontend/components/common/Toolbar.tsx
- frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
- frontend/src/employee-frontend/state/child.tsx
- frontend/src/lib-common/finite-date-range.ts
- frontend/src/lib-common/utils/useRestApi.ts
- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
- service/src/integrationTest/kotlin/fi/espoo/evaka/backupcare/BackupCareIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
- service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareController.kt
- service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
- Added database trigger to enforce that backup cares must be during a placement
- Triggers both ways: when placements are modified/deleted, or when backup cares are modified/added
- Added automatic adjusting of backup care validity periods when placements are modified/deleted
- Added UI elements to warn about automatic adjusting of backup care periods whenever relevant
> EVAKA-4574 Require backup care to be during a placement

- frontend/src/lib-customizations/espoo/employee/assets/i18n/fi.tsx
- The vasu email notification seems to be missing functionality. Remove related info text until the functionality really exists
> Remove wrong info text for now

- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
`lower(somerange)` can't use a gist index
> Use index-compatible range operator in condition

- frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
Some employees have a really limited height screens on which the event calendar participant selection list does not fit. It is also difficult to scroll without a roll button mouse. This change gives more space for the list to make so much room that everything that needs to fit on screen hopefully fits (needs to be tested by the employees to get confirmation)
> Move participant selection widget higher to give more space for list

- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
When message is sent to multiple recipients, a message_thread is created to sender. The sent_at timestamp is part of the identity of the thread, so it must stay the same for each created message in order to avoid creating a thread per recipient
> As sent_at is part of message thread identity ensure it stays the same

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueriesTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionSearchTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/db/JdbiExtensions.kt
- service/src/main/resources/db/migration/V270__fee_decision_sum_cache.sql
- service/src/main/resources/migrations.txt
- the whole fee decision, including its `fee_decision_child` rows, is always upserted as one big unit, so this column should always be up to date since we update it during this upsert operation
- the new sum column is only used in the search query where it provides the greatest improvement
- the old extra sum calculation join in the search query resulted in a full table scan of `fee_decision` + `fee_decision_child` tables
- also includes new integration tests for *almost* all fee decision search parameters / sort orders
> Store fee decision total fee in a column

- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
- service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfService.kt
- service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt
- service/src/main/kotlin/fi/espoo/evaka/shared/message/MessageProvider.kt
If financial decision recipient has restricted info enabled, send the message via suomi.fi. If the recipient has the sfi e-channel enabled he will receive the message immediately. If instead the paper channel is enabled, the decision is sent to financial handers who will then manually send it to the proper address
> Send financial decision sfi messages to restricted info recipient

- frontend/src/employee-frontend/components/employee/EmployeePreferredFirstNamePage.tsx
- If user selected the first name from the preferred name list without any other interactions with the selection widget a null value was sent
- After sending the selected value the button was not initially disabled
> Initialize preferred name selection correctly

- frontend/src/employee-mobile-frontend/components/attendances/child-info/ImageEditor.tsx
If the edited image had an unfortunate aspect ratio and did not fit the screen, these things were not visible. It's possible to scroll the page, but it's unintuitive.
Before:
After:
> Make ImageEditor buttons+disclaimer sticky

- frontend/src/e2e-test/pages/employee/units/unit-attendances-page.ts
- frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
- frontend/src/employee-frontend/components/unit/TabCalendar.tsx
A previous change broke the navigation and caused the user to only be able to navigate one week at a time even when in the monthly view. Now fixed and will navigate one whole month in the month view and one week at a time in the week view.
> Fix navigation between months in the unit monthly view

- frontend/src/citizen-frontend/AccessibilityStatement.tsx
- frontend/src/citizen-frontend/App.tsx
- frontend/src/citizen-frontend/ScrollToTop.tsx
- frontend/src/citizen-frontend/children/ChildPage.tsx
- frontend/src/citizen-frontend/map/MapPage.tsx
- frontend/src/citizen-frontend/map/MapView.tsx
- frontend/src/citizen-frontend/messages/ThreadView.tsx
In citizen frontend scroll every page to the top on navigation. Navigating back behaves similarly because there's no simple way to make it work like in a traditional web page.
Also:
- Fix messages reply button focus outline
- Remove back button in child page
> Citizen scroll page to top on navigation

- service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
- service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
The query would sometimes break when backup placements would split the original placement in multiple parts because the group placement join had no check that it overlaps with the computed placements resulting in the intersection `ce.period * daterange(dgp.start_date, dgp.end_date, '[]') * cp.period` being empty. Also joins `group_placement` only if the `child_placement` is not a backup placement.
> Fix citizen calendar events query breaking sometimes

- frontend/src/employee-frontend/components/unit/unit-reservations/ChildReservationsTable.tsx
The `ChildReservationsTable` component (indirectly) called `reloadReservations` on mount. This caused useless database load, because the endpoint in question does heavy computations.
Fix by resetting component state properly.
> HOTFIX: Avoid fetching data twice on component mount
